docs/source/optional_plugins/varianter_yaml_to_mux.rst
optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py
selftests/.data/mux-selftest-advanced.yaml
selftests/unit/test_mux.py

This PR changes the way we parse the yaml file. Instead of treating all mappings as tree-node-structure it first attempts to create ordered dicts instead and only when advanced features (like our tags) are used or when the potential node is connected to root, the content is conversed into a tree. This way dicts inside another object, or explicitly defined dicts stay as dicts and will be available (almost) unmodified in test params.
The almost stands for the essential changes that are needed due to yaml parser nature, where we parse the objects from inside out, therefor we can't tell in advanced whether they are dicts or nodes and for nodes we require the correct order they appear in (`collection.OrderedDict`) and we don't want to convert keys into arbitrary types (`on` should stay as `on` …

yaml_to_mux: Construct tree as OrderedDict [v2]

---

docs/source/GetStartedGuide.rst

The extra category for plugins looks confusing to me. This patch
slightly changes the wording and moves the links to optional plugins
directly into the PIP installation section.

docs: Move pip-related installation to one category

---

avocado/core/test.py
docs/source/ReferenceGuide.rst
docs/source/Replay.rst
docs/source/WritingTests.rst
selftests/functional/test_multiplex.py
selftests/functional/test_statuses.py
selftests/unit/test_remote.py
selftests/unit/test_test.py

This addresses the issue #2189, also according to the discussions and suggestions on https://trello.com/c/iPZihxhn/1120-serialized-test-ids-contain-the-character-invalid-in-windows.

Test-ID: change the format to make it play better with Windows filesystems

---

avocado/core/loader.py

NOT_A_TEST is a test resolution result that currently only applies to
INSTRUMENTED, PyUNITTEST and SIMPLE tests.  The message given on the
command line, though, doesn't make that completely clear because it
omits the PyUNITTEST and SIMPLE test types.
---
Changes from v1 (#2191):
* Added newly introduced PyUNITTEST to the message

Loader: be clear about the meaning of NOT_A_TEST [v2]

---

avocado/core/job.py

An Avocado job execution will log the GIT information when it's run
from a GIT repo.  But, let's make having GIT optional, so that we
don't introduce yet another depedency.
---
Changes from v1 (#2214):
* Added extra escape (`%%)` char

avocado/core/job.py: make GIT optional when getting Avocado version

---

avocado/utils/vmimage.py

Debian and Ubuntu use 'amd64' to refer to 64bits arch. Let's use 'amd64'
when the specified arch (auto-discovered or not) is 'x86_64'.

vmimage: adjust the 64bits arch on Debian/Ubuntu

---

Makefile

This shouldn't change the experience for current users, but it
makes Makefile work on environments with Python 3 only.

Makefile: keep using Python 2, but fallback to Python 3

---

avocado/core/job.py

The first commit contains only pylint fixes, while the second commit makes sure we get Avocado version from the currently executed file's location.
v1: https://github.com/avocado-framework/avocado/pull/2225
changes:
```yaml
v2: Fixed the 2 typos in the 2nd commit
```

job: Improve _get_avocado_git_version [v2]

---

MANIFEST.in

This fixes the warning "warning: no files found matching
'examples/*.yaml'" while running "make develop".

MANIFEST.in: there are no longer YAML files under examples

---

avocado/core/sysinfo.py
avocado/utils/astring.py
optional_plugins/html/avocado_result_html/__init__.py
selftests/functional/test_basic.py
selftests/functional/test_output.py
selftests/functional/test_sysinfo.py
selftests/unit/test_astring.py
selftests/unit/test_test.py

As we realized in https://github.com/avocado-framework/avocado/issues/2189 there are some windows-unfriendly characters in our generated output. This PR first fixes our selftests, then makes sure we use `astring.string_to_safe_path` in all files generated in results and the last commit improves the `astring.string_to_safe_path` to be windows friendly.
Note the `string` approach in that function is very fast, but fails on unicode strings, that's why there is a fallback to slower, but unicode-friendly implementation.
v1: https://github.com/avocado-framework/avocado/pull/2224
v2: https://github.com/avocado-framework/avocado/pull/2227
Changes:
```yaml
v2: Revert to `pkg_resources` but use the correct name this time (1st commit)
v2: Use the FS_UNSAFE_CHARS variable correctly in astring (3rd …
```

Avoid the usage of Windows-unfriendly filenames [v3]

---

avocado/core/test.py
avocado/utils/process.py
selftests/functional/test_output.py

Avocado process module has a routine to drain the std* buffer with a
per-line basis loop. This loop makes the new-line character to be
dropped.
On the other hand, the Python logging system is hard-coded to add a new-line
character at the end of the msg string.
The problem takes place when `process` writes a line which originally
had new-line character at the end but the logging system still adds the
new-line character to that line.
In this patch:
- avocado.utils.process to include the new-line character in the lines
that originally had one.
- avocado.core.test to use for raw outputs a custom logging FileHandler
that does not add a new-line character at the end of each line.
Verified with (checking `.../test-results/1-.../[stdout|stderr|output]`):
$ avocado run --external-runner …

log the raw output on stdout/stderr

---

avocado/utils/network.py
selftests/unit/test_utils_network.py

And add accompanying tests that didn't exist in the origin of the code
(Avocado-Virt) and that weren't added at the port time.

avocado/utils/network.py: fix for PortTracker.release_port

---

optional_plugins/runner_remote/avocado_runner_remote/__init__.py
python-avocado.spec
requirements-selftests.txt
requirements-travis.txt
selftests/unit/test_datadir.py
selftests/unit/test_distro.py
selftests/unit/test_remote.py
selftests/unit/test_test.py
selftests/unit/test_utils_partition.py
selftests/unit/test_vm.py
spell.ignore

This is a port to the mock library that is in the standard in Python 3, and it's available in Python 2, and already a requirement for Avocado.
The approach used on this port is to avoid excessive mocking, and use the real code, unless when interacting with dynamic and non-existing components (such as a remote system).
---
Changes from v3 (#2241):
* Fixed double "that" typo
* Removed mock of `fabric` in `test_remote.py`
Changes from v2 (#2232):
* Rebased and resolved conflicts
* Bumped the release number on the SPEC file and updated the ChangeLog entry
Changes from v1 (#2226):
* Dropped Job related commits from PR #2222, now merged on master
* Added a try/finally block on `test_remote.py` to ensure temp dir is removed
* Added a mock assert for `runner.remote.run` on `test_remote.py` to …

Drop flexmock requirement [v4]

---

avocado/core/parser.py

The goal of this change is to make the behavior of the Avocado command
line application as similar as possible to the behavior when running
under Python 2.  This bit is about what happens when the simplest
possible Avocado command line is run:
$ avocado
On Python 2, it prints the complete usage, along with the error
message "too few arguments".  While we could go employ extreme changes
to make the very same error message be given on Python 3, this seems
wrong.  The reason is that the message is generated by the Python 2
standard library.  The Python 3 standard library relies on "required"
arguments instead.  When settings the subcommand sub parser as a
required option, the behavior is exactly the same, minus the error
message which becomes "the following arguments are required: …

Python 3: make the subcommands sub parser a required option

---

avocado/core/data_dir.py
avocado/core/output.py
avocado/core/test.py
avocado/plugins/list.py
avocado/utils/astring.py
avocado/utils/stacktrace.py
optional_plugins/runner_remote/avocado_runner_remote/__init__.py
selftests/unit/test_astring.py

A port of `avocado.utils.astring` and related test to Python 3.
Given the nature of the subject, strings, and the big differences between Python 2 and 3 on that matter, it was impossible to not have conditionals on version on even skips on some of the unittests.
---
Changes from v1 (#2249):
* Use `range` instead of `xrange`, favoring Python 3 names

Python 3: port avocado.utils.astring [v2]

---

avocado/core/job.py
avocado/core/loader.py
avocado/core/output.py
avocado/core/parser.py
avocado/core/test.py
avocado/core/tree.py
avocado/core/varianter.py
avocado/utils/debug.py
avocado/utils/memory.py
avocado/utils/stacktrace.py
optional_plugins/html/avocado_result_html/__init__.py
optional_plugins/loader_yaml/avocado_loader_yaml/__init__.py
optional_plugins/resultsdb/avocado_resultsdb/__init__.py
optional_plugins/runner_vm/avocado_runner_vm/__init__.py
optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py
selftests/functional/test_basic.py
selftests/unit/test_mux.py

This changes uses the six compatibility equivalents for iterkeys,
iteritems and itervalues.

Python 3 port: address use of dictionary iterators

---

selftests/unit/test_jobdata.py

And switch to an more "unittest.TestCase" like approach.
Besides the style and result visibility values in itself, with a Python 3 port, this will allow us to selectively test some of the more recent versions and skip others depending on the environment we're running (Python 2 or Python 3).

jobdata selftests: split into individual test cases

---

avocado/utils/pci.py

Earlier function used to return the entire physical slot location
including port information if any. Now it returns slot information
only till adapter level, not the port level.
Signed-off-by: Venkat R B <vrbagal1@linux.vnet.ibm.com>

Removed port related information while returing location

---

avocado/utils/astring.py
selftests/unit/test_astring.py

This PR reverts some old behavior changed in https://github.com/avocado-framework/avocado/pull/2249 while it keeps the py3 compatibility.
Basically the first commit brings back the `FS_UNSAFE_CHARS` as it might be a useful variable to be exported and the second commit brings back the support to treat unicode in py2 mode as we do that in all of the remaining astring methods.

Bring back some of the `utils.astring` features

---

avocado/core/output.py
selftests/functional/test_output.py

The 4235b3299210c24f91539754312c8ad09053cf32 changed the
stdout/stderr/output logging handlers to not to add tailing '\n's, but
these are processed by LoggingFile, which is designed to remove the
'\n's and to logged them per line. As a result the unittest was
incorrectly changed as the first outputs actually add the '\n' which was
removed in the expected output.
This patch keeps the raw approach as it is necessary for the last
buffered line and instead of buffering puts all lines including the
tailing '\n' and not '\n' for the remaining last line (if it's
available). Consequently this should improve the situation where output
is being produced by stderr and stdout concurrently as no buffering of
the non-tailing-newline output is done on LoggingFile level.
Signed-off-by: Lukáš Doktor …

output: Adjust LoggingFile to work with raw output

---

avocado/core/job.py
avocado/core/jobdata_compat_36_to_52.py
avocado/core/loader.py
avocado/core/mux.py
avocado/core/output.py
avocado/core/safeloader.py
avocado/core/settings.py
avocado/core/tree.py
avocado/core/varianter.py
avocado/plugins/replay.py
avocado/utils/data_factory.py
avocado/utils/external/spark.py
avocado/utils/lv_utils.py
avocado/utils/path.py
docs/source/conf.py
examples/plugins/job-pre-post/sleep/avocado_job_sleep.py
examples/tests/gdbtest.py
examples/tests/sleeptenmin.py
examples/tests/whiteboard.py
selftests/functional/test_basic.py
selftests/functional/test_loader.py
selftests/functional/test_lv_utils.py
selftests/functional/test_utils.py
selftests/unit/test_mux.py
selftests/unit/test_test.py
selftests/unit/test_utils_stacktrace.py

This set of changes allows Avocado to list tests, besides other features.  The next batch of work (in progress) focus on actually getting the tests running.
---
Changes from v1 (#2253):
* Change commit message on "avocado/core/loader.py: simplify detection
of python files" mentioning the behavior change and and added a test
* Added similar fix to avocado/core/safeloader.py not closing file
(just like the one existing in avocado/core/loader.py) Other similar
fixes are scheduled to a future (already in progress) PR.
* Created "script" attribute on SimpleTestClassTest.setUp() and
check for its existance before removing it on tearDown()
* Replaced "tst_instance_{pass,fail}" attributes on
test_simple_test_pass_status and test_simple_test_fail_status
for a simpler "tst_instance" variable.
* …

Python 3 port: further porting work [v2]

---

docs/source/WritingTests.rst

Just a 2 notes that might improve the documentation regarding recently added `get_data`.
v1: https://github.com/avocado-framework/avocado/pull/2264
changes:
```yaml
v2: Typofix and tweak in the 2nd commit
```

docs: Two little improvements regarding `get_data` documentation [v2]

---

avocado/core/test.py
docs/source/WritingTests.rst
selftests/functional/test_output_check.py

v2:
- Add the diffs to the log (in addition to the files).
- Remove the assert message.
- Use python logging (instead of `with open()`) to achieve the items above.
- Rename the diff files from `std*_expected.diff` to `std*.diff`.
- Docs.
v1: #2258

test: check-output to record diffs [V2]

---

avocado/core/sysinfo.py
docs/source/Sysinfo.rst
etc/avocado/avocado.conf

We have the support for it every since the beginning, let's allow it's usage as users asked for it https://github.com/avocado-framework/avocado/issues/2169
v1: https://github.com/avocado-framework/avocado/pull/2254
v2: https://github.com/avocado-framework/avocado/pull/2267
Changes:
```yaml
v2: setting renamed from "collectibles_per_test" to "per_test"
v2: fixed typo in commit message
v3: Fixed cfg section in documentation
```

sysinfo: Per test collectibles [v3]

---

optional_plugins/golang/avocado_golang/__init__.py

This prevents an error when the avocado golang plugin is installed,
but "go" itself is not.
This still allows tests to be listed without "go" because:
* it is not a requirement for that
* there's value in listing tests even when your system is (still?)
not completely setup to run them
* Avocado hasn't promised symmetry between listing and guaranteeing
that tests will be able to run
* There may be situations in which we can *not* predict if tests
that we can list can be executed
---
* Improved commit message, with reasons for allowing listing
* Fixed the error message (`s/be//`)

golang: error test execution when "go" binary was not found [v2]

---

avocado/core/runner.py
avocado/core/test.py
avocado/core/varianter.py
optional_plugins/html/avocado_result_html/__init__.py
setup.py

The previous batch of Python port work allowed the Avocado test runner to list tests.  This PR enables it to actually run tests.
This was tested with all the default plugins, plus the HTML optional plugin enabled.
There are still issues with Avocado itself, and also with many of the optional plugins.  One of the most visible issues, an `avocado.utils.process` that procues a traceback and a `TypeError: string argument expected, got 'bytes'` error that pollutes the UI, will be handled by a re-spin of PR #2151, which is coming next.

Python 3 port: enable Avocado to run tests

---

optional_plugins/runner_remote/avocado_runner_remote/__init__.py

The operator is inverted since the beginning of times and no one ever
noticed. Until now.
Fixes #2275

remote: fix timeout check

---

avocado/utils/vmimage.py
docs/source/utils/vmimage.rst

The IMAGE_PROVIDERS stores possible classes to provide images, let's
avoid unnecessary multiple occurrences.

utils.vmimage: Use set to store providers

---

optional_plugins/runner_remote/avocado_runner_remote/__init__.py

Recent changes to remote runner use only stderr to get Avocado version,
but the docker plugin does not return separate stream for stdout and
stderr, therefor it always fails to get the version string. This patch
uses combination of stdeerr + stdout, which should be safe as we only
care about the first occurrence (so in case both stderr and stdout
produce version string, the stderr one will be used, anyway such
question is only hypothetical)

optional_plugins: Use stdout&stderr to get version

---

avocado/core/test.py
avocado/plugins/run.py
avocado/utils/process.py
selftests/functional/test_output.py
selftests/unit/test_utils_process.py

Avocado currently will run processes and split the STDOUT and STDERR streams.  This makes it impossible to have ordered (combined) output.
Some tests will record the combined output, and to play good with them,  Avocado must support a combined **and ordered** stdout+stderr mode.

Ordered process output

---

avocado/core/restclient/cli/app.py
contrib/scripts/avocado-find-unittests
optional_plugins/runner_remote/setup.py
selftests/cyclical_deps
setup.py

Another batch of changes for Python 3.  With these, Avocado can be installed and executed from a Python 3 virtual environment (venv) and `make check` on a development environment gets to the point of running tests (although some still fail) .

Python3 micro tasks pending

---

.travis.yml
contrib/scripts/avocado-check-pr.sh
docs/source/ContributionGuide.rst
selftests/checkall
selftests/functional/test_basic.py

This series introduces a contrib script to manually check PRs, changes the commits that are tested in travis, improves parallel check to avoid false-negatives and uses it to speed-up travis execution.
v1: https://github.com/avocado-framework/avocado/pull/2244
Changes:
```yaml
v2: avocado-check-pr check starts with first PR commit
v2: new commit to check only PR commits in travis PR check
v2: documentation
v2: possibility to specify remote branches
v2: new commit to avoid false-negatives in parallel check
v2: new commit to use parallel check in travis
v2: some bugfixes and little improvements like support to "abort" the interactive
execution (with cleanup)
```

Improve PR checks

---

.travis.yml
avocado/utils/process.py

- Revert "travis: Use parallel check in travis"
This reverts commit 4b29699.
Parallel check was enabled in Travis, but it's overloading the system
and making the time sensitive tests to FAIL.
- avocado.utils.process: fix default prefix
Log prefix needs at least the %-style string formatter. Let's include
that as the default so we don't break under 'no prefix'.

Travis fixes

---

selftests/functional/test_output.py

It looks like Travis does some different handling of process, and
we need to manually force the writes to the stdout.

selftests/functional/test_output.py: force writing to stdout

---

docs/source/optional_plugins/varianter_pict.rst

On `make rpm`, docs build fails with:
docs/source/optional_plugins/varianter_pict.rst:33: WARNING: Could
not lex literal_block as "ini".
This patch changes the way to define a block of code for a
proven-to-be-good one.

docs: fix make rpm sphinx error

---

optional_plugins/runner_remote/avocado_runner_remote/__init__.py

The remote runner is currently assuming not only about the existence
of mux_to_yaml plugin, which is bad enough, but relying on it to be
installed and active.
Let's default to no "mux files" if the plugin is not available.

runner_remote: do not assume varianter mux_to_yaml plugin is available

---

avocado/utils/multipath.py

There is a typo error in command execution in multipath.py in
get_path_status() method. so corrected it and it is working fine now.
Signed-off-by: Naresh Bannoth <nbannoth@linux.vnet.ibm.com>

correction of typo error in multipath.py

---

avocado/utils/wait.py

Sometimes, we want to use function has arguments in wait_for().
This patch supported optional arguments for wait function.
It's optional, so nothing effect for original usage.

utils/wait: support optional arguments for wait function

---

avocado/utils/process.py
selftests/unit/test_utils_process.py

The FDDrainer reads from the PIPEs and writes to both the internal
StringIO instances and to stream logging handlers.  There are no
guarantees that the logging handlers will flush the content before the
FDDrainer finishes.
Let's explicitly close all the handlers (which should really be
FileHandlers) associated with the stream loggers, which should flush
and sync the content on the files themselves.
Additionally, the combined drainer was being missed from the flush
process, and was causing some output in that mode to be unavailable on
generated output.

FDDrainer: flush the file based handlers before filling results

---

avocado/core/app.py

Hello guys, recently I'm getting more and more `/var/tmp/avocado_*` dirs being left behind. Not sure whether something changed in our sources, or the python version I use (python-2.7.13-2.fc25.x86_64) does not run `__del__` but this addresses the issue and should not generate new problems.

avocado: Force clean_tmp_files on exit

---

avocado/core/loader.py
selftests/functional/test_loader.py

v2:
- Add `:param subtests_filter:` to the `_make_test()` method docstring.
- Drop `ignore_status=True` from the selftest call to `process.run()`.
- Rebase.
v1: #2303 
- Make subtests filter to work in directory discoveries.
- Make subtests filter to work for SIMPLE tests.

Subtests filter fixes [V2]

---

examples/tests/doublefree.py

v2:
- Keep test pattern specific to `darwin`.
v1: #2316

examples: fix doublefree test [v2]

---

optional_plugins/resultsdb/avocado_resultsdb/__init__.py

The message is being printed even woth different result formats (json,
tap, ...). This patch makes it to be printed only when using default
TUI.

resultsdb: print IU message only when using default TUI

---

contrib/scripts/avocado-check-pr.sh

Actually the first~1 is necessary to check the first PR commit.

contrib: Fix the range in `avocado-check-pr`

---

avocado/core/runner.py
avocado/core/sysinfo.py
avocado/core/test.py
avocado/plugins/distro.py
avocado/plugins/replay.py
avocado/utils/asset.py
avocado/utils/cpu.py
avocado/utils/crypto.py
avocado/utils/distro.py
avocado/utils/download.py
avocado/utils/iso9660.py
avocado/utils/linux_modules.py
avocado/utils/memory.py
avocado/utils/partition.py
avocado/utils/path.py
avocado/utils/process.py
docs/source/conf.py
examples/tests/gdbtest.py
examples/tests/gendata.py
examples/tests/test_env.py
examples/tests/whiteboard.py
selftests/functional/test_basic.py
selftests/functional/test_job_timeout.py
selftests/functional/test_output.py
selftests/functional/test_skiptests.py
selftests/functional/test_statuses.py
selftests/unit/test_job.py
selftests/unit/test_utils_partition.py
setup.py

This is an attempt to catch most (if not all) usages of open
that do not follow the context manager pattern.
Sometimes, for better readability, our own `genio` library is
used.
---
* Included a higher number of occurrences (now, really possibly all of the applicable ones)

Python 3 port: implement consistent open() usage style [v2]

---

avocado/core/sysinfo.py
avocado/utils/gdb.py
avocado/utils/process.py
selftests/functional/test_sysinfo.py

This PR includes a number of cleanups and fixes related to `avocado.utils.process` library, including dropping some custom code from the sysinfo implementation and relying on that library.
---
Changes from v1 (#2337):
- Marked sysinfo interruption tests as "time/resource sensitive"

Process and sysinfo [v2]

---

avocado/core/varianter.py
optional_plugins/varianter_pict/avocado_varianter_pict/__init__.py

With the introduction of our first extra varianter plugin (PICT), I noticed that the UI is not handling multiple plugins properly. This PR fixes that by:
- Making sure the varianter will not include line breaks for plugins with no variants.
- Making sure the varianter_pict plugin will return an empty string on no-variants.

Fix variants output

---

optional_plugins/varianter_pict/avocado_varianter_pict/__init__.py

the variater_pict plugin has no verbosity level other than the default,
which is not enough to expose the parameters content.
This patch enables higher verbosity so users can see the parameters
content when using `-c` or `--variants 2`(or above) in the `avocado
variants` command.

varianter_pict: enable higher verbosity

---

optional_plugins/golang/avocado_golang/__init__.py

We should not discover the golang tests when we are not able to run them. This PR makes the golang plugin to skip the discovery process when the `go` bin is not present on the system.

Fix golang loader

---

avocado/utils/crypto.py

Fix the following two errors in hash_file:
* A wrong indentation caused a dead loop
* Forgot returning `None` when the given hash algorithm is unknown
Signed-off-by: Xu Han <xuhan@redhat.com>

utils.crypto: Fix two errors in hash_file

---

avocado/core/job.py
avocado/core/jobdata.py
avocado/core/parameters.py
avocado/core/parser.py
avocado/core/plugin_interfaces.py
avocado/core/runner.py
avocado/core/test.py
avocado/core/varianter.py
avocado/plugins/variants.py
avocado/utils/process.py
docs/source/TestParameters.rst
optional_plugins/loader_yaml/avocado_loader_yaml/__init__.py
optional_plugins/varianter_pict/avocado_varianter_pict/__init__.py
optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py
optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/mux.py
selftests/functional/test_basic.py
selftests/functional/test_multiplex.py
selftests/unit/test_mux.py

This PR is a collection of architectural and terminology arrangements.
It starts by not using the "mux" or "multiplexer" terminology in places where the (abstract) varianter interface is meant to be.  Then, it cleans up the `AvocadoParams` interfaces.  Finally, it moves the tests that are related to the mux code to the `yaml_to_mux` optional plugin, a primer that should be followed on other optional plugins.
---
Changes from v3 (#2349):
- Removal of the `Multiplexer: move respective tests to the yaml_to_mux plugin` to be introduced in a later PR
- Removed `test_id` docstring from `AvocadoParams`
- Removed `__getstate__` and `__setstate__` methods from `AvocadoParams` on commit `Parameters: remove knowledge about a specific (job) logger` because they are workarounds for the (now removed) …

Parameters: variants, not mux [v4]

---

avocado/core/parser.py
avocado/plugins/variants.py
optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py

Commit 51e46987af536048b55853ffdbfbde62b62cb822 changed it from
`mux_debug` to `debug`, but using `debug` is actually dangerous if some
higher level plugin creates the same option, since it can make the
varianter plugin to use TreeNodeDebug instead of TreeNode.
Let's use a more exclusive naming, while still in line with the actual
implementation.

Better naming for internal varianter debug argument

---

avocado/core/varianter.py

Recently we renamed the default varianter paths from "mux_path" to
"paths", which results in default "paths" being used when replaying
older results (including 52.0). Let's "upgrade" the results on-load.

varianter: Bring back compatibility with 52.0 results

---

README.rst
docs/source/GetStartedGuide.rst

We've got a new server, and the RPM repo is already there.  Let's use
that new server in the documentation.

Docs: update location for RPM repo location

---

.travis.yml
requirements-selftests.txt
requirements-travis.txt

This is a collection of configuration updates for the Travis-CI system.
---
Changes from v1 (#2368):
- Removed commit `Travis-CI: reduce the git clone depth`

Travis-CI: configuration updates [v2]

---

avocado/utils/network.py

Current code will try to find available from the start of range one by one, sometimes we want to randomly choose to reduce the chance to conflict.
---
Changes from v1 (#2359):
- Indentation fix
- Use range from six (iterator)
- Convert to list before (and only when) shuffling port range

support to find free port randomly [v2]

---

python-avocado.spec
selftests/unit/test_utils_cpu.py

After the tagging of 57.0, I noticed that the building of packages on EPEL 7 would fail because of older `mock` packages.
These changes reflect what was added to packages 57.0-1 for EPEL 7:
http://avocado-project.org/data/repos/epel-7-noarch/python-avocado-57.0-1.el7.centos.src.rpm
Whose contents are:
* `0001-selftests-unit-test_utils_cpu.py-skip-tests-on-older.patch`
* `avocado-57.0.tar.gz`
* `python-avocado.spec`
And, after that, to keep RPM history consistent, the patches are removed and the release version incremented again.

EPEL 7: RPM build release 57.0-1

---

requirements-travis.txt

A few extra configurations needed for the Python 3 builds running on Travis-CI.

Travis configuration for Python 3

---

avocado/utils/process.py
selftests/unit/test_utils_process.py

This seems like a small change, but it's a big way in the way towards Python 3.  Basically, it changes the behavior to always use bytes when reading and writing from the file descriptor (usually a PIPE) and also providing bytes instead of strings on its `data` attribute.

FD Drainer: always use bytes

---

avocado/utils/lv_utils.py

A collection of small fixes and cosmetic improvements to the `lv_utils` utility module.
---
Changes from v1 (#2381):
* Use `CmdResult` instance (`ex.result`) in the message logged as error instead of the bare exception instance `ex`

avocado/utils/lv_utils.py fixes [v2]

---

optional_plugins/html/avocado_result_html/__init__.py

The https://github.com/avocado-framework/avocado/pull/2385/commits/e51acbfad23feb0b0bf4fa0c51c51d4602a10945 broke "--open-browser" on python2 systems. Let's revert that commit and use different approach.

Fix `--open-browser` on Py2k

---

avocado/core/runner.py
avocado/utils/external/gdbmi_parser.py
avocado/utils/genio.py
avocado/utils/software_manager.py
examples/tests/failtest_ugly.py
examples/tests/gdbtest.py
scripts/avocado-run-testplan

A collection of miscellaneous fixes for the Python 3 port.
---
Changes from v1 (#2379):
* Use `six.moves.input()` to adapt to differences in `input()` on Python 2 and 3

Python 3 port: collection of fixes [v2]

---

avocado/core/parameters.py
selftests/unit/test_parameters.py

The docstring given on `_greedy_path()` has examples that don't match
the implementation.  To prevent the implementation from deviating
(again?) let's turn those into tests.
Also, to make the purpose of that function more clear, this
changes its name to `_greedy_path_to_re()`.

Parameters: fix wrong examples on _greedy_path

---

avocado/utils/vmimage.py

WIth the new repository, now it is possible to add our own JeOS Image
Provider to the vmimage module.

vmimage: add JeOS Image Provider

---

avocado/utils/archive.py
avocado/utils/vmimage.py
requirements.txt

pyliblzma is not required in python >= 3.3, and backports.lzma
works for all versions prior to that one. Let's update
the requirements.txt file to only install that backport
when necessary.

requirements.txt: Add conditional pyliblzma-req-install

---

README.rst
docs/README.rst
docs/source/GetStartedGuide.rst

The installation instructions will now favor a simpler (and more Pythonic) deployment strategy: the use of `pip` based installs.
By favoring installations in isolated (user dir or virtual environments) it should be possible to quickly install, upgrade and remove Avocado from a system, be it a developer workstation or a system that will just run tests and be done with it. 
**IMPORTANT**:  for a proper user experience, these documentation changes depend on the packaging fixes on #2394.  Without it, a `pip install --user avocado-framework` will fail trying to install data system wide (such as into `/etc`).

Docs: installation/deployment improvements

---

Makefile

Python wheel packages are really convenient.  Let's create and
distrubute them in addition to the source packages.

Makefile: create distribution rules for wheel packages

---

avocado/core/job.py

In case Avocado is executed from top of it's git repository the base_dir == "". It passes all the checks as "os.path.join" produces valid relative paths, but it fails when changing the dir there.
This breaks bisect so let's revert the patch which made this visible and apply it with the fix included.

Avoid using "" as path to get avocado git version

---

avocado/utils/cpu.py

arm64 or aarch64 pattern is not easy to identify in the
cpuinfo. For v7 there is model name in the cpuinfo and it
could be regonize as arm for 32 bit. But in v8 only could
found 'CPU architecture' in the cpuinfo and current code
will fail to match and return i386 which is wrong.
For fix this, if 'CPU architecture' found in cpuinfo, use
platform.machine to return the arch name.
Signed-off-by: Wayne Sun <gsun@redhat.com>

utils.cpu: Update cpu info pattern for aarch64

---

.travis.yml
selftests/checkall

Increases the failed_once threshold to 24 and enables the parallel check in Travis.

Increase failed_once threshold and enable parallel check in Travis

---

avocado/utils/software_manager.py

This avoids possible incorrect file location on cache-refresh and adds some cleanups to that code.
v1: https://github.com/avocado-framework/avocado/pull/2350
Changes:
```yaml
v2: Completely reworked as "yumdownloader" can't be fixed for older versions
v2: Added minor fixes to the touched code
```

utils.software_manager: Several "get_source" improvements of YUM backend [v2]

---

setup.py

With the python3 patches we have another core dependency on six. Let's
include it in setup.py as without it Avocado is unusable.

setup: Add "six" as install_requires

---

selftests/unit/test_xunit.py

In case on of the first cleanups fails the following ones are not
performed, leaving uncleaned files. Lets perform always all steps and
then check for occurred errors.

selftests: Avoid uncleaned dirs on xunit cleanup error

---

avocado/core/settings.py

Recently we introduced "in-package-config" which is packaged by default
with Avocado and in the original version if exists the system-wide
config is not used at all. I think this is unexpected behavior as users
are used to set configs in /etc so this patch changes it to first use
in-package-config, then in-etc-config and last the user-config.

settings: Change the config-file order

---

avocado/core/data_dir.py
avocado/core/settings.py

One user is using Avocado in container as a user without home-dir. That leads to some issues given to our wrong assumptions that there are always some writable locations.

avocado: Some fixes related to user-config

---

avocado/core/settings.py

The user-config location ("~/.config/avocado.conf") might not be
writable by users (usually when executing in docker without user
home-dir). Let's use the file if available, but don't fail in case we
fail to produce it.

[52LTS] avocado.settings: Don't fail when user can't write user-config

---

python-avocado.spec

Unless a lower version is set as a requirement, the RPM building
process will attempt to download from PyPI, which is not allowed.

SPEC: require a lower six version on EL7

---

optional_plugins/loader_yaml/avocado_loader_yaml/__init__.py

The YAML Test Loader is sending the messages for the UI. They
should go to the Job Log instead.

yaml loader: use JOB log instead of UI log

---

avocado/utils/process.py

Add support to provide input with subprocess.Popen's stdin.write method. Optionally flush the input buffer.

process.py: Add subprocess stdin.write() method

---

avocado/core/tree.py

There's a difference on how Python 2 and 3 represents a set(), which is true
for the set derived FilterSet.  It just happens the a tree fingerprint
depends on its environment, which depends on the FilterSet representation.
Let's provide a predictive __repr__ implementation, and consequently, a
predictive fingerprint for Trees across Python versions.
This fixes the following unittest failure on Python 3:
FAIL: test_fingerprint (selftests.unit.test_tree.TreeNode)
----------------------------------------------------------------------
File "/home/cleber/src/avocado/avocado/selftests/unit/test_tree.py", line 63, in test_fingerprint
"/foo{},{},FilterSet([]),FilterSet([])")
AssertionError: '/foo{},{},FilterSet(),FilterSet()' != …

Python 3: provide a predictive FilterSet.__repr__() implementation

---

avocado/utils/process.py

Revert "process.py: Add subprocess stdin.write() method"
The commit 3a66bcb is causing the
"selftests.functional.test_basic.RunnerOperationTest.test_read" selftest
to fail.
@apahim @clebergnu please take a look at this first and rebase all outstanding PRs after this is merged, otherwise the `incremental_check` fails (and if merged without it we'll have even more commits with malfunctioning `make check`).

Revert "process.py: Add subprocess stdin.write() method"

---

avocado/core/test.py
avocado/etc/avocado/avocado.conf
docs/source/WritingTests.rst
selftests/functional/test_basic.py

Currently simple tests have a limited status API, being able to set only
the WARN status by generating an output string in a very specific and
hard-coded format.
This patch, while respects the current behaviour, creates configuration
keys, allowing users to provide regular expressions to search for in the
test outputs, aiming to set the final test status to either WARN or SKIP
when the test finishes with exit code 0.
v4:
- rebased to avoid incremental_check failure
v3: #2434 
- Improve/fix selftest.
- Make clear that we are talking about python regex in both docs and the config file.
v2: #2430 
- Move class attributes to method variables.
v1: #2425

SIMPLE tests: improve status API

---

README.rst
avocado/utils/vmimage.py
docs/source/GetStartedGuide.rst

HTTPS has been enabled on the avocado-project.org server, so let's use
it by default on docs and when downloading images from it.

Server infrastructure: switch default URLs to HTTPS

---

avocado/utils/distro.py

1-In SUSE distro distro.detect() is failing as undefined variable
2- fixed pep8 issue on line no 319

 Fixed issue in avocado:utils:distro

---

avocado/core/runner.py

It was noticed during a review that, even though the SimpleQueue
requires a context on Python 3, the multiprocessing module can choose
one itself.
Since I originally had no intention to force the `spawn` type of
context, let's use that instead.  Also, since we're using different
names for a helper function and the class, inspekt/pylint exceptions
are not needed anymore.
Kudos to Amador Pahim for suggesting that.
Reference: https://github.com/avocado-framework/avocado/pull/2441#discussion_r167850053

Runner: let multiprocessing module choose the context type

---

avocado/core/test.py
examples/tests/whiteboard.py
selftests/functional/test_basic.py
selftests/functional/test_output.py
selftests/functional/test_output_check.py
selftests/unit/test_runner_queue.py

This is a second batch (not a v2) of miscellaneous test (and other) fixes, mostly necessary for the Python 3 port.
---
Changes from v1 (#2441):
* Let the `multiprocessing` module choose que context (when required, on Python 3) for the SimpleQueue used on the runner (as per https://github.com/avocado-framework/avocado/pull/2451)

Selftests:  miscellaneous fixes (2nd batch) [v2]

---

contrib/scripts/avocado-check-pr.sh

The "--rawurl" is not supported on later "fpaste" versions as it outputs
everything else to stderr. Anyway to keep compatibility with older
fpaste let's explicitly use `tail -n 1` to get only the last line.

contrib: Stop using "--rawurl" in "avocado-check-pr"

---

avocado/core/job.py
avocado/core/test.py
avocado/core/tree.py
avocado/plugins/xunit.py
avocado/utils/iso9660.py
avocado/utils/process.py
examples/tests/doublefree.py
optional_plugins/varianter_yaml_to_mux/tests/test_multiplex.py
optional_plugins/varianter_yaml_to_mux/tests/test_mux.py
selftests/functional/test_argument_parsing.py
selftests/functional/test_basic.py
selftests/functional/test_interrupt.py
selftests/functional/test_loader.py
selftests/functional/test_output.py
selftests/functional/test_plugin_diff.py
selftests/functional/test_plugin_jobscripts.py
selftests/functional/test_replay_basic.py
selftests/functional/test_replay_external_runner.py
selftests/functional/test_replay_failfast.py
selftests/functional/test_standalone.py
selftests/functional/test_streams.py
selftests/functional/test_sysinfo.py
selftests/functional/test_unittest_compat.py
selftests/functional/test_utils.py
selftests/unit/test_utils_iso9660.py

This is the fourth batch (not a v4) of miscellaneous test (and other) fixes, mostly necessary for the Python 3 port.
---
Changes from v1 (#2454):
* Added missing use of `Element()` (as opposed to `document.CreateElement()`) in `
xunit plugin: fix DOM usage`

Selftests and misc fixes (4th batch) [v2]

---

.travis.yml
Makefile
avocado/core/parser.py
avocado/core/varianter.py
avocado/utils/build.py
optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/mux.py

With 36lts now declared EOLed[1], let's remove code that was related to specifics of that release.
[1] - https://www.redhat.com/archives/avocado-devel/2018-February/msg00015.html
Prior to merging this, Avocado-Virt requires changes such as the ones proposed here: https://github.com/avocado-framework/avocado-virt/pull/104
---
* New commit: `mux: remove _get_variant_ids() method`
* New commit: `varianter: remove _process_default_params() method`
* Also document `ignore_status` parameter
* Removed `RFC` prefix from `avocado.utils.make: drop legacy interface` keeping the `avocado.utils.make.make()` method interface unchanged at this point

Drop 36lts code [v2]

---

avocado/core/loader.py
optional_plugins/runner_remote/avocado_runner_remote/__init__.py

This loader is supposed to not perform anything locally, and it's
actually a hack to bypass the loader when tests are to be resolved and
run remotely.
Its only users is the remote runner.  To avoid pollution in core,
let's move it to that module.

DummyLoader: move it out of core

---

avocado/plugins/diff.py
avocado/plugins/jsonresult.py
docs/source/ResultFormats.rst
selftests/functional/test_basic.py
selftests/functional/test_output.py

The "url" and "test" fields are just legacy and duplicated fields
that carry the same data as the "id" field.  Let's remove those.
---
Changes from v1 (#2461):
* Removed mentions for the fields in the documentation

JSON Result Plugin: remove legacy (duplicated) fields [v2]

---

.travis.yml
selftests/checkall
selftests/run
selftests/unit/test_runner_queue.py

This is a another milestone in the Python 3 port, in which failures to Python 3 will no longer be ignored on Travis-CI.  But, given that functional tests and optional plugin tests are still not 100% ported, this only runs unittests on Python 3.
---
Changes from v1 (#2464):
* Changed the order of commits, an attempt to tweak Travis wrt "allow failures" on Python 3
* Rebased

CI: enable Python 3 unittests [v2]

---

avocado/core/loader.py
avocado/core/test.py
docs/source/optional_plugins/yaml_loader.rst
examples/yaml_to_mux_loader/advanced.yaml
optional_plugins/loader_yaml/avocado_loader_yaml/__init__.py

This PR adds "special" key to the "yaml_loader" to prefix the test name. This would be useful for my CI as I need to run the same tests but with different setting. To support this some changes to our "Test" classes are necessary, because currently the "name" determines the to-be-executed command.

avocado_loader_yaml: Allow to set test name prefix

---

avocado/core/job.py
avocado/core/test.py

It was noticed that when running the full set of functional tests on Python 3 that 10 directories where leaked (some with extra files):
10 directories get left out:
```
$ inotifywatch -e create,delete /tmp 
Establishing watches...
Finished establishing watches, now collecting statistics.
^Ctotal  create  delete  filename
566    288     278     /tmp/
$ ls -1d avocado_*
avocado_0wkvc511
avocado_4_b5c3t7
avocado_8ll0n0me
avocado_9apb4zwz
avocado_9zg8jv_l
avocado_bq749f_t
avocado_ieli0ydf
avocado_o3i810ri
avocado_xfj81asc
avocado_z6tgawwk
```
The two fixes here avoid this leakage.

Python 3: avoid leaking temporary files

---

setup.py

We heavily depend on setuptools, let's add it to "install_requires".
Addresses: https://github.com/avocado-framework/avocado/issues/1798
Note: it's already required in RPM spec file.

setup: Add "setuptools" dependency

---

optional_plugins/glib/avocado_glib/__init__.py

This check was introduced in the previous draft of this plugin, when it
was using gtester, and left over. Dropping.

glib: remove legacy check

---

optional_plugins/glib/avocado_glib/__init__.py
optional_plugins/golang/avocado_golang/__init__.py
optional_plugins/robot/avocado_robot/__init__.py

Now there's a new parameter `executable` to use as the command line
information. The previous parameter, `name` can now be hijacked by
the yaml_loader, so this PR addresses that change in all the affected
optional_plugins.

Adapt optional_plugins to SimpleTest changes

---

setup.py

To fix the pip 9.0.1 install python requirements with ">=2.7, >=3.4" failure,
">=2.7, >=3.4" means ">=2.7" and ">=3.4", so the result is ">=3.4"
for reference: https://stackoverflow.com/questions/44660448/
Signed-off-by: Junxiang Li <junli@redhat.com>

Minorfix: Fix the install requirements

---

avocado/utils/build.py

As reported in the following link,
https://github.com/avocado-framework/avocado/issues/2476 build.run_make fails to run when used without any argument. This patch handles the failure and runs make with ncpus if it is not specified in "env".

Fix: utils/build.by

---

man/avocado.rst
optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py
optional_plugins/varianter_yaml_to_mux/tests/test_multiplex.py

The '--filter-{only,out}' and '--multiplex' options have been
deprecated in favor of '--mux-filter-{only,out}' and '--mux-yaml'.
Let's remove them for good.

Remove deprecated multiplex options

---

contrib/scripts/avocado-check-pr.sh

To avoid breakage when newer versions come out, let's pin to current
GitHub API version to v3.
Reference: https://developer.github.com/v3/media/#request-specific-version

avocado-check-pr.sh: pin GitHub API version

---

optional_plugins/loader_yaml/avocado_loader_yaml/__init__.py

The `extra_params` is a mutable object and can be modified by loader.
This happens eg. in external_runner loader which removes the optional
key. This patch uses `copy.deepcopy` to avoid such issues.

BUG: optional_plugins.loader_yaml: Avoid corrupting of extra_params

---

avocado/core/decorators.py
avocado/core/exceptions.py
avocado/core/test.py
docs/source/WritingTests.rst
examples/tests/cancelonsetup.py
examples/tests/vm-cleanup.py
selftests/.data/test_statuses.py
selftests/functional/test_statuses.py

The skip() method has been deprecated for quite some time.  Let's
remove it for good and have users using the decorators and cancel()
instead.

Test: remove deprecated skip() method

---

avocado/utils/data_structures.py
selftests/unit/test_data_structures.py

On Python 3, the calculation of a value for a unit will return
a float.  Let's make things predictable accross Python 2 and 3
and force an integer instead.
Reference: https://github.com/avocado-framework/avocado/pull/2498

DataSize: force values to be integers on Python 3

---

avocado/utils/process.py

The method flush() in FDDrainer does not check the stream is open
before get its file descriptor, resulting in "ValueError: I/O operation
on closed file".
Changed flush() to check the stream is open, otherwise do not
try to flush.

utils.process: FDDrainer.flush() check stream is open

---

avocado/core/tree.py
optional_plugins/varianter_yaml_to_mux/tests/test_mux.py
selftests/functional/test_json_variants.py

This is the ninth batch (not a v9) of miscellaneous test (and other) fixes, mostly necessary for the Python 3 port.
---
Changes from v1 (#2484):
* Changed `test_fingerprint_order` to also detect no extra content exists (suggested by @apahim )

Selftests and misc fixes (9th batch) [v2]

---

avocado/utils/process.py
selftests/unit/test_utils_process.py

The FDDrainer can fail to flush due to some other conditions,
including when the stream handler is a plain StreamHandler,
and not a FileHandler.
Let's add tests that cover this situation, and another one that's
already fixed that deals with closed streams.
Reference: https://github.com/avocado-framework/avocado/pull/2512
---
Changes from v1 (#2513):
* Used `self.assertIsNotNone(fd_drainer._stream_logger)` to ensure the test condition (i.e. stream is closed) is granted
* Ensured at least one handle has its stream closed before `flush()`

FDDrainer: flush reliably with different stream loggers [v2]

---

avocado/core/test.py
docs/source/DebuggingWithGDB.rst
docs/source/WritingTests.rst
examples/tests/cabort.py
examples/tests/datadir.py
examples/tests/doublefree.py
examples/tests/doublefree_nasty.py
examples/tests/env_variables.sh
examples/tests/linuxbuild.py
examples/tests/modify_variable.py
examples/tests/raise.py
examples/tests/synctest.py

After much discussion, it was decided that `srcdir` must go, and
`workdir` should be used instead.  At this time, let's deprecate
it, and in the near future, remove it.
The deprecation approach chosen is to flag tests that use `srcdir`
with warning, so users will hopefully take notice.
Reference: https://github.com/avocado-framework/avocado/issues/1924
Reference: https://trello.com/c/U1aaJjPJ/1158-deprecate-testsrcdir
Reference: https://trello.com/c/dCcxhJc2/1267-remove-testsrcdir
---
Changes from v1 (#2501):
* Produces test warnings on `srcdir` access
* Added estimate date on removal
* Moved the `AVOCADO_TEST_SRCDIR` environment variable documentation to the last position in the table, close to the deprecation warning.

Test: deprecate srcdir [v2]

---

selftests/functional/test_basic.py
selftests/functional/test_journal.py
selftests/functional/test_json_variants.py
selftests/functional/test_loader.py
selftests/functional/test_output.py
selftests/functional/test_output_check.py
selftests/functional/test_skiptests.py
selftests/functional/test_statuses.py

Under Python 3.4, which runs on our CI and is our lowest supported
version, json.loads() requires a string, while newer versions also
allows bytes.
>>> json.loads(b'{}')
File "/home/cleber/.local/lib/python3.4/json/__init__.py", line 312, in loads s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
Let's make that code compatible with Python 3.4.

Python 3: load JSON as supported on 3.4 (and earlier)

---

avocado/core/test.py
optional_plugins/html/avocado_result_html/__init__.py
optional_plugins/resultsdb/avocado_resultsdb/__init__.py

v2:
- No need to check whether `self.params` is present and populated.
v1: 2511

test results: optimize params information [v2]

---

examples/tests/raise.py
selftests/functional/test_basic.py
selftests/unit/test_xunit.py

The latest jobs have been failing because of the following issues:
```
************* Module raise
E1130: 48,30: Raise.test: bad operand type for unary -: NoneType
************* Module selftests.functional.test_basic
I1101:1191,24: PluginsXunitTest.run_and_check: Module 'lxml.etree'
has not 'XMLSchema' member, but source is unavailable. Consider
adding this module to extension-pkg-whitelist if you want to
perform analysis based on run-time introspection of living
objects.
I1101:1191,40: PluginsXunitTest.run_and_check: Module 'lxml.etree'
has not 'parse' member, but source is unavailable. Consider adding
this module to extension-pkg-whitelist if you want to perform
analysis based on run-time introspection of living objects.
I1101:1193,43: PluginsXunitTest.run_and_check: Module 'lxml.etree' …
```

Travis-CI: whitelist style check errors

---

avocado/utils/memory.py

The last change in meminfo object to use the new DataSize object
introduced a wrong behaviour. Currently meminfo is not returning updated
values. This patch fixes it.

meminfo: attributes should return current values

---

avocado/core/test.py
optional_plugins/html/avocado_result_html/__init__.py
optional_plugins/resultsdb/avocado_resultsdb/__init__.py

First commit makes "get_state" lenient towards incompatible "self.params" and the second commit makes "get_state" to use directly "self.__params" rather than "self.params", which should allow child classes to modify "self.params" while reporting the original Avocado-params (if treated correctly).
v1: https://github.com/avocado-framework/avocado/pull/2534
Changes:
```yaml
v2: Added commit to simplify child-classes params handling
```

test: Tweak get_state [v2]

---

avocado/core/test.py
selftests/unit/test_test.py

A small collection of miscellaneous `avocado.Test` improvements.
---
Changes from v1 (#2506):
* Use `RuntimeError` instead of `ValueError`
* New commits:
* `Test: rely on TestId.str_filesystem for the workdir`
* `Test: initialize workdir early in non-lazy mode`
* Some properties have **not** being converted to non-lazy mode, according to the issues described at: https://trello.com/c/SNIYpFS7/1278-avocadotest-optimize-some-properties

Misc avocado.Test improvements [v2]

---

avocado/core/job.py
avocado/core/test.py
avocado/plugins/run.py
optional_plugins/runner_remote/tests/test_remote.py
optional_plugins/runner_vm/tests/test_vm.py
selftests/unit/test_job.py

Historically the `avocado.core.job.Job` uses `datadir.get_tmp_dir` to get the job tmpdir, which (together with tmpdir cleanup and check) disallows the use of multiple jobs within one python interpreter. Let's create a job tmpdir there instead to allow that.
This unveiled how much handlers and temporary settings Job produces so there is an extra commit to require `Job.setup` and `Job.cleanup` calls manually to explicitly define where those handlers are in use.
v1: https://github.com/avocado-framework/avocado/pull/2436
v2: https://github.com/avocado-framework/avocado/pull/2465
v3: https://github.com/avocado-framework/avocado/pull/2520
v4: https://github.com/avocado-framework/avocado/pull/2541
Changes:
```yaml
v2: Use `datadir.get_tmp_dir` directly in Job instead of optional argument
v2: …
```

 avocado.core.job: Provide per-job tmpdir [v5]

---

avocado/utils/process.py

Module commands is removed in Python 3, try to simulate its function and outputs.
Signed-off-by: Junxiang Li junli@redhat.com
Changes from v1 (#2510):
- Update some old docstring
- Ensure the function could print str
- Full the paras
Changes from v2 (#2544):
- Rebased to allow CI jobs to pass after fixes
Changes from v3 (#2545):
- Fix the docstring error for new commands
- Separate commits for updating docstring

Python 3: Port from commands module to utils.process [v4]

---

avocado/plugins/exec_path.py
python-avocado.spec

This PR brings support for Python 3 versions of the Avocado RPM packages.

Python 3: Add RPM package support

---

optional_plugins/runner_remote/avocado_runner_remote/__init__.py
optional_plugins/varianter_yaml_to_mux/tests/test_mux.py
selftests/.data/test_statuses.py
selftests/checkall
selftests/unit/test_loader.py

Enabling an additional couple of warnings to our lint check. 
---
Changes from v1 (#2546):
* Renamed variable `ascii_` to `tree_view`

Lint: add w0101 and w0404 checks [v2]

---

avocado/core/defaults.py
avocado/core/test.py
avocado/utils/process.py
selftests/unit/test_utils_process.py

And allow that setting to be used on `avocado.uttils` APIs such as `process.run()`.  This fixes the crash reported, and fixed with a different implementation on PR #2538.
@ldoktor for your appreciation and review.

Avocado: set default encoding

---

avocado/utils/process.py
selftests/unit/test_utils_process.py

And only if the method is not available, attempt to fallback to
the stdout itself if it is a string.
Before 30617c1, the following kind of check was done:
>>> type(bytes('foo')) in string_types
False
And after it, the check was changed to:
>>> isinstance(bytes('foo'), string_types)
True
That made the bytes decoding not to be performed at times.  While the
new check is correct, we should favor the attempt to decode, and
only if not available, fallback to the original stdout if it looks
like a string.
---
Changes from v1 (#2549):
* Refer to the correct commit

avocado.utils.process: attempt first to decode bytes into text [v2]

---

examples/tests/doublefree.py
examples/tests/doublefree_nasty.py
examples/tests/modify_variable.py
examples/tests/multiple_tests.py
examples/tests/synctest.py
spell.ignore

---
Changes from v1 (#2551):
* `s/a the/a/` on docstrings

Spell check fixes for sprint #60 [v2]

---

selftests/functional/test_plugin_diff.py

And not the hardcoded path "./scripts/avocado".
Signed-off-by: Merlin Mathesius mmathesi@redhat.com
Signed-off-by: Cleber Rosa crosa@redhat.com

selftests/functional/test_plugin_diff.py: use the detected avocado script

---

avocado/core/test.py
selftests/functional/test_basic.py

To support the old syntax we need to use `re.MULTILINE` in SKIP detection and I believe it should be enabled for all regexps. While on it I noticed typo in `skip_location`, which is addressed by the second commit.

test: Adjust SimpleTest SKIP/WARN detection + bugfix

---

selftests/functional/test_plugin_diff.py

And not the hardcoded path "./scripts/avocado".
Signed-off-by: Merlin Mathesius <mmathesi@redhat.com>

[52LTS] selftests/functional/test_plugin_diff.py: use the detected avocado script

---

avocado/plugins/tap.py

text_output was removed from test status. Now we have to open the log
file directly.

tap: replace the text_output broken call

---

avocado/utils/astring.py
avocado/utils/external/spark.py
avocado/utils/linux_modules.py
avocado/utils/memory.py
avocado/utils/software_manager.py
selftests/functional/test_basic.py
selftests/unit/test_astring.py

The newly W605 warning is caused by incorrect escaped chars, that are
automatically translated to '\\' but future versions should treat it as
SyntaxError.

pylint: Fix W605 issues

---

avocado/utils/memory.py

Waiting 120s is not appropriate as the system takes less time for
memory state to change from 'going-online' to 'online' so changed
it to 10s and with freq of 0.2s

Wait 10s for the memory state to change

---

avocado/utils/astring.py
selftests/unit/test_test.py

We are using `;` in the test name, before the Variant ID. That character
is unsafe to be used as a fs path and, as such, need to be replaced for
a `_`.
Fixes: #2567

utils.astring: add `;` to the FS_UNSAFE_CHARS

---

examples/tests/gdbtest.py

When this test was initially written, the concept of a shared
directory available across tests did not exist.  Let's optimize the
execution by avoid compilation of the same binary on every single
test.

examples/tests/gdbtest.py: use teststmpdir for compiled binaries

---

selftests/functional/test_basic.py
selftests/functional/test_interrupt.py
selftests/functional/test_loader.py

And that have been causing failures on Travis jobs, due to limited
on unreliable amount of resources present.
This is the full list of tests that won't be run anymore on Travis,
only on `make check-full`:
selftests.functional.test_basic.RunnerOperationTest.test_early_latest_result
selftests.functional.test_basic.RunnerSimpleTest.test_kill_stopped_sleep
selftests.functional.test_interrupt.InterruptTest.test_well_behaved_sigint
selftests.functional.test_interrupt.InterruptTest.test_well_behaved_sigterm
selftests.functional.test_loader.LoaderTestFunctional.test_simple_using_main
selftests.functional.test_loader.LoaderTestFunctional.test_sleep_a_lot

Travis-CI: skip tests that are time/resource sensitive

---

optional_plugins/varianter_yaml_to_mux/tests/test_multiplex.py
selftests/checkall
selftests/functional/test_basic.py
selftests/functional/test_interrupt.py
selftests/functional/test_loader.py
selftests/functional/test_output.py
selftests/functional/test_output_check.py
selftests/run

There are few issues (3 to my count) which affect a number of tests
on Python 3.  Instead of not executing any of the functional tests,
let's skip the broken ones.
This is important because it will prevent new issues from making
its way into the Avocado code.
The list of tests being skipped is being tracked on our planning board,
so that they are accounted for, and enabled when fixed.
Reference: https://trello.com/c/eFY9Vw1R/1282-python-3-functional-tests-checklist
---
Changes from v2 (#2565):
* Rebased on top of PR #2585 
Changes from v1 (#2518):
* Added commit to fix loading of JSON on Python 3.4 (which runs on Travis-CI)
* Rebased

Python 3: enable functional tests and temporary skips to broken tests [v3]

---

avocado/utils/cpu.py

- try harder to detect arm.
- detect more archs (s390, sparc64 and i386).
- fallback to plataform.machine() (instead of returning i386).
Reference: https://trello.com/c/WbbZw5wq/1213-obsolete-getcpuarch-and-add-2-functions-instead-with-consistent-returns

utils.cpu: improve get_cpu_arch()

---

python-avocado.spec
selftests/functional/test_basic.py
selftests/functional/test_standalone.py
selftests/unit/test_job.py
selftests/unit/test_runner_queue.py

This release I got quite a lot of issues mainly related to python3 changes. This fixes almost all of them (TAP issue and --vm-domain issues not included as they'll require deeper analysis).

Few selftest and python-avocado.spec fixes related to manual testplan

---

avocado/core/sysinfo.py

when writing log into log file,string is used instead of bytes
Signed-off-by: chunfuwen <chwen@redhat.com>

python3: fix 'str' does not support the buffer interface

---

avocado/plugins/list.py
avocado/utils/astring.py
selftests/functional/test_basic.py
selftests/unit/test_utils_astring.py

The first patch improves iter_tabular_output() and tabular_output() by allowing to strip trailing whitespace on rows. It is a pre-req for next patch that solves https://trello.com/c/JWeay87z/1045-strip-tabularoutput-lines
Changes since v4 (#2610):
- Adjusted the PluginsTest.test_list_no_file_loader() test due lack of whitespace on outputs to be compared.

Avocado list tabular out [v5]

---

selftests/.data/jenkins-junit.xsd
selftests/functional/test_basic.py
selftests/unit/test_xunit.py

This prints the error information when schema validation fails, and updates the Jenkins JUnit schema name and source.

Xunit Plugin: minor changes to schema and schema validation

---

avocado/core/test.py
avocado/plugins/jsonresult.py
avocado/plugins/xunit.py
avocado/utils/astring.py
avocado/utils/partition.py
examples/tests/errortest_nasty.py
examples/tests/errortest_nasty2.py
optional_plugins/html/avocado_result_html/__init__.py
selftests/functional/test_standalone.py
selftests/unit/test_astring.py

While working on yaml2mux I created few utils to help me developing py2/py3 decoded streams. To test them and see whether they're useful outside I started fixing Avocado to support unicode properly. This is a first stage to hammer-out the basic usage which would be then applied on other pieces (including yaml2mux).
Basically I bring back the idea of defining "preferred encoding" in astring to avoid the need to import locale and remembering the ugly long name and using this encoding by default everywhere (for now in `astring` module, but eventually even in process, etc.).
On many places in Avocado we use `str()` to convert objects to string representation, which doesn't work on py2 with unicode so the `astring.to_text` method was adjusted to allow such usage. Eventually it should replace …

Some Test encoding fixes [v4]

---

avocado/utils/cpu.py
selftests/unit/test_utils_cpu.py

For a number of architectures, and a extension to the logic to check
for riscv and ARM v8 (AKA, aarch64) processors.
Reference: https://github.com/avocado-framework/avocado/pull/2589
---
Changes from v1 (#2594):
* Renamed risc-v arch name to "riscv"
* Return "aarch64" for ARM v8
* Fixed style issues
* Rebased

avocado.utils.cpu: add tests for get_cpu_arch() [v2]

---

python-avocado.spec

While examining the latest avocado binary RPMs, I noticed a few things that are fixed by this PR:
* move man pages from `python2-avocado` to `python-avocado-common` package
* claim package ownership of all config and content directories
* Python version-specific packaging of `avocado-rest-client`
I noticed another thing that I didn't fix...
The supposedly version-agnostic `python-avocado-examples` package has byte-compiled `.pyc` and `.pyo` files for python2 (system default python) in `/usr/share/avocado`. Due to that installation directory, the RPM build process automatically byte-compiles all `.py` files it finds.
Since the examples are technically documentation, the ideal way to fix that problem would be to install the examples to `/usr/share/doc/avocado` instead--which is ignored by …

SPEC file cleanup

---

selftests/unit/test_data_structures.py

On some architectures, Python will return a long on
data_structures.DataSize conversions.  That makes the identity
check assertion fail, because:
>>> long(0) == int(0)
True
But:
>>> long(0) is int(0)
False
Reference: https://kojipkgs.fedoraproject.org//work/tasks/1223/26881223/build.log

selftests/unit/test_data_structures.py: identity check is unsuitable

---

avocado/utils/vmimage.py

Fedora 28 changed the URL of the Cloud Images, from "CloudImages" to
simply "Cloud".  Let's adapt the name depending on the version
requested.

avocado/utils/vmimage.py: support Fedora 28 directory structure change

---

avocado/core/test.py
avocado/etc/avocado/avocado.conf
docs/source/Configuration.rst
docs/source/GetStartedGuide.rst
docs/source/Loaders.rst
docs/source/WritingTests.rst
man/avocado.rst
python-avocado.spec

Following up on an open question from PR #2625:
The supposedly version-agnostic `python-avocado-examples` package currently contains byte-compiled `.pyc` and `.pyo` files for python2 (which is the system default python) which get installed in `/usr/share/avocado`. Due to that choice of installation directory, the RPM build process automatically byte-compiles all `.py` files it finds.
Since the examples are technically documentation, the ideal way to fix that problem is to install the examples to `/usr/share/doc/avocado` instead--which is ignored by the automatic byte-compilation.
Signed-off-by: Merlin Mathesius <mmathesi@redhat.com>

SPEC file: relocate examples to doc directory

---

avocado/utils/astring.py
avocado/utils/process.py
docs/source/WritingTests.rst
selftests/unit/test_utils_process.py

This is a cherry-pick of https://github.com/avocado-framework/avocado/pull/2650 with only the non-controversial commits.
Changes:
```yaml
v2: Changed other `mod` to `data` occurrences in the docstring
v2: Added documentation about `output` file and pointer to `replace` behavior
v1: Removed the controversial "Support for non-default encoding"
v1: Added note to documentation about "replace" in stdout checker
v1: Use "replace" for the remaining chars without \n as well (forgot in the original series)
v1: Added selftest for "replace" ignoring chars
```

Process encoding cherry-pick [v2]

---

avocado/utils/pci.py
selftests/unit/test_utils_pci.py

In case of bare-metal machine the actual string for the location code parameter
is 'PLX Slot1' but the regex was failing to parse, so extended regex to also cover
this case. also return the slot cleanly i.e only if the match is found.
that fixes this error: at pci.py", line 185,
AttributeError: 'NoneType' object has no attribute 'group'

get_slot_from_sysfs fails for bare-metal machine

---

avocado/plugins/diff.py

The test name combines $test_id-$test_name;$variant_id, which prevents
from comparing apples to oranges, but for some jobs we know the
$test_name itself identifies the test well enough and by stripping the
$test_id we can easily compare even tests with different number of
tests.
Example with ids (stock):
-1-passtest.py:PassTest.test: PASS
+1-failtest.py:FailTest.test: FAIL
+2-passtest.py:PassTest.test: PASS
The same without ids (--diff-strip-id):
+failtest.py:FailTest.test: FAIL
passtest.py:PassTest.test: PASS
and it gets more useful with multiple inserted tests.

plugins.diff: Allow to strip ids from test names

---

avocado/core/test.py
docs/source/WritingTests.rst
examples/tests/env_variables.sh
examples/tests/linuxbuild.py
selftests/functional/test_export_variables.py
selftests/unit/test_test.py

These have been deprecated for a while, and are now past due their removal, so let's do it now.
---
Changes from v1 (#2653):
* Changed wording and fixed typo on datadir removal (s/extint/previously existing)
* Better unittest docstrings

Remove the deprecated Test.srcdir and Test.datadir attributes [v2]

---

avocado/utils/distro.py

Add an Amazon Linux Probe, for both versions 1 and 2
of the distribution.

avocado.utils.distro: Add Amazon Linux Probe

---

README.rst
docs/source/GetStartedGuide.rst

Avocado is frequently used with Avocado-VT, so let's make it easier
for users to jump to Avocado-VT's documentation for a smoothier
installation experience.
This is based on real feedback from a long time user, after wasting time
attempting to find Avocado-VT references.

Docs: reference Avocado-VT from Avocado's installation instructions

---

avocado/utils/cpu.py
selftests/unit/test_utils_cpu.py

This PR fixes a number of issues with the CPU utility libraries.  Basically, it moves to using bytes, since it interacts with `/proc/*` and `/sys/*` files which are produced by the Kernel and won't follow any kind of userspace locale/encoding.
The failures on Python 3 were not being caught on CI because of another issue (https://trello.com/c/G3bT5ekt/1342-bug-parallel-self-check-misses-tests-not-run).

CPU Utils: support both Python 2 and 3 

---

examples/tests/env_variables.sh
selftests/functional/test_export_variables.py

AVOCADO_TEST_DATADIR is deprecated.
Removing them from the examples and selftests.

Removing the deprecated AVOCADO_TEST_DATADIR

---

avocado/utils/cpu.py

The legacy disable value is currently transformed in a loop using the
same variable, which results in TypeError as the transformed output is
not a valid input. Let's fix it by only single transformation in case
`setstate` is not used.
With `setstate` the value can be safely overridden as the value comes
from `setstate`.

utils.cpu: Avoid multiple-transformation of disable value

---

avocado/utils/pci.py

PCI Bridges can be represented in lspci output in different ways.
But they are all of Class 06.
So, handling using class id instead, which is a better way.
Changes from V1 (https://github.com/avocado-framework/avocado/pull/2380/commits/e80c4478c07e0292daf65c74dfe8dd3e7b4b423) : used `startswith()` as per suggestion from @apahim 

Better handling of PCI bridges in pci utils

---

avocado/plugins/tap.py
docs/source/release_notes/lts/next.rst
man/avocado.rst
selftests/functional/test_output.py

For a while we want to decrease the default verbosity https://trello.com/c/90Zvwccm/1303-allow-to-tweak-verbosity-of-tap-plugin and recently we got feedback that it even slows-down test execution https://github.com/avocado-framework/avocado/issues/2647 Let's address both and disable default verbosity while improving the performance by decreasing the number of fsync.
v1: https://github.com/avocado-framework/avocado/pull/2679
Changes:
```yaml
v2: Fixed selftests
v2: Use 'Defaults to ...' instead of '((default)'
v2: Rebased
```
PS: Even on "errortest.py" the difference is `0.2s`

Two little improvements to TAP plugin [v2]

---

selftests/checkall

During the parallel execution of unittests, only conditions for FAIL
and ERROR are checked.  Under Python > 3.4, that's fine because load
failures are treated as FAILures:
```
$ python3.6
Python 3.6.5 (default, Mar 29 2018, 18:20:46)
[GCC 8.0.1 20180317 (Red Hat 8.0.1-0.19)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import unittest.loader
>>> l = unittest.loader.TestLoader()
>>> l.loadTestsFromName('selftests.unit.test_utils_cpu.Cpu.test_cpu_arch_ppc64_power8')
<unittest.suite.TestSuite tests=[<unittest.loader._FailedTest testMethod=test_utils_cpu>]>
```
But, under Python 3.4, no such treatment is done:
```
$ python3.4
Python 3.4.3 (default, Jan 13 2018, 13:06:46)
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)] on linux
Type "help", "copyright", "credits" …
```

selftests/checkall: check load failures [v2]

---

avocado/core/parser.py
selftests/functional/test_argument_parsing.py

Many arguments are provided by plugins, let's suggest checking the
installed plugins on unrecognized argument to raise awareness of the
need to install additional plugins which might help people that see
Avocado for the first time.
v1: https://github.com/avocado-framework/avocado/pull/2644
Changes
```yaml
v2: Improved error message
```

parser: Suggest installing plugins on missing command

---

avocado/core/loader.py
avocado/plugins/list.py
optional_plugins/glib/avocado_glib/__init__.py
optional_plugins/golang/avocado_golang/__init__.py
optional_plugins/loader_yaml/avocado_loader_yaml/__init__.py
optional_plugins/robot/avocado_robot/__init__.py
optional_plugins/runner_remote/avocado_runner_remote/__init__.py
python-avocado.spec
selftests/unit/test_loader.py
setup.py

This change reveleaed a couple of location in the symbolic names where
not being used, but their special values were being evaluated.  Let's
avoid using the special (and subtle) meaning of ALL (True) and
DEFAULT/AVAILABLE (which evaluate to False).
The enum library is part of the standard library, starting from 3.4
(which is the mininum version we require for Avocado).  On Python 2.7,
we can rely on the backport package.
This is of course not necessary right now, but I feel that we can
continue modernizing the code base, and not wait for 2020 and then be
liberated to use newer constructs and libraries.
Reference: https://trello.com/c/k90E1kdg/1357-loader-remove-compatibility-aliases
---
Changes from v2 (#2681):
* Added compatibility aliases …

Test Loader: use enums from from Python 3.4 [v3]

---

avocado/utils/multipath.py

We were sleeping instead of waiting for the service to become
stable, after a service restart. So, replaced the sleep with
wait_for.

multipath: Replaced the sleep with wait_for

---

optional_plugins/runner_remote/setup.py
python-avocado.spec

Avocado 62.0 fails to build in Fedora Rawhide because the old `fabric` package was renamed to `fabric3`, and there is a new `fabric` package.
It appears that `optional_plugins/runner_remote/setup.py` tried to accommodate this renaming, but did so based on checking the Python version rather than the Fedora release. This PR corrects that.
The SPEC file also needs to require the renamed `fabric` package starting with the current Fedora Rawhide release. It also needs to require the Python `distro` package so the previously mentioned `setup.py` script update can detect the Fedora release. This PR makes those changes as well.
Also note: the renamed `fabric` package now also includes a Python3 version--which should help make several plugins available for Python3.

Fix Rawhide build failure due to fabric package rename

---

optional_plugins/runner_remote/avocado_runner_remote/__init__.py
optional_plugins/runner_remote/tests/test_remote.py

Add support for "--filter-by-tags" and automates the way arguments are whitelisted.
Fixes: https://github.com/avocado-framework/avocado/issues/2704
Changes:
```yaml
v2: Repeat `--filter-by-tags` per each item as it uses `action=store` and not `nargs+`
```

Tags for remote runner [v2]

---

optional_plugins/runner_remote/avocado_runner_remote/__init__.py
optional_plugins/runner_remote/setup.py

Respect the "~/.ssh/config" files when using remote runner to allow
users to configure their connection details.
Fixes: https://github.com/avocado-framework/avocado/issues/2141

optional_plugins.remote_runner: Respect ~/.ssh/config

---

optional_plugins/varianter_yaml_to_mux/setup.py

The PyYAML-4.0 to PyYAML-4.2b1 lack "construct_python_str" which is used
in varianter_yaml_to_mux. Note that 4.0 nor 4.1 were ever released on
pip but they exist in some distributions, therefor it makes sense to
include them here.

optional_plugins: Blacklist unsupported versions of PyYAML

---

selftests/functional/test_output.py

It has been reported that on some occasions python can report extra
lines when the pipe is broken:
python2 -c 'print("Hello, World!")' | no-such-command
-bash: no-such-command: command not found
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
Let's remove the check for the number of lines and only keep the check
for unexpected words.
Fixes: https://github.com/avocado-framework/avocado/issues/2671

selftests: Easy a bit the OutputPluginTest.test_broken_pipe test

---

avocado/utils/service.py
selftests/unit/test_utils_service.py

There are few style-fixes and improved selftests related to `avocado.utils.service`. The last commit might be problematic as it changes variable-names, but I only addressed the private ones so hopefully no-one is using them.
v1: https://github.com/avocado-framework/avocado/pull/2668
v2: https://github.com/avocado-framework/avocado/pull/2670
Changes:
```yaml
v2: Removed and "improved" assert message as it wasn't that helpful
v2: Removed accidentally modified docstrings that weren't meant to be updated (variable name)
v2: Rebased
v3: Used "!=" instead of "not in"
```
_I haven't changed the pylint fixes commit as I simply fixed all issues within the module instead of fixing some specific issues everywhere. It was not on purpose, I accidentally fixed them while improving the library (sorry, …

utils.service: Few style-fixes [v3]

---

avocado/core/test.py
avocado/utils/script.py
selftests/functional/test_output_check.py

We addressed the process encoding almost everywhere, only the RawFileHandler stayed unchanged resulting in non-ascii output not being recorded. Let's use `astring.ENCODING` and just to be sure 'xmlcharrefreplace' to store the output as much as possible (we already mention in documentation that we want to keep this one in text-mode).
The rest of the commits are minor tweaks and fixes needed for selftest purposes.
Fixes: https://github.com/avocado-framework/avocado/pull/2638

Fix output check recorder encoding

---

avocado/core/dispatcher.py
avocado/core/output.py
avocado/utils/debug.py
avocado/utils/process.py
optional_plugins/runner_remote/avocado_runner_remote/__init__.py
optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/mux.py
selftests/unit/test_output.py

This  slightly diverged so it started as "less", but there are several fixes  found while working on it and in travis. See the actual commit messages  for details.
v1: https://github.com/avocado-framework/avocado/pull/2676
changes:
```yaml
v2: Addressed a untreated logger name change in "optional_plugins"
v2: Improved messages/docstrings
v2: Use list instead of string in raised exception
```

 Avoid crash in case paginator tries to use not available "less" [v2]

---

requirements-travis.txt

Avocado uses inspekt, which in turn uses pylint.  On Travis-CI under
Python 2.7, pylint 1.9.2 is being used, while on Python 3.4 it's
installing 2.0.0.
The pylint 2.0.0 API is different, and produces the following error:
Running 'inspekt lint --exclude=.git --enable W0101,W0102,W0404,W0611,W0612,W0622'
Pylint disabled: W,R,C,E1002,E1101,E1103,E1120,F0401,I0011
Pylint enabled : W0101,W0102,W0404,W0611,W0612,W0622
__init__() got an unexpected keyword argument 'exit'
lint FAILED
Let's pin the pylint version for predictable results, as we do with
pycodestyle.
Reference: https://trello.com/c/LDbYJFeR/1374-lint-failed-on-python-3

Travis CI: pin pylint version

---

selftests/functional/test_output_check.py

Formatting bytes was only introduced on Python 3.5, so let's just
add the bytes. At the same time, there's no need for some of that
content to live in the module namespace, as only STDOUT and STDERR
are used later in the tests.

selftests/functional/test_output_check.py: fix Python 3.4 syntax

---

optional_plugins/runner_remote/setup.py

Fedora 29 (currently rawhide) has a python2-fabric3 package, so it can
use that (Fabric3) as a requirement on both Python 2.7 and 3.4+.  But
we have not switched to Fabric3 on other environments, so let's keep
the fabric (1.x) series there.

Remote runner: provide fabric version for Python 3 on non-Fedora

---

selftests/functional/test_basic.py
selftests/functional/test_skiptests.py
selftests/functional/test_utils.py
selftests/run

This PR makes sure the currently running version of the Python interpreter is used to execute certain test scripts. This becomes absolutely necessary in Fedora Rawhide because `/usr/bin/python` no longer exists.
This PR also updates an assertion in `test_dry_run()` in `selftests/functional/test_basic.py` to report diagnostic information to help determine _why_ the assertion failed.

small improvements to selftests

---

avocado/utils/cpu.py

@sathnaga this is related to https://github.com/avocado-framework/avocado/pull/2697 would you please review it?

utils: Avoid crashe in case only one cpufreq governor is supported

---

avocado/utils/archive.py

tests or framework might need the name of the extracted archive to
perform necessary steps, it is better and harmless to return the name
in extract().
Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>

utils/archive: return extracted name

---

avocado/core/tree.py
optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/mux.py

Raising StopIteration gets translated to a RuntimeError in Python 3.7.
The same behavior can be achieved by 'return' from generators.
Reference: https://github.com/avocado-framework/avocado/issues/2721

PEP479: do not raise StopIteration

---

selftests/functional/test_basic.py

`examples/tests/simplewarning.sh` calls a generic avocado command,
which gets added to the path by the test code. That generic avocado
command is `scripts/avocado`, from the source repository, which
contains the unversioned `/usr/bin/env python`.
Under some environments, such as Fedora >= 29, there may be no
unversioned Python binary.  Let's respect the UNITTEST_AVOCADO_CMD
environment variable, and add the the directory containting that
binary to the PATH.

selftests/functional/test_basic.py: prevent unversioned Python

---

python-avocado.spec

@ldoktor, as I suggested in https://github.com/avocado-framework/avocado/pull/2669, I spent a few moments revising the SPEC to enable python3 versions of runner and resultsdb plugins when package dependencies are available.
Unfortunately, there are currently known compatibility issues with the release of the PyYAML package in Rawhide that cause self-tests to fail, and there are probably other issues as well.
Due to other obligations, I likely won't have a chance to work on this any more for several weeks. But hopefully this is a head start if you want to run with it.

enable python3 versions of runner and resultsdb plugins

---

Makefile.include

Some systems don't ship with "pip" binary and only provide the "pip3".
Instead of attempting to get the right one, let's just use "python -m
pip" that should work the same way plus we always use the right version
(py2/py3).

Makefile: Make sure to use pip of the same version as python

---

python-avocado.spec

Add RPM packaging for the CIT varianter plugin.
---
Changes from v1 (#2733):
* Fixed the description (not based on third-party tool)

CIT Varianter: add RPM packages [v2]

---

avocado/utils/cpu.py
selftests/unit/test_utils_cpu.py

Difference between aarch32/64 is fairly simple, let's detect it
ourselves instead of relying on "machine.platform".
Fixes: https://github.com/avocado-framework/avocado/issues/2737
v1: https://github.com/avocado-framework/avocado/pull/2739
Changes:
```yaml
v2: Fixed indentation
v2: Use bytes in "startswith"
```
PS: We could either fix selftest and mock the `machine` call in `arm` case, or avoid the `machine` completely. Here I chose the later as the detection is (currently) fairly simple and we are about to rework it anyway in https://trello.com/c/WbbZw5wq/1213-obsolete-getcpuarch-and-add-2-functions-instead-with-consistent-returns

utils.cpu: Custom detection of arm [v2]

---

Makefile

commit "c5d6209 Makefile: add requirements-plugins target" forgot an
's' in 'requirements'
Signed-off-by: Fabiano Rosas <farosas@linux.ibm.com>

Makefile: fix typo in requirements-plugins target

---

avocado/utils/iso9660.py
requirements-travis.txt
selftests/unit/test_utils_iso9660.py

This implements another backend for the avocado.utils.iso9660 library,
based on the pure Python pycdlib.
The library, as it's the case with all other ISO9660 utilities, is
optional and should only attempted to be be used if they are available
in the system.
In theory, we're well equipped with backends, but this brings the
interesting possibility of running on non-UNIX platforms.
---
Changes from v2 (#2730):
* Simplified `has_pycdlib`
Changes from v1 (#2727):
* Bumped pycdlib requirement to 1.6.0 on Travis (yet to be released, but already contains fixes)
* Added new class to `__all__`
---
Note: the Travis-CI jobs will only pass after the new pycdlib is released an available from pip.

ISO9660: add a pycdlib backend [v3]

---

avocado/core/parameters.py
avocado/core/varianter.py
selftests/unit/test_parameters.py

This PR modifies the "--json-variants-load" to not to crash on py3.

Fix "--json-variants-load" for python3

---

optional_plugins/varianter_cit/avocado_varianter_cit/__init__.py

This unifies the to_str and fixes a bug in varianter path for the CIT plugin.

Fix varianter_cit mux-path and str representation

---

avocado/utils/archive.py

Which will return the first member of the archive, either a file or
directory.  If the archive is empty, it'll return None.

avocado.utils.archive: improve docstring for extract()

---

avocado/utils/process.py
selftests/unit/test_utils_process.py

Python 3.7 introduced a new way to add breakpoint on the code. It was
added the built-in breackpoint function. There was couple of places
where the word breakpoint was being redefined making pylint execution
fail with W0622 error (Redefining built-in). This commit replaces
'breakpoint' with 'break_point' in these places.

Fix W0622 pylint error in python 3.7

---

.gitignore

When `make develop` is run egg-info directories are created. We
shouldn't add them to version control, so this commit adds the proper
entry to gitignore file.

Adds egg-info directories to gitignore

---

selftests/run

E1111 error happens when a function which doesn't return is used to
assign to something. In this particular case the `unittest.TextTestResut`
`stopTest` method doesn't return and its result is being assigned to a
variable. This behaviour makes pylint fails with E1111 error. This
commit just don't assign the result of super() call and also keeps the
super class method behavior (not returning).

Fix E1111 pylint error

---

selftests/functional/test_output.py

Instead of creating new temporary dirs and files, and handling their
removal in each test, let's just create additional dirs/files in the
already provided tmpdir, which will be removed by the test tearDown
method.

selftests/functional/test_output.py: simplify temporary dir/file usage

---

avocado/utils/archive.py
avocado/utils/vmimage.py
selftests/unit/test_utils_vmimage.py

The `avocado.util.archive` already contains code to extract files compressed with xz.  It may be that there's only support for tar+xz, but in any case, the code should be improved and live in `avocado.utils.archive`.
Plus, a couple of other `vmimage` fixes.

avocado.utils.vmimage: move decompression to avocado.utils.archive

---

avocado/utils/vmimage.py

Which is used for the (usually temporary) snapshot image.  By default,
it's kept in the on the same directory as the base image.  When
downloading the base image into a test's cache_dir, it makes sense to
keep the snapshot out of the cache_dir, usually in the test's workdir.
---
Changes from v1 (#2749):
* Dropped a typo (`s/the//`)

avocado.utils.vmimage: allow users to specify a snapshot dir [v2]

---

requirements-travis.txt

This started as a hunt for "foo" doesn't exist in module "bar" errors
in "inspekt lint" checks.  It looks like it fixes those issues, but
even if it doesn't, it's a valid change in itself.

Travis: update versions of modules used in lint/syntax checks

---

selftests/deployment/README
selftests/deployment/ansible.cfg
selftests/deployment/inventory
selftests/deployment/pip-git.yml
selftests/deployment/tasks/epel.yml
selftests/deployment/tasks/python_rpm_pkgs.yml
selftests/deployment/vars.yml

While abusing the term tests, this is an initial set of files that are
intended to test how Avocado can be deployed on various platforms,
using different installation methods.
At this point, a single combination of installation method (pip) and
destination (virtual environment).

Initial set of deployment "tests"

---

avocado/plugins/diff.py
avocado/utils/external/spark.py
selftests/checkall
selftests/unit/test_test.py

In order to enable all pylint W01xx checks, this change removes some
pointless statements that already was in the code base and enable proper
checks in checkall script.
Reference: https://trello.com/c/Ohh7Q6qj
Signed-off-by: Caio Carrara ccarrara@redhat.com
---
Changes from v1 (#2772)
- Replaces map-lambda by list comprehension on Spark (enabling Pylint W0110)

Pylint enable w01xx checks v2

---

avocado/utils/distro.py

The standard library platform.dist function has been deprecated since
2.6, and has now been removed in 3.8.  Since we used as mostly a
fallback probe (other more specific ones are present), it seems safe
to remove this one, and probably wiser to remove it "sooner" than
"even later".
Reference: https://trello.com/c/f2g8BUSt
Reference: https://docs.python.org/2/library/platform.html#platform.dist

avocado.utils.distro: remove dependency on deprecated platform.dist

---

requirements-travis.txt

PyYAML is the first failure on Travis' Python Nightly jobs.  The
version we're using is ancient, dating from Mar 27, 2014.  Let's
update that and see how the nightly job goes.

Travis: bump PyYAML pinned version to 3.13

---

avocado/utils/external/spark.py
selftests/checkall

There was an else on while without break. That has no meaning because
since while has no break, the else block will be always executed. This
change removes the else statement and keeps the block.
The pylint W0120 check was also enabled since now it's possible.
Reference: https://trello.com/c/Ohh7Q6qj
ps: the change doesn't seems too clear on Github diff.

Enable pylint w0120

---

avocado/utils/memory.py
selftests/unit/test_utils_memory.py

There is a pylint issue in the current utils.memory module. The
function get_buddy_info() makes use of eval()[1] what is
discouraged. In order to enable more pylint checkers, this eval()
call will be removed in a next PR. However, to minimize potential
problems considering that the change needed is not too small, this
current PR adds unit tests for the function.
It was also considered this change is valuable for the project as it is.
The tests was done mocking the real output of `/proc/buddyinfo`. To make
it easier the process to get the buddy info content was extracted for a
specific function that actually only wraps the open call. This way we
can mock this function return only instead of try mock the builtin open
function.
[1] - …

Adds unit tests for utils.memory.get_buddy_info v3

---

avocado/utils/iso9660.py
selftests/unit/test_utils_iso9660.py

This adds a capabilities selection mechanism for users of `avocado.utils.iso9660.iso9660` and ISO image creation support for the ISO9660PyCDLib backend.  More backends may add the same capabilities later.
---
Changes from v1 (#2756):
* Moved `content` variable outside of the for loop on `test_create_write`
* Rewritten capabilities tests, mocking the checks for external tools for better predictability

avocado.utils.iso9660: add capabilities and create/write [v2]

---

avocado/plugins/diff.py
avocado/plugins/replay.py
avocado/utils/filelock.py
avocado/utils/memory.py
contrib/scripts/avocado-find-unittests
contrib/scripts/avocado-get-job-results-dir.py
optional_plugins/runner_vm/avocado_runner_vm/__init__.py
selftests/checkall

This change enables W0150 (lost-exception) and W1645 (Exception.message
removed in Python 3) related to exception heandling.
This change also enables other checks that didn't require code changes
W0122, W0123, W0124, W0125.
Reference: https://trello.com/c/Ohh7Q6qj

Enable pylint exception related checks and more

---

avocado/utils/partition.py
selftests/unit/test_utils_partition.py

This deals better with situations where `lsof` is not available, or `kill` fails.
Changes from v3 (#2792):
* Added a `pylint: disable=W0622` do ignore the "redefinition" of `FileNotFoundError`
Changes from v2 (#2789):
* Fixed string formatting
* Treated `FileNotFoundError` exception and added alias on Python 2
* Added test for real behavior on systems without `lsof`
* Added test with mocked behavior for getting PIDs using mountpoint
Changes from v1 (#2769):
* Added unittest style change
* Added unittest classes refactor
* Refactor method to get pids
* Added error logging and exception raising on error conditions

avocado/utils/partition.py: do not blow up on systems with no lsof [v4]

---

avocado/utils/cloudinit.py
selftests/unit/test_utils_cloudinit.py

This addition to the utilities library facilitates the use of the
cloudinit features inside Linux OSs images for the cloud.
For now, it eases the creation of "cidata" ISOs, containing
configuration to cloud-init, and also a simple "phone home"
server.
---
Changes from v1 (#2795):
* Silent the PhoneHome Request Handler (so no output is sent to the STDERR, the default on the Python standard library)
* Added a test for the PhoneHome server

avocado.utils: introduce cloudinit module [v2]

---

selftests/unit/test_utils_cloudinit.py

Based on the discussion, it makes sense to have individual tests for
bad and good requests, and also one that shares the state among bad
and good requests.
---
Changes from v1 (#2797):
* Due to problems with Python 3.4 reusing the HTTP client, create and close the connection as part of the `post_ignore_response()` method

avocado.utils.cloudinit test improvements [v2]

---

avocado/plugins/human.py

Currently when a test fails I have to go dig through a very verbose log file with a fairly cumbersome path to see what went sideways. This slows down interactive development with avocado significantly. If the human UI also reports the test failure reason, it would streamline things quite a bit. This PR attempts to do that in a minimally invasive way.

add failure reason to human UI on failed tests

---

avocado/utils/vmimage.py

Users of the `avocado.utils.vmimage` API are currently exposed to differences in how some distros make images available.  For instance, Fedora has a "Fedora Secondary" directory for some architectures, but for users, it's just Fedora.
This attempts to hide those internal-only details and make the use more straightforward.
---
Changes from v1 (#2800):
* Fixed docstring on non-Base Fedora Image Provider

vmimage: use common arch and distro names [v2]

---

Makefile

The MAKEFILE variable name is misleading, given that it holds the
location of a possible PLUGIN directory.

Makefile: use better descriptive PLUGIN variable name

---

avocado/core/test.py

The current sysinfo end_test() hook is badly positioned, in a way that
it only gets called if no exception is raised (that is, tests end with
PASS).

Sysinfo: fix post collection on non-PASS tests

---

avocado/utils/vmimage.py
selftests/unit/test_utils_vmimage.py

First of all, a disclaimer: this is hackish.  But, it's the simplest
and thus best fix I could think of.
What happens here is that this module makes no distintcion between
what is a base class "abstract" class, and a concrete class.  With the
goal of reducing code duplication, a goal that will remain valid here
and in other modules, it made sense to create a common Fedora class.
Now, because only being a ImageProviderBase suffices, the
FedoraImageProviderBase class, which is not intended to be used as a
concrete (final) class, is being carried along and its "name" is
checked, causing crashes.
This introduces the ad-hoc, hackish, notion, that a concrete
ImageProvider is one that contains a name.
---
Changes from v1 (#2816):
* Removed one now …

avocado.utils.vmimage: differentiate against base and concrete classes [v2]

---

avocado/utils/distro.py

While running avocado in ubuntu system distro.detect().name has output
"unknown".  This is probably due to the removal of StdLibProbe.  Let's
add a proper Ubuntu probe.  Before this:
>>> distro.detect().version and distro.detect().release
0
>>> from avocado.utils import distro
>>> distro.detect().name
unknown
>>> distro.detect().version
0
>>> distro.detect().release
0
After this patch:
>>> from avocado.utils import distro
>>> print distro.detect().name
Ubuntu
>>> print distro.detect().version
18
>>> print distro.detect().release
04
Reported-by:   Kamalesh Babulal <kamalesh@linux.vnet.ibm.com>

avocado.utils.distro: introduce UbuntuProbe

---

avocado/utils/distro.py

Based on the distro module API, it should be possible to get the
version and release simply by providing a regex that has either one or
two groups.

avocado.utils.distro: simplify AmazonProbe

---

Makefile

The build directory of the main Avocado module is already cleaned by
the `clean` rule, but when plugins contain a build directory, they are
not currently cleaned.
Sometimes this leads to annoying `inspekt` failures, because previous
different versions of the plugin may be in the build directory, and
the error message only mentions the name of the module/class/method
violating the check, but not the exact file name.

Makefile: improve clean up of plugins

---

avocado/core/safeloader.py
selftests/.data/loader_instrumented/dont_crash.py
selftests/unit/test_loader.py

This PR contains first few commits of the recursive-by-default https://github.com/avocado-framework/avocado/pull/2768 PR and contains only some fixes and refactors to prepare for recursive-by-default.
v1: https://github.com/avocado-framework/avocado/pull/2773
v2: https://github.com/avocado-framework/avocado/pull/2774
v3: https://github.com/avocado-framework/avocado/pull/2828
```yaml
v2: Removed accidental fix of a typo (it's included later in the original PR along with selftest)
v3: Fixed the removed typo fix (Accidentally broke another line in v2)
v4: Modified the selftest to cope with abs vs. rel paths on py3 vs. py2
```

safeloader: Several cleanups and preps for "recursive-by-default" [v4]

---

avocado/core/loader.py
selftests/functional/test_basic.py

I was trying to use the external runner, in a reasonably simple way:
from within a project (QEMU) build dir, I'd run:
```
$ avocado run --external-runner=tests/qemu-iotests/check \
--external-runner-chdir=runner -- 001 002
```
But, what should work, did not.  The problem is with the non-absolute
path to the external runner, that is needed because we're changing
directories.
Absolute paths won't hurt otherwise (when no chdir is done), so it's
always done here.

External Runner: support relative paths given on the command line

---

avocado/utils/disk.py

added disk utility
1- get_disk_blocksize -- this function return block size of given disk(path)
2- get_disks -- this function return all disk present in system

Added new disk utility in  avcoado lib

---

scripts/avocado

I tend to favor more predictable and standard behavior, and the
currently used approach to "protect" the import of Python standard
libraries seems to me to be far from standard.
With this change, if the system's Python interpreter is broken, or if
Python standard libraries can not be imported/loaded, the default
behavior will be executed.  If it seems to be an Avocado problem, then
we try to print a line describing that.

scripts/avocado: use a more standard behavior on import failure

---

avocado/utils/linux_modules.py
selftests/__init__.py
selftests/unit/test_utils_cpu.py
selftests/unit/test_utils_linux_modules.py

Instead of executing `lsmod`.  Plus other fixes and improvements.

avocado.utils.linux_modules: use information from /proc/modules

---

avocado/utils/process.py
selftests/unit/test_utils_process.py

Let's provide the "__str__" method for "CmdError" to be able to see the
actual content on print(error).
v1: https://github.com/avocado-framework/avocado/pull/2678
v2: https://github.com/avocado-framework/avocado/pull/2840
Changes:
```yaml
v2: Use `%r` rather than decoding the outputs
v2: Slightly simplified output and commit message
v3: Add selftests
```

Provide "__str__" for "CmdError" [v3]

---

avocado/utils/download.py
avocado/utils/vmimage.py

On Python 3, the HTML parser expects text, so let's define the respective encoding on providers.

avocado.utils.vmimage: add encoding setting

---

avocado/utils/process.py
selftests/unit/test_utils_process.py

A large number of information being acquired by running external commands can be retrieved just as easily by reading files in `/proc`.
Let's use that approach instead.
---
Changes from v3 (#2846):
* Accommodate for command lines (`tcomm` fields) with spaces
Changes from v2 (#2845):
* Make `recent_mock()` utility common to selftests (new commit)
* Skipped `get_parent_pid()` test on old mock 
Changes from v1 (#2844):
* Open `/proc/*/stat` files explicitly in binary mode
* Added a test for `get_children_pids()`
* Rebased and removed commits not associated with this PR

avocado.utils.process: minimize the use of external commands [v4]

---

optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py
optional_plugins/varianter_yaml_to_mux/tests/.data/mux-selftest-using.yaml
optional_plugins/varianter_yaml_to_mux/tests/test_multiplex.py
optional_plugins/varianter_yaml_to_mux/tests/test_mux.py

With the goal of improving test coverage, documentation, and IMO, readability.
---
Changes from v1 (#2853):
* Use context manager style on `assertRaises`

Yaml to mux: unwind (unnest) some utility functions [v2]

---

optional_plugins/runner_remote/tests/test_remote.py
selftests/functional/test_replay_basic.py

There was a functional test on avocado that depended on remote plugin.
This change moves this test to proper plugin instead of run the test
only if the plugin is available during test execution.
Reference: https://trello.com/c/NPEUj0wZ

Moves remote test to proper plugin

---

optional_plugins/html/tests/test_html_result.py
selftests/functional/test_output.py

There was a functional test on avocado that depended on html plugin.
This change moves this test to proper plugin instead of run the test
only if the plugin is available during test execution.
Reference: https://trello.com/c/EVggIZzj

Moves html result test to proper plugin

---

avocado/utils/process.py
selftests/unit/test_utils_process.py

Seems that is important have a default way to get a process owner id in
process utils module. This function will be useful soon when we have to
deal with timeout of sudo enabled processes (explained in reference link).
This change is being added as suggested here: [#2854](https://github.com/avocado-framework/avocado/pull/2854/files#r219902574)
Reference: https://trello.com/c/ROPWdFFr

Adds function to return owner id of a process

---

avocado/utils/cloudinit.py

This improves the `avocado.utils.cloudinit` library, adding support for passing user only (password optional), enabling SSH authentication with the `root` user and key based authentication.
---
Changes from v1 (#2864):
* Fixed typo (`s/authorized_keys/authorized_key/`)

cloudinit: support for SSH key based authentication [v2]

---

avocado/core/safeloader.py
selftests/.data/loader_instrumented/double_import.py
selftests/unit/test_loader.py

Currently there is a typo and a bug. Let's fix the typo, add selftest to
document the current behavior and deal with the bug (should detect 4
classes) later.

safeloader: Fix typo in 'asname' and add selftest

---

avocado/core/safeloader.py
selftests/.data/loader_instrumented/double_import.py
selftests/unit/test_loader.py

This is a continuation (and a conclusion) of the hotfix in #2868.  I had imagined that the backport for the complete fix was not going to be easy, but it turned out to be straightforward.
---
This allows us to detect when someone imports avocado multiple times
with different names.
---
Changes from v1 (#2870):
* Removed unit test comment about behavior being broken (since this is a fix)

safeloader: Support "multiple import" with different name [v2]

---

avocado/utils/service.py

Fix issue: re.search(r"Loaded: loaded", output) failed
| TypeError: cannot use a string pattern on a bytes-like object
ID: 1632665
Signed-off-by: Sitong Liu <siliu@redhat.com>

Python 3: fix a byte-str issue of utils.service

---

avocado/utils/vmimage.py
selftests/unit/test_utils_vmimage.py

This change focus mostly on increasing tests for VmImageHtmlParser and
ImageProviderBase. During the tests implementation some improvements
were detected: the process of feed a html parser run both for get an
image version and image url was duplicated so it was unified in a single
method.
Besides that the process of get a best version for an image was put on a
specific method so each provider can override it if required. Today the
default rule for a best version is based on calling max() function on
found versions. However we can't assume it's the default for every
provider. As far as we know, for a possible OpenSuse provider in future
this rule will not be valid.
Reference: https://trello.com/c/vtM1SPpJ
---
Changes from v1 (#2879):
* …

vmimage: more tests for parser and base and minor improvements v2

---

avocado/utils/iso9660.py

When running privileged, MixInMntDir requires the "mixed in class" to
adhere to some expectations, including having a `path` attribute, and
unmounting the filesystem on `close()`.
It looks like this wasn't properly tested because of the seldom (if
any) privileged executions.

avocado.utils.iso9660: make proper use of MixInMntDir on ISO9660PyCDLib

---

avocado/utils/lv_utils.py
selftests/functional/test_lv_utils.py

The lv_utils functional tests, which usually don't run because
they require privileged execution, revealed a number of broken
expectations when it comes to bytes and text handling.
Let's fix both the module and the test.
---
Changes from v1 (#2891)
* Made regex pattern raw strings

avocado.utils.lvutils: fix bytes/text problems [v2]

---

avocado/core/job.py
avocado/core/runner.py
avocado/plugins/run.py
docs/source/TestParameters.rst
examples/tests/sleeptest.py
selftests/functional/test_basic.py

This adds support for passing parameters to test via non-varianter based plugins, and it's a core Avocado feature.
---
Changes from v1 (#2888):
* Rebased
* Fix typo (new commit)

Add core test parameter passing support (non-varianter based) [v2]

---

avocado/utils/software_manager.py

Currently on rhel based systems, if the name given for provides is
not part of package name itself, provides method return none.
We would have to handle situations where name is present in
filenames, this commit adds functionality of searching packages
based on filenames as well.
Signed-off-by: Srikanth Aithal <sraithal@linux.vnet.ibm.com>

Enhance provides package feature in softwaremanager

---

avocado/core/safeloader.py
selftests/unit/test_loader.py

This is an attempt to reduce the size and (my perceived) complexity of #2839, and consequently enable me to do a better review.  Because of the hotfixes that were already applied (PRs #2874, #2868), the amount of code that is really devoted to enabling recursive behavior by default is dropping - and this is another small step into that direction.
Also, the author @ldoktor recognizes that the those PR introduces some code duplication.  There's one commit here that attempts to do the opposite and be useful (verbatim or as inspiration) to the original PR. 
---
Changes from v2 (#2886):
* Removed commit `safeloader: add tests where INSTRUMENTED tests should not be found`, so now the title of this PR becomes misleading, because there are no picks from the original PR
Changes from v1 (#2875):
* …

recursive by default: picks from the complete PR [v3]

---

avocado/plugins/human.py

The 984424989c9f2fd229f8d589a40240a70dcc873e added fail-reason to UI,
but for some tests this could be multiple lines of explanation, which
does not really fit in the UI purpose. Let's limit the maximum size to
255 chars (this number is not important, it just have to be sensible)
and avoid '\n' in the output.

plugins.human: Avoid signaling too long fail-reasons in UI

---

avocado/utils/partition.py
selftests/unit/test_utils_partition.py

1. rewrite MtabLock, as a proxy class for filelock.FileLock.
2. update related unit test.

utils.partition: rewrite with filelock

---

avocado/utils/kernel.py

not passed while kernel download avocado error out as
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
when url not passed it uses default  else try to download url
after this patch
KernelBuild('4.4.133, None, /tmp/avocado_avocado.utils.kerneloVPgOZ')
>>> k = kernel.KernelBuild('4.4.133')
>>> k.download()
>>>
[praveen@localhost avocado]$ python
Python 2.7.14 (default, Mar 14 2018, 16:45:33)
[GCC 8.0.1 20180222 (Red Hat 8.0.1-0.16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from avocado.utils import kernel
>>> k = kernel.KernelBuild('4.4.133')
>>> k.download(url='https://git.kernel.org/torvalds/t/linux-4.19-rc6.tar.gz')
>>>
Reported-by:  lolyu <lolyu@redhat.com>

Fixed issue : address issue #2873 (kernel library)  as when url

---

avocado/core/runner.py
selftests/functional/test_basic.py

The correct name of the exception is TestAbortError, and not
TestAbortedError.

Runner: fix typo in exception name

---

avocado/utils/kernel.py
selftests/unit/test_utils_kernel.py

The current utils kernel module has no tests. Recently it was added a
fix[1] to the process of kernel url building. To keep this process
without future regressions, this change adds a proper test for it.
It's important to note that a new internal method was added to the
KernelBuild class to make easier to test it. Indirectly it's an
improvement of download method that now is shorter and more explicit.
[1] 
- commit c84ac6ba5eb892a54128e42649b9beb53fc1c20e 
- PR #2893 

Add tests for kernel download url building

---

.travis.yml
Makefile
selftests/checkall

The Makefile is used mostly on development related work flows, and has
up to know stick to Python 2 by default.  I think it's time to flip
the switch, and look for a Python 3 binary by default.

Default to Python 3 for development purposes

---

avocado/core/runner.py

When a test is interrupted, there is no reason it should get only 1 second to do it's
cleanup when we otherwise give a test 10 seconds to clean up if it just dies.
Fixes: 2908
Signed-off-by: Brian J. Murrell <brian@interlinx.bc.ca>

Allow an interrupted test 60s to clean up

---

avocado/core/loader.py
avocado/core/output.py
avocado/core/restclient/connection.py
avocado/core/restclient/response.py
avocado/core/result.py
avocado/core/settings.py
avocado/utils/archive.py
avocado/utils/external/gdbmi_parser.py
avocado/utils/gdb.py
avocado/utils/genio.py
avocado/utils/iso9660.py
avocado/utils/lv_utils.py
avocado/utils/memory.py
examples/tests/cancelonsetup.py
examples/tests/passtest.py
optional_plugins/html/avocado_result_html/__init__.py
optional_plugins/runner_docker/avocado_runner_docker/__init__.py
optional_plugins/runner_remote/avocado_runner_remote/__init__.py
optional_plugins/runner_vm/avocado_runner_vm/__init__.py
requirements-selftests.txt
selftests/functional/test_output.py

The newly released pylint version 2.2.0, changed its default behavior
(enabled) the following checks:
* :unnecessary-pass (W0107): *Unnecessary pass statement*
Used when a "pass" statement that can be avoided is encountered.
* :unused-import (W0611): *Unused %s*
Used when an imported module or variable is not used.
Let's apply fixes to those checks, and at the same time, pin the
pylint version so that our CI environment is more stable (code that
test our code -- pylint -- doesn't change, while our code changes).

Selftests: respect pylint 2.2.0 checks

---

avocado/core/job.py
selftests/unit/test_job.py

Just a collection of small, internal changes.
The reason for those are, that eventually (maybe sooner than later) we want to make the Job API public, so it makes sense to think of the private/public parts and even internal attribute names.

Job: internal changes

---

selftests/checkall

On 03d81feada, we let the Avocado developer choose the Python version
to use by setting a PYTHON variable that gets passed to `make`
commands.
But, we missed the case when the execution of the selftests is not
done in parallel.

Respect Python versions on non-parallel selftests

---

avocado/plugins/xunit.py
selftests/unit/test_xunit.py

Currently we use "avocado" as a suite name, let's use job-dir which is
quite useful when matching xml results to output directories.
Note I considered using uid, which is available directly in `results`, but the job-dir seems better.
@brianjmurrell any suggestions?

plugins.xunit: Use job-dir-name as name

---

Makefile

Some distros don't create `/bin/python` and only ship with
`/bin/python2` or `/bin/python3`.  As we are already detecting
`python3` let's also look for `python2` explicitly.
Also, let's fallback to unversioned `python` if no other is found, as
unlikely as it may be.

Makefile: also check for Python 2 explicitly

---

selftests/unit/test_utils_partition.py

The "avocado.util.partition" selftests will only run when the right environment is preset, that is, you run them as privileged users that can do partition and filesystem operations.  For this reason, they're not always executed on developer environments (that's true for my own).
When trying to run them in suitable environment, I found some issues described and fixed in the individual commits.

avocado.utils.partition selftests fixes

---

avocado/utils/lv_utils.py
avocado/utils/partition.py
selftests/unit/test_utils_partition.py

Both when writing to mountpoint, using a Python interpreter, and when
trying to listing open files during a forceful unmount of the disk.

selftests/unit/test_utils_partition.py: use sudo

---

python-avocado.spec

There are a number of backends and requirements for iso9660 tests
to run.  Let's add those as build requirements to that as many
as possible tests and code paths get executed during the checks
in the RPM build.  With this, two other test cases get executed:
Before:
- (Python 2): Ran 600 tests in 198.076s OK (skipped=42)
- (Python 3): Ran 600 tests in 196.489s OK (skipped=45)
After:
- (Python 2): Ran 600 tests in 180.514s OK (skipped=40)
- (Python 3): Ran 600 tests in 188.545s OK (skipped=43)
---
Changes from v1 (#2936):
* Moved requirements to the the "with_tests" conditional block, as they're only used on tests (@mmathesius)

SPEC: add build requirements so that tests for iso9660 gets run [v2]

---

.travis.yml

According to the references given below, Travis workers now run
on VMs that are sudo capable, and the sudo configuration should
now be removed.
Reference: https://docs.travis-ci.com/user/reference/overview/
Reference: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

Travis-CI: remove sudo configuration

---

selftests/__init__.py
selftests/checkall
selftests/functional/test_basic.py
selftests/list
selftests/run

There are currently two ways of running unittests:
* Using an "almost-vanilla" unittest runner, in non-parallel mode (`selftests/run`)
* Using shell code (`parallel_selftests` in `selftests/checkall`)
But the list of tests is obtained in two different ways.
Also, because an AST based tool is being used to find unittests, other constraints are put on some of the tests.  Let's add symmetry to the test suite, no matter how it's executed.

Selftests: converge execution to the same tests

---

avocado/core/job.py
avocado/plugins/run.py
selftests/functional/test_basic.py
selftests/unit/test_job.py

In an effort to make jobs more self contained, and given that dry-run
jobs created temporary content that is not supposed to be kept after
the job is run, this introduces the following changes:
* Jobs with "dry-run" enabled will now, by default, cleanup their
own data.  Basically, this means that the "base log directory"
created during job initialization, and that for non "dry-run"
jobs is usually "~/avocado/job-results", will also be removed
at the job's "cleanup()" phase.
* A new "--dry-run-no-cleanup" command line option, that only makes
sense when jobs with dry-run enabled start to clean up data for
themselves
* Because some result plugins will, by default, write to the job
results directory, results plugins are now run before a job cleanup
is done.
Signed-off-by: Cleber Rosa …

Job: clean up "dry-run" jobs by default [v2]

---

selftests/unit/test_utils_iso9660.py

This is basically about the simplification of the ISO9660 selftests, removing the techniques previously used to make sure tests were found and properly run on the previous unittest execution model.

Iso9660: selftests improvements

---

avocado/utils/iso9660.py
avocado/utils/path.py
selftests/unit/test_utils_path.py

It's a common use case to want to make sure a file can be read, or if
not fail as early as possible with a relevant error message.
The avocado.utils.iso9600 is doing that itself, but for the sake of
being useful to a wider audience, let's make that a utility itself.
As always, the benefits are also increased test coverage and
documentation.

avocado.utils.path: introduce check_readable()

---

avocado/core/result.py
selftests/unit/test_result.py

Currently to generate the HTML report the success rate of a test result
is computed by the plugin itself[1]. Since this is an information about the
test result it should be calculated by the Result object and no anywhere
else.
This change adds the rate property to Result class according with the
code (method) already in place in HTML plugin. This new property will be
used soon when the new template engine be added to HTML plugin.
[1] - https://github.com/avocado-framework/avocado/blob/master/optional_plugins/html/avocado_result_html/__init__.py#L84
---
Changes from v1 #2950 
* Normalize the new rate property to always return float type

Add rate to result v2

---

avocado/utils/process.py
selftests/unit/test_utils_process.py

Actually I already found out the https://github.com/avocado-framework/avocado/pull/2945 implementation is broken and can lead to zombie invasion...
v1: https://github.com/avocado-framework/avocado/pull/2954
v2: https://github.com/avocado-framework/avocado/pull/2956
Changes:
```yaml
v2: Add selftest for return value and check for it in existing tests
v3: Reorganized killed_pids list
v3: Improved docstring
```

 Avoid zombie invasion [v3]

---

avocado/utils/genio.py
selftests/unit/test_utils_genio.py

Added utility which takes as argument a file and pattern
and return true or false respectively when pattern matches in
file or not
```
>>> from avocado.utils import genio
>>> genio.check_pattern_in_file("/home/praveen/file1", "praveen")
True
>>> genio.check_pattern_in_file("/home/praveen/file1", "Praveen")
False
>>> genio.check_pattern_in_file("/home/praveen/file12", "Praveen")
File "avocado/utils/genio.py", line 219, in find_pattern
% (filename, pattern))
avocado.utils.genio.GenIOError: invalid file /home/praveen/file12 to match pattern Praveen
```
This work started with Praveen contribution (#2837) and I've just
continued with some adjustments.
---
Changes from v2 (#2963)
* Fix broken tests because of function …

utils.genio: Creates function to match pattern in file [v3] 

---

avocado/core/loader.py
avocado/core/safeloader.py
selftests/unit/test_loader.py
selftests/unit/test_safeloader.py

A use case that has appeared is to give more meaning to tags, for instance, to tag a test as being capable of running (or requiring) a given CPU architecture.  Right now, only "flat" tags, with common meaning are possible.
This includes a change of the internal format used to keep track of tags, so that it will be possible to add different values to a tag with the same key.  This would be valid for a test that say, can work on both `x86_64` and `ppc64`, so those values would live under a `arch` key.
The user facing behavior at this point should not have been changed by this.

Tags: prep work for the support of key:val

---

avocado/core/loader.py
selftests/unit/test_loader.py

Just like #2965, this contains a number of new tests and refactors in preparation for the support of key:val tags.
The description on #2965 also applies here:
---
A use case that has appeared is to give more meaning to tags, for instance, to tag a test as being capable of running (or requiring) a given CPU architecture. Right now, only "flat" tags, with common meaning are possible.
This includes a change of the internal format used to keep track of tags, so that it will be possible to add different values to a tag with the same key. This would be valid for a test that say, can work on both x86_64 and ppc64, so those values would live under a arch key.
The user facing behavior at this point should not have been changed by this.
---

Tags: more prep work for the support of key:val

---

avocado/core/job.py
avocado/core/loader.py
avocado/plugins/list.py
avocado/plugins/run.py
docs/source/WritingTests.rst
selftests/unit/test_loader.py

Up to this point, the matching and thus filtering of tags was flat.
Now, the individual value of the required keys are checked.
For instance, if you have a test such as:
class My(Test):
def test(self):
"""
:avocado: tags=classification:tier1
"""
...
Both of these filter conditions will match:
$ avocado run -t classification test.py
$ avocado run -t classification:tier1 test.py
But this won't match:
$ avocado run -t classification:tier2 test.py
Also, similarly to the how there's support for including tests that
have no tags at all, there's support for including tests that are
not tagged with a specific keys.

Tags: add support for tag key/val match

---

avocado/core/loader.py
avocado/core/test.py

On some situations, the same information may be given on tags that can
be reused during test runtime.  Let's create a property to allow a
test to read them.

Tags: make tags available to tests as a property

---

avocado/utils/network.py
python-avocado.spec
requirements-selftests.txt
selftests/unit/test_utils_network.py

Hello guys, it took me quite long to find out our is_port_free function is seriously insufficient (first I blamed qemu, but it's us). The first commit fixes the issue where ipv4 address is already freed, but ipv6 address is still occupied, the second commit makes sure we don't allow using port that is already used by UDP (not sure why but at least on my system it allows that without complaint). Third replaces "localhost" with "", because on "localhost" python binds only to 127.0.0.1/::1 but on "" it binds to all localhost interfaces (like 192.168.122.1, ...), which is commonly used by programs and we were not detectin these. After that follows fixes and optimization.
PS: This (hopefully) fixes (or at least decreases probability) very rare Avocado-vt migration issue where ports are not …

Improve is_port_free [v2]

---

optional_plugins/html/MANIFEST.in

Without this, the data files associated with the avocado_result_html
module won't be installed.

HTML Plugin: update the new data directory name

---

avocado/utils/service.py
selftests/unit/test_utils_service.py

for result parser functions, enforce all strings to be of bytes.

utils.service: enforce uniform string type

---

CONTRIBUTING.rst

Common location for contributing guidelines is "./CONTRIBUTING*" and
even github encourages us to use it. Let's symlink our documentation to
simplify first-time contributions (and also to make github happier).

Add link to our documentation about contibuting guidelines

---

avocado/plugins/xunit.py
selftests/unit/test_xunit.py

Any xUnit XML file when used to import test results in Jenkins CI
must comply to Ant and Maven's xUnit format specification. From
Jenkins' xUnit version 2.0 and up, the floating-point representation
of 'time' attribute should match Maven's surefire format
that restricts the use of at most 3 decimal places. But the Avocado's
xUnit plugin renders the 'time' attribute with several decimal places,
resulting in error to the load results.xml in Jenkins.
This change solves that problem by ensuring that the 'time' attribute
in Avocado's results.xml file is formatted with 3 decimal places.

plugins.xunit: Format 'time' with 3 decimal places

---

avocado/utils/cpu.py

This change adds a new utility function that receives a process id and
returns all processors (id) being used by the process (and its threads)
informed.
This work started with Praveen contributions (#2841) and I've just
continued with some adjustments.
---
Changes from v1 (#2989):
- Backward access cpu id to not cause misleading reading because
whitespaces in process name

utils.cpu: adds function to get cpus used by process [v2]

---

docs/source/optional_plugins/varianter_cit.rst

According to the author of the publication, the authoritative source,
we were using an incorrect URL to the publication that backs the CIT
implementation.  Let's fix that.

CIT Plugin: update location of relevant publication

---

avocado/utils/memory.py

1. read directly from /proc/meminfo.
2. improve the regex to get more accurate result.

improve avocado.utils.memory.read_from_meminfo

---

optional_plugins/varianter_yaml_to_mux/setup.py

This changes addresses the CVE-2017-18342[1] that defines: "In PyYAML
before 4.1, the yaml.load() API could execute arbitrary code. In other
words, yaml.safe_load is not used."
The change affects only installation using Python 3 because when
building EL7 RPMs, we want to use version 3.10, which is packaged on
EPEL.
[1] - https://nvd.nist.gov/vuln/detail/CVE-2017-18342
---
Changes from v2 (#2992)
* Adjust PyYAML version definition for Python 2 because rpm building
Changes from v1 (#2990)
* Apply the PyYAML version bump only for Python 3 installation

yaml_to_mux: bump pyyaml version [v3]

---

optional_plugins/robot/avocado_robot/__init__.py

When the Robot Framework finds an issue worthwhile to be shown on
the UI, it will do so, but that confuses Avocado users by mixing
the content from both layers.
Let's disable the Robot framework console logger, and only shown
the messages we intend to.

Robot plugin: silence output in the console

---

avocado/core/data_dir.py
avocado/utils/path.py
selftests/unit/test_datadir.py

If one is running avocado as a privileged user, the "usable_ro_dir()"
function may create a system wide directory for hosting tests.  That's
confusing because, the following workflow is possible:
1) Regular user creates test, say "foo.py" in his own test dir
2) Privileged user run "avocado run does_not_exist.py", which by
means of "usable_ro_dir()", may create a system wide location
for tests.
3) Regular user runs "avocado run foo.py", and then test is not found
because "avocado.core.data_dir.get_test_dir()" gives precedence to
the system test dir created earlier.
This is also a problem when running the selftests from within the
tree, when working as a privileged user.  And finally, as a general
rule, we should avoid creating directories in system-wide locations so
silently, so I do …

Tests' directory: don't create system wide directory [v2]

---

examples/tests/assert.py
selftests/functional/test_basic.py
selftests/functional/test_loader.py

Based on some reports of failures to behave properly on
unittest.TestCase's assertRaises methods, let's improve the test
coverage on these situations.
References: https://github.com/avocado-framework/avocado/issues/2791

Unittest compatibility: test assertRaises()

---

.copr/Makefile

This adds a Makefile that adds support for the Fedora COPR service to
build packages for Avocado, right out of a Git repo.  To do so, create
your project, and in "Builds" tab, select "New Build".
On "1. Select source type" section, select "SCM".  On section
"2. Provide the source", under "Clone url" add the URL of your repo.
For instance, this has been tested with:
https://github.com/clebergnu/avocado
Under "Committish", enter a reference to a given commit.  For instance, this
has been tested with the name of this branch: "copr_makefile".
Under "3. How to build SRPM from the source", select "make srpm".
Finally, select the appropriate Chroots.  It's better not to have
"Enable internet access during this build" option checked.
Finally, it's advisable to not attempt to run this Makefile …

COPR SCM/"make srpm" support

---

optional_plugins/varianter_yaml_to_mux/setup.py
python-avocado.spec
selftests/unit/test_utils_vmimage.py

During some experiments with builds on COPR (), the two different build issues appeared.
For the first one, it affected Fedora 28 builds.  This build includes the first commit only:
https://copr.fedorainfracloud.org/coprs/cleber/avocado-copr-test/build/851713/
The second was related to builds happening on ppc64le.  The following COPR build includes both commits and includes ppc64le chroots:
https://copr.fedorainfracloud.org/coprs/cleber/avocado-copr-test/build/851721/

RPM build fixes (revealed by COPR builds) 

---

avocado/utils/ssh.py

The master connection is not currently being initialized properly due to the lack of the control path configuration is missing.

avocado.utils.ssh: fixes for the master connection

---

avocado/core/runner.py

The first commit fixes issue where:
avocado --show all run sleeptenmin.py --mux-inject /run:timeout:1
always reported unfinished test process even though it finished properly. The second commit is a simple pylint-fix.

runner: Fix deadline evaluation

---

python-avocado.spec

Starting with Fedora 30, only a minimal set of language packs are
installed on build roots, and consequently available during the build
of packages.
Some of the Avocado tests use varied locale settings, so we need the
full language packs installed.
Reference: https://github.com/avocado-framework/avocado/issues/2978
Refernece: https://fedoraproject.org/wiki/Changes/Remove_glibc-langpacks-all_from_buildroot

Fix RPM build on Fedora >= 30

---

avocado/plugins/xunit.py
man/avocado.rst

Recently we modified the reported xunit job name to match the avocado
job name, but this breaks the Jenkins feature that detects first failure
as it only evaluates results of the same job name. Let's allow to set
this value so people can have multiple results easily comparable.
v1: https://github.com/avocado-framework/avocado/pull/3010
Changes:
```yaml
v2: Renamed variable "override_job_name" to "job_name"
v2: Added "man" entry
```

plugins.xunit: Allow to override job-name

---

avocado/utils/process.py
selftests/unit/test_utils_process.py

This series is inspired by a real bug where "process.run(..., timeout=something)" hangs for infinity. While on it I moved the timeout handling to wait instead of run as I always wanted to do so, then fix for the hang followed by improved killing mechanism are added. Last commit is just finishing touch that might improve the reported message.
v1: https://github.com/avocado-framework/avocado/pull/3005
v2: https://github.com/avocado-framework/avocado/pull/3017
Changes:
```yaml
v2: Adjust docstrings accordingly to the changes
v2: Style-fixes in selftests
v2: Skip one new selftest in travis and the other in both RPM and travis environments
v3: Log warning/error when killing process with non-default signal
```

 utils.process: Avoid hangs when timeouts are specified [v3]

---

avocado/utils/archive.py

fix that opens compressed file in binary instead of text mode.

utils.archive.extract_lzma: open in binary

---

python-avocado.spec

python2-resultsdb_api package has been removed in F30 so
python2-avocado-plugins-resultsdb was also disabled.
This is a "manual" cherry-pick from Merlin Mathesius' work, picked
after the COPR build started failing on rawhide.
CC: Merlin Mathesius <mmathesi@redhat.com>
Reference: https://src.fedoraproject.org/fork/merlinm/rpms/python-avocado/c/fa2eeb5c8a92bb788adf7288b882bcd2f5086cb1?branch=latest
Reference: https://copr-be.cloud.fedoraproject.org/results/@avocado/avocado-latest/fedora-rawhide-x86_64/00854194-python-avocado/builder-live.log

SPEC: remove Python 2 version of resultsdb plugin on Fedora >= 30

---

selftests/functional/test_basic.py
selftests/functional/test_interrupt.py

Recently we fixed bug where timeouts were not kept under certain
conditions, but the fix lacked selftests modification of those 2
affected selftests as they rely on test-postprocess timing.
@cacarrara, please adjust your merge workflow to prevent such breakages as `make check` should catch these https://avocado-framework.readthedocs.io/en/67.0/ContributionGuide.html#code-review
PS: It wasn't on purpose, I just ran only a subset when polishing the commits and today when rebasing I found out `make check` is failing...

selftests: Fix timeouts

---

avocado/core/safeloader.py
selftests/.data/loader_instrumented/dont_detect_non_avocado.py
selftests/.data/loader_instrumented/imports.py
selftests/.data/loader_instrumented/infinite_recurse.py
selftests/.data/loader_instrumented/parent1.py
selftests/.data/loader_instrumented/parent4.py
selftests/.data/loader_instrumented/parent7.py
selftests/.data/loader_instrumented/parent9.py
selftests/.data/loader_instrumented/path/parent10.py
selftests/.data/loader_instrumented/path/parent2.py
selftests/.data/loader_instrumented/path/parent3.py
selftests/.data/loader_instrumented/path/parent5.py
selftests/.data/loader_instrumented/path/parent6.py
selftests/.data/loader_instrumented/path/parent8.py
selftests/unit/test_loader.py
selftests/unit/test_safeloader.py

This PR shuffles the loader code quite a lot to allow recursive discovery by default. It keeps the current implementation, therefor on "disable" and "enable" it simply proceeds to discover the class, only remembers whether it seen such tag (as it means it is "avocado.Test" no matter whether it really is).
I have not updated documentation yet, please let me know whether this is acceptable and then I'll include documentation fixes.
v1: https://github.com/avocado-framework/avocado/pull/2687
v2: https://github.com/avocado-framework/avocado/pull/2768
v3: https://github.com/avocado-framework/avocado/pull/2839
v3b: https://github.com/avocado-framework/avocado/pull/3008
Changes:
```yaml
v2: rebased (which resulted in all code being in safeloader rather than loader)
v3: rebased (several commits …
```

Recursive rework4 with cleber

---

docs/source/conf.py
selftests/doc/test_doc_build.py

This test was always skipped due to different urllib handling in
python3. Let's use our download library to check the connectivity.

selftests: Fix python3 compatibility

---

docs/source/SubclassingAvocado.rst
docs/source/WritingTests.rst
docs/source/release_notes/51_0.rst
docs/source/release_notes/lts/52_0.rst
docs/source/release_notes/lts/next.rst

We recently switched from simple to recursive discovery by default,
let's document how the discovery works now.
This is related to https://github.com/avocado-framework/avocado/pull/3024

docs: Document the current recursive discovery

---

python-avocado.spec

This is a follow-up to #3022 -- which was cherry-picked from my downstream work. Unfortunately, the scattered SPEC file conditionals from that really hurts the eyes and brain, so I cleaned it up by setting and using a global variable. This PR provides no different functionality, it's just easier to read and understand what's going on.

SPEC file cleanup related to python2-resultsdb_api removal in F30

---

examples/testplans/release.json

Instead of, now, re-building the packages locally. The COPR repo already builds them for different distros and on two architectures.
---
Changes from v1 (#3029):
* Squashed the first two commits
* Added a commit about the `rpmlint` step

Release test plan: use the Avocado COPR repo

---

avocado/core/safeloader.py

Safeloader is supposed to keep the order of the classes and methods as
they're present on the source code file.  When not using a ordered
dict as an data structure, we count on pure luck.
This addresses the failure of the test_dont_detect_non_avocado test on
unit.test_loader.TestLoader.

Safeloader: return an ordered dictionary

---

avocado/core/dispatcher.py
avocado/core/job.py
avocado/core/plugin_interfaces.py
avocado/core/settings.py
avocado/plugins/config.py
docs/source/Configuration.rst

This PR fixes several issues in "avocado.core.settings" and on top adds plugin to allow to extend/modify the list of config-file locations to be parsed into settings. This plugin is to be used by Avocado-vt (and hopefully other plugins will follow) to clearly define their config files.
v1: https://github.com/avocado-framework/avocado/pull/2780
related: https://github.com/avocado-framework/avocado-vt/pull/1142
Changes:
```yaml
v2: Use ExtensionManager instead of EnabledExtensionManager
v2: New commit with style fixes
v2: Added documentation in "settings: Change the way config files are processed" and
"Add support for SettingsPlugin".
```

Several "settings" fixes and plugin to allow setting/modifying config file paths

---

avocado/plugins/xunit.py
selftests/unit/test_xunit.py

Finally I found the reason why some of my logs were present while others were not....

plugins.xunit: Record log when fits the xunit limit

---

selftests/functional/test_utils.py

The fake-vmstat process should run for infinity. Using wait with 1s
timeout will eventually destroy the test after the timeout, but cleaner
solution is to explicitly terminate it and then use the wait to make
sure it finished (or eventually nuke it)
introduced in: https://github.com/avocado-framework/avocado/pull/3036

selftests: Kill the process before waiting

---

selftests/unit/test_utils_network.py

netifaces is an external library, that is not trivially installable by
pip (requires a C compiler).  Let's make the test conditional to the
presence of the netifaces library.

test_utils_network.py: skip test when netifaces is not available

---

selftests/checkall

In the parallel execution, not honoring the Python version used
elsewhere may cause unexpected issues.  One is an error situation in
which Python 3's unittest.loader can not load an exception definition
that exists only Python 2.

selftests: use the proper Python version when listing tests

---

avocado/core/test.py
selftests/functional/test_basic.py

Each test has its own log file within a given job result dir,
located at "test-results/$(test-id)/debug.log".
If the test is an INSTRUMENTED test, using the standard Python logging
module/API, all produced content should be recorded into the test log
file.  This adds a handler that does exactly that to the logging
module root logger.

Record all logged messages during test run into the test log

---

avocado/plugins/jsonresult.py

Instead of a stringified version of Python's version of null,
that is, "None".
The generated JSON file is consumed by the remote test runner,
and given that the failure reason is a valid string, it's shown
in the Human UI.
Reference: https://trello.com/c/ihTDNdov/1472-bug-remote-vm-runner-prints-none-on-pass-results

JSON Result: store possible empty fail_reason as null

---

selftests/deployment/README
selftests/deployment/pip-git.yml
selftests/deployment/rpm-copr.yml
selftests/deployment/tasks/avocado_copr_repo.yml
selftests/deployment/tasks/avocado_vt_copr_repo.yml
selftests/deployment/tasks/avocado_vt_rpm_pkgs.yml
selftests/deployment/tasks/epel.yml
selftests/deployment/tasks/python_rpm_pkgs.yml
selftests/deployment/tasks/virtualenv_script.yml

This updates the playbooks to check the deployment on Fedora 29, and adds Avocado-VT deployment checks, given that it's a very important plugin and checks the plugin interfaces of Avocado itself.

Deployment checks: update playbook to Fedora 29 and add Avocado-VT

---

avocado/core/job.py

The log files produced for the root logger are confused with hidden
files (.INFO, .DEBUG, .WARN, .ERROR) because the root logger's name
is an empty string.

Use more appropriate default name for the stored root logger stream

---

requirements-selftests.txt

The pylint version in use requires a specific version (or a not
so greater version) of astroid.  When the astroid version is not
pinned, astroid version 2.2.4 currently gets installed.
Then, pylint (and thus inspektor) fails with:
'Import' object has no attribute 'infer_name_module'
Let's bump the pylint version (already pinned) and pin a compatible
astroid version too.

Selftests: pin pylint and astroid version

---

requirements-selftests.txt

The pylint version in use requires a specific version (or a not
so greater version) of astroid.  When the astroid version is not
pinned, astroid version 2.2.4 currently gets installed.
Then, pylint (and thus inspektor) fails with:
'Import' object has no attribute 'infer_name_module'
Let's bump the pylint version (already pinned) and pin a compatible
astroid version too.

[LTS] Selftests: pin pylint and astroid version

---

.travis.yml

This basically means that any pushes to the 69lts branch will also
generate a new Travis CI job.

[LTS] Travis CI: add 69lts to the list of branches to be checked

---

.travis.yml

This basically means that any pushes to the 69lts branch will also
generate a new Travis CI job.

Travis CI: add 69lts to the list of branches to be checked

---

.travis.yml

So that we can start testing newer Python versions and more
up to date platforms.

Travis CI: bump distro from Trusty to Xenial

---

README.rst
docs/source/GetStartedGuide.rst

The "avocado-latest" Copr repo currently points to packages that are
built with the latest master branch.  Now, there's also a
"avocado-latest-lts" Copr repo, which points to the "latest state of
the latest LTS" branch, which means, the 69lts branch.
So, if a fix makes its way to 69lts, and users want that fix before a
minor version is released, they'd find that fix in the packages
generated from this repo.

[LTS] Docs: add link to LTS version of the Copr repo

---

avocado/utils/vmimage.py

The build of a given image, when given to avocado.utils.vmimage.get()
is incorrectly being assigned the same version number.

avocado/utils/vmimage.py: fix build usage

---

avocado/utils/vmimage.py

The build of a given image, when given to avocado.utils.vmimage.get()
is incorrectly being assigned the same version number.

[LTS] avocado/utils/vmimage.py: fix build usage

---

Makefile
avocado/core/settings.py
avocado/utils/astring.py
avocado/utils/process.py
avocado/utils/software_manager.py
docs/Makefile
docs/source/Configuration.rst
optional_plugins/varianter_cit/tests/test_functional.py
selftests/functional/test_basic.py
selftests/functional/test_loader.py
selftests/functional/test_standalone.py
selftests/unit/test_astring.py
selftests/unit/test_utils_disk.py

Even though explicit Python 2 support was dropped, there are still some leftovers, unneeded code to accommodate it.
Let's clean those up.

Python 2 leftovers

---

avocado/utils/distro.py

fixed redhat distro version check in Rhel8.0
/etc/redhat-release output pattern changed
cat /etc/redhat-release
Red Hat Enterprise Linux release 8.0 Beta (Ootpa)
changed regex pattern which handle Rhel8 case as well

Fixed issue in avocado.utils.distro

---

docs/source/OtherResources.rst
docs/source/optional_plugins/azure.rst
docs/source/optional_plugins/index.rst

Because of deprecation according to author.
Reference: https://github.com/avocado-framework/avocado/issues/3074

Docs: remove mention of azure plugin

---

avocado/core/dispatcher.py
avocado/core/settings.py
avocado/core/settings_dispatcher.py

This avoids the circular import that was originally a problem, and
removes the "weird" SettingsDispatcher assignment to itself, while
still adding documentation to keep this and the other dispatchers
"linked".
Reference: https://github.com/avocado-framework/avocado/issues/3065

Settings Dispatcher: move it to its own module

---

selftests/__init__.py
selftests/unit/test_utils_cpu.py
selftests/unit/test_utils_disk.py
selftests/unit/test_utils_linux_modules.py
selftests/unit/test_utils_process.py

When the recent_mock() utility was introduced, I may have missed the
fact that it would be possible to mock builtins.open().  Or, it may
be that was only possible in Python 3.
Anyway, now that we only support Python 3, let's just mock
builtins.open() and drop this custom decorator.

Selftests: use builtins.open for mock

---

avocado/utils/distro.py
avocado/utils/genio.py

backport code   #3078  and  #3081 to 69lts
1- Added append_file, append_one_line functions to genio.
There are situations where files with more than one line
are to be created with some filtered data. In those
situations, the existing functions namely write_file,
write_one_line are not helping.
Signed-off-by: Nageswara R Sastry <rnsastry@linux.vnet.ibm.com>
2- fixed redhat distro version check in Rhel8.0
/etc/redhat-release output pattern changed
cat /etc/redhat-release
Red Hat Enterprise Linux release 8.0 Beta (Ootpa)
changed regex pattern which handle Rhel8 case as well

backport code   #3078  and  #3081 to 69lts

---

avocado/core/safeloader.py
selftests/unit/test_loader.py

A "from <module> import <symbol>" statement will not always have
a module name set, one example is:
from . import BASEDIR
In these situations, the statement's module attribute will be None.

Safeloader: handle add_import_object ImportFrom alias statement

---

avocado/core/safeloader.py
selftests/unit/test_loader.py

A "from <module> import <symbol>" statement will not always have
a module name set, one example is:
from . import BASEDIR
In these situations, the statement's module attribute will be None.

[LTS] Safeloader: handle add_import_object ImportFrom alias statement

---

avocado/core/safeloader.py
selftests/unit/test_safeloader.py

This does a number of refactors to the safeloader, with the goal of simplifying the code, reducing duplication and preparing for further changes.
---
Changes from v1 (#3097):
* Fixed docstring typo (`s/module/klass`) - spotted by @PraveenPenguin

Safeloader: refactor [v2]

---

selftests/unit/test_safeloader.py
selftests/unit/test_utils_service.py

The `test_utils_service.py` file uses a more complex than necessary inheritance approach and a static method, while a single utility function is necessary.  The `test_safeloader.py` change is simpler and just puts one of the tests in a class that doesn't require the previous one's setup.

Selftests: increase granularity and simplify inheritance approach

---

avocado/core/loader.py
avocado/core/safeloader.py
contrib/scripts/avocado-find-unittests
selftests/.data/loader_instrumented/dont_detect_non_avocado.py
selftests/unit/test_loader.py
selftests/unit/test_safeloader.py

This adds another round of refactors to the safeloader module, but on top of it, it implements a much improved function for finding Python unittests.
Even with two rounds of refactors (this PR and #3099), I must say there's still some code duplication and optimization opportunities.
Anyway, this brings a foundation in which it will be possible to switch Avocado's own test execution to a new experimental runner.

Safeloader: improve Python unittest support

---

.travis.yml
selftests/signedoff-check.sh

For a long time we have resorted to a hack, let's call it "all commits
hack", to test all commits in a branch on Travis-CI.  While it clear
had a positive side, it also had its annoyances.
Now, more and more often, we're faced with the obligation of breaking
PRs in smaller pieces just because of the limitations that the free
tier of Travis-CI imposes (for instance max job time is 50 minutes).
For instance, as this is written, the status of the master branch
is broken, because of the max job time.  And there's no way to
waive it or tweak it.
Also, the hack caused some really interesting problems, and caused
a lot of time wasted, for instance, because it masks the merge commit
that Travis-CI creates, and consequently, makes the signedoff-check.sh
fail on the real HEAD of the merged branch. …

Travis-CI: check the HEAD of the branch only

---

optional_plugins/html/avocado_result_html/__init__.py

Current 'None' evaluates as string where 'None' is not None.

Use proper default option if no html_output option was provided

---

selftests/modules-boundaries.sh

This shell script can not actually be used with non-bash sheels.  This
only manifests on some environments where /bin/sh is not bash, and the
exact outcome is similar to:
* Checking for avocado.core imports from examples/tests: selftests/modules-boundaries.sh: 9: selftests/modules-boundaries.sh: RESULT: not found
0
* Checking for non-relative avocado imports from avocado/core: selftests/modules-boundaries.sh: 20: selftests/modules-boundaries.sh: RESULT: not found
0
* Checking for avocado imports from avocado/utils: selftests/modules-boundaries.sh: 31: selftests/modules-boundaries.sh: RESULT: not found
0
PASS: no module boundary infringement(s) found

selftests/modules-boundaries.sh: use bash as interpreter

---

examples/tests/cit_parameters.py
optional_plugins/varianter_cit/avocado_varianter_cit/__init__.py
optional_plugins/varianter_cit/tests/test_functional.py

The data type expected to be given to each yield variant contains the
variant id, the "variant" itself, which should be a list of
TreeNode-like instances, and finally the applicable default search
paths.
The "variant" itself, has to be a list, given that on the very first
varianter implementation, it's supposed to contain one item for each
branch of the tree.

Varianter CIT Plugin: fix data type of variant nodes

---

optional_plugins/varianter_cit/tests/test_functional.py

I clearly missed that on 71d915dd3, as there's no point of using
a locally defined "basedir" and the one from the sefltests module.

Varianter CIT test: use BASEDIR from selftests module

---

examples/tests/cit_parameters.py
optional_plugins/varianter_cit/avocado_varianter_cit/__init__.py
optional_plugins/varianter_cit/tests/test_functional.py

This is the LTS backport of #3116 and #3117.

[LTS] Varianter CIT Plugin: fix data type of variant nodes

---

scripts/avocado

An `OSError` would be raised when avocado crashes the second time,
that because the crash dir has already existed while the script
attempted to create it again.
Let's catch the error and ignore it.
Signed-off-by: Xu Han <xuhan@redhat.com>

scripts/avocado: fix the `OSError` complained by `get_crash_dir()`

---

scripts/avocado

This is the LTS backport of https://github.com/avocado-framework/avocado/pull/3120.

[LTS] scripts/avocado: fix the `OSError` complained by `get_crash_dir()`

---

avocado/core/loader.py
avocado/plugins/list.py

The list command was not showing the values for keys.  Also, this fixes filtering multiple key:vals.

List and better filter support for key:val tags

---

avocado/utils/network.py

AFAICT, most users of find_free_port() don't really care about the
port number being the first in the range, and to be honest, most users
I've seen don't even give a range.
So, the result when using the first port in the range is a high change
of collision, with no real benefit.  Let's change the default policy,
using a random port allocation.
PS: this is motivated by real world collisions I've experienced when
running tests in parallel, *and* when running other loads in the same
machine along tests.

avocado/utils/network.py: use random port allocation by default

---

Makefile.include

Makefile update so "make rpm", etc. can be used to build with mock using the python3-aexpect package from the Fedora modular repositories.

Make "make rpm" work again

---

Makefile.include
python-avocado.spec

This is a follow-on to my earlier PR #3129, which got "make rpm" working again. This PR fixes up the avocado SPEC file so "make rpm" now succeeds for Fedora 31/Rawhide

Make Fedora 31 builds work again

---

avocado/utils/linux_modules.py

The new definitions (Enum based) have been present for quite a long
time.  Let's remove the deprecated ones in accordance to previous
planning.
Reference: https://trello.com/c/BMC7yFbX

avocado/utils/linux_modules.py: remove compatiblity definitions

---

requirements-selftests.txt

Onn Travis CI, setuptools (pkg_resources) is finding a six installation at:
```
/opt/python/3.4.6/lib/python3.4/site-packages/pkg_resources/_vendor/six.py
```
But attempting to uninstall it from:
```
/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/six-1.10.0.dist-info
```
Producing the following error:
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/six-1.10.0.dist-info/METADATA'
```
Not only that, but a whole world of problems are solved with the
setuptools upgrade.  Basically, because of the older setuptools, some
dependencies to be installed from pip are fetched from .tar.gz, such
as this on Travis' Python 3.4.6:
```
Installed /home/travis/build/avocado-framework/avocado/optional_plugins/runner_ …
```

[LTS] Bump setuptools version while testing [v2]

---

avocado/utils/vmimage.py

And because of that, it's hosted in a different set of servers.

avocado/utils/vmimage.py: s390x is also a Fedora secondary arch

---

avocado/utils/vmimage.py

And because of that, it's hosted in a different set of servers.

[LTS] avocado/utils/vmimage.py: s390x is also a Fedora secondary arch

---

avocado/core/loader.py
avocado/plugins/list.py

The list command was not showing the values for keys. Also, this fixes filtering multiple key:vals.
This is an LTS backport of https://github.com/avocado-framework/avocado/pull/3127

[LTS] List and better filter support for key:val tags

---

avocado/utils/process.py

get_events -- this function returns only the perf events matching with
supplied pattern
Signed-off-by: Nageswara R Sastry <rnsastry@linux.vnet.ibm.com>

perf.py: Added perf get events

---

avocado/utils/linux.py

Thse two allow users to get and set content from /proc/sys
PS: The namespace chosen for this module acklowdges that we have way
too much content that is Linux specific, without actually defining it
as such.  This may be start of a proper "avocado.utils.linux" module,
with modules such "avocado.utils.lv_utils" being moved there, and
consequently being named "avocado.utils.linux.lv" for instance.
---
This is a version based on the comments from #3091.

Added utilities to set and get /proc/sys settings [v2]

---

avocado/utils/memory.py

add `get_supported_huge_pages_size()` to get multiple hugepage
sizes supported by the host.
Suggested-by: Amador Pahim <amador@pahim.org>
Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>

utils/memory: add method to get all supported hugepage sizes

---

requirements-selftests.txt
selftests/functional/test_basic.py
selftests/unit/test_xunit.py

The later is a pure Python library, designed for the specific purpose
of validating schema, while the former requires a compiler tool chain
to be installed in a number of scenarios.
Let's also pin the version of its direct depency, elementpath.

XUnit schema check: replace lxml with xmlschema

---

avocado/utils/diff_validator.py
selftests/unit/test_utils_diff_validator.py

These utilities are useful for expected changes in any file on a
tested system. More info is provided within the module docstrings.
--
Changes from v2 (#3150)
* Renamed "conf_file" variable
Changes from v1 (#3112):
* Renamed module to `diff_validator`

avocado.utils: introduce diff_validator [v3]

---

optional_plugins/varianter_cit/avocado_varianter_cit/Cit.py
optional_plugins/varianter_cit/tests/test_cit.py

When the chosen value can't be changed, bacause of some constrain. The function randomly choose diferent valueWhen the chosen value couldn't be changed, because of some constraints. The function randomly chose different value, which is not expected behavior. Now when this event occurs, the function raises ValueError exception and it's handled.

CIT plugin change_one_value fix

---

avocado/utils/datadrainer.py
selftests/unit/test_utils_datadrainer.py

This module is a loose generalization of the FDDrainer present in avocado.utils.process, but intended for a wider audience.
---
Changes from v3 (#3146):
* Used Python 3 syntax for metaclass
* Adapted test to real base implementation, preventing base class to be instantiated
Changes from v2 (#3142):
* Added metaclass to BaseDrainer
Changes from v1 (#3133):
* Made base class an ABC (@apahim)
* Strip only newlines on line logger (@apahim)

Introduce Data Drainer (avocado.utils.datadrainer) [v4]

---

avocado/core/plugin_interfaces.py
selftests/unit/test_plugin_interfaces.py

And test that the interface (only) classes can not be used directly.

Plugin interfaces: port to Python 3 ABC syntax

---

contrib/scripts/summarize-job-failures.py

This introduces a simple script that has the goal of pointing out
tests that failed across a possibly large set of jobs.
---
Changes from v1 (#3126):
* Fixed typo (s/support/supposed)
* Added verification for test IDs in the various given JSON files, making sure all have the same set of tests (@richtja)
* Various refactors

Contrib script: summarize test failures across many jobs [v2]

---

avocado/core/output.py
avocado/core/parser.py
avocado/etc/avocado/avocado.conf
avocado/plugins/run.py
docs/source/DebuggingWithGDB.rst
docs/source/GetStartedGuide.rst
docs/source/ResultFormats.rst
man/avocado.rst
optional_plugins/runner_remote/avocado_runner_remote/__init__.py
optional_plugins/runner_remote/tests/test_remote.py
optional_plugins/varianter_yaml_to_mux/tests/test_multiplex.py
selftests/functional/test_basic.py
selftests/functional/test_output.py
selftests/functional/test_streams.py

Those are older forms of `--show=none` and `--show=test`, so let's remove some clutter and keep only one of each.
---
Changes from v1 (#3149):
* Fixed location of block that can enable the paginator (@wainersm)

Drop --silent and --show-job-log [v2]

---

avocado/core/loader.py

These were intended to keep compatibility with other plugins,
but given that we're past an LTS release, it's desirable to
remove them.

Loader: drop discover mode compatibility definitions

---

avocado/utils/cpu.py

We're checking for identity with literal integers.  Let's fix the
SyntaxWarning: "is" with a literal. Did you mean "=="
given by Python 3.8 and later.

Python 3.8 support: fix SyntaxWarning on avocado.utils.cpu

---

avocado/core/job.py
avocado/plugins/run.py

This adds a command line option "--job-category" that allows one
running tests to quickly category this job in a directory.
A symbolic link is used to point to the (relative) path of the
complete job result directory.

Job: result categorization support

---

selftests/checkall

And use the avocado module entry point, instead of any specific
script.

selftests/checkall: respect Python version set/found

---

examples/tests/gendata.py
selftests/functional/test_basic.py

This is a really bad example of a test, in the sense that it requires
a huge library just to draw an image.
Let's drop it, given that the remaining example works just as well.

examples/tests/gendata.py: drop "bsod" example tests

---

avocado/core/defaults.py
avocado/core/runner.py
avocado/etc/avocado/avocado.conf

This makes the various test runner timeout variables into better defined defaults (for internal consumption) and allow them to be configured by the user.
This is a foundation step for issue https://github.com/avocado-framework/avocado/issues/2908 .

Runner: make timeouts configurable

---

avocado/core/job.py

The recently introduced feature on job category would produce warnings
that wouldn't be visible in the logs because the log initialization is
done later (requires a log directory to be defined).
Let's create the category after the log has been sucessfully
initialized, and while at it, also show the warning in the UI.
---
Changes from v1 (#3165):
* Fixed string formatting

Job: give warning on both the UI and LOG [v2]

---

avocado/utils/partition.py

Patch provides way to input mkfs flags and mount options as current implementation does not have a way to provide.

Fix: Provide way to input mkfs flags and mount options

---

avocado/utils/cpu.py

Added Power9 in get_cpu_vendor_name subroutine as
in power9 system it returns None

Added Power9 in get_cpu_vendor_name subroutine

---

selftests/functional/test_output.py

There was a drop of "bsod" example #3164, but test_gendata still testing if bsod file was created.
This commit deletes bsod file check.

test_gendata fix

---

avocado/__init__.py
avocado/core/decorators.py
docs/source/WritingTests.rst
examples/tests/cancel_on_exception.py
selftests/functional/test_basic.py

aims to cancel the test after certain type of exception is raised within
the wrapped function.

introduce decorator cancel_on

---

avocado/utils/asset.py

Added support in asset.fetch as locations can be single url
and that case it can be string url

Added support in asset.fetch as locations can be single url

---

avocado/core/test.py
avocado/utils/archive.py
avocado/utils/process.py
docs/source/GetStartedGuide.rst
selftests/unit/test_utils_process.py

There are still some code present that would help with Python 2 compatibility, and for Avocado 70.0 and later, we don't need any of it as only Python 3.4 is now supported.
Note: 69.x is still supported for Python 2 users.

Clean up of remaining Python 2 compatibility code

---

avocado/core/runner.py

When the test is interrupted, there is new test state created but without the start time.
This commit fixing the problem.

Fix: wrong start date on INTERRUPTED tests

---

avocado/utils/genio.py

Patch fixes genio utility with os.write expecting string encoding with python3.
ERROR|   File "avocado/utils/genio.py", line 143, in write_file_or_fail
ERROR|     os.write(fd, data)
ERROR| TypeError: a bytes-like object is required, not 'str'

Fix: os.write expects string encode

---

avocado/etc/avocado/conf.d/glib.conf
docs/source/optional_plugins/glib.rst
optional_plugins/glib/avocado_glib/__init__.py
python-avocado.spec

This plugin will try to run every executable file it can find with the
-l parameter, which is not so good.
This keeps things simple and creating a unsafe configuration, and
requiring the user to manually set it to True.
Reference: https://trello.com/c/xewwbjpq

GLib loader plugin: implement safe mode by default

---

avocado/core/dispatcher.py
avocado/core/extension_manager.py
avocado/core/settings_dispatcher.py
contrib/docker/Dockerfile.debian
docs/source/Plugins.rst
docs/source/SubclassingAvocado.rst
python-avocado.spec
requirements-selftests.txt
selftests/functional/test_streams.py
selftests/unit/test_dispatcher.py
setup.py

Avocado uses the stevedore library, which has origins in OpenStack, as
a way to find plugins and activate them.  It's very useful, but
Avocado itself only uses a very small part of it, and actually extends
most of what it uses.
Given that stevedore itself is a simple wrapper around setuptools
(pkg_resources, really), this simply adds the little code we need
around pkg_resources.
The benefits is that the core Avocado application now depends only on
Python and setuptools (which is bundled together on many systems).
Reference: https://trello.com/c/vCgzJ02N
---
Changes from v1 (#3182):
* Added (back) docstrings to `enabled()`, both in `extension_manager` and `dispatcher` modules.
* Removed mention to Stevedore in the Wrap up section of the docs.

Remove stevedore package requirement [v2]

---

avocado/utils/process.py
selftests/functional/test_utils.py

waiting during the defined time for results of subprocess.
Reference: https://trello.com/c/mY5GpHKX
---
Changes from v1 (#3172):
* Docstring change according to suggestions
* Stop test splitted into two separated tests
* Marking of time taking tests

Set timeout to stop method of SubProcess [v2]

---

avocado/core/extension_manager.py

The original (stevedore based) implementation would also put
the entry point information to the list of load failures.
This is needed by avocado.core.output.log_plugin_failures(),
and causes a crash if any plugin fails to load.  Let's put
it back then.
Reference: https://github.com/avocado-framework/avocado/pull/3192#issuecomment-510831956

Add the entry point info to the load failures list

---

avocado/core/loader.py
avocado/core/safeloader.py
avocado/core/test.py
selftests/unit/test_loader.py

This adds support for the Avocado tags mechanism to plain Python
Unittests.  It's possible to filter tests based on both "flat" and
"key:val" tags.

Python Unittests: add support for Avocado tags

---

optional_plugins/runner_remote/avocado_runner_remote/__init__.py

With python 3, avocado remote runner may fail with "Avocado job failed:
JobError: Remote machine does not seem to have avocado installed" if
stderr is non-empty. The version check includes stderr since python 2
writes the version output to stderr. Since avocado versions over 69.0 only
support python 3, drop stderr from the check.
Signed-off-by: John Allen <john.allen@amd.com>

optional_plugins/runner_remote: Drop stderr from remote version check

---

avocado/core/output.py

It turns out there are three separate errors on three different levels
playing together that I can call the good, the bad, and the ugly. The
ugly one is the entire python 3.7 interpreter crashing as described here:
https://bugs.python.org/issue36272
Python crashing instead of handling the recursion with RecursionError is
then fixed in a patch like:
diff --git a/Lib/logging/__init__.py b/Lib/logging/__init__.py
index b4659af7cc..7457549cb9 100644
--- a/Lib/logging/__init__.py
+++ b/Lib/logging/__init__.py
@@ -1094,6 +1094,8 @@ class StreamHandler(Handler):
stream.write(msg + self.terminator)
self.flush()
+        except RecursionError as e:
+            raise
except Exception:
self.handleError(record)
which was not yet available at time of writing this but merged. This can
handle the ugly …

Temporarily fix a stack overflow problem in python 3.7

---

selftests/unit/test_nrunner.py

This test assumed that, because it'd run an empty unittest, it'd
finish in 0s.  Well, that's not the case on some low powered or
overloaded systems.  So, let's just look for the output to look
similarly enough.

selftests/unit/test_nrunner.py: do not assume 0 seconds execution time

---

.travis.yml
selftests/functional/test_basic.py
selftests/functional/test_output.py
selftests/functional/test_plugin_diff.py
selftests/functional/test_streams.py
selftests/run_coverage

The codecov.io service allows easy reporting of coverage data, let's
include that in our CI to put additional stress on committers to write
tests as well as on us to require them.
Sample output is here: https://github.com/ldoktor/avocado/pull/2

Enable codecov coverage reports for Avocado

---

avocado/utils/memory.py

In power systems, 16G hugepages are not runtime configurable with pseries platform, handling it here.

Handle hugepages for POWER platform

---

avocado/utils/pci.py

Adding infiniband device to dictionary which resolves pci class
ID to names on sysfs.

Adding devices to pci class dictionary

---

optional_plugins/html/avocado_result_html/templates/avocado_html.js
optional_plugins/html/avocado_result_html/templates/results.html
optional_plugins/html/avocado_result_html/templates/style.css

Bring back some features from autotest report, namely the
ability to display all records in the table and an extra dropdown
to filter records by status.
Also, to avoid breaking the table layout when we have long
values we truncate those and add an ellipsis to the end. The
full content will then be displayed in a tooltip by hovering
over the cells.

Improve the HTML report

---

avocado/core/dispatcher.py
avocado/core/enabled_extension_manager.py

This class is not really a dispatcher designed to be used standalone,
but a extension manager with additional features that can be used as
the basis for real dispatchers.
If it didn't depend on the settings module, it'd be a good candidate
for living in the avocado.core.extension_manager module, but to avoid
circular dependencies there, it needs to live elsewhere.  With those
things in mind, let's put it in its own module.

Move extension manager with disable/order support to its own module

---

optional_plugins/html/avocado_result_html/templates/avocado_html.js
optional_plugins/html/avocado_result_html/templates/results.html
optional_plugins/html/avocado_result_html/templates/style.css

After commit 0d8b50e the visibility of whiteboard tooltip was broken. This commit solves this problem and also creates same style for all tooltips inside results table.

Fix of whiteboard visibility HTML

---

avocado/core/parser_common_args.py
avocado/plugins/list.py
avocado/plugins/run.py

Let's extract the common command line arguments into its own module
and reuse on all commands that use it.

Tags: unify command line arguments

---

optional_plugins/robot/setup.py
optional_plugins/robot/tests/avocado.robot
optional_plugins/robot/tests/test_robot.py

This is a very simple test for the Robot plugin loader, that makes
sure Avocado sees the right tests from a ".robot" file.

Robot plugin: introduce loader tests

---

optional_plugins/html/avocado_result_html/templates/avocado_html.js
optional_plugins/html/avocado_result_html/templates/results.html
optional_plugins/html/avocado_result_html/templates/style.css

After commit 0d8b50e the popover of the info column was broken
due to the HTML title attribute being added. This column doesn't
need that tooltip as it already has a bootstrap popover applied
to it by __init__.py when filling this column.
Also, after commit d6f80ad the ability to filter by status was
lost after wrapping status element in divs, so we need to unwrap
them when filling the dropdown. Finally, bring back a CSS style
that was removed but is needed to make the status dropdown look
the same as the page dropdown added by datatables.
Signed-off-by: Samir Aguiar <samirjaguiar@gmail.com>

Fix filtering and popover in HTML report

---

avocado/utils/software_manager.py

Python3 no longer provides next() for generator object. Fixed it to be compliant with python3

Fix: software_manager.py get_source method

---

selftests/unit/test_utils_diff_validator.py

…allel
The creation of the temporary files are done in the same place, so tests
can conflict with others when running in parallel (the default for
the N(ext) runner based executions).
This is what I've been seeing every now and then on Travis:
======================================================================
ERROR: test_change_wrong_add (selftests.unit.test_utils_diff_validator.ChangeValidationTest)
----------------------------------------------------------------------
File "/home/travis/build/avocado-framework/avocado/selftests/unit/test_utils_diff_validator.py", line 79, in test_change_wrong_add
changes = diff_validator.extract_changes(change.get_target_files())
File "/home/travis/build/avocado-framework/avocado/avocado/utils/diff_validator.py", …

selftests/unit/test_utils_diff_validator.py: allow test to run in par… [v2]

---

avocado/core/safeloader.py
selftests/unit/test_safeloader.py

On c26a93675 support for tags on Python unittests was added.  But,
when base classes are used, the extra info was being discarded and
only method names were being returned.  Let's fix that.
---
Changes from v2 (#3236):
* Also renamed test, ending in `python_unittest` to make its purpose clearer
Changes from v1 (#3204):
* Renamed `RECURSIVE_DISCOVERY_UNITTEST` to `RECURSIVE_DISCOVERY_PYTHON_UNITTEST`

Python unittest support: do not remove extra info (such as tags) [v3]

---

optional_plugins/html/avocado_result_html/__init__.py
optional_plugins/runner_docker/avocado_runner_docker/__init__.py

A Python 3 fix for Docker and a fix for the assumption that the whiteboard will always be present (introduced in 2ba4b5321a2c5fdaeec9691db9d6a717532cce6c).

Docker and HTML plugin fixes

---

optional_plugins/html/avocado_result_html/__init__.py
optional_plugins/html/avocado_result_html/templates/results.html
optional_plugins/html/avocado_result_html/templates/style.css

1. Inline SVG in CSS instead of retrieving SVG files from directory.
2. Replace `white-space: pre` with `white-space: pre-wrap`

Fix can not load svg files in HTML

---

optional_plugins/loader_yaml/avocado_loader_yaml/__init__.py
optional_plugins/loader_yaml/tests/.data/two_tests.yaml
optional_plugins/loader_yaml/tests/test_yaml_loader.py

The nrunner commits switched from Namespace to dict args, but this has
not been tackled for loader_yaml plugin. Let's fix it now.

optional_plugins.loader_yaml: Fix dict usage after nrunner commits

---

selftests/run_coverage

We're running "optional_plugins/*" selftests so it makes sense to
include it into the report as well.

selftests: Include "optional_plugins/*" to coverage report

---

selftests/functional/test_basic.py

The commit this reverts was added to handle the unittest execution
within the context of coverage reporting.  But, it breaks the test
execution when the AVOCADO variable can not be splitted into more than
one component.
Later, a skip for this test was added when running within the context
of coverage reporting, so reverting this would seem logical even if it
was not breaking a test.
This reverts commit f87bab3513459415ba1088ec637c56d952132022.

Revert "selftests: Improve avocado_abs command"

---

selftests/deployment/rpm-copr.yml
selftests/deployment/tasks/avocado_vt_rpm_pkgs.yml

The name says it all, updates to the deployment checks to reflect the fact Avocado is Python 3 based.

Deployment checks: update to py3

---

avocado/utils/crypto.py

This commit adds io.DEFAULT_BUFFER_SIZE variable which determines the size by the device.

hash_file buffer size

---

avocado/plugins/expected_files_merge.py
avocado/utils/genio.py
selftests/functional/test_output_check.py
selftests/unit/test_utils_genio.py
setup.py

It is the implementation of .expected files merge, which after the job execution cascadely merge equal .expected files from variant level to file level. When the .expected files at the same level are equal, they are deleted and it is created a new file in the upper level.
---
Changes from v1 (#3243):
- Solved problem with the unwanted move to the upper-level directory
- Comparison of two files by hash
- Tests for new functions in genio utility
- Created plugin for merging files
Changes from v2 (#3259):
- Changed names of variables like `file` to `filename`
- Deleted repeated code
- Typo fixes
- New test for expected_files_merge
- Deleted CLI plugin interface
- Usage `avocado.utils.crypto.hash_file` in genio
- Better equality check for file …

Merge of stdout/stderr.expected files second implemantation [v3]

---

optional_plugins/golang/avocado_golang/__init__.py
optional_plugins/robot/avocado_robot/__init__.py

With the work on the test resolver (which should replace some of the current test "loader" mechanism), we'll have two implementations living (loader and resolver) for some time.
To avoid duplicating code, the let's extract code that is going to be used on the resolver version of those plugins.

Robot/Golang plugins: extract utilities

---

python-avocado.spec

This solves a build issue with Fedora >= 31, and removes a old workaround related to libvirt-python.

RPM packages: libvirt-python issue and workaround

---

codecov.yml
optional_plugins/loader_yaml/tests/.data/two_tests.yaml
optional_plugins/loader_yaml/tests/test_yaml_loader.py

Add tests for other yaml-loader features that I use in my CI (and want them to stay functional :-)). While on it also added codecov config to not to require CI PASS.

optional_plugins: Increase test coverage of mux-suite

---

avocado/core/test.py

And define it at class initialization time (to avoid W0201).

avocado.Test: make file_handler attribute private

---

avocado/utils/archive.py

Commit 4c6e6949d correctly removed the conditional and tarfile
wrappers for lzma capabilities, but incorrectly removed the '.xz' from
the extensions supported by ArchiveFile.
Let's put it back unconditionally.

avocado/utils/archive.py: bring back support for xz archives

---

avocado/utils/cpu.py
selftests/unit/test_utils_cpu.py

Also better docstring and fix format to follow PEP 257
Reference: https://trello.com/c/aJzNUeA5
Signed-off-by: Beraldo Leal <beraldo.leal@cern.ch>
Hi all, this is my first PR here.
@sathnaga, can you please take a look?
I didn't add a changelog note because I didn't know where to insert.

Removed support for the legacy integer parameter on set_cpuidle_state

---

avocado/core/safeloader.py
selftests/unit/test_safeloader.py

Some use cases, for instance on QEMU, will use tag values as a default
value for some key characteristics of the test.  For instance:
:avocado: tags=arch:x86_64
Is already used for determining the architecture specific aspect of a
test, and will that value set if a parameter was not explicitly set.
But, due to the limited character set supported in tags, some values
can not be set.  For instance:
:avocado: tags=machine:s390-ccw-virtio
Cannot be properly recognized without dashes being supported.

Tags: extend the supported character set allowing dashes

---

avocado/utils/configure_network.py

Changing ifcfg path for suse to /etc/sysconfig/network.

Changing path for Suse

---

Makefile

Because of the addition of the Makefile.include file, the first
target was changed to the first on Makefile.include, while it
should have been the "all" target that shows the help message.
Let's change the order of the include to restore the behavior
of showing the help message when running just `make`.

Makefile: show help message as the default target

---

avocado/utils/cpu.py
selftests/unit/test_utils_cpu.py

A fix and extra tests for `avocado.utils.cpu.get_cpu_vendor_name()` (from #3277 and #3278)

CPU vendor fix and tests

---

avocado/utils/vmimage.py
contrib/scripts/vmimage-populate-cache.py

CirrOS is a very popular, tiny cloud image.  It's just natural that
we add support to vmimage.
Also added here is a contrib script that can validate this provider,
and can always be extended later.

avocado.utils.vmimage: add CirrOS provider

---

avocado/core/nrunner.py
avocado/core/nrunner_avocado_instrumented.py
avocado/plugins/nrun.py
docs/source/NRunner.rst
selftests/functional/test_nrunner_interface.py
setup.py

This adds some introspection to a runner by means of the `capabilities` command, and makes the `avocado nrun` command (the early equivalent to the creation of an Avocado job and counterpart to the `avocado run` command) able to use other external binaries/scripts to run different kinds of tests (runnables).
The last commit adds, for the first time, an Avocado selftests written as an Avocado INSTRUMENTED test, with the following goals:
1) test the basic behavior of multiple runner implementations
2) experience with Avocado selftests written as Avocado INSTRUMENTED tests
3) test "avocado nrun" and the avocado-runner-avocado-instrumented

Nrunner: extra runners and INSTRUMENTED support

---

avocado/utils/vmimage.py
selftests/unit/test_utils_vmimage.py

This PR adds some fixes and improvements to vmimage utility, it is:
- Deletion of useless variable `LZMA_CAPABLE`
- Recovery of image parameters from its file name.
- Usage of multiple cache directories 
- Possibility to get information about images before download.

Vmimage utility improvements

---

python-avocado.spec
selftests/unit/test_utils_vmimage.py

A few issues (from the RPM perspective) were introduced by #3289 and #3247, as can be seen by the failed COPR builds:
* https://copr.fedorainfracloud.org/coprs/g/avocado/avocado-latest/build/1028659/
* https://copr.fedorainfracloud.org/coprs/g/avocado/avocado-latest/build/1028677/
They are resolved here.

RPM build fixes

---

avocado/utils/process.py
selftests/unit/test_utils_process.py

It's definitely a common pattern to run commands, and if the output
matches a given expected pattern, have that output.  On a previous
discussion, I pointed out that:
"I think this could be introduced as an avocado.utils.process
utility instead, one that takes a command and a pattern. I don't
think this justifies a new module (avocado.utils.perf) and the
hardcoded perf list list command. If, the perf list command output
were to be parsed into a proper data structure, then I think it'd
make sense to have a perf module."
What I meant there, it's that a generic utility function could be
added, not one that runs "perf list".  This makes the function
introduced here to be a generic function.  Users for this function
should simply start using:
get_command_output_matching("perf list", "pattern") …

avocado.utils.process: function for getting matching output

---

avocado/core/data_dir.py
avocado/utils/path.py

Change the behavior of usable_ro_dir so it does not create a dir.
If a new dir is needed, usable_rw_dir should be used.
Reference: https://trello.com/c/xsKNnIYu/

The path.usable_ro_dir shouldn't create a dir

---

Makefile.include

`Makefile.include` has been updated for Rawhide becoming Fedora 32  so `make rpm`, etc. can be used to build with `mock` using the appropriate `python-aexpect` package from the Fedora modular repositories.

build update for Fedora Rawhide

---

avocado/plugins/vmimage.py
avocado/utils/asset.py
avocado/utils/vmimage.py
selftests/functional/test_plugin_vmimage.py
selftests/unit/test_plugin_vmimage.py
selftests/unit/test_utils_asset.py
setup.py

Vmimage plugin for management vm images. Has two functions one for downloading new vmimages to the avocado cache and one for listing all existing vmimages inside avocado cache.
---
Changes from v1 (#3264):
- Split into multiple commits
- In fedora secondary usage of local system arch
- For cash_dirs support for anything that can be looped over
- Fix bug with display of download image
- Better CLI
- Functional tests for the CLI
Changes from v2 (#3269):
- New directory structure for keeping information about images
- Changed `LOG_UI.info` to `LOG_UI.debug`
- Fix, problems with command-line options
- Fix, extra white chars in the docstring
- New unit test of downloading images
Changes from v3 (#3280):
- Metadata file for storing information about images
- Fixed typos
- Usage of CirrOS for …

Vmimage cmd [v5]

---

selftests/functional/test_plugin_vmimage.py
selftests/unit/test_plugin_vmimage.py

Basically to deal with network access aspects of some tests, which shouldn't happen by default.

vmimage: fixes to tests

---

avocado/utils/ssh.py
selftests/unit/test_utils_ssh.py

This, among other minor things, adds password based authentication.  A use can be seen here:
https://github.com/clebergnu/qemu/tree/ssh_password
More specifically:
https://github.com/clebergnu/qemu/commit/f295b3a06b1cc2f689063dd23d4f2c710e980e29

avocado.utils.ssh: support password based authenticaction

---

.travis.yml
avocado/utils/cpu.py

as in python3 it complains about TypeError: cannot use a
string pattern on a bytes-like object

Fix issue in avocado:utils:cpu.get_cpu_vendor_name()

---

Makefile.include
python-avocado.spec

This PR contains several build fixes for 69LTS. The first two are a backport of #3132 to 69LTS.
1. `Makefile.include` has been updated so `make rpm`, etc. can be used to build with `mock` using the `python-aexpect` packages from the Fedora modular repositories.
2. The SPEC has been updated to disable building components dependent upon Fiber in Fedora 31 and later, since avocado is currently incompatible with the new Fiber API. (#3125)
3. The SPEC has been updated to drop builds for Python 2 from Fedora 31 and RHEL 8 onward.

69lts build fixes

---

avocado/core/nrunner.py
avocado/core/nrunner_avocado_instrumented.py
examples/recipes/runnables/exec_echo_no_newline.json
selftests/functional/test_nrunner.py
selftests/unit/test_nrunner.py

This improves the nrunner code with support for encoded (in base64) simple arguments, and proper support for keyword arguments.

nrunner: encoded args and keyword args support

---

avocado/core/job.py
avocado/core/runner.py
avocado/plugins/human.py
avocado/plugins/tap.py
selftests/functional/test_output.py

This is the responsibility of the human UI plugin, which should check
if other plugin has taken ownership of the STDOUT.
This keeps the job interruption reason in the job itself, because,
quite simply, it's a job wide event.
Reference: https://github.com/avocado-framework/avocado/issues/3317

Job: don't produce output that goes to the UI

---

avocado/core/nrunner.py
avocado/core/nrunner_avocado_instrumented.py
selftests/functional/test_nrunner.py
selftests/unit/test_nrunner.py

The `kwargs` attribute on the nrunner Runnables has not been properly used so far.  This introduces serialization and de-serialization support for kwargs, and with that, makes tags a "first class" runnable attribute.

nrunner: improve support for keyword arguments and introduce JSON

---

Makefile
selftests/functional/test_utils.py

To the `make check-full` target, not running on the coverage
checks, which include their execution on Travis-CI.
Reference: https://github.com/avocado-framework/avocado/issues/3321

Limit functional.test_utils.FileLockTest.test_filelock execution

---

avocado/core/nrunner.py
avocado/core/tags.py
avocado/plugins/nrun.py
python-avocado.spec
selftests/unit/test_tags.py
setup.py

The nrunner is soon going to be hooked up to the "resolver"[1][2] plugins, and disconnected from the current "test loader" code.
These changes are the adaptations I found necessary to then introduce the resolver.
[1] - https://github.com/clebergnu/avocado/commits/wip/resolver
[2] - https://github.com/clebergnu/avocado/commit/d9835d51682af13a332130cd4c9a78b4788190b7

nrunner: resolver prep work

---

avocado/core/plugin_interfaces.py
avocado/core/resolver.py
avocado/etc/avocado/avocado.conf
avocado/plugins/nlist.py
avocado/plugins/nrun.py
avocado/plugins/plugins.py
avocado/plugins/resolvers.py
optional_plugins/glib/avocado_glib/__init__.py
optional_plugins/glib/setup.py
optional_plugins/golang/avocado_golang/__init__.py
optional_plugins/golang/setup.py
optional_plugins/golang/tests/test_golang.py
optional_plugins/robot/avocado_robot/__init__.py
optional_plugins/robot/setup.py
selftests/functional/test_resolver.py
selftests/unit/test_resolver.py
setup.py

Introduce avocado.core.resolver as an alternative to loader
This new module, plugin interface and associated infrastructure provides an alternative that is better integrated to the other Avocado plugins. 
Currently, it's only leveraged by the N(ext) runner, and exposed via an also experimental `nlist` command.
---
An explanation was presented here:
https://www.redhat.com/archives/avocado-devel/2019-July/msg00002.html
I'm aware of a few limitations on this version, including not being able to filter by test name (what the loader calls "subtest filter").  All the limitations will be addressed before this feature is considered stable (it's currently marked as experimental, and limited to the also experimental `nrunner`)

Introduce avocado.core.resolver as an alternative to loader

---

avocado/plugins/nlist.py

This fixes a logic mistake in the creation of the "test matrix" when
the verbose mode is active.

nlist: fix listing of tests in verbose mode

---

.packit.yml

This is an initial attempt to implement Packit as a service to
build packages on pull requests.
The goal is to not have changes that will cause breakages to
packaging, and thus, releases should be smoother.  Also, if users
choose to, they should be able to have RPMs for all development
versions at any time too.

Packit Initial Support

---

avocado/utils/asset.py

Under systems with heavy load, and multiple tests contending for
access to an asset file, the test can error because of the short
timeout.
This is a simple workaround that favors less false negatives and
trades it off with a possibly longer test execution time.  The
complementary and definitive solution, though, is to avoid
recalculating the hash if a "verified" flag is in place and it's newer
than the asset file itself.
Reference: https://trello.com/c/WdnjY4n7

avocado.utils.asset: generously increase the lock acquisition timeout

---

avocado/core/job.py
avocado/core/result.py
avocado/core/runner.py
optional_plugins/runner_docker/avocado_runner_docker/__init__.py
optional_plugins/runner_remote/avocado_runner_remote/__init__.py
optional_plugins/runner_remote/tests/test_remote.py
optional_plugins/runner_vm/avocado_runner_vm/__init__.py
optional_plugins/runner_vm/tests/test_vm.py
selftests/unit/test_jsonresult.py
selftests/unit/test_result.py
selftests/unit/test_runner_queue.py
selftests/unit/test_xunit.py

Even though there are currently multiple implementations of test runners, (`avocado_runner_remote.RemoteTestRunner`, and `avocado_runner_vm.VMTestRunner` and `avocado_runner_docker.DockerTestRunner`)  there's no interface currently defined.  
The `avocado.core.runner.TestRunner` is currently both the main (local) implementation and serves as the base class for other runners.
This currently makes the internal interface more clear, and further work will define the final and "public" interface in `avocado.core.plugin_interfaces`.

Test runner: work towards defining an interface

---

avocado/core/job.py
avocado/core/sysinfo.py
avocado/core/test.py
avocado/plugins/sysinfo.py
setup.py

The infrastructure to run code before and after jobs are run already exist.  Let's make use of those, and in due time, do the same for the sysinfo collection on tests.

Sysinfo: job collection implemented as a plugin

---

avocado/core/nrunner.py
avocado/core/nrunner_avocado_instrumented.py
selftests/functional/test_nrunner.py
selftests/unit/test_nrunner.py

The avocado.core.test.Test class provides a large number of
information on each state message that gets sent to the runner.  Among
those are some related to the execution time of each test.  That
information is consumed by the job and makes its way into the test
results.
Let's start providing information on the various nrunner based
runners, taking the time (pun not intended) to think if those are
really necessary or the responsibility of the runner.  For instance,
the "time_elapsed" information is probably best calculated by the job
and not by each individual runner.

nrunner: give time_start and time_end information

---

avocado/core/test.py
selftests/functional/test_plugin_jobscripts.py
selftests/functional/test_replay_basic.py
selftests/functional/test_replay_external_runner.py
selftests/run
selftests/unit/test_nrunner.py

This PR should fix leftover and badly named temporary directories as part of a `make check-full` command.

Tests execution and temporary dir fixes

---

avocado/plugins/diff.py
avocado/plugins/list.py
avocado/plugins/sysinfo.py

The command line parser is really the entire "avocado" command line
parser, and not limited to the "test running" aspects.  The original
text is not wrong, but a bit misleading.
While at it, let's reduce the possible confusion that may be caused by
the `avocado.core.parser` module having two similar classes, with very
different origins, and give the right type of the parser argument to
the configure method.

Docs: improve the docstring about the parser argument

---

avocado/core/loader.py
avocado/core/references.py
avocado/core/resolver.py
avocado/plugins/resolvers.py
docs/source/ReferenceGuide.rst
selftests/unit/test_references.py
selftests/unit/test_resolver.py

The loader code has support for filters, so that one can specificy a subset of tests with list/run.  Let's add the same feature to nlist/nrun, that is, to the resolver code.

resolver: add support for filters for avocado-instrumented

---

avocado/plugins/assets.py
selftests/functional/test_plugin_assets.py
selftests/unit/test_plugin_assets.py
setup.py

Implements 'assets fetch' command that uses a parser on instrumented test source to find 'fetch_asset' calls composed of simple strings as parameters, or at least one level of variable in the same context
with a string assignment, and fetch those assets without running the test.
---
Changes from v1 (#3333)
- Executing asset.Asset instead of an avocado test.
- Handling one level of variable string assignment.
- Fix lots of pylint messages.
- Changed the way the call is built to fit asset.Asset call.
Changes from v2 (#3337)
- Fix bug that incorrectly considered functions outside of the classes.
- Add command return codes.
- Move `fetch_assets` out of the node visitor class.
- Add functional tests.
- Add some unit tests. Some are still …

Add initial support to 'assets fetch' command with a simple parser [v4]

---

avocado/core/nrunner.py
avocado/plugins/nlist.py
examples/recipes/runnables/exec_sh_echo_env_var.json
selftests/functional/test_nrunner.py
selftests/unit/test_nrunner.py

The current nrunner implementation already contains the concept of "recipes", which are file based representation of Runnables and Tasks.
This PR improves the state of serialization of Runnables, making it possible to create recipes straight from the reference resolution process.  Basic workflow is:
```
$ avocado nlist --write-recipes-to-directory=/tmp/ -- /bin/true /bin/false
exec-test /bin/true
exec-test /bin/false
$ avocado runnable-run-recipe /tmp/1.json
{'status': 'running', 'time_start': 1571866686.689068}
{'status': 'running'}
{'status': 'pass', 'returncode': 0, 'stdout': b'', 'stderr': b'', 'time_end': 1571866686.7021923}
$ avocado runnable-run-recipe /tmp/2.json
{'status': 'running', 'time_start': 1571866689.989536}
{'status': 'running'}
{'status': 'fail', 'returncode': 1, …
```

Nrunner: runnable serialization

---

optional_plugins/robot/avocado_robot/runner.py
optional_plugins/robot/setup.py

The resolver support is already present, but so far, there was no
support for running Robot Framework tests with the nrunner.  This
introduces a basic version, very similar to the already existing
regular runner.

nrunner: introduce Robot Framework runner

---

optional_plugins/robot/setup.py

The current requirement will install the new version of Robot Framework
(3.2), which is coming with incompatible APIs. This is breaking the
Avocado command line and making some tests to fail. This small fix
forces to install robotframework<=3.1.2.

optional_plugins: robot: fixed dependency version

---

requirements-selftests.txt

When the git repository is cloned and the required packages are installed using `pip install -r requirements-selftests.txt`, it fails as new libvirt interfaces have changed. Update libvirt-python package version fix the problem.

Bump libvirt-python package version on requirements-selftests.txt

---

docs/source/conf.py

Travis jobs were falling due to some pylint checks in conf.py and
Makefile.  This commit fixes these lint errors.

docs: fixed some pylint errors

---

.travis.yml

This is just a simplification of how the codecov job is specific, removing shell based logic for proper configuration for each job.  This makes the commands executed on the Travis jobs to not require any interpretation by human beings.

Travis CI: codecov configuration refactor 

---

avocado/utils/vmimage.py

Avocado currently searches for the qemu-img binary on the system,
picking the first one available (respecting the PATH environment
variable and looking at common places).
In some specific circurnstances, such as when testing QEMU itself,
it's desirable to use a matching qemu-img binary.  Let's allow this
configuration to be done at the module level, to be less intrusive on
the API, so that the vast majority of vmimage users don't have to
care about it.

vmimage: allow the qemu-img binary to be overriden

---

avocado/utils/multipath.py
avocado/utils/pci.py

This is a quick follow up to b258f0d88, which changed the return of
many utilities from bytes into str.  This makes it extra clear the
return type for those utilities.

Multipath and PCI utilities: add return type to docstrings

---

avocado/utils/process.py
selftests/unit/test_utils_process.py

`send_signal` fails to send signal to itself in sudo mode, which only
send signals to its child processes.

process.SubProcess.send_signal: fix the failure to signal itself

---

avocado/core/settings.py
avocado/core/sysinfo.py
avocado/etc/avocado/avocado.conf
selftests/unit/test_settings.py

When installing from pip, configfile paths are not relatives to the
current distribution installation path. This set of changes will fix the
the behavior for paths inside configfiles: if a path is relative, then
prepend the right distribution path before using it.

core.settings: fixed configfile paths when using non-distro installs [v1]

---

avocado/core/safeloader.py
selftests/unit/test_safeloader.py

The safeloader attempts to find modules at a parent location
in an attempt to find classes that may inherit from avocado.Test.
But, it should not depend on being able to find those modules,
and simply bail out if they're are not a parent location.
Test code and bug found by Nicolas Brignone.
CC: Nicolas Brignone <nbrignon@redhat.com>

safeloader: do not require to find module at parent path

---

avocado/utils/kernel.py

Version 2 of https://github.com/avocado-framework/avocado/pull/3386
Changes:
- Accepted @clebergnu 's suggestions
- Added a handler for `targets` parameter of `configure()` when it uses default value (commit https://github.com/avocado-framework/avocado/commit/786f7a4cd3675916e950580c6fb3e0c0fd6a9b86)
- Added docstring for `build_dir` property
- Added commit that fixes pylint warnings

[v2] Utils kernel improvements

---

.pylintrc

While developing, some IDEs will report lint problems that are not covered by selftests/inspekt-lint.sh. The developer may disable the message in the source code without knowing it is not covered by the
lint check. The pylintrc can be used to avoid this kind of mismatch. The messages enabled/disabled in the initial file are those listed on selftests/inspekt-lint.sh.

Add an initial pylintrc file to be used with IDEs

---

avocado/core/output.py
avocado/etc/avocado/avocado.conf

In some cases we are redirecting the output to a periodically
checked log file and preserving the colors to easily detect the
test statuses can be useful too.

Add a switch for enforcing colored output to non-tty targets

---

examples/tests/linuxbuild.py

The current 3.x based kernel version is quite anciente.  Let's update
to the latest available version.

examples/tests/linuxbuild.py: update kernel version

---

avocado/core/loader.py

This is originally from #3393, described as:
"The first part of the pull request is actually a refactoring of FileLoader to simplify the creation of alternative loaders. The newly introduced class, SimpleFileLoader, is then used by the TAP plugin, but it could also be used by e.g. the GLib loader in order to get better error reporting (e.g. broken links) and remove duplicated code.".
The only change compared to #3393 is a very simple style fix.

Loader refactors

---

avocado/utils/vmimage.py

vmimage: avoid taking snapshots when only the base image is needed
The avocado.utils.vmimage library currently takes non-lazy approach,
calling `get()` when it's instantiated, even though it has some
provision for acting lazily with its `path` and `base_image`
properties.
This change keeps the behavior of favoring a snapshot image when
`get()` is called, because most of the times we expect that users want
a image they can interact with and throw away.  But, when doing other
operations, such as downloading the images, it's totally unnecessary
to create snapshots.
Let's avoid duplicity on the action at instantiation time, allowing
users to either call `get()` or `download()`, or have access to the
snapshot by accessing the `path` property or the base image by
accessing the `base_image` …

Vmimage: act lazy and don't do snapshot

---

avocado/utils/service.py
selftests/unit/test_utils_service.py

lgtm was alerting one error related to mktemp deprecated function. This
small change replaces mktemp with mkstemp.
Reference: https://lgtm.com/rules/1507928201922/

utils/service: replace mktemp with mkstemp

---

optional_plugins/varianter_yaml_to_mux/tests/test_unit.py

Use of PyYAML's yaml.load function without specifying the Loader=... parameter,
has been deprecated and a warning is displayed when running selftests/run.
This small change fixes that.
Reference: https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

fixes yaml.load deprecation warning

---

avocado/core/output.py

When self.pipe do not exist, an AttributeError exception is raised.
This change just adds this catch.
-----------------------
* Changed the approach as suggested by @clebergnu.
Now is check if self.pipe exists on close, write and flush methods.

core/output: Catching ignored exception [v2]

---

spell.ignore

Added few words to spell.ignore so that pylint spell check stop
complaining.

spell.ignore: adding few words to make pylint happy

---

avocado/core/loader.py
avocado/core/tapparser.py
avocado/core/test.py
avocado/plugins/resolvers.py
docs/source/guides/user/chapters/concepts.rst
docs/source/guides/user/chapters/loaders.rst
selftests/functional/test_loader.py
selftests/unit/test_tap.py
setup.py

The new loader comes with a TAP parser, which logs individual failures
that were reported in the executable's output, and transforms them into
an overall PASS/FAIL/SKIP state.
Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
---
Note: this version is different from the original work (https://github.com/avocado-framework/avocado/pull/3393/commits/081ce9c9cb683c342227d57395ff160c43c81724) only in the sense that it makes the TAP test loader a core feature, as oposed to an optional plugin).

add TAP test loader

---

examples/testplans/release/pre.json
selftests/functional/test_sysinfo.py

As part of the process of reducing the manual steps, and automate as
much as possible on pre-release manual steps, this change adds the HTML
check on sysinfo output.

selftests/functional: Test sysinfo HTML output

---

selftests/unit/test_utils_cloudinit.py

Instead of trying to find a free port on our code, let the socket system
code allocate a port.  Because the server will be running, and the socket
bound, it's possible to get the port number with getsockname().
This fixes an `OSError: [Errno 98] Address already in use` that used to
appear on Travis-CI from time to time.

selftests/unit/test_utils_cloudinit.py: use automatically aloccated port

---

optional_plugins/loader_yaml/avocado_loader_yaml/__init__.py

A loader's discover() method can be passed a None reference, which is
a valid scenario, and the given loader may for instance return all
builtin/default tests.
In the case of the YAML Loader, this references is expected to be a
path to YAML file, so it should bail out early when None is given.
This fixes the error that can be seen on the command line similar to:
Test discovery plugin <avocado_loader_yaml.YamlTestsuiteLoader
object at 0x7f544a6c62e8> failed: expected string or bytes-like object

YAML Loader: behave when empty references are given

---

avocado/utils/lv_utils.py

This function is deprecated since Sep, 2018. This small change remove
this function.

thin_lv_create: removed deprecated function

---

docs/source/quickstart/index.rst

Because the Quick Start index page is also now being used as the
README page, it's confusing to be welcoming users to the Avocado
Documentation from there.  Also, when users open the documentation,
they already know they're there, and a simpler message also does the
job well IMO.

docs/source/quickstart/index.rst: make welcome message more generic

---

avocado/plugins/jsonresult.py

The job results JSON file does not contain the counters for
interrupted and warned tests. This change add the 'warn' and
'interrupt' fields in the JSON file.

plugins: jsonresult: add missing warn and interrupt fields

---

.travis.yml
Makefile
avocado/plugins/run.py

As discussed during the RFC and blueprint 001, we need to warn users
that sysinfo and other boolean args on and off will be deprecated soon.
-----
* Removed unused import
* Suppress warnings when running tests

added booleand args deprecation message [v2]

---

avocado/utils/multipath.py

multipath -ll command used to exit with TRUE condition in previos logic
all the tim. Hence change it properly with the help of if condition which
checks for real existance of mpath.
Now it is working fine.

modifying device_exists function in multipath.py utils

---

avocado/utils/configure_network.py

up or down using ethtool.
This utility can be used in other network tests to check if the
link of an interface is up or not.

Add interface_link_up function to check if the link is

---

avocado/core/data_dir.py
avocado/core/jobdata.py
avocado/plugins/diff.py
avocado/plugins/replay.py
contrib/scripts/avocado-get-job-results-dir.py
optional_plugins/loader_yaml/tests/test_yaml_loader.py
selftests/unit/test_datadir.py

This PR contain commits that move methods from jobdata to data_dir which is conceptually the right place. Then I improved (renamed too) the methods, besides some improvements+fixes. It seems the only clients of those methods are the diff and replay plugins, so they were adapted (that resulted on cleaner code).
I added a bunch of tests in `selftests/unit/test_datadir.py.DataDirTests`. I thought in maybe create another test class on same module but I hold that change so that I could get a quicker overall feedback on those changes first.
---
Changes v2 -> v3:
* Fixed style (missing and trailing newline)
* Fixed `optional_plugins.loader_yaml.tests.test_yaml_loader.YamlLoaderTests.test_replay` that was using the full job log path as a reference to the job results dir.
Changes v1 -> v2: fixed …

Move methods from jobdata to data_dir and refactor [v3]

---

avocado/core/job.py
avocado/core/nrunner.py
avocado/core/resolver.py
avocado/plugins/assets.py
avocado/plugins/nrun.py
avocado/plugins/runner_nrunner.py
examples/jobs/nrunner.py
selftests/unit/test_job.py
setup.py

This introduces a "job compliant test runner" based on the nrunner.  It still lacks a number of features, such as:
* Variants
* Test type support for anything available outside of the core "avocado.core.nrunner" module
* Proper result collection and storage
And many other features.  But, it lays a skeleton of an implementation that we can work with.  The only way to use it right now is to run the supplied `examples/job/nrunner.py` job file.

Nrunner: introduce a job compliant runner

---

selftests/deployment/roles/common/tasks/repos.yml

When you have Fedora modules enabled, Avocado package will be installed
from modules instead of the ones in the COPR or Official. This change
will disable fedora-modular and fedora-updates-modular repos during this
deployment.
----
* Converted int to str

selftests/deployment: Disable fedora-modular repos [v2]

---

selftests/functional/test_output.py
selftests/functional/test_plugin_jobscripts.py
selftests/functional/test_streams.py

There are a number of selftests that assume that the stderr should
never contain anything.  In truthfulness, that is more appropriate
to the stdout, once the stderr can produce content even when a
silent operation is requested.
On some other cases, the intention of stderr is mixed with that of the
stdout, like attempting to parse JSON from stdout and from stderr.
The content that goes to stderr can include any type of error
messages, and will not conform or be part of the intended JSON
produced by the JSON result plugin.
This fixes errors such as:
```
ERROR: test_output_compatible_setup (selftests.functional.test_output.OutputPluginTest)
----------------------------------------------------------------------
File …
```

selftests: acknowledge the use of stderr for its natural purpose

---

selftests/deployment/roles/common/tasks/aexpect.yml
selftests/deployment/roles/common/tasks/dependencies.yml
selftests/deployment/roles/common/tasks/main.yml

Since that python3-aexpect is only available on fedora module, we need
to install it before disabling the module.
----
* Changed from latest to present

selftests/deployment: installing aexpect first [v2]

---

docs/source/quickstart/index.rst

Because PyPI will complain if a module description can not be rendered
as proper reStructuredText.
In the future, we may consider having a different module description
instead, so that the quickstart document will not be limited to pure
reStructuredText content.

README/quickstart: downgrade to pure reStructuredText

---

docs/source/quickstart/index.rst

For some awkward reason, the docs badge stopped working without the last backslash on the target link.

Add a backslash to the link of the docs badge.

---

avocado/plugins/run.py

Removed some duplicated strings on warning messages.

small fix: removed duplicated strings on warning messages

---

docs/source/guides/user/chapters/concepts.rst
docs/source/guides/user/chapters/loaders.rst

The NextRunner introduces new concepts that can mix up with the current
ones. This small change adds a note to our documentation to warn our
users about that.
---
* Removed `nrun` and `run` association

docs: added a note warning about new concepts [v2]

---

avocado/core/nrunner.py
avocado/core/nrunner_avocado_instrumented.py
optional_plugins/robot/avocado_robot/runner.py
selftests/unit/test_nrunner.py

The NextRunner will be a core component of Avocado and we could try to keep the code as clean as possible to facilitate the understanding and readability. This changes only the order of a few methods and moves other ones to the respective classes.
---
* Fixed missing changes on nrunner_avocado_instrumented.py
* Merged tests changes into respective commits

small nrunner refactoring [v3]

---

selftests/unit/test_nrunner.py

'"command"' is not a valid sequence of arguments (from the Python interpreter
perspective).

tests/nrunner: removed unnecessary double quotes

---

docs/source/guides/contributor/index.rst

docs: Remove double index reference to RFC on Contributor's Guide.

---

avocado/core/sysinfo.py

Currently when a sysinfo's triggered command does not exit in the system the job's
log get printed with the Python exception. Instead let's print an user-friendly
message stating that the command is not found.
Before this change
```
2020-01-29 10:23:04,769 sysinfo          L0445 INFO | Profiler disabled
2020-01-29 10:23:04,782 sysinfo          L0172 WARNI| Could not execute "numactl --hardware show": [Errno 2] No such file or directory: 'numactl' (numactl --hardware show): 'numactl'
2020-01-29 10:23:04,795 sysinfo          L0105 DEBUG| Not logging /sys/kernel/debug/sched_features (file does not exist)
2020-01-29 10:23:04,797 sysinfo          L0105 DEBUG| Not logging /proc/pci (file does not exist)
2020-01-29 10:23:04,798 sysinfo          L0105 DEBUG| Not logging …
```

avocado/core: sysinfo: Improve the log message when the command is not found

---

avocado/core/data_dir.py
avocado/core/plugin_interfaces.py
avocado/core/resolver.py
avocado/utils/configure_network.py

Fix the following warnings when running `make html` to build html documents:
```
/home/wrampazz/src/avocado/avocado.dev/avocado/core/data_dir.py:docstring of avocado.core.data_dir.get_job_results_dir:5: WARNING: Unexpected indentation.
/home/wrampazz/src/avocado/avocado.dev/avocado/core/data_dir.py:docstring of avocado.core.data_dir.get_job_results_dir:6: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/wrampazz/src/avocado/avocado.dev/avocado/core/plugin_interfaces.py:docstring of avocado.core.plugin_interfaces.Resolver.resolve:7: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/home/wrampazz/src/avocado/avocado.dev/avocado/core/resolver.py:docstring of avocado.core.resolver.ReferenceResolution:14: WARNING: Field list ends …
```

docs: Fix warnings when running `make html`

---

docs/source/quickstart/index.rst

GitHub was rendering as a quote few parts of our quickstart. This small
change removes unnecessary spaces.

docs/quickstart: fixed indentation

---

avocado/core/nrunner.py

Because argparser will attempt to parse arguments that start with a
dash as yet another option, instead of the value to the '-a' option,
we need to escape them.
This is a complement to 48826017e, which introduced this concept and
the decoding of base64 arguments, but failed to encode the necessary
ones when creating a list of arguments.

nrunner: escape command line arguments that stat with a dash

---

.packit.yml

- remove upstream_package_name - pypi name is not used for archives
- use alias for fedora chroots
- remove synced_files <- not used

Fix packit conf

---

.travis.yml

Which are failing because of permission denied errors outside of our control.

Travis Ci: disable PIP cache for s390x and aarch64

---

docs/source/guides/contributor/chapters/environment.rst

Today, in order to install selfttests-requirements we need make and libvirt-devel. Without this, make requirements-selftests will fail. This will add this instruction to our contributor guide.

docs: Improve contributor usability with some explicit requirements

---

optional_plugins/html/setup.py

Because jinja2 drops support of python 3.5 with the new version, we have to
stay on the jinja2 older version with python 3.5 support. Because of this, we were having a problem with using HTML optional plugin on python 3.5

Specific version for jinja2 package

---

avocado/plugins/config.py
avocado/plugins/diff.py
avocado/plugins/list.py
avocado/plugins/plugins.py

Currently, --paginator and --verbose are configured locally by few
plugins but used globally (due to the argparse design). With the new
settings module being implemented, we need to put everything inside a
'settings namespace'. During a meeting discussion, we agreed that
--paginator and --verbose should be a global option. This just add a
warning message for this future change.
----
* Only a small typo error

added verbose and paginator deprecation message [v2]

---

avocado/plugins/journal.py

journal plugin was not considering --journal option. It was always
creating the journal file, even when --journal it is not present. This
change will take into consideration this option.

plugins/journal: Fix journal plugin to consider command line parameter

---

avocado/core/decorators.py
selftests/functional/test_skiptests.py

This commit expand the avocado.skip* decorators from methods to classes.
When a user uses skip decorator on the class, the decorator is applied
to every class method.
Reference: https://github.com/avocado-framework/avocado/issues/3473
---
Changes from v1 (#3566):
- Deletion of unused variable `value`
- Usage of `isinstance(obj, type)`

Avocado.skip* usable on classes [v2]

---

avocado/core/nrunner_tap.py
selftests/unit/test_nrunner.py
setup.py

The first draft of a TAPRunner for the Next Runner.  This is using the
`tapparser` module to process TAP outputs. More improvements will come
here.
---
Changes from v3:
* Split TAP runner into its own script (given that it requires Avocado libraries, as this follows the current model as per `nrunner_avocado_instrumented.py`).
* Merged commits;
* Using `/bin/sh` instead of `/bin/bash` on tests;
* Tests are now checking if `/bin/sh` exists, otherwise will skip;
* Using the current "status approach". `status` instead of `result`;
* Removed `aborted` status;
* Added a better docstring;
* Added tests;
* Removed `encoding` argument from `subprocess.Popen` since that is only available on `>=python3.6`

nrunner/tap: implementing a TAPRunner first version [v4]

---

python-avocado.spec

Even though we adjusted some tests to be less strict about the output
produced by Avocado, we currently ignore those on:
* make check
* Travis CI
So it seems fair that the other place that runs those tests (during an
RPM build) do the same.
BTW, these "Python warnings" are really tips that Avocado itself gives
to users, for instance, with regards to upcoming deprecation of features.

python-avocado.spec: ignore Python warnings when running tests

---

python-avocado.spec

Which was introduced in a0f64cf3f, but it wasn't packaged.
This failure wasn't caught at the same time the script was introduced
because the packit system had a different failure at that time.

python-avocado.spec: package avocado-runner-tap

---

docs/source/guides/user/chapters/installing.rst
docs/source/quickstart/index.rst

1. Minor update aligning references to official documentation and sections.
2. For users not familiar with pip give a hint how to call `avocado` after
running `pip install --user ...`
Signed-off-by: Sebastian Mitterle <smitterl@redhat.com>

Update quickstart doc

---

avocado/utils/pmem.py

Patch adds PMEM library support to manage persistent memory using ndctl and daxctl binaries. This patch allows managing pmem devices such as creation, deletion, enabling, disabling and re-configuring both namespaces and regions depending on supported hardware.

Added PMEM library support

---

avocado/utils/asset.py

This exposes `find_asset_file` private method and removes the necessity of a parameter to call it, adding the necessary logic to this method itself. Also, it removes duplicated logic from `get_metadata` method after the changes on `find_asset_file`.
This is a pre-work for extending the Asset module to allow the skip of a test if an asset is not available.

Misc Asset: Expose find_asset_file method.

---

avocado/utils/ssh.py
examples/apis/utils/ssh.py

Given that most of the value of the `avocado.utils.ssh` module has to do with creating the command lines that will execute on remote systems, it seems fair to expose that.  This seems to be one way to allow for many use cases without bloating the API or introducing much complexity.
Related to https://github.com/avocado-framework/avocado/pull/3578

SSH: expose raw commands generated

---

avocado/utils/pmem.py
selftests/unit/test_utils_pmem.py

This is a simple set of simplifications to the `avocado.utils.pmem` module.
---
Changes from v1 (#3599):
* Use return from `avocado.utils.path.find_command` to set the binary paths

avocado.utils.pmem: do not init, use which or shell [v2]

---

avocado/utils/pmem.py

And not the given parameter, in accordance to the same logic used for
ndctl.

avocado.utils.pmem: use absolute location for daxctl binary

---

avocado/utils/ssh.py

I've only one doubt about use the content of examples/apis/utils/ssh.py in the module's documentation because this example seems outdated (it is easier to use the `cmd` function). Nevertheless, looking forward your opinion.

utils/ssh: just a few improvements to API documentation

---

avocado/core/test.py
avocado/utils/asset.py
selftests/functional/test_test_fetch_asset.py

This extension allows the user to choose if the `fetch_asset` core method should move the asset to the cache or should just look for the asset in the cache.
The user can cancel the test when the asset is not available in the cache or when there was a problem adding the asset to the cache.
---
Changes from v4:
- Small refactor to remove duplicate code.
Changes from v3:
- Changed the behavior of `fetch_asset_file` on Asset class to raise an exception instead of returning `None`.
- Handle the exception from `fetch_asset_file` on `fetch_asset` core method.
- Refactor `get_metadata` to reduce code.
- Add comments.
- Remove the explicit calls to the cancel exception.
- Fix string formating for the log message.
- Add …

Extends fetch_asset core method to find assets and cancel the test. [v5]

---

selftests/unit/test_job.py

When running selftests, two unit tests from the Job class are throwing `No test references provided nor any other arguments resolved into tests. Please double check the executed command.`
error message to the output. The messages were suppressed by this change when the run method from the Job class is called to avoid polluting the output.

Temporarily suppress console errors on Job unit tests.

---

avocado/utils/ssh.py

It was never the intention, AFAICT, to capture and supress the
exceptions that could occurr during the use of an ssh.Session()
instance as a context manager.  But, because it was returning True,
that was effectively what was happening.
By not returning True, any exceptions that happen during the context
will be propagated.
Reference: https://docs.python.org/3/reference/datamodel.html#object.__exit__

avocado/utils/ssh.py: do not capture and supress exception at __exit__

---

avocado/utils/software_manager.py

`avocado-software-manager` is now a script we ship, so it should be useful to users. Unfortunately, there's no output being generated at this point.
This basically does a few refactors, and then initializes the logging when `main()` is used.
---
Changes from v1 (#3604):
* Replaced `executable` for `self.base_command` in first commit

Software manager: refactors and make avocado-software-manager useful [v2]

---

avocado/utils/asset.py
selftests/functional/test_utils_asset.py

Other public methods from Asset class were changed to throw an exception instead of returning `None` when the action expected from the method fails. The only method still returning `None` is `get_metadata`. This changes the behavior to throw an exception instead of returning `None`.

Misc Asset: update get_metadata to throw an exception.

---

avocado/utils/asset.py

Changes introduced by this third round of refactoring in the Asset class:
- move repeated operations to the constructor.
- change `_get_relative_dir` method to used attribute.
- avoid handling strings on `_get_relative_dir`.
- rename class attribute `parsed_url` and `basename`.
- remove unnecessary attribute `self.cache_relative_dir`.

Asset refactoring round 3

---

avocado/utils/configure_network.py
avocado/utils/gdb.py
avocado/utils/network/common.py
avocado/utils/network/exceptions.py
avocado/utils/network/hosts.py
avocado/utils/network/interfaces.py
avocado/utils/network/ports.py
selftests/unit/test_utils_network.py

Multiple pull requests were trying to add more features to this library.
But because of a lack of convention, it was getting hard to understand
this and we were losing usability. Besides a complete rewrite here, this
pull request is a) adding a complete set of methods to handle network
interfaces parameters; b) adding a wait when setting MTU values on
interfaces; and c) better support for IPv6.
Thanks to @anascko, @vaishnavibhat, @PraveenPenguin, and @smruti77
-----
* Implemented LocalHost and RemoteHost
* Small fixes on documentation
* Converted `_run_command` to `run_command`
* Fixed _connect() method to raise exceptions when fails

utils/network: Big refactoring on network library to improve consistency [v3]

---

requirements-selftests.txt

psutils is only used by selftests but psutil through 5.6.5 can have a
double free.  This occurs because of refcount mishandling within a while
or for loop that converts system data into a Python object.

fixes CVE-2019-18874

---

.travis.yml
Makefile

For some reason runing tests with PYTHONWARNINGS=ignore on python3.6
will hang some tests (this is not happening on 3.7). In anycase, we
should not ignore warnings during the tests but writer proper tests to
take this warnings into consideration.

python warnings: fixes tests on python 3.5 and 3.6

---

avocado/utils/configure_network.py
avocado/utils/network/__init__.py

In order to keep compatibility with third-party projects, this change
will bring back old network modules and will also add an alert
deprecation warning message.  

utils/network: bring back configure_network and network

---

selftests/functional/test_plugin_assets.py

With the change on the mechanism to build the url, the hash for the asset location has changed and was not corrected in this test.

Misc Asset: fixes the asset plugin success test.

---

python-avocado.spec

Commit 8f658866 removed most of the PYTHONWARNINGS set during
selftest executions, but missed this one in the spec file.

SPEC: remove PYTHONWARNINGS from rpm builds

---

avocado/utils/configure_network.py
avocado/utils/network/__init__.py

By mistake I introduced a comma to split a long string. This was
sending a tuple to warnings.war() method. This change will just remove
the comma from the long string.

utils/network: fixed long string on warning message

---

avocado/plugins/assets.py

If there are multiple test classes in the same file, the current method pointer is not reset when parsing the next test class in the file. This may cause a KeyError exception when there is an assignment in a class attribute in the following class.

Plugin Asset: reset method pointer when parsing a new class.

---

avocado/utils/network/interfaces.py

Some versions of iproute give us a different output when getting
interface details. This small fix will handle properly both output
formats.

utils/network: fixed get_interface on different iproute output

---

optional_plugins/html/avocado_result_html/__init__.py

code, this change only migrates the html optional plugin options to use
the new module. This will associate the '--html', '--open-browser',
'--html-job-result' to 'run.html_output', 'run.open_browser' and
'run.html_job_result' respectively on configuration file.

future/settings: Migrate html optional plugin to use the new API

---

optional_plugins/loader_yaml/avocado_loader_yaml/__init__.py

code, this change only migrates the loader_yaml optional plugin options
to use the new module. This will associate  --mux-suite-only and
--mux-suite-out to 'run.mux_suite_only' and 'run.mux_suite_out'
respectively. on the configuration file.

future/settings: Migrate loader_yaml optional plugin to use the new API

---

avocado/plugins/vmimage.py
avocado/utils/vmimage.py
jobs/release.py
selftests/functional/test_plugin_vmimage.py
selftests/release/vmimage.py
selftests/release/vmimage.py.data/variants.yml
selftests/unit/test_utils_vmimage.py

The `avocado.utils.vmimage` library allows users to fetch images for Operating Systems that should be capable of being executed as virtual machines. It retrieves those images directly from the organizations that publish them. But, the hard truth, is that those organizations change the structure from time to time.
To avoid releasing Avocado with vmimage "providers" broken, and to make it clear what we have tested and "support", this introduces a "release job" and release tests. Those tests are expected to take longer to run and require more resources, such as network access. To run the release job, one just needs to:
```
./jobs/release.py
```
Subsequent to this, the idea is to publish the list of images being tested for support with the documentation. LTS releases may receive backports …

vmimage: add complete online coverage [v2]

---

avocado/utils/cpu.py
docs/source/releases/lts/next.rst
selftests/unit/test_utils_cpu.py

cpu vendor logic for PowerPC is wrong since long time,
instead of `ibm` method was returning the cpu version, this
patchs fixes the same and adds a new method to return the
cpu version, similarly the method to get cpu arch even did the
same thing in case of PowerPC, so fixed that too.
While refactoring, based on community suggestions,
have unified naming conventions across arch accordingly.

Refactor cpu library to adopt common naming convention across arch

---

avocado/core/nrunner.py
avocado/plugins/nrun.py
avocado/plugins/runner_nrunner.py
selftests/unit/test_nrunner.py

The current nrunner execution model is one such that it "fires (a task) and forgets" about it. It hopes that they will eventually return information to the status server, but the universe conspires against that.
This implements some foundation work so that we can keep track of the "alive" status of a task. This status is not used to its full potential, as it requires the status server (or a replacement to it) to keep checking if spawned tasks that have not responded (yet?) are still alive.  This is expected to be the implemented following this.
---
Changes from v1 (#3685):
* Renamed candidate variable to candidate_cmd in pick_runner_command()
* Moved check_runner_command_candidate() function to a Task method by
the name is_kind_supported_by_runner_command
* Renamed runner variable to …

N(ext)Runner: implement foundation for keeping track of tasks [v2]

---

avocado/utils/asset.py

When there is a problem downloading an asset, there is no need to remove the temporary file as it was never created. This issue was masking the real download problem.

Misc Asset: return correct fail during download problems.

---

avocado/core/nrunner.py
avocado/core/nrunner_avocado_instrumented.py
avocado/core/nrunner_tap.py
avocado/plugins/nrun.py
optional_plugins/robot/avocado_robot/runner.py
selftests/functional/test_nrunner.py
selftests/unit/test_nrunner.py
selftests/unit/test_test.py

`status` keyword in `avocado-runner-*` is being used for both: runner execution status and test result status.
After fix `avocado-runner-tap` output will be:
```
$ avocado-runner-tap runnable-run -k "tap" -u "/bin/sh" -a "/tmp/foo.sh"
{'status': 'running', 'timestamp': 1585773826.9089062}
{'status': 'running', 'timestamp': 1585773828.913483}
{'status': 'finished', 'result': 'pass', 'returncode': 0, 'timestamp': 1585773828.9147718}
```
`make check` passed: [job.log](https://cpaste.org/?ce009b9759f250cf#5JjRo1QKvpT7NBBbQdQpg5KaEaqusyHfdNmHFJVjsWKA)
One more test `test_runner_tap_error` added:
`Task complete (pass): 143-selftests.unit.test_nrunner.Runner.test_runner_tap_error`
Issue: https://github.com/avocado-framework/avocado/issues/3547
---
This is a rebase of #3692 to solve conflicts, …

NextRunner: Remove the ambiguity of "status" and introduce the "result" keyword

---

avocado/plugins/assets.py
selftests/functional/test_plugin_assets.py

When the command `avocado assets fetch` fails to download one of a list of assets, it ends with return code different from 0.
It may be useful to allow the command to end with a 0 return code, independent of any problem it had during the download execution. This allows, for example, Travis CI to continue.

Plugin Asset: introduces --ignore-errors to assets fetch command.

---

optional_plugins/html/setup.py

The new MarkupSafe 2.0.0 do not support Python 3.5. We need to restrict MarkupSafe version to 1.x.

Fix Jinja2 dependency of MarkupSafe to support Python 3.5

---

selftests/release/vmimage.py.data/variants.yml

And make the YAML tree structure more coherent, by using shorter
versions in the upper nodes and the full version in the value only.

release selftests: update the version of Debian supported vmimage

---

selftests/functional/test_output_check.py

There's only one path component given, so it's unnecessary.

test_output_check.py: drop unnecessary use of os.path.join()

---

optional_plugins/glib/setup.py
optional_plugins/golang/setup.py
optional_plugins/html/setup.py
optional_plugins/loader_yaml/setup.py
optional_plugins/result_upload/setup.py
optional_plugins/resultsdb/setup.py
optional_plugins/robot/setup.py
optional_plugins/runner_docker/setup.py
optional_plugins/runner_remote/setup.py
optional_plugins/runner_vm/setup.py
optional_plugins/varianter_cit/setup.py
optional_plugins/varianter_pict/setup.py
optional_plugins/varianter_yaml_to_mux/setup.py

Right now the requirements from plugins only state that they need
avocado-framework.  But, changes between versions can cause
incompatiblity between plugins and Avocado proper.  This enforces a
stricter and safer approach that matches the Avocado and plugin
versions.

Optional plugins: require the same Avocado version

---

avocado/core/nrunner.py
avocado/core/nrunner_avocado_instrumented.py
selftests/unit/test_nrunner.py

This, besides fixing some unrelated issues (described in their own commits), implements a more coherent location for the registries of known runners, both in the command and class forms.
The commands are currently and usually used by an upper layer, such the current spawners, and the classes are used internally in the runner scripts. But, it should be possible in the future to also have classes being used by (most probably local only) spawners for increased efficiency.
---
Changes from v1 (#3712):
* Set the `status` key to `finished` on the final `avocado-instrumented` state message (@beraldoleal)

Nrunner: Runnable support for picking command or class [v2]

---

avocado/core/loader.py
avocado/core/nrunner.py
avocado/core/safeloader.py
avocado/plugins/resolvers.py
selftests/unit/test_safeloader.py

This adds support to use `requirement` docstrings to define a test requirement in JSON format.
- Moved unittests to the correct commit;
- Spell fixes;
- Removed support on loader and test class;
- Added more code to nrunner from https://github.com/avocado-framework/avocado/pull/3718#pullrequestreview-395075773.

Add support to `requirement` docstring [v2]

---

selftests/unit/test_datadir.py

There's currently one flaw with one of the data_dir tests, lacking in its ideal coverage. Also here, a few minor readability and style improvements.

selftests: fixes and improvements to data_dir tests

---

avocado/core/nrunner.py
avocado/core/nrunner_avocado_instrumented.py
avocado/core/nrunner_tap.py
avocado/core/spawners/common.py
avocado/core/spawners/podman.py
avocado/core/spawners/process.py
avocado/plugins/nrun.py
avocado/plugins/runner_nrunner.py
selftests/functional/test_nrunner.py
selftests/unit/test_nrunner.py

This pull request will introduce the ability to tests to see through the environment variable AVOCADO_TEST_OUTPUT_DIR where to write output results. This is part of #3695 and is the foundation to collect those results. Also, a small organization is proposed here, removing spawners from nrunner.py.
- Removed leftovers from a bad merge;
- Replaced `mkdir /uuid4()` with `mkdtemp()`;
- Moved unittest changes to the right commit;
- Calling self.prepare_status on other runners;
- Fixed kwargs vs env logic;

nrunner: exports to the tests a temporary output dir (and a small refactoring) - v2

---

avocado/utils/partition.py

Most of the recent kernels support bind mounting automatically, hence introducing a flag which allows user to skip the check of existing mounted devices or mountpoints.

Add bind flag to skip checking of mounting device/point

---

avocado/core/loader.py
avocado/core/nrunner.py
avocado/core/safeloader.py
avocado/plugins/resolvers.py
selftests/unit/test_safeloader.py

This adds support to use `requirement` docstrings to define a test requirement in JSON format.
- Add missing support to Python unittest resolver plugin.
- Moved unittests to the correct commit;
- Spell fixes;
- Removed support on loader and test class;
- Added more code to nrunner from https://github.com/avocado-framework/avocado/pull/3718#pullrequestreview-395075773.

Add support to `requirement` docstring [v3]

---

avocado/utils/cpu.py

and user want to do operation it will fail as python error (bash error)
and it feels user as lib is broken , so this patch address this
before this patch :
03:16:25 ERROR|   File "/home/OpTest/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/cpustress.py", line 103, in __online_cpus
cpu.online(cpus)
03:16:25 ERROR|   File "/usr/lib/python3.6/site-packages/avocado_framework-77.0-py3.6.egg/avocado/utils/cpu.py", line 256, in online
fd.write(b'1')

Added check in cpu utility is cpu is already online or offline

---

avocado/core/output.py

When using the job API (with runner or nrunner) the `job.log` is a empty
file.  However this is only happening when calling for the first time. I
don't understand the logic behind AVOCADO_LOG_EARLY, but looks like we
don't want to have a empty file when calling from the job api. This
small change will bring back the job.log file. Github issue #3737 has
more details.
Reference: https://github.com/avocado-framework/avocado/issues/3737

core/output: fix empty job.log when using the Job API

---

optional_plugins/result_upload/avocado_result_upload/__init__.py

code, this change only migrates the results_upload optional plugin
options to use the new module. This will associate  --results-upload-url
and --results-upload-cmd to plugins.result_upload.url and
plugins.result_upload.cmd respectively on the configuration file.

future/settings: Migrate results_upload optional plugin to use the new API

---

optional_plugins/resultsdb/avocado_resultsdb/__init__.py

code, this change only migrates the resultsdb optional plugin options to
use the new module. This will associate --resultsdb-api,
--resultsdb-logs, and --resultsdb-note-limit to
plugins.resultsdb.api_url, plugins.resultsdb.logs_url and
plugins.resultsdb.note_size_limit respectively on the configuration file.

future/settings: Migrate resultsdb optional plugin to use the new API

---

avocado/utils/gdb.py
selftests/unit/test_gdb.py

Instead of strings, which is a more honest approach to a "wire level" protocol and Python 3.
Relates to #3504 #3521 
---
Changes from v1 (#3733):
* Style fixes (too many and too little empty lines)
* Fixed references to `remote_encode` and `remote_decode` after functions have been moved to class methods.

GDBRemote: convert to use bytes [v2]

---

avocado/plugins/runner_nrunner.py

This will generate a basic output inside the tasks logdir.
-----
* Assuming that the last status will not always have 'stdout' and 'stderr';

nrunner: populate task logdir - v2

---

avocado/core/spawners/podman.py

With the new directory layout I forgot to fix the path join. There is no
more need for the 'core' part. This will fix the error "error evaluating
symlinks "": lstat ... no such file or directory".

nrunner: small fix on podman spawner

---

avocado/utils/external/gdbmi_parser.py
avocado/utils/external/spark.py
selftests/inspekt-style.sh

`has_key()` was deprecated in Python 2. It is recommended to use the
in operator instead.
This basically removes the global whitelist for W601, and fixes the
few occurrences where it happens.

Code style: enforce W601

---

optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py

After updating to Fedora 32, I started receiving this message while executing avocado command:
/home/wrampazz/src/avocado/avocado.dev/optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py:168: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if name is not '':
```
$ avocado
/home/wrampazz/src/avocado/avocado.dev/optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py:168: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if name is not '':
usage: avocado [-h] [-v] [--config [CONFIG_FILE]] [--paginator {on,off}] [-V] [--show [STREAM[:LVL]]]
{assets,config,diff,distro,exec-path,list,nlist,nrun,plugins,run,sysinfo,variants,vmimage} ...
Avocado Test Runner
optional arguments:
-h, --help            show this help message …
```

yaml to mux plugin: fix incorrect comparison.

---

avocado/utils/software_manager.py

software_manager.py: Add build dependency for DnfBackend
As --tolerant option is not supported with dnf-builddep, adding build dependency method to DnfBackend to fix this.

software_manager.py: Fix tolerant option with yum-builddep

---

avocado/core/nrunner.py
avocado/core/spawners/podman.py
avocado/core/spawners/process.py
avocado/plugins/nrun.py

The most important feature is a list of the failed/errored tasks, which currently usually requires a scrollback/search of the previous output.
---
Changes from v1 (#3753):
* Renamed `id_` variable to `task_id` (@beraldoleal)

Nrunner: improvements to the status server [v2]

---

avocado/utils/network/interfaces.py

This is a quick fix to bring back the simple backup method, without the
timestamp. This will avoid the directory of being full with a lot of
backup files. We still need to improve this backup routine in the near
future to support backup per interface.

utils/network: Bring back the simple backup method

---

avocado/core/app.py
avocado/utils/process.py
avocado/utils/vmimage.py

Just some quick workarounds/fixes found while trying to run Avocado on non-UNIX platforms.  This basically means adhering to what Python itself makes available on UNIX platforms, so it's a "strictness" improvement in itself.

Non UNIX portability improvements

---

avocado/utils/partition.py

Which seems to exist only because FileNotFoundError was not available
on Python <= 3.2, so it should have been removed alongside Python 2
support.

avocado/utils/partition.py: remove dead code

---

avocado/utils/network/interfaces.py

As we need to revert back the interface file when test completed
so added utility can be used for same

[V2]Add method which can be use for restore for interface file from backup

---

selftests/deployment/roles/avocado/tasks/pip/plugins.yml
selftests/deployment/roles/avocado/tasks/rpm/avocado.yml
selftests/deployment/roles/avocado/tasks/rpm/plugins.yml
selftests/deployment/roles/common/tasks/aexpect.yml
selftests/deployment/roles/common/tasks/dependencies.yml

On RHEL and Fedora, when we have the installation of multiple packages, let's use dnf instead given that we only support RHEL and Fedora versions already "dnf capable". That speeds up significantly the playbooks, given that all those packages will be attempted to be installed at once.
Also a couple of other cleanups.

Deployment checks: use DNF on Fedora and EL

---

optional_plugins/varianter_cit/avocado_varianter_cit/__init__.py

code, this change only migrates the varianter_cit optional plugin
options to use the new module.

future/settings: Migrate varianter_cit optional plugin to use the new API

---

avocado/core/loader.py
avocado/plugins/run.py
selftests/functional/test_basic.py

This is part of the BP001 and aims to replace all "string booleans" to
real booleans in the command-line. For now, I'm starting small only with
the '--ignore-missing-references' option.

convert to bool option: --ignore-missing-references

---

avocado/core/spawners/podman.py
avocado/core/spawners/process.py
avocado/plugins/nrun.py

This is a complement to e422cd52815f6b7a6afa73956a9da05014aec9db,
given that Avocado only supports Python 3.5 and later.

nrunner: update asyncio syntax usage

---

avocado/core/spawners/mock.py
avocado/core/spawners/process.py
avocado/plugins/nrun.py
selftests/unit/test_spawner.py

This increases the test coverage of the Spawners, by introducing a mock spawners that behave as expected (different than live Spawners which are suject to timing issues).
It was originally part of PR #3765, but was split here because the scheduler introduced there needs some more TLC. 
---
Changes from (#3785 ):
* Updated asyncio syntax
* Fixed small typo in commit message

nrunner: spawner improvements [v2]

---

avocado/utils/software_manager.py

Patch changes the approach to install the build dependencies as the existing method needs a work around suggested in redhat BZ https://bugzilla.redhat.com/show_bug.cgi?id=1717532#c28
As the bugzilla states, SRPM is generated in the build system on an x86_64 host and the Requires determined for the SRPM are set by the macros that are evaluated at the time of its creation. Because it is generated on an x86_64 host, the packages are added as a Requires to the SRPM. The yum-builddep command attempts to honor this.
The workaround is to install the kernel SRPM via rpm and run yum builddep on the kernel.spec file that is installed on the host. This ensure the proper macros are set for the architecture one
wishes to build for.

software_manager.py: Change approach to install dependencies

---

optional_plugins/varianter_pict/avocado_varianter_pict/__init__.py

code, this change only migrates the varianter_pict optional plugin
options to use the new module.

future/settings: Migrate varianter_pict optional plugin to use the new API

---

selftests/__init__.py
selftests/functional/test_basic.py
selftests/functional/test_interrupt.py
selftests/functional/test_loader.py
selftests/functional/test_sysinfo.py
selftests/functional/test_utils.py
selftests/unit/test_plugin_vmimage.py
selftests/unit/test_utils_process.py

That will consolidate the same message and checks at a common
location.

selftests: avoid duplication of skip blocks with a custom decorator

---

avocado/utils/cpu.py
selftests/unit/test_utils_cpu.py

This fixes an attempt to use a string regex with bytes coming
from the /proc/cpuinfo file.  Before this:
>>> cpu.cpu_has_flags('PowerNv')
File "/root/tests/avocado/avocado/utils/cpu.py", line 93, in cpu_has_flags
if not _list_matches(cpu_info, '.*%s.*' % flag):
File "/root/tests/avocado/avocado/utils/cpu.py", line 41, in _list_matches
match = re.search(pattern, content)
File "/usr/lib64/python3.6/re.py", line 182, in search
return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
>>>
Becase the regex being built is simply a presence check, we can skip
the regex and do just that, a presence check after decoding the
flag string into bytes.
Signed-off-by: Praveen K …

avocado.utils.cpu: fix bytes/string issue with cpu_has_flags

---

optional_plugins/runner_docker/avocado_runner_docker/__init__.py
optional_plugins/runner_remote/avocado_runner_remote/__init__.py
optional_plugins/runner_vm/avocado_runner_vm/__init__.py

The remote, vm and docker runner plugins (the ones that allows users
to run a job on those environments), all depend on the Fabric3, which
in turn depends on many other Python modules.  Fabric3 is dead with
the Python 3 compatible releases of fabric, but it requires an API
overhaul, very close to rewriting those plugins.
Maintaining those plugins is proving increasingly hard due to version
mismatch failures and bitrot, and the migration effort, given the
current plans of the Avocado project, is not really worth it.  With
the N(ext)Runner architecture, the goal is for *individual* tests to
be able to be executed in remote environments, so some of the
functionality may be brought back in the future, but under a very
different implementation, which may include even different
dependencies. …

Remote/VM/Docker runners: deprecate them

---

avocado/utils/disk.py

Fixed get_disks to return all block devices, like multipaths,
LVs, etc. Previously we used to get only /dev/sdX devices.
Reported-by: Naresh Bannoth <nbannoth@in.ibm.com>

avocado/utils/disk.py: Enhance get_disks

---

avocado/utils/stacktrace.py

We should avoid ambiguous variables names. Travis was complaining about
it.

fixed E741: ambiguous variable name 'l'

---

Makefile.include

Fedora 32 is no longer rawhide, but Fedora 33 is.  This fixes the
result of a "make MOCK_CONFIG=fedora-33-x86_64 rpm" command.

Makefile: update Fedora rawhide version

---

avocado/core/nrunner.py

This is a small refactor to make the list of commands available as a class attribute avoiding multiple resolutions and string manipulation when a command needs to be resolved.
Also, it changes a list comprehension by a list casting as it is faster.
Ps. this is related to my path to a full review and learning on the Avocado Nrunner architecture. If the code does not make sense, feel free to just close this PR.

Refactor base runner app

---

Makefile.include
docs/source/guides/user/chapters/installing.rst
examples/testplans/release/release.json
python-avocado.spec

We want to minimize our maintenance effort and avoid duplication, so let's stop building the deprecated plugins ASAP, and let's point users towards the distro repos, so that we can in the near future remove both the runners and Avocado's own repo.
This is related to https://github.com/avocado-framework/avocado/issues/3519

RPM Packages: don't build deprecated runners and drop mentions of "official" repos

---

avocado/plugins/sysinfo.py

When running the `avocado sysinfo` command, because of the current
"./" default, the logic that creates the custom "sysinfo-$timestamp"
directory is skipped, and the pre/post/profile directories are created
within the current working directory.  This is not the originally
intended behavior.
With this new default, users should have the previous experience again
(and a clearer expectation with the more verbose help message).

sysinfo: fix location of implicit directory creation

---

avocado/utils/pmem.py

With recent changes to ndctl utility, the behaviour for changed for disabling/destroying namespaces with "all"
Before recent changes, it always iterates idle namespaces
```
$ ndctl disable-namespace all
disabled 2 namespaces
$ echo $?
0
```
Now it returns failure even if idle namespaces are found
```
$ ndctl disable-namespace all
error disabling namespaces: No such device or address
disabled 0 namespaces
$ echo $?
250
```
With this check, command executes only if active namespaces are available

Check namespaces exists before command executes

---

optional_plugins/runner_remote/tests/test_remote.py
optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py

code, this change only migrates the varianter_yaml_to_mux optional
plugin options to use the new module.
This Pull Request also removes the `varianter_yaml_to_mux` dependency
from the `runner_remote` plugin.

future/settings: Migrate varianter_yaml_to_mux optional plugin to use the new API

---

avocado/core/nrunner.py

While testing the status server using telnet, when a `bye` is sent, it is translated to `b'bye\r\n'`, making the status server crash and not exit.
Do not crash the StatusServer when an unknown command or a malformed JSON is received.
Changes from [V3]:
- added a commit to handle unknown command or malformed JSON to avoid crashing.
Changes from [V2]:
- `strip` can handle it, no need to use `splitlines`.
Changes from [V1}:
- split the message with `splitlines`. This handles a good amount of separators.

Nrunner: Extend status server exit and command handling.

---

avocado/plugins/nrun.py

All plugins that generate output for users to see, that is, a UI,
should use avocado.core.output.LOG_UI, because of convention and
because it applies the core `--show` command option.
There's one instenace in the nrun plugin which was using print
instead, and this fixes it.

nrun: use LOG_UI instead of print

---

avocado/utils/multipath.py

json output is very huge for larger configuration which is making
difficult in debugging the script and actual issues. so disabled
the json output by adding verbose=False.

Disabled the json output print in multipath.py

---

avocado/core/job.py
avocado/plugins/run.py
examples/jobs/nrunner.py
examples/jobs/podman.py
jobs/timesensitive.py
selftests/unit/test_job.py

And some clarifications about a default runner being set and used by a job, as an exception.
Changes from v1 (#3816):
* Documented the `test_runner` attribute (new commit) 
* Set the default test runner early and once (new commit)

Job: allow the selection of the test runner by command line [v2]

---

avocado/core/nrunner.py

- Remove the task just if the status server is waiting for it;
- Follow the `handle_task_started` method pattern, printing just when `self.verbose = True`;
- Change the start message string from `Results` to `Status`, just like the other messages on this class.
Despite thinking that the `handle_task_started` and the `handle_task_finished` are placeholders for future development (as I don't think they are responsible for printing status, stdout, stderr, and output), let's make the methods behave the same way.

Nrunner: minor changes to the status server for consistency.

---

optional_plugins/result_upload/avocado_result_upload/__init__.py

The incorrect key caused the `--result-upload-cmd` option to be
ignored.

Fix incorrect option key in result_upload optional plugin.

---

avocado/core/output.py
avocado/plugins/human.py
avocado/plugins/jobs.py

Running a job, by means of `avocado run` produces a UI (handled by the human UI plugin).  It feels to me that the output should be more similar. This moves `avocado jobs show` closer to `avocado run`.
Also, during the development/review of #3829, a number of comments were made about using some utility methods also used by `avocado list` and others.
---
Changes from v1 (#3833):
* Squashed commits that change the `avocado jobs show` output to the final result

Avocado jobs show: move closer to human UI [v2]

---

avocado/core/job.py
examples/jobs/passjob_with_test.py

This feature can be easily replaced by the Job API, without using
hacks to protect the fork bomb, and doing things more explicitly.
An example job with a builtin test is here as an example.

Jobs: deprecate standalone jobs

---

avocado/core/loader.py
avocado/plugins/list.py
avocado/plugins/replay.py
avocado/plugins/run.py
docs/source/guides/user/chapters/loaders.rst

This will migrate --loaders, --external-runner, --external-runner-chdir and --external-runner-testdir to use the new API calls.
**Changes from v1:**
* Removed from user guide reference to `--loader ?`;
* Small typo fix on comment;
* Small typo fix on option help msg;
* Moved change to proper commit;

Migrate loader settings to use the new API (v2)

---

avocado/core/job.py
avocado/plugins/run.py
examples/jobs/passjob_html.py

Users of the Job API expect the result files (such as JSON, xunit,
HTML, or any other format implemented by installed plugins) to be
respected by the job configurations.
By moving the handling from the plugin that implements "avocado run"
to the Job itself, both users will be able to use them.

Job: assume the task of generating results

---

avocado/core/app.py
avocado/core/job.py
avocado/core/output.py
avocado/core/parser.py
optional_plugins/runner_remote/avocado_runner_remote/__init__.py
optional_plugins/runner_remote/tests/test_remote.py
optional_plugins/runner_vm/tests/test_vm.py
selftests/unit/test_job.py

code, this change only migrates the core option --show
option to use the new settings API.

future.settings: migrate --show to use the new API

---

avocado/core/job.py
avocado/core/sysinfo.py
avocado/core/test.py
avocado/plugins/runner.py
avocado/plugins/sysinfo.py
optional_plugins/html/avocado_result_html/templates/results.html
selftests/functional/test_export_variables.py
selftests/unit/test_job.py
selftests/unit/test_sysinfo.py
setup.py

The sysinfo feature has a well defined behavior, it runs before and after tests (all or each and every one), and it fits well into the pre/post plugins that Avocado has.
As described in https://github.com/avocado-framework/avocado/issues/3460, let's make sure we're using those plugin interfaces, and not hardcoded hooks.
Also, some sysinfo related style and minor consistency improvements on the HTML report.
---
Changes from v1 (#3846):
* The original PR was a single commit, with just one cleanup.

Sysinfo: use it as pre/post tests plugin and cleanups [v2]

---

Makefile

make requirements is an invalid target, right now. This small change
just remove the instruction on makefile.

small fix on Makefile: removed missing target

---

Makefile
avocado/core/__init__.py
avocado/core/job.py
avocado/core/parser.py
selftests/jobs/pass
selftests/jobs/tests/pass
selftests/unit/test_job.py

This restores the job API usage, which was broken by 89e07d6f6ffb3180851471f9e471d96d7212a7a2, and adds a job as selftests, to avoid regressions.

Job API: fixes and jobs as tests

---

avocado/utils/software_manager.py

Patch adds build_dep for ZypperBackend so that the function can be commonly used for any distro type from a test as
smm.build_dep(pkgname)

software_manager.py: Add build_dep for Zypper

---

avocado/core/future/settings.py
avocado/core/job.py
avocado/core/parser_common_args.py
avocado/plugins/list.py
avocado/plugins/nlist.py
avocado/plugins/nrun.py
avocado/plugins/run.py
selftests/pre_release/jobs/timesensitive.py
selftests/unit/test_future_settings.py

Which is needed to fix the `timesensitive.py` breakage with filtering by tags not being applied (or having a section name including `None`.
---
Changes from v1 (#3862):
* Added check in unittest for parser
* Renamed `filter_by_tags` section to `filter.by_tags`

Tags: make the registration of options generic to many commands [v2]

---

selftests/unit/test_job.py

**Note for reviewers**
This PR takes into account that we'll have, soon, a knob to change the test runner or test both at `make check` time.  For now, a reviewer has to edit the default runner at `avocado.core.job` manually to test it with the nrunner plugin.
Also, some failures in other unittests are fixed by other PRs that are under review.
---
When setting the "run.test_runner" configuration key to "nrunner",
these unittests for the job class fail to take into account that the
test suite will be comprised of nrunner.Tasks, instead of so called
"test factories".
This change takes that into account and makes the tests succeed.  It's
necessary, though, to manually set the runner to verify the fix.
It's expected that we'll add a full coverage for both test runner
implementations soon, and …

selftests/unit/test_job.py: fixes for using the nrunner plugin

---

avocado/core/job.py
avocado/core/test.py
avocado/core/test_id.py
avocado/plugins/nrun.py
avocado/plugins/runner.py
avocado/plugins/runner_nrunner.py
selftests/unit/test_loader.py
selftests/unit/test_test.py
selftests/unit/test_test_id.py

The Test IDs (and the resulting presentation and job results structure) is different when using the nrunner in a job.  This should make the behavior the same between both implementations.
---
Changes from v1 (#3868):
* Initialized task with a uuid, so that it always has a valid identifier

Nrunner: fix Test IDs [v2]

---

avocado/plugins/run.py
avocado/plugins/sysinfo.py
setup.py

The avocado.core.job module has been using future.settings for some
time now, instead of the legacy settings module.
While future.settings is able to read configuration files and merge
their content into the produced dictionary, it checks that the option
has been registered in the first place.
This adds one of the sysinfo configurations that are available on
the configuration file we ship, but that is not being registered.
A final version, if this approach is agreed upon, should include
all option in the configuration file.
Reference: https://github.com/avocado-framework/avocado/issues/3873

Sysinfo: register options so values from config are respected

---

avocado/core/future/settings.py
avocado/core/settings.py

The value of doing this is very questionable, because most users
will probably never change anything.  The users that want to do
so, can manually create a directory and file.
Reference: https://github.com/avocado-framework/avocado/issues/3541

Settings: do not attempt to create empty configuration value

---

Makefile
avocado/__main__.py
avocado/core/app.py
avocado/core/data_dir.py
avocado/core/main.py
avocado/plugins/jsonresult.py
avocado/plugins/tap.py
avocado/plugins/xunit.py
docs/source/guides/contributor/chapters/tips.rst
docs/source/guides/user/chapters/advanced.rst
docs/source/guides/writer/chapters/writing.rst
man/avocado.rst
optional_plugins/varianter_yaml_to_mux/tests/test_functional.py
python-avocado.spec
selftests/__init__.py
selftests/functional/test_basic.py
selftests/functional/test_job_api_features.py
selftests/functional/test_plugin_diff.py
selftests/functional/test_streams.py
selftests/jobs/pass
selftests/run_coverage
selftests/unit/test_jsonresult.py
selftests/unit/test_xunit.py
setup.py

This makes all the builtin result plugins use the same namespace, and allow the configuration to be set either via the Job API, configuration files or command line.
This is part of https://github.com/avocado-framework/avocado/issues/3795

Job API: standardize job run result namespace 

---

avocado/core/nrunner.py
avocado/core/spawners/common.py
avocado/plugins/jobs.py
avocado/plugins/runner_nrunner.py

This patch will fix the get-output-files logic on the next runner. After this, you will be able to download files that are executed using the `--test-runner=nrunner`.
In order to test this, you need to create a test that will generate any file inside the `$AVOCADO_TEST_OUTPUT_DIR` folder.
This is also adding an empty line when showing jobs details with `avocado jobs show` command.

nrunner: enable "avocado jobs get-output-files" command

---

avocado/utils/wait.py

As explained in the Python docs, and suggested in the referenced issue, this should make Avocado more reliable wrt times.  Running tests that play with the clock is not that uncommon, and this could improve the chances of Avocado not breaking under such conditions.
Reference: https://github.com/avocado-framework/avocado/issues/3565

avocado.utils.wait: use monotonic time

---

avocado/core/sysinfo.py
avocado/plugins/sysinfo.py

As part of the effort to remove default values scattered around the code, this change only migrates the remain sysinfo.collect options to use the new settings API.

future.settings: Migrate sysinfo.collect options to use the new API

---

avocado/core/nrunner.py
avocado/core/nrunner_avocado_instrumented.py
selftests/jobs/pass
selftests/jobs/tests/passtest.py
setup.py

If the `avocado.core.nrunner` module is being used by the Avocado Job, via the `avocado.plugins.runner_nrunner`, it can benefit from being on a system that has setuptools installed and can pick runner for runnables from there.
But, if the "nrunner" module is being executed by itself, let's say, on a remote system, it may not access to setuptools or entrypoints, so it should still rely on its internal runner registry.
This change allows the Avocado Job to run all ranges of test types (runnable kinds, really) currently supported.  This is true for executions without spawners and always local, which currently, in a job, it's the only way they're done.
This is related to https://github.com/avocado-framework/avocado/issues/3865

 N(ext) Runner: implement entry point based runner selection

---

avocado/core/future/settings.py

Avocado future settings misses package default config
file to be parsed, let's add it.
Fixes: https://github.com/avocado-framework/avocado/issues/3884
Reported-by: Narasimhan V <sim@linux.vnet.ibm.com>
Suggested-by: Cleber Rosa <crosa@redhat.com>

core.future.setting: Fixup: Add package default avocado config

---

optional_plugins/loader_yaml/tests/test_yaml_loader.py
selftests/__init__.py
selftests/functional/test_nrunner.py
selftests/unit/test_nrunner.py
selftests/unit/test_utils_process.py

By introducing a decorator that skips a test unless the file at the
path given as parameter exists.

Selftests: refactor skip condition for existing file

---

avocado/core/__init__.py
avocado/core/data_dir.py
selftests/unit/test_datadir.py
selftests/unit/test_plugin_vmimage.py

Besides migrating `datadir.paths.*` to use the new API, this also moves the logic of `intree` attribute from legacy `Settings` class to `data_dir` module as this is the only place that uses it. The new API does not have the `intree` attribute and, in my opinion, should not have for now.
This effort was explicitly to migrate the `datadir.paths.*` to the new API, but looking at `get_test_dir` function in the `data_dir` module, it seems to me that we will need to evaluate its logic with the new Settings API.
Changes from V1:
- Update unit tests to use settings with context manager instead of creating a function to register the options.
- Update description about in tree execution.

future.settings: Migrate datadir.paths.* to use the new API. [V2]

---

avocado/core/__init__.py
avocado/core/defaults.py
avocado/core/runner.py

future.settings: migrate runner.timeout.* to use the new API

---

avocado/core/sysinfo.py
avocado/etc/avocado/avocado.conf
avocado/plugins/sysinfo.py

Sysinfo files and commands are logged in pre and post. We can
optimize this by checking if the file or command output has
changed, and not logging when not changed.
Provided a parameter in avocado.conf to control this behaviour.

Optimize sysinfo by not logging duplicates in post

---

avocado/utils/linux_modules.py

Fix issue as if modprobe fails library is error out
ex:
File "/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/utils/linux_modules.py", line 56, in load_module
process.system('/sbin/modprobe ' + module_name)
File "/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/utils/process.py", line 1103, in system
encoding=encoding)
File "/usr/local/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/utils/process.py", line 1040, in run
raise CmdError(cmd, sp.result)
avocado.utils.process.CmdError: Command '/sbin/modprobe lkdtm' failed.
stdout: b''
stderr: b'modprobe: FATAL: Module lkdtm not found in directory /lib/modules/5.4.16\n'
additional_info: None …

Fix issue in linux_modules

---

.gitignore
avocado/core/future/settings.py
avocado/plugins/config.py
docs/Makefile
docs/source/config/index.rst
docs/source/index.rst

This will add a new command "avocado config reference" that will print
on output the current configuration reference guide in rst format. And
can be used to update our documentation.  This PR also change our
documentation to include this reference. There is room for improvements,
for instance we can soon split the configuration into sections and also
give the ability to download a config file template.

future.settings: added a 'reference' option to the 'config' command-line

---

avocado/core/future/settings.py
selftests/unit/test_future_settings.py

This is using the ast module to eval lists as lists in python (using
single or double quotation marks). In the near future we can replace
this eval with a more inteligent and save method.

future.settings: brings back the previous parsing method for lists

---

avocado/core/__init__.py
avocado/core/enabled_extension_manager.py

This leverages the information about the plugin types registered with
setuptools (which is mandatory and follows a pattern) to register the
name of the sections that will control the order of such plugins.
Then, together with the disable list, those are registered once at
the usual location for other core options.

Plugins: migrate disable and order configuration to the new settings

---

avocado/plugins/config.py
docs/Makefile
docs/source/conf.py

Which doesn't do builds by makefiles, but by using conf.py only. So,
currently, at:
https://avocado-framework.readthedocs.io/en/latest/config/index.html
The config reference is now being shown, and this is a fix.

Docs: show configuration reference on builds done at readthedocs.io

---

avocado/core/future/settings.py

Instead of trying to create the name from the option instance
information.  While at it, rename the tag variable appropriately.
---
Changes from v1 (#3954):
* Replaced try/except block with dictionary presence check

Future Settings: reuse the namespace already available [v2]

---

python-avocado.spec

The command we use on the Makefile to generate a tarball:
git log --pretty=format:'%h' -n 1
Depends on the git behavior, and it has changed the number of
charatecters it uses.  So, we need to add an extra character on the
spec file too.

SPEC: add one extra digit to the short commit

---

avocado/core/future/settings.py

When _value is 0, the value property returns the default value instead of the correct _value.

Future Settings: check if _value is None into value property.

---

Makefile

git changes, from time to time, that is, from version to version, the
meaning of the '%h' formatting string, for short commits.  This
attempts to make it more stable.
BTW, git will use the minimum amount of charatecters needed to
uniquely identify a commit.  We hope that 9 charatecters will be OK
for now.

Makefile: make the short commit of a more predictable size

---

.travis.yml

Upon job validation, Travis shows:
root: missing os, using the default linux
root: key matrix is an alias for jobs, using jobs
Let's help it out, and give/use those keys/values.

Travis CI: provide missing/default key names

---

avocado/core/job.py
avocado/core/plugin_interfaces.py
avocado/plugins/run.py
avocado/plugins/runner.py
avocado/plugins/runner_nrunner.py
selftests/functional/test_job_timeout.py

With the progress that we made on Avocado's config dict we can now pass the entire dict to methods and avoid long method signatures. We have here also an attempt to reduce the lines on the `__init__()` method to improve code readability and maintainability making some attributes a `@property` (since our configuration is now via the `config` dictionary, those changes will protect the properties and avoid unwanted setters).
This is part of bigger refactoring to allow run jobs with multiple suites.
**Changes from v1:**
- Fixed the `time_to_seconds()`: now it is being called at register_option;
- Removed `()` (parentesis) at import line;
- Fixed commit log message;
- Added a few commits to convert some attributes to a `@property`;
- Migrates the registration of run.job_timeout from …

core: small refactoring on job.py and a smaller run_suite() signature (v2)

---

avocado/utils/gdb.py

Remote protocol specification states that the checksum should be two-digit.
This patch fixes one-digit checksum formatting.

GDB Remote: fix checksum format

---

avocado/core/sysinfo.py
avocado/core/test.py
avocado/plugins/sysinfo.py

sysinfo collectibles were being collected in case of all test
results. But we need to collect some data in case of test failures
only. Introduced a way to do that.
v3 of #3874 

Way to provide sysinfo in case of test failure [v3]

---

avocado/utils/pmem.py

This reverts commit 3038c8fb75f0eda2651c11aed3b3743caf2ada47. As the reason for the above commit to actually include this fix is declared a bug.
This is not expected to happen with any device and it was a bad stack update.
$ ndctl disable-namespace all
error disabling namespaces: No such device or address
disabled 0 namespaces
So removing the unnecessary changes.

Revert "Check namespaces exists before command executes"

---

avocado/core/job.py
avocado/core/loader.py
avocado/plugins/list.py
optional_plugins/loader_yaml/avocado_loader_yaml/__init__.py

A instance of `argparse.Namespace` has been used for a long time as
the main source of configuration, and that name is still present in
many places in the code.
We're now at the point where all configuration (but a few exceptions,
before the complete settings module is initialized and generates a
configuration) comes from the "avocado.core.future.settings" module,
and it may not even have a argparser or command line option
contributing to it.
So, let's rename those "args" occurences to "config" which is now
the unified output of the settings module.

Rename args to config

---

examples/jobs/passjob_html.py
optional_plugins/html/avocado_result_html/__init__.py

Other result plugins follow the pattern `job.run.result.'plugin'.enabled`. Examples:
- `job.run.result.json.enabled`
- `job.run.result.tap.enabled`
- `job.run.result.xunit.enabled`

HTML plugin: change option to comply with other plugins.

---

avocado/core/job.py
avocado/core/resolver.py
avocado/core/suite.py
avocado/core/utils.py
avocado/plugins/assets.py
avocado/plugins/nrun.py
selftests/unit/test_job.py

This is an attempt to organize and prepare the code to support multiple suites in a single Job. Each TestSuite will have its own configuration.
- Fixed some imports on the respective commits;
- Removed "fix lint" commit since that was not necessary anymore;
- `from_config()` now has only one argument (`config`);
- Replaced enum with `object()` values;
- `convert_to_dry_run()` is only executed with the current runner;
- Added some tests to stress the `suite.status` values;
- Converted a few methods to private;

core: Introduces the TestSuite() class and small refactoring (v2)

---

setup.py

In function log_plugin_failures() of output.py, failure[0] is
an instance of EntryPoint.
In the previous version of stevedore, the EntryPoint is
pkg_resources.EntryPoint. In the latest released stevedore-3.0, 
EntryPoint is actually importlib_metadata.EntryPoint, which doesn't
have the attribute 'module_name'. Pinning stevedore under version
3.0 could fix this problem.
Signed-off-by: Haijiao Zhao <haizhao@redhat.com>

Fixup: Pin stevedore to a version under 3.0 before API change

---

requirements-selftests.txt

As pylint is already pinned, and without this, an incompatible version
(with pylint) may be fetched and installed.

Pin isort version when running tests

---

avocado/core/sysinfo.py
docs/source/guides/user/chapters/introduction.rst

sysinfo collectibles commands generate not only outputs, but also
files. The output is stored in appropriate test sysinfo directory,
but not the files generated.
Now, with the introduction of new environment variable
AVOCADO_SYSINFODIR, the sysinfo commands can use them to place the
directory appropriately.
This new environment variable takes care of pre/post as well.
This was to handle the issue from:
https://github.com/avocado-framework/avocado/issues/3977

sysinfo: Introduce AVOCADO_SYSINFODIR

---

avocado/utils/lv_utils.py

The functions vg_ramdisk() and vg_ramdisk_cleanup() were more
complex in what they did, assuming loop devices and trying to
boost performance, though there was little evidence. There
was no obvious benefit in terms of the operation it performed
as well. The code maintainence was also becoming more complex.
So deprecating it, and encouraging to use the individual
functions instead.
Check the pull request for more details:
avocado-framework/avocado/pull/3857

lv_utils: deprecate vg_ramdisk, vg_ramdisk_cleanup

---

avocado/utils/ssh.py

add scp_connection() and scp_cmd() to ssh.py for copy file to
remote and from remote through session.

passwordless scp add function to ssh.py

---

avocado/core/varianter.py
optional_plugins/varianter_yaml_to_mux/tests/test_functional.py

This patch address the below reported issue on
test name not having complete variants tag names.
Now we get all relevant variants tags included in
the test name which will be useful for result
analysis.
Fixes: https://github.com/avocado-framework/avocado/issues/3615

Fixup: Test name to include all variant tags

---

avocado/plugins/dict_variants.py
examples/jobs/sleepjob_dict_varianter.py
setup.py

This is a minimal and straightforward implementation of a varianter
that gets fed from a Python dictionary.
And example job is included, but there's currently no support for a
command line argument, as it's not that useful IMO to express a
dictionary in a commandline argument.

Variants: introduce Python dictionary based implementation

---

avocado/plugins/jobs.py

This is avoiding conflicts with names and fixes #3885.

output-files: create output files inside separated directories

---

optional_plugins/varianter_cit/tests/test_basic.py
selftests/__init__.py
selftests/functional/test_basic.py
selftests/functional/test_export_variables.py
selftests/functional/test_getdata.py
selftests/functional/test_interrupt.py
selftests/functional/test_job_api_features.py
selftests/functional/test_job_timeout.py
selftests/functional/test_journal.py
selftests/functional/test_json_variants.py
selftests/functional/test_loader.py
selftests/functional/test_lv_utils.py
selftests/functional/test_nrunner.py
selftests/functional/test_output.py
selftests/functional/test_output_check.py
selftests/functional/test_plugin_diff.py
selftests/functional/test_plugin_jobscripts.py
selftests/functional/test_replay_basic.py
selftests/functional/test_replay_external_runner.py
selftests/functional/test_replay_failfast.py
selftests/functional/test_skiptests.py
selftests/functional/test_statuses.py
selftests/functional/test_streams.py
selftests/functional/test_sysinfo.py
selftests/functional/test_teststmpdir.py
selftests/functional/test_unittest_compat.py
selftests/functional/test_utils.py
selftests/functional/test_utils_asset.py
selftests/functional/test_wrapper.py
selftests/unit/test_references.py

Which is a simple class that contains setUp/tearDown methods that create and cleanup a temporary directory for the test's usage.
It also changes into Avocado's base directory to allow for consistent execution, which is a common pattern and ensures these tests are more consistent among themselves.

Functional selftests: reduce code duplication by introducing TestCaseTmpDir

---

avocado/plugins/dict_variants.py

This adds support to values different than strings, like True or False, to be used in the dictionary.

DictVariants Plugin: cast value to string before join

---

avocado/utils/service.py
docs/source/conf.py
docs/source/guides/user/chapters/configuring.rst
docs/source/guides/user/chapters/installing.rst

When compiling our current documentation with make html we had some warnings #4017. This PR fixing them.
The problem was:
```
avocado/avocado/utils/service.py:docstring of avocado.utils.service.ServiceManager:6: WARNING: Error in "code-block" directive:
1 argument(s) required, 0 supplied.
avocado/avocado/utils/service.py:docstring of avocado.utils.service.SpecificServiceManager:5: WARNING: Error in "code-block" directive:
1 argument(s) required, 0 supplied.
avocado/docs/source/guides/contributor/rfcs/lts.rst:176: WARNING: undefined label: fedora-from-avocados-own-repo (if the link has no caption the label must precede a section header)
avocado/docs/source/guides/writer/chapters/writing.rst:1658: WARNING: undefined label: tests-api-reference (if the link has no caption the label must …
```

Documentation wannings fix

---

Makefile

The COPR builds are currently broken, because the git produces a short
commit id with a different number of digits then expected.
We'd solved this problem for the release buildson 335448380, but
missed the regular builds.

SRPM builds: enforce reproducible short commit IDs

---

docs/source/guides/user/chapters/concepts.rst

docs: add a note about references vs wildcard

---

docs/source/plugins/optional/varianter_yaml_to_mux.rst
optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py

When using --mux-inject, we parse the whole path, key and value
as one string. So, the value passed to test is always a string.
Fixed that by maintaining the data type using ast.literal_eval().
V2 of https://github.com/avocado-framework/avocado/pull/3988, with documentation added.
Reported-by: Harish <harish@linux.ibm.com>
Suggested-by: Satheesh Rajendran <sathnaga@linux.vnet.ibm.com>
Tested-by: Harish <harish@linux.ibm.com>

mux-inject: Maintain data type of injected value [v2]

---

.copr/Makefile

On commit 26b4ed895 the generation of the short commit IDs was fixed, but I
completely forgot that COPR makes use of a different Makefile.
Hopefully this third attempt will be the lucky one.
In the future, it'd be nice if both Makefile and .copr/Makefile rules
could be shared/combined.

SRPM builds: enforce reproducible short commit IDs on COPR

---

docs/source/guides/writer/chapters/parameters.rst
docs/source/plugins/index.rst
docs/source/plugins/optional/multiplexer.rst
docs/source/plugins/optional/varianter_yaml_to_mux.rst

In some time ago in #2312 there was a change in understanding the Mux module as
the main interface for the implementation of variant plugins and development
was targeted to the Avocado Varianter. But this change wasn't taken into
account in the documentation. This commit change that.

[Doc] Refactoring of Mux module

---

avocado/core/parser.py
avocado/plugins/variants.py

And its usage in the result configuration dictionary.
There are no really worthy justification of this.  Last minor one was
to allow plugins to handle the ancient default_params, which is no
longer used as early as 69.0LTS and should be removed following this.
Fixes: https://github.com/avocado-framework/avocado/issues/3981

Varianter: remove registration of avocado_variants in the argparse

---

avocado/core/safeloader.py
selftests/unit/test_safeloader.py

The safeloader is failing to keep track of relative imports, because a relative location has no explicit module name within the code.
To test that, we resort to parsing a functional test file that does a relative import for the TestCaseTmpDir class.
Fixes: https://github.com/avocado-framework/avocado/issues/4036

Safeloader: support relative imports in the PythonModule class

---

avocado/core/jobdata.py
avocado/core/plugin_interfaces.py
avocado/core/varianter.py
avocado/plugins/dict_variants.py
avocado/plugins/diff.py
avocado/plugins/json_variants.py
avocado/plugins/run.py
avocado/plugins/runner.py
docs/source/guides/writer/chapters/parameters.rst
docs/source/guides/writer/chapters/writing.rst
docs/source/plugins/optional/multiplexer.rst
optional_plugins/varianter_cit/avocado_varianter_cit/__init__.py
optional_plugins/varianter_pict/avocado_varianter_pict/__init__.py
optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py
optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/mux.py
optional_plugins/varianter_yaml_to_mux/tests/test_unit.py
setup.py

Both are ancient and correlated, seldom used, but makes us carry a lot of internal baggage.  Let's clean up the interface of varianters by dropping them.

Variants: drop update defaults and default parameters

---

optional_plugins/html/avocado_result_html/__init__.py

Currently, when running `avocado run`, the 'HTML RESULT' line is
printed, even if the job had no tests in the test suite and did not
really run.
The reason is that on 856c3b572 the TestSuite() class was introduced,
and with that, a different exception started to being raised when an
empty test suite was created.
When the new exception is handled, the job is set to FAILed, instead
of ERRORed.  We could change the exception or their handling, but I
think this side effect is actually a good thing.  A Job with an empty
test suite failed to proceed, but did not really ERRORed.
ERROR is currently reserved, and used in most cases, when things that
are not expected happen, and say, Avocado crashes.

HTML Plugin: adapt to job status when job has an empty test suite

---

avocado/utils/lv_utils.py

Providing automatic yes for vgcreate command, since vg creation
can fail if, say, a filesystem is already present.
Reported-by: Wen Xiong <wenxiong@linux.vnet.ibm.com>

lv_utils: Automatic yes for vgcreate command

---

docs/source/guides/writer/chapters/parameters.rst

In ecf253c45 we removed the default parameters, but forgot to remove
all the documentation.

Docs: drop section on default params which has been removed

---

avocado/core/loader.py
docs/source/guides/user/chapters/introduction.rst
docs/source/guides/user/chapters/loaders.rst
selftests/functional/test_loader.py

avocado run command line can accept options --loaders and --external-runner in
one time. But when we use external runner there is a specific loader and we
don't use values from option --loaders. When user uses both these options, we
have to warn him about this behaviour.
Reference: #3899
---
Changes from v1 (#4024):
* Typo fixes
* Documentation
* Tests
---
Changes from v2 (#4046):
* `assertTrue` to `assertIn`
* `assertFalse` to `assertNotIn`
* usage of `/bin/sh`
---
Changes from v3 (#4047):
* Usage of `@skipUnlessPathExists` when  the system doesn't have a `\bin\sh`

Warning of loader and external runner incompatibility [v4]

---

selftests/functional/test_job_timeout.py

Under the 5 seconds timeout that is specified in the job.  The best
way we can control the environment in which those tests run is to skip
them on general `make check` runs, and tag them so that they are
executed one at a time on
`selftests/pre_release/jobs/timesensitive.py`.
Fixes: https://github.com/avocado-framework/avocado/issues/3689

selftests/functional/test_job_timeout.py: do not assume tests will run

---

avocado/core/tags.py
avocado/plugins/list.py
avocado/plugins/nlist.py
selftests/functional/test_list.py
selftests/functional/test_resolver.py

While "avocado run" has been working, filtering while listing tests has been broken.  This fixes all issues found and adds tests to avoid regressions.

Fix "avocado list" and "avocado nlist" filtering by tags support

---

avocado/core/job.py
avocado/core/output.py
selftests/functional/test_output.py

The logging system inside avocado doesn't expect changes in configuration
between jobs. This PR brings feature for enabling and disabling logging
configurations of the system. It saves the old configurations to the list for
later use.
Reference: #3997
---
Changes from version (#4051)
- Skip condition for `/bin/true`
- inverted logic in `del_last_configuration()`

[Bug fix] `core.show` is not respected [v2]

---

avocado/core/nrunner.py
avocado/core/status_server.py
avocado/plugins/nrun.py

The only reason for the "avocado/core/nrunner.py" to be standalone is
to ease its deployment into an environment that contains nothing but
Python itself.  This will hopefully change in the future when we solve
the deployment problem.
For now, it's clear that at least the StatusServer does not need to
live in that module and be deployed when tests are executed in a
different environment.  The StatusServer is used solely by the
`avocado nrun` command, and thus, can live on another module.

N(ext) Runner: move the status server out of the nrunner module

---

contrib/testsuites/run-kvm-unit-test.sh

git://git.kernel.org/pub/scm/virt/kvm/kvm-unit-tests is not used
anymore, use https://gitlab.com/kvm-unit-tests/kvm-unit-tests instead.

Migrate the kvm-unit-tests repository to the link currently in use

---

avocado/core/job.py
avocado/core/jobdata.py
avocado/core/suite.py
avocado/core/utils.py
avocado/core/varianter.py
avocado/plugins/assets.py
avocado/plugins/diff.py
avocado/plugins/run.py
avocado/plugins/runner.py
avocado/plugins/runner_nrunner.py
examples/jobs/nrunner.py
examples/jobs/passjob.py
examples/jobs/passjob_cit_varianter.py
examples/jobs/passjob_custom.py
examples/jobs/passjob_html.py
examples/jobs/sleepjob_dict_varianter.py
examples/jobs/sleepjob_json_varianter.py
optional_plugins/varianter_yaml_to_mux/tests/test_functional.py
selftests/functional/test_job_api_features.py
selftests/functional/test_output.py
selftests/jobs/nrunner_interface
selftests/jobs/pass
selftests/unit/test_job.py
selftests/unit/test_suite.py

This is the current work of supporting multiple test_suites inside a job. While it is still waiting for one specific test to pass (see the last commit) this is ready for review. Keep in mind this feature will be supported as *experimental* when using multiple test suites. Take a look inside `examples/jobs/passjob.py` file and docstrings to understand the idea behind the separation keeping consistency across the classes.

Adding support to multiple test_suites (job.test_suites) - Experimental

---

avocado/utils/distro.py

Add an OpenEuler Probe for openEuler system.
Signed-off-by: Wang Shengfang <wangshengfang@huawei.com>

avocado.utils.distro: support openEuler
