avocado-framework/avocado

- avocado/core/tree.py
- docs/source/MultiplexConfig.rst
- examples/mux-selftest-advanced.yaml
- examples/mux-selftest-distro.yaml
- selftests/all/unit/avocado/tree_unittest.py
This pull request adds following multiplexer features.
* Support for !include to include other yaml file (either absolute path, or relative to the current yaml file.
* Support for !using to prepend multiple nodes (prepend only, It's impossible to move it outside the current position)
* Support for !remove_node to remove node (It's similar to only filter, but you're able to recreate any complex structure and reuse it. This feature should help building upstream->downstream configs.
* Support for !remove_value to remove value (The same usecase as !remove_node. This one I'm not fully convinced about as you can just change the value instead. I added it to double the node version).
v0: https://github.com/avocado-framework/avocado/pull/316
Changes:
v1: Support python's regexp to specify …
> avocado.multiplexer: Add support for including files and removing node/values [v1]

- selftests/checkall
- selftests/coverageall
Make sure the checkall and coverageall scripts return
failures.
> selftests: Fix return codes

- avocado/core/data_dir.py
- etc/avocado/avocado.conf
- selftests/all/unit/avocado/datadir_unittest.py
Strictly speaking, the test runner is a plugin just like any
other, besides, what is being configured there is in fact datadir
paths, hence the rename.
> avocado.core: Rename 'runner' config section to 'datadir.paths'

- avocado/test.py
When importing of the test fails, it's class is set to MissingTest
and then it's executed. But running requires runner_queue param.
Without it the test fails and Avocado hangs for infinity for early
status.
The hang can be reproduced by importing missing library in `passtest` (eg `import asdf`), which causes the test to be set as `test.MissingTest` instead of normal test and infinity hang. This is only a bugfix which makes this test work. Similar change needs to be done to `RemoteTest`.
Last but not least I don't like the way this works. IMO we need to provide the traceback to help user identify the problem. Currently when there is a problem parsing the file, Avocado crashes with traceback. Only when there is a `ImportError` it's silently ignored and missing test is runned instead.
I …
> avocado.test: Add missing argument to test.MissingTest

- avocado/runner.py
If the test is very quick, it may run in less than 0.1 secs, which is the
minimum time we wait for the result to be available in TestRunner::run_suite().
Since utils.wait_for() accepts a "first" parameter, documented as "Time to sleep
before first attempt", let's use it with a very aggressive low value, just
enough for the main process to be put to sleep by the scheduler and give time
for the other process to run.
Benchmark using multiplextest:
$ TESTS=""; for f in $(seq 1 100); do TESTS="$TESTS examples/tests/multiplextest.py"; done
$ time scripts/avocado run $TESTS > /dev/null
Before this change:
real    0m12.114s
user    0m1.549s
sys     0m1.038s
After:
real    0m2.639s
user    0m1.065s
sys     0m0.764s
Signed-off-by: Ademar de Souza Reis Jr <areis@redhat.com>
> avocado.runner: optimize the run of quick tests

- avocado/linux/distro.py
- avocado/plugins/distro.py
- man/avocado.rst
- selftests/all/unit/avocado/distro_unittest.py
Avocado has some planned features that depend on knowing the Linux Distribution being used on the system and knowing its details. Information such as all currently installed packages, the packages that ship with the distribution, packages that were added on top of the system and others are necessary for those planned features.
This PR brings in this kind of support, as another step towards the implementation of the Component Isolation grand feature.
Changes from v0:
* Return proper exit status when required command line arguments are missing
* Make `save_distro()` do better error checking (and look better) by using the `with` keyword
* Fixed typos on commit message
> Component Isolation: Linux Distribution Support [v1]

- avocado/core/exit_codes.py
- avocado/job.py
- avocado/plugins/distro.py
- avocado/plugins/runner.py
- avocado/plugins/wrapper.py
At the time it seemed a good idea to have an exit_code.AVOCADO_CRASH
integer, but since we also use it for option validation errors, it's
misleading a good deal of the time. Let's use a more generic
AVOCADO_FAIL, update usages and description.
> avocado.core.exit_codes: Change AVOCADO_CRASH to AVOCADO_FAIL

- avocado/plugins/jsonresult.py
- avocado/plugins/remote.py
- avocado/plugins/vm.py
- avocado/test.py
- selftests/all/unit/avocado/remote_unittest.py
- selftests/all/unit/avocado/vm_unittest.py
Fix the compatibility with HTML result plugin when using together with remote or vm plugins:
* Define time_start and time_end attributes on class RemoteTest..
* Move self.result.end_tests() close to tear_down() in order to have sysinfo files unarchived on remote and vm plugins.
> Fix compatibility problem with vm and remote plugins and htmlresult feature.

- docs/source/DebuggingWithGDB.rst
- docs/source/WritingTests.rst
Explain to the user that the class name for their avocado test
is arbitrary (that's actually a recent change, see 6674048).
Also advise them to stick with CamelCase, just for style
purposes.
> docs: Specify that avocado test class names are arbitrary

- avocado/job.py
Avocado tries hard to not surprise the user, and attempts to preserve
the test ID (from the command line test urls) in the test result directory
structure. Because of that, we should not keep using a test ID that is a
relative path, because too much can go wrong.
This patch simply checks if a test ID (from an test url) looks like a
relative path, and if so, changes it to an absolute path. Detailed
explanation on how this is currently broken follows:
At TestLoader.discover_test() (from loader.py), a test name is derived
from a test ID:
```
test_name = params.get('id')
```
The test class itself, along with test parameters (including `id`) are
produced and returned by `TestLoader._make_test()`.
The test class is then instantiated with these parameters, and a "tagged
name" is constructed by …
> Test ID and "tagged name" construction and convention

- avocado/runner.py
- avocado/test.py
- avocado/utils/stacktrace.py
This is a follow up to #348.
This improves the ability to debug avocado in a very delicate spot: Test loading. Since the load happens on a subprocess, and the main avocado process requires a response from the other side to know what to do, our users (and devs) were left in the dark, requiring debug to understand what went wrong. This changes now.
* Changed module name: avocado.utils.tb -> avocado.utils.stacktrace, per @ruda's comments.
* Improved error message on test load bug, per @clebergnu's comments.
> [V2] Improve test load debug

- avocado/test.py
This fixes the leading `/` of paths being stripped from test ids. Pretty straightforward stuff.
> Fix use of relative paths in avocado

- .gitignore
This is a directory used by PyCharm, one of the IDEs some
of the team members are using. Let's add it to .gitignore.
> .gitignore: Add .idea directory

- avocado/runner.py
Having it here was a mistake caused by commit 5347d8ec
causing timeout to be printed to avocado stdout. Let's
fix that.
> avocado.runner: Remove root logger logging upon timeout

- avocado/sysinfo.py
It looks like there was intention to add the extra parameter that
the Command class takes (whether to compress the log file or not),
but it wasn't added as a parameter to the string formatting operation.
> avocado/sysinfo.py: simple formatting fix for the Command class

- selftests/all/doc/doc_build_test.py
- selftests/all/functional/avocado/basic_tests.py
- selftests/all/functional/avocado/export_variables_tests.py
- selftests/all/functional/avocado/gdb_tests.py
- selftests/all/functional/avocado/journal_tests.py
- selftests/all/functional/avocado/loader_tests.py
- selftests/all/functional/avocado/output_check_tests.py
- selftests/all/functional/avocado/output_tests.py
- selftests/all/functional/avocado/standalone_tests.py
- selftests/all/functional/avocado/utils_tests.py
- selftests/all/functional/avocado/wrapper_tests.py
- selftests/all/unit/avocado/archive_unittest.py
- selftests/all/unit/avocado/datadir_unittest.py
- selftests/all/unit/avocado/distro_unittest.py
- selftests/all/unit/avocado/gdb_unittest.py
- selftests/all/unit/avocado/jsonresult_unittest.py
- selftests/all/unit/avocado/loader_unittest.py
- selftests/all/unit/avocado/multiplexer_unittest.py
- selftests/all/unit/avocado/plugins_unittest.py
- selftests/all/unit/avocado/remote_unittest.py
- selftests/all/unit/avocado/settings_unittest.py
- selftests/all/unit/avocado/sysinfo_unittest.py
- selftests/all/unit/avocado/test_unittest.py
- selftests/all/unit/avocado/tree_unittest.py
- selftests/all/unit/avocado/utils_params_unittest.py
- selftests/all/unit/avocado/utils_process_unittest.py
- selftests/all/unit/avocado/vm_unittest.py
- selftests/all/unit/avocado/xunit_unittest.py
This PR introduces two cleanup to unittests:
* removes shebangs since unittests are no longer have executable bits set
* removes left over license headers
> Unittests: remove shebangs and license headers

- avocado/plugins/xunit.py
xunit doesn't support WARN test restul and currently is just ignored.
This commit maps WARN test results as PASS.
> avocado.plugins.xunit: Add WARN status as PASS

- avocado/aexpect.py
- docs/source/Plugins.rst
- examples/plugins/avocado_hello.py
- scripts/avocado-journal-replay
- selftests/all/doc/doc_build_test.py
- selftests/all/functional/avocado/basic_tests.py
- selftests/all/functional/avocado/loader_tests.py
- selftests/all/functional/avocado/utils_tests.py
- selftests/all/unit/avocado/loader_unittest.py
OK, I did it. This has got to be the most stupid commit ever on this repo.
Still, "print 'foo'" annoys me, and if want to have Avocado running on
Python 3 anytime, we would have to do this anyway.
> Remove occurences of old `print` statement syntax

- avocado/utils/remote.py
Each operation (Remote.run) should have timeout to prevent unlimited
hangs. I choose default timeout 60s but it can be adjusted.
> avocado.utils.remote: Add operation timeout

- avocado/job.py
- avocado/plugins/htmlresult.py
- avocado/plugins/runner.py
- avocado/runner.py
- etc/avocado/avocado.conf
- man/avocado.rst
- selftests/all/functional/avocado/basic_tests.py
- selftests/all/functional/avocado/export_variables_tests.py
- selftests/all/functional/avocado/gdb_tests.py
- selftests/all/functional/avocado/journal_tests.py
- selftests/all/functional/avocado/loader_tests.py
- selftests/all/functional/avocado/multiplex_tests.py
- selftests/all/functional/avocado/output_check_tests.py
- selftests/all/functional/avocado/output_tests.py
- selftests/all/functional/avocado/sysinfo_tests.py
- selftests/all/functional/avocado/wrapper_tests.py
Follow up of PR #384.
---
Changes:
* Use command line option `--sysinfo=on|off` to enable or disable sysinfo, remove option `--disable-sysinfo`.
* Use configuration option `enabled` in section `[sysinfo.collect]` to enable or disable sysinfo. Default to enabled.
* The command line option always overwrites the configuration value.
* Rebase code.
> Implement --sysinfo=on|off feature [V3]

- avocado/core/exceptions.py
- avocado/core/output.py
- avocado/core/status.py
- avocado/job.py
- avocado/loader.py
- avocado/plugins/htmlresult.py
- avocado/plugins/jsonresult.py
- avocado/plugins/remote.py
- avocado/plugins/test_lister.py
- avocado/plugins/vm.py
- avocado/plugins/xunit.py
- avocado/result.py
- avocado/runner.py
- docs/source/GetStartedGuide.rst
- docs/source/RemoteMachinePlugin.rst
- docs/source/VirtualMachinePlugin.rst
- docs/source/WritingTests.rst
- man/avocado.rst
- selftests/all/functional/avocado/basic_tests.py
- selftests/all/functional/avocado/loader_tests.py
- selftests/all/unit/avocado/loader_unittest.py
This is a follow up to #380.
This has the full functionality, including the list functionality and fixes to the remote and vm plugins.
Changes from V12:
* Rebased
* Consolidated a branch per @ldoktor's comments.
Changes from V11:
* Behavior tweaks
Changes from V10:
* Small optimization on test loading suggested by @ldoktor
Changes from V9:
* Properly handle broken symlinks (pointed by @adereis)
* Consolidated commits
Changes from V8:
* Error on missing and non tests, introducing input validation to the list of tests (suggested by @adereis)
* Updated documentation (suggested by @adereis)
* Removed (once again) the concept of MissingTest (suggested by @adereis)
Changes from V7:
* Fixed a misleading commit message, per @ldoktor's comments.
* Simplified the selective showing of tests per …
> [V13] Test discovery and load (Phase II)

- avocado/core/tree.py
- avocado/multiplexer.py
- docs/source/MultiplexConfig.rst
- examples/mux-selftest-advanced.yaml
- examples/mux-selftest.yaml
- selftests/all/unit/avocado/multiplexer_unittest.py
- selftests/all/unit/avocado/tree_unittest.py
Formerly known as `avocado.multiplexer: Support for multiplex domains`
Instead of detecting non-sibling nodes generate list of leaves per
each parent and pass it up the tree to the root. Results should be
the same as before, only speed is improved.
Additionally allow specifying nodes (!join), whose children belongs to
the same group. This extends the possibilities beyond what was possible
before.
v0: https://github.com/avocado-framework/avocado/pull/324
v1: https://github.com/avocado-framework/avocado/pull/330
v2: https://github.com/avocado-framework/avocado/pull/356
v3: https://github.com/avocado-framework/avocado/pull/381
Changelog:
v1: !mux-domain yaml tag renamed to !multiplex
v1: Support for node merging
v1: Merging !multiplex tag is |= as people tend to specify it in first, not last …
> avocado.multiplexer: Modify multiplexation mechanism [v4]

- avocado/plugins/remote.py
- avocado/plugins/vm.py
- avocado/utils/remote.py
- avocado/utils/virt.py
- selftests/all/functional/avocado/output_tests.py
- selftests/all/unit/avocado/remote_unittest.py
- selftests/all/unit/avocado/vm_unittest.py
this pull request unifies test locations for remote plugin. It might be one of possible solutions to the #352 . There are couple of changes from before.
1.  set fabric to copy file mode (tests have to be executable)
2.  remote plugin turns each url into aboslute path
3.  parent dirs are copied recursively into $remote_test_dir + $absolute_path
4.  remote execution uses $remote_test_dir + $absolute_path to avoid clashes
5.  remote paths are logged in results
6.  additional support for `--remote-no-copy` execute tests as they are on VM
I tested various executions and it seems to be more consistent. But I might missed something so please think about it for a while.
v0: https://github.com/avocado-framework/avocado/pull/361
v1: https://github.com/avocado-framework/avocado/pull/387
v2: …
> avocado.plugins.remote: Unify test locations and use absolute path [v5]

- Makefile
- docs/Makefile
docs/build is currently present in the git repository, but I see no reason for it. Removing it results in a couple of cleanups.
> Better handling of docs/build

- avocado/plugins/wrapper.py
When no wrappers are activated this plugin still checks for
the compatibility with --gdb. Skip activate when no --wrapper set.
> avocado.plugins.wrapper: Don't activate when not enabled

- avocado/aexpect.py
- avocado/core/data_dir.py
- avocado/job.py
- avocado/plugins/htmlresult.py
- avocado/test.py
- avocado/utils/io.py
- avocado/utils/script.py
The idea of the standalone mode is to be able to have a avocado test to behave like a regular script, outputing to STDOUT the basic log (the same as --show-job-log would) and return an meaningful status code). This should help avocado tests to be run along any other test code or framework.
In this mode, a job will still be created, and the basic output files will also be created, but will be hidden from the user, and removed after the job finishes running.
This is a partial solution to the so called "jobless" mode, which would allow a test to run without a job.
Also, an initially related, now unrelated commit, that unifies the usage of directory creation on our code base.
> Job standalone mode

- avocado/plugins/htmlresult.py
- avocado/sysinfo.py
- etc/avocado/avocado.conf
- selftests/all/functional/avocado/multiplex_tests.py
- selftests/all/unit/avocado/sysinfo_unittest.py
Changes:
* [v4-v5]: Rebased
* New option `profilers` in class Sysinfo. This is a string to contain the command line options for the profilers (like the configuration option `profiler_commands`). Remove `profiler` option, which was just a On/Off option.
* Define .stop() just for the Daemon class, remove from the other classes.
* Apply recommendations from @clebergnu and @adereis  about `.strip()`, documentation and order of commits.
* Rebased code from the upstream.
> Introduce sysinfo profilers (journalctl & vmstat) [v5]

- avocado/core/output.py
- avocado/linux/software_manager.py
- avocado/plugins/distro.py
- avocado/plugins/gdb.py
- avocado/utils/path.py
- avocado/utils/process.py
- docs/source/conf.py
The reasons for the proposed move include:
1) Even though `find_command()` looks for executables, it doesn't really try to execute them as a living process.
2) The implementation looks for it in a `$PATH` like list, so, out of a possibly better choice, `avocado.utils.path` was chosen.
3) Other modules can use that functionality, but not the execution of process.
4) Avoid circular dependencies: this is actually the first motivation of the proposed change, and a true story with the GDB plugin/test. Since `avocado.utils.process` depends on `avocado.gdb`, this module can not use `find_command()` to look for `gdb`/`gdbserver` binaries.
Also, included is a fix to `software_manager.py` that was found in the process.
> avocado.utils.process.find_command(): move from avocado.utils.process to avocado.utils.path

- requirements-travis.txt
It'll be necessary so that we can start ignoring error E402
during pylint checking.
> requirements-travis.txt: Require the latest version of inspektor

- avocado/core/tree.py
- avocado/linux/software_manager.py
- avocado/plugins/remote.py
- avocado/plugins/vm.py
- avocado/utils/astring.py
- avocado/utils/debug.py
- selftests/all/functional/avocado/multiplex_tests.py
The new pep8 adds W503 line break before %s check. This is mass style
update of avocado framework without any actual changes.
> PEP8 fixes: W503

- docs/source/Introduction.rst
Add link to the DevConf mindmap to introduction documentation.
> docs: Add workshop mindmap to Introduction docs

- docs/source/GetStartedGuide.rst
Add a new section inside the "Getting started guide", about installing Avocado from the git repository with confidence that the dependencies will be installed.
> Documentation: Add section about installing from git repository.

- avocado/core/tree.py
- avocado/job.py
- avocado/multiplexer.py
- avocado/plugins/htmlresult.py
- avocado/plugins/multiplexer.py
- avocado/plugins/runner.py
Instead of breaking Avocado if some required Python modules is not installed, like PyYAML and pystache, we will now graceful disable these features.
Note that installing Avocado from a package or following the documentation instructions, will bring all the features and dependencies that Avocado supports and needs.
But if the user chooses to not install the above modules, Avocado will work with less features (i.e. without the HTML report and the Multiplexer).
> Drop features HTML Report and Multiplexer gracefully.

- avocado/plugins/htmlresult.py
- avocado/plugins/jsonresult.py
- avocado/plugins/remote.py
- avocado/plugins/resources/htmlresult/templates/report.mustache
- avocado/test.py
- selftests/all/unit/avocado/remote_unittest.py
Fix a couple of bugs with HTML result:
* Redirect stderr/stdout of browser (option `--open-browser`) to /dev/null
* Fix wrong HTML report links for remote/vm tests
> HTML result fixes

- examples/tests/doublefree.py
This test is using the location of the source file as the build
location, instead of the `srcdir` provided by the Test class.
Also, since `srcdir` is a temporary directory, I believe we should
not have to manually clean it up.
> doublefree test: fix the temporary directories being used

- docs/source/GetStartedGuide.rst
This adds some simple fixes/improvements to (one of) the first documentation a new Avocado user would read.
> Documentation: simple fixes/improvements to the Get Started Guide

- avocado/__init__.py
- avocado/core/output.py
- selftests/all/functional/avocado/basic_tests.py
- selftests/all/functional/avocado/loader_tests.py
Create an additional logging handler for the avocado application,
that outputs to stderr, and two filters, that filter messages
per logging level. This way, normal information (app output)
goes to stdout and error messages go to stderr. The unittests
were updated accordingly.
> avocado.core.output: Errors should go to stderr, not stdout

- examples/testplans/release.json
- scripts/avocado-run-testplan
This PR introduces a very simple tool to help with manual test plans, a collection of tests that can not (yet) be easily automated in avocado but are very important to have done once in a while.
The test plan itself, provided as an example that can turn into our official release test plan, is a WIP as there's room for many more important manual tests.
> Manual Test Plan

- examples/tests/cabort.py
- examples/tests/cabort.py.data/abort.c
- examples/tests/datadir.py
- examples/tests/raise.py
- examples/tests/raise.py.data/raise.c
- examples/tests/raise.py.data/raise.yaml
- examples/wrappers/bind_cpu0.sh
Follow up of PR #438.
---
Changes:
From @clebergnu questions and suggestions, we've got now:
* Include an updated `datadir` test to use the proper temporary dir to build the binary. (like the `doublefree` test is doing now).
* Update `cabort` and `raise` tests to use the proper temporary dir to build the binaries.
* Check for exit code `-6` when running the test `cabort`, so it now looks like a real test.
* Check for exit codes and messages when running the test `raise`, so it now looks like a real test.
* Rebased.
> A few contributions to examples: bind_cpu0, cabort and raise [V2].

- avocado/test.py
- docs/source/WritingTests.rst
- examples/tests/warntest.py
This patch simplifies the concept of WARN test. In case user uses the
self.log.warn or self.log.warning methods, test is marked as dirty and
in case everything else worked fine it finishes with TestWarn exception.
v0: https://github.com/avocado-framework/avocado/pull/385
v1: https://github.com/avocado-framework/avocado/pull/419
v2: https://github.com/avocado-framework/avocado/pull/422
Changes:
v1: Documentation adjustments about "self.log.warn"
v1: Make "avocado-bash-utils" work without avocado
v2: Remove bash-version RFC to speedup the inclusion
v3: English language correction
>  avocado.test: Set the test as WARN when self.log.warn used [v3]

- Makefile
- avocado.spec
- avocado/restclient/__init__.py
- avocado/restclient/cli/__init__.py
- avocado/restclient/cli/actions/__init__.py
- avocado/restclient/cli/actions/base.py
- avocado/restclient/cli/actions/server.py
- avocado/restclient/cli/app.py
- avocado/restclient/cli/args/__init__.py
- avocado/restclient/cli/args/base.py
- avocado/restclient/cli/args/server.py
- avocado/restclient/cli/parser.py
- avocado/restclient/connection.py
- avocado/restclient/response.py
- etc/avocado/avocado.conf
- examples/api/restclient/api.py
- examples/api/restclient/ping.py
- examples/api/restclient/request.py
- man/avocado-rest-client.rst
- requirements-travis.txt
- requirements.txt
- scripts/avocado-rest-client
- selftests/all/unit/avocado/restclient_response_unittest.py
- setup.py
Introduce REST client API modules, allowing scripts that interact with avocado-server easier to write, and also a command line avocado-rest-client application.
This work is derived from experience and code from the Autotest RPC Client (https://github.com/autotest/arc).
Changes from v3:
* Fixed reference in the docstrings to arcli (from arc)
* Release number bump on spec file
* Add missing avocado.restclient.cli.actions module to setup.py
* Be more specific with exceptions during connection initialization
* Rebased to latest master
* Rebased to latest master
>   REST Client: introduce API and avocado-rest-client application [v4]

- examples/tests/doublefree.py
- selftests/all/functional/avocado/output_tests.py
Change the behavior to expect the test to pass, by using test asserts.
> examples.tests.doublefree: Change behavior to expect success/pass.

- avocado/plugins/xunit.py
- avocado/test.py
- examples/tests/failtest_nasty.py
- examples/tests/failtest_nasty2.py
- selftests/all/functional/avocado/standalone_tests.py
The NastyException error is back:
class NastyException(Exception):
def __init__(self, msg):
self.msg = msg
def __str__(self):
return self.msg
crashes Avocado. The problem is we are trying to re-raise the exceptions
and then read the traceback again. Even reading of the details of this
very nasty written exception causes critical failure.
What this patch does instead of handling issues wherever we produce
them, it waits till the exception bubbles to the entry-point and it
tries to read it. If it fails, we log the original traceback
(information about the failure) and then user-friendly message saying
we're unable to retrieve the original failure.
Additionally I had to modify the xunit output as in case of very nasty
inputs it's unable to reproduce the values.
Signed-off-by: Lukáš Doktor …
> avocado.test: Fortify avocado before very nasty exceptions

- avocado/job.py
- setup.py
Fix avocado runner problem when running avocado from the base RPM package:
* Include `avocado.module` inside setup.py.
* Check if htmlresult plugin is installed from the import,
to set the HTML result feature on or off.
```
$ avocado
Could not import module plugin 'avocado.plugins.runner': cannot import name htmlresult
Could not import module plugin 'avocado.plugins.remote': No module named remote
Could not import module plugin 'avocado.plugins.vm': No module named remote
Could not configure plugin 'journal': 'Parser' object has no attribute 'runner'
Could not configure plugin 'json': 'Parser' object has no attribute 'runner'
Could not configure plugin 'xunit': 'Parser' object has no attribute 'runner'
Could not configure plugin 'gdb': 'Parser' object has no attribute 'runner'
Could not …
```
> Fix avocado runner problem when running avocado from the base package.

- docs/source/DebuggingWithGDB.rst
The current way the text was built looks bad while
looking at the docs in the browser.
> DebuggingWithGDB.rst: Fix typo and text flow

- avocado/core/data_dir.py
- avocado/job.py
- avocado/test.py
Follow up of PR #453 .
---
Changes:
* The Job class has now only one argument `args` (so the previous argument `standalone` goes inside `args`).
* The Job class will always contain a valid `args` (don't need to check for `None`).
* Rename API `avocado.core.data_dir.get_job_logs_dir` to `avocado.core.data_dir.create_job_logs_dir`.
* Rephrase standalone test result to 'Test results available in %s'.
* Rebased code.
>   self.job: Command line options in "jobless mode" [V2]

- Makefile
That will link avocado-virt modules and plugins if they happen to
live in the same directory as avocado (toplevel directory) does.
> Makefile: implement `link` target

- avocado/job.py
- avocado/remote/runner.py
- selftests/all/unit/avocado/remote_unittest.py
This is a collection of fixes and extra checks that make using remote test support more consistent and thus with better usability.
Summary:
* When using --remote-no-copy the test files will neither be copied from the current system nor executed on it, so disable all sorts of checks. Fix for issue #417.
* Improve the checks regarding avocado installation on the remote system
* Add checks for tests before trying to run them
* return the original `avocado list` error message, which is more detailed and includes the missing files, instead of a general error message.
* Also return the version number if avocado is found to be installed on the remote system
* Use a simpler Python idiom (getattr with default instead of hasattr and extra check)
> Remote test support: extra checks for improved usability [v3]

- avocado/test.py
Fixes the https://github.com/avocado-framework/avocado/issues/415
Current behavior of process.run(shell=False) is it expects multiple
arguments and split the provided cmd. This doesn't fit the SimpleTest
as it founds a binary and then tries to execute it without any
arguments as it might be separated by spaces. This patch escapes the
executed command using "pipes.quote" to avoid it's splitting.
>  avocado.test: Escape filename when executing SimpleTest

- avocado/plugins/runner.py
Adding multiple multiplex files via -m is order dependent. This might
not be obvious and this patch adds the note about this.
v1: https://github.com/avocado-framework/avocado/pull/466
Changelog:
v2: dependant -> dependent (msg and code)
> avocado.plugins.runner: improve -m description [v2]

- avocado/__init__.py
- avocado/job.py
- avocado/sysinfo.py
Follow up for #469, except for the `END testname` log marker, which is controversial, but could be added later without any side effects.
> Jobless mode 

- avocado/utils/archive.py
The line above says enough, but let me stress the point that we want
Avocado to be portable enough to run on various and possibly limited
systems.
Embedded systems and lightweight VMs/containers are a very compeling
target for avocado, so IMHO we should strive to make the avocado core
runnable with as little as a standard Python installation.
* Renamed LZMA_SUPPORTED to LZMA_CAPABLE
* There's no need to make _WrapLZMA class definition conditional
> pyliblzma: make it optional since it is not essential [v2]

- avocado/loader.py
- selftests/all/unit/avocado/loader_unittest.py
This allows people to derive indirectly from test.Test and still
import the direct base class like this:
from base import MyBaseTest
class MyInheritedTest(MyBaseTest):
...
Without this change, the loader might pick `MyBaseTest` as the
class to test instead of `MyInheritedTest`.
Signed-off-by: Marius Vollmer <mvollmer@redhat.com>
> loader: Ignore imported classes.

- examples/testplans/release.json
This adds more tests to the release test plan, adds more precise descriptions
of the test and expected results.
Also, the test plan follows a sequence of steps that is more concise and eases
the manual testing process.
* Added Remote Machine HTML links test
* Added HTML sysinfo test
* Added HTML external links test
> Release test plan: more tests, more precise descriptions and optimal test flow [v3]

- avocado/multiplexer.py
It turns out that ignore not being there still makes
the pylint check to pass on both python 2.6 and 2.7.
> avocado.multiplexer: Remove unnecessary pylint ignore

- .travis.yml
- avocado.spec
- avocado/__init__.py
- avocado/cli/parser.py
- avocado/plugins/htmlresult.py
- avocado/remote/runner.py
- avocado/test.py
- requirements-travis-python26.txt
- requirements-travis.txt
- selftests/all/functional/avocado/argument_parsing_tests.py
- selftests/all/functional/avocado/basic_tests.py
- selftests/all/functional/avocado/loader_tests.py
- selftests/all/functional/avocado/multiplex_tests.py
- selftests/all/functional/avocado/output_check_tests.py
- selftests/all/functional/avocado/output_tests.py
- selftests/all/functional/avocado/standalone_tests.py
- selftests/all/functional/avocado/sysinfo_tests.py
- selftests/all/functional/avocado/utils_tests.py
- selftests/all/unit/avocado/multiplexer_unittest.py
- selftests/all/unit/avocado/remote_unittest.py
- selftests/all/unit/avocado/settings_unittest.py
- selftests/all/unit/avocado/sysinfo_unittest.py
- selftests/all/unit/avocado/test_unittest.py
- selftests/all/unit/avocado/tree_unittest.py
- selftests/all/unit/avocado/utils_process_unittest.py
- selftests/run
Make avocado to run under RHEL6 (python 2.6) and also add 2.6 testing targets.
* Implemented changes per @ldoktor's comments on the previous review.
> [V3] Python 2.6 (RHEL6) compatibility

- avocado/plugins/plugin_list.py
- avocado/plugins/test_list.py
- avocado/remote/runner.py
- selftests/all/unit/avocado/remote_unittest.py
Fix #486, by adding an option to list related plugins in avocado to ignore paginators.
> Fix issue #486 

- avocado/core/output.py
- avocado/job.py
- selftests/all/functional/avocado/multiplex_tests.py
- selftests/all/functional/avocado/output_tests.py
- selftests/all/functional/avocado/standalone_tests.py
Implements card
https://trello.com/c/H1Yz0AQl/349-print-job-id-results-dir-in-the-debug-log
> Print Job ID in job log

- Makefile
The `man` target is not currently using make's dependency system, let's
fix that.
> Makefile: have a better target/recipe with deps for man pages

- avocado/job.py
We were printing the results dir only when standalone test
mode was used. Let's extend that to --show-job-log as well
by moving the message to the end of the job execution
method.
> avocado.job: Print test results dir even on --show-job-log

- avocado.spec
- avocado/plugins/exec_path.py
- avocado/test.py
- docs/source/WritingTests.rst
- examples/tests/simplewarning.sh
- libexec/avocado-bash-utils
- libexec/avocado_debug
- libexec/avocado_error
- libexec/avocado_info
- libexec/avocado_warn
- scripts/avocado
- selftests/all/functional/avocado/basic_tests.py
- setup.py
This patch is initial support for people using custom bash scripts
with avocado. They can use "source avocado-bash-utils" to get the
functions into their bash script and utilize them.
This version contain functions to write to Test.log the same way it's
possible from python including failing the test with TestWarn in case
avocado_warn was used.
v0: https://github.com/avocado-framework/avocado/pull/419
v1: https://github.com/avocado-framework/avocado/pull/428
v2: https://github.com/avocado-framework/avocado/pull/447
v3: https://github.com/avocado-framework/avocado/pull/460
v4: https://github.com/avocado-framework/avocado/pull/496
v5: https://github.com/avocado-framework/avocado/pull/498
v6: https://github.com/avocado-framework/avocado/pull/501
v7: …
> scripts.avocado-bash-utils: Add Avocado bash utils [v8]

- avocado/core/tree.py
- avocado/job.py
- avocado/multiplexer.py
- avocado/runner.py
- avocado/test.py
Hello guys,
apart from one bugfix this patch makes no real changes (therefor no unittests needs to be adjusted), it only refactors how we generate multiplexed variants. It prepares the code for the "real" multiplexer with namespaces support. I'd like to do these little steps rather then preparing a big patch set with all the changes.
Regards,
Lukáš
v1: https://github.com/avocado-framework/avocado/pull/502
v2: https://github.com/avocado-framework/avocado/pull/506
Changelog:
v2: Calculate number of all tests correctly (864/1 => 864/864)
v3: Correct docstrings (remove references to multiplex_files where they were removed)
> avocado.job: Refactor how multiplexation happens [v3]

- avocado/aexpect.py
We can't require avocado imports in the server part of
the aexpect process because that will be executed
stand alone, and will not have access to the rest
of the avocado libraries. The bugs were introduced
in commits:
6f380e0d77d839dac1b30987e84fa300b4a99058
3fa9077f133b2445f839056cd568d21d14f7975d
This patch fixes the problem by moving the imports
to the client side of the module.
> avocado.aexpect: Fix bugs that broke avocado-virt

- avocado/__main__.py
- avocado/cli/parser.py
- docs/source/conf.py
This PR adds the `avocado-virt` API documentation alongside avocado's code API.
This was tested on a separate repo and can be seen at work over at:
https://avocado-doc-tmp.readthedocs.org/en/latest/api/avocado.virt.html
> Include virt API on readthedocs.org

- avocado/plugins/remote.py
- avocado/plugins/vm.py
- avocado/remote/result.py
- avocado/remote/runner.py
- selftests/all/unit/avocado/remote_unittest.py
Sometimes avocado on guest hangs. This patch adds host timeout to
interrupt the execution.
It's not perfect as we don't get the intermediary results. You can manually connect to the machine and try downloading the results yourself based on job ID. We should probably automate this in the future, but this patch should at least prevent CI from hanging.
#513
v1: https://github.com/avocado-framework/avocado/pull/519
changes:
v2: Typos fixed
> avocado.remote: Add support for host-timeout [v2]

- MANIFEST.in
- Makefile
- avocado.spec
Because of missing requirements, the unittests will only be run for now on Fedora.
This also introduces other build (RPM and Makefile) related changes and improvements.
> Run unittests during the build of RPM packages [v2]

- avocado/cli/app.py
When running `run --help` piped through a non existing command,
exit gracefully with a shell error and don't print the whole trace
back message.
Reference: https://trello.com/c/Nm4elZrb/363-bug-avocado-should-fail-gracefully-when-redirected-to-a-broken-pipe
Signed-off-by: Rudá Moura <rmoura@redhat.com>
> avocado.cli.app: Fix bug regarding `run --help` and broken pipe.

- avocado/runner.py
A patch from @ldoktor that I'd like to push earlier than his PR on parameters, since I believe it's a nice defensive and stand alone patch.
> avocado.runner: Fortify early_state.get(timeout)

- avocado/core/output.py
- avocado/job.py
- avocado/result.py
- avocado/runner.py
- docs/source/GetStartedGuide.rst
- docs/source/OutputPlugins.rst
- docs/source/WritingTests.rst
- man/avocado.rst
The main goal of this PR is to give correct results when tests a job is interrupted. Previously, we'd have situations where the tests that were not run would not make into the SKIP count.
Additionally, since this state was already present on some status definitions and exceptions, this clearly announces the test(s) that was INTERRUPTed and did not finish properly.
* Add a better commit message on `avocado/runner.py: remove unnecessary ctrl_c variable`.
> Test interruption and misleading UI on skipped tests [v2]

- Makefile
The ReST files at doc/build/api are automatically generated by code
on `conf.py` and should also be removed on the `clean` target.
> Makefile: clean auto generated API documentation files

- examples/tests/multiple_tests.py
- selftests/all/functional/avocado/basic_tests.py
- selftests/all/functional/avocado/export_variables_tests.py
- selftests/all/functional/avocado/gdb_tests.py
- selftests/all/functional/avocado/journal_tests.py
- selftests/all/functional/avocado/loader_tests.py
- selftests/all/functional/avocado/multiplex_tests.py
- selftests/all/functional/avocado/output_check_tests.py
- selftests/all/functional/avocado/output_tests.py
- selftests/all/functional/avocado/standalone_tests.py
- selftests/all/functional/avocado/sysinfo_tests.py
- selftests/all/functional/avocado/utils_tests.py
- selftests/all/functional/avocado/wrapper_tests.py
- selftests/all/unit/avocado/datadir_unittest.py
- selftests/all/unit/avocado/jsonresult_unittest.py
- selftests/all/unit/avocado/multiples_tests.py
- selftests/all/unit/avocado/sysinfo_unittest.py
- selftests/all/unit/avocado/test_unittest.py
- selftests/all/unit/avocado/xunit_unittest.py
Getting to eliminate all places where we were not properly cleaning up temporary test results in both /tmp and ~/avocado/job-results was harder than I thought. But I finally got there.
* Addressed comments from @ldoktor and @clebergnu.
> Functional test fixes

- avocado.spec
- avocado/sysinfo.py
- avocado/utils/genio.py
- etc/avocado/avocado.conf
- etc/avocado/sysinfo/commands
- etc/avocado/sysinfo/files
- etc/avocado/sysinfo/profilers
- selftests/all/functional/avocado/sysinfo_tests.py
- selftests/all/unit/avocado/sysinfo_unittest.py
- setup.py
This PR turns the hard coded configuration of files/commands into something more flexible by being configurable with external files.
* Return the default `profiler` parameter value to `None`, so that it looks at the configuration value by default
* Fix typo in docstring
> Sysinfo: make it configurable [v2]

- avocado/test.py
A test may or may not have a data dir. Also, a test might
be on a read only location, so forcing the creation of
one will raise an OSError. This fixes a problem introduced
with 133b60e8dbae94eef5d9a69411bec6a565e90d45.
> avocado.test: Don't force creation of the test datadir

- avocado/loader.py
- avocado/test.py
- selftests/all/unit/avocado/test_unittest.py
Follow up of #544 
---
Changes:
* Get rid of `test_parameters_simple` and `test_parameters_name`.
> avocado.test.SimpleTest: Use parameter name instead of path [V2]

- avocado/core/tree.py
- avocado/multiplexer.py
- avocado/plugins/multiplexer.py
- avocado/plugins/runner.py
- avocado/test.py
- examples/mux-selftest-params.yaml
- selftests/all/functional/avocado/multiplex_tests.py
- selftests/all/unit/avocado/multiplexer_unittest.py
1) It adds support to set resolution order by `--mux-entry` on the  command-line. We discussed with Ademar about the way we handle arguments so this patch does it the way I favor. Please review it and let me know whether I should make the same for the other args (like --multiplex, --filter-only, ...) or whether I should modify this commit to use the current approach.
2) Adds support to inject the yaml file into a specific location by `-m [$location:]$file`. What it does is it generates the tree from the yaml file and prepends the $location when specified.
3) Is just bugfix/improvement
4) existing feature enablement on cmdline
5) adds the proper params clash detection
6) style fixups
7) bugfixes
8) unittest
v1: https://github.com/avocado-framework/avocado/pull/530
v2: …
>  avocado.multiplexer: Support for overriding entry points and yaml locations [v3]

- avocado/multiplexer.py
The '/' prefix is leftover from -m $using:$path development and was
already solved in -m patch. Remove this code which actually breaks the
params resolving.
> avocado.multiplexer: Fix mux-entry path

- avocado/plugins/htmlresult.py
- avocado/plugins/multiplexer.py
- avocado/plugins/wrapper.py
- avocado/plugins/xunit.py
Trivial patch that normalizes description of the
plugins present on the base avocado repository.
> avocado.plugins: Make plugins description uniform

- docs/source/DebuggingWithGDB.rst
It was attempted to fill in the gaps so that avocado-virt would be
able to transparently use avocado GDB support. It turns out that a
number of foundation changes will have to be made to support launching
process in the background while running inside GDB.
So, for now, let's document that limitation.
> docs: add section on GDB support and avocado-virt usage

- docs/source/conf.py
Commit 120345a attempted to download and build avocado-virt API
documentation together with the avocado API. While this was reliable
offline, it succeeded only on the very first version builds at
readthedocs.org.
So, let's revert back that hackish form of combining the docs. Further
commits will add API documentation generation to avocado-virt itself,
and link avocado and avocado-virt by means of the intersphinx mapping
feature and readthedocs.org sub-project support.
> docs: revert attempt to fetch and build avocado-virt API documentation

- avocado/plugins/remote.py
- avocado/plugins/vm.py
- avocado/remote/result.py
- avocado/remote/runner.py
- selftests/all/unit/avocado/remote_unittest.py
The "timeout" argument was added to "run_testsuite" but not added to
avocado.remote, which now raises exception. This patch merges the
--remote-timeout and --job-timeout keeping only the --job-timeout.
> avocado.remote: Accept "timeout" arg

- Makefile
It was noted that, on some Python version, the generated tarballs
actually have a lot of files missing. IMHO, if we track a file on git,
then it should make into the tarball. Also IMHO, the distutils sdist
code is a nice thing to have if you can't export your code right from
your SCM.
This is kept simple on purpose so that if we hit any unintended side
effect we can revert to the previous way of generation source
tarballs.
> Makefile: replace source tarball generation from distutils to git

- avocado/core/job.py
- avocado/core/plugins/multiplexer.py
- avocado/core/tree.py
This is rebase from the current master of @ldoktor 's “Handle incorrect yaml files without exception [v2]’ #578. The v2 looks good to me, so @clebergnu can you check this and do the merge?
> avocado: Handle incorrect yaml files without exception [v3]

- avocado/core/job.py
- avocado/core/plugins/builtin.py
- avocado/core/plugins/htmlresult.py
- avocado/core/plugins/manager.py
- avocado/core/plugins/plugin_list.py
Show a better output to the user in case our plugins are disabled or unloadable.
* Instead of guessing the plugin disable cause, use a more generic but accurate description.  The description chosen is to simply say that the plugin was disabled during configuration (`configure()`), which is often done, but not limited to, missing dependencies.
* Changed the presentation from having colored `Enabled` or `Disabled` at the RHS of the plugin description to a single colored header.
* Increased one space in the formatting string (`format_str`)
* Dropped the use of FailedPlugin in favor of a simpler (name, reason) tuple.
* Catch a single, and more broad `Exception` since `ImportError`s will also be caught and treated the same way.
> Plugins improve list view [v2]

- avocado.spec
- setup.py
The GDB config file was not being installed and packaged in the RPM
package. This should fix it.
> setup.py: Add missing gdb.conf file in the avocado RPM

- avocado/core/plugins/multiplexer.py
- avocado/core/tree.py
This pull request improves the multiplexer usability by normalizing filter entries and compressing the variants list. It was inspired by @adereis's input.
v1: https://github.com/avocado-framework/avocado/pull/617
Changes:
v2: Use "rstrip()" instead of removing a single '/'
v2: New commit with simple avocado.core.tree cleanup
> Couple of multiplexer related improvements [v2]

- avocado/core/parser.py
- avocado/core/plugins/plugin.py
Use the less generic term 'dispatch', for the proper internal
attribute, to dispatch the code to execute, after parsing
command line and so on.
Signed-off-by: Rudá Moura <rmoura@redhat.com>
> avocado.core: Internal attribute to take_action() is now 'dispatch'.

- avocado/core/tree.py
- avocado/multiplexer.py
- docs/source/MultiplexConfig.rst
- docs/source/WritingTests.rst
- selftests/all/functional/avocado/multiplex_tests.py
- selftests/all/unit/avocado/multiplexer_unittest.py
- selftests/all/unit/avocado/tree_unittest.py
This patch changes the default mux-entry to `/run` as it tends to be
more convenient.
The biggest change is that this location is used as default location
for added YAML files. It's also used as the base when using relative
path YAML file injection. The only way to include file into the exact
location is to use absolute path (`/your/location`).
The benefit is that single simple YAML file doesn't require any additional
location and is in the default mux-entry location. Check the documentation
for details.
v1: https://github.com/avocado-framework/avocado/pull/622
Changes:
v2: Documentation tweaks by Ademar and Lucas
> avocado.multiplexer: Inject YAML files into /run [v2]

- avocado/core/parser.py
- avocado/core/plugins/multiplexer.py
- avocado/core/plugins/runner.py
- avocado/core/tree.py
- avocado/multiplexer.py
- selftests/all/unit/avocado/multiplexer_unittest.py
- selftests/all/unit/avocado/tree_unittest.py
This patch adds "--env" argument, which allows one to specify
[path:]key:value records which are injected into the multiplex tree
parsed from yaml files.
It also demonstrate the way plugins can override multiplex tree
therefor modify test params during activate/run phase.
There are few intrusive changes. It reuses the existing namespace
during "avocado.core.parser.Parser.finish" part to keep the values set
during "Plugin.activate" phase and it adds
"self.args.default_multiplex_tree" argument which is reserved for
multiplex tree to be merged into tree made from yaml files.
The `avocado-virt` can use the same structue to override
`qemu_bin` and other values from cmdline.
v0: https://github.com/avocado-framework/avocado/pull/614
v1: https://github.com/avocado-framework/avocado/pull/627
v2: …
> avocado.multiplexer: Support for modifying multiplex tree on cmdline [v3]

- avocado/multiplexer.py
- selftests/all/unit/avocado/multiplexer_unittest.py
One of the requirements is to evaluate paths from right to left. This
works fine with relative paths, but was intentionally disabled for
absolute paths. Anyway this behavior is wrong and both, absolute and
relative, paths should be evaluated from right to left and allow
remaining path on left.
> avocado.multiplexer: Evaluate abspath from right

- Makefile
- avocado/core/exceptions.py
- avocado/core/job.py
- avocado/core/loader.py
- avocado/core/output.py
- avocado/core/plugins/test_list.py
- avocado/multiplexer.py
This is a follow up to PR #632
The PR has been renamed because it no longer contains the actual virt test compatibility plugins. However, you definitely want to test this together with the avocado-vt initial pull request (see below).
You can try out this work by following the steps:
1) Check out this branch
2) Set the environment variable 'VIRT_TEST_PATH' to a path containing a copy of virt test
3) The copy of virt-test has to be in my new branch avocado-integration-v4 [1]
4) Check out the avocado-vt repo, then merge PR 1 -> avocado-framework/avocado-vt#3. The code checked out has to be in the same base dir as your copy of avocado
5) Type `make link` in the avocado dir, so that the plugins can be properly linked.
6) Bootstrap your testing in the virt test dir by running `./run -t qemu …
> [V12] Load/List tests from multiple sources

- avocado/core/plugins/config.py
- selftests/all/functional/avocado/basic_tests.py
Add the --paginator (on|off) option to 'avocado config'.
This option has been missing from that command, which
is inconsistent with the other listing options we have.
> avocado config: Add --paginator to command

- Makefile
Sometimes the local checks, including documentation builds and other
unit and functional tests will fail because of either stale state
or because of external plugins.
Let's require a clean source tree before running local checks to
avoid those false positives.
> Makefile: require a clean source tree before running local checks

- avocado/core/plugins/gdb.py
- docs/source/Configuration.rst
- docs/source/ContributionGuide.rst
- docs/source/DebuggingWithGDB.rst
- docs/source/GetStartedGuide.rst
- docs/source/Introduction.rst
- docs/source/OutputPlugins.rst
- docs/source/Plugins.rst
- docs/source/ReferenceGuide.rst
- docs/source/RemoteMachinePlugin.rst
- docs/source/ResultsSpecification.rst
- docs/source/VirtualMachinePlugin.rst
- docs/source/WrapProcess.rst
- docs/source/WritingTests.rst
- docs/source/conf.py
- docs/source/index.rst
This is a general review of our documentation, both on a macro and micro level.
I've gone through the first sections thinking of myself as a novice user, and this has changed the organization of the Getting Started Guide.
There are still some tasks in progress or pending, including:
* The API docs reorganization, which is dependent on #636  and it's kept for a later PR
* The man-pages should comprehensively (automatically) include all command line options
* Reorganization of other sections
* Wording changes suggested by Lucas.
* Mention the function naming conventions for the test methods and
link to PEP 8 relevant section for functions and classes.
* Break into finer grained sections.
* Updated Ubuntu repository version
---
This is a follow up of #639.
> Documentation Review (v2)

- docs/source/Introduction.rst
- docs/source/ReferenceGuide.rst
Another round of fixes and improvements to the Avocado documentation.
The big highlight is the documentation of the library namespaces and their respective API stability guarantees.
---
* Fix typo spotted by Lucas (s/will/you).
> Documentation Review (2nd round) - (v2)

- avocado/core/plugins/builtin.py
- avocado/core/settings.py
- etc/avocado/avocado.conf
- selftests/all/unit/avocado/settings_unittest.py
Follow up to PR #647.
Implement Trello card:
https://trello.com/c/8Yth6z9a/399-allow-broken-plugins-to-be-silenced-by-configuration
Although my solution is a bit more flexible than what's described in the card. It's not strictly what the card wants, but conversations on IRC/discussions  show that it's a reasonable solution nevertheless.
Changes from V2:
* Rebase against the latest master
> [V3] Silence broken plugins

- avocado/core/job.py
- avocado/core/loader.py
For a while we have been using code similar to this:
def load_plugins(self, args):
for key in args.__dict__.keys():
if key.endswith('_loader'):
One could argue that the sufix check is not quite elegant
or correct, so we can remove that and get straight to the
business of checking the actual loading class we're interested
in. This PR changes all the occurrences of that practice inside
the avocado code.
* Use iteritems() instead of .keys(), as suggested by ldoktor.
> [V2] avocado: Avoid loading plugin classes in the code based on hardcoded arg names

- avocado/core/job.py
- avocado/core/loader.py
This fixes a bug introduced by cb751ea5e238cbfab735144173d56a1cc48e5ab5.
It turns out that .itervalues() is a bad idea, given that the
args dictionary is modified by plugins, leading to a bug when
we have multiple test source plugins enabled at once.
I'm sorry I didn't notice this before the commit was merged.
> avocado: Fix use of itervalues() in args dict

- avocado/core/parser.py
- avocado/core/settings.py
- man/avocado.rst
Changes from PR #657 
From @ldoktor suggestions...
* Fix typos
* Merge commits for the option --config and the man-page.
* Change order of commits, first to expose the method and then the commit to introduce the new option.
> Add option to read a custom configuration from a file [v2]

- setup.py
The new location was not reflected on the setup.py script, resulting
in the module not being present after installation.
> setup.py: add missing module avocado.utils.external

- avocado/core/test.py
- examples/tests/doublefail.py
- examples/tests/errortest.py
- examples/tests/failtest.py
- examples/tests/skiponsetup.py
- examples/tests/skiptest.py
- examples/tests/warntest.py
- selftests/all/functional/avocado/basic_tests.py
This introduces utility methods, preserves the example tests at their current location and add tests for skipping during `setUp()`.
> API Review: add test methods for SKIP/FAIL/ERROR themselves

- avocado/core/loader.py
- avocado/utils/stacktrace.py
The `discover_url` function should not fail, instead it should return
empty results. In case of failure, it's impossible to find out what
went wrong as we don't log any details, thus it might happen that
`avocado list` shows tests, which are not found during `avocado run`.
This patch temporarily logs reason into the `avocado.app.exceptions`
and traceback into the `avocado.app.traceback` logger. Booth are
enabled by default, but the plan is to make these optional and
show only the `exceptions` by default.
>  core.loader: Log discover_url exceptions [v1]

- avocado/core/exceptions.py
- avocado/core/test.py
- examples/tests/skiponsetup.py
- selftests/all/functional/avocado/unittest_compat.py
- selftests/all/unit/avocado/jsonresult_unittest.py
- selftests/all/unit/avocado/test_unittest.py
- selftests/all/unit/avocado/xunit_unittest.py
Introduced with commit d6abdcd4a6ea382c0447ece49f983b37823de245,
avocado tests no longer report correctly to the unittest runner.
The reason is that there is a structure that must be correctly
updated by the run() method (the result instance), that was not
being updated in the new implementation.
Therefore, one possible fix, presented here, is to once again
*not* implement run() at all. this way we avoid messing around
with internal data structures, and when avocado is executed
under nosetests, or the default unittest runner, we get the
expected behavior of the method. The downside is that we have
less perceived integration among both classes.
* TestFail now has double inheritance (TestBaseException, AssertionError), per @adereis's suggestion.
> [V2] avocado.core.test: Fix problem with unittest compatibility

- avocado/core/multiplexer.py
- avocado/core/plugins/runner.py
- avocado/core/test.py
- docs/source/MultiplexConfig.rst
- docs/source/WritingTests.rst
--mux-entry was a bit confusing as what it does it splits the result
params into multiple slices and while quering for keys they are
evaluated in the specified order, thus behaving the same as Linux PATH
bash variable.
> multiplexer: Change the --mux-entry to --mux-path

- docs/source/MultiplexConfig.rst
- man/avocado.rst
Fix a couple of problems in the multiplexer related documentation.
* Removed references to `scripts/` in the avocado path, pointed out by @adereis.
> [V2] Fix man page multiplexer

- avocado/core/job.py
- avocado/core/multiplexer.py
- selftests/all/functional/avocado/multiplex_tests.py
This is a follow up of #673.
This implements: https://trello.com/c/jP6FD8bF/386-job-results-log-record-the-command-line-options-config-and-multiplexing-tree-human-readable.
Add the following information to the job log:
* command line
* version information
* config information
* plugins status
* multiplex tree representation
To help with debug and bug fixing.
You can see a job log example here -> https://gist.github.com/lmr/5055dbe5b1dd2eebe7b5
* Only display git info if git commands succeed, suggested by @clebergnu 
* Change `tree` attribute to `Mux` to `root`, suggested by @clebergnu 
* Use `astring.tabular_output` in code that formats tables of text, as suggested by @clebergnu
* Fixed unittests
* Added multiplex tree representaion
> [V3] job results: log/record the command line options, config and multiplexing tree (human readable)

- avocado/core/test.py
The extra line was confusing, therefore, we shall remove
it from the logs.
Log excerpt:
Job ID: eb8975442b95f700697e20f6f2da8012f7e49454
START examples/tests/sleeptest.py
PARAMS (key=timeout, path=*, default=None) => None
PARAMS (key=sleep_length, path=*, default=1) => 1
Sleeping for 1.00 seconds
PASS examples/tests/sleeptest.py
> avocado.core.test: Remove extra logged line after test starts

- docs/source/WrapProcess.rst
- man/avocado.rst
Changes from PR #679 
* Fix typo (specify/specifies)
* Don't escape * , since we're bash-centric.
* Adjustments in commit messages.
> BUG/documentation: setting wrappers for specific binaries do not work [V2]

- avocado/core/loader.py
- avocado/core/plugins/test_list.py
Loader plugins can specify default set of tests, when none supplied.
Currently list of these defaults is generated and then examined by
all loader plugins. This might generate clashes and false-negative
results, for example avocado-vt defines "vt_list_all" which obviously
shouldn't be parsed by file-plugin.
This patch changes the behavior so when no urls specified each plugin
chose and processes only his own defaults. To do this it was necessary
to reorder the recognition thus now you get all successful hits of all
urls from the first plugin, then the second....
Additionally small optimization was added to skip urls which are already
successfully assigned. This doesn't affects the results as they were
only added when not already handled.
Last minor tweak avoids false-positive result when …
> avocado.core.loader: Discover only per-plugin-default tests [v2]

- avocado/core/plugins/resources/htmlresult/templates/report.mustache
The uid is only a test name and is not unique across the execution. We
should use tagged_name which consists of the uid and the optional tag to
be consistent with avocado runner.
Changes:
v1: Add reason for this change
> plugins.htmlresult: Use tagged_name instead of uid

- avocado/core/test.py
- docs/source/ReferenceGuide.rst
- etc/avocado/avocado.conf
- examples/tests/uncaught_exception.py
- selftests/all/functional/avocado/basic_tests.py
On unhandeled unknown exceptions the test should finish with ERROR
rather than FAIL as the test developer didn't think it might happen.
This behavior is configurable in config when the user have a different
opinion.
v1: https://github.com/avocado-framework/avocado/pull/689
Changes:
v2: Use test instead fo runTest method
v2: Add documentation about possible test statuses
> core.test: Map generic exceptions to TestError [v2]

- avocado.spec
The recent API reorganization made a module requiring
importlib to be loaded at setup stage. Hence the backport
python-importlib, available in EPEL, has to be added to
the BuildRequires field of the spec.
> avocado.spec: Update BuildRequires to include python-importlib

- Makefile
Add a couple new targets, `link_vt` and `link_virt`, for convenience purposes. The target `link` continues to work as expected.
> Makefile: New `link_vt` and `link_virt` targets

- avocado/core/log.py
- avocado/core/output.py
- avocado/core/remote/result.py
- avocado/core/remote/runner.py
- avocado/core/remoter.py
- avocado/core/runner.py
- avocado/core/test.py
- avocado/core/virt.py
- selftests/all/unit/avocado/remote_unittest.py
We have been using `fabric` for quite some time, but missing on important debugging opportunities. This PR lets us to log the entirety of the SSH logging streams produced by fabric and its underlying library, paramiko. This way we can help users (and ourselves) to figure out bugs related to SSH, as long as the code uses fabric.
An example of a typical `remote.log` can be seen here:
https://gist.github.com/lmr/1b5e74927be91d80ae90
* Changed log names from `ssh.log` -> `remote.log`, per @adereis' suggestion.
* Added 'env' to the list of executed commands every time the remote/vm plugins are executed, to improve debugging info and pinpoint reasons why the avocado executable was not found, per @adereis' suggestion.
> [V2] Fix fabric logging

- avocado/core/plugins/gdb.py
- avocado/core/plugins/htmlresult.py
- avocado/core/plugins/jsonresult.py
- avocado/core/plugins/remote.py
- avocado/core/plugins/runner.py
- avocado/core/plugins/vm.py
- avocado/core/plugins/wrapper.py
- avocado/core/plugins/xunit.py
- docs/source/DebuggingWithGDB.rst
- docs/source/WrapProcess.rst
- man/avocado.rst
Just a collection of usability fixes aimed at improving the consistency of command line options, help messages and documentation.
> Usability fixes on "$ avocado run --help"

- avocado/core/plugins/multiplexer.py
- avocado/core/plugins/runner.py
--env injects node/key/values into the multiplexed tree. It's 100%
related to mux therefor --mux-inject would better reflect the
functionality.
The --mux-path description was rather misleading, hopefully this will
help users to get better notion (although reading the documentation is
still preferred).
v1: https://github.com/avocado-framework/avocado/pull/706
Changes:
v2: Improved "--mux-path" description by lmr
> avocado.core.plugins: Rename --env and improve --mux-path desc [v2]

- avocado/core/remote/result.py
- avocado/core/remote/runner.py
- selftests/all/unit/avocado/remote_unittest.py
This is a proposed fix for the conditions described in:
https://trello.com/c/dowZqjjo/429-running-tests-remotely-copies-tests-unnecessarily
> Execution of tests remotely copies tests unnecessarily

- avocado.spec
- docs/source/GetStartedGuide.rst
- examples/simpletests/failtest.sh
- examples/simpletests/passtest.sh
- setup.py
This fixes #628.
Add a couple of simple shell scripts that can be listed
and executed with avocado. Let's update our documentation
to use this new dir and avoid people confused with our
wrappers.
> examples: Add a folder with simple tests

- avocado/__init__.py
- avocado/core/exceptions.py
- examples/tests/fail_on_exception.py
- selftests/all/functional/avocado/basic_tests.py
This patch renames the fail_on_error decorator to fail_on and adds
support to supply list of exceptions. This way the decorator can be used
not only to make tests fail on generic exceptions but also to specify
parts of code with expected failures of given type.
v1: https://github.com/avocado-framework/avocado/pull/715
v2: https://github.com/avocado-framework/avocado/pull/716
Changes:
v2: Exceptions must be specified as tuple, not list
v2: correct the func name in __init__
v3: Improved docstrings
v3: Improved Exception vs. function detection mechanism
> avocado.core.exceptions: Update fail_on_error and rename to fail_on

- .travis.yml
Use addons to install packages instead of sudo.
> .travis.yaml: Migrate to container-based infrastructure

- avocado/core/plugins/gdb.py
When we changed the policy regarding skipping tests,
we forgot to change how the gdb plugin behaves on
undefined behavior - We are not supposed to be skipping
tests during its execution anymore.
So let's fix the problem by changing the undefined
behavior exception to a TestError instead of a TestNAError.
> GDB Plugin: Change undefined behavior exception

- avocado/core/job.py
- avocado/core/loader.py
- avocado/core/log.py
- avocado/core/multiplexer.py
- avocado/core/output.py
- avocado/core/plugins/runner.py
- avocado/core/plugins/test_list.py
- avocado/core/runner.py
- avocado/utils/debug.py
- etc/avocado/avocado.conf
- selftests/all/functional/avocado/basic_tests.py
- selftests/all/functional/avocado/loader_tests.py
- selftests/all/unit/avocado/loader_unittest.py
This pull request is focused on loader plugins unification. First few commits are avocado-debug related and were used to debug the code.
The main changes are:
1. FileLoader was split and proper abstract base class was created
1. `job` was removed completely from job as neither loader, nor test should interact with it. The only parameter left there is `args` as it affects the behavior of some loaders (eg. avocado-vt). This is a stage1 version, which only removes `job` from loaders, it's still passed to the test by `job`.
1. The loader API was radically simplified as explained below.
1. The job logging starts immediately when the job output dir is established and it incorporates `avocado.test` and the `root` loggers (`avocado.linux` was removed and `root` logger added to include the generic …
> avocado.core.loader: Refactor the loader to be consistent [v3]

- avocado/core/job.py
- avocado/core/plugins/test_list.py
- avocado/utils/astring.py
- selftests/all/unit/avocado/astring_unittest.py
Fixes the issue described in the card:
https://trello.com/c/OMDemACG/451-avocado-list-output-contains-many-trailiing-whitespaces
> Fix tabular output

- avocado/utils/astring.py
This patch doesn't generate the trailing whitespaces rather then
removing them from the output afterwards, which was potentially
dangerous as the line might start with the whitespace and got displaced.
> avocado.utils.astring: Improve the tabular_output

- avocado/core/result.py
- docs/source/GetStartedGuide.rst
- docs/source/ResultFormats.rst
- docs/source/RunningTestsRemotely.rst
- docs/source/WritingTests.rst
- man/avocado.rst
- selftests/all/functional/avocado/job_timeout_tests.py
Instead of putting outputs on separate lines, condensate
test results summary into a single line. The new output
looks like:
$ avocado run passtest
JOB ID     : f2f5060440bd57cba646c1f223ec8c40d03f539b
JOB LOG    : /home/user/avocado/job-results/job-2015-07-27T17.13-f2f5060/job.log
JOB HTML   : /home/user/avocado/job-results/job-2015-07-27T17.13-f2f5060/html/results.html
TESTS      : 1
(1/1) passtest.py:PassTest.test: PASS (0.00 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
TIME       : 0.00 s
We updated a few unittests in order to not depend on the
looks of the human output anymore, since unless we are
specifically testing for human output behavior, the unittests
should use machine readable output. Also, the documentation
was updated to reflect the new output …
> [V2] avocado: Shorter app output

- avocado/core/runner.py
Due to successive refactors in the test runner mechanism,
we did not notice that our Ctrl+C handling during job
execution went south. This patch fixes it by moving the
interruption handling to a place where we can actually
break free from the test looping. I also made the interrupt
messages cleaner, while keeping them informative.
The behavior "don't kill test subprocesses unless the user
really wants it" was also kept. You can test this by
running the multiplex test (large collection of tests):
$ scripts/avocado run examples/tests/multiplextest.py --multiplex examples/tests/multiplextest.py.data/multiplextest.yaml
JOB ID     : 783b06e69da4bbc964709748c12f014b65ef5b52
JOB LOG    : /home/lmr/avocado/job-results/job-2015-07-29T02.05-783b06e/job.log
JOB HTML   : …
> avocado.core.runner: Do better Ctrl+C handling

- avocado/core/multiplexer.py
"avocado multiplex" and "avocado run" should share the same variant
numbers. This patch forces multiplexer to set the tag when generating
multiple variants. This way the tag is always set accordingly to the
variant.
When multiple tests of the same name are executed, the first argument is
the multiplexed variant number and additional `.$num` is added to
generate unique name.
v1: https://github.com/avocado-framework/avocado/pull/734
Changes:
v2: Add "variant" prefix so it's easier to see what is variant index and what tag
> avocado.core.multiplexer: Assign tag to match multiplex variant

- avocado/core/multiplexer.py
This reverts commit 913ab2abeedf714fe860be37227ce48578fca377.
Turns out that change appends inconditionally the tags to tests,
even the ones not using the multiplexing system. We need to revert
and figure a better solution.
> Revert "avocado.core.multiplexer: Assign tag to match multiplex variant"

- requirements-selftests.txt
- requirements-travis.txt
Update inspektor requirement to 0.1.16, since it
fixes the bug of it not requiring pep8.
> requirements: Update inspektor requirement

- avocado/utils/iso9660.py
We probably don't want to log the full CDROM content...
> avocado.utils.iso9660: Be less verbose

- etc/avocado/sysinfo/commands
By default Avocado's sysinfo collects both the output of the `mount`
command and the content of the /proc/mounts file. This is really the
same information with a very minor formatting change (the addition of
parentheses around mount options).
Since reading a file is supposed to be faster than running a command,
let's remove the `mount` command execution.
> sysinfo: fix duplicated collection of current mounted filesystems

- avocado.spec
With one new unittest requiring mock, now python-mock
is necessary as a build require.
> avocado.spec: Add python-mock to BuildRequires

- avocado/core/data_dir.py
- avocado/core/job.py
- selftests/all/functional/avocado/basic_tests.py
Right now the symlink `latest` is created when the job finishes. I'd like to create the symlink when the job starts (after the point where we stop removing the results of incorrect execution like `avocado run`).
The motivation is to be able to use `tail -f $PATH/latest/job.log` to monitor the run of the current job.
This implements the card:
https://trello.com/c/QJ4wCD8x/447-reconsider-when-the-latest-log-symlink-is-created
> Reconsider when the `latest` log symlink is created

- examples/tests/trinity.py
The logs from the trinity test are full of ANSI characters that add
colors to messages, which makes it difficult to read/manipulate
them.
Fix that by passing -m to trinity. From trinity --help:
'--monochrome,-m: don't output ANSI codes'
> trinity example test: don't output ANSI characters to the logs

- avocado.spec
They are necessary for the GDB functionality in avocado,
so let's bring them in.
> avocado.spec: Introduce gdb and gdb-gdbserver as dependencies

- avocado/core/runner.py
Some test loader plugins will return the 'timeout' parameter
as a string, so this will cause avocado to break, given that
it will add the timeout to another float value later in the
runner code. Let's ensure that value will be converted to
a float before the addition is made.
> avocado.core.runner: Make getting the timeout from test plugins more robust

- avocado/utils/process.py
We can't set signal handlers inside a thread. In such
cases, let's not try to set the signal handler. This
fixes a problem where subprocesses executed with
`avocado.utils.process` APIs would fail if executed
inside threads.
One example of a thread that runs subprocesses can
be found on our avocado-vt plugin: The virt related
tests run a screendump thread, that will produce
screendumps on a specific directory. These screendumps
will be encoded later into a video. The libvirt VM
implementation takes screendumps by executing
process.run('virsh screendump'). So that's one of
the possible examples where process APIs can be used
inside of threads, and we should support such examples.
> avocado.utils.process: Let SubProcesses to run in threads

- avocado/core/test.py
Avocado allows the usage of GDB, but our default self.srcdir is
incompatible with it causing many tests to fail. This patch simply
replaces the ':' in basename to '_'. It's already created in a temporary
directory, so there shouldn't be any name clashes.
This patch fixes the `modify_variable` test and probably can supersede the:
https://github.com/clebergnu/avocado/commit/d9cf28921f0d2a9f82c23908d23881b09bd5650c
commit. (but I need to check it first)
> avocado.core.test: Use GDB-friendly srcdir

- avocado/core/output.py
- avocado/core/runner.py
The human output prints the test name, progress and pass/skip test
statuses into stdout and fail/error/interrupt ones as stderr. This
results in unreadable output. This patch logs all of them in stdout.
Additionally I changed the throbber colors, but that can be ripped off...
@clebergnu what do you think?
> avocado.core.output: Use stdout to log test statuses

- Makefile
With avocado-vt plugins renamed, 'make link' must
change.
ATTENTION: Please do a 'make clean' before applying
this patch (or clean your source tree before 'make link').
Notes: This should be applied only after https://github.com/avocado-framework/avocado-vt/pull/74, if that's ever applied. This comment is not in the actual commit, it's something that I made with github form edition support.
> Makefile: Modify avocado-vt plugin links

- avocado/utils/gdb.py
- avocado/utils/process.py
The process and gdb related APIs trust on subprocess.Popen
to start a process. When shell=False and the command being
executed is missing, Subprocss.Popen will raise an OSError
with errno 2, with no additional message about what file
is actually missing.
OSError: [Errno 2] No such file or directory
As you might have guessed, my workaround is to capture
OSErrors with errno 2, and re-raise them with a more
helpful message.
'File /usr/bin/gdbserver not found'
* Re-raise the exception when errno != 2 per @ldoktor's review
> [V2] Fix unhelpful message when calling process/GDB APIs

- avocado/core/job.py
Implements the card -> https://trello.com/c/PBJkTCtP/474-show-the-temporary-dir-location-in-the-logs
* Message capitalization changes requested by @ldoktor
> [V2] avocado.core.job: Log avocado temporary dir

- avocado/core/job.py
Display the variants after the tree representation in the job log.
> avocado.core.job: Print variants after the tree representation

- avocado/core/output.py
- avocado/core/result.py
- docs/source/GetStartedGuide.rst
- docs/source/ResultFormats.rst
- docs/source/RunningTestsRemotely.rst
- docs/source/WritingTests.rst
Implements the card
https://trello.com/c/NcxQk6tv/472-show-link-to-html-report-at-end-of-job-not-beginning
See the before/after each commit in the individual commit messages.
* Documentation updated according to a few misses spotted by @ldoktor
> [V2] Output tweaks

- avocado/core/loader.py
- avocado/core/plugins/inner_runner.py
- avocado/core/test.py
- docs/source/GetStartedGuide.rst
- man/avocado.rst
- selftests/all/functional/avocado/basic_tests.py
In some external test suites, what is defined as a "test" can not be
run by itself and need a specific runner script/tool.
This introduces the concept of an "inner runner", that is, a custom
test runner or tool that can deal with custom tests that do follow
the Avocado SIMPLE test definition.
This implements the Trello card:
https://trello.com/c/TpXecE2n/486-introduce-inner-runner-to-avocado-run
More information can be found in the man page section about it.
* removed "level" from "inner level runner" mentions
* replicated docs from man page to "main" docs
> Inner Runner implementation [v2]

- avocado/core/output.py
- selftests/all/functional/avocado/basic_tests.py
The correct mapping for FAIL tests is term_support.fail_str,
not term_support.error_str. This will make FAIL tests to
report as FAIL again.
> avocado.core.output: Fix mistake introduced in aa11081

- examples/tests/linuxbuild.py
With ldoktor's fix 136a78b this is unnecessary and we
risk it being confused for people looking at the
examples.
> examples/linuxbuild.py: Revert self.srcdir override

- avocado/core/runner.py
- requirements-selftests.txt
- requirements-travis.txt
- selftests/all/functional/avocado/interrupt_tests.py
This is a follow up to #755
Fix Ctrl+C handling. Revert my original patch, fix it properly and add a functional test for it. Good stuff.
* Rebased against the latest master
* Fixed the actual bug in one commit and introduced behavior changes on another commit
* Functional tests no longer have nasty code per @ldoktor's comments
* Used `psutil` to do the remaining process checking. It's much nicer (we don't have to mess with `ps` and `grep`, which is pretty horrible) and faster (from 8 seconds to 4 seconds of execution).
> [V3] Fix Ctrl+C for realz

- selftests/functional/test_interrupt.py
If between psutil.procs() and the instantiation of the Process
object the given pid has terminated, we'll get a NoSuchProcess
error from psutils. Let's expand the list comprehension to avoid
getting caught by such a condition.
> selftests/functional/test_interrupt.py: Fix NoSuchProcess bug

- selftests/run_coverage
The https://github.com/clebergnu/avocado/commit/e9c0d8134fcd185b20e1628d106631275f6e3e14 removed the code coverage script. From time to time it's useful. It requires `python-coverage` to be installed, but as it's only an extra feature, I did not add it to the requirements. Those who are suppose to utilize it should be familiar with enough with the process...
> selftests: Add run_coverage

- docs/source/Configuration.rst
If avocado is running from git repos, instead of a regular
system wide install, in tree config files will be used instead
of the system wide config files. Make that clear in the documentation.
> docs: Configuration - Add note about alternate config locations

- Makefile
This patch removes the hardcoded plugin linking and instead queries all
../!(avocado)/Makefile files to link or unlink the plugins. This should
help people to deploy own plugins in the same fashion without the need
to modify avocado's main Makefile.
> RFC: Makefile: Move "make link" to plugins

- selftests/run
The way we built the unittest runner will happily
ignore errors, which is bad from a CI standpoint.
Let's ensure that errors don't go unnoticed by
analyzing the results object and see if it's got
errors or failures.
> selftests/run: Ensure bad statuses trigger an exit code != 0

- docs/source/WritingTests.rst
Currently the yaml contents in this page is missing '!mux'
keyword, run as-is will show users errors. Fixing by adding
keyword '!mux' to the yaml content.
Signed-off-by: Srikanth Aithal <sraithal@linux.vnet.ibm.com>
> docs: Add Multiplexation to WritingTests.html#basic-example

- setup.py
In module avocado.core.plugins.builtin, There is a calling of
os.listdir() to iterate files in the installed python directory.
If avocado is installed in an .egg file which is compressed, it will
fail to load because that path does not really exists.
To avoid this failure, this patch set zip_safe to False explicitly.
So setuptools will install package to a real directory instead of a
zipped .egg file.
The error message I met is as following:
```
File "/usr/bin/avocado", line 4, in <module>
__import__('pkg_resources').run_script('avocado==0.27.0', 'avocado')
File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
self.require(requires)[0].run_script(script_name, ns)
File …
```
> setup.py: Set zip_safe flag to false

- avocado/core/log.py
Initialize "root" logger as "NullHandler" to prevent other libraries
from initializing. Avocado adds file or stream handlers when it
requires them (avocado-vt).
v1: https://github.com/avocado-framework/avocado/pull/742#issuecomment-129687841
Changelog:
v2: Rather than removing handlers this correctly initialize the "root" logger
Test:
1. remove Pillow (pip uninstall Pillow)
2. avocado run boot
=> without the patch it shows the full avocado-vt log in console altogether with `avocado.ui`
=> with the patch everything goes into correct logger
__Question: Side effect is, that the warning about missing "python-imaging" is ignored. There are couple of solutions:__
* Use v1, which displays the warning in stdout and then removes the handlers
* Make the PIL import/warning later in the code, when …
> avocado.core.log: Initialize "root" logger [v2]

- avocado/core/plugins/builtin.py
Hello guys,
I spent couple of hours trying to find out why avocado fails when I run it from Jenkins and passes when I run the very same command manually, always getting "IOError" without the file (the file is not set even in err.filename).
Long story short, it was old environment value "AUTOTEST_PATH", which was not valid and set in Jenkins. This extended debug would point me directly to the place where it happens.
Regards,
Lukáš
> avocado.core.plugins: Print traceback on failure

- examples/testplans/release.json
We did change the short name identifiers that are displayed
in `avocado plugins`. Let's update so people don't get lost.
> examples/testplans/release.json: Change vt plugin identifiers

- selftests/functional/test_interrupt.py
Fedora 21 ships psutils 0.6, that has the API psutil.get_pid_list()
instead of psutil.pids(). Let's make both compatible, for the sake
of running unittests on COPR builds.
> selftests/test_interrupt.py: Make test compatible with psutils 0.6

- avocado/core/remoter.py
The response of very slow machine with uninitilized sshd causes fabric
to raise NetworkError even though timeout was not yet reached. This
patch calls fabric in loop until the timeout is exhausted.
> avocado.core.remoter: Handle fabric NetworkError properly

- avocado.spec
- selftests/functional/test_interrupt.py
An interesting side effect of @clebergnu's work of ditching nose and standardizing all the unittests and functional tests is that all the tests are run at rpm build time. While a great idea, it made building our avocado packages on different chroots challenging. 
This solves yet another problem I found in Fedora, the only ones remaining now are the result of bugs in Fedora 23 and Rawhide, so this covers our bases (mostly).
> Spec files Update

- avocado/core/test.py
- examples/tests/failtest_nasty3.py
- selftests/functional/test_standalone.py
Currently when one passes exception, which is not instance of Exception,
avocado proceeds and returns "INTERRUPTED" test instead of "ERROR". This
for example happens when old-style-class is used as exception. This
patch uses pure "except" without any argument to catch such exceptions
and then it wraps them in "exceptions.TestError" instead.
The same applies to "setUp" and "tearDown", they only use different
class as a wrapper.
> avocado.core.test: Avoid passing ugly exceptions

- examples/tests/errortest_nasty.py
- examples/tests/errortest_nasty2.py
- examples/tests/errortest_nasty3.py
- selftests/functional/test_standalone.py
This patch is a response to @clebergnu recommendation from https://github.com/avocado-framework/avocado/pull/789
> examples.tests: Rename failtest_nasty* to errortest_nasty*

- avocado/core/remote/result.py
- avocado/core/remote/runner.py
- selftests/unit/test_remote.py
This patch adds support for using multiplex files and remote plugin
together. It copies all of the specified multiplex files and then
uses them in execution.
> avocado.core.remote: Add support for multiplex files on remote machine

- avocado/core/plugins/htmlresult.py
- avocado/core/remote/runner.py
- selftests/unit/test_remote.py
This fixes an issue I've noticed after testing @ldoktor's latest PR that gave avocado the ability to run multiplexed tests while using remote/vm plugins. It turns out the problem was slightly different than what I thought at first, but the issue is fixed here anyway.
> Fix HTML report links using multiplexed remote plugin

- selftests/functional/test_basic.py
The Xunit and JSON test cases inherit from PluginsTest. This test defines
some hardcoded-values tests, which are then inherited and run for each
inherited class with the exact same values. This patch creates abstract
class, which all 3 cases share and makes them inherit from it, rather
than from the actual testcase.
> selftests.functional.test_basic: Fix improper inheritance

- avocado/core/data_dir.py
We only want a temporary directory to be created when
`datadir.get_tmp_dir()` is called, and not when the Borg class is
instantiated.
This fixes the issue when temporary directories are created regardless
if a proper job is created or not.
> avocado/core/data_dir.py: do not create temp dir on Borg instantiation

- avocado/core/plugins/vm.py
- avocado/core/remote/result.py
- avocado/core/virt.py
- docs/source/RunningTestsRemotely.rst
By leveraging the `avocado.core.virt.VM.ip_address` method, let's make
the `--vm-hostname` optional. If the IP address can not be found, then
ask users to manually provide it.
If the user has a VM running, or has had it running a "while" back,
chances are pretty high Avocado will be able to find it's IP address.
This PR also includes other related fixes.
> VM Plugin: attempt to find virtual machine IP address

- .travis.yml
- Makefile
- avocado/core/data_dir.py
- avocado/core/job.py
- avocado/core/test.py
- avocado/utils/data_factory.py
- avocado/utils/data_structures.py
- avocado/utils/iso9660.py
- avocado/utils/kernel_build.py
- examples/tests/vm-cleanup.py
- selftests/check_tmp_dirs
- selftests/functional/test_basic.py
- selftests/functional/test_export_variables.py
- selftests/functional/test_gdb.py
- selftests/functional/test_interrupt.py
- selftests/functional/test_job_timeout.py
- selftests/functional/test_journal.py
- selftests/functional/test_loader.py
- selftests/functional/test_multiplex.py
- selftests/functional/test_output.py
- selftests/functional/test_output_check.py
- selftests/functional/test_sysinfo.py
- selftests/functional/test_utils.py
- selftests/functional/test_wrapper.py
- selftests/unit/test_archive.py
- selftests/unit/test_datadir.py
- selftests/unit/test_jsonresult.py
- selftests/unit/test_remote.py
- selftests/unit/test_test.py
- selftests/unit/test_xunit.py
Clean and fix a number of issues with temporary data management in avocado. In particular, unittests are better now and we have more confidence that they are cleaning up after themselves properly.
Also, this fixes the Trello card: https://trello.com/c/fsPcqePU/475-bug-avocado-help-leaves-a-temporary-dir-in-var-tmp
Of course, there are more things to take care of, but now in the plugins, such as `avocado-vt`.
Changed from V1:
* Moved asserts to `data_dir.get_tmp_dir` function
* Prefixes to `tempfile.mkdtemp` now are in the form `'avocado_' + __name__`
> [V2] TMP dir management updates

- avocado/core/plugins/remote.py
- avocado/core/plugins/vm.py
- avocado/core/remote/result.py
- avocado/core/remoter.py
- selftests/unit/test_remote.py
- selftests/unit/test_vm.py
And fix/improve the current implementation by:
- Properly passing the fabric environment parameter (named "timeout",
and not "connection_timeout").
- Set different timeouts for Remote (60 seconds) and VM (120
seconds). The reasoning is that for VM it may be needed to start
the VM itself.
- The timeout passed to fabric is now the timeout the user gives,
divided by the number of attempts.
- Change the default attempts from 3 to 10 so that the overall
timeout is broken in smaller pieces and user hopefully waits less
time for a successful outcome.
This was tested using an EL7 VM using TCG (non-kvm).
> Remote/VM timeouts: introduce timeout command line options

- avocado/core/job.py
- avocado/core/tree.py
When a multiplex file includes a missing file, avocado only reports
"there is a missing file" without any explanations whatsoever. This
patch changes it to a ValueError with the original file and the
missing one.
Additionally it adds missing Exception to try/except, which was
already possible on certain errors, to avoid tracebacks.
Comes from https://github.com/avocado-framework/avocado/pull/813
> avocado.core.tree: Improve error message on missing !include file [v1]

- avocado/core/remote/runner.py
extra_params compounds of multiple items. Let's use " ".join() instead
of manually adding spaces.
Comes from https://github.com/avocado-framework/avocado/pull/813
> avocado.core.remote: Improbe extra_params usage

- avocado/core/data_dir.py
- selftests/unit/test_datadir.py
When one execute 2 jobs with first 7 chars of unique id at the same
time, they end-up in the same logdir.
This patch makes the creation safer. First it creates the main
directory, then it tries to create the directory with 7 chars of the
unique id. On failure it adds another char until it finds empty dir.
In case you spawn 2 jobs with the same id at the same time, it adds
a number starting with 0.
If you spawn more tham 1000 jobs at the same time with the exact same
id, it fails with IOError.
v1: https://github.com/avocado-framework/avocado/pull/813
Changes:
v2: Create the logdir even when logdir is specified
v2: Pylint fixes
v2: Added unittest
v3: Add `assert` in unittest
> avocado.core.data_dir: Make logdir creation safer [v3]

- .travis.yml
Those packages are not being installed anyway, and do not
interfere with general CI testing.
> .travis.yml: Skip installing packages using apt

- requirements-docs.txt
Add a file specifically for our automated documentation
builds (on readthedocs.org).
> docs: Add a readthedocs specific requirements file

- avocado/core/loader.py
- avocado/core/plugins/runner.py
- avocado/core/plugins/test_list.py
- avocado/core/test.py
- docs/source/GetStartedGuide.rst
- docs/source/Loaders.rst
- etc/avocado/avocado.conf
- man/avocado.rst
- selftests/functional/test_basic.py
This pull request fixes some issues and changes the --loaders behavior to only accept test types of given plugin (file.SIMPLE vs. SIMPLE) and only correct test types (excluding MISSING, BROKEN...).
Additionally it moves the inner_runner as a separate loader plugin and renames it to external_runner.
v1: https://github.com/avocado-framework/avocado/pull/823
Changes:
v2:  Use __func__ instead of im_func
v2:  Fix typos and English sentences
v2b: Take care of "allowed_test_types" for simple plugins
v2b: Check that all extra_params were handled
> avocado.core.loader: improve the --loaders [v2b]

- avocado/core/loader.py
- selftests/doc/test_doc_build.py
- selftests/unit/test_loader.py
Since the test loader now attempts to find Avocado instrumented tests by using a parser and doesn't really load/execute test files, it can't tell if a given class inherits from avocado.Test.
For those cases, a developer may signal, using a docstring tag, that either:
* A test class that doesn't look like an Avocado test class is indeed one (":avocado: enable")
* A test class that looks like an Avocado test class should not be treated as such (":avocado: disable")
Also included is a a simple optimization by breaking earlier from the parser loop.
Please test these, and for v1 I'll update the diagrams and documentations.
The documentation is on PR #828.
---
* Added two more tests and suggestions by Lukáš Doktor
---
Changes from v0:
* Use unittest2 on Python 2.6
* Added fix …
> Test Loader: support for enable/disable docstring tags [v2]

- docs/source/ReferenceGuide.rst
- docs/source/WritingTests.rst
This is a follow up to #828.
Add documentation about test tags. This is meant to be pushed after #827 is pushed.
Changes from [V1]:
* Capitalized the words Python and Avocado when refering to the respective programs/programming languages.
> [V2] Add tag docs

- avocado.spec
- debian/control
This is an improved version of #835.
Add python setuptools dependencies in our distro package build files, since that's explicitly required in Ubuntu PPA builds now.
> Package build updates

- Makefile
- avocado.spec
Instead of trusting in rpmbuild to do the rpm builds,
use mock - a program that builds the rpms from fresh
chroots. This ensures that BuildRequires are correct
and that the binary rpms build cleanly.
This requires a few changes to the Makefile targets
and the avocado spec file, laid out in this patch.
Also, add instructions on how to fulfill deps to build
RPM packages.
> Makefile: Use mock to build RPMs

- avocado/core/loader.py
The plugin's discover() method should always return a
list of tests, and not None, since the discover() method
in TestLoaderProxy uses .extend(), that only works with
an iterable. This fixes the issue found when running
`avocado list` (no arguments passed to list):
Test discovery plugin <avocado.core.loader.ExternalLoader object at 0x7f5b42978850> failed: 'NoneType' object is not iterable
> avocado.core.loader: Return empty list instead of None:

- docs/source/GetStartedGuide.rst
The other URL, which denotes git+ssh, requires the user to acknowledge
host SSH keys and so forth. Let's keep things simple.
> Use pure git URL for users getting started with Avocado

- avocado/core/app.py
- avocado/core/parser.py
- avocado/core/plugins/manager.py
- docs/source/Plugins.rst
- man/avocado.rst
- selftests/functional/test_basic.py
In preparation for the large plugin refactor, let's simplify the code ASAP
and drop related (custom) functionality that is going to be replaced.
Standard setuptools entrypoints is going to provide better capability then
our custom code that supports external 'avocado_*.py'module loading.
> Plugins: remove external plugin support

- avocado/utils/software_manager.py
This is a follow up to PR #853.
* Simplify install() on YumBackend proper
* Refactor YumBackend to make the base cmd selectable, so that DnfBackend can use the same code, replacing `yum` with `dnf`.
> [V2] Add DNF backend to software manager

- etc/avocado/sysinfo/commands
dmesg -c does not work well in multi-user/execution scenario and also it
removes the messages for debugging purposes on the system. Let's store
full dmesg and leave it up-to the users to diff it.
v1: https://github.com/avocado-framework/avocado/pull/844
Changes:
v2: Use simplest approach by storing the full "dmesg"
> etc: Use dmesg without `-c` [v2]

- avocado/core/loader.py
- avocado/core/plugins/test_list.py
The 'list_tests' parameters is used to select which tests should be
listed.  IMHO, it sounds like a boolean kind of parameter, which will
either list tests or not. Let's replace that parameter name with
'which_tests', that IMHO give a better message about its intended
usage.
Also, let's standardize the docstrings, and use the declared supported
symbols for these parameters (DEFAULT, AVAILABLE or ALL) instead of their
values (False, etc).
> Test loader: replace list_tests parameter name for a better description

- avocado/core/remote/runner.py
- avocado/core/test.py
- avocado/utils/astring.py
- avocado/utils/process.py
- selftests/functional/test_basic.py
This PR contains fixes to few recent PR.
1. It fixes the log-remaining-buffer-on-exit
2. Refactors the safe-path generation into a utils.astring function
3. Adds selftest to make sure we support quotation properly (linux only)
v1: https://github.com/avocado-framework/avocado/pull/864
Changes:
v2: Fixed typo in commit message
v2: Removed the fix for quoted chars in remote which was causing troubles
> Recent fixes [v2]

- avocado/core/loader.py
Separate the unreachable code commits from the unittest detection PR I've sent previously.
This intends to clean up some code that is now currently unreachable (therefore irrelevant) to avocado.
> Remove unreachable code

- avocado/core/virt.py
The current code assumes that libvirt will always return information
about the VM in a given format, and also assumes that the VM will have
a NIC, which may not be the case.
This adds better checks if the conditions are not met, skipping the
IP detection feature, instead of crashing.
> avocado/core/virt.py: avoid crashing when trying to detect VM IP address

- avocado/utils/process.py
In the newer CmdError class implementation the __init__() doesn't
have anymore the third non-mandatory argument "additional_text".
But still in the different parts of the source code the
CmdError is used with the third argument. If there is no special
reason behind deleting the "additional_text" then I would suggest
to keep for having the backward compatibility.
(for example got argument amount errors while running particular
libvirt tests which had to raise a CmdError exception)
> process.py: CmdError class backward compatibility fix

- avocado/core/multiplexer.py
Hello guys,
while working on the internal filters RFC I made some minor improvements. When using combined tree (deep and flat nodes) with 5845850 variants it takes 31.63s with the old code and 27.63s with this patch (using 800MHz cpu). Nothing major, but still an improvement :smile:.
Regards,
Lukáš
> avocado.core.multiplexer: Optimization

- avocado/core/remoter.py
fabric.network was never imported in avocado.core.remoter,
but fabric.network.NetworkError was referenced in its code,
making the exception to never actually be captured. Let's
fix it.
While at it, let's resolve one complaint of the pycharm
python checker: When importing some module on a try/except
block, make some effort to define the module in case of
failure.
> avocado.core.remoter: Fix error on exception reference

- avocado/utils/software_manager.py
This is a follow up to #889.
Sometimes we might add a repo that has no GPG keys and
still want to install a package from that repo. We need
--allow-unauthenticated to tell APT that we really want to install
it.
> software_manager: Add --allow-unauthenticated to apt options

- avocado/utils/process.py
- selftests/unit/test_utils_process.py
shlex.split() can fail on some strange commands (eg. on an unfinished
quotation). This patch fallbacks to simple string.split() in such cases,
which might return incorrect results, but is safer to use. Although it
logs warning about this notifying the user about possible issue.
This is based on https://github.com/avocado-framework/avocado/pull/887 and also https://github.com/avocado-framework/avocado/pull/875
> avocado.utils.process: Improve detection to run cmd in GDB [v2]

- requirements-travis.txt
Require inspektor 0.1.18 to fix the pylint requirement
problems on python 2.6.
> requirements-travis.txt: Fix inspektor requirement problems

- requirements-travis.txt
- selftests/check_tmp_dirs
Inspektor 0.2.0 has some improvements in the queue,
mainly now by default we are going to start being
picky on unused imports. Which is something I wanted
to do for a long time.
> requirements-travis.txt: Require inspektor 0.2.0

- avocado/core/loader.py
- selftests/unit/test_loader.py
We used to support whitelisting of avocado subtests, but it's not working anymore. This patch brings this functionality back and adds unittests.
> avocado.core.loader: Fix subtests filter

- scripts/avocado
Some distributions mount /tmp as tmpfs, which does not implement all
usual filesystem functions, like O_DIRECT flag. This causes problems for
some tests. Let's check if the user already set TMP in environment and
if not, try to use /var/tmp by default.
This should resolve the issue https://github.com/avocado-framework/avocado/issues/895
> scripts.avocado: Use /var/tmp if TMP not set in env

- selftests/functional/test_output.py
- selftests/functional/test_sysinfo.py
There are a couple of functional unittests that assume that a given
output was produced by the regular UI, that is, the Human output
format.
That is fine, since they're functional tests. But, some situations
lead to test errors, instead of pointing failures. Let's turn those
into explicit checks and fail properly instead of producing errors.
Note: These errors were visible when the human output was disabled, in
the plugin overhaul work, but the fixes still make sense independently
of that work.
---
* Add generated output to aid debugging in case of failures
> Human output: functional test fixes [v2]

- selftests/functional/test_output.py
The `test_gendata` test of `OutputTest` runs the example test
`gendata.py`, but the `gendata.py` itself has a conditional in one of
the tests that make use of the PIL (aka Pillow package) library and
does nothing if it's missing.
PIL (Pillow) is highly dependent on C compilers and libraries to be
able to build itself. This makes systems it harder to run the full
Avocado self tests on more diverse (usually minimalist) systems.
So, let's make that functional test optional, if the libraries are not
present.
> selftests/functional/test_output.py: skip test on absence of PIL library

- Makefile
- requirements-python26.txt
This PR fixes an old issue with make install-requirements and adds Python2.6 requirements. It's based on #881 and on #916.
> Makefile: Add requirements-python26 [v2]

- docs/source/DebuggingWithGDB.rst
- docs/source/ReferenceGuide.rst
This includes the documentation of the "func_at_exit" feature, and also a fix to the GDB module namespace.
> Docs fixes and improvements

- avocado/utils/service.py
On local runs, for non-root users, it's possible to verify
the contents of /proc/1/cmdline. Of course, we should do
this only if we are on a local run (process.run is passed
to get_name_of_init) and we couldn't directly read from
/proc/1/exe.
After this patch, it's possible to instantiate ServiceManager
on local runs made by non-root users.
> avocado.utils.service: Make ServiceManager available to non-root

- avocado/utils/pts.py
- selftests/all/unit/avocado/pts_unittest.py
Based on previous experiences (GDB terminal redirection attempts),
it's common for applications that need to allocate a pseudo to have
the name of the allocated file. This is, unfortunately, something that
the Python standard library doesn't give for free.
This simple utility module wraps and extends the Python standard
library `pty` module, providing a `openpty` function that, besides
allocating the pseudo terminal, also returns its name.
> Pseudo terminals: add utility module

- avocado/core/app.py
Older versions of stevedore does not support `__contains__` method. Use
try/except to handle subcommand handling.
> avocado.core.app: Improve compatibility with older stevedore

- docs/source/GetStartedGuide.rst
RHEL requires epel to be enabled. Let's mention it in the documentation.
> docs: Improve GetStartedGuide for RHEL

- avocado/core/loader.py
- selftests/functional/test_basic.py
If a test has local imports (a fairly common use case),
we have to append the base test dir to sys.path. Otherwise,
we end up having a horrible traceback as a result:
Exception loading test
File "/home/lmr/Code/avocado.lmr/avocado/core/runner.py", line 200, in _run_test
instance = loader.load_test(test_factory)
File "/home/lmr/Code/avocado.lmr/avocado/core/loader.py", line 262, in load_test
test_module = imp.load_module(module_name, f, p, d)
File "scylla_longevity.py", line 5, in <module>
from sdcm.tester import ScyllaClusterTester
ImportError: No module named sdcm.tester
Which is clearly not wanted. We had this problem before
and now we have a regression. It's time for a functional
test to make sure we don't regress again.
Signed-off-by: Lucas Meneghel …
> avocado.core.loader: Append test directory to sys.path [v2]

- selftests/functional/test_basic.py
There are a few leftover references to the old Plugin classes in
the functional tests. Let's remove them.
> selftests/functional/test_basic.py: remove references to old Plugin

- avocado/core/html.py
- avocado/core/job.py
We currently only set HTML support as disabled if the `html.py`
library fails to import. The truth is that missing files that
are intended to be present on the (separately packaged) HTML
plugin package can cause other kinds of exceptions.
Let's add an extra check, looking if the resource files are
present (currently the template file).
Note: there's one outstanding bug, for which a fix is being
worked on. When Avocado is installed, either from packages
or from source code, the HTML plugin entry point is always
registered. That means the plugin Python module is always
tried to be loaded. If the plugin *package* is not installed,
an error message is given on the command line.
> HTML output support: behave when the plugin is not installed

- avocado/core/loader.py
This reacts to: https://github.com/clebergnu/avocado/commit/62ae0d60b769252d2c55117bbdbf6f654a2f642b#commitcomment-15297513
It's safer to use "remove" in case someone adjusted "sys.path".
> avocado.core.loader: Use sys.path.remove instead of pop

- avocado/core/loader.py
- selftests/functional/test_loader.py
- selftests/unit/test_loader.py
As per report on issue #952, Avocado currently finds multiple tests
when multiple test names exist in a given Python class. When the
test code itself is loaded and the test class instantiated, only
one test method will remain (others will have been overloaded by
that one).
So, to mimic this in the static, AST based, test discovery, let's
make the test methods unique and try to keep the order in which the
AST parser found them.
---
* Keep order of methods found by the AST parser
> loader: make test methods unique when discovering tests [v2]

- avocado/core/dispatcher.py
- avocado/core/loader.py
These are two fixes that were found to be necessary while investigating https://github.com/avocado-framework/avocado-vt/issues/322.
> Make loader registration unique and make dispatcher propagate exceptions

- avocado/plugins/wrapper.py
--gdb-run-bin is incompatible with --wrapper option. The original code
checked presence of "gdb_run_bin" in args, but it's always present with
default value `[]`. This patch changes the check to gettattr.
> avocado.plugins.wrapper: Check the --gdb-run-bin value

- selftests/functional/test_interrupt.py
In InterruptTest.test_well_behaved, sometimes it
takes a bit extra time for avocado to end, causing
a psutil.NoSuchProcess exception by the time the test
tries to access .cmdline() in the Process() object.
That condition means the process is already out of
the process list, which means the test passed. Let's
handle the NoSuchProcess exception accordingly.
> selftests/test_interrupt.py: Handle timing problems

- avocado/plugins/remote.py
- avocado/plugins/vm.py
Turns out that setting the argument value directly does not suit most
of our code. Let's revert back to the old way of setting the remote/vm
result/runner until we implement proper runner and result plugin interfaces.
> VM/Remote plugin: revert to previous technique for setting result/runner

- avocado/core/remote/result.py
- avocado/plugins/vm.py
For parity of features with the remote plugin, let's add the SSH
port as an option of the VM plugin as well.
> VM plugin: add port number as option

- Makefile
The "make link" target purpose is to help avocado developers to prepare
environment to run avocado from sources including all subprojects.
Nowadays it requires to run "setup.py develop" manually, but let's
assume wast majority of users of "make link" feature use "setup.py
develop --user" and call it automatically for each subproject (if they
support that).
This way simple "make link" prepares the environment to run avocado from
sources. It can also be used when new targets (plugins) are added
without the need to think which subproject needs to be updated.
NOTE: The subprojects are responsible to add the "python setup.py
develop --user" into the "link" and "unlink" targets.
> Makefile: Call setup.py develop in "make link"

- avocado/core/job.py
- avocado/core/loader.py
- avocado/plugins/replay.py
Hi guys (especially @apahim),
there are few minor things I mentioned in review, but were not as important to prevent inclusion. I'd like to avoid special handling in `job` for plugins as much as possible. The commit 188b812 is maybe a bit controversial, but I can see the benefit for other future plugins (maybe we can rename the `--multiplex-files` to `--multiplex` which would make it less confusing).
v1: https://github.com/avocado-framework/avocado/pull/965
Changes:
v2: Fixed typo "does not exist"
> avocado: Couple of minor --replay changes [v2]

- avocado/core/exceptions.py
- avocado/core/html.py
- avocado/core/result.py
- avocado/core/status.py
- avocado/core/test.py
- avocado/core/xunit.py
- avocado/plugins/replay.py
- docs/source/ReferenceGuide.rst
- selftests/functional/test_replay.py
Merging the concepts of TEST_NA and SKIP and limiting the status list to be used in --replay-test-status option.
avocado-vt pull request:
https://github.com/avocado-framework/avocado-vt/pull/338
> Rename TEST_NA and handle status options in --replay-test-status

- selftests/functional/test_interrupt.py
Turns out I thought out a1afd91 poorly, I needed to use
a more encompassing try/except block, and replicate the
block in the two tests that do psutil shenanigans.
> test_interrupt.py: Finish change a1afd91

- avocado/core/parser.py
- selftests/functional/test_argument_parsing.py
- selftests/functional/test_basic.py
- selftests/functional/test_replay.py
v1 #981
v1 #982 
Changes:
- Changed from print_usage() to print_help() on invalid argument.
> avocado.core: show the subcommand help on unknown argparse option [v3]

- avocado/core/test.py
Another round of cleanups, according to:
https://trello.com/c/W58vhyHR/539-bug-some-avocado-test-methods-and-atributes-are-public
---
* Be more explicit when returning `None` on `basedir`.
> Test namespace cleanup [2nd round] [v2]

- avocado/core/job.py
- selftests/functional/test_loader.py
Because the current implementation of avocado.main() creates a job
and runs "sys.argv[0]" to implement standalone mode, it ends up
running itself over and over.
This simple proposed fix, prevents avocado.main() from running
itself again if called from itself. Since they are on different
processes, the mechanism chosen to do this is to set an environment
variable, that will be seen by the next process.
Also, by exiting from main() with an error code, the test first
level test will fail. This will let the user know that the chosen
approach (SIMPLE tests written in Python and calling main()) are
not worthy of a PASS.
The functional tests make use of Python's standard library utilities
(subprocess module) directly for running Avocado because of current
issues with Avocado's own process …
> avocado.main(): avoid an infinite fork loop bomb [v4]

- avocado/utils/process.py
- avocado/utils/service.py
- avocado/utils/software_manager.py
- selftests/unit/test_utils_process.py
- selftests/unit/test_utils_service.py
This is a follow up to #974
Following @ldoktor's suggestion, I took the longer path of adding sudo related options to process APIs, and then using them on the service and software_manager modules.
Changes:
[v2] Renamed function that modifies process.run and friends commands upon sudo value
[v2] Mock path.find_command so that it's not necessary to skip unittests
[v2] Added unittests that simulate machines without sudo installed
> Run commands that require admin privileges with 'sudo' [2]

- avocado/core/test.py
- selftests/functional/test_basic.py
This is a continuation of the work on the `avocado.Test` class. While these few patches actually don't to much cleaning, they are, as said before, a continuation of the previous work, and they also address an unrelated bug that was found during code reviews.
> Test namespace cleanup [3rd round]

- avocado/core/runner.py
- selftests/functional/test_basic.py
The "replay_map" allows to substitute the test class with custom class.
The problem is, that the "methodName" defined in "test_params" might not
exist in this class.
We have two choices, either leave it up to the user, to substitute with
a compatible class (eg. by creating the "methodName" in "__init__"
before calling the super.__init__), or we can require them to always use
given "methodName". This patch uses the second approach as it seems less
magical to me.
Reproducer:
```
avocado run skiponsetup
avocado run --replay $PREV_ID --replay-test-status PASS
```
> avocado.core.runner: Force methodName on replay_map substitution

- avocado/core/job.py
- avocado/core/remote/result.py
- avocado/core/result.py
- avocado/plugins/html.py
- avocado/plugins/journal.py
- avocado/plugins/json.py
- avocado/plugins/remote.py
- avocado/plugins/vm.py
- avocado/plugins/xunit.py
- selftests/functional/test_output.py
Small improvements to test results found while debugging issue described at:
https://trello.com/c/wrDuEnYI/578-bug-avocado-can-t-mix-remote-vm-runners-and-additional-results-html-xunit-etc
> Test result small improvements

- avocado/core/settings.py
Reuse the value of "_config_path_intree" to set "_config_path_intree_extra".
> avocado/core/settings.py: simple optimization

- Makefile
The check target have a couple of (relevant) directory cleaning up
commands that are, IMHO, out of place. Let's move them to the clean
target.
> Makefile: move the removal of avocado directories to the clean target

- avocado/core/test.py
The code for executing binary is the same for booth, let's require
self._command to contain the binary and merge the code to avoid future
diversion.
> avocado.core.test: Merge Simple and External runner code

- avocado/utils/process.py
- selftests/unit/test_utils_process.py
This function is useful, when one executes shell=True commands where
he sets values and then executes command. He can use this function
to get the actual binary path instead of the first variable=value
assignment.
v1: https://github.com/avocado-framework/avocado/pull/1009
Changes:
v2: Added unittest
v2: Improved docstring
v2: Fixed typo in commit message
> avocado.utils.process: Add function to get first binary from shell cmd [v2]

- avocado/core/loader.py
- avocado/core/multiplexer.py
- avocado/core/runner.py
- avocado/core/test.py
This PR first removes the possibility to initialize params in loader, which does not even work. Then it removes the "avocado_inject_params" hack, which should be superseded by different avocado-vt init https://github.com/avocado-framework/avocado-vt/pull/353 . On top of this cleanup it sets `self.timeout` in `Test.__init__`, which is then used by the `runner` instead of `Test.params.get("timeout")`, which gives incorrect results on avocado-vt as `self.params` contains different params.
v1: https://github.com/avocado-framework/avocado/pull/990
v2: https://github.com/avocado-framework/avocado/pull/1008
Changes:
v2: Everything except the idea of "self.timeout"
v3: Removed invalid params docstring
v3: Always set self.timeout in Test and use existing self.timeout as default
__This commit …
> avocado.core: Avoid timeout bug in avocado-vt [v3]

- Makefile
One of the clean steps executed prior to the deletion of the 'pyc' files
calls `$(PYTHON) setup.py develop --uninstall --user`, which ends up
loading modules and creating some of those again. Let's change the order
so that the Python compiled files are really gone after a `make clean`.
> Makefile: cleanup Python compiled files properly

- avocado/core/app.py
- avocado/core/runner.py
- avocado/utils/process.py
- docs/source/DevelopmentTips.rst
- selftests/functional/test_basic.py
Sometimes it's useful for debugging purposes to pause the running test.
This is currently hard as tests run as subprocess. This patch adds
a special handler for SIGTSTP (ctrl+z) which sends SIGSTOP/SIGCONT
to the test process and it's children.
v1: https://github.com/avocado-framework/avocado/pull/1003
v2: https://github.com/avocado-framework/avocado/pull/1014
Changes:
v2: Use Lock to avoid concurrent execution
v2: Remove "\n" from job.log
v3: Added fix for infinite hang in avocado (new commit)
> avocado.core.runner: Support sigtstp to interrupt tests [v3]

- avocado/core/job.py
- avocado/core/remote/__init__.py
- avocado/core/remote/result.py
- avocado/core/remote/runner.py
- avocado/core/result.py
- avocado/core/runner.py
- avocado/plugins/vm.py
- selftests/unit/test_remote.py
- selftests/unit/test_vm.py
This change was intended to fix a "simple" bug, that is, to allow remote/vm runners to be used alongside with extra results (HTML, JSON, etc), but it turned out to be a reasonable refactor.
Besides review, this PR is lacking one last fix to one of the affected unit tests. The last commit brings a WiP version of a final fix.
v0: https://github.com/avocado-framework/avocado/pull/1024
Changes:
v1: Initialize "job.urls" in "job.__init__"
v1: Unittest fixes
v1: New commit which removes unused code from "job"
> Move remote/vm result functionality to runners [v1]

- .travis.yml
- Makefile
- requirements-python26.txt
- requirements-travis-python26.txt
- requirements-travis.txt
- requirements.txt
Managing different requirements files for different python version
requires much more efforts when the requirements became too complex.
This issue emerged when a required package `stevedore` decide not
supporting Python 2.6 since version `1.11.0`.
```
>>> import stevedore
File "/usr/lib/python2.6/site-packages/stevedore/__init__.py", line 23, in <module>
LOG.addHandler(logging.NullHandler())
AttributeError: 'module' object has no attribute 'NullHandler
```
Pip provides a feature named [Environment Markers](https://www.python.org/dev/peps/pep-0496/)
for requirements file to include specific packages conditionally which could
properly solve this issue.
This fix:
1. Use environment markers and merge python version …
> Use environment marker for conditional requirements

- avocado/plugins/replay.py
- selftests/functional/test_replay.py
v2:
- Better error message.
- Using `if $foo is not None` instead of `if $foo` notation.
v1 #1031
> avocado.plugins.replay fix crashes when using --replay-test-status [v2]

- avocado/core/html.py
- requirements-travis.txt
Hello guys, this addresses the https://github.com/avocado-framework/avocado/issues/891 issue and hopefully fixes it properly. Details are in commit messages.
v1: https://github.com/avocado-framework/avocado/pull/1030
Chages:
v2: Rebase
v2: Use new requirements.txt scheme
> avocado.core.html: Fix the unicode handling for older pystache [v2]

- Makefile
Hello guys,
this reacts to https://github.com/avocado-framework/avocado/pull/1033
Our `requirements.txt` depends on `pip>=6.1` so in my opinion we have to include this in the requirements. We can't do it in `requirements.txt` as older `pip` can't cope with that, so let's use `make requirements` target to check the pip version first.
On systems with matching pip (F22+) nothing happens, the user only sees his pip version matches the requirements and nothing is upgraded. On older systems (F21, or debian jessie) this upgrades the pip and then runs our requirements, which should be correctly installed. Without the upgrade the user gets ugly python traceback.
The last modification is probably my fault. I used `--upgrade`, because I though pip works as `yum`. It works differently and the …
> Makefile: pip adjustments

- avocado/core/test.py
- docs/source/WritingTests.rst
- examples/tests/cabort.py
- examples/tests/datadir.py
- examples/tests/doublefree.py
- examples/tests/doublefree_nasty.py
- examples/tests/gdbtest.py
- examples/tests/linuxbuild.py
- examples/tests/modify_variable.py
- examples/tests/raise.py
- examples/tests/synctest.py
- examples/tests/trinity.py
This is a continuation of the work on the avocado.Test class. While these few patches actually don't to much cleaning, they are, as said before, a continuation of the previous work, and they also address an unrelated bug that was found during code reviews.
Reference:
https://trello.com/c/W58vhyHR/539-bug-some-avocado-test-methods-and-atributes-are-public
> Test namespace cleanup [4th round]

- avocado/core/data_dir.py
- avocado/core/test.py
- avocado/utils/asset.py
- avocado/utils/path.py
- docs/source/WritingTests.rst
- etc/avocado/avocado.conf
- selftests/unit/test_utils_asset.py
v8:
- Use `$data_dir/cache` as the global fallback cachedir instead of a per test temporary fallback cachedir.
v7: #1060 
- Drop the `Asset.path` attribute.
- Do not fetch-on-init.
- Add support to https.
- Trust `settings.get_value()` will return the type requested. A list in this case.
v6: #1038 
- Create symbolic links instead of copying file when `file://` location is provided.
- Changed from `download._get_file()` to `download.url_download()` to be used for `http://` and `ftp://` , since we don't copy files from `file://` locations anymore. 
- Moved `avocado.core.data_dir._usable_rw_dir()` to `avocado.utils.path.usable_rw_dir()` and use it in asset fetcher.
-  Some minor code style improvements.
v5: #1028 
- Support for multiple cache directories in cache_dirs configuration key.
- …
> Asset fetcher [v8]

- Makefile
- avocado/core/loader.py
- avocado/core/safeloader.py
- avocado/utils/data_structures.py
- contrib/avocado-find-unittests
- selftests/checkall
- selftests/functional/test_output.py
- selftests/unit/test_loader.py
- selftests/unit/test_safeloader.py
- selftests/unit/test_utils_linux_modules.py
- selftests/unit/test_utils_service.py
When the safe(r) test loader mechanism was introduced in the `avocado.core.loader` module, it was written specifically to address Avocado's own needs (that is, `avocado.Test` based test classes).
Now, we want to:
* Allow the safe test loader to be optional, that is, allow the user to run `$ avocado list --unsafe` or similar
* Increase the scope of tests that can be run by Avocado, and that includes standard Python unittests
The first step is to abstract and isolate the original safe loader code, which is done and this PR in the form of the  `avocado.core.safeloader` module. Then, as a PoC, we deliver a contrib script that makes use of this new module and finds unittests on Python source code files.
This brings us to an interesting situation, where, although not without flaws or …
> Safe Loader: a second, more abstract and reusable implementation [v2]

- docs/source/WritingTests.rst
Asset fetcher changed the fallback directory to be the data_dir/cache
instead of a test temporary directory. This patch reflects in docs
that change.
> Adjust the asset fetcher documentation

- avocado/core/data_dir.py
- selftests/functional/test_basic.py
- selftests/unit/test_datadir.py
The configurations related to the "data_dir" are currently read at module load time. This means that changes in the configuration between module load time and changes to the settings (such as parsing an additional config file) is never seen.
This fixes this issue, making every lookup of the data_dir settings dynamic.
Reference:
https://trello.com/c/QSNlIbP6/574-bug-data-dir-module-ignores-settings
> data_dir: make settings dynamic

- avocado/core/loader.py
- avocado/core/replay.py
- avocado/plugins/replay.py
- selftests/functional/test_replay_basic.py
- selftests/functional/test_replay_external_runner.py
v5:
- Testing replay with and without external-runner in original job.
v4: #1071 
- Test with external runner in original job.
- Use json module (instead of ast) to load job result.
v3: #1069 
- Rebased to use the new logging.
v2: #1056 
- Whitelist with args options to replay.
- external-runner-chdir defaults to None.
v1: #1046 
- Record the loader options and reload them on job replay.
> avocado.pugins.replay record/replay loader options [v5]

- docs/source/GetStartedGuide.rst
Trying to follow the docs to install avocado from source,
make requirements command fails doe to the missing
dependencies.
This patch adds the two missing dependencies I had to install
in addition to the ones listed in docs.
Reference: https://trello.com/c/1ryTxsXw
> fix docs to not fail on make requirements

- avocado/core/test.py
Depending on the name of the test, it may need a "safe" tagged name,
that is, one that can be turned into a filesystem path. Most, if not all,
cases apply to SIMPLE tests, that have slashes in the test names, such
as "/bin/true".
The test class code needs to check if the "safe" test name directory
exists, and apply the incremental numeric tag to it.
Also, an explicit check that raises a test setup failure was added, so
that Avocado won't silently reuse an existing test log dir.
Reference: https://trello.com/c/nPrrRv5N
> Test: increment to tagged name not applied on "unsafe" names

- avocado/core/remoter.py
Fabric automatically echoes all text typed into the terminal back
out to the user. This makes avocado treat the echoed strings as
fabric return.
This patch disables terminal echo in fabric.
Reference: https://trello.com/c/xqN7bq6N
> Turn fabric pty off

- examples/testplans/release.json
Handling tty in travis is quite problematic, this adds a manual selftest
for paginator issue where tty was left in a different state than it was
before avocado execution.
v1: https://github.com/avocado-framework/avocado/pull/1081
Changes:
v2: Use tab instead of soft spaces
> examples.testplans: Add tty cleanup logging selftest

- avocado/core/parser.py
- avocado/core/remote/runner.py
- avocado/plugins/replay.py
- avocado/plugins/run.py
- docs/source/Replay.rst
- man/avocado.rst
- selftests/functional/test_replay_basic.py
- selftests/unit/test_remote.py
Let's formally use `--multiplex` as an option on `run` and deprecate `--multiplex-files`.
Also, to avoid ambiguity and allow for precise argument names and this
command line examples, let's disable abbreviations. One example where
this led to confusion:
```
$ avocado run --show test passtest
```
Instead of
```
$ avocado --show test run passtest
```
With this change, the first command line would result in:
```
avocado run: error: unrecognized arguments: --show
```
Which is much more precise than:
```
Unable to discover url(s) 'test' with loader plugins(s) 'file',
'external', try running 'avocado list -V test' to see the details.
```
Disabling the arguments abbreviation without depending on the fix
applied to Python itself is suggested here:
http://bugs.python.org/msg204678
---
Changes from …
> Command line argument parser: disable abbreviations [v2]

- avocado/core/loader.py
- selftests/functional/test_basic.py
A test base on the external runner feature depends on both the
external runner and the test URL. These two are always combined to
generate the complete command that will be executed by Avocado.
But, the Avocado command line application does not require URLs to be
given on the command line, because these may come from other sources
on loaders other than the basic FileLoader.
So, let's also explicitly require a URL to be given to to the External
Runner loader to return a test factory (class and parameters).
> External Runner: deal with empty test URL

- docs/source/WritingTests.rst
Let's give a real example on how to use logging streams when writing
tests, and use the runner options that allow for logging streams to
be captured into log files.
---
* Fixed command line option name from `--store-log-stream` to `--store-logging-stream`
* Add sleeps between "steps", and while at that, also record the sleep on the progress stream
> docs: add logging capabilities docs to test writers [v2]

- avocado/core/remoter.py
We need to finish when the time.time() is greater than the timeout, not
lower.
> avocado.core.remoter: Correct the timeout condition

- avocado/core/output.py
- selftests/functional/test_streams.py
Hello guys, the `--show $stream:$level` currently does not work as there is an incorrect variable used to parse the level from. Additionally I found out we log only INFO level for "remote" builtin stream, which is different from the "remote.log" people are used to. There is also no way to tweak the level for builtin streams so I hardcoded "DEBUG" for now and added card to allow overriding it: https://trello.com/c/FnZaz8ml/631-support-log-level-specification-for-built-in-streams
> avocado.core.output: Two bugfixes

- avocado/core/job.py
- selftests/functional/test_basic.py
In case no tests are found we advice users to run `avocado list -V`
followed by list of urls, which does not really work with no-urls given.
This patch adds second message in case the user does not provide urls
(eg. is using the `--vt-config` option).
> avocado.core.job: Provide a better message when no tests found

- avocado/core/parser.py
v1: #1103 
- Use [`nargs='?'`](https://docs.python.org/2.7/library/argparse.html#nargs) for `--show` option.
v2:
- Use `nargs='?'` for `--config` as well.
> add nargs='?' to toplevel options so we accept empty argument [v2]

- .gitattributes
*.svg, .min.js and .min.css are text files, but they're not
intended to be edited by hand.
Worst of all, they keep poluting the output of git grep.
> Add .gitattributes, marking some files as binary

- avocado/core/exceptions.py
- avocado/core/job.py
- avocado/core/remote/runner.py
- avocado/core/runner.py
- avocado/core/test.py
- avocado/core/xunit.py
- selftests/functional/test_basic.py
- selftests/functional/test_job_timeout.py
v1 #1101:
- Include interrupted tetsts in xunit results.
- Fix return code for timed out jobs.
v2: #1102 
- Make the exit code OR'able.
- Put job return code in line with OR'able exit code.
- Adjust tests.
v3: #1105 
- Restore v1 (#1101).
- Remove `add_interrupted()` from `xunit` and reuse `add_error()` for `INTERRUPTED` status.
v4: #1108 
- Return only a list with all tests status from `runner` to `job`.
- Adjust `remote.runner` to aslo return the new `summary` list.
- When the test is skipped due to a job timeout, overwrite its `SKIP` status on `summary` with `INTERRUPTED` so `job` can set the right status.
v5: #1111 
- `summary` is now a `set()` containing `INTERRUPTED` when the job is timed out or `FAIL` if any test finishes with a bad status (`not status.mapping(test-status)`). Empty …
> Fix job status on timeout [v6]

- avocado/utils/astring.py
- selftests/unit/test_astring.py
People tend to mix unicode, strings and encoded strings. This patch adds
"avocado.utils.astring.string_safe_encode" function, which tries to
allow all of the listed inputs and it assumes "utf-8" is in use for
encoded strings.
This function is then used in the tabular_output to avoid
"UnicodeDecodeErrors" for all listed input types.
This fixes the https://trello.com/c/ulT3Cbl4/592-bug-avocado-list-crashes-with-non-ascii-dir-names
> avocado.utils.astring: Be more lenient regarding utf-8 chars

- avocado/core/loader.py
The _make_avocado_tests accepts "make_broken" function and not
"list_non_tests" flag. We forgot to update one occurrence of this.
> avocado.core.loader: Use make_broken in _make_avocado_tests

- avocado/core/runner.py
- avocado/core/test.py
- avocado/utils/astring.py
- selftests/functional/test_basic.py
- selftests/unit/test_test.py
This patchset fixes the issue https://trello.com/c/6LBKIUtN/591-bug-long-filenames-crash-avocado and avoids crash on https://trello.com/c/BdC56G6X/542-bug-avocado-can-t-handle-exceptions-raised-while-reading-the-test-queue and https://trello.com/c/JhfMuJkW/623-bug-regression-no-test-result-for-some-relative-pathnames
Basically it modifies the way `Test.logdir` is created and reuses the `Test.logdir` for other file name related variables.
Last but not least it adds commit to fix missing test status on early failure.
v1: https://github.com/avocado-framework/avocado/pull/1090
v2: https://github.com/avocado-framework/avocado/pull/1098
v3: https://github.com/avocado-framework/avocado/pull/1109
Changes:
v2: New commit to fix the names with leading '.'
v3: Different approach to uninitialized …
> Handle long filenames in avocado and fix unknown test status [v4]

- avocado/core/result.py
Currently UI shows coherent results, reporting tests that where not
executed due to an interruption as SKIP. This information is not in
line with results.json, which does not account un-executed tests.
This patch changes the _reconcile() call from HumanTestResult() class
to its parent class, TestResult(). That way all classes inheriting from
TestResult() will have proper results to report.
Reference: https://trello.com/c/8CXFl13M
> avocado.code.result fix results.json on job interruption

- avocado/core/loader.py
- avocado/core/runner.py
- avocado/core/test.py
- selftests/functional/test_basic.py
v1: #1107 
- Fake the test class when the original class cannot be loaded.
- Capture the load exception and log it.
- Set `status` = `ERROR` to the test that failed to be loaded.
v2: #1116 
- User `self.error()` instead of a new exception.
- Functional test.
v3: #1117 
- Rename the fake test class from `TestLoaderError` to `TestError`
- Rename the fake test function from `test` to `unknown`
- Better 'python bad code' in test.
v4:
- Restore test name function as `test`.
- Functional test to assert the original test class/name is in the log.
> avocado.core.loader fix crash on loader exception [v4]

- avocado/core/xunit.py
- docs/source/ResultFormats.rst
- requirements-selftests.txt
- requirements-travis.txt
- selftests/functional/test_basic.py
- selftests/functional/test_job_timeout.py
- selftests/unit/junit-4.xsd
- selftests/unit/test_xunit.py
v1: #1119 
- Change xunit key name from `skip` to `skipped`.
- Adjust tests.
- New test to validate xunit output against _junit-4.xsd_.
v2:
- Improve test message.
> avocado.core.xunit fix XUnit results fail XSD validation [v2]

- avocado/core/test.py
- selftests/unit/test_test.py
Hello guys, I'm sorry I forgot to cleanup the flexmock in one of the selftests and there was also a hidden bug in the filename length check.
@clebergnu thanks for the report.
> Filename handling bugfixes

- avocado/core/remoter.py
v1: #1128 
Avocado is not interactive. Remote can prompt for interaction for
a number of reasons: unknown host key, password request and so on.
This patch makes Avocado to fail when interaction for remote access is
needed, forwarding the correspondent Fabric's message for the user.
v2:
- Exception class in the beginning of the module.
- Keep just the `pass` in the exception class.
v3:
- Rename exception class.
> avocado.core.remoter remote actions should fail on prompt [v3]

- avocado/core/settings.py
When avocado is run out of the source tree, it ignores the user local
configuration (~/.config/avocado/avocado.conf).  IMHO this is both
inconsistent and bad for development sessions.
> avocado/core/settings.py: do not ignore user local configuration

- avocado.spec
Commit 8dad284 introduced a requirement on python-lxml. Let's reflect
that on the SPEC file.
> avocado.spec: add python-lxml to build dependencies

- avocado/core/exit_codes.py
- avocado/core/job.py
- docs/source/ResultFormats.rst
- selftests/functional/test_job_timeout.py
Currently, exit codes cover all situations with one single value.
This patch makes exit codes to be ORable, so we can better represent
the variety of things that happens during an Avocado execution.
Reference: https://trello.com/c/SU5fixgH
> Make exit codes a combination of meanings (aka ORable)

- avocado/core/multiplexer.py
- avocado/core/parser.py
- avocado/plugins/multiplex.py
- avocado/plugins/run.py
The `args.default_multiplex_tree` stands for default avocado params,
which currently supports only `multiplexer` implementation. This might
change in the future, but this variable could be used by other backends
too. So let's rename it now to `default_avocado_params`.
Additionally it's only set when the system is multiplexer-enabled, but
it has nothing to do with the multiplexer (directly). Multiplexer is
only one of the sources of params. So let's initialize it always. This
avoids a bug in `avocado-virt`, which uses this default params to set
it's params and it does that via this generic API (not dependent on the
multiplexer at all).
__This has to be merged together with https://github.com/avocado-framework/avocado-virt/pull/78 PR__
> avocado: Rename the `args.default_multiplex_tree`

- avocado/core/html.py
- avocado/core/jsonresult.py
- avocado/core/result.py
- avocado/core/test.py
- avocado/core/xunit.py
- selftests/unit/test_jsonresult.py
Hello guys,
while reviewing the jsonresult PR I noticed that the results are quite broken. This PR tries to fix the most pressing issues and removing possible problems by removing unused API (which has a minor speedup effect).
Please see the commits for details.
v1: https://github.com/avocado-framework/avocado/pull/1121
Changes:
v2: Removed the unused API also from TestResultProxy
v2: Always use -1 for undefined time/duration references
v2: Squash commits which were suppose to be squashed
v2: Remove accidentally committed remnant from debugging
> avocado.core.result: Couple of bugfixes and cleanups [v2]

- avocado/core/remoter.py
- etc/avocado/avocado.conf
- selftests/functional/test_thirdparty_bugs.py
v1: #1127 
- Create `reject_unknown_host` option.
v2: #1135 
- Defaults to `False` due to the Paramiko issue with `ecdsa` host key fingerprint.
- Proper config section.
v3: #1140 
- Include `disable_known_hosts` option.
- `reject_unknown_hosts` defaults to `True` internally.
- Test to check when the issue in Paramiko gets fixed.
v4:
- Add `__Insecure__` in avocado.conf comments.
- Skip functional test when url is not available.
> avocado.core.remoter option to reject remote unknown hosts [v4]

- avocado/core/remoter.py
when the user provides --remote-password and the host is not found
in known_hosts, it raises fabric.network.NetworkError. We catch this
exception in remoter as usually it means the connection timed out
and if we have enough time we try it again.
This patch checks if 'not found in known_hosts' is present in the
exception message and breaks the loop to retry, re-raising the exception.
> avocado.core.remoter fail early when host is not in known_hosts

- avocado/core/remoter.py
We use `False` in avocado.conf and remoter should have the same default.
> avocado.core.remoter fix default for reject_unknown_hosts

- README.rst
- docs/source/Introduction.rst
The slides links are broken.  Let's remove them, and eventually re-add
them when they are put back in place.
> docs/source/Introduction.rst: remove broken link to slides

- examples/testplans/release.json
It's `vt_list` and not `vt_lister`, so let's fix it.
> examples/testplans/release.json: fix vt_list plugin name

- avocado/utils/service.py
When using a system V init service manager to check an unavailable
package, the error messages are sent via stderr, not stdout.
Signed-off-by: Hao Liu <hliu@redhat.com>
> avocado.utils.service: Check stderr when service do not exists

- avocado/core/remoter.py
The function _update_fabric_env updates only hostname, username,
key_file and port, but some users might use password. Let's update it as
well.
> avocado.core.remoter: Update the password argument on env update

- .travis.yml
- Makefile
- avocado.spec
- avocado/core/dispatcher.py
- avocado/core/job.py
- avocado/plugins/base.py
- avocado/plugins/jobscripts.py
- avocado/plugins/plugins.py
- docs/source/Plugins.rst
- docs/source/ReferenceGuide.rst
- etc/avocado/conf.d/jobscripts.conf
- etc/avocado/scripts/job/post.d/README
- etc/avocado/scripts/job/pre.d/README
- examples/plugins/README.rst
- examples/plugins/job-pre-post/mail/avocado_job_mail.py
- examples/plugins/job-pre-post/mail/setup.py
- examples/plugins/job-pre-post/sleep/avocado_job_sleep.py
- examples/plugins/job-pre-post/sleep/setup.py
- selftests/functional/test_plugin_jobscripts.py
- setup.py
This introduces a new Plugin interface, and allows plugin writers to execute custom actions before and after the jobs are run.
The plugin interface gives the avocado.core.job.Job instance to plugin writers, who can collect information from it.
Also, two examples are given, including a "real world" mail notification plugin.
--
Changes from v5 (#1147):
* Made job `test_suite` a documented/public attribute
* Moved the pre job hook to after test discovery/resolution
Changes from v4 (#1139):
* Catch all exceptions (include old style ones) in the dispatcher
* Slightly improved the docstrings
* Changed the jobscripts configuration section to `plugins.jobscripts`
* Enable warnings by default when scripts do exit 0
* Slightly improved the documentation
Changes from v3 (#1134):
* Added Makefile …
> Job pre and post plugins [v6]

- requirements-travis.txt
- requirements.txt
Fabric 1.10.0 has a dependency issue. This patch changes
the fabric version to the highest available
version right now.
> Fix travis build for python2.6

- .travis.yml
Travis will clone the repo and then fetch the pull-request, regardless
the branch it's coming from. That's why a PR has to contain the correct
parenting. But the build will happen only if the PR is proposed to an
enabled branch. That's what this PR enables.
> enable travis build for 36lts branch

- docs/source/ContributionGuide.rst
Simple "make link" documentation.
trello: https://trello.com/c/LdXWhQ2Z/641-add-documentation-of-make-link-target
> docs: Add "make link" documentation 

- avocado/core/app.py
Python ignores SIGPIPE on startup, because it prefers to check every
write and raise an IOError exception rather than taking the signal.
This patch changes SIGPIPE back to its default action in order to
behave correctly.
Reference: https://trello.com/c/ysKxcHEa
> fix crash on broken pipe

- .travis.yml
Currently we have a travis script to run make check with every
commit on the PR. But the script is hard coded to get the commit
list using the branch master as reference.
This commit uses travis env variables to make the script branch
independent, so we can have the same .travis.yaml file for every
branch we create (LTS branches for instance).
> configure travis to the branch independent

- .travis.yml
The first commit is checked by the main check, don't re-check it with
the per-commit check.
> travis: Run the per-commit check only for ascendant commits

- avocado/core/app.py
Python ignores SIGPIPE on startup, because it prefers to check every
write and raise an IOError exception rather than taking the signal.
This patch changes SIGPIPE back to its default action in order to
behave correctly.
Reviewed-on: https://github.com/avocado-framework/avocado/pull/1164
Reference: https://trello.com/c/ysKxcHEa
> [36lts] fix crash on broken pipe

- avocado/utils/kernel.py
- examples/tests/linuxbuild.py
I Have added two methods in the file in utils/base_utils.py.
These two methods are generic and can be used by the upcoming tests as well. Currently, these methods are required for me to implement libhugetlbfs tests as mentioned in the issue - 'https://github.com/avocado-framework/avocado-misc-tests/issues/11'
> Added base_utils.py which has two generic methods

- avocado/core/loader.py
- selftests/functional/test_basic.py
- selftests/functional/test_gdb.py
- selftests/functional/test_multiplex.py
- selftests/functional/test_output.py
- selftests/functional/test_plugin_jobscripts.py
- selftests/functional/test_replay_basic.py
- selftests/functional/test_streams.py
- selftests/functional/test_sysinfo.py
This patch fixes and improves resolving of the test aliases (paths
relative to `data_dir.get_tests_dir`).
1. It removes the magic `.py` suffix, which prevented non-python files
from being resolved (simple.sh was resolved to $tests/simple.sh.py)
2. It adds the feature to filter the class/method from the test
reference by parsing $test_reference:$class.$method for implicit
resolver. (previously this worked only for absolute path resolver)
Visible changes are:
* `avocado run passtest` => fails (used to work)
* `avocado run passtest.py` => works (did not work)
* `avocado run env_variables.sh` => works (did not work)
* `avocado run passtest.py:PassTest.test` => works (did not work)
Trello: https://trello.com/c/jPpRVdBG/644-remove-the-py-detection-in-loaders
>  avocado.core.loader: Fix the test alias resolver [v1]

- docs/source/ContributionGuide.rst
Simple "make link" documentation.
trello: https://trello.com/c/LdXWhQ2Z/641-add-documentation-of-make-link-target
master: https://github.com/avocado-framework/avocado/pull/1171
> docs: Add "make link" documentation

- avocado/core/html.py
- avocado/core/resources/htmlresult/templates/report.mustache
- avocado/core/runner.py
Currently the sysinfo info on the HTML report only shows the pre-testp hase of sysinfo.  It should really include all three phases.
Reference: https://trello.com/c/sXZQTfta
> HTML report: make sysinfo section aware of pre/post/profile

- avocado/core/html.py
- avocado/core/resources/htmlresult/templates/report.mustache
- avocado/core/runner.py
Currently the sysinfo info on the HTML report only shows the pre-test phase of sysinfo. It should really include all three phases.
Reference: https://trello.com/c/sXZQTfta
> HTML report: make sysinfo section aware of pre/post/profile [36lts]

- avocado/core/runner.py
- selftests/functional/test_basic.py
- selftests/functional/test_job_timeout.py
Currently avocado adds custom handlers of SIGINT and SIGUSR1 in order to
produce traceback and notify about user interaction or timeout. This
could be missleading in case the test uses those signals and potentially
dangerous as some tests assume default behavior.
This patch removes the custom handling of SIGINT and SIGUSR1 and
reports the failure in `job.log`. Additionally it tries to inject the
error message in the test output, if status.logfile available.
In order to keep the useful traceback in case of interruption, this
patch overrides the default SIGTERM handler. The default behavior of
SIGTERM is to die, our custom handler raises SystemExit with info saying
the test was interrupted by sigterm, which should generate traceback and
finish. The runner then changes the result to …
> avocado: Avoid custom handling of SIGINT and SIGUSR [v2]

- selftests/functional/test_basic.py
The result-dir of the
test_basic.RunnerSimpleTest.test_kill_stopped_sleep depends on `sleep`
binary location. This patch uses the `astring.string_to_safe_path`
function to determine the location.
trello: https://trello.com/c/b9iWgZW8/696-bug-regression-in-test-kill-stopped-sleep
> selftests: Fix test_basic..test_kill_stopped_sleep resultdir

- avocado/core/result.py
- avocado/plugins/run.py
- docs/source/GetStartedGuide.rst
- docs/source/Loaders.rst
- docs/source/MultiplexConfig.rst
- docs/source/Plugins.rst
- docs/source/ReferenceGuide.rst
- docs/source/Replay.rst
- docs/source/ResultFormats.rst
- docs/source/RunningTestsRemotely.rst
- docs/source/WritingTests.rst
This PR fixes a feature removed accidentally in 0.34.0, fixes couple of issues in the current documentation and finally brings the serialized-test-ids https://github.com/avocado-framework/avocado/pull/1158 and alias modification https://github.com/avocado-framework/avocado/pull/1159 documentation.
trello: https://trello.com/c/p3D97waT/647-test-ids-logs-ui-and-documentation
v1: https://github.com/avocado-framework/avocado/pull/1186
changes:
v2: Fixed missing `sleeptest` => `sleeptest.py`
v2: Improved the Test References/TestName description in ReferenceGuide
v2: Use `json.tool` instead of `pprint` to humanize the results
> Test ids docs2

- avocado/core/runner.py
- selftests/functional/test_basic.py
- selftests/functional/test_job_timeout.py
Currently avocado adds custom handlers of SIGINT and SIGUSR1 in order to
produce traceback and notify about user interaction or timeout. This
could be missleading in case the test uses those signals and potentially
dangerous as some tests assume default behavior.
This patch removes the custom handling of SIGINT and SIGUSR1 and
reports the failure in `job.log`. Additionally it tries to inject the
error message in the test output, if status.logfile available.
In order to keep the useful traceback in case of interruption, this
patch overrides the default SIGTERM handler. The default behavior of
SIGTERM is to die, our custom handler raises SystemExit with info saying
the test was interrupted by sigterm, which should generate traceback and
finish. The runner then changes the result to …
> [36lts] avocado: Avoid custom handling of SIGINT and SIGUSR

- avocado/core/loader.py
- avocado/core/result.py
- avocado/plugins/run.py
- docs/source/GetStartedGuide.rst
- docs/source/Loaders.rst
- docs/source/MultiplexConfig.rst
- docs/source/Plugins.rst
- docs/source/ReferenceGuide.rst
- docs/source/Replay.rst
- docs/source/ResultFormats.rst
- docs/source/RunningTestsRemotely.rst
- docs/source/WritingTests.rst
- selftests/functional/test_basic.py
- selftests/functional/test_gdb.py
- selftests/functional/test_multiplex.py
- selftests/functional/test_output.py
- selftests/functional/test_plugin_jobscripts.py
- selftests/functional/test_replay_basic.py
- selftests/functional/test_streams.py
- selftests/functional/test_sysinfo.py
Backport the https://github.com/avocado-framework/avocado/pull/1159 and https://github.com/avocado-framework/avocado/pull/1194 to 36lts. The https://github.com/avocado-framework/avocado/pull/1158 is already part of 36lts.
trello: https://trello.com/c/jPpRVdBG/644-remove-the-py-detection-in-loaders
trello: https://trello.com/c/p3D97waT/647-test-ids-logs-ui-and-documentation
The 1159 applied cleanly with few different line numbers, the 1194 applied cleanly without any changes.
> [36lts] Docs and resolver fixes

- examples/tests/linuxbuild.py
Signed-off-by: Wei Jiangang <weijg.fnst@cn.fujitsu.com>
> linuxbuild: fix NameError that 'os' is not defined

- avocado/core/resources/htmlresult/templates/report.mustache
- avocado/core/result.py
- docs/source/GetStartedGuide.rst
- docs/source/Replay.rst
- docs/source/ResultFormats.rst
- docs/source/RunningTestsRemotely.rst
- docs/source/WritingTests.rst
- man/avocado.rst
- selftests/functional/test_interrupt.py
Avocado has until now shown very simplified time information for jobs,
and some could even say unprecise or just plain incorrect.
The fact is that the time displayed in the UI (HumanResult) and also
on the various other supported formats is the sum of the run time of
individual tests.
The problem with that is tha a job may include other actions that can
take time, from little to substancial amounts.  This makes it clear
that a job that say, took 30 seconds to run (although not displayed at
this point), spent only 20 seconds actually running tests.
--
Changes from v1 (#1203):
* Use "Cumulative test time" in HTML report
> Tests time accounting: be more precise about what is being shown [v2]

- avocado/core/resources/htmlresult/templates/report.mustache
- avocado/core/result.py
- docs/source/GetStartedGuide.rst
- docs/source/Replay.rst
- docs/source/ResultFormats.rst
- docs/source/RunningTestsRemotely.rst
- docs/source/WritingTests.rst
- man/avocado.rst
- selftests/functional/test_interrupt.py
Avocado has until now shown very simplified time information for jobs,
and some could even say unprecise or just plain incorrect.
The fact is that the time displayed in the UI (HumanResult) and also
on the various other supported formats is the sum of the run time of
individual tests.
The problem with that is tha a job may include other actions that can
take time, from little to substancial amounts.  This makes it clear
that a job that say, took 30 seconds to run (although not displayed at
this point), spent only 20 seconds actually running tests.
--
Backport of #1207
> [36lts] Tests time accounting: be more precise about what is being shown

- contrib/job-scripts/coreudmp-handling/README
- contrib/job-scripts/coreudmp-handling/post.d/001-restore-core-pattern
- contrib/job-scripts/coreudmp-handling/post.d/002-link-core-to-tests
- contrib/job-scripts/coreudmp-handling/pre.d/001-set-core-pattern
This adds a "contrib" level set of scripts that will put coredump
files in the job result directory.  Additionally, the system core
pattern, changed to achieve that result will be restore after the job
finishes running tests.
Finally, coredump files are attempted to be associated with individual
tests so users can quickly deal with the coredumps of possibly failed
tests.
--
Changes from v2 (#1211):
* Fix typo (s/you/your)
* Fix old directory name (s/crash-dumps/coredumps)
* Add instructions on how to set the scripts permanently 
Changes from v1 (#1210):
* Added licenses and descriptions
* Uses prlimit to set core file size limit automatically
* Uses timestamps of test and core files to correlate them
> Job scripts: add core dump handling set of scripts [v3]

- avocado/core/loader.py
The path of the module to be imported/loaded is reflected later at run
time.  Non-absolute paths can refer to the wrong locations if the
current working directory changes.  Absolute paths are always
absolutes, so, let's use them.
> avocado/core/loader.py: always use absolute module path at import time

- docs/source/GetStartedGuide.rst
Avocado now has both the regular and LTS package repositories. Let's
give some background on them, and let users know that they can choose
between the two.
> docs: add information on LTS repositories

- Makefile
- docs/source/ContributionGuide.rst
Support `make requirements-plugins` to walk all sub-directories
like the same way `make link` works.
v1: https://github.com/avocado-framework/avocado/pull/1205
Changes:
v2: Depend on "requirements" to install main avocado requirements first
v2: Add documentation
> Makefile: implement make-requirements-plugins

- avocado/core/job.py
Currently avocado executes the job-post hook after disabling the test
logging, which, as a matter of fact, is also the job logging. That means
the output produced by job-post plugins is not stored. This patch moves
disabling of the test log into the finally part after the job post hooks
were executed.
Note: I'm not talking about the "app" error messages, but about the
stdout/stderr and avocado.test outputs.
> avocado.core.job: Stop logging after the jobpost hook

- Makefile
While testing `make requirements*` on a fresh machine, I found that
we rely on pip itself, which may not be available.  Its bootstrap
process is pretty simple, atomic and well documented, so it seems
like a good idea to add it as a convenience.
> Makefile: boostrap pip installation automatically

- avocado/core/data_dir.py
Up until now, if users are running Avocado out of the source trees,
the in tree example test directories are favored.  This suits most
development use cases, but it fails to respect regular users settings
when they're running out of the source checkouts.
This changes the respected order, only using the in source tree
examples directory if a different configuration is not set.  Then the
usual system wide and user default directories are used.
Reference: https://trello.com/c/VKWgvm2E
--
* Drop now unused `_get_ro_dir()`
> Test directories: favor explicitly configured test directories [v2]

- avocado/utils/build.py
v2:
- Set `-j` defaults on MAKEFLAGS env variable.
v1: #1234 
Parallelism is usually a good thing when it comes to build source codes.
This patch adds the -j option to make utils using ncpus+1 when -j is not
provided by the user.
Reference: https://trello.com/c/H4e7SuOC
> add -j option to make

- avocado/core/test.py
The `;` character is problematic for some makefiles, let's replace it
with `_` the same way we did for `:`. The result should still be
readable enough by human, it's guaranteed to be still unique which
concludes all requirements for machines regarding workdir.
Issue: https://github.com/avocado-framework/avocado-misc-tests/issues/36
Reference: https://github.com/avocado-framework/avocado/pull/756 (similar issue)
> avocado.core.test: Replace `;` in workdir too

- avocado/core/test.py
- avocado/utils/kernel.py
- examples/tests/linuxbuild.py
v4:
- Make `cache_dirs` available in `Test()` API.
- Use `cache_dirs` from `Test()` API in the linuxbuild example test.
v3: #1248 
- data_dirs as a list of paths.
- add data_dirs in linuxbuild example test.
v2: #1242 
- Introduce `data_dir` option to `KernelBuild()` so we can take advantage of the cache mechanism from the asset fetcher.
v1: #1233 
Using asset fetcher for KernelBuild download() so we can take
advantage of the cache mechanism.
Reference: https://trello.com/c/d6qeRbJD
> Use asset fetcher for KernelBuild download() [v4]

- avocado/core/runner.py
- selftests/functional/test_basic.py
- selftests/functional/test_job_timeout.py
This PR contains the https://github.com/avocado-framework/avocado/pull/1243 and it adds two new commits to unify runner failures handling including propagating of the TestStatus queue error.
Trello: https://trello.com/c/E6ibibBb/716-avocado-runner-possibly-leaves-test-processes-behind
Trello: https://trello.com/c/BdC56G6X/542-bug-avocado-can-t-handle-exceptions-raised-while-reading-the-test-queue
> avocado: Improve TestStatus handling

- avocado/core/test.py
- selftests/unit/test_loader.py
With the d6abdcd `Test` methods changed
but for SimpleTest the wrong method was chosed and only the test
execution is performed now, the post-process class is completelly
ignored. This changes the method to the correct one and adjusts
ExternalRunner to not run this postprocess.
This fixes issue found by @clebergnu while looking at issue https://github.com/avocado-framework/avocado/issues/1244
v1: https://github.com/avocado-framework/avocado/pull/1245#discussion_r66211275
```yaml
v2: Use __file__ for tmpdir prefix
```
> avocado.core.test: Fix SimpleTest [v2]

- avocado/utils/data_structures.py
- selftests/unit/test_data_structures.py
This patch changes the error message on ZeroDivisionError to not split
by `.split()` method to allow loading the matrix by simple split.
Additionally this changes the zip method to izip in for loop.
> avocado.utils.data_structures: Adjust compare_matrices

- avocado/core/app.py
This variable is a leftover from the days the preceded the plugin system
overhaul.  It serves no purpose now, so, let's remove it.
> avocado/core/app.py: remove useless initialized variable

- avocado/plugins/tap.py
- docs/source/ResultFormats.rst
- selftests/functional/test_output.py
- setup.py
This patch adds simple TAP (v12) results plugin. It supports stdout/file
output and is fully stream-lined (uses 1 line buffering to file).
v1: https://github.com/avocado-framework/avocado/pull/1224
v2: https://github.com/avocado-framework/avocado/pull/1232
v3: https://github.com/avocado-framework/avocado/pull/1249
v4: https://github.com/avocado-framework/avocado/pull/1258
Changes:
```
v2: Add test's stdout
v2: Put test's comments before the test (to follow TAP standard)
v2: Add unittest by Cleber
v2: Strengthen and modify the unittest (next commit)
v3: Squash the unittest changes and use in-unit-test file again
as I was not able to make travis work.
v4: Added TAP documentation
v5: Added `::` in documentation to align block properly
```
> avocado.plugins: Add TAP output plugin [v5]

- avocado/utils/lv_utils.py
- selftests/functional/test_lv_utils.py
This utils library allows manipulating LVM. It'll be used by the `Lvsetup` test.
v1: https://github.com/avocado-framework/avocado/pull/1237
v2: https://github.com/avocado-framework/avocado/pull/1254
v3: https://github.com/avocado-framework/avocado/pull/1257
Changes:
```yaml
v2: Removing shell=True, adding sudo=True in necessary places
v2: Removing unnecessary Logging of result
v2: Adding necessary comments
v2: Adding Custom Exception Class
v3: Added new commit with fixes and selftest
v4: Squash the commit with fixes
```
> avocado.utils.lv_utils: Add LVM utility [v4]

- avocado/utils/process.py
The current implementation of pid_exists() is such that, if any error
condition is obtained from sending a signal to a given process, than
it means that it doesn't exist.
But that is not true, and the same OSError exception raised when the
process doesn't exist, can be raised when there's no permission to
send a signal to a process (such as someone else's process).  So,
let's be very specific and check for ESRCH, which means "no such
process".
> avocado/utils/process.py: avoid false positives on pid_exists()

- Makefile
- docs/source/MaintenanceGuide.rst
Avocado needs a bit of custom massaging to be able to properly live
under "avocado-framework" on PyPI.  This adds a target that will
make the upload of new releases easier.
> Makefile: add rule for creating package files for PyPI

- avocado/core/multiplexer.py
- selftests/unit/test_multiplexer.py
When unhashable argument is passed to the `params.get`, it crashes while
trying to obtain value from cache. This patch fallbacks to new query on
such exception.
Trello: https://trello.com/c/hjipQN0L/729-bug-multiplexer-does-not-accept-unhashable-objects-as-default
Related to: https://github.com/avocado-framework/avocado-misc-tests/pull/60
> avocado.core.multiplexer: Allow unhashable arguments

- avocado/utils/lv_utils.py
Hello @apahim, @clebergnu, there are two issues preventing `vg_ramdisk_cleanup` to work properly. Would you please review this preferably? It leaves uncleaned partitions/mounts after cleanup...
> avocado.utils.lv_utils: Two bugfixes

- avocado/utils/process.py
This is a backport to LTS.  It's relevant because Avocado-VT users with the Job Lock plugin (enabled by default) can have false positives in the detection of stale lock files.
--
The current implementation of pid_exists() is such that, if any error
condition is obtained from sending a signal to a given process, than
it means that it doesn't exist.
But that is not true, and the same OSError exception raised when the
process doesn't exist, can be raised when there's no permission to
send a signal to a process (such as someone else's process).  So,
let's be very specific and check for ESRCH, which means "no such
process".
> [LTS BUGFIX] avocado/utils/process.py: avoid false positives on pid_exists()

- avocado/core/test.py
- avocado/plugins/run.py
- avocado/utils/asset.py
- avocado/utils/data_structures.py
- docs/source/WritingTests.rst
- selftests/functional/test_job_timeout.py
- selftests/unit/test_utils_asset.py
v4:
- Fix exception `time_to_seconds()` exception message.
v3: #1277 
- Use specific class in `except` when calling `time_to_seconds()` in `run.py`.
- Improved unittest.
- Improved docs.
- Don't hard code behavior for `0` and negative values in `expire`.
v2: #1275 
- Move `time_to_seconds()` to `data_structures`.
- Accept zero and negative values.
- Unittest.
v1: #1266 
Now users can invalidate (download again) a local copy of the asset file if
it has more than a given time since created.
Reference: https://trello.com/c/JLk01wOl
>  Add expire time for asset fetcher [v4]

- avocado/plugins/run.py
The --job-timeout now accepts values <= zero and treats them as no
timeout, let's reflect that in help msg.
> avocado.plugins.run: Fix job-timeout documentation

- avocado/utils/partition.py
- selftests/unit/test_utils_partition.py
This utility comes from `autotest` and will be used by `parallel_dd` test.
v1: https://github.com/avocado-framework/avocado/pull/1240
v2: https://github.com/avocado-framework/avocado/pull/1251
Changes:
```yaml
v2: Added commit which fixes autotest's issues and brings selftest
v3: Fixed `tmpfile` `prefix` in unittest
```
> avocado.utils: Add "partition" utility [v3]

- avocado/core/app.py
v3:
- Move the  'paginator off' code to the exceptions in `app` so we cover any case instead of argparse error only.
v2: #1271 
- Close `STD_OUTPUT` in app `init()` instead of just turning paginator off (as in the previous version).
- Turn the paginator off on argparse error.
v1: #1268 
- Disables the paginator on argparse error
> Close STD_OUTPUT on app exception [v3]

- avocado/core/remote/runner.py
- avocado/core/remoter.py
- avocado/plugins/envkeep.py
- docs/source/RunningTestsRemotely.rst
- selftests/unit/test_remote.py
- selftests/unit/test_vm.py
- setup.py
v3:
- Remove try/except from plugin option parser.
- Remove the meaningless code in plugin `run()`.
- Rebase.
v2: #1272 
- Style changes.
v1: #1264 
Add options --env-keep to run command so users can make
available in remote executions of Avocado some environment
variables that are available locally.
Reference: https://trello.com/c/Ddcly0oG
> avocado.core.remoter keep environment variables [v3]

- contrib/testsuites/run-kvm-unit-test.sh
This script runs kvm-unit-test tests as individual tests in avocado.
I'll update the `avocado-vt` documentation to use this script to run kvm-unit-test. When we implement `JobAPI` we can turn this script to job instead.
v1: https://github.com/avocado-framework/avocado/pull/1280
Changes:
```yaml
v2: Remove the `tests/` prefix from test names (by running the tests from "tests" directory)
```
> contrib: Add run-kvm-unit-test script [v2]

- docs/source/MultiplexConfig.rst
We have a warning about the mandatory space when using
the `!include :` construct.  Since the warning has an exclamation mark (for
punctuation purposes) it can make it a bit confusing since the
example given begins with an exclamation mark (for syntactic
purposes).
Also, in reStructured Text markup, double underscores do not add
emphasis, as it seems to be the original intention.
> Multiplex doc: try to be clearer about mandatory space and colon

- avocado/core/tree.py
- selftests/unit/test_tree.py
Commit 19cb82c removed the `get_ascii()` method and added the utility
function `tree_view()`.  But there is a leftover using the old method.
Let's replace them.
> avocado/core/tree.py: replace get_ascii() with tree_view()

- avocado/core/replay.py
- avocado/plugins/replay.py
- docs/source/Replay.rst
- selftests/functional/test_replay_basic.py
v2:
- Added help message.
- Added documentation.
v1: #1305 
Now users can execute 'avocado run --replay latest' to have the latest
job replayed. No need to remember the job id.
Reference: https://trello.com/c/C0YCTT6d
> Add 'latest' option to replay feature [v2]

- examples/testplans/release.json
Support for spell checking had been added to avocado recently, let's
make that mandatory step of manual testplan.
v1: https://github.com/avocado-framework/avocado/pull/1306
Changes:
v2: indentation fixes
> examples: Add `make spell` to testplan

- docs/source/0_32_0.rst
- docs/source/0_33_0.rst
- docs/source/0_34_0.rst
- docs/source/35_0.rst
- docs/source/36_0.rst
- docs/source/37_0.rst
- docs/source/38_0.rst
- docs/source/index.rst
v2:
- Release notes as last item in index.
- Remove sprint theme from release notes file and just mention it as a footnote link.
v1: #1314 
Including the release notes in our docs.
> [RFC] Release Notes in docs [V2]

- avocado/core/runner.py
- avocado/plugins/run.py
- docs/source/GetStartedGuide.rst
- selftests/functional/test_basic.py
v2:
- Access `job.args` properly.
- Add `AVOCADO_JOB_INTERRUPTED` to exit code.
- Use the same wording for `--help`.
v1: #1313 
With this option, a test that ends with a 'bad' status will make
the job to be interrupted.
> Add --failfast option to avocado run command [v2]

- avocado/core/app.py
- avocado/core/output.py
- selftests/functional/test_output.py
This reverts the previously introduced change in SIGPIPE handling, and adds a more specific handling of the IOError (due to EPIPE) that caused Avocado to crash.
--
* Deal with the different shell used in travis
> Deal with IOError due to (EPIPE) [v2]

- avocado/core/app.py
- avocado/core/output.py
- selftests/functional/test_output.py
This reverts the previously introduced change in SIGPIPE handling, and adds a more specific handling of the IOError (due to EPIPE) that caused Avocado to crash.
> [LTS] Deal with IOError due to EPIPE

- avocado/core/multiplexer.py
- avocado/core/runner.py
The runner uses multiplexer to modify the test-template, which is not
really clean. It should only as for variants and the runner itself
should be responsible for adjusting the template which is exactly what
this patch does.
> avocado.core: Cleanup runner->multiplexer API

- avocado/core/app.py
- avocado/core/job.py
- avocado/core/parser.py
- avocado/core/result.py
- avocado/plugins/json.py
- avocado/plugins/tap.py
- avocado/plugins/xunit.py
- selftests/functional/test_output.py
- selftests/unit/test_parser.py
This has the goal of moving the logic of incompatible options out of the job layer. This way, plugins can try to acquire the rights to standard output, and if more than one do, the application is aborted.
This is one piece required to make the job completely unaware of result plugins, which is coming next.
--
Changes from v2 (#1324)
* Use `argparse.ArgumentError` as exception
* Rely on the ArgumentParser default `error` method to exit the application on argument errors
Changes from v1 (#1315):
* Store the name of the option that claimed the stdout in the parsed args itself (a `Namespace`)
* Remove unused (leftover from development) exception `StdoutAlreadyClaimedError`
> Introduce FileOrStdoutAction [v3]

- avocado/core/multiplexer.py
- avocado/core/test.py
- docs/source/WritingTests.rst
- selftests/unit/test_multiplexer.py
- selftests/unit/test_test.py
When the support for Test IDs was introduced, support for string based
test names and tags was kept in deprecated mode, scheduled to be
removed on an upcoming release.
This planned upcoming release for removal has already passed, so let's
remove them now.
--
Changes from v1 (#1303):
* Updated docs
> avocado/core/test.py: remove support for string test names and tags [v2]

- docs/source/index.rst
- requirements-selftests.txt
- requirements-travis.txt
This reverts commit 00e9aa461983d5f10c9bd42fa8874aa73b40fc5d.
python-sphinx 1.3 is not available for fedora 23 so the rpm build is doomed to fail with this patch. Let's revert this change and reconsider it when required python-sphinx version is available.
> Revert "Improve documentation index"

- avocado/core/remote/runner.py
- avocado/core/runner.py
- avocado/plugins/docker.py
- docs/source/RunningTestsRemotely.rst
- selftests/unit/test_vm.py
- setup.py
Similarly to --remote or --vm plugins this plugin allows one to run the
job inside a docker container by specifying the docker image. It
executes a new container, then attaches it and uses it similarly as
--remote plugin uses remote machine.
To check it out you can use "ldoktor/fedora-avocado" image which is
available on (the default) hub.docker.com
Trello: https://trello.com/c/FOxIriF3/616-support-running-tests-in-a-docker-container-based-on-the-remote-plugin
v1: https://github.com/avocado-framework/avocado/pull/1310
v2: https://github.com/avocado-framework/avocado/pull/1319
v3: https://github.com/avocado-framework/avocado/pull/1326
Changes:
```yaml
v2: Added --docker-cmd argument
v2: Removed the --docker-hypervisor-uri (superseded by --docker-cmd)
v2: New commit to handle urls without …
```
> avocado.plugins: Add plugin to run job in docker container [v4]

- avocado/core/output.py
Fedora 24 using screen has TERM=screen.xterm-256color. This patch adds
that terminal option in the list of valid options to be colorized.
> Include Fedora 24 screen terminal

- avocado/core/job.py
When the tests are not going to be copied, there's no need to try to
discover them locally.
This patch fakes the test_suite when remote-no-copy is used.
Reference: https://trello.com/c/MRgIcW5T
> Don't discover tests when using --remote-no-copy

- avocado/utils/asset.py
- avocado/utils/filelock.py
- selftests/unit/test_utils_asset.py
- selftests/unit/test_utils_filelock.py
- spell.ignore
v5:
- Avoid race condition in the filelocker.
- Return filelocker instance to allow the syntax `with FileLock(filename) as f:`.
- Improve filelocker docstring.
- Use `O_SYNC` to avoid race conditions in file creation/write.
v4: #1325 
- `FileLock` as a context manager.
- Proper exception message when no timeout is set.
- Use `utils.process.pid_exists()` instead of redundant code.
- Improve tests.
- Minor style improvements.
v3: #1309 
- Make lock timeout configurable and set it to `1s` in asset fetcher.
v2: #1304 
-  Introduce the file locker utility.
-  Asset fetcher improvements:
- Use the avocado.utils.filelock to avoid race conditions:
- Drop EnviromentError exceptions on cache miss.
- Clean excessive debug messages.
- Unify hashfile for any algorithm.
- Improve hashfile control.
v1: …
> Asset improvements v5

- selftests/checkall
This allows `AVOCADO_SELF_CHECK=1 ./selftests/checkall` to run
inside virtualenv environemnts.
> Use python from env instead of absolute pyton path

- avocado/plugins/journal.py
We found some users of this plugin, and we're unsure they actually use
this as intended.  Even if they don't use it as intended, it may be a
good thing, *but* we should make it clear what was the original goal
of this feature.
> avocado/plugins/journal.py: make the goal of this plugin more clear

- avocado/utils/asset.py
- avocado/utils/kernel.py
And the docstring of the asset library itself.
--
Changes from v1 (#1340):
* Set `expire=None`
> avocado/utils/kernel.py: fix the use of the asset library [v2]

- avocado/utils/asset.py
- avocado/utils/kernel.py
The `kernel.py` fix breaks the `data_dirs` feature. Let's revert that commit and instead of fixing the `kernel` utility, make the `expire` argument optional while keeping the default behavior. This should suit all existing code depending on `asset` to work without the need to adjust it.
> Revert `kernel.py` commit and use different approach to fix the issue

- avocado/core/test.py
- avocado/utils/asset.py
- selftests/unit/test_utils_asset.py
Currently asset fetcher returns path to the asset file or None
when it fails to fetch it. This patch makes it o raise an exception
in such cases.
Reference: https://trello.com/c/CXhCbFAr
v1: https://github.com/avocado-framework/avocado/pull/1348
Changes:
v2: Added docstrings
> avocado.utils.asset raise exception when not able to fetch asset [v2]

- avocado.spec
- requirements.txt
The aexpect module is used by the Docker plugin.  Since we do not
package those separately, let's add it as a global Avocado dependency.
> aexpect: add it to source and package installation requirements

- avocado/utils/process.py
This patch addresses one of the possible issues described in https://github.com/avocado-framework/avocado/issues/1343 (https://github.com/scylladb/scylla-cluster-tests/issues/129). While working on it I spotted potential issue where process terminated by avocado might have reported clean results. Additionally there were few fixes more-less related to the changes.
issue: https://github.com/avocado-framework/avocado/issues/1343
trello: https://trello.com/c/0xtzz0vh/730-add-get-pid-to-utils-process
trello: https://trello.com/c/c7csRBY2/739-log-the-exit-status-and-execution-time-when-process-finishes
v1: https://github.com/avocado-framework/avocado/pull/1347
Changes
```yaml
v2: Fix typo in get_pid docstring
```
>  avocado.utils.process: Avoid busy loop and various fixes [v2]

- avocado/core/runner.py
- avocado/plugins/replay.py
- avocado/plugins/run.py
- docs/source/GetStartedGuide.rst
- docs/source/Replay.rst
- selftests/functional/test_basic.py
- selftests/functional/test_replay_failfast.py
v2:
- Turn ``--failfast`` argument mandatory (on|off).
v1: #1345 
Now replay jobs will respect the original job failfast option, when used. Also,
it is possible to disable failfast option on replay jobs with `--failfast off`.
> Add failfast support for replay [v2]

- docs/source/DebuggingWithGDB.rst
- examples/wrappers/rr.sh
This example wrapper script runs binaries inside rr (record), which
saves the execution environment, allowing to deterministically debug
possible failures later.
The usage instructions to run tests with this wrapper are no different
than other wrappers.  The effect of the wrapper, though, deserves notice:
it creates an "rr" directory inside the test results, which rr uses
to save its data files.
Replays should be executed like this:
$ rr replay $JOB-RESULTS/test-results/$TEST/data/rr/$BINARY_NUMBER
Where $BINARY_NUMBER is the "Nth" execution of "binary" by your
test.
--
Changes from v1 (#1338):
* Added references to the rr web site
* Added documentation
* Changed output directory to `$AVOCADO_TEST_OUTPUTDIR/rr`
* Added `-n` so that it works on …
> Wrappers: add support for rr [v2]

- docs/source/conf.py
Sphinx actually use the contents of the `release` variable as the
user visible version number, so release here is very different from,
say, a RPM release number.
Let's set the release number to the very same version number.
> docs: fix the version (release) number used by sphinx

- avocado/core/version.py
- setup.py
This changes how Avocado queries for its version numbers, moving the authoritative setting to the setup script.  This avoid loading a lot of modules from `setup.py`, and even fixes crashes we'd have on systems without most Avocado requirements.
Also, two additional improvements to our `setup.py`.
--
Changes from v1 (#1356):
* Use version `unknown.unknown` instead of `0.0` when distribution is not found with `pkg_resources`
> Avocado version and setup improvements [v2]

- avocado/plugins/xunit.py
The overhead of prettyxml is quite minimal, while the readability is
huge. Let's enable prettyxml by default to be able to read the results
manually.
> avocado.plugins.xml: Use pretty xml to make output human readable

- avocado/plugins/jsonresult.py
- docs/source/ResultFormats.rst
In the same fashion the default XUnit output has been made pretty,
let's not allow JSON to envy it.
> JSON Result: output the result in pretty format

- contrib/job-scripts/coredump-handling/pre.d/001-set-core-pattern
The job-scripts are system-wide and always enabled when installed. Let's
skip the `coredump` one in case it's not executed as root to avoid big
fat warnings in every execution. Instead this patch adds a `stderr`
message informing user that coredump support was disabled because it's
not executed as root.
There is no need to modify the other coredump-related scripts as they
depend on files generated by this first script.
> contrib: Disable coredump support when not running as root

- avocado/core/output.py
Currently we keep the long lines and let people to scroll left+right to
see the content. This patch changes the paginator to wrap the lines (by
default, it can be tweaked by environment variables).
For my workflows this works better as you see the full output on one
screen and you can easily copy&paste it without the need to scroll left
and right.
trello: https://trello.com/c/haciTU69/663-avocado-list-using-paginator-even-when-not-listing-results
> avocado.core.output: Wrap the lines in paginator

- avocado/utils/cpu.py
Signed-off-by: Praveen K Pandey praveen@linux.vnet.ibm.com
v1: #1370 
v2: https://github.com/avocado-framework/avocado/pull/1373
```
v2: style-fix for pep8
v2: added a function that return list of on -line cpu number
v3: Improve the cpu_online_list docstring
```
> add a function that returns the online cpu indexes [3]

- avocado/core/job.py
- avocado/core/replay.py
- avocado/plugins/diff.py
- docs/source/Diff.rst
- docs/source/index.rst
- selftests/functional/test_plugin_diff.py
- setup.py
v5:
- Logging improvements.
- Remove '\n' after the sysinfo headers.
v4: #1374 
- Improve help.
- Simplify section headers.
- Massive pylint compliance fixes.
- Improve argument parsing for `--diff-filter`
v3: #1371 
- Highlight section headers with `rst` markers.
- Use `nooption` instead of `-option` for `--diff-filter`.
- Introduce `--create-reports` mode, where we suppress the embedded diff tool and create tmp files with the content to be used in external diff tools. 
- Fix issue when using job results directories to identify jobs.
- Encoding improvements.
- Resources optimizations by not creating intermediary lists with all the content.
- Basic functional tests.
v2: #1369 
- Use the paginator for the diff.
- Allow an optional destination file parameter to be passed with `--html`.
- …
> Avocado Job Diff [V5]

- Makefile
- avocado/core/html.py
- avocado/core/job.py
This work rewrites a part of the HTML report generation code, and then moves it out of the `avocado.core`, removing knowledge and dependencies about the HTML code.
Then after that, it makes the HTML result plugin a real (Python-level) plugin, living in a separate module namespace.
This is the first part of the original (v2) of the PR.
--
Changes from v2 (#1375):
* Fixed a reference to `results_dit` that was left in the debugging output 
Changes from v1 (#1372):
* Fixed the module namespace used to look for resources
> HTML Result: make it a real plugin [v3 - part1]

- avocado.spec
The TAP test requires the perl-Test-Harness package, let's add it to the
build dependencies. It fails silently, but there is a message just when
the selftests are executed:
+ selftests/run
Can't locate TAP/Parser.pm in @INC (you may need to install the
TAP::Parser module) (@INC contains: /usr/local/lib64/perl5
/usr/local/share/perl5 /usr/lib64/perl5/vendor_perl
/usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at
-e line 1.
BEGIN failed--compilation aborted at -e line 1.
> avocado.spec: Add build dependency for TAP parser

- avocado/core/multiplexer.py
- avocado/core/runner.py
Fixes #1380 
This reverts commit b6cbe7340ae16543665603a8bab8aa49d68bf9e2.
> Revert "avocado.core: Cleanup runner->multiplexer API"

- scripts/avocado-run-testplan
Usually we want to include all the commits of related projects to the
report. Let's add a convenient way to list all siblings HEAD shas.
v1: https://github.com/avocado-framework/avocado/pull/1387
Changes:
```yaml
v2: Use `git` command rather than `git` python library, which is not in the requirements
```
> scripts.avocado-run-testplan: Report git commits [v2]

- examples/testplans/release.json
The aexpect is required by avocado RPMs, but it's not available in
standard distribution. Let's just list the options to get it.
> examples.testplans: Mention aexpect in the RPM install step

- Makefile
- selftests/functional/test_utils.py
We used a functional test during the development of the lockfile module, but didn't include because really useful tests would take too long to run.
This adds a `Makefile` target for longer tests, which include this one. 
--
Changes from v2 ( #1397):
* Added exception information to the failure message
Changes from v1 ( #1378):
* Changed test tunables to more agressive behavior: 1000 players, 100 times smaller timeouts
* Removed `as lock` from `with FileLock` as it was not being used
> Add LockFile (avocado.utils.lockfile) test [v3]

- avocado/plugins/multiplex.py
The shortcut `-s` used for `--system-wide` clashes with `--silent|-s`
from the main apps arguments, disabling the output. This is the argparse
limitation so let's just remove the shortcut and let users use the full
argument instead.
v1: https://github.com/avocado-framework/avocado/pull/1401
Changes:
```
v2: Remove the short `-sw` and keep only the full `--system-wide` argument
```
> avocado.plugins.multiplex: Change the `system-wide` shortcut

- avocado/core/html.py
- avocado/core/remote/runner.py
A user reported a crash in html plugin in sysinfo reporting when running as root due to UnicodeDecodeError. This series fixes the remote to avoid running with broken plugins and the second patch skips files which it fails to read and replaces the content with a note instead.
This series is only a workaround, I'll investigate and try to find a better solution. So far I was only able to reproduce the same with non-utf-8 encoding (which is known limitation of avocado as python2 does not provide much opportunity to get the system encoding).
__This needs to be backported to 36.3__
> avocado: Remote and html bugfixes

- avocado/core/html.py
- avocado/core/resources/htmlresult/templates/report.mustache
The sysinfo collection can sometimes fail. Let's log a link along with
reason instead of an empty line.
> avocado.core.html: Show link to file which failed to processed

- avocado/core/sysinfo.py
I noticed during a `make check` that my system was collecting the list
of installed packages.  Initially, I thought it was some explicit
check performed by a sysinfo related test, but it turned out that,
whenever avocado is run with the `sysinfo` command, it forces the
package collection.
That behavior is wrong, because it disregards the configuration key
`installed_packages` under `sysinfo.collect` that defaults to False.
If users intend to collect installed packages, than they should change
the appropriate configuration key.
> Sysinfo: do not force package collection

- avocado/utils/lv_utils.py
lvcreate command warns about filesystem signature detected, on
RedHat. Needs a parameter '-y' to continue.
> lv_utils lvcreate fixup.

- docs/source/ContributionGuide.rst
https://github.com/avocado-framework/avocado-misc-tests is frozen.
We created a new community maintained repository in:
https://github.com/avocado-framework-tests/avocado-misc-tests
Let's advertise it in our docs.
> Add community maintained repositories to our docs

- avocado/core/html.py
- avocado/core/remote/runner.py
- avocado/core/resources/htmlresult/templates/report.mustache
A user reported a crash in html plugin in sysinfo reporting when running as root due to UnicodeDecodeError. This series fixes the remote to avoid running with broken plugins and the second patch skips files which it fails to read and replaces the content with a note instead.
This series is only a workaround, I'll investigate and try to find a better solution. So far I was only able to reproduce the same with non-utf-8 encoding (which is known limitation of avocado as python2 does not provide much opportunity to get the system encoding). The last patch improves the html output in case of failure.
master: https://github.com/avocado-framework/avocado/pull/1416
master: https://github.com/avocado-framework/avocado/pull/1418
> [backport] avocado: Remote and html bugfixes

- avocado/utils/partition.py
- selftests/unit/test_utils_partition.py
After spending a couple of time looking at this test, I noticed that it could use a couple of improvements.  Among them is the use of our own `find_command` utility function instead of running `which` (kind of shell approach) and the use of more specific checks for skipping the partition related tests.
> avocado/utils/partition.py: test related improvements

- avocado/core/tree.py
- docs/source/MultiplexConfig.rst
- examples/mux-selftest-advanced.yaml
- selftests/unit/test_tree.py
The PyYAML by default replaces any value with object. This could be
confusing as:
```
on:
true: true
```
becomes:
```
/True/True:True
```
This patch modifies the constructor so only values and tags are
converted.
Trello: https://trello.com/c/BCC1Tg28/813-multiplexer-disable-automatic-conversion-for-everything-but-values
v1: https://github.com/avocado-framework/avocado/pull/1409#discussion_r76632932
Changes:
```yaml
v2: Added documentation
```
> avocado.core.tree: Disable automatic conversion for node names [v2]

- Makefile
- contrib/packages/debian/Makefile
- contrib/packages/debian/README
- selftests/unit/test_utils_partition.py
This is a small collection of Makefile related cleanups and improvements.
--
Changes from v1 (#1430):
* Added missing `contrib/packaging/debian/Makefile` file
* Added a Debian package contrib README file
* Changed the name of the target from `show` to `variables`
* Removed mention of COPR in the Makefile embedded documentaiton
* Added option that controls mock (RPM build related) config
* Added unittest fix for breakage that usually manifests itself in the mock build environment
* Limit attempts to run clean/link to directories containing Makefiles
> Makefile improvements [v2]

- avocado/core/data_dir.py
- avocado/core/settings.py
- avocado/core/sysinfo.py
- avocado/plugins/diff.py
- avocado/plugins/gdb.py
- avocado/plugins/jobscripts.py
- avocado/plugins/replay.py
- selftests/unit/test_settings.py
It's common to use the tilde notation (`~/foo`) to refer to locations
inside the user directory.  Let's introduce a new settings key type,
called `path`, that will automatically expand the tilde notation
if one is found.
--
Changes from v3 (#1428):
* Use `os.path.expanduser` in unittest instead of `os.environ.get('HOME', ...)` approach
Changes from v2 (#1400):
* Added missing places where key type "path" could/should be used, including replay, diff and gdb plugins.
Changes from v1 (#1377):
* Added `path` as an argument to `key_type`
* Added unittest for paths used in `str` types of key
* General docstring improvements 
* Switched key types from `str` to `path` on appropriate sections
> avocado/core/settings.py: allow settings to use the home dir notation [v4]

- setup.py
`VIRTUAL_ENV` variable might not be always present. That's the
case for _ReadTheDocs_. On the other hand, `sys.real_prefix` seems to
be a more reliable way to detect we are under a _virtualenv_.
Reference: https://trello.com/c/PRTvrTOH
You can check the result here: http://apahim-avocado.readthedocs.io/en/fix_rtd_version/
> setup.py: fix the virtualenv detection

- avocado/core/virt.py
- docs/source/RunningTestsRemotely.rst
v3:
- Rename from `_get_ip()` to `_get_ip_from_libvirt_agent()`
- Move the `querytype` definition to the `_get_ip_from_libvirt_agent()`
- Filter out loopback devices based on their MAC (`00:00:00:00:00:00`)
- Return IP only if it's IPv4.
- Include a libvirt return example in `_get_ip_from_libvirt_agent()` docstring.
v2: #1440
- Use only AGENT query type since LEASE type can still be unsafe.
- Docs update.
v1: #1438 
- Migrate the probe method to use libvirt's domifaddr method, using both LEASE and AGENT query types.
- Introduce a 30s timeout to wait for the IP information.
> avocado.core.virt change ip probe method [v3]

- avocado/core/sysinfo.py
v2:
- Fix `log.debug()` notation.
- Move empty initialization to `else` clauses.
- Remove `Profilers declared` log message.
v1: #1435 
- Currently we fail silently when sysinfo configuration files
are not present. This patch adds a log.debug message so the user
will have a chance to understand why sysinfo is not being
collected.
> avocado.core.sysinfo log when sysinfo files are not present [v2]

- avocado/core/sysinfo.py
- etc/avocado/avocado.conf
This commit allows setting custom LANG for sysinfo collection to
simplify `avocado diff` comparison between different machines. One can
disable this by setting no/empty value.
Trello: https://trello.com/c/3uE5GTq9/800-use-lc-all-c-for-sysinfo-gathering-by-default
> avocado.core.sysinfo: Force LANG for sysinfo collection

- Makefile
- examples/plugins/job-pre-post/mail/avocado_job_mail.py
- examples/plugins/job-pre-post/sleep/avocado_job_sleep.py
- optional_plugins/README.rst
This adds support for optional plugins dir and related Makefile targets.  The first candidate for this `optional_plugins` dir is the HTML result plugin, but I decided to send this separately so that it can be more easily reviewed and tested.
To test it, I suggest to copy `examples/plugins/job-pre-post/sleep` to the `optional_plugins` dir and run `make link`.  After that, running any job should have the plugin activated.
To clean up, run `make clean` (and then remove the copied `sleep` dir).
> Plugins: add support for optional plugins dir and related Makefile targets

- avocado/core/sysinfo.py
- etc/avocado/avocado.conf
This commit allows setting custom LC_ALL for sysinfo collection to
simplify `avocado diff` comparison between different machines. One can
disable this by setting no/empty value.
v1: https://github.com/avocado-framework/avocado/pull/1446
Trello: https://trello.com/c/3uE5GTq9/800-use-lc-all-c-for-sysinfo-gathering-by-default
Changes:
```
v2: Use LC_ALL instead of LANG
```
> avocado.core.sysinfo: Force LC_ALL for sysinfo collection [v2]

- avocado/plugins/jsonresult.py
- avocado/plugins/plugins.py
- avocado/plugins/xunit.py
- optional_plugins/html/avocado_result_html/__init__.py
The "Result" plugin interface was defined a while ago, and we now have
three implementations (JSON, XUnit, HTML).
Let's include them in the plugin listing, that is, when a user calls
`avocado plugins`.
> Result plugins: also list them on "plugins" command

- avocado/core/runner.py
We already disable stdin by setting sys.stdin for tests, but there is
still way to access it via `os.read(0, ...)`. This patch replaces the
`0` (STDIN) file descriptor with the `/dev/null` file descriptor.
Simple check is:
avocado run /bin/read
which hangs until data are provided and fails with this patch.
> avocado.core.runner: Disable stdin for tests

- Makefile
- avocado/core/version.py
- optional_plugins/html/setup.py
- requirements-docs.txt
- requirements-travis.txt
- requirements.txt
- setup.py
This collection of patches tries to streamline the installation experience that users will get with the standard Python tools.
In short, we rename the *package* to `avocado-framework`, adjust some optional packages from `requires*.txt` and finally add core requirements to `setup.py` itself.
This should allow any user to install avocado using `pip install avocado-framework` after this is incorporated and a new package is pushed to PyPI.  Until then, the same experience can be tested by running:
```
pip install -e git://github.com/clebergnu/avocado.git@requirements#egg=avocado-framework
```
This can be done, say, in a virtual environment, and the basic avocado functionality should be up and running with this single command.
> Packaging and installation improvements

- examples/testplans/release.json
Now the --vm-domain, when used without --vm-hostname, requires the qemu
guest agent to be running. This patch includes this information in our
pre-release test plan.
> testplan: install and start qemu-ga

- avocado/utils/build.py
1- fix style compatible to pep8 standard
2- rename make to run_make which using process.run
>  added a function which uses "process.run"[v3]

- .travis.yml
This patch enables all the optional plugins in travis to increate the
test coverage.
Reference: https://trello.com/c/UHdVHzOZ
> travis: enable plugins in travis ci check

- avocado/core/test.py
When the test fails, it is useful to expose the local variables of the
test function.
Reference: https://trello.com/c/yvhobkqO
> test: expose local variables on test error

- docs/source/GetStartedGuide.rst
We have introduced updated packages (41.0) to PyPI, which now support
a much improved installation experience using pip. Let's add a section
on that.
While on that, let's restructure the sub sections levels.  The proposal
here for the sub sections on the "Installing Avocado" section is:
1) Installing from Packages
1.1) Fedora
1.2) Enterprise Linux
2) Generic installation from a GIT repository
3) Installing from standard Python tools
> docs: add section on Avocado installation using pip

- Makefile
The avocado package was renamed in 760d82c91ec to `avocado-framework`,
but the cleanup was left unchanged. This commit fixes it.
> Makefile: Fix the egg cleanup

- selftests/checkall
`.git` may hold content that ends up being checked by inspektor, such
as the `git-rerere` cache.  This may cause false positives, so let's
skip `.git` completetly from those checks.
> selftests/checkall: skip `.git` directory on inspekt based checks

- avocado/core/job.py
The filtering of test methods is now implemented at the loader module.
This is an unused leftover from older versions, so let's remove it.
> avocado/core/job.py: remove unused method _filter_test_suite

- docs/source/GetStartedGuide.rst
The python's argparse is quite clever and usually evaluates the
positionals and arguments correctly. But with subparsers or weird test
names it might falsely evaluate test name as argument, for example:
avocado run --my_test
avocado run passtest.py --show-job-log failtest.py
those will fail as --my_test looks like an invalid option and
--show-job-log is subparser's option not known to the main parser but as
the main parser already filled positionals it evaluates the
`failtest.py` as extra argument.
The most appropriate way to distinguish between args and positional args
is the `--` separator:
avocado run -- --my_test
avocado run --show-job-log -- passtest.py failtest.py
v1: https://github.com/avocado-framework/avocado/pull/1479
Changes:
```
v2: Fixed typo therefore
v2: Use plural for args …
```
> docs: Add note about args vs. positional args [v2]

- selftests/functional/test_output.py
Currently one of the test_output tests depends on a correct English
message, but the test runs under the system locales. Let's force the
LC_ALL for that execution.
> selftests: Use LC_ALL=C in tests which parse output

- avocado/core/test.py
- selftests/functional/test_basic.py
The --dry-run replaces the test class with a special one instead. When
the original class used a different but "test" methodName this fails
during __init__ as unittest requires the methodName attribute to exists.
This patch always changes the methodName to "test", which is defined in
the fake dry-run class.
> avocado.core.test: Always use "test" as methodName in dry-run

- examples/tests/sleeptenmin.py
The sleeptenmin example test contains `self.report_state` which should
not be called directly and it defines variable which is not used.
> examples: Minor fixes in sleeptenmin test

- Makefile
- avocado.spec
- docs/source/conf.py
- selftests/functional/test_basic.py
- selftests/functional/test_output.py
- selftests/functional/test_wrapper.py
This contains a number of fixes and small improvements that I found necessary to have `make check` passing on a EL6 host.
--
Changes from v1 (#1474):
* Moved HTML bugfix to separate PR
* Use symbolic `errno.EEXIST` instead of literal value
* Use `AVOCADO_OPTIONAL_PLUGINS` in `develop` target and `AVOCADO_EXTERNAL_PLUGINS` in `link` target
> Python 2.6 / EL6 fixes [v2]

- .travis.yml
- Makefile
- selftests/checkall
- selftests/run
This PR makes the `checkall` fail with the first error, unless `SELF_CHECK_CONTINUOUS` is set, which suits better to `git bisect` usage. While on it I went ahead and add colors and results to the output and last but not least finally the parallel execution support, which I wanted to add for ages (and already deleted my branch, so it's freshly developed today).
Trello: https://trello.com/c/6QAdqKeE/582-make-check-could-fail-fast
v1: https://github.com/avocado-framework/avocado/pull/1485
v2: https://github.com/avocado-framework/avocado/pull/1490#discussion_r80911669
Changes:
```
v2: New commit to enable fail fast per unittest (and not just per-module)
v2: Rebased
v3: Fix the boundaries typo
```
> selftests.checkall: Adjust the behavior and add parallel check [v3]

- avocado/core/dispatcher.py
- avocado/core/job.py
- optional_plugins/html/avocado_result_html/__init__.py
Previously, a crash in one result plugin could abort the execution of other plugins and consequently the last parts of the avocado command line application execution.
Let's handle exceptions that could be raised there, as it's already being done with Job Pre/Post plugins.
Additionally, this bundles the HTML result fix with older pystache versions, since one of the review requests was to improve the handling when unicode conversions occur so that Avocado doesn't crash.
> Handle result plugin failures / HTML result fix with older pystache

- avocado/core/dispatcher.py
- avocado/plugins/plugins.py
- docs/source/Plugins.rst
- etc/avocado/avocado.conf
- selftests/functional/test_basic.py
While the behavior of having a plugin enabled once it's installed has suited Avocado reasonably well, there are valid use cases that require plugins to be disabled.
While adding this mechanism, let's define what the Avocado fully qualified name for a given plugin is.
While not an urgent feature, enabling and disabling plugins is actually one requirement for the implementation of the Job API.  While this change allows for disabling plugins globally, a refinement of the same logic will allow a given Job to enable/disable some of Avocado's functionality.
> Plugins: add mechanism to disable installed plugins

- README.rst
Before you can run the script straight out of the run tree you need to
run a make develop step so let's make it clear.
Signed-off-by: Alex Bennée <alex.bennee@linaro.org>
> README.rst: mention make develop (fixes #1496)

- avocado/core/sysinfo.py
Using avocado.utils.process to run the journalctl commands makes avocado
to ignore the KeyboardInterrupt signal and consider the test as PASS due
to the later (sysinfo post) command executed successfully.
This patch changes the method to run the journalctl commands to
subprocess.check_output. Now Avocado seems to handle KeyboardInterrupt
nicely.
Reference: https://trello.com/c/dNgrjMOJ
> Fix issue in journalctl log watcher

- scripts/avocado-journal-replay
There's a missing space at the end of the line, that is, let's
replace "datato" with "data to".
Signed-off-by: Wei Jiangang <weijg.fnst@cn.fujitsu.com>
> scripts/avocado-journal-replay: Fix usage message

- selftests/checkall
It might be useful to also list the command which failed to run in
parallel selfcheck.
> selftests.checkall: Print the unittest cmd which failed

- avocado/utils/process.py
v2:
- Add it pid as a CmdResult class parameter.
- Include pid information in CmdResult class __repr__().
v1: #1516 
process.Popen returns the process ID, so let's use it in our
CmdResult class.
Fixes: #1514
> avocado.utils.process add pid information to CmdResult [v2]

- docs/source/GetStartedGuide.rst
The OpenSUSE project ships the LTS versions of Avocado.  Let's
document that so users on that distro can get a head start using
official distro packages if they choose to do so.
Signed-off-by: Sergey Bronnikov <sergeyb@openvz.org>
> Docs: describe OpenSUSE support in Avocado

- avocado/utils/git.py
The usual use of the git library is to get latest (or some) version,
quite frequently into a unique tmp dir. Let's disable recording it's
output for --output-check.
Signed-off-by: Philipp Wagner <imphil@philipp-wagner.com>
Issue: https://github.com/avocado-framework/avocado/issues/1505
Reproducer:
```diff
diff --git a/examples/tests/passtest.py b/examples/tests/passtest.py
index 4f6e25c..c5a5459 100755
--- a/examples/tests/passtest.py
+++ b/examples/tests/passtest.py
@@ -14,6 +14,8 @@ class PassTest(Test):
"""
A test simply doesn't have to fail in order to pass
"""
+        from avocado.utils import git
+        git.get_repo("https://github.com/ldoktor/my_git")
pass
```
```
avocado run passtest.py --output-check-record all
cat …
```
> avocado.utils.git: Don't produce check output

- avocado/core/job.py
Backport
When the tests are not going to be copied, there's no need to try to
discover them locally.
This patch fakes the test_suite when remote-no-copy is used.
Reference: b168855ef4b773de7ba8b8b69e6b18e0cf93db03
> [36lts] Don't discover tests when using --remote-no-copy

- selftests/functional/test_basic.py
Recently I fixed a bug where test which asks for input hangs for
infinity but I forgot to add unittest for it. Let's add it now.
v1: https://github.com/avocado-framework/avocado/pull/1520
v2: https://github.com/avocado-framework/avocado/pull/1528
Changes:
```
v2: Fix typo reada => read
v3: Skip test in decorator, rather then in test
```
> selftests: Add /bin/read selftest

- docs/source/GetStartedGuide.rst
Some pieces of Avocado are distributed as optional packages, let's
document that fact and how to install them using both RPM and source
based installs.
> Docs: document optional packages installation

- avocado/core/remote/runner.py
- avocado/plugins/yaml_to_mux.py
- selftests/unit/test_remote.py
- Rename `multiplex` to `mux_yaml` in remote runner and related selftests.
- Since `avocado.test` is not available when plugins are in action, use `avocado.app` logger to warn users about the deprecated option.
> fix issues with new mux-yaml option

- avocado/core/job.py
- avocado/core/remote/result.py
- avocado/core/remote/runner.py
- avocado/core/result.py
- avocado/core/runner.py
- avocado/plugins/tap.py
- selftests/unit/test_remote.py
This is collection of cleanups on the result module, that sets some of the stage for the conversion of the Result class to a pure result (data) holder.
Since these changes do not (or should not) introduce behavior change, I felt like sending them earlier.
--
Changes from v1 (#1537):
* Removed `output` attribute from RemoteResult
* Removed `self.args` access on RemoteResult (using `job.args` instead)
> Result cleanups [v2]

- avocado/core/runner.py
Avocado is running slowly on my machine and the reason are the sleep() calls in the test run loops. This PR optimizes a couple of sleep() calls to make Avocado more responsive and consuming less CPU.
> avocado.core.runner: optimize sleep times in waiting loops

- avocado/utils/process.py
- selftests/functional/test_lv_utils.py
- selftests/unit/test_utils_iso9660.py
- selftests/unit/test_utils_partition.py
There were several implementations of can_sudo methods in selftests,
most of them broken as eg. "mount" can run without sudo, which is what
happens if sudo is not available.
This patch replaces those custom methods with the one recently
introduced in `avocado.utils.process`.
v1: https://github.com/avocado-framework/avocado/pull/1533
v2: https://github.com/avocado-framework/avocado/pull/1541
v3: https://github.com/avocado-framework/avocado/pull/1542
Changes:
```
v2: New commit to support custom command for can_sudo
v2: Use the custom commands (where it makes sense) in selftests
v3: Change one plain sudo check for "mount" one in iso9660
v3: Add "kill" sudo check in one partition test
v4: Use `kill -l`
v4: Remove the `missing_binary(mkfs.ext2)` which is handled by `can_sudo(mkfs...`
```
> selftests: Replace custom can_sudo check with process.can_sudo [v4]

- selftests/functional/test_basic.py
- selftests/functional/test_lv_utils.py
v2:
Probe the binary only once and use if throughout the skip tests and the tests themselves.
v1: #1555 
Let's separate the check for requirements and the test code according to
the project's understanding of setup/test phases.
> selftests: Remove skip test [v2]

- avocado/core/loader.py
v2:
Sort the directories as well.
v1: #1554 
This was requested on avocado-devel mail list. Now the test directories
and the test files are sorted alphabetically by the test loader.
Reference: https://trello.com/c/whLgcvtO
> avocado.core.loader sort directories/files alphabetically [v2]

- docs/source/GetStartedGuide.rst
There is a "`" missing of the in-line code and break the layout of the document.
> In-line code block format fix

- avocado/core/job.py
- avocado/core/loader.py
- avocado/core/remote/runner.py
- avocado/core/result.py
- avocado/core/runner.py
- avocado/plugins/docker.py
- avocado/plugins/remote.py
- avocado/plugins/vm.py
- docs/source/RunningTestsRemotely.rst
- selftests/unit/test_jsonresult.py
- selftests/unit/test_remote.py
- selftests/unit/test_xunit.py
v3:
- Use test.SkipTest instead of test.DummyTest.
- Rename `ResultProxy.tests_total()` to `ResultProxy.set_tests_total()`.
- Drop `--mux-ignore-missing` option introduced in v2.
- Document the issue with multiplex + remote in regards to the multiplex files availability.
v2: #1563 
- Rename `RemoteLoader` to `DummyLoader`.
- Rename `UnknownTest` to `DummyTest`.
- Introduce the `--mux-ignore-missing` option to yaml_to_mux plugin so users can ignore failures due to missing multiplex files in local host.
- Include stacktrace in debug log when the job fails remotely.
- Cleanup in docker plugin, removed unused functions after remote copy removal.
v1: #1543 
- Move the number of tests probe from the job to the runner.
- Create a remote loader for the remote plugin.
- Improve error handling of …
> Remove improvements [V3]

- contrib/scripts/avocado-get-job-results-dir.py
v2:
- Write errors messages to stderr.
v1:
- Simple contrib script to find the Job results directory of a given Job identified by the Job (partial) ID.
> Job ID: utility/command to find job results by ID [V2]

- avocado/core/remote/runner.py
- avocado/plugins/docker.py
- selftests/unit/test_remote.py
- Fix attribute leftover after commit 295b8f6.
- Drop directory change for remote executions, not needed anymore after commit  9d483a360 and doomed to break remote avocado in machines that does not have the directory already created.
> Docker plugin fixes

- avocado/plugins/docker.py
In the https://github.com/avocado-framework/avocado/pull/1569 we removed the `receive_files` from docker, which is still necessary in order to receive results of the avocado job. Let's bring it back.
Also note that without the plugins order it might happen that the `html` plugin runs before the `archive`, which results in:
```
DOCKER     : Container id 'db60234eeafabc131fbd63a5c427b60268557f92b8ae4062613613fcfb59c431'
DOCKER     : Container name 'job-2016-10-27T09.42-c0eb3e2.avocado'
JOB ID     : c0eb3e28165c3bb3bf4f613af78422377a381989
JOB LOG    : /home/medic/avocado/job-results/job-2016-10-27T09.42-c0eb3e2/job.log
TESTS      : 1
(1/1) /bin/true: PASS (0.00 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
TESTS TIME : 0.00 s
Error running method "render" of …
```
> docker: Return the receive_files and improve UI

- avocado/utils/process.py
In order to exit subprocess gracefully, our library overrides the
default SIGINT handler with a custom handler that waits for the
subprocess. Since the default SIGINT handler raises a KeyboardExeption,
which is expected by the caller, and our custom handler does not, this
patch calls the default handler from inside our custom handler, after
the steps required to exit the subprocess gracefully.
Reference: https://trello.com/c/NZPg155x
> avocado.utils.process: execute default sigint handler

- avocado.spec
- avocado/core/data_dir.py
- avocado/core/version.py
- avocado/utils/kernel.py
- avocado/utils/partition.py
- avocado/utils/software_manager.py
- examples/testplans/release.json
As a preparation for proposing official Avocado packages to Fedora, let's make sure our packages are free or warnings/errors (as detected by rpmlint).
> Resolution of RPM package warnings and errors spotted by rpmlint 

- avocado/core/sysinfo.py
During revert f1456dc3e72a7bec20e0d00fdf6af87a15dba119, which reverted
f658f0e5d3099a7a1f896120848f644ae8e21ef7 the `--quiet` was removed,
but it is suppose to be there. Let's revert that part.
> sysinfo: Revert the removed `--quiet` option to journalctl

- selftests/functional/test_basic.py
- selftests/functional/test_output.py
The first one disables the `sysinfo` collection and adds `job-restuls-dir` where it's not defined, the second merges two checks into the same one (0.812s vs. 1.123s and we don't expect this to fail frequently - or at all).
> selftests: Two little adjustments

- selftests/functional/test_basic.py
- selftests/functional/test_multiplex.py
- selftests/functional/test_plugin_jobscripts.py
Some functional tests, most of which execute a full avocado command,
were missing the `--job-results-dir`, pointing to a directory that
would be removed after the tests.  This has led to the pollution of
the standard job results directory (usually `~/avocado/job-results`)
when selftests are run.
This proposal fixes all but one set of functional tests, which has
to be fixed with a different set of changes (see reference).
Besides the functional tests, some unittests are also creating
job results that should be discarded.  It's believed that at least
some of this is caused by the relationship between tests and jobs,
but this is speculation and it's not attepted to be fixed on this
patch.
Reference: https://trello.com/c/I2ieqhR5
Signed-off-by: Cleber Rosa crosa@redhat.com
> Functional tests: prevent the persistence of temporary job results

- avocado/core/test.py
Creating a test interactively is not entirely a use case we have
thought about, AFAICT, but it shouldn't fail because of an
implementation detail.
The implementation detail, in detail, is that the `filename` property
uses inspect to try to locate the file that backs
`avocado.core.test.Test` based tests.  The proposed change is that,
if inspect fails to find the file that backs the test, the tests'
`filename` property should resolve to None.
In practice, this allows the following snippets to be tried on the
Python interpreter:
```
>>> import avocado
>>> class Test(avocado.Test):
...     def test(self):
...         pass
>>> t = Test()
```
> Test: allow for avocado.core.test.Test tests without a hosting file

- avocado/core/multiplexer.py
- avocado/core/test.py
- docs/source/WritingTests.rst
- docs: remove examples of `default_params` usage.
- api: include deprecation message for `default_params`.
> Start the deprecation process for `default_params`

- avocado/core/loader.py
- selftests/unit/test_loader.py
Let's make these symbols available in the documentation, and use them
where they're not yet being used.
--
Changes from v1 [#1587]
* Fixed missing exposing the `ALL` variables to the docs
> Loader: use symbolic names for discovery test type selection [v2]

- docs/source/release_notes/36_0.rst
- docs/source/release_notes/37_0.rst
- docs/source/release_notes/38_0.rst
- docs/source/release_notes/39_0.rst
- docs/source/release_notes/40_0.rst
- docs/source/release_notes/41_0.rst
- docs/source/release_notes/42_0.rst
We have docs available on Red The Docs for all versions from 36.0
onwards. Let's include in each release notes the link for the version
documentation so users can easily see the docs for that version.
> docs: include link for the version documentation

- docs/source/MaintenanceGuide.rst
Let's include in the `Releasing avocado` guide the steps required to
configure Read The Docs every version release.
> docs: include Read The Docs steps

- requirements-selftests.txt
- selftests/cyclical_deps
graphviz drawing tools are no longer imported into the top
level namespace of networkx (networkx >= 1.11). This patch
changes the read_dot(), using it from the actual module.
Also, let's update the required version for pydot to make sure it works with latest networkx.
> fix selftests/cyclical_deps

- avocado/core/dispatcher.py
- avocado/core/job.py
- avocado/core/plugin_interfaces.py
- avocado/core/remote/runner.py
- avocado/core/remote/test.py
- avocado/core/result.py
- avocado/core/runner.py
- avocado/plugins/docker.py
- avocado/plugins/human.py
- avocado/plugins/journal.py
- avocado/plugins/run.py
- avocado/plugins/tap.py
- optional_plugins/html/avocado_result_html/__init__.py
- selftests/unit/test_job.py
- selftests/unit/test_jsonresult.py
- selftests/unit/test_remote.py
- selftests/unit/test_result.py
- selftests/unit/test_vm.py
- selftests/unit/test_xunit.py
- setup.py
This is a complete implementation of the `ResultEvents` plugin interface, including the migration of the `HumanResult`, `TAP` and `Journal` plugins.  A few notes:
* The `FileOrStdOutAction` approach was kept to lock access to STDOUT.  As suggested by @ldoktor there are fancier and cleaner approaches, but they were not attempted here.
* Those changes expose a lot of issues about or current job/runner implementation details.  Some of the commits are controversial and inteded as a RFC.
--
Changes from v1 (#1592):
* Reordered commits, putting commits that are not explicitly related to the Result Events plugins changes (that is, general bugfixes) first.
* Merged (squashed) commits "Result: introduce interface for event based result plugins" and " 	Result: introduce result events dispatcher" …
> Result Events [v4]

- avocado/plugins/tap.py
Before this patch tap output to a file fails with below error
File "/usr/lib/python2.7/site-packages/avocado_framework-42.0-py2.7.egg/avocado/core/result.py", line 178, in check_test
self.end_test(state)
File "/usr/lib/python2.7/site-packages/avocado_framework-42.0-py2.7.egg/avocado/plugins/tap.py", line 69, in end_test
self.__write("#   " + line)
File "/usr/lib/python2.7/site-packages/avocado_framework-42.0-py2.7.egg/avocado/plugins/tap.py", line 35, in writeln
return self.output.write(msg % args + "\n")
TypeError: not enough arguments for format string
This patch addresses above issue.
> Fixup: format strings for tap output[V3]

- docs/source/Configuration.rst
- docs/source/DevelopmentTips.rst
- docs/source/Diff.rst
- docs/source/GetStartedGuide.rst
- docs/source/MaintenanceGuide.rst
- docs/source/Mux.rst
- docs/source/ResultFormats.rst
- docs/source/RunningTestsRemotely.rst
- docs/source/WritingTests.rst
Please take a look at the individual commit messages for details.
v1: https://github.com/avocado-framework/avocado/pull/1605
Changes:
v2: rpm => RPM
v2: Use the full outputdir location to avoid confusion
> docs: Bunch of documentation fixes and improvements 

- avocado.spec
- selftests/doc/test_doc_build.py
1. Added explicit build dependencies upon kmod to prevent test_lv_utils check
failures.
2. Modified test_build_docs to explicitly ignore bogus warnings due to a bug
in older versions of python-sphinx package causing checks to fail.
3. Enabled EL7 checks during package build.
Signed-off-by: Merlin Mathesius <mmathesi@redhat.com>
> Fix selftests on EL7 and enable checks on package build

- avocado/plugins/journal.py
- avocado/plugins/plugins.py
- avocado/plugins/run.py
This PR adds "result events" plugins to the output given when running `avocado plugins`.
It also fixes two related issues that are visible when running `avocado plugins`
-- 
Changes from v1 (#1606):
* Made the fix to journal a separate commit
* Split line to reduce length on `plugins.py`
> Plugins list: add result events [v2]

- avocado/plugins/human.py
Commit 2e6ecce6 made the human results a real plugin. But the change
broke the human results for replay jobs. This is a fix that makes the
human results to show the SRC JOB ID properly again.
> Fix human output for replay jobs

- avocado/core/data_dir.py
- avocado/core/job.py
- avocado/plugins/run.py
- etc/avocado/avocado.conf
v1: #1615 
v2: #1620 
- New option `--keep-tmp (on|off)` for Avocado run command with precedence over the `keep_tmp_files` config option.
v3:
- Drop non-working config option `keep_tmp_files`.
- Decide whether we will keep the tmp dir or not based on the `basedir`. If it's not `None`, then we create the tmp_dir in the `basedir` location and don't remove it when the job finishes.
> Preserve test environment for post-mortem debug [v3]

- setup.py
python 2.6 require stevedore>=1.8.0,<=1.10.0
but,there is no constraint condition in setup.py,
it will cause vt-bootstrap failed with python 2.6.
So define the stevedore version conditionally on
the current python version
issue:
https://github.com/avocado-framework/avocado/issues/1613
Signed-off-by: Yanan Fu <yfu@redhat.com>
> setup: define the stevedore version conditionally on the current python version

- avocado/plugins/replay.py
- selftests/functional/test_basic.py
- selftests/functional/test_replay_basic.py
- selftests/functional/test_replay_external_runner.py
- selftests/functional/test_replay_failfast.py
v2:
- Fix commit message.
- Add a test with the source job identified by its results directory.
v1: #1626 
- Make replay to use the `--job-results-dir` as a location to find the source job.
- Drop the `replay-data-dir`, which became redundant after the ability to identify a source job by its results directory.
>  Replay to use --job-results-dir as source job location [v2]

- docs/source/ResultFormats.rst
Instead of the `Result` (old-style plugin) approach.
Also, the example `xunit` module was incorrect and it's fixed here.
> docs: use ResultEvents interface

- docs/source/WritingTests.rst
The term we've used so far, it's too specific and conflicts with
the idea of "tagging", that is, categorizing tests.
Independent of the upcoming work on "tags", it looks like a good
idea to change the terminology being used here.
> Docs: rename the "avocado tags" to "docstring directives"

- Makefile
- examples/testplans/release.json
- selftests/functional/test_basic.py
- selftests/functional/test_interrupt.py
- selftests/functional/test_utils.py
We've been getting failures on both Travis CI and RPM build servers.  Let's run these tests only on environments where resources are plentiful.
This addresses #1619.
> Selftests: deal with resource/time sensitive tests

- Makefile
We renamed make check-long to make check-full. Let's reflect that change
in the help message.
> Makefile: fix help message

- avocado/core/output.py
- avocado/core/runner.py
- avocado/core/test.py
v5:
- Create `LoggingFile.rm_handler()`.
- Adjust `_stop_logging()` to avoid any possibility of infinite recursion error.
v4: #1649 
- Adjust the `_stop_logging()` sequence.
v3:  #1647 
- Drop the commit with the protection to the `LoggingFile`
- Remove the handlers in `_stop_logging()`.
v2: #1644 
- Use `continue` to skip the logger instead of appending a `NULL_HANDLER()` to the logger.
v1: #1631 
- Check if all loggers in `output.LoggingFile()` instance contains a handler and, if not, add the `NullHandler`.
- Add loggers `avocado.core.stdout` and `avocado.core.stdout` to the `sys.stdout` / `sys.stderr` (which are `output.LoggingFile()` instances) only when we have a handlers for them.
> Fix issue "RuntimeError: maximum recursion depth exceeded" [V5] 

- avocado/core/job.py
- avocado/core/loader.py
- avocado/core/safeloader.py
- avocado/plugins/list.py
- avocado/plugins/run.py
- docs/source/WritingTests.rst
- examples/tests/abort.py
- examples/tests/cabort.py
- examples/tests/datadir.py
- examples/tests/doublefail.py
- examples/tests/doublefree.py
- examples/tests/doublefree_nasty.py
- examples/tests/errortest.py
- examples/tests/errortest_nasty.py
- examples/tests/errortest_nasty2.py
- examples/tests/errortest_nasty3.py
- examples/tests/fail_on_exception.py
- examples/tests/failtest.py
- examples/tests/gdbtest.py
- examples/tests/linuxbuild.py
- examples/tests/modify_variable.py
- examples/tests/passtest.py
- examples/tests/sleeptenmin.py
- examples/tests/uncaught_exception.py
- selftests/unit/test_loader.py
- selftests/unit/test_safeloader.py
This adds support for test tags (to choose categorized tests) to the safeloader, loader, and also to the list and run commands.
---
Changes from v3 (#1651):
* Added warning about how docstring directives do not allow spaces in between the value and how that affects tags.
Changes from v2 (#1637):
* Made the filtering agnostic to test type. Although we only support getting tags from INSTRUMENTED tests, the filtering does not check that.  This was necessary to make things such as `--filter-by-tags-include-empty` work accross the board and suggested by @famz
* Added test that checks that everything after a space on "tags=" values are ignored.  The root reason is the format for *all* docstring directives (see regex). Suggested by @ldoktor
* Added tests for docstrings directives with spaces, as …
>  Test filtering by tags [v4]

- avocado/core/output.py
- avocado/core/runner.py
- avocado/core/test.py
We currently override sys.stdout and sys.stderr with instances of
output.LoggingFile with some loggers. But bu adding test loggers in the
runner is causing output.LoggingFile to have loggers without handlers.
This patch creates a mechanism to include loggers later in a
output.LoggingFile instance so we can delay the test loggers inclusion
in sys.stderr/sys.stdout to the correct moment.
Also, create the proper cleanup in _stop_logging()
Merged upstream as 58581e160b63bd9d99c8154d82dcb4a6c0c7c03d
> [backport] 36lts: don't add logger without handlers to output.LoggingFile instances

- avocado/core/loader.py
- spell.ignore
Only two occurrences. One is a typo and another is an exception.
> spell: fix spelling for v44 release

- docs/source/GetStartedGuide.rst
It looks like the test result is not copy-paste from real test. 
Since there are two `(6/6)`, and actually no `ERROR` occurs but get 2 in result summary.
> docs: Update the documentation test output

- avocado/plugins/tap.py
- selftests/functional/test_output.py
We do produce `results.xml` and `results.json`, let's also include
`results.tap` by default and allow disabling this by `--tap-job-result`.
Note it's impossible to initialize the default result.tap in `__init__`
as we only get `args` and not the job itself, therefor this patch adds
it as first thing inside the `pre_tests` step.
> avocado.plugins.tap: Produce result.tap by default

- avocado/utils/distro.py
- avocado/utils/software_manager.py
The package manager for both is zypper. Both have an /etc/os-release
file, but the content of it is quite different.
Some examples:
NAME="openSUSE Leap"
VERSION="42.2"
ID=opensuse
NAME="SLES"
VERSION="12-SP2"
VERSION_ID="12.2"
NAME="openSUSE Tumbleweed"
ID=opensuse
VERSION_ID="20161125"
So I took the easy path - what they all have in common is the SUSE
string. And as no other probe looks at /etc/os-release, this is very
safe for now.
> Support SUSE and openSUSE

- avocado/core/runner.py
- avocado/utils/gdb.py
This patch set increases some runner timeouts, gdb init timeout and improves the loop condition.
v1: https://github.com/avocado-framework/avocado/pull/1661
Changes:
```
v2: Send kill -9 just once
```
> Increase avocado timeouts [v2]

- docs/source/Loaders.rst
From test writer perspective, we need the information about test tags in
the Writing Tests section. But from the users executing tests
perspective, the information about test tags should be present in Test
Discovery section. Let's fix that creating this cross-reference.
Changes from v1 (#1664):
- Better section header.
> docs: cross-reference for test tags in 'Test discovery' [v2]

- avocado/utils/astring.py
- selftests/unit/test_astring.py
This PR makes tabular output work properly when the columns contains terminal control characters. As a side effect it's also possible to print matrices with different number of columns.
v1: https://github.com/avocado-framework/avocado/pull/1662
Changes:
```
v2: Complete rework which uses custom formatting to avoid python's limitation in "%-{num}s"
v2: Remove (or rather not-implement) the MOVE_LEFT and MOVE_RIGHT term control characters
```
> avocado.utils.astring: Handle term ctrl characters in tabular output

- avocado/utils/pci.py
avocado.utils.pci: Adds pci related modules.
Changelog from v1 #1657:
* Removed the use of pipes in bash commands, and used python parsing.
* Added docstring to explain more about the functionality of the module.
* Added a new function to get the kernel driver.
* And taken care other python usability related comments of @ldoktor from v1.
Changelog from v2 #1672:
* Changed the reference from 'pci device' to 'pci address' for better interpretation.
* Changed the name of function names for better interpretaton.
* Updated docstrings about ppc specific functions.
* removed `shell=True` wherever not needed.
* And taken care other python usability related comments of @ldoktor from v2.
> Adding PCI module [v3]

- docs/source/ContributionGuide.rst
Let's add the recommended (legal) language that will let our
contributors know what a "Signed-off-by" line means when sending
contributions to Avocado.
--
Changes fom v1 (#1689):
* Added "or any later version"
> docs: make contribution licensing terms (DCO style) more explicit [v2]

- .travis.yml
- selftests/checkall
Let's make sure code without correct "Signed-off-by" message is not accepted. In order to avoid having multiple implementations or spoiling Makefile with yet another check I implemented it in "selftests/checkall", which used to be executed per all commit except of the first one and I also changed the travis script to use the same check for all commits, so now the "checkall" script checks all commits.
> travis: Enforce signed-off-by message in travis

- avocado/core/loader.py
- avocado/core/test.py
- selftests/functional/test_basic.py
- selftests/functional/test_output.py
- selftests/unit/test_loader.py
v2:
- Keep selftests `test_ugly_echo_cmd`.
- Allow `external-runner` to use arguments.
- Instead of script, use external runner in test `test_kill_stopped_sleep`.
v1: #1692
> Remove argument support for SIMPLE tests [V2]

- Makefile
Since we favor the creation of a tarball with "git archive", PyPI gets
sensitive every now and then with our uploads.  Since the 42.0
release, pushing the new packages to PyPI would result in Server
Errors.
This adds the PKG-INFO to the tarball that will be uploaded, which
seems to fix the current errors.  Also, since it's now a single file,
it can be pushed with the "twine" command line application.
Alternatively, we could double check our file manifest, and rely
entirely on setuptools to generate the tarball.  But, I'm not a big
fan of adding files to version control, and then to a manifest of any
sort.
Note: in the past, this was also necessary because of the tweaks to
the information inside the PKG-INFO file, namely the package name
(avocado -> avocado-framework).
Signed-off-by: …
> Makefile: adjust PyPI packaging/upload

- avocado/utils/multipath.py
- avocado/utils/pci.py
Those should really be ":param <parameter_name>:".  The rendered text
for "parm" is readable, but it's not properly recognized as a
parameter.
> API docs: rendered docstrings do not recognize ":parm"

- avocado/core/test.py
The external runner tests currently do not support the extended API for
simple tests. This patch moves the extended API into the
`SimpleTest.execute_cmd` in order to run this from inherited tests like
ExternalRunner.
Note this version affects all tests which share the
`SimpleTest.execute_cmd`. I think it's a good think, but I'd be also
fine with implementing it as another SimpleTest method and call this
method from inherited tests where it makes sense (like ExternalRunner).
> avocado.core.test: Support avocado-bash-utils in external runner

- avocado/core/test.py
- avocado/core/varianter.py
- avocado/utils/pci.py
- selftests/unit/test_astring.py
- spell.ignore
This is a collection of docstring, literal string and the spelling
ignore list fixes for the 45th release.
---
Changes from v3 (#1708):
* The last word on tabular output unittest tis kept the same as the previous one (4 chars)
Changes from v2 (#1707):
* Removed `:` typo
* Changes words on tabular output unittest to keep incremental word length
> Spelling fixes for the 45th release [v4]

- avocado/utils/process.py
Result returned by process.system_output() contains trailing
newline. To make it's functionality similar to Popen.communicate()
or commands.get_output() , the trailing newline needs to be stripped.
Added keyword parameter strip_trail_nl to preserve the trailing
newline if needed.
Also added comments in docstring for parameters sudo and
ignore_bg_processes
Signed-off-by: Greeshma Gopinath <ggopinat@redhat.com>
> Striping trailing newline from system_output() result

- contrib/scripts/avocado-bisect.sh
This makes sure we setup and clean the environment before/after the
executed check. It comes from simple script I have been using for ages
and finally I took the time to add colors and some UI to allow running
on unstable environment.
> contrib: Add script which helps bisecting avocado execution

- Makefile
The "make link" feature goes through subdirs trying to either use
`setup.py` or `Makefile` to install all plugins. The problem is that
even when `Makefile` is present it might not support `make link` target
which results in failure. This patch instead of failure in this case
just lists "FAIL" followed by the module name.
> Makefile: Don't fail when "make link" fails

- selftests/checkall
pep8 v2.3.0 introduced the check for bare except clause (E722). Until
now, we don't explicitly disable the pep8 checks we don't want because
inspekt has a default exclude list (E501, E265, W601 and E402).
Let's make explicit the exclude list for the checks we don't want in our
selftests, adding to the list the new E722 check.
> selftests: exclude E722 from pep8 check

- avocado/plugins/yaml_to_mux.py
When we use args:--mux-yaml or --multiplex if the yaml file not existing it
will show more detail error messages
Reference: https://trello.com/c/hYCrS1oI/900-improve-yaml-to-mux-error-messages
Signed-off-by: mengalong <alongmeng@gmail.com>
> improve yaml_to_mux error messages

- avocado.spec
The pystache package should only be a requirement for the HTML
result plugin, not for the base avocado package.
---
* Rebased because of PEP8 erros (skipping them is already on master)
> avocado.spec: do not require pystache on base avocado package [v2]

- .travis.yml
- selftests/checkall
- selftests/functional/test_unittest_compat.py
- selftests/unit/test_job.py
- selftests/unit/test_jsonresult.py
- selftests/unit/test_test.py
- selftests/unit/test_xunit.py
This pull request fixes all places where we were producing results by running selftests and then it adds a check that no new results are produced throughout the `make check` execution.
v1: https://github.com/avocado-framework/avocado/pull/1722
v2: https://github.com/avocado-framework/avocado/pull/1732
Changes:
```
v2: Get the logs_dir from `avocado config`
v2: Enable resultsdir check by default (Use SKIP_RESULTSDIR_CHECK to disable it)
v2: Moved DummyTest class to class namespace rather than using get_tst method
v2: NOT moved the AvocadoPass class from setUp to class namespace because it's
a local var and I prefer the current solution.
v2: NOT using the resultscheck for checks outside checkall as that would require Makefile
changes and I don't see it important enough.
v3: Replace …
```
> selftests: Don't produce results in default results dir [v3]

- avocado/__init__.py
- avocado/core/decorators.py
- avocado/core/exceptions.py
- avocado/core/test.py
- docs/source/WritingTests.rst
- selftests/functional/test_skiptests.py
v2:
- Use `avocado.utils.script` in selftests.
- Include doccumentation.
- Better naming and organization for skip exceptions.
v1: #1725 
- Improve selftests.
- Move decorators from `avocado.Test` to `avocado`.
RFC: #1718
> Add skip, skipIf and skipUnless decorators [V2]

- .travis.yml
- selftests/functional/test_teststmpdir.py
Two patches related to Travis:
1. A "temporary fix" (more of a temporary workaround) so that our workflow is not halted
2. An improvement to the package requirements in the environment we run our tests in
---
Changes from v1 (#1745):
* Skip the test only during regular `make check` and Travis runs, keep it enabled one `make check-full`
> Travis fixes [v2]

- avocado/core/remote/runner.py
- avocado/plugins/docker.py
We're not checking if the there's an owner for the STDOUT when
displaying the runner connection information.  This makes
command lines that output, say, xunit to the STDOUT, to become
corrupted with a "LOGIN: " (or similar) line.
---
Changes from v1 (#1724):
* Added similar check to VM and Docker plugins
> Remote/VM/Docker Runners: check if it's OK to use STDOUT

- avocado/core/sysinfo.py
- docs/source/Sysinfo.rst
- docs/source/index.rst
- etc/avocado/avocado.conf
- selftests/functional/test_sysinfo.py
This PR addresses the https://github.com/avocado-framework/avocado/issues/1714 by adding an optional timeout for sysinfo `commands` gathering and also adds the basic sysinfo documentation.
v1: https://github.com/avocado-framework/avocado/pull/1715
v2: https://github.com/avocado-framework/avocado/pull/1730
Changes:
```yaml
v2: Use timer thread rather than busy loop
v2: Make the value configurable via settings
v2: Add functional selftests
v3: Set the default in config to avoid confusion of what is the default
```
> sysinfo: Introduce a timeout for Command gathering [v3]

- avocado/utils/asset.py
Hash files (%s-CHECKSUM) were always written into the last cache
directory specified in `datadir.paths.cache_dirs`. This failed if that
directory does not exist or is not writable.
Fix this by setting self.hash_file again when deciding were to download
the asset to.
> avocado.utils.asset: put hashfile next to asset file

- avocado/__init__.py
- avocado/core/decorators.py
- avocado/core/exceptions.py
The `avocado.core.decorators` module has been recently added with the
`skip*` family of decorators.  Still, we have `fail_on()`, also a
decorator, defined in `avocado.core.exceptions`.
For consistency, let's put them in the same module.  There are no
changes to users of the Avocado Test API.
> fail_on(): move internal implementation to avocado.core.decorators

- avocado/utils/pci.py
Different servers returns the slot numbers in different formate.
So filtering it with regExp may not return correct value.
hence return a slot value directly from file output, and leave
upto the user for rheir usage accordingly.
following are few example of different slot values on different
systems
examples:
root@ltciofvtr-firestone1:~# lsvpd -l 0000:01:00.1 | grep -i "*YL"
*YL Slot5
root@ltciofvtr-firestone1:~#
root@ltc-briggs3:~# lsvpd -l 0004:01:00.1 | grep -i "*YL"
*YL WIO Slot3
root@ltc-briggs3:~#
root@ltcalpine-lp2:~# lsvpd -l 0028:01:00.0 | grep -i "*YL"
*YL U78C7.001.RCH0040-P1-C9-T1
root@ltcalpine-lp2:~#
> Return slot direct from file output without any filter

- avocado/utils/pci.py
lspci output lists System perpheral deivece's pci address too,
like PCI Bridge, which are not much operable by end user. Hence
skipping them while parsing the pci adress to the user.
these deivce looks like as follows
*XXX:XX:XX.X System peripheral: PLX Technology, Inc. Device 87d0
example:
root@ltc-briggs3:~# lspci -D | grep -i peripheral
0001:01:00.1 System peripheral: PLX Technology, Inc. Device 87d0
0001:01:00.2 System peripheral: PLX Technology, Inc. Device 87d0
0001:01:00.3 System peripheral: PLX Technology, Inc. Device 87d0
0001:01:00.4 System peripheral: PLX Technology, Inc. Device 87d0
root@ltc-briggs3:~#
> adding a line to pci.py to skip System peripheral device in output

- Makefile
We already tweaked the "make link" to not fail when "make link" fails
but I forgot about unlink, which is now failing. Let's allow the "make
link" failure as there might be non-related modules not implementing the
"make unlink" functionality.
> Makefile: Don't fail when "make unlink" fails

- avocado/core/result.py
- avocado/core/runner.py
- avocado/plugins/tap.py
- optional_plugins/runner_remote/avocado_runner_remote/__init__.py
- selftests/functional/test_output.py
- selftests/unit/test_jsonresult.py
- selftests/unit/test_remote.py
- selftests/unit/test_xunit.py
The number of tests to be run in TAP output.  The current implementation uses the number of tests but do not take into account the number of variants.
> TAP: fix number of test to be run (tests * variants)

- examples/testplans/release.json
The virt/vt plugin names contain '-'s and not '_'s.
> testplan: Correct plugin names

- docs/source/GetStartedGuide.rst
v1: https://github.com/avocado-framework/avocado/pull/1780
Changes:
```yaml
v2: 2 English corrections by Cleber
```
> docs: Add docs about interrupting/pausing tests execution [v2]

- avocado/plugins/human.py
This information is not accurate since it does not consider the number
of variants. Also, if it was accurate, it would be redundant.
Let's just remove it.  
Reference: https://trello.com/c/62I3ABZ0
> Remove the TESTS line from the UI

- avocado/plugins/yaml_to_mux.py
- selftests/unit/test_mux.py
Previously we were directly using the yaml.Loader, which is shared
across all `yaml` instances. This patch creates a `_BaseLoader` with the
basic set of constructors. That one is copied and updated of the
run-time data (debug/non-debug) during the `_create_from_yaml` to allow
loading debug and non-debug files in a single execution without
overriding the same loader.
v1: https://github.com/avocado-framework/avocado/pull/1787
Changes
```yaml
v2: Move `add_constructor` to the class-scope
```
> yaml_to_mux: Use custom yaml.Loader [v2]

- selftests/checkall
checkall runs `ls` twice in the job-results dir. Once before the
selftests and once again after the tests, comparing the outputs to make
sure there's no new results there after the selftests.
When the job-results does not exist in advance (the case in travis
environments), the message 'ls: cannot access /home/travis/avocado/job-results:
No such file or directory' is shown in the logs. The message is harmless
and does not affect the check. Let's just suppress the stderr from the
`ls` command in that check.
Reference: https://trello.com/c/IBoLAJjf
> selftests: suppress missing directory message

- docs/source/WritingTests.rst
- docs/source/api_utils_heading
- docs/source/conf.py
While reviewing some of new utils I saw repeated improper patterns. This attempts to set the goals for avocado.utils writing and improves the test writing documentation to describe how to handle libraries exceptions from tests properly.
v1: https://github.com/avocado-framework/avocado/pull/1789
Changes
```yaml
v2: Add all improvements mentioned by cleber except of the signal
```
> Docs: describe test statuses and improve libraries heading [v2]

- avocado.spec
Build on ci.centos.org passes after adding `python-setuptools`.
> Fix #1798 Add missing requirement

- Makefile
We haven't updated the 36.x releases on PyPI, and to do so, we need
a backport of the pypi target.
> Makefile: backport pypi target

- Makefile
On commit dfd3742, a backport for the pypi target, I missed the clean
up of the PYPI_UPLOAD dir.  Let's include it here.
> Makefile: also clean PYPI_UPLOAD dir

- docs/source/release_notes/46_0.rst
Signed-off-by: Mateusz Wagner <mateuszwag@gmail.com>
Fixes issue a with sign in a previous pull req: https://github.com/avocado-framework/avocado/pull/1804
> Fix names of runners' packages in 46.0 release notes.

- avocado/utils/genio.py
- avocado/utils/memory.py
GenIOException Base Exception class has been created for all IO related exceptions.
Also adds write_file_or_fail method in genio library which writes
to a file and raises exception when write fails.
Signed-off-by: Santhosh G <santhog4@linux.vnet.ibm.com>
> Added methods in memory library that gets and sets a transparent huge page values.

- avocado/core/app.py
- avocado/utils/process.py
v3:
- Use `process.kill_process_tree()` instead of custom routine to kill sub-processes.
v2: #1814 
- Add to `avocado.utils.process.get_children_pids()` the ability to return all levels of sub-processes (using the argument `recursive=True`).
- Use `avocado.utils.process` instead os `psutil`.
v1: #1813
> Handle sigterm [v3]

- avocado/core/data_dir.py
- examples/tests/whiteboard.py
- selftests/functional/test_output.py
It is possible to set relative paths in settings, but once we evaluate
them we should turn them into absolute paths to avoid incorrect
representation on `os.chdir` (or so)
Addresses issue: https://github.com/avocado-framework/avocado/issues/1818
> data_dir: Alwas return abspath dir from settings

- avocado/core/test.py
- docs/source/WritingTests.rst
- selftests/functional/test_basic.py
- selftests/unit/test_jsonresult.py
- selftests/unit/test_test.py
- selftests/unit/test_xunit.py
There are several `avocado.test` values which are public but restricted to Avocado usage. Lately we had some nasty user failures which turned out to be related to users overriding those variables. The purpose of this PR is to lower the probability of those clashes usually by turning the internal only variables to internal variables (`__`), then turning the read-only variables to properties without setter.
This is a first part of the https://github.com/avocado-framework/avocado/pull/1809 which was too long for travis to finish...
v2: https://github.com/avocado-framework/avocado/pull/1810
Changes:
```yaml
v2: Remove few commits (will resend when this is merged)
v2: All the minor fixes suggested by lmr
v2: Selftest fixes
v3: Remove the duplicate `default_params` protection commit
v3: Add …
```
> Test: Cleanup and protect the avocado.Test public values [v3]

- avocado/utils/partition.py
mkfs function in partition.py is failing to create a btrfs file
system when already a file system exists on the given disk.
adding -f option will resolve the issue. So added the same and
it is working fine now.
> Added -f argument for formating a disk with btrfs file system

- avocado/core/runner.py
- avocado/core/test.py
- avocado/plugins/xunit.py
This is a stage2 of the https://github.com/avocado-framework/avocado/pull/1817 which includes some deeper changes to avocado.Test to cover all of the publicly available variables.
This version doesn't need any updates to Avocado-vt, but it won't work with older Avocado-vt versions (prior to https://github.com/avocado-framework/avocado-vt/pull/900 )
> Test: Cleanup and protect the avocado.Test public values, stage2

- avocado/plugins/yaml_to_mux.py
--filter-only/--filter-out are being deprecated by
--mux-filter-only/--mux-filter-out, but the deprecation
messages are pointing users to --mux-only/--mux-out, which
does not exist.
This patch fixes the deprecation messages, referencing the
correct new options.
> yaml_to_mux: fix deprecation message

- avocado/core/runner.py
variants.itertests() changed the format of each variant from a tuple to
a dictionary. After that change, the runner was not updated to provide
the mux_path considering the new format.
This patch adds the mux_path to the factory params in _iter_variants(),
fixing the Test.self.__params resolution.
Fixes: #1839 
> runner: fix _iter_variants()

- avocado/core/mux.py
- avocado/core/plugin_interfaces.py
- avocado/plugins/yaml_to_mux.py
- docs/source/TestParameters.rst
All the plugin interfaces defined in `avocado.core.plugin_interfaces`
ommit the "plugin" term, simply because this is already qualified in
the module name.
Let's also standardize the Varianter interface to "plugin-less" name.
---
Changes from v1 (#1841):
* Removed "plugin" suffix from docstring and docs references
> Varianter: drop "plugin" from interface name

- avocado/utils/iso9660.py
- avocado/utils/process.py
- examples/tests/doublefree.py
- selftests/functional/test_basic.py
- selftests/functional/test_interrupt.py
- selftests/functional/test_lv_utils.py
- selftests/unit/test_archive.py
- selftests/unit/test_utils_partition.py
- selftests/unit/test_utils_process.py
This is a follow up to #1838 .
We still have ways to go before we can say that macOS is a 2nd tier supported platform on avocado, but this at least makes the avocado selftests to work under that platform. More work is necessary to  make some APIs to fully work on macOS in a way that pleases different groups that use avocado.
I've removed the commit that adds OSX as a target on Travis CI because that is going to take more time and effort. The changes proposed are not hugely controversial and touch avocado APIs where the change was trivial.
Changes from V3:
* Addressed comments made by @apahim.
* Made what the deal is with macOS and `echo` more explicit and solved the problem in a better way.
Changes from V2:
* Fixed  `echo` find logic as pointed by @clebergnu.
Changes from V1 (RFC):
* …
> [V4] Make selftests to work with macOS

- avocado/core/exit_codes.py
- avocado/core/restclient/cli/app.py
- avocado/plugins/diff.py
- avocado/plugins/multiplex.py
- avocado/plugins/replay.py
- avocado/plugins/yaml_to_mux.py
- selftests/functional/test_multiplex.py
- selftests/functional/test_replay_basic.py
The definition of AVOCADO_JOB_FAIL was "Something went wrong with the
Job itself, by explicit avocado.core.exceptions.JobError exception",
while AVOCADO_FAIL is defined as "Something else went wrong and
avocado failed (or crashed). Commonly used on command line validation
errors".
With those in mind, I support that AVOCADO_JOB_FAIL should be slightly
adjusted (see changes in the diff), to include other types of
failures, but limited to job *execution* failures.  AVOCADO_FAIL is
already generic enough, so there's no need to change its definition.
This is important, IMHO, because users could quickly understand if a
job was executed, and failed, or if some earlier type of failure (such
as command line validation) happened.
With this updated definition, I spotted a few places where …
> Exit codes: review AVOCADO_JOB_FAIL and AVOCADO_FAIL usage

- selftests/cyclical_deps
The correct package name doesn't contain "python-"
> trivial: cyclical_deps: fix typo of install command

- avocado/core/dispatcher.py
And not `order()` as mentioned in the docstring.
> avocado/core/dispatcher.py: function `sorted()` is the one being used

- Makefile
- python-avocado.spec
- selftests/functional/test_basic.py
This is an incremental work to reduce the differences between downstream and upstream packages.
For now, the package is being renamed to be the same accross upstream and downstream.
> SPEC file: sync package name with downstream

- docs/source/Plugins.rst
Links to setuptools documentation were obsolete. So I updated them
Signed-off-by: Radek Duda <rduda@redhat.com>
> Corrected broken links in docs

- selftests/checkall
To make sure the seltests does not leave job results behind,
we introduced a check which compares the job-results directory
content from before the selftets with the content after the
selftests. But using `AVOCADO_SELF_CHECK=1 make check`, we
expect at least one extra result in the job-results directory,
making the content of the job-results to not be the same after
the tests.
This patch changes the avocado command used for self check
in `make check`, pointing the results to a temporary directory.
Reference: https://trello.com/c/y57xZSUS
> selftests: selfcheck with results in a tempdir

- docs/source/WritingTests.rst
Mention the behaviour of different skip forms regarding the tearDown().
Reference: https://trello.com/c/gsdBAmMY
> docs: tearDown() on test skip

- avocado/core/status.py
These were introduced when the throbber feedback was implemented,
and probably the idea was to give extra information in the UI.
This was never implemented, and no other internal component relies
on it, so let's remove it to avoid bitrot.
> avocado/core/status.py: feedback definition was never used

- avocado/plugins/plugins.py
- avocado/plugins/yaml_to_mux.py
That includes creating a new section for them, and also adding
name and description to the `yaml_to_mux` implementation.
> Varianter plugins: list them in `avocado plugins`

- README.rst
- docs/source/GetStartedGuide.rst
- docs/source/Introduction.rst
- docs/source/OtherResources.rst
- docs/source/index.rst
The README page has been left without updates for a while.  Now that we need to update the available package names felt like a good time to do a sync and face lift.
The idea for README is that it whould be nicely rendered (here on GitHub):
https://github.com/clebergnu/avocado/tree/readme_v2#avocado-test-framework
But also easy to read as a plain text file.
To prevent from further differences between the main documentation sources and the README file, a few notices have been left on the main documentation to remind developers to always sync the content (but try to keep README readable by not using advanced sphinx tags).
---
Changes from v1 (#1861):
* Mention the install method from Fedora repository
* Replaced notes about Debian to a proper section
> Updated README and Installation docs with new package names [v2]

- optional_plugins/robot/avocado_robot/__init__.py
- optional_plugins/robot/setup.py
v4:
- Make robot loader always registered along with default loaders.
- Fix discovery recursion.
- Fix `avocado list` results.
- Accept extra regex in the test reference the same way we accept in builtin loaders (`avocado list ~/Downloads/WebDemo/login_tests/:invalid_login.*Empty`)
v3: #1873 
- Handle `robot.run()` `stderr`.
- Handle `robot.run()` return code.
v2: #1869 
- Use `robot.run()` instead of robot command.
v1: #1868
> Robot Plugin [V4]

- optional_plugins/robot/avocado_robot/__init__.py
We have to consider that `avocado list` may be executed without the test
references.
> robot: fix issue on missing test references

- selftests/checkall
- selftests/cyclical_deps
Two backport of selftest related fixes, needed for a clean `make check` on my system (and possibly on every non-EL6/EL7 system out there).
> [LTS] backport selftest fixes

- avocado/__init__.py
In many cases when you are developing a test suite using
avocado libraries, you want to flag certain exceptional
conditions as real test failures, rather than something
that will be converted to an ERROR status (the current
default behavior).
Consider QEMU testing: An exception involving a QEMU core
dump should be considered a failure in pretty much every
scenario one can think of. So it makes sense to have code
similar to:
from avocado import TestFail
QEMUCoreDump(TestFail):
pass
so that when said exception happens inside library code,
the test can be immediately flagged as a failure, without
having to introduce boilerplate code to check for error
conditions.
So at least the 3 main test related exceptions (TestFail,
TestError and TestCancel) should be directly exposed in
the test writer …
> [RFC] Add TestFail, TestError and TestCancel to the avocado namespace

- avocado/utils/process.py
When the "sudo" is present in the PATH but is broken, the
"process.system" raises OSError. Let's address this issue and report
False in such case (as sudo is unusable)
> utils.process: Fix can_sudo on broken systems

- avocado/utils/lv_utils.py
Added '-y' to pvcreate since pvcreate asks for confirmation
if previous filesystem signature exists.
```
WARNING: ext4 signature detected on /dev/sdb at offset 1080. Wipe it? [y/n]: n
Aborted wiping of ext4.
1 existing signature left on the device.
Wiping ext4 signature on /dev/sdb.
Physical volume "/dev/sdb" successfully created.
```
> Added -y to pvcreate in lv_utils

- avocado/utils/memory.py
The write to /proc/sys/vm/drop_caches requires root, let's use the
`sudo` to allow the execution for non-root executions as well.
> utils: Use sudo to drop caches

- python-avocado.spec
This is the 2nd batch of changes to our (upstream) SPEC file, so that it better matches the downstream one.
The goal is to have similar user experiences with the downstream and upstream packages, while reducing developer overhead with new Avocado releases.
> SPEC downstream sync [2nd batch]

- avocado/core/dispatcher.py
- avocado/core/mux.py
- avocado/core/tree.py
- avocado/core/varianter.py
- avocado/plugins/yaml_to_mux.py
- docs/source/TestParameters.rst
- examples/mux-selftest.yaml
- selftests/unit/test_mux.py
This PR adds the support for the internal filters to the Mux. The basic idea is to define relations ({could be only used | could not be used} with other branch), which makes it a bit different from what we know from `--mux-filter-{only|out}`:
1. They are applied per complete variant (because the filters are compound of per-leaf-filters)
2. They don't remove/keep the nodes, but they only evaluate whether this resulting variant makes sense (whether it passes the filters)
Details are in the updated documentation.
v2: https://github.com/avocado-framework/avocado/pull/1885
Changes:
v3: Improved documentation
v3: Rebased
> mux: Add support for internal filters [v3]

- selftests/functional/test_argument_parsing.py
- selftests/functional/test_basic.py
- selftests/functional/test_canceltests.py
- selftests/functional/test_export_variables.py
- selftests/functional/test_gdb.py
- selftests/functional/test_interrupt.py
- selftests/functional/test_job_timeout.py
- selftests/functional/test_journal.py
- selftests/functional/test_loader.py
- selftests/functional/test_multiplex.py
- selftests/functional/test_output.py
- selftests/functional/test_output_check.py
- selftests/functional/test_plugin_diff.py
- selftests/functional/test_plugin_jobscripts.py
- selftests/functional/test_replay_basic.py
- selftests/functional/test_replay_external_runner.py
- selftests/functional/test_replay_failfast.py
- selftests/functional/test_skiptests.py
- selftests/functional/test_streams.py
- selftests/functional/test_sysinfo.py
- selftests/functional/test_teststmpdir.py
- selftests/functional/test_wrapper.py
- selftests/run_coverage
Currently the `selftests/run_coverage` only reports unit coverage. This
patch allows specifying custom `avocado` command in selftests and uses
it to run coverage to also include the functional tests to results.
v1: https://github.com/avocado-framework/avocado/pull/1867
Changes:
```yaml
v2: change "coverage rm ..." to "rm ..."
v2: rebased
```
> selftests: Improve code-coverage report [v2]

- avocado/core/loader.py
- avocado/core/safeloader.py
- docs/source/WritingTests.rst
- selftests/unit/test_safeloader.py
v2:
- Refactor/rename to optimize the safeloader functions to handle the docstrings.
- Docs about enable and disable in the same docstring.
v1: #1913
>  support multiple docstring directives [v2]

- avocado/utils/pci.py
Add a new function, which takes pci_address and pci_class as
i/P and returns corresponding pci_interface
Signed-off-by: Venkat R B <vrbagal1@linux.vnet.ibm.com>
> utils: Add "get_interfaces_in_pci_address" method to pci.py

- Makefile
- python-avocado.spec
Downstream (Fedora and EPEL) RPM packages have had a different way
of building release (by default) and snapshot packages by editing
the SPEC file.
Let's sync with them, while also allowing snapshot packages to be
built from our usual `make rpm` command.  Release builds are still
supported with `make rpm-release`.
> SPEC file: sync how we build snapshot and release packages

- avocado/core/data_dir.py
- avocado/plugins/teststmpdir.py
- docs/source/ReferenceGuide.rst
- selftests/check_tmp_dirs
- selftests/functional/test_teststmpdir.py
- selftests/functional/test_unittest_compat.py
- selftests/run
- selftests/unit/test_job.py
I double (triple) checked the `post_tests` hook is guaranteed (with documented exceptions) to be executed when `pre_tests` hook was. This adds the documentation regarding this and another commit to avoid unnecessary protection using `__del__` in one of the `post_tests` plugin.
v1: https://github.com/avocado-framework/avocado/pull/1829
Changes:
```yaml
v2: rebased
v2: changed the commit message of the "REMOVEME" commit (which is to be included now)
```
> Pre/post tests documentation and related cleanup [v2]

- avocado/plugins/jsonresult.py
- avocado/plugins/xunit.py
- selftests/functional/test_output.py
v2:
- Test results files (non)creation instead of the avocado command (non)stdout.
v1: #1923
> fix output on unknown tests [V2]

- python-avocado.spec
Commit 7a249b7 removed files that were intended to be packaged in the
optional plugin packages.  By doing so, they ended up in the main
package.
This fixes that issue, and puts both the directories with the
package and module name (which differ) into each optional plugin
package file listing.
> python-avocado.spec: fix excluded files for optional plugin packages

- avocado/core/mux.py
- avocado/core/tree.py
- selftests/functional/test_multiplex.py
- selftests/unit/test_mux.py
This PR changes the serial-id-based variant_ids with id based on leaf names and hash of their contents. This is a reworked (and improved) version of https://github.com/avocado-framework/avocado/pull/1591 which also supports the debug mode.
Sample output is:
```
$ avocado run passtest.py -m examples/mux-environment.yaml 
JOB ID     : 1a68bf76137bde5f64fe3f8fc9d0b0b502edc7a8
JOB LOG    : /home/medic/avocado/job-results/job-2017-04-12T11.30-1a68bf7/job.log
(01/24) passtest.py:PassTest.test;fedora-debug-intel-scsi-88ab: PASS (0.01 s)
(02/24) passtest.py:PassTest.test;fedora-prod-intel-scsi-2d69: PASS (0.01 s)
...
```
compare to the old:
```
$ avocado run passtest.py -m examples/mux-environment.yaml 
JOB ID     : 140e93e43a595ee8e7681891bd2cbc101b92d77a
JOB LOG    : …
```
> Mux: Improve the generation of Variant-IDs

- avocado/core/loader.py
- selftests/functional/test_basic.py
The MissingTest is yielded by TestLoaderProxy, but it was implemented
and described in FileLoader, which caused troubles when FileLoader was
not being used. This simple fix allows TestLoaderProxy to define basic
mappings and adds MissingTest to it.
v1: https://github.com/avocado-framework/avocado/pull/1920
v2: https://github.com/avocado-framework/avocado/pull/1926
v3: https://github.com/avocado-framework/avocado/pull/1933
Changes:
```yaml
v2: Use different approach as this is a bugfix and the correct fix will be introduced later
v3: Rework the lazy-init to normal init on `load_plugins`
v3: Add selftest
v4: Add new commit to fix uncovered branch making FileLoader to crash
v4: Move the update_mappings to a different function to improve readability
v4: Remove unnecessary accidental change in …
```
> Loader: Move MissingTest mapping to TestLoaderProxy [v4]

- avocado/core/loader.py
The option "--loaders" accepts either loader plugin or plugin followed
by test type. Listing both at the same time was a bit confusing so this
patch lists them per-plugin.
> loader: Distinguish between loader plugins and types

- etc/avocado/avocado.conf
- python-avocado.spec
Avocado's "data_dir" has always been meant for readable **and** writable
content.
Right now, this is broken because the system wide default for
"base_dir" (data_dir's parent) is set to /usr/share/avocado, and
consequently, "data_dir" is set to /usr/share/avocado/data.
Let's use "/var/lib/avocado" for the "base_dir", and
"/var/lib/avocado/data" for the "data_dir".  Content intended to be
read-only, such as example tests and wrappers, are still set to
/usr/share/avocado.
This has been tested with Avocado-VT, making the result of system
wide content, such as test providers and downloadable files be
put under "/var/lib/avocado/data/avocado-vt".
Reference: https://trello.com/c/KU1DvSAz
> data_dir: use a directory intended for writable content

- selftests/functional/test_basic.py
- selftests/functional/test_loader.py
As it has already been done to some other tests, two other tests have
been producing false positives.  This has been observed recently in
package builds in build farms.
Let's run them only when `make check-full` is called, which is
usually done at dedicated machines with plenty of resources.
Reference: https://kojipkgs.fedoraproject.org/work/tasks/9189/19059189/build.log
Reference: https://kojipkgs.fedoraproject.org/work/tasks/9445/19069445/build.log
---
Changes from v1 (#1930):
- Shortened 1st line of commit message
- Added second test, which is failing on the same conditions
> selftests: mark some tests as time sensitive [v2]

- avocado/utils/archive.py
When one extracts a zip file with symlinks multiple times, the symlinks
are not replaced by the `extractall`, which results in our
`_update_zip_extra_attrs` workaround to try to create a symlink to the
content of the file, rather than to the destination. This patch checks
whether the link already exists, removes it and refresh it from the
zipfile.
> utils.archive: Skip extra treatment of existing symlinks

- avocado/core/data_dir.py
- avocado/core/exceptions.py
- avocado/core/tree.py
- examples/testplans/release.json
- optional_plugins/html/avocado_result_html/__init__.py
- selftests/functional/test_basic.py
- selftests/unit/test_mux.py
- spell.ignore
there are few fixes found while running pre-release checks.
> Pre-release fixes

- optional_plugins/resultsdb/avocado_resultsdb/__init__.py
The ResultsDB expects the Testcase, not the Test ID. Even so, the
Testcase can be considered the combination of the test name plus the
variant.
While on this, this patch adds the parameters information to the
ResultsDB 'data' section.
> resultsdb: include information about variants

- man/avocado.rst
With the resultdb optional plugin new arguments were added which are
missing in our man pages.
> man: Add resultsdb options

- docs/source/optional_plugins/index.rst
- docs/source/optional_plugins/robot.rst
Robot plugin was introduced without documentation. This PR adds the
basic information about the Robot plugin.
---
Changes from v1 (#1949):
* Rebased
* Drop `.rst` suffix from `results` section item
> docs: add robot plugin information [v2]

- avocado/utils/multipath.py
Test which are using this utility are failing as they start using
multipath as soon as services are re-satrted. But multipath need
some time to load the services completely. So to load the
multipaths properly we need to give some sleep time which resolve
the issue
> Added a sleep time after starting multipath services in multipath.py

- avocado/utils/pci.py
Given the PCI address, function will return corresponding
PCI Class name
Signed-off-by: Venkat R B <vrbagal1@linux.vnet.ibm.com>
> utils: Add "get_pci_class_name" method to pci.py

- avocado/utils/pci.py
When there is no device associated to given pci_address the error
message is a bit misleading. Let's report a better one.
> utils: Improve error message of pci.get_pci_class_name

- optional_plugins/html/avocado_result_html/__init__.py
- optional_plugins/html/avocado_result_html/resources/templates/report.mustache
- Include `Params` as a test name tooltip.
- Split Test ID in UID, Test Name and Variant, so users can order by any of them individually.
> html report: include params and split Test ID

- avocado/core/decorators.py
- avocado/core/exceptions.py
- avocado/core/loader.py
- avocado/core/test.py
- selftests/functional/test_basic.py
- selftests/unit/test_test.py
Due to the deprecation of the self.skip(), the availability of the skip
decorators and the new CANCEL status, some internal improvements are
important to keep our behaviour sane and our own code sound and clean.
- The test.SkipTest class was renamed to test.MockingTest to be even more
generic, intending to be overridden by sub-classes that make the test
to end both with SKIP or CANCEL status. To keep it generic,
test.MockingTest class will not SKIP the test if used directly anymore.
- The test.TimeOutSkipTest and test.ReplaySkipTest classes now are using
the skip decorators instead of raising an exception in setUp(), since
'skipping' the test means 'don't execute anything', not even the
setUp().
- The test.DryRunTest class, which is expected to log itself in setUp()
and then abort the …
> Skip internal improvements [v3]

- avocado/utils/astring.py
- selftests/unit/test_astring.py
The "astring.string_safe_encode" is a method, which tries to encode the
string no-matter how wrong it is. Let's also allow broken corrupted
strings by using "ignore" to skip the corrupted chars.
v1: https://github.com/avocado-framework/avocado/pull/1901
Changes:
```yaml
v2: Improved selftest to contain incorrect characters
v2: Use "replace" rather than "ignore" to emphasize there was something ugly
```
> utils.astring: Be really lenient towards incorrect strings [v2]

- docs/source/GetStartedGuide.rst
- docs/source/index.rst
- docs/source/optional_plugins/index.rst
- docs/source/rfcs/LongTermStability.rst
- docs/source/rfcs/index.rst
We have been speaking for a while about adding discussed **and accepted** RFCs to the main documentation, for reference (and cross reference).
This adds a section holder and the current version (v5) of the LTS RFC, as posted on the mailing list:
https://www.redhat.com/archives/avocado-devel/2017-April/msg00050.html
If that doesn't raise any other points, and is considered accepted, then we can merge this PR.
---
Changes from v1 (#1963):
* Updated Long Term Stability RFC to version 5
> Docs: add section on RFCs (and LTS RFC version 5) [v2]

- selftests/functional/test_multiplex.py
- selftests/functional/test_plugin_diff.py
- selftests/functional/test_replay_basic.py
- selftests/functional/test_replay_external_runner.py
- selftests/functional/test_replay_failfast.py
- selftests/functional/test_teststmpdir.py
- selftests/unit/test_remote.py
- selftests/unit/test_utils_stacktrace.py
- selftests/unit/test_vm.py
Previous commit d5fd51c attempted to remove all shebangs, as a result
of 143b574 that remove the executable bit of all tests.
There are still a few left, so this let's clean them up.
> selftests: remove python shebangs

- avocado/core/runner.py
- selftests/functional/test_basic.py
- selftests/functional/test_job_timeout.py
This PR fixes a little issue regarding postprocess failure message and increases the test postprocess timeouts to empirically set hardcoded values. The diff is a bit more complex as it has to deal with the UI, because longer timeouts without updating the UI would be confusing to users.
v1: https://github.com/avocado-framework/avocado/pull/1929
Changes
```yaml
v2: Use constants rather than hardcoded values
v2: Improve docstring
v2: Tweak the selftest timeout
```
> runner: Increase the test postprocess timeout [v2]

- avocado/core/mux.py
Now that the variant IDs are not a sequential number, we need this extra
information so users can easily know how many variants were generated.
Reference: https://trello.com/c/N7pB9E4O
> mux: show total number of variants

- avocado/plugins/multiplex.py
- avocado/plugins/variants.py
- avocado/plugins/yaml_to_mux.py
- docs/source/Configuration.rst
- docs/source/ReferenceGuide.rst
- docs/source/Replay.rst
- docs/source/TestParameters.rst
- docs/source/WritingTests.rst
- selftests/functional/test_multiplex.py
- setup.py
The "avocado multiplex" command is misleading as multiplexation is only
the generic concept used by one of our varianter plugins
implementations. Let's change the command name to "avocado variants"
which better reflects what is it used for.
As people depend on "avocado multiplex" command let's keep both of them
for now to give people time till Avocado 52.0 to migrate.
v1: https://github.com/avocado-framework/avocado/pull/1936
Changes:
```yaml
v2: Fix `avocado multiplex` mentions in documentation
v2: New commit to fix the `multiplex` word usage in documentation
v2: Fix the deprecation message
```
Not changed:
```yaml
v2: VARIANTS_FILENAME = 'multiplex' # it would break backward compatibility, we should do it once we implement a proper serialization
```
> variants: Introduce "avocado variants" command [v2]

- avocado/utils/distro.py
- avocado/utils/software_manager.py
This is essentially a name change for the Red Hat Enteprise Linux probe, with a few fixes.  This is the foundation of a proposal for Avocado-VT that will create a `host-os.cfg` at `avocado vt-bootstrap` execution time.
This change may cause disruption for tests that rely on the `redhat` name.  A separate PR for avocado-mist-tests, our largest source of tests, accompany this one:
https://github.com/avocado-framework-tests/avocado-misc-tests/pull/468
> Distro Detection: use "rhel" for Red Hat Enterprise Linux

- avocado/core/loader.py
- docs/source/WritingTests.rst
- selftests/unit/test_loader.py
V1: #1972
- Refactor `loader._find_avocado_tests()` to reduce code repetition.
- Add support for tags in test methods:
- Tags are now related to the method and not to the class.
- Methods will inherit the tags from the class.
V2:
- Use an ordered structure to keep the methods in the order that they are discovered in.
- Include a selftest to make sure the order is maintained.
>  Support tags in test methods [v2]

- contrib/testsuites/run-kvm-unit-test.sh
support configuring kvm-unit-test with supported arguments for enabling tests to
run in PowerPC.
Signed-off-by: Balamuruhan S <bala24@linux.vnet.ibm.com>
> run-kvm-unit-test.sh [Version 2]: enable options for configuring kvm-unit-tests

- avocado/core/job.py
- avocado/core/jobdata.py
- avocado/plugins/replay.py
- avocado/plugins/tap.py
- docs/source/Replay.rst
- selftests/unit/test_replay.py
This PR fixes the way we get info about not-executed-tests from "results.json" and then adds support to resume job by using `--replay-resume` argument. This is basically just a symlink to `--replay-test-status INTERRUPTED` and it can be also combined with other statuses. The only drawback could be when the "results.json" is not yet available (host crash, kill -9, ...) the "results.tap" is used and it does not support all test statuses and for the replay purpose it maps all failures to ERRORs.
v1: https://github.com/avocado-framework/avocado/pull/1942
v2: https://github.com/avocado-framework/avocado/pull/1958
v3: https://github.com/avocado-framework/avocado/pull/1976
Changes:
```yaml
v2: Add documentation
v2: Add commit to always sync basic job-related data on disk
v3: Remove shebang from …
```
> replay: Add support to resume interrupted/crashed job [v4] 

- avocado/core/output.py
The recently added CANCEL color is not cleaned when we disable TERM
support.
> output: Disable CANCEL color on unsupported terms

- avocado/utils/cpu.py
Added a new item for vendors_map dic to def get_cpu_vendor_name():
Signed-off-by: Venkat R B <vrbagal1@linux.vnet.ibm.com>
> Extended vendors_map dict for Power8

- selftests/functional/test_teststmpdir.py
The tests seems to be stable after the series of improvements applied to
our selftests procedures. Time to restore this check in travis.
> Remove skip from teststmpdir functional test

- README.rst
- avocado/core/job.py
- avocado/core/runner.py
- avocado/plugins/human.py
- avocado/plugins/run.py
- docs/source/GetStartedGuide.rst
- docs/source/Replay.rst
- docs/source/ResultFormats.rst
- docs/source/RunningTestsRemotely.rst
- docs/source/WritingTests.rst
- man/avocado.rst
- selftests/functional/test_interrupt.py
- selftests/unit/test_job.py
- setup.py
This is the last changes to deliver the so called "Job time should be wall clock time".
It introduces necessary fixes to the location of Pre/Post Job plugins execution, followed by Job time accounting, and the human interface addition itself. 
**This change impacts Avocado-VT**.  Related PR:  https://github.com/avocado-framework/avocado-vt/pull/1003
---
Changes from v3 (#1988):
* `JobPreDispatcher` needed to be created before the introduced try/finally block
Changes from v2 (#1973):
* Protect the execution of "post" by encapsulating them inside a try/finally block
* Used a different job elapsed time to prove Avocado is not calculating it when start or finish time is manually set
* Enabled tests previously skipped by using the data dir tmp tracker, and setting each job result to those …
> Pre/Post Job changes and Job Time Accounting (aka "Job time should be wall clock time") [v4]

- .travis.yml
- Makefile
- python-avocado.spec
- selftests/functional/test_basic.py
- selftests/functional/test_interrupt.py
- selftests/functional/test_loader.py
- selftests/functional/test_utils.py
- selftests/run_coverage
A finer level of granularity may help to extend our testing coverage while reducing the amount of false positives.  Also, one (somewhat related) packaging fixes was squeezed in here.
**There should be changes on tests run on current environments**, besides the explicit move into level 1 on the second-last commit.
---
Changes from v2 (#1991):
* Ommit `make check-extended` target
Changes from v1 (#1968):
* Made the `AVOCADO_CHECK_LEVEL=0` implicit on Makefile `check` target
* Moved `InterruptTest.test_well_behaved` into level 1
* Removed the trailing `*` from the avocado data dir.
> Selftests: introduce multiple test levels [v3]

- spell.ignore
Only one spell fix for this version.
> spell: v50 fix

- optional_plugins/html/avocado_result_html/__init__.py
Generate the html report even if `state['params']` is not available.
> html: ignore missing params

- Makefile
Make clean is missing the egg directories. This patch includes in make
clean a command to remove them.
Reference: https://trello.com/c/VgF0fkEa
> Makefile: remove 'egg' directories on make clean

- Makefile
When switching between 36lts and master branch, content from 36lts
(the .egg-info dir) may be kept.  The reason for that is that 36lts
used "avocado" as the module name, and thus produces
"avocado.egg-info" dir.
> Makefile: also remove 36lts "egg-info" dir

- avocado/core/exceptions.py
- avocado/core/loader.py
- avocado/core/output.py
- avocado/core/test.py
- optional_plugins/robot/avocado_robot/__init__.py
- selftests/unit/test_loader.py
Hello guys, this PR is suppose to clear a bit the verbose loaders and should demonstrate how to make useful info to people using avocado. The idea is to not change anything for normal execution, but to report more info in verbose execution, which should help people to analyze what went wrong. Currently the only information is test type (or failure type) followed by test-reference. In this PR I'm replacing the test-reference with additional information. There is a related PR https://github.com/avocado-framework/avocado-vt/pull/1018 which adds similar info for Avocado-vt so I recommend checking the results while using both.
I also experimented with using Exception to report failures. It was better to distinguish between correct and incorrect discoveries and it made sure to report all the …
> Loader failures

- avocado/core/job.py
- avocado/core/loader.py
- avocado/plugins/replay.py
- avocado/plugins/run.py
- docs/source/GetStartedGuide.rst
- selftests/functional/test_basic.py
v2:
- Add docstring.
- Rename option to `--ignore-missing-references`
- Add selftest with all references missing.
v1: #2012
> Be lenient with test references

- selftests/run
We used to use increased verbosity to get name of the test which left
tmp dirs behind, but it is not necessary. This commit decreases the
verbosity and only logs the error as well as test name in case this
failure is detected.
> selftests: Decrease the verbosity

- requirements-selftests.txt
- requirements.txt
- setup.py
The current requirement set for the stevedore library doing build/use
of Avocado doesn't actually reflect the minimum version needed.
The proof is that Avocado on EL7, when installed from packages, will
run just fine with 0.14, the version that ships on that distro.
Without this change, package builds on EL7 attempt to download a newer
(Python) module:
Processing dependencies for avocado-framework==50.0
Searching for stevedore>=1.8.0
Reading https://pypi.python.org/simple/stevedore/
Best match: stevedore 1.21.0
Downloading  https://pypi.python.org/[...]/stevedore-1.21.0.tar.gz[...]
With this change, no download is attempted:
Processing dependencies for avocado-framework==50.0
Searching for stevedore==0.14
Best match: stevedore 0.14
Adding stevedore 0.14 to easy-install.pth file
Using …
> Lower stevedore version requirement

- python-avocado.spec
This change may help to quickly read the conditionals.  It's
already been applied on Fedora packages, so let's sync it here.
Also added here is some small comment section changes (mostly
capitalization), again to sync with downstream.
CC: Lukáš Doktor <ldoktor@redhat.com>
> SPEC file: visual aid for conditionals by means of indentation

- avocado/utils/cpu.py
Added method to get total,online cpus count and
made pylint happy with few minor fixes.
> Added methods to get total,online cpus count and few pylint fixes

- .travis.yml
Let's enable the AVOCADO_LOG_DEBUG to get the details about exceptions
in our selftests as we don't have access to the produced traceback files
after the job is finished.
> travis: Enable AVOCADO_LOG_DEBUG

- Makefile
Similar to make link, the requirements-plugins target walks through
the plugins and install dependencies.
It checks if the plugin has either:
* A Makefile
* A requirements.txt file
https://trello.com/c/R9rxte6o/608-add-make-requirements-plugins
Signed-off-by: Greeshma Gopinath <ggopinat@redhat.com>
---
Changes from v4 (#2001):
* Do not run `setup.py develop`, only satisfy requirements from `requirements.txt` (or Makefile)
Changes from v3 (#1866):
* Fixed pip invocation (was calling with an additional dir)
* Broke into Makefile *or* setup.py+requirements.txt conditional
> Makefile: add requirements-plugins target [v5]

- selftests/functional/test_basic.py
- selftests/functional/test_loader.py
Since too may reports of false positives have been generated during
RPM package builds, let's move all test sensitive tests into level 1.
This means that those tests will not be run on RPM package builds, but
will continue to run on Travis-CI.
> selftests: move time sensitive tests into level 1

- avocado/core/dispatcher.py
- avocado/core/mux.py
- avocado/core/output.py
- avocado/core/settings.py
- selftests/functional/test_loader.py
- selftests/functional/test_lv_utils.py
This is yet another round of Python 3 compatibility patches.  At this point:
* `avocado` runs, not all plugins work correctly
* `python3 setup.py test` also runs, but of course, there are many failures.  It looks like most of the failures are related to byte/string issues
To test this, please run `python3 setup.py develop --user` before trials
**Note: the name of this PR is a bit misleading now, since plugins are loaded, but was kept to be consistent across versions**
---
Changes from v1 (#2025):
* Plugin should be *enabled* if not on a disabled list (or entry, config file, etc, doesn't exist)
> Py3k support: `avocado` runs (no plugins) and tests run (many failures) [v2]

- avocado/utils/memory.py
Added a function to get the linux page size for the given
kernel, it returns a byte value from 'getconf PAGESIZE'
command.
systems can have 4k, 64k page sizes, accordingly decide to
start a memory tests.
> utils/memory.py : function to get the linux page size

- avocado/core/runner.py
When the test does not produces the early_status in 60s or when the test
pushes the final status and not exits we SIGKILL the test, leaving us
with no trace on where it might hang. Let's use SIGTERM first and wait
for 1s to see whether the process won't be able to give us traceback,
otherwise nuke it with SIGKILL as before.
>  runner: Try to interrupt test gently first

- avocado/core/safeloader.py
- docs/source/ReferenceGuide.rst
- docs/source/WritingTests.rst
- selftests/unit/test_safeloader.py
The format of the docstring directives has not been formally described
so far.  Because at least two different features are built on that,
and possibly more will come, it's a good idea to define a format.
This introduces a stricter format, basically adding a number of
requirements or rules.  To make the following description more
consistent let's call the ":avocado:" part of the docstring directive
"the marker" and what follows it the "content".
1) One or more spaces are required between the ":avocado:" marker and
the content.  The following is a valid docstring directive:
":avocado: enable"
While this is invalid:
":avocado:enable"
2) A more limited set of characters are now allowed in the content,
namely one from the following set: [a-zA-Z0-9_:,=].  The following
is a valid docstring …
> docstring directives: define more formal and strict format

- avocado/plugins/list.py
- docs/source/GetStartedGuide.rst
- docs/source/WritingTests.rst
- man/avocado.rst
- selftests/functional/test_basic.py
This shows tags (and statistics) when `avocado list` is called with `--verbose`.
---
Changes from v1 (#2033):
* Added a functional selftest
> `avocado list`: show tags in verbose mode [v2]

- selftests/functional/test_loader.py
This patch adds the missing definition of `MODE_0644` in
`LoaderTestFunctional` class.
> fix loader selftest

- selftests/checkall
For couple of weeks the `inspekt lint` produces unwanted `Your code has
been rated at 10.00/10 (previous run: 10.00/10, +0.00)` messages
polluting the log too much for me to bear. I tried to remove those
messages, but so far I haven't found a solution, so let's just silence
it unless there is a lint failure.
> selftests: Silence `inspekt lint` unless there is an error

- avocado/core/job.py
- avocado/core/runner.py
- avocado/plugins/run.py
- docs/source/TestParameters.rst
- man/avocado.rst
- optional_plugins/runner_remote/avocado_runner_remote/__init__.py
- selftests/functional/test_multiplex.py
The suite order means the order in which the variants will be applied to
tests. Right now we run all variants of first test, then the same for
the second, third, ... tests. The new option "--suite-order" allows to
alternatively specify "tests-per-variant" mode where we run first
variant of all tests, then second variant, third, ...
v1: https://github.com/avocado-framework/avocado/pull/2031
Changes:
```yaml
v2: Raise exception on incorrect order
v2: Change --suite-order to --executon-order and improve help related message
```
Not changed:
```yaml
v2: I keep using None as default as it's a new argument so it makes sense to default
from None which is by default supplied in standalone execution and many selftests.
```
> runner: Allow to specify suite order [v2]

- selftests/run
We rely on garbage collector to run __del__s before we check all tmpdirs
were cleaned. Let's force-run gc.collect() and (just to be sure) run
sync.
> selftests: Avoid false-negative tmpdir check failures

- avocado/core/loader.py
- docs/source/WritingTests.rst
- selftests/unit/test_loader.py
v4:
- Docs adjustments to match the current behavior.
- Split commit which handles the `path` when it's a directory.
v3: #2060 
- Remove commit to order test classes.
- Add parents methods to the child class (instead of add parents classes with their methods).
- In consequence of the previous item, remove the commit adding the path information to the internal 'info' structure.
- Squash the 2 remaining commits since they are related to the same functionality.
v2: #2053 
- `:avocado: disable` works as usual, and in this v2 it has no effect in a recursive discovery.
- Improved docs, addressing v1 comments.
v1: #2052 
- Recursion, when engaged (using `:avocado: recursive`), will discover all parents up to the base class.
- `:avocado: enable` works as usual, but it's not needed in a recursive …
> Recursive Test Discovery [V4]

- avocado/utils/cpu.py
Added support for POWER9 cpu arch identification
> Added support for POWER9 cpu arch identification

- avocado/core/loader.py
Currently when the target file does not exists the FileLoader reports:
"Does not look like an INSTRUMENTED test, nor is it executable" which
can be a bit misleading. Let's change it to: "File not found
($locations)".
v1: https://github.com/avocado-framework/avocado/pull/2036
Changes:
```
v2: Rebased and remove the accidental `etc` changes
```
> loader: Improve message when file does not exists [v2]

- avocado/core/jobdata.py
- avocado/core/tree.py
- avocado/core/varianter.py
- avocado/plugins/replay.py
- selftests/functional/test_replay_basic.py
Currently we use pickle to store args and variants, which does not scale between versions and is also insecure as one can sneak-in malicious code. In this PR I'm using json to serialize the data while using None to store insecure content in args and I added a method to safely serialize variants and again using json to store them. For variants there is potential loss of information as it can contain insecure objects which are turned to strings and also I'm not storing the full state, only simplified produced variants representation which is safe and from AvocadoParams point of view represents the status.
Note: as a consequence it's now possible to re-run/diff jobs without the varianter plugins (or with different ones as they are not used to produce the variants anyway).
v1: …
> jobdata: Store only data, not data+code [v2]

- avocado/plugins/plugins.py
Let's include an empty line between the plugin categories, so it's
easier to distinguish between different plugin types.
> Plugin listing: improve readability

- docs/source/Loaders.rst
v3:
- Addressed the comments from V2.
v2: #2075 
- Move the text to the `Loaders.rst`.
- Include detail the information, limiting the regex usage to the FileLoader/INSTRUMENTED.
- Include `External Loader` information.
v1: #2068 
Let's add some extra information and some examples about the test
references.
> docs: improve the docs regarding the test references [v3]

- etc/avocado/avocado.conf
Currently there are two types of plugin names, one is the fully
qualified plugin name, which is the namespace used by stevedore and the
other is the module name, which is the module which handles the code.
It's probably too late to adjust the behavior, but let's at least
provide correct examples to simplify the usage.
> etc: Correct plugin names in avocado.conf

- avocado/core/runner.py
- docs/source/ReferenceGuide.rst
- docs/source/WritingTests.rst
- examples/tests/test_env.py
Each test executed in Avocado gets its own process. But, there are a
few peculiarities that test writers may have to deal with, so let's
document those.
---
Changes from v2 (#2092):
* Add missing word (want)
* Rebased
Changes from v1 (#2078):
* Note that the behavior of fd 1 and 2 will be addressed in a future version
* Removed item about `SIGTSTOP`
* Addition of item about environment variables
* New commit: fixes for the "Environment Variables for Simple Tests" section
* New file: ``test_env.py``, with an example test that users can run to show (most of) the documented information
> Docs: document the test process environment [v3]

- avocado/core/mux.py
- avocado/core/varianter.py
The `avocado variants` without any variants reports nothing at all, which is not actually what it looks like during `avocado run`. On `avocado run` default params are supplied as a `None` variant. Let's duplicate this behavior on `avocado variants` as well.
While on it I noticed that the `--system-wide` is broken, because of a wrong variable name. Fix is included in this PR.
v1: https://github.com/avocado-framework/avocado/pull/2087
Changes
```yaml
v2: Force variant-id to "" instead of None when no variant available
```
> Fix "avocado variants" with no variants and the "--system-wide" argument [v2]

- optional_plugins/html/avocado_result_html/__init__.py
All other result plugins write (by default) to the job results dir.
The HTML plugin was different because it used to require a number of
files.  Now, it's a single file, and thus, could/should live in the
same place as other files.
To ease the transition of the location, let's add a symlink, so that
users can still rely on the old location.
--
Changes from v1 (#2100):
* Write the file at `$job_resutls_dir/results.html` and link at `$job_results_dir/html/results.html`
> HTML: write report in the same location other results live [v2]

- avocado/plugins/replay.py
- avocado/plugins/run.py
Some adjusts are needed in order to have `--execution-order` properly working with `replay`.
The commits here were cherry-picked from PR #2099.
> Fix replay `--execution-order`

- avocado/utils/cpu.py
_get_cpu_status(), online() and offline() functions will used in
mulitple places, so adding it to cpu library.
this will be used in cpu tests of avocado-misc-tests
> [POST_LTS] utils/cpu.py: functions for cpu off, on and check status

- python-avocado.spec
There's now python-aexpect packages on EL7, so we should
be using it.
> python-avocado.spec: fix python-aexpect depedency on EL7

- avocado/core/app.py
When trying out Avocado installations, I wanted to silence the plugin
errors that I knew would fail to load.  I chose to do that by running
a command such as:
$ avocado --config=silent_plugins.conf run passtest.py
But it did not behave as expected.  The reason is that plugins are
loaded first, and then the parsing of command line (with additional
parsing of config files) is done.  Let's parse the command line
earlier then.
> Broken plugin notification: fix behavior with additional config files

- avocado/plugins/list.py
- avocado/plugins/run.py
It looks like the tags mechanism has a lot of potential to be used
very often, so a long command line option seems to much typing.
Let's add `-t` (for *t*ags), to allow users to run commands which
are much nicer to type, such as:
$ avocado run . -t BZ12345678
> Tags: add short command line option for `--filter-by-tags`

- optional_plugins/html/avocado_result_html/__init__.py
The location of the HTML report was moved from
`$RESULTS/html/results.html` to `$RESULTS/results.html`, while a link
was left on the first location.
We don't have to carry that compatibility link anymore.
> HTML report: remove legacy symlink

- avocado/core/jobdata.py
This file is a legacy compatibility that now, after another LTS release
can be removed.
> jobdata: remove legacy `urls` link to `test_references`

- avocado/plugins/replay.py
The replay plugin checks for `remote` execution, which requires remote
runner to be installed. Let's avoid crash by supplying default on
missing attribute.
Resolves issue: https://github.com/avocado-framework/avocado/issues/2116
> replay: Avoid crash when remote runner not installed

- avocado/plugins/list.py
All test loaders now return the test name as a value under the first
level test class parameters.  Let's drop the legacy code that used
to check at the test parameters "id" key and the test class parameter
"path" key.
This has also been tested with external loaders such as Avocado-VT
and Avocado-Virt.
> List plugin: always use the test class parameter "name"

- avocado/core/test.py
- examples/tests/synctest.py
- examples/tests/trinity.py
Most of the LazyProperty variables in Test are actually always read on
"get_state" and other occasions so it does not make sense to set it
Lazily.
Also protect the remaining lazily initialized property from overriding
by using @property instead of our custom LazyProperty, which is not
really a property.
This commit requires some adjustments to nasty example tests which used
to override self.srcdir, which is not allowed (and restricted since this
commit).
> test: Remove unnecessary LazyProperty from Test class

- avocado/core/loader.py
- avocado/core/mux.py
- avocado/core/runner.py
- avocado/core/varianter.py
- docs/source/optional_plugins/varianter_yaml_to_mux.rst
- examples/yaml_to_mux_loader/advanced.yaml
- examples/yaml_to_mux_loader/basic.yaml
- examples/yaml_to_mux_loader/loaders.yaml
- optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py
- selftests/functional/test_loader.py
this attempts to solve our long-outstanding inability of assign variants to only some of the tests in the testsuite. It adds a new loader (for demonstration purpose bundled with the optional yaml_to_mux varianter plugin, but the location might change) which goes through a YAML file, allows the same syntax as `yaml_to_mux` but instead of just producing variants it looks for `test_reference` key per each variant. If available it attempts to discover the test using the provided loader (or FileLoader when none) and it associates the __current__ variant/params to that test. This is then passed to the runner and executed with the params filled by the loader (not the varianter).
You can test this by running:
$ avocado run examples/yaml_to_mux_loader/basic.yaml
v1: …
> Yaml testsuite loader [v2]

- avocado/utils/archive.py
On python3 this naked open reports ResourceWarning. Let's properly close
it:
```
python3 unit/test_archive.py 
.........../home/medic/Work/Projekty/avocado/avocado/build/lib/avocado/utils/archive.py:191: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/avocado___main__rv2ihor0/tmp0drzyrsb/dir/link_to_link_to_file2' mode='r' encoding='UTF-8'>
src = open(dst, 'r').read()
/home/medic/Work/Projekty/avocado/avocado/build/lib/avocado/utils/archive.py:191: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/avocado___main__rv2ihor0/tmp0drzyrsb/dir/2nd_link_to_file' mode='r' encoding='UTF-8'>
src = open(dst, 'r').read()
/home/medic/Work/Projekty/avocado/avocado/build/lib/avocado/utils/archive.py:191: ResourceWarning: unclosed file <_io.TextIOWrapper …
```
> utils.archive: Properly close the opened file

- avocado/core/varianter.py
- selftests/functional/test_basic.py
- selftests/functional/test_multiplex.py
When no variants are provided Avocado sets the default variant, but
instead of list of mux paths it created just string "/run", which
processed into ["/", "r", "u", "n"]. Let's fix this by setting list.
Also the proper mux_path should be `/run/*` in order to include all
children nodes of the "/run".
> varianter: Fix mux_path on no-variants

- avocado/core/test.py
- selftests/functional/test_basic.py
The fail_reason is the instance of the actual exception. We do store it
only as string in case of old-type exception, but even new style
exceptions might be not available when sys.path is different causing
unpickle on runner part impossible.
> test: Store fail_reason only as string

- avocado/core/output.py
- avocado/core/runner.py
- optional_plugins/robot/avocado_robot/__init__.py
- optional_plugins/runner_remote/avocado_runner_remote/__init__.py
- selftests/functional/test_output.py
This patch set fixes a bit the test's (runner's) logging setup and makes sure `sys.stdout` calls are properly forwarded with "[stdout] " prefix to `avocado.test` (job.log) and without any prefix to `avocado.test.stdout` (`test_result/stdout`).
v1: https://github.com/avocado-framework/avocado/pull/2132
Changes:
```yaml
v2: Fixed typos/language
v2: Remove the possibility to add single log name (instead of list)
```
> runner: Prefix sys.stdout|err output in test log with [stdout|stderr]

- python-avocado.spec
shortcommit is supposed to contain the 8 first characters instead of 7.
> spec: fix shortcommit

- avocado/core/test.py
- avocado/plugins/diff.py
- avocado/plugins/xunit.py
- avocado/utils/data_structures.py
- avocado/utils/filelock.py
- examples/tests/gdbtest.py
- selftests/functional/test_argument_parsing.py
- selftests/functional/test_basic.py
- selftests/functional/test_loader.py
- selftests/functional/test_skiptests.py
- selftests/unit/test_data_structures.py
- selftests/unit/test_datadir.py
- selftests/unit/test_restclient_response.py
- selftests/unit/test_settings.py
- selftests/unit/test_xunit.py
These include: avoiding deprecated or now-invalid idioms, specifying text or binary modes when appropriate, and a simple-minded conversion of Process to use BytesIO.
_edit_: removed the Process part because it seems to break Python2.
> Some changes towards working on Python 3

- avocado/core/app.py
- avocado/core/runner.py
- docs/source/ReferenceGuide.rst
- selftests/functional/test_interrupt.py
v6:
- Fixes in docs.
- Helper methods declared ahead of their calls.
- Use `self.assertTrue` instead of `if not wait.wait_for` where applies.
v5: #2152 
- Add docs.
- Selftests:
- Use `proc.stdout.read()` instead of `proc.communicate()`
- Improve comments.
v4: #2150 
- Selftests:
- Refactor to reuse the common methods.
- Use `stderr=subprocess.STDOUT` 
v3: #2140 
- Change the approach to fix this issue. Previously, I was trying to handle the signals from the main process all the way to the test sub-process, through all the layers in between. That was proven hand to control and with a big number of corner cases. Now, the approach is rather simple:
- When a SIGINT in received by the main process, propagate the SIGINT for all the children.
- When a SIGTERM is received by the main process, …
> Fix SIGINT/SIGTERM [v6]

- spell.ignore
Fixing spell error introduced recently.
> spell: additional exceptions

- requirements-selftests.txt
- selftests/functional/test_interrupt.py
Too late I noticed missing requirements change in https://github.com/avocado-framework/avocado/pull/2157 plus I need to increase timeouts in the test_interrupt tests.
> selftests: Two small selftest-related tweaks

- avocado/utils/wait.py
Parameter is `step`, docstring says `steps`. Fixing.
> utils.wait: docstring typo

- .travis.yml
- requirements-travis.txt
With the EOL of Ubuntu 12.04, Travis CI is now running our tests using
Ubuntu 14.04. With this change, our check started to fail.
Even though I'm not sure about the reasons, I could make it work by
using a newer version of `pillow` and also installing `libvirt-python` with
`pip` (`import libvirt` is not working in the `virtualenv` with libvirt-python
installed with apt).
> Fix Travis check 

- avocado/core/data_dir.py
- avocado/core/runner.py
- avocado/core/test.py
- avocado/utils/astring.py
- docs/source/ReferenceGuide.rst
- docs/source/TestParameters.rst
- docs/source/WritingTests.rst
- optional_plugins/runner_remote/avocado_runner_remote/__init__.py
- selftests/unit/test_astring.py
- selftests/unit/test_datadir.py
- selftests/unit/test_jsonresult.py
- selftests/unit/test_loader.py
- selftests/unit/test_settings.py
- selftests/unit/test_sysinfo.py
- selftests/unit/test_test.py
- selftests/unit/test_utils_asset.py
- selftests/unit/test_utils_output.py
- selftests/unit/test_xunit.py
This contains the fixes commit originally part of PR #2164.
I decided to split it because the Travis job wouldn't pass with this number of commits, and also because the changes about test/variant data files can be better reviewed alone.
---
Changes relative to PR #2164:
On commit `Docs: give examples on both Test Names and Test IDs`:
* Shortened test uid (that is, replaced "001-test_name" for "1-test_name")
Removal of commit `avocado/core/test.py: do not default test name to unknown`
On commit `avocado/core/test.py: do not force TestName type`:
* Wrote a proper commit message
On commit `avocado/core/test.py: rename TestName to TestID`:
* Fixed the `__init__()` docstring parameter "variant" information
* Fixed the name property docstring about returning (removed the FIXME and gave …
> Misc Fixes (originally part of "Support for test/variant data files")

- avocado/utils/memory.py
New functions added for memory offline and online, check if memory is
hotpluggable, check if kernel supports memory hotplug.
These functions will be used more often by memory testcases in avocado-misc-tests
Implemented review comments from #2114, #2116
> utils/memory: Memory hotplug and hotunplug functions [v3]

- avocado/utils/memory.py
MemTotal in /proc/meminfo would display total
usable memory(i.e. physical ram minus a few reserved
bits and the kernel binary code)
So, this method helps to report actual memory size according
to online-memory blocks available via "/sys"
> Added a method to get near real physical memory size

- avocado/core/job.py
The recording of Avocado version, when running from a GIT repo has
been broken for a long time (since the SPEC file was renamed).  This
could be a simple fix to just match the new SPEC file named, but I
think we can do better.  Besides this fix, the changes here include:
- Print a short commit instead (8 chars)
- Omit branch name, commit is authoritative enough and developers can
tell the name of a branch if it's really necessary
But, let me say that this is still broken.  The GIT version
information is only printed if the current work directory is inside
the GIT repo directory.  A better (and way more complex) fix would be
one that looks where the avocado script and Python libraries were
loaded from, and check if that location is a GIT repo.  Instead of
doing that, though, it'd make more …
> avocado/core/job.py: fix Avocado version info output to log [v2]

- avocado/plugins/replay.py
The current state of this comment is the result of a mechanical change
replacing `urls` with `references`.
The source for references given on the command line is working as
intended, that is, if test references are given on the command line
they are taken and will override the ones on the replay args.
> avocado/plugins/replay.py: remove misleading TODO comment

- avocado/core/data_dir.py
- avocado/core/settings.py
This patch prevents the use of `~` for data and settings purposes to
avoid polluting of the main system while we are in python virtual
environment.
> venv: Avoid using home dirs when using virtual_env

- avocado/core/varianter.py
The variant-id is defined as string defining the variant name, but it
can also contain value `None` to mark the variant as "without name".
> varianter: Avoid conversion of variant_id to str

- avocado/utils/multipath.py
Changelog from V1 #2121:
* Removed useless `shell=True`, and add `sudo=True`.
* Handled the case where json output might not be available, to return an empty string.
* Split the changes into 2 commits.
> Multipath enhancement [V2]

- avocado/core/test.py
- selftests/functional/test_output.py
Some tests that rely on output check may also rely on the combined
generated output (stdout+stderr).  The first step is to record that
in the same order it was generated.
> Output record: also record the combined stdout+stderr output

- avocado/core/runner.py
Currently, the signal handler for SIGTSTP (which implements the test
pause/resume) is installed before the test process is created, and
thus, is inherited by it.
There's a clean up of the signal handler in the test process, but this
clean up can be prevented by installing the signal handler on the test
runner alone (after the test process is created).
The ramifications of this proposal are such that, in the chance that a
SIGTSTP is received after the test process is created and before the
signal handler is installed in the test runner process, nothing will
happen.  In contrast, the current approach may have the signal handler
action being executed, and attempting to send SIGSTOP or SIGCONT to
the test process, but not doing so because there's no test process
yet.
In the end, it seems that …
> runner: install the SIGTSTP handler on the runner only [v2]

- scripts/avocado
- scripts/avocado-rest-client
- selftests/functional/test_basic.py
A couple of cleanups/simplifications for the avocado executables (aka scripts).
---
Changes from v1 (#2093):
* Move the avocado import to after the exception hook is set
> Simplifications to Avocado's executables (aka scripts) [v2]

- avocado/core/test.py
- selftests/functional/test_statuses.py
Now that the teardown() is always called, we have to explicitly flag
when it should be skipped. That's the case when someone decorates the
setUp() with a skip decorator or when someone calls self.skip() in
setUp().
Reference: https://trello.com/c/B6DJe0JS
> test: flag that test is being skipped

- avocado/core/test.py
Currently it might not be easy to determine what version of the test
source was executed (eg. when test-repo is used). Let's log the filename
entry which is the location of the source file of the test class.
In the future we or users should be able to extend the concept of test
metadata of other useful details like mentioned in
https://trello.com/c/XvaiS4UV/1063-introduce-test-repo-concept-to-
make-test-names-more-relevant
for example "test_tainted, test_version (sha), etc.
v1: https://github.com/avocado-framework/avocado/pull/2178
Changes:
```yaml
v2: Simplified to only log self.filename if available
```
> test: Log full path to the test source

- avocado/utils/vmimage.py
Utility to provide Qcow VM Images acquired from distro repositories.
Usage:
>>> from avocado.utils import vmimage
>>> image = vmimage.get()
>>> image
<Image name=Fedora version=26 arch=x86_64>
>>> image.name
'Fedora'
>>> image.path
'/tmp/Fedora-Cloud-Base-26-1.5.x86_64-d369c285.qcow2'
>>> image.get()
'/tmp/Fedora-Cloud-Base-26-1.5.x86_64-e887c743.qcow2'
>>> image.path
'/tmp/Fedora-Cloud-Base-26-1.5.x86_64-e887c743.qcow2'
>>> image.version
26
>>> image.base_image
'/tmp/Fedora-Cloud-Base-26-1.5.x86_64.qcow2'
>>> image = vmimage.get(arch='aarch64')
>>> image
<Image name=FedoraSecondary version=26 arch=aarch64>
>>> image.name
'FedoraSecondary'
>>> image.path
'/tmp/Fedora-Cloud-Base-26-1.5.aarch64-07b8fbda.qcow2'
>>> image = vmimage.get(version=7)
>>> image
<Image name=CentOS version=7 …
> Introducing the vmimage util [v4]

- avocado/core/loader.py
- avocado/core/test.py
- docs/source/Loaders.rst
- docs/source/ReferenceGuide.rst
- selftests/.data/unittests.py
- selftests/checkall
- selftests/functional/test_basic.py
- selftests/functional/test_loader.py
- selftests/functional/test_output.py
- selftests/functional/test_plugin_jobscripts.py
- selftests/functional/test_statuses.py
- selftests/functional/test_streams.py
- selftests/functional/test_utils.py
- selftests/unit/test_loader.py
- selftests/unit/test_mux.py
This PR adds support to discover python unittests as individual tests, which was previously supported only as contrib script + external runner.
As Avocado tests are in fact python unittests, disabled Avocado tests are excluded from the results to avoid confusion. Also to support running tests from parent locations, each unittest is executed from it's __file__ directory (eg. running `/tmp/foo.py => cd /tmp && python -m unittest foo.$class.$test`, instead of `..........tmp.foo.$class.$test` which would not work).
v1: https://github.com/avocado-framework/avocado/pull/2182
v2: https://github.com/avocado-framework/avocado/pull/2192
v3: https://github.com/avocado-framework/avocado/pull/2194
v4: https://github.com/avocado-framework/avocado/pull/2196
changes:
```yaml
v2: Instead of working-around …
```
> loader: Add support to discover individual python unittests and some style fixes [v5]

- avocado/core/sysinfo.py
The sysinfo collection allows to use daemons to collect information while the tests are running, but as issue https://github.com/avocado-framework/avocado/issues/2135 showed us the daemons might not be cleaned properly afterwards. This PR adds some protections to decrease the probability we leave processes behind.
Fixes issue: https://github.com/avocado-framework/avocado/issues/2135
> sysinfo: couple of daemon treatment fixes

- docs/source/GetStartedGuide.rst
We need some updates in the installation process when performing a Generic installation from a GIT repository:
- Move from `yum` to `dnf` in our docs.
- Update the list of packages to be installed via package manager in our docs. 
v2:
- Drop the commit adding `libvirt-python` to requirements.txt.
v1: #2195
> Fixes for "install from source" [v2]

- docs/source/GetStartedGuide.rst
It's currently not clear how users should go about installing the
optional plugins when using PyPI/pip.
Let's list the package names as they're available on PyPI.
> Docs: include information on installation of plugins from PyPI
