docs/source/Configuration.rst
To reflect the latest status quo regarding Configuration.
=> docs/Configuration: Update Configuration section

avocado/sysinfo.py, etc/avocado/avocado.conf
Fix and make sysinfo's collection of installed packages configurable.
=> Component Isolation: sysinfo installed packages collection

avocado/core/output.py, selftests/all/functional/avocado/output_tests.py
Follow up to #334.
Changes from V1:
* Use a more descriptive attribute name
=> [V1] Redirect output fix

avocado/job.py, avocado/plugins/htmlresult.py, avocado/runtime.py
This is a follow up to #342.
* Use the runtime module info (Cleber's work)
* Evaluate the pass rate in a cleaner fashion (Cleber's suggestion)
=> [V2] HTML result plugin bugfixes

avocado/plugins/remote.py
Avocado sometimes produces unexpected texts (failures) before
the actual json output. This patch tries to parse the output
for the correct line instead of using first line.
Note: Avocado should not produce any strings when --json -
specified. Anyway having this logic might be still useful.
=> plugins.remote: Improve json parsing

avocado/core/output.py, avocado/utils/astring.py, selftests/all/unit/avocado/astring_unittest.py
Preliminary commits to the latest version of the test discovery PR, that will succeed #358.
Just one fix and one utility function.
=> Pre-requesites to test discovery V7

avocado/utils/process.py, selftests/all/functional/avocado/wrapper_tests.py
@ruda, I've decided to split this fix to make the test discovery PR V9 leaner. Please take a look.
=> Fix Wrapper Patterns

avocado/core/exceptions.py, setup.py
A couple of simple fixes necessary for the Test Discovery work, but are better on a separate PR. Please review, @ruda or @clebergnu
=> More fixes before discovery

avocado/core/output.py, avocado/plugins/plugins_list.py, avocado/plugins/remote.py, avocado/plugins/runner.py, avocado/plugins/test_lister.py, avocado/plugins/vm.py, avocado/test.py, selftests/all/functional/avocado/loader_tests.py, selftests/all/unit/avocado/loader_unittest.py, selftests/all/unit/avocado/remote_unittest.py, selftests/all/unit/avocado/vm_unittest.py
A bunch of small fixes for the 0.20.1 "Eurotrip Part II" release.
* Adjusted a commit message per @clebergnu's comments.
* Used another way to detect avocado absent from the remote system
=> Devconf bugfixes v2

avocado/core/data_dir.py, avocado/job.py, avocado/plugins/runner.py, selftests/all/functional/avocado/argument_parsing_tests.py, selftests/all/functional/avocado/basic_tests.py
Follow up of PR #424.
---
Changes:
* Fixed typo *lastest* (latest).
* Rebased code to the current master.
=> Argument parsing job result [V4]

avocado/core/output.py, etc/avocado/avocado.conf
Another work item for the 21st Sprint.
=> Disable colored output

avocado/test.py
Sorry but I just couldn't sleep knowing I did it non-optimally... Please accept this minor change.
=> avocado.test: Little speed optimization of the warn log

avocado/__init__.py, avocado/utils/process.py, selftests/all/functional/avocado/multiplex_tests.py, selftests/all/functional/avocado/output_tests.py
* Fix regression when the number of lines from the output was reduced,
so we're now assuming 13 lines, instead of 14. Fix issue #472.
* Cosmetic fixes (PEP8 issue)
=> Regression and cosmetics

avocado/cli/parser.py, avocado/job.py, avocado/plugins/gdb.py, avocado/plugins/htmlresult.py, avocado/plugins/journal.py, avocado/plugins/jsonresult.py, avocado/plugins/plugin_list.py, avocado/plugins/runner.py, avocado/plugins/test_list.py, avocado/plugins/wrapper.py, avocado/plugins/xunit.py, avocado/remote/runner.py, avocado/test.py, docs/source/WritingTests.rst, man/avocado.rst, selftests/all/functional/avocado/output_check_tests.py, selftests/all/unit/avocado/remote_unittest.py
Follow up of #497.
----
Changes:
* Validate values for `--job-log-level`.
* Cosmetic fix.
---
Things left for “Part II”.
* Review and validate options for `remote`, `vm` and `gdb` stuff.
* Remove some command line options and leave them on the configuration file.
=> Review command line options. [V5]

avocado/multiplexer.py, avocado/remote/runner.py, selftests/all/unit/avocado/remote_unittest.py, setup.py
Few fixes I found while working on avocado options review.
=> Bugfixes 26/03/2015

etc/avocado/avocado.conf, etc/avocado/conf.d/gdb.conf
Document config file options, to help users understand why they are there.
=> [V2] Document config file options

avocado/plugins/exec_path.py, examples/tests/simplewarning.sh, scripts/avocado
Use -e to exit on first failure.
=> examples.tests.simplewarning: Use -e to exit on failure

avocado/job.py, avocado/plugins/runner.py, avocado/runner.py, avocado/test.py, selftests/all/functional/avocado/job_timeout_tests.py
Follow up of #550 
---
Changes:
Address commends made by @lmr,
* Gives a proper error message when the values for job timeout is not OK.
* Improve the functional test.
* Cosmetics.
=>   Set timeout per job execution [V4]

avocado/runner.py
Swap `runTest()` with `_runTest()`. Now `run_suite()` will call `runTest()` and then, create a subprocess with `_runTest()`.
Plus more refactoring:
* Update documentation.
* Use longer variable names.
* Cosmetics.
Signed-off-by: Rudá Moura <rmoura@redhat.com>
=> avocado.runner: Swap runTest() and _runTest().

examples/testplans/release.json, scripts/avocado-run-testplan
Hi guys, I believe "description" is an important part of the result. In this pull request I tried to change the human output to still be "human readable" but also contain the necessarily information. Feel free to disagree or change the layout.
The first commit is typo-fix and can be applied either separately or with this modification.
=> testplan: Description improvement

avocado/multiplexer.py, avocado/runner.py
Typo fix and suggestion for parameters logging.
=> Multiplexer tweaks

avocado/core/data_dir.py, avocado/utils/genio.py, avocado/utils/process.py
As the name implies, these are just some trivial fixes I found while working on other tasks.
=> Trivial fixes 2015-04-27

avocado.spec, avocado/version.py, setup.py
* setup.y: Fix location of plugins and resources
* avocado.version: Update to version 0.24.0
* avocado.spec: Update to version 0.24.0
=> Updates for the upcoming version 0.24.0

setup.cfg
This little detail has gone unnoticed. Let's fix it.
=> setup.cfg: Update to 0.24.0

Makefile, examples/testplans/release.json
* 	Makefile: Update link creating for avocado-virt
* 	examples.testplans: test execution should use --sysinfo on
=> Final updates for release 0.24.0

avocado/core/job.py, avocado/core/plugins/builtin.py
After discussion on plugin failures, send a couple of patches that aim to avoid confusion on users about failed to load plugins.
=> Plugin fail mechanics

avocado/utils/software_manager.py
When using the software_manager component on a Red Hat like distro,
if the yum module for Python is not installed, log the information
as an error message and use the basic support from rpm/yum.
Why this?
If the module yum is not installed (for example, in a virtualenv),
the software_manager component will not traceback when creating
an instance of YumBackend and only the method provides() will be disabled.
=> avocado.utils.software_manager: Check if yum module is present

avocado/core/remote/runner.py
When setup() or tear_down() fails, Avocado will provide a gentle error message and a proper exit code and put the traceback in the test log.
./scripts/avocado run --remote-host nowhereland passtest
LOGIN      : rmoura@nowhereland:22
Avocado job failed: JobError: Name lookup failed for nowhereland
Prior to this commit, when setup or tear_down failed, Avocado dumps the traceback and prints that it crashed, which can potentially confuses the user.
=> avocado.core.remote.runner: When setup/teardown fails, exit gently.

avocado/core/test.py
These are a collection of low hanging fruits in an attempt to give `avocado.Test` users (test writers) a better sense of what is the API allowed/intended for their use.
Related to:
https://trello.com/c/cVehsq2J/421-review-avocado-test-api
=> avocado.Test cleanup: low hanging fruits

avocado.spec, avocado/core/version.py, setup.cfg
=> Avocado: Update to release 0.25.0

examples/tests/cabort.py, examples/tests/datadir.py, examples/tests/doublefree.py, examples/tests/doublefree_nasty.py, examples/tests/fiotest.py, examples/tests/linuxbuild.py, examples/tests/modify_variable.py, examples/tests/multiplextest.py, examples/tests/raise.py, examples/tests/sleeptenmin.py, examples/tests/sleeptest.py, examples/tests/synctest.py, examples/tests/timeouttest.py, examples/tests/whiteboard.py
Summarize the test params to help people understand and run and
adjust test variants via multiplexer easily.
Changes:
v1: Modified commit description advised by Ademar
=> examples.tests: Add params descriptions

.travis.yml, Makefile, examples/testplans/release.json, requirements-travis.txt, scripts/avocado-run-testplan, selftests/cyclical_deps
Some improvements to both the manual testing and the CI testing of avocado.
=> [V2] Manual and ci testing improvements

examples/testplans/release.json
Include our newest plugin into the list of functional tests.
=> testplans: Update release test plan with avocado-vt tests

avocado/core/job.py, avocado/utils/process.py
Hello guys,
following patches should improve the Avocado UI experience. See the details in commit messages.
Regards,
Lukáš
=> avocado: Two UI improvements

requirements-selftests.txt
Per @ldoktor's request, we should update the selftests requirements.
=> requirements-selftests: Update dependencies

avocado/utils/process.py
Signed-off-by: Hao Liu <hliu@redhat.com>
=> avocado.utils.process: Add missing parenthesis

avocado/core/remoter.py
Currently the remote loop is missing "break" so it resends the same
command until the timeout is reached.
While working on this I recreated the loop so it supports None timeout,
which is required for some operations.
=> avocado.core.remoter: Avoid repeating of the remote command

avocado/core/job.py, avocado/core/loader.py, avocado/core/log.py
Please see commit messages for details.
=> Few bugfixes and improvements

docs/source/RunningTestsRemotely.rst, docs/source/WritingTests.rst, examples/testplans/release.json
A handful of fixes for the avocado 0.29.0 release.
=> Update docs and testplan

Makefile, debian/changelog
We have a new 0.29.0 build out, this PR updates the deb build files with the appropriate values.
=> Ubuntu build updates

docs/source/MaintenanceGuide.rst, docs/source/index.rst
In order for the process to not get lost and help newer
maintainers, here's a writeup with the steps to keep in
mind when releasing avocado.
=> avocado: Add a maintenance guide

avocado/core/exit_codes.py, selftests/functional/test_argument_parsing.py, selftests/functional/test_basic.py, selftests/functional/test_export_variables.py, selftests/functional/test_job_timeout.py, selftests/functional/test_journal.py, selftests/functional/test_multiplex.py, selftests/functional/test_output.py, selftests/functional/test_output_check.py, selftests/functional/test_standalone.py, selftests/functional/test_sysinfo.py, selftests/functional/test_wrapper.py
This implements the card described at:
https://trello.com/c/SU5fixgH/510-improve-job-statuses
=> Exit codes: use symbols

scripts/avocado
=> scripts/avocado: Fix typo

README.rst
The repository for Fedora/RHEL has changed.
=> README: Change the yum repository

avocado/core/remote/__init__.py, avocado/core/remote/runner.py, avocado/core/runner.py
This was caught by modified inspektor check. I'm still
working on inspektor, meanwhile let's send this fix.
=> avocado: Fixing unused imports

requirements-selftests.txt
"make check" needs pydot to run.
=> Add pydot to selftests requirements

avocado/utils/git.py
Var "lbranch" was hard coded to "master", so it was never copied from var "branch".
Also fixed/reordered some docstrings.
=> Fix test providers checkout

avocado/core/runner.py
This patchset fixes two issues with the current runner, one of them hopefully fixes the https://github.com/avocado-framework/avocado/issues/898 issue (although I was not able to reproduce it). Please see the details in the patches.
=> avocado.core.runner: Two bugfixes

avocado.spec, docs/source/GetStartedGuide.rst
A collection of fixes (packaging and docs) for the upcoming release.
=> Fixes for the upcoming release (0.31)

avocado/core/runner.py
Simple documentation addition and early state tweak.
=> Early state docs and tweaks

avocado/core/remote/runner.py
Sometimes remote servers might have MOTD (message of the day)
banners, that will introduce line breaks on the remote output
of the `avocado -v` command. Let's use re.MULTILINE and
re.findall to solve that.
=> avocado.core.remote.runner: Use more robust avocado version check

avocado/utils/software_manager.py
Some debian packages are needy and demand our attention
even if we already told apt-get to answer all questions
with 'yes'. We need to export
DEBIAN_FRONTEND='noninteractive'
So that apt-get can be run fully unattended. Let's adjust
accordingly, and pass some default dpkg values.
=> avocado.utils.software_manager: More debian fixes

docs/source/ContributionGuide.rst, docs/source/GetStartedGuide.rst, docs/source/index.rst
Mostly related to the previous questions and feedback on the mailing list.
=> Docs fixes and improvements

examples/tests/aiostress.py, examples/tests/aiostress.py.data/aio-stress.c
Add new 'aiostress' test based on autotest.
=> avocado.tests: Port aiostress from autotest [v2]

avocado/core/runner.py
I've noticed this when writing tests using the boto3 (Amazon
AWS) API - for some exceptions, not all the arguments of the
exception can be pickled, leading to the following crash:
(1/2) scylla_longevity.py:LongevityTest.test_20_minutes: -
Avocado crashed: TypeError: ('__init__() takes exactly 3 arguments (2 given)', <class 'botocore.exceptions.ClientError'>, ("An error occurred (InvalidAMIID.NotFound) when calling the RunInstances operation: The image id 'ami-20776841' does not exist",))
File "/home/lmr/Code/avocado.lmr/avocado/core/job.py", line 451, in _run
timeout=self.timeout)
File "/home/lmr/Code/avocado.lmr/avocado/core/runner.py", line 368, in run_suite
deadline)
File "/home/lmr/Code/avocado.lmr/avocado/core/runner.py", line 284, in run_test
if …
=> [V2] avocado.core.runner: Fix problems with exceptions that can't be pickled

avocado/core/test.py
=> avocado.core.test: PEP8 Fix

avocado/core/test.py
First round of cleanups, according to the requirements defined at:
https://trello.com/c/W58vhyHR/539-bug-some-avocado-test-methods-and-atributes-are-public
=> Test namespace cleanup

avocado/utils/software_manager.py
Hello guys,
this PR fixes a TypeError, when we created a repo and then tried to remove it in the same process. Then it improves the tmpfile handling in the same module and adds few pylint fixes on top.
=> avocado.utils.software_manager: Bugfixes and cleanups

.travis.yml
Last time it did not work, let's try it again to see whether it works.
=> .travis: Let's try using cache again

.travis.yml, Makefile
This adds very simple incremental per-commit smoke check in travis.
=> Incremental smoke-check

avocado.spec, selftests/unit/test_utils_process.py
Hello guys,
this contains fixes for: FAIL: 'Avocado RPM build': I have fixes in my tree
=> Two bugfixes regarding the testplan

avocado/core/html.py
Some users are getting UnicodeDecodeError, but we're unable to reproduce
it. This commit lists the full template and repr() of the failure so we
can at least see what was rendered and identify the source.
No one should actually see this message and we should remove it once we
identify and fix this problem, but without such extensive debug we can't
do anything about it.
=> avocado.core.html: Add extensive debug on UnicodeDecodeError

avocado/core/job.py, avocado/core/loader.py, avocado/core/output.py, avocado/core/remote/runner.py, avocado/core/sysinfo.py, avocado/plugins/html.py, avocado/plugins/json.py, avocado/plugins/multiplex.py, avocado/plugins/remote.py, avocado/plugins/vm.py, avocado/plugins/wrapper.py, selftests/functional/test_multiplex.py, selftests/functional/test_standalone.py, selftests/unit/test_jsonresult.py, selftests/unit/test_xunit.py
This is a subset of #1040, with the following changes:
* Style fixes on https://github.com/ldoktor/avocado/commit/a73d09cf8ed47f43181c33a07a8b2527f5e53e5f
* Bring the changes from "add_log_handler" in https://github.com/ldoktor/avocado/commit/4bbec4a933debb5bf8febe10422ac148ae6d6c79 to the original rename/change in https://github.com/ldoktor/avocado/commit/bcf500c486b300baf298d298abb0de2a513825c5
* Test fixes to comply with the slight change of behavior and to add robustness to them
=> Refactor logging initialization [subset/first round]

avocado/core/test.py, selftests/unit/test_test.py
All *SkipTests are now inherited from "SkipTest" baseclass. This
baseclass contains improved __init__ which removes any unsupported
parameters from the Test.__init__ super call.
This is because those classes are used to substitute other avocado test
classes, for example "avocado-vt" tests which contain "vt_params"
argument unsupported by Test.__init__.
v1: https://github.com/avocado-framework/avocado/pull/1050
Changes:
v2: Create SkipTest baseclass
v2: Prioritize kwargs to args as they say what they mean
v2: Added unittest
=> avocado.core.test: Refactor *SkipTests and support extra params [v2]

avocado/core/job.py
When avocado fails to update the link to the latest results, the whole
job is aborted. This is unfortunate and after a discussion we considered
this as a "soft" issue.
With this patch we only log an information, that the latest link was not
updated into the job-log and proceed to testing.
This commit also extends the link creation to be
concurrent-execution-safe by creating `latest-$PID` symlink first and
then renames the symlink to `latest`. The rename is atomic operation and
does not suffer the delete->create problem, where other process creates
the file before this one.
v0: https://github.com/avocado-framework/avocado/pull/1055
Changes:
v2: Redefine the problem, make latest link update "soft" failure
v2: Use symlink creation proposed by @clebergnu
=> avocado.core.job: Avoid test failure on latest link failure

.travis.yml, Makefile
Let's try to enable full per-commit check in travis
=> .travis.yml: Run full "make check" per commit in travis

avocado/core/xunit.py, selftests/functional/test_output.py
Xunit/XML CDATA/attributes must not contain non-printable characters.
This patch escapes such characters using hex value.
=> avocado.core.xunit: Escape non-printable characters

avocado/core/app.py, avocado/core/output.py, avocado/plugins/base.py, avocado/plugins/plugins.py
Collection of miscellaneous improvements and simplifications to the Plugin related code.
=> Plugin Improvements

docs/source/GetStartedGuide.rst
=> Get Started Guide: remove obsolete note

docs/source/ContributionGuide.rst
Add short section about GPG signing (optional).
=> docs: Add GPG signature part to Contribution Guide

avocado/core/loader.py, avocado/core/runner.py
Very simple docstring fixes on the Runner and Loader modules.
=> Runner and Loader docstring fixes

docs/source/conf.py
It is expected to be string, not integer.
=> fix docs release type

avocado/core/runner.py
v1: #1165 
- Add try/except to the `run_test()` so we can avoid crash on ctrl+c outside the test loop.
v2: #1167 
- Move the try/except to the `run_suite()`
- Add `INTERRUPTED` to the summary on 'except'.
v3: #1168 
- Log message regarding the interruption.
v4:
- Better log message.
- Variable name convention fix.
=> fix crashes if Ctrl+C is hit in the 'wrong' moment [v4]

avocado/core/runner.py
If Ctrl+C is hit outside the loop waiting for the test, instead
of failing nicelly, Avocado crashes.
This patch adds a try/except for the run_suite function so we can
catch the KeyboardInterrupt outside the loop that waits for the test
addint 'INTERRUPTED' to the summary.
Reviewed-on: #1170
Reference: https://trello.com/c/lDj56sKW
=> [36lts] fix crashes if Ctrl+C is hit in the 'wrong' moment

.travis.yml, requirements-travis.txt, requirements.txt
This PR contains a series of upstream patches related to travis. The individual PR upstream pages are referenced in each commit message.
=> [36lts] travis backports

avocado/core/remote/runner.py, examples/testplans/release.json
Hello guys,
the testplan uncovered couple of issues regarding the remote runner, some naming changes and avocado-virt issue (fixed in https://github.com/avocado-framework/avocado-virt/pull/80 ).
=> Testplan related bugfixes

avocado/utils/data_structures.py
Added geometric mean utility in data_structures
=> Added Geometric Mean utility

selftests/unit/test_data_structures.py
Couple of avocado.utils.data_structure unit tests.
=> selftests: Add avocado.utils.data_structures unit tests

docs/source/MultiplexConfig.rst
Signed-off-by: Lin Ma <lma@suse.com>
=> docs: a typo fix in 'Multiplex Configuration'

avocado/utils/data_structures.py, selftests/unit/test_data_structures.py
A utility to compare two matrices and return the difference in another matrix.
=> Adding compare_matrices utility

selftests/unit/test_archive.py, selftests/unit/test_utils_partition.py
Two pre-release unittest fixes found by @apahim when checking `make rpm`.
=> selftests: Few pre-release unittest fixes

avocado/core/app.py, avocado/core/loader.py, avocado/core/multiplexer.py, avocado/core/output.py, avocado/core/restclient/cli/parser.py, avocado/core/restclient/connection.py, avocado/core/safeloader.py, avocado/core/status.py, avocado/core/test.py, avocado/core/tree.py, avocado/plugins/distro.py, avocado/utils/asset.py, avocado/utils/astring.py, avocado/utils/aurl.py, avocado/utils/data_structures.py, avocado/utils/distro.py, avocado/utils/gdb.py, avocado/utils/iso9660.py, avocado/utils/path.py, avocado/utils/process.py, avocado/utils/service.py, avocado/utils/software_manager.py, docs/source/RunningTestsRemotely.rst, selftests/functional/test_basic.py, selftests/unit/test_tree.py, selftests/unit/test_utils_asset.py
=> Massive spelling correction

docs/source/index.rst, docs/source/release_notes/0_25_0.rst, docs/source/release_notes/0_26_0.rst, docs/source/release_notes/0_27_0.rst, docs/source/release_notes/0_27_1.rst, docs/source/release_notes/0_28_0.rst, docs/source/release_notes/0_29_0.rst, docs/source/release_notes/0_30_0.rst, docs/source/release_notes/0_31_0.rst, docs/source/release_notes/0_32_0.rst, docs/source/release_notes/0_33_0.rst, docs/source/release_notes/0_34_0.rst, docs/source/release_notes/35_0.rst, docs/source/release_notes/36_0.rst, docs/source/release_notes/37_0.rst, docs/source/release_notes/38_0.rst, docs/source/release_notes/index.rst, requirements-selftests.txt, requirements-travis.txt
v2:
- Remove parenthesis from release names.
- Reorganize the commits.
v1: #1317 
- Add captions to separate sections in readthedocs left menu.
- Remove the heads as we are now using captions.
- Fix anchors.
- Create a release_notes directory and an dedicated index file.
- Another batch of release notes.
=> Documentation Improvements [v2]

avocado/plugins/docker.py
Couple of docker plugin tweaks to improve user experience
v1: https://github.com/avocado-framework/avocado/pull/1332
changes:
```
v2: [crosa] Added commit to get the cid from the last line
(to avoid errors when pulling the image)
```
=> avocado.plugins.docker: User experience fixes

avocado/utils/process.py
This patch uses Timer instead of a busy poll loop when using
`process.run` with timeout.
=> [LTS] avocado.utils.process: Avoid busy loop in run

avocado/core/remote/runner.py
The commit e13734f53f5bce7321e88a09c28c104a49190995 broke the remote
execution as it depends on single-line json results output. This patch
adds a way to parse the output from pretty or single-line json output
(tested on avocado LTS and the current master)
=> avocado.core.remote: Adjust to pretty json output

avocado/core/html.py, avocado/utils/filelock.py, spell.ignore
Hello guys,
there are two little issues found while running the manual testplan.
v1: https://github.com/avocado-framework/avocado/pull/1388
Changes:
```
v2: Yet another grammar fix
```
=> Testplan related bugfixes [v2]

docs/source/MaintenanceGuide.rst, docs/source/MultiplexConfig.rst, docs/source/RunningTestsRemotely.rst, docs/source/release_notes/0_27_0.rst, docs/source/release_notes/0_27_1.rst, docs/source/release_notes/0_28_0.rst, docs/source/release_notes/0_29_0.rst, docs/source/release_notes/0_30_0.rst, docs/source/release_notes/0_31_0.rst, docs/source/release_notes/0_32_0.rst, docs/source/release_notes/0_33_0.rst, docs/source/release_notes/0_34_0.rst, docs/source/release_notes/35_0.rst, docs/source/release_notes/36_0.rst, docs/source/release_notes/37_0.rst, docs/source/release_notes/38_0.rst, docs/source/release_notes/39_0.rst
There are several fixes found while reviewing the documentation.
=> docs: Fixes found in docs review

requirements-travis.txt
=> requirements: Use the latest inspektor in travis

avocado/core/remote/runner.py, avocado/utils/archive.py
Signed-off-by: Wei Jiangang <weijg.fnst@cn.fujitsu.com>
=> avocado.core.runner: Fix undefined name

docs/source/ContributionGuide.rst
v2:
- Incorporated all suggestions from v1 (#1435) review.
v1: #1435 
- Create a git workflow section based on the devel list
discussion.
=> docs: add git workflow [v2]

optional_plugins/html/avocado_result_html/__init__.py
this PR addresses little style fixes in the html plugin.
=> optional_plugins.html: Minor fixes

avocado/core/remote/runner.py, avocado/core/virt.py
v2:
- Better messages.
- Exception class docstring.
v1: #1469
=> virt: improve error messages [v2]

avocado/core/test.py
There are few minor improvements which came to my mind when looking at https://github.com/avocado-framework/avocado/pull/1467
=> avocado: Few little improvements to listing local vars

docs/source/WritingTests.rst
This issue has come up repeatedly, so let's document how and why we
(don't) support `setUpClass` and `tearDownClass`.  While at it, let's
give some ideas on how to work around this, or better put, write tests
more aligned with Avocado's design of more isolated tests.
--
Changes from v1 (#1497):
* Suggested paragraps rewritten
* Typos corrected
=> Docs: document unittest class level setUp and tearDown compatibility

avocado/plugins/docker.py, contrib/docker/Dockerfile.debian, contrib/docker/Dockerfile.fedora, docs/source/RunningTestsRemotely.rst
Various Docker improvements by Dmitry Monakhov.
--
Changes from v2 (#1486):
* Documentation changes
* rename: --docker-opt --docker-option as ldoktor@ suggests
* place Dockerfiles to contrib/docker as adereis@ and ldoktor@ suggests
* docs: move docker description to appropriate file close to docker section.
=> Docker improvements [v3]

avocado/core/sysinfo.py, selftests/functional/test_plugin_jobscripts.py, spell.ignore
Collection of  fixes based on release test plan for 42.0.
=> Fixes based on release test plan for 42.0

avocado/utils/data_structures.py
Added author name in data_structures.py #1223 and #1227
=> avocado.utils.data_structures: add author

avocado/core/plugin_interfaces.py, avocado/utils/build.py, avocado/utils/process.py, spell.ignore
=> spell: Couple of spellcheck fixes

avocado/plugins/journal.py
Sending this one-line fix while the PR that would include this is still under discussion.
=> fix unicode handling in journal plugin

avocado/core/loader.py, avocado/plugins/list.py
Small collection of fixes related to the loader and the list command (originally part of #1629).
=> Misc loader and list fixes

avocado/core/multiplexer.py, avocado/core/remoter.py, avocado/core/sysinfo.py, selftests/unit/test_parser.py
Recent pylint is again a bit more pedantic. Let's fix places where
possible and locally disable checks with false-detections.
=> Few pylint fixes

avocado/utils/pci.py
Please read the individual commit messages for details.
=> avocado.utils.pci: Couple of bugfixes

avocado/utils/pci.py
The first 2 commits are bugfixes and part of a different PR. The 3rd commit is a RFC regarding function name and the last commit should clarify what kind of parameter is expected in each function.
v1: https://github.com/avocado-framework/avocado/pull/1681
Changes:
```yaml
v2: Rebased to the latest master
```
=> avocado.utils.pci: Couple of adjustments to make params explicite

avocado/utils/lv_utils.py
Added '-' to regex which searches for pv name from the output
of 'pvs' command.
=> Fixed the regex to find PV name

avocado/utils/pci.py
added some code to fetch some more info from vpd
=> ltered get_vpd in pci.py

avocado/core/remote/runner.py
Reduced the number of calls to join/map
Previous pull request: #1759 
Reference: https://trello.com/c/ZcV36ncd
Signed-off-by: Maurice Saldivar <maurice.a.saldivar@hpe.com>
=> adds warning to UI & job.log if remote avocado version mismatch

docs/source/Configuration.rst
Add a section to Configuration documentation about virtualenv.
Signed-off-by: Andrei Stepanov <astepano@redhat.com>
=> Add a notice to docs about configs in virtualenv.

docs/source/Configuration.rst, docs/source/DevelopmentTips.rst, docs/source/Loaders.rst, docs/source/WritingTests.rst
Several docs update related to docs upkeep...
=> docs: Several docs-related tweaks and updates

avocado/core/job.py
See the actual changes in the commit messages.
=> Job: Few datadir-related job-log tweaks

docs/source/GetStartedGuide.rst, docs/source/Replay.rst, docs/source/ResultFormats.rst, docs/source/RunningTestsRemotely.rst, docs/source/WritingTests.rst
The 'TESTS' line was removed from the UI. Let's update the examples in
our docs accordingly.
=> docs: update the examples according to current UI

requirements-docs.txt, requirements-travis.txt
v2:
- Pin the version.
v1: #1827
=> requirements: use latest stevedore [v2]

man/avocado.rst
man is quite outdated. This patch updates the man to reflect the
current options and UI.
Reference: https://trello.com/c/UB6hG2mD
v1: #1830
=> man: update man page [v2]

avocado/utils/process.py, spell.ignore
Here the spell fixes for the v47 test plan.
=> spell: v47 fixes

docs/source/WritingTests.rst
Signed-off-by: Jun Guo <blackhumour.gj@gmail.com>
The current layout is incorrect:
=> [DOCS] Minor fix for WritingTest document

avocado/core/exceptions.py, avocado/core/output.py, avocado/core/result.py, avocado/core/status.py, avocado/core/test.py, avocado/plugins/human.py, avocado/plugins/jsonresult.py, avocado/plugins/tap.py, avocado/plugins/xunit.py, docs/source/WritingTests.rst, examples/tests/canceltest.py, optional_plugins/html/avocado_result_html/__init__.py, selftests/functional/test_canceltests.py
v2:
- Addressed comments in V1 review.
v1: #1847
=> Introduce the CANCEL status and the self.cancel() [v2]

avocado/core/job.py, avocado/core/output.py, avocado/plugins/tap.py, avocado/utils/asset.py, avocado/utils/download.py, avocado/utils/lv_utils.py, optional_plugins/runner_remote/avocado_runner_remote/__init__.py, selftests/functional/test_lv_utils.py, selftests/functional/test_output.py, selftests/functional/test_thirdparty_bugs.py
The title says it all.  While this still doesn't bring full Python 3 compatibility (there's still quite a bit to be done) it improves things a little, while not breaking Python 2 code.
---
Changes from v1 (#1858):
* Fixed other `except Exception as detail` type of statements
=> Python 3k: another round of compatibility improvements [v2]

docs/source/WritingTests.rst
Same issue as PR https://github.com/avocado-framework/avocado/pull/1853. Sorry I didn't notice it last time.
Signed-off-by: Jun Guo <blackhumour.gj@gmail.com>
=> [DOCS] Correct the code block output.

avocado/core/app.py
For https://github.com/avocado-framework/avocado/issues/1870
=> app: backport three patches for bugs fix

avocado/utils/linux_modules.py
avocado.utils.linux_modules: Improved the module.
Added the following parameters to the return value of
loaded_module_info()
* filename
* version
* parameters list
* depends list
Changelog from v1:
* Implemented the `if/elif` as per the suggestion from @ldoktor 
Changelog from v2:
* Optimized the dictionary formation and updated docstring as per the suggestion from @apahim 
Changelog from v3:
* Seperated the docstring changes into seperate commit
* Addressed the code so that no index error occurs, as per suggestion from @lmr 
=> Improved linux_modules [v4]

optional_plugins/robot/avocado_robot/__init__.py
v3:
- One last pylint fix.
- Rebase.
v2: #1892 
- Use the specific exception.
- Bonus commit: pylint fixes
v1: #1889
=> robot: fix error on unknown tests [v3]

examples/testplans/release.json
The package names have changed, let's sync that with what's used
in the release example testplan.
=> Release example testplan: update RPM package names

optional_plugins/robot/avocado_robot/__init__.py
=> Robot Loader: use symbolic names

optional_plugins/resultsdb/setup.py, python-avocado.spec
This includes a set of fixes to package the resultsdb plugin.
=> resultsdb: packaging fixes

docs/source/Configuration.rst, docs/source/ResultFormats.rst, docs/source/RunningTestsRemotely.rst, docs/source/TestParameters.rst, docs/source/index.rst, docs/source/optional_plugins/index.rst, docs/source/optional_plugins/results.rst
A few fixes found during the docs review...
v1: https://github.com/avocado-framework/avocado/pull/1950
Changes:
```
v2: fixe corrupted patch
```
=> Docs: Some of fixes and improvements [v2]

python-avocado.spec
=> SPEC: add missing docker directory

avocado/plugins/human.py, avocado/plugins/journal.py, selftests/functional/test_output.py
Collection of two bugfixes that manifested after the "job time should be wall clock time" PR.
---
Changes from v2 (#1997):
* Added functional test coverage for plugin errors
Changes from v1 (#1996):
* Added functional test coverage
=> Bugfixes: journal failure and test/job UI [v3]

avocado/utils/cpu.py
A simple couple of improvements to `avocado.utils.cpu`.
Related to #2010
=> avocado.utils.cpu improvements

avocado/core/loader.py
Let's modify the `make_broken` function to optionally accept
`description` which is used to report additional comments after the test
uid, instead of doing this manually per each call.
This also replaces the same parameter for the dummy `ignore_broken`
function which still contained other optional parameter not used by the
parallel `make_broken` function.
This commit was suggested here https://github.com/avocado-framework/avocado/pull/2015/commits/5f6d9f011acdc6ef8471b76adc610de831032254#r117045713 by @clebergnu
=> loader: Simplify additional description definition

avocado/core/loader.py, avocado/core/varianter.py, docs/source/conf.py, selftests/unit/test_safeloader.py, setup.py, spell.ignore
Including style, spelling and doc build fixes.
=> Sprint #51 fixes

README.rst, docs/source/GetStartedGuide.rst, docs/source/rfcs/LongTermStability.rst, optional_plugins/varianter_yaml_to_mux/setup.py
Collection of documentation fixes for upcoming release 51.0.
=> Pre-release 51.0 documentation fixes

docs/source/ContributionGuide.rst
v2:
- Improve the sentence about PR's failing in the CI.
v1: #2067
=> docs: add `code review` section [V2]

docs/source/ReferenceGuide.rst
We were lacking a clearer explanation on the pre/post job and pre/post
tests interface.  When they're executed, and under which conditions
they'll be attempted.
---
Changes from v1 (#2083):
* Mention that during a job's pre plugin execution, some conditions such as signals can interrupt them
* Mention which conditions can abort job's post plugin execution
=> Docs: add section on pre/post job and pre/post tests [v2]

docs/source/ReferenceGuide.rst, docs/source/Replay.rst, docs/source/ResultFormats.rst, docs/source/WritingTests.rst, docs/source/optional_plugins/varianter_yaml_to_mux.rst
A collection of fixes in various parts of the documentation.
---
Changes from v1 (#2079):
* Change commit message about JSON support to yaml_to_mux
=> Docs: misc fixes [v2]

spell.ignore
=> spell: Add missing word

avocado/core/jobdata.py, avocado/core/jobdata_compat_36_to_52.py, avocado/core/mux.py, spell.ignore
Spell fixes and exception for the 53 release.
=> spell v53: fixes and exceptions

avocado/core/tree.py, avocado/plugins/variants.py, avocado/utils/asset.py, avocado/utils/kernel.py, requirements-travis.txt, selftests/checkall, selftests/functional/test_basic.py, selftests/unit/test_data_structures.py, selftests/unit/test_vm.py, selftests/unit/test_xunit.py
Update avocado's CI scripts to use inspektor 0.4.5.
=> Update CI scripts to use inspektor 0.4.5

avocado/utils/memory.py
This module has a number of functions aiming to retrieve and/or
convert values from /proc/meminfo. It's time to create a more robust
representation of /proc/meminfo. This commit creates a MemInfo class,
instantiated in a meminfo object.
The MemInfo class carries one attribute for each item in /proc/meminfo.
Each attribute is in fact an instance of the _MemInfoItem class, which
contains attributes to expose the item value. The basic 'value'
attribute will show the value as is. The additional attributes will
show the converted value, according to the selected unit.
Usage:
>>> from avocado.utils import memory
>>> memory.meminfo
<avocado.utils.memory.MemInfo object at 0x7fe8e737f250>
>>> dir(memory.meminfo)
['Active', 'Active_anon_', 'Active_file_', 'AnonHugePages',
'AnonPages', 'Bounce', …
=> utils.memory: create a meminfo object [v3]

avocado/utils/network.py
Moved from avocado-virt, this seems like a useful addition to the
avocado utility libraries.
=> [POST_LTS] avocado/utils/network.py: introduce PortTracker

avocado/utils/memory.py, avocado/utils/multipath.py, avocado/utils/vmimage.py, spell.ignore
Just the usual spelling fixes and additions to the ignore list.
=> Spelling fixes

avocado/core/data_dir.py, avocado/core/job.py, avocado/plugins/replay.py, avocado/plugins/run.py, optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py, selftests/unit/test_job.py, selftests/unit/test_jsonresult.py, selftests/unit/test_xunit.py
And, a `yaml_to_mux` fix that came along the way.
---
Changes from v1 (#2222):
* Added try/finally block in test_job_dryrun_no_base_logdir to make sure base log dir is cleaned up
=> Job: collection of fixes related to logdir and dry run [v2]

selftests/unit/test_jobdata.py
=> selftests/unit/test_jobdata.py: Remove unused msg variable

Makefile
Trivial typo correction for the Makefile.
Signed-off-by: Po-Hsu Lin <po-hsu.lin@canonical.com>
=> Makefile: typo correction

avocado/core/test.py, avocado/utils/astring.py, selftests/unit/test_test.py, spell.ignore
=> spell: Fix incorrect spelling

docs/source/GetStartedGuide.rst, docs/source/WritingTests.rst
Some things I noticed while doing the docs upkeep.
=> docs: Some fixes from docs upkeep

python-avocado.spec
Fix YAML loader package, and package golang plugin.
=> Release 55 packaging fixes

avocado/utils/vmimage.py, docs/source/index.rst, docs/source/utils/index.rst, docs/source/utils/vmimage.rst
v3:
- Split the docs commit.
- Fix docs text.
- Create docs section for `Custom Image Provider`.
v2:
- Docs.
v1: #2277
=> vmimage: make the list of providers expandable [v3]

docs/source/SubclassingAvocado.rst, docs/source/index.rst
Let's document the best practices on subclassing Avocado with some real-world examples.
=> docs: Subclassing Avocado

avocado/utils/multipath.py
Added fail_path() and reinstate_path() functions which fail given
multipath disk and reinstate the multipath disk respectively.
Used wat_for() instead of giving a random sleep time.
=> Added two more functions to multipath.py library file

avocado/core/dispatcher.py, avocado/utils/gdb.py, avocado/utils/wait.py, selftests/checkall, selftests/unit/test_job.py
Recently our sources were polluted with W0102, let's clean them up and add `make check` to avoid further intoxication.
=> pylint: Avoid W0102

avocado/utils/software_manager.py
Patch adds required methods in YumBackend, ZypperBackend and AptBackend for creating a ready-to-build directory
* v1 #2290  
* v2 #2325
=> Added required methods for ready-to-build source directory [v3]

avocado/core/app.py, avocado/core/test.py, avocado/utils/process.py, avocado/utils/software_manager.py, spell.ignore
=> spell: Fix typos and update spell.ignore

avocado/core/tree.py, selftests/unit/test_tree.py
The `avocado.core.tree` module is the foundation to a lot of important functionality in Avocado, including parameters and the yaml_to_mux implementation of the variants interface.
This adds documentation and tests to the `TreeNode` class.
=> Tree: docs and tests

examples/tests/errortest_nasty3.py, optional_plugins/html/avocado_result_html/__init__.py, requirements-travis.txt, requirements.txt, scripts/avocado, scripts/avocado-run-testplan, selftests/unit/test_xunit.py
Another collection of miscellaneous fixes for the Python 3 port.
=> Python 3 port: (another) collection of fixes

avocado/core/job.py, avocado/utils/process.py, setup.py
A collection of miscellaneous improvements collected "along the way" during other work.
=> Miscellaneous improvements

avocado/utils/filelock.py, selftests/unit/test_safeloader.py
Just another set of Python 3 port fixes.
=> Python3 port: safeloader and filelock fixes

optional_plugins/html/avocado_result_html/__init__.py, optional_plugins/html/avocado_result_html/resources/templates/report.mustache
Count WARN in to calculate the success rate in the HTML report.
=> html: add warn in success rate

optional_plugins/html/avocado_result_html/__init__.py, optional_plugins/html/avocado_result_html/resources/templates/report.mustache
Success rate to use the following formula:
( PASS + WARN ) / ( TOTAL - SKIP - CANCEL ) * 100
=> html: rework success rate

avocado/core/test.py, selftests/unit/test_runner_queue.py
v2:
- Include unit test.
v1: #2423
=> test: include 'whiteboard' in preserved parameters [V2]

optional_plugins/varianter_yaml_to_mux/tests/test_multiplex.py, selftests/functional/test_basic.py, selftests/unit/test_utils_iso9660.py, selftests/unit/test_utils_partition.py
Just a collection of miscellaneous fixes to some selftests.
=> Selftests: miscellaneous fixes

avocado/core/sysinfo.py, selftests/functional/test_output.py, selftests/functional/test_standalone.py, selftests/functional/test_utils.py
This is the third batch (not a v3) of miscellaneous test (and other) fixes, mostly necessary for the Python 3 port.
=> Selftests: miscellaneous fixes (3rd batch)

avocado/core/dispatcher.py
Currently almost each "Dispatcher" implements it's own "map_method",
some allow to log tracebacks, some doesn't... Let's implement 2 main
variants, one simple without reporting the results, the other with
support for deepcopying of the arguments and returning the list of
results and use them in all dispatchers.
The main difference against previous version is that all dispatchers
will log the traceback (to avocado.debug) and that instead of individual
arguments it supports *args.
=> dispatcher: Unify the map_method implementations

avocado/plugins/tap.py
Those fixes were part of https://github.com/avocado-framework/avocado/pull/2453 reviewed already by @apahim and @clebergnu.
=> Couple of TAP results fixes

avocado/core/varianter.py, optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/mux.py, selftests/functional/test_basic.py
This is the fifth batch (not a v5) of miscellaneous test (and other) fixes, mostly necessary for the Python 3 port.
=> Selftests and misc fixes (5th batch)

avocado/etc/avocado/avocado.conf, avocado/plugins/run.py, optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/mux.py, optional_plugins/varianter_yaml_to_mux/tests/test_mux.py, selftests/functional/test_loader.py
This is the sixth batch (not a v6) of miscellaneous test (and other) fixes, mostly necessary for the Python 3 port.
=> Selftests and misc fixes (6th batch)

avocado/core/test.py, selftests/functional/test_basic.py, selftests/functional/test_job_timeout.py, selftests/functional/test_loader.py, selftests/functional/test_output.py
This is the seventh batch (not a v7) of miscellaneous test (and other) fixes, mostly necessary for the Python 3 port.
=> Selftests and misc fixes (7th batch)

avocado/core/tree.py, avocado/utils/process.py, optional_plugins/varianter_yaml_to_mux/tests/test_mux.py, scripts/avocado, selftests/unit/test_utils_process.py
This is the eighth batch (not a v8) of miscellaneous test (and other) fixes, mostly necessary for the Python 3 port.
=> Selftests and misc fixes (8th batch)

avocado/core/dispatcher.py, spell.ignore
As part of the v59 release process.
=> spell fixes

docs/source/conf.py, examples/tests/cabort.py, examples/tests/datadir.py, examples/tests/gdbtest.py, examples/tests/linuxbuild.py, optional_plugins/varianter_pict/avocado_varianter_pict/__init__.py, spell.ignore
A small collection of simple fixes in preparation for the 59.0 release.
=> Pre-release 59.0 fixes

avocado/utils/data_structures.py, avocado/utils/memory.py, selftests/unit/test_data_structures.py
v2:
- Added selftest.
- More strict about the `data` input format.
v1: #2495
=> Introducing the DataSize object [V2]

optional_plugins/loader_yaml/avocado_loader_yaml/__init__.py
This PR adds few little improvements that could simplify my mux-suites.
=> optional_plugins.loader_yaml: Few little improvements

python-avocado.spec
This is a collection of cleanups and prep work for the upcoming Python 3 RPM packages.
=> RPM: cleanups and Python 3 packaging prep work

avocado/utils/distro.py
We need compare the length instead of the tuple
Signed-off-by: Junxiang Li <junli@redhat.com>
=> Fix the regex error

avocado/utils/process.py
Signed-off-by: Junxiang Li <junli@redhat.com>
=> Minorfix: Fix the string_types 

avocado/utils/kernel.py, examples/tests/linuxbuild.py, examples/tests/linuxbuild.py.data/linuxbuild.yaml
Signed-off-by: William Tambe <william.tambe@amd.com>
=> Extend avocado/avocado/utils/kernel.py to include kernel install [v2]

optional_plugins/html/avocado_result_html/__init__.py
Collection of fixes for the sprint 60.
=> Sprint #60 fixes

python-avocado.spec
And a number of other RPM package fixes.
=> RPM Packages: add requirements for versioned sub-packages

selftests/functional/test_thirdparty_bugs.py
As it was done in d2b4edc, Python 3.4 needs a string to be passed to
json.loads() (and, indirectly, to json.load()).  Different from
d2b4edc, the content we fetch externally may be able to tell us the
encoding that is used.
Let's use that information, if available, to decode the stream of
bytes into a string that is acceptable to json.loads().
=> selftests/functional/test_thirdparty_bugs.py: feed string to json

avocado/utils/external/gdbmi_parser.py, examples/tests/gdbtest.py
A couple of fixes related to the example gdbtest.py.
=> gdbtest.py Fixes

requirements-travis.txt
=> Travis-CI: pin pycodestyle version

avocado/utils/memory.py
Added support to pass full string of block id like 'memory234',
it saves few steps of the user to find the memory blocks and call
this functions to hotplug/unplug
=> Use complete string for the block id to hotplug/hotunplug

avocado/utils/software_manager.py
Signed-off-by: chunfuwen <chwen@redhat.com>
=> Python 3: fix re.findall() using string pattern on a bytes-like object

Makefile, python-avocado.spec, requirements-travis.txt, selftests/checkall, selftests/functional/test_replay_basic.py
Just a number of Makefile, specfile and checkall fixes.
v1: https://github.com/avocado-framework/avocado/pull/2605
Changes:
```yaml
v2: New commit to require inspekt with output fix
```
=> Misc build and check fixes [v2]

selftests/unit/test_utils_memory.py
=> selftest: Fix line-wrap

avocado/utils/cpu.py, selftests/unit/test_utils_cpu.py
Add methods to get/set cpuidle states
in host and selftests for the method.
=> Add methods to get/set cpu_idle states

avocado/utils/asset.py
=> utils.asset: Little optimization of _get_writable_cache_dir

avocado/utils/pci.py, selftests/unit/test_utils_pci.py
This adds a little speedup for "get_slot_from_sysfs" and also treats the generic exception in case of incorrect value.
=> Two little tweaks to get_slot_from_sysfs

avocado/utils/service.py, selftests/unit/test_utils_service.py
Only rebased (no clashes) https://github.com/avocado-framework/avocado/pull/2640#pullrequestreview-127944371
=> utils.service: add systemd options, make service calls safer[ v2]

docs/source/GetStartedGuide.rst, docs/source/OtherResources.rst, docs/source/optional_plugins/avocado_ec2.rst, docs/source/optional_plugins/azure.rst, docs/source/optional_plugins/index.rst
Let's update our "other resources" section.
=> docs: Add info about some external resources

examples/testplans/release.json
First 2 commits are minor adjustments, the last 2 commits are probably controversial but I don't see a point in spending time on those projects, unless we decide to re-open them again.
=> Some testplan adjustments

avocado/utils/cpu.py
Add method to change given cpu frequency governor systemwide
and choose a random available one if special governor value
`random` is given.
=> Add method to set/get cpu frequency governor

.travis.yml
This PR adds a number of jobs of different Python versions to our Travis-CI jobs.
=> Travis-CI: add Python versions

docs/source/OtherResources.rst
=> docs: Add link to OpenPowerHostOs tests

avocado/core/job.py
The title says it all: just a collection of refactors and docstring improvements.
=> Job: simple refactors and docstring improvements

examples/testplans/release.json, selftests/functional/test_streams.py
A collection of fixes for upcoming release 64.0
=> Fixes for upcoming release 64.0

selftests/functional/test_thirdparty_bugs.py
Just a couple of minor improvements to the thirdparty selftests.
=> Minor improvements to the thirdparty selftests

optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py
Remove code that is not used, or not necessary.
=> Yaml to Mux: remove unused code

avocado/utils/linux_modules.py
1- pep8 issue fixed 
2-added utilility that retun module directory
of running kernel
=> Added module utility

selftests/run
To non-parallel execution script.
=> Selftests: add html optional plugins tests

avocado/utils/process.py, selftests/unit/test_utils_process.py
This change makes possible to call kill_process_tree() function with
pid of sudo enabled processes and it also makes possible handle timeout of
subprocesses called with sudo=True.
Both cases now use a new function created in process module to return
the user owner id of a pid (get_owner_id).
For the case of subprocesses run with sudo=True it was necessary adjust
the send_signal() method of SubProcess class so it can send the signal
for sudo process child.
Reference: https://trello.com/c/ROPWdFFr
---
Changes from v1 (#2854)
* Use of new function created in other PR `get_owner_id()` to 
check sudo enabled process;
* Exception handling on `SubProcess.send_signal()` method 
when dealing with sudo enabled process;
* Minor method renaming;
* A …
=> Handles killing process run as sudo [v2]

optional_plugins/loader_yaml/avocado_loader_yaml/__init__.py
This reverts commit e6c3dad88732346a0c1cdbf506c672aed9199d86.
=> Revert "optional_plugins: Use simple "copy" in "loader_yaml" for args"

avocado/core/safeloader.py, avocado/utils/distro.py, optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py, spell.ignore
This change fix some spelling errors and add to the list os ignoring
words some new cases
=> Fix some spelling errors

avocado/core/loader.py, avocado/core/runner.py
=> Simple refactors related to test loader and parameters

avocado/utils/vmimage.py, selftests/unit/test_utils_vmimage.py
This change adds a functional version of OpenSUSE vmimage provider.
Because of some specific aspects of OpenSUSE versioning this provider
version works properly with most recent known versions (42.3, 42.2. 42.1
and 15.0) and should work properly with future versions as well (15+).
This provider version also don't work with Tumbleweed (rolling release)
versions, only with Leap versions. Because for tests it's better to
change one thing at time, the rolling release is not a version supported
right now.
Reference: https://trello.com/c/i2TSbT3M
=> Adds OpenSUSE vmimage provider

avocado/plugins/xunit.py, selftests/unit/test_xunit.py
For a long time I don't see outputs of some tests and finally got to look at it. Spoiler alert, it's py3k fix :smile:
=> plugins.xunit: Python3 fixes

selftests/functional/test_lv_utils.py
This makes a few style changes, and some simplifications and reliability improvements for the `lv_utils` module selftests.
=> lv_utils: selftest improvements

avocado/utils/lv_utils.py
First batch of cherry-picks from #2859.  These have been reviewed, and being put in a separate PR to allow it to go though CI.
=> LV utility extensions - batch 1

avocado/utils/lv_utils.py
Second batch of cherry-picks from #2859. These have been reviewed, and being put in a separate PR to allow it to go though CI.
=> LV utility extensions - batch 2

avocado/utils/lv_utils.py
Third and last batch of cherry-picks from #2859. These have been reviewed, and being put in a separate PR to allow it to go though CI.
=> LV utility extensions - batch 3

avocado/utils/process.py, selftests/unit/test_utils_process.py
When using the "process.kill_process_tree" it might be useful to wait
for all of the pids to die.
v1: https://github.com/avocado-framework/avocado/pull/2924
Changes
```yaml
v2: Replace "wait" argument for "timeout"
v2: Use "negative, 0, positive" numbers instead of None, False, positive
v2: Use 0.01s sleep instead of 0.1
v2: Use the same (0.01s) step for final wait_for (instead of 1s)
v2: Raise RuntimeError in case of timeout
v2: Improved selftest (check for time.sleep calls)
v2: Human-friendlier selftest names
v2: Rebased
```
Not changed:
```yaml
v2: Parameter to adjust internal-sleep-time as at this point I don't think it's useful
enough and people can always ask for improvement.
```
=> avocado.utils: Allow waiting for pid(s) to die [v2]

avocado/utils/distro.py, avocado/utils/software_manager.py, selftests/unit/test_utils_software_manager.py
A small collection of fixes to get `provides()` working on Debian/Ubuntu + Python 3.
=> Software manager: misc fixes

optional_plugins/html/avocado_result_html/__init__.py, python-avocado.spec
A fix for EL7 and the SPEC file bits.
=> HTML plugin: RPM build related updates

avocado/core/safeloader.py, selftests/unit/test_loader.py
While working on the loader and changes to the tags mechanism, a number of cleanup and refactors became apparent.
=> Loader: tests improvements

avocado/utils/disk.py, selftests/unit/test_utils_disk.py
This change introduces two new utility functions related with
filesystems. One function returns all filesystem types supported by the
running kernel and the other returns the filesystem type of a given
mount point.
---
Changes from v3 (#2968)
* fix tests (mocking builtin open function) on Python 3.4
Changes from v2 (#2967)
* squashed all changes in only one commit because of lint error in previous commits
Changes from v1 (#2962)
* squashed my changes
* try fix lint errors
=> utils.disk: Adds utility functions related to filesystems [v4] 

spell.ignore
=> Adds new words to spell check ignore list

avocado/core/safeloader.py
The "discovery" with/without class_name given are really different
use-cases. Let's split them. Currently that means lots of redundant
code, but it'll allow some cleanups later.
=> safeloader: Split the discovery with and without class_name given

avocado/core/loader.py
As commented in #2986 this change is still valuable so I've decided
to open this PR with only the minor refactor related to loader.
=> loader: simplifies file name check to be processed

avocado/core/output.py
=> Be a bit more informative about plugin loading failures

docs/source/optional_plugins/varianter_yaml_to_mux.rst
This change adds a new section to yaml to mux documentation about how to
inject values to the final multiplex tree using --mux-inject argument.
Reference: https://trello.com/c/4souBmiE
Signed-off-by: Caio Carrara ccarrara@redhat.com
---
Changes from v1 (#2999):
* Added practical examples and fix typo
=> yaml_to_mux: adds documentation about mux-inject [v2]

avocado/utils/process.py
Signed-off-by: Junxiang Li <junli@redhat.com>
=> Minorfix: Fixup the type error

Makefile, Makefile.include
Just a small collection of makefile related fixes and style improvements.
=> Makefile fixes

README.rst, docs/source/GetStartedGuide.rst
Let's publicize the COPR repo, both how to use it and the build
status, on our docs.
=> Docs: add reference to COPR repo and build status

README.rst, docs/source/GetStartedGuide.rst
A quick review on the installation docs shows that the plugins/packages list need an update.
=> LTS prep: update plugins and packages

avocado/utils/gdb.py, avocado/utils/iso9660.py, avocado/utils/process.py
Collection of fixes to alerts spotted by lgtm.com.
=> Collection of fixes to alerts spotted by lgtm.com

README.rst
Besides Copr, which provides a build status badge, let's also
(proudly) display the ratings and issues that lgtm gives us.
=> README: add build and quality badges

avocado/utils/genio.py
Added append_file, append_one_line functions to genio.
There are situations where files with more than one line
are to be created with some filtered data. In those
situations, the existing functions namely write_file,
write_one_line are not helping.
Signed-off-by: Nageswara R Sastry <rnsastry@linux.vnet.ibm.com>
=> genio: Added function append to file

.travis.yml, Makefile, optional_plugins/loader_yaml/tests/test_yaml_loader.py, selftests/unit/test_utils_cloudinit.py
These are some fixes related to the selftests that came up while working on the next version of the test runner.
=> Selftests: prepare for N(ext) runner

avocado/core/runner.py, selftests/unit/test_runner_queue.py, selftests/unit/test_test.py
This is just a collection of minor changes found while working on deeper changes to the runner and test modules.
=> Runner and test: misc minor changes

avocado/utils/configure_network.py
This patch generates network config file when IP address, interface
name and netmask is provided.
=> Netowrk config utlity patch

avocado/utils/lv_utils.py
lv_utils: adding a method to reactivate vg. It also has the option
to specify whether to export and import vg before activating or not.
=> Adding a method to reactivate vg in lv_utils

avocado/utils/file_utils.py, avocado/utils/software_manager.py
These are some useful utilities we developed for our own test suite that are generalizable to avocado utils and could be used by other test suites too.
=> Util extensions

setup.py
=> Formalize support for Python 3.7

avocado/core/loader.py
A collection of small fixes related to the loader code.
=> Loader: misc minor fixes

optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py
Usage of SafeLoader for ymal file instead of normal Loader, because Loader may construct an arbitrary Python object and that is not safe.
Reference: https://trello.com/c/1tTwO1Tu
=> Yaml_to_mux SafeLoader

avocado/core/nrunner.py, optional_plugins/varianter_pict/avocado_varianter_pict/__init__.py, selftests/functional/test_loader.py
Nothing major here, just a collection of misc small fixes.
=> Misc small fixes

avocado/plugins/list.py, avocado/plugins/run.py, man/avocado.rst
The current help given on tag related options is slightly out of sync, let's update them.
=> Tags: update of help content

avocado/core/nrunner.py, avocado/plugins/nrun.py
Some usability improvements for the (still experimental) N(ext) Runner.
=> N(ext) Runner: usability improvements

.travis.yml, optional_plugins/golang/avocado_golang/__init__.py, optional_plugins/golang/setup.py, optional_plugins/golang/tests/src/countavocados/countavocados.go, optional_plugins/golang/tests/src/countavocados/countavocados_test.go, optional_plugins/golang/tests/test_golang.py
This simple test help us to not break this plugin.  More tests
are expected to be added later.
=> Golang plugin: add a test for the loader

README.rst, selftests/run_coverage
A collection of small improvements to the code coverage support.
=> Code coverage: small improvements

avocado/core/nrunner.py, avocado/plugins/nrun.py, selftests/unit/test_nrunner.py
A collection of misc improvements, in preparation for the metadata support changes.
=> Nrunner: misc improvements

avocado/core/nrunner.py, avocado/plugins/nrun.py, selftests/unit/test_nrunner.py
This improves the current state of Runnable serialization.  Further improvements are on the pipeline, including proper support for keyword arguments and more complex data types.
=> nrunner: runnable serialization

avocado/utils/configure_network.py
added type to the script for infiniband.
=> Ip configure handle for infiniband interface

avocado/utils/configure_network.py
Added ping check, set mtu value in host and peer machine and
get peer interface from peer ip function.
=> Added four new function to configure_network file.

optional_plugins/golang/avocado_golang/__init__.py, optional_plugins/golang/tests/src/countavocados/countavocados_test.go, optional_plugins/golang/tests/test_golang.py
This adds support for running Go lang examples, which are very much like tests.
=> Go lang: support for examples

avocado/utils/configure_network.py
function to vreate configuration file for IPV6 address.
=> Adding function to create ifcfg- file for IPV6 configuration.

python-avocado.spec
Due to the lack of some packages on EL and EPEL 8, a few plugins are
not enabled (when compared to the Fedora builds).
Because only EL 8 is supported (due to Python 3 only requirements),
we're not enforcing any version check.  This may be needed in the
future, but it's probably a problem for the not so immediate future.
=> SPEC: add support for EL 8 packages

avocado/utils/multipath.py, avocado/utils/pci.py
Updating pci and multipath utils to address byte to string
conversion.
=> Addressing byte to string conversion on utils

avocado/utils/configure_network.py
removed self form ping_check and set_mtu_host function.
=> Removing self from ping_check and set_mtu_host

avocado/utils/multipath.py, avocado/utils/pci.py
for fixing this error, ERROR: [Errno 8] Exec format error
added shell=True in script.
=> added shell=True in process.run for pci and multipath file.

avocado/utils/multipath.py
Added new methods for multipath-tool like suspend, resume, remove,
Add etc to make the multipath test easy.
=> Added new library functions for multipath-tool

avocado/utils/multipath.py
Added two more functions which were missed in last commit.
=> More Functions into multipath.py

.pylintrc, avocado/core/runner.py
A simple pylint configuration tweak and a warning fix.
=> Pylint configuration improvement and warning fix 

docs/source/guides/user/chapters/loaders.rst
=> Docs: fill in basic information about Test Loaders

avocado/utils/asset.py
=> Misc avocado.utils.assets style improvements

docs/source/blueprints/BP001.rst, docs/source/index.rst
This is the outcome of the discussions on the RFC "Configuration by
convention". It is still a draft and after revised and approved we can
start working on the specific issues.
-----
* Fixed sections
* Changed status to Approved
* Included a menu entry on documentation menu for blueprints
=> docs/blueprints: First blueprint: Configuration by convention [v2]

docs/source/blueprints/BP001.rst
=> BP001: fixed typo

avocado/utils/asset.py
This is the first of a series of PRs to refactor the Asset class to allow future extensions.
What is covered in this PR:
- change `log` variable name to uppercase;
- removes unnecessary verification of None type;
- rename _compute_hash to _create_hash_file;
- moves methods to alphabetic order and adds docstrings
=> Misc asset: Initial Asset class refactor.

docs/source/quickstart/index.rst
Re-add the _Build and Quality Status_ section with badges to the README file.
=> Re-add build and quality badges on README.

avocado/core/job.py, avocado/plugins/nrun.py, avocado/plugins/runner_nrunner.py
=> Correct small spell problems on docstrings.

docs/source/releases/75_0.rst
This adds a missing (by mistake) release notes document that should
have been part of the 75.0 tag/release.
=> Release Notes for version 75.0

avocado/utils/process.py
This contain trivial changes on the docstring of `utils/process.py` functions.
=> utils/process: Improve/fix documentation

avocado/utils/kernel.py
Currently the KernelBuild.build() does not allow to specify
the number of jobs (make -j option). But one may want to set
that in order to speed up the build time. So in this change
it was added the njobs parameter to the method.
---
Changes v1 -> v2:
* If njobs is None then pass '-j' without value
* default value is multiprocessing.cpu_count()
v1: #3392
=> avocado/utils/kernel.py: allow to set number of jobs [v2]

avocado/utils/software_manager.py, setup.py
Provides some improvements to utils/software_manager and clean ups.
Changes:
* v1: #3552
* v2: #3571
=> utils/software_manager: one improvement and some clean ups [V3]

avocado/core/nrunner_tap.py, avocado/utils/kernel.py, spell.ignore
=> Fix minor spelling problems for next release.

avocado/utils/pmem.py
Patch fixes typo from a recent change
=> pmem.py: Fix typo from recent change

examples/tests/assets.py
=> Trivial fixes and improves to assets example test

avocado/utils/cloudinit.py
Improves the API documentation.
=> utils/cloudinit: documentation improvements

avocado/plugins/assets.py
Adjusts the asset plugin to handle the correct exception raised by the Asset class.
=> Misc Asset: adjust plugin to handle the correct exception.

avocado/core/nrunner.py, avocado/utils/pmem.py, avocado/utils/ssh.py, selftests/functional/test_test_fetch_asset.py, spell.ignore
=> Fix spelling for release 77.0.

avocado/utils/service.py
More improvements to documentation, now for `avocado.utils.service`
=> Utils service doc improvements

avocado/utils/ssh.py
I, as a test writer, would like to have the status of the command auto-checked by `avocado.utils.ssh.Session.cmd()` so that I don't need to check myself on every call.
This change adds the ignore_status parameter to
Session.cmd() method. If ignore_status=False then
it raises an utils.process.CmdError in case the
command (or something with the ssh connection) failed.
=> utils/ssh: Add ignore_status parameter to cmd()

avocado/plugins/nrun.py
By default, nrun will try to run always in parallel, and sometimes we
need to run the tasks in serial. This will add the --parallel-tasks option to
nrun command.
----
* Before was --serial (bool), now is --parallel-tasks (integer)
=> nrunner: added --parallel-tasks option to nrun [v2]

optional_plugins/html/avocado_result_html/__init__.py, optional_plugins/html/avocado_result_html/templates/avocado_html.js, optional_plugins/html/avocado_result_html/templates/results.html, optional_plugins/html/avocado_result_html/templates/style.css
Clean up the plugin code following HTML5 standards, turn all tooltips into
Bootstrap popovers, improve escaping of HTML code in the template and
add support for resizable columns.
=> Improvements to the HTML report

avocado/plugins/assets.py, avocado/utils/asset.py, selftests/functional/test_plugin_assets.py, selftests/functional/test_utils_asset.py
=> Misc Asset: fix hash creation for the asset location URI

avocado/plugins/nrun.py
This method was not being used
=> nrunner: remove unnecessary method

optional_plugins/html/setup.py, optional_plugins/robot/setup.py, requirements-selftests.txt
This is a combination of both #3704 and #3673.
=> [LTS] Package requirements

avocado/core/nrunner.py, optional_plugins/varianter_cit/avocado_varianter_cit/Cit.py, selftests/.data/get_data.py.data/get_data.json, selftests/functional/test_getdata.py, selftests/functional/test_output.py, selftests/functional/test_output_check.py
Collection of misc minor and style fixes from selftests, Cit Varianter plugin and nrunner.
=> Misc minor fixes

selftests/functional/test_basic.py, selftests/unit/test_utils_cpu.py, selftests/unit/test_utils_cpu.py.data/armv7, selftests/unit/test_utils_cpu.py.data/armv8, selftests/unit/test_utils_cpu.py.data/i386, selftests/unit/test_utils_cpu.py.data/power8, selftests/unit/test_utils_cpu.py.data/power9, selftests/unit/test_utils_cpu.py.data/risc_v, selftests/unit/test_utils_cpu.py.data/s390x, selftests/unit/test_utils_cpu.py.data/s390x_2, selftests/unit/test_utils_cpu.py.data/s390x_3, selftests/unit/test_utils_cpu.py.data/x86_64, selftests/unit/test_utils_process.py
=> Misc selftests improvements and cleanups 

selftests/unit/test_utils_memory.py
A collection of minor style improvements for `selftests/unit/test_utils_memory.py`.
=> avocado.utils.memory selftests minor style improvements 

avocado/core/safeloader.py, selftests/unit/test_safeloader.py
=> Safeloader: add missing slash to the requirements regular expression

docs/source/guides/writer/chapters/writing.rst
=> Documentation: update test writer `Fetching asset files`

avocado/core/nrunner.py
Python 3.8 started to show the following deprecation warning:
"DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead"
This changes the code in the nrunner to comply with "async def".
=> Nrunner: fix @coroutine deprecation warning for Python 3.8

docs/source/future/core/nrunner.rst
This gives a more in-depth description of the current runner
implementation, and how it contrasts with the nrunner architecture.
This serves as an update to the current documentation, and not as
a roadmap/blueprint for future nrunner related development.
---
Changes from v1 (#3775):
* Fixed double "contain" - @willianrampazzo 
* Changed section title - @beraldoleal @willianrampazzo 
Part of #3754
=> N(ext)Runner docs: update documentation describing current status [v2]

docs/source/quickstart/index.rst
Code climate has more metrics related to code quality and maintainability.
Adding this badge to README.
=> README: Adding a maintainability badge

avocado/core/nrunner.py, selftests/unit/test_datadir.py, spell.ignore
=> Fix spelling for release 79.0.

optional_plugins/varianter_pict/avocado_varianter_pict/__init__.py
A collection of Python 3 fixes including handling string/bytes and
using builtin zip.
=> PICT plugin: Python 3 fixes

avocado/core/future/settings.py, avocado/core/nrunner.py, avocado/utils/cpu.py, avocado/utils/network/interfaces.py
Multiple warnings during `make html` for the documentation.
=> Docs: fix make html warnings.

avocado/plugins/nrun.py
This will make the spawner that was executed available on `nrun.spawner`
namespace on config parsed dictionary.
**Changes from v1:**
* Small sentence improvement on help message;
* Lowercase "Podman" and "Process";
* Renamed the long arg to `--spawner`
=> nrunner: convert --podman-spawner into --spawner=podman (v2)

avocado/utils/multipath.py
get the wwid for the given mpath user friendly name.
Signed-off-by: Hariharan T S <hari@linux.vnet.ibm.com>
=> Add funtion to get wwid for the given userfriendly mpath.

avocado/plugins/runner_nrunner.py
While it's not possible for the current nrunner plugin implementation
to kill tasks, it's possible to abort a job execution between tasks.
This implementation does just that, also adding a missing call to
end the result tracking of tests, so that tests not executed are
listed as SKIPs.
If you have a test that runs for about 1 second, and do:
$ avocado run --test-runner=nrunner --job-timeout=2s test test test test
It should produce:
RESULTS    : PASS 2 | ERROR 0 | FAIL 0 | SKIP 2 | WARN 0 | INTERRUPT 0 | CANCEL 0
=> nrunner plugin: implement support for job level timeout

avocado/utils/lv_utils.py
The function "get_diskspace()" calculate the size of a single disk.
deprecating this function intead of replacing it with new function.
And adding a new function get_disks_total_space(), which returns the
size of multiple disks combinely.
=> calculating and return the size multiple disk

optional_plugins/glib/avocado_glib/__init__.py
=> future.settings: glib optional plugin to use the new settings API

avocado/core/future/settings.py, selftests/unit/test_settings.py
Sometimes it is useful to register the argparser after the registration.
This change will allow the registration of command-line argument to
occur after its registration.
=> future.settings: added new method for lazy argparser registration

avocado/core/varianter.py
=> avocado.core.varianter: remove 52lts compatibility

selftests/pre_release/tests/vmimage.py.data/variants.yml
=> vmimage: fixed debian images versions

avocado/core/future/settings.py, avocado/core/job.py, docs/source/releases/57_0.rst, spell.ignore
=> spell fix: Just small spell fixes

.travis.yml, requirements-selftests.txt, selftests/run_coverage
=> codeclimate: enable codecoverage

avocado/core/app.py
Moving them out of the instantce initialization, and into their own
simpler methods.
=> avocado/core/app.py: refactor splitting init method

avocado/core/exceptions.py, avocado/core/job.py, avocado/core/jobdata.py, optional_plugins/html/avocado_result_html/__init__.py, selftests/unit/test_job.py
This is a collection of misc refactors, cleanups and improvements.
=> Job API: misc refactors, cleanups and improvements

.codeclimate.yml
Running bandit locally, we currently have:
Total issues (by severity):
Undefined: 0.0
Low: 81.0
Medium: 85.0
High: 6.0
Total issues (by confidence):
Undefined: 0.0
Low: 49.0
Medium: 11.0
High: 112.0
This should give us extended information about security issues, and
help us to work towards eliminating them.
=> codeclimate: enable bandit plugin

avocado/plugins/replay.py
=> future.settings: make plugins/replay to use the new API

examples/plugins/job-pre-post/mail/avocado_job_mail.py, examples/plugins/job-pre-post/mail/setup.py
=> future.settings: Migrate job pre/post mail example to use the new API.

avocado/core/future/settings.py, avocado/plugins/config.py
=> future.settings: remove old settings reference on plugins/config

examples/plugins/job-pre-post/sleep/avocado_job_sleep.py, examples/plugins/job-pre-post/sleep/setup.py
=> future.settings: Migrate job pre/post sleep example to use the new API.

avocado/core/future/settings.py, avocado/core/parser.py, selftests/unit/test_hintfiles.py
=> future.settings: Migrates hintfiles parser to use the new API

avocado/core/future/settings.py, avocado/core/jobdata.py
=> future.settings: Migrates core/jobdata.py to use the new API

docs/source/guides/user/chapters/configuring.rst, docs/source/guides/user/chapters/datadirs.rst
Those are suggestions from @pevogam.
=> docs: small improvements on configuring documentation

docs/source/guides/user/chapters/installing.rst
=> Docs: remove unnecessary requirements command for source install.

avocado/utils/disk.py
Adding APIs to create and delete loop devices.
=> Adding loop device APIs

avocado/utils/softwareraid.py
Add new utils for softwareraid.
=> utils/softwareraid: Add new utils

avocado/core/suite.py
Empty references should be allowed, because individual loaders can
actually come up with tests without references.  This is the case
for instance of the Avocado-VT loader, when using the `--vt-config`
command line option.
What shouldn't be the normal case, though, and should raise an
exception, is not having any tests at the end of the resolution/loader
execution.  Also, while it at, let's concentrate this behavior in a
single place.
Reference: https://github.com/avocado-framework/avocado/issues/3985
=> Suite: allow empty references

avocado/core/job.py, avocado/core/plugin_interfaces.py, avocado/core/suite.py, avocado/plugins/runner.py, avocado/plugins/runner_nrunner.py, selftests/unit/test_job.py
The subject says it all. Basically some refactoring and prep work to improve consistency when running with multiple test suites.
=> core: prep work and refactoring to accept multiple TestSuites in one job

optional_plugins/loader_yaml/avocado_loader_yaml/__init__.py, optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py, optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/mux.py, optional_plugins/varianter_yaml_to_mux/tests/test_functional.py, optional_plugins/varianter_yaml_to_mux/tests/test_unit.py
A collection of cleanups and optmizations for the Yaml to Mux plugin.
=> Yaml to mux: cleanups and optmizations

optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py, optional_plugins/varianter_yaml_to_mux/tests/test_unit.py
This is a followup of #3999 with a few more cleanups and refactors.
=> Yaml to Mux: further cleanup

docs/source/guides/user/chapters/introduction.rst
Updating documentations for the latest sysinfo changes.
Ref: https://github.com/avocado-framework/avocado/pull/3923
Ref: https://github.com/avocado-framework/avocado/pull/3924
=> sysinfo: Documentation updations.

docs/source/guides/user/chapters/introduction.rst, docs/source/guides/writer/chapters/writing.rst
Signed-off-by: Ethan Mallove <ethanx.a.mallove@intel.com>
=> trivial typo: quotating => quoting

avocado/utils/pmem.py
Patch adds infoblocks function to pmem library
=> Add infoblocks function to pmem library

docs/source/quickstart/index.rst
=> typo lastest->latest

optional_plugins/html/avocado_result_html/__init__.py
Adjust the features options names of HTML Optional Plugin  to comply with the name of other similar result plugins features.
=> HTML Optional Plugin: Adjust the features options name.

docs/source/guides/contributor/chapters/plugins.rst, examples/plugins/cli-cmd/hello/hello.py, examples/plugins/cli-cmd/hello/setup.py
By introducing a real, working, and up to date example and linking it
to the documentation.
=> Plugin documentation: revamp the CLI command example

avocado/plugins/xunit.py, selftests/unit/test_xunit.py
=> XUnit Plugin: fix features names.

optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py
Just a small and quick fix to make lgtm happy.
=> lgtm: removed unused variable to make lgtm happy

avocado/core/future/settings.py
=> future.settings: improved docstring on default value

avocado/utils/cpu.py
Fixes:https://github.com/avocado-framework/avocado/issues/4067
Signed-off-by: Yanan Fu <yfu@redhat.com>
=> utils.cpu.get_version: Fix IndexError: list index out of range

docs/source/guides/contributor/chapters/plugins.rst
Those are suggestions made by @pevogam on #4065.
=> docs: small fixes on documentation

selftests/job_api/test_features.py
Add more features tests to test_feature.py. Also, add a command-line parameter to list features tested.
=> [Job API] Add more features tests to test_feature.py

avocado/core/settings.py
=> avocado/core/settings.py: simple typo fix

avocado/core/job.py
=> core.job: Warn user if job is empty

Makefile, selftests/job_api/test_features.py
Add more features to the test_features.py.
Add the test to the Makefile to run during make check. Adding it to the default runner as nrunner is not running it.
=> [Job API] Add more features tests to test_features.py

avocado/plugins/list.py
=> fixed list output to be lower() and make travis happy

selftests/pre_release/jobs/vmimage.py
=> [Release 81] fix vmimage.py job to conform with test suites.

selftests/pre_release/jobs/timesensitive.py
=> pre_release.timesensitive: Adding status_server uri and using custom TestSuite

selftests/pre_release/tests/vmimage.py.data/variants.yml
=> [Release 81] update vmimage distros versions.

examples/testplans/release/pre.json
Remove deprecated verification on --vm-* and --remote-*.
=> [Release 81] update pre-release testplan

docs/source/guides/user/chapters/logging.rst
=> [Documentation] Clarify use of avocado.app.debug logging stream.

docs/source/guides/user/chapters/advanced.rst
=> [Documentation] Add working example to --wrapper option.

docs/source/guides/user/chapters/operations.rst
This is closing #4106. We have still a few issues to solve there, but I created #4176 and #4177 to track there.
=> docs: Review on user's guide (sections: basic concepts and basic operations)

docs/source/guides/user/chapters/results.rst
=> added a simple note on results specification chapter about spawners

docs/source/guides/user/chapters/loaders.rst
=> docs: fixed gdb examples output

docs/source/guides/contributor/chapters/tips.rst
=> [Documentation] add note to development tips about logging stream.

docs/source/guides/contributor/chapters/contact.rst
=> [Documentation] add GitHub repository to contact information.

docs/source/guides/writer/chapters/parameters.rst, docs/source/guides/writer/chapters/writing.rst
=> docs: Fixed writer/chapters/parameters.rst content

docs/source/guides/contributor/chapters/results.rst
=> [Documentation] fix small documentation typo.

avocado/plugins/runner_nrunner.py
Without this, test errors are reported, but the job status code
is not updated with a failure.  Scripts depending on the job exit
code only would fail to catch errors.
=> nrunner: add a failure status to the job summary on failed tests

docs/source/guides/writer/chapters/writing.rst
When a review of writing tests was done The issue #4167 was found. Because we
are fixing it in #4213 we can update the documentation to be synchronized with
example of SyncTest.
Reference: #4135, #4167, #4213
=> SyncTest documentation

avocado/plugins/list.py
If is in verbose mode, then failed resolutions will be displayed.
This fixes #4165.
=> plugins.list: showing resolutions failures when in verbose mode

docs/source/guides/contributor/chapters/runners.rst
Part of the contributor's guide.
Fixes: https://github.com/avocado-framework/avocado/issues/4194
=> Docs: review of the runner/nrunner section

selftests/pre_release/tests/vmimage.py.data/variants.yml
=> Pre Release 82.0: Update list of variants for vmimage tests

avocado/utils/disk.py
add is_root_device() to disk.py to check root device.
=> add a function to check root device

avocado/utils/network/interfaces.py
the current format is not supported by SuSE distro
=> network cfg file fix

examples/jobs/README, examples/jobs/README.rst
=> Examples: reword the README from the jobs folder to encourage use.

docs/source/guides/contributor/chapters/runners.rst, docs/source/guides/writer/chapters/parameters.rst
This is a fix of small sphinx warnings in the documentation.
=> Doc warnings fix

avocado/core/app.py, avocado/core/output.py, avocado/core/parser.py, selftests/functional/test_basic.py
Like it was done previously to other command line options that would
take 'on' and 'off'.
=> Paginator: turn command line option into a boolean

avocado/utils/dmesg.py, spell.ignore
Patch adds following dmesg utility
1- collect dmesg in a file (either userdefine or library created file)
2- clear dmesg
3- verify_pattern(s) in dmesg
4- verify_dmesg having level check
Signed-off-by: Praveen K Pandey praveen@linux.vnet.ibm.com
=> Patch add basic linux dmesg utility function [v2]

avocado/utils/linux.py
Patch add a library which check selinux enforcing in system or not
=> Patch add a library which check selinux enforcing in system or not

avocado/plugins/runner_nrunner.py
Sometimes we can have a status_server running in a different machine or
port. This patch will introduce the status_server_listen option that
will be used when listening the status, while status_server_uri will be
used to connect to a status server.
This fixes #4269
=> status_server: split status_server_uri logic

avocado/utils/pmem.py
Patch adds daxctl related libraries such as offline-memory, online-memory and reconfigure-device for devdax namespaces
=> utils/pmem.py: Add daxctl related libraries

avocado/plugins/jsonresult.py, avocado/plugins/tap.py, avocado/plugins/xunit.py, optional_plugins/html/avocado_result_html/__init__.py, selftests/functional/test_output.py, selftests/functional/test_streams.py
This is part of a big effort to convert all "string boolean" args to real boolean. Please check BP001 for details.
=> Add deprecation warning messages to "string boolean" args

avocado/core/nrunner_avocado_instrumented.py
It adds support to the timeout class attribute for avocado instrumented tests in nrunner.
Reference:#4257
=> Nrunner support to timeout class attribute

docs/source/blueprints/BP000.rst
After discussions, this is marked as 'approved'.
- Moved from 'draft' to 'approved'
- A lot of changes suggested by @pevogam
=> blueprints: Adding a BP000 - v2

selftests/check.py
And a style-only change for `selftests/check.py`
=> Selftests: increase nrunner interface coverage

avocado/core/loader.py, avocado/plugins/list.py
This is similar to #4347 , but with a new commit fixing the issue that caused the test failures.
=> Restore loader extra listing

python-avocado.spec, selftests/check.py
Most important change is that checking done in RPM `%check` phase will be very close to  `make check`, for increased coverage and consistency.
=> RPM specfile and selftests/check.py improvements

requirements-selftests.txt
Just a couple of changes to the selftests requirements file.
=> Selftests requirements: clean up and update

selftests/pre_release/tests/vmimage.py.data/variants.yml
=> Pre-release: update tested versions of Debian

selftests/pre_release/tests/vmimage.py.data/variants.yml
=> vmimage: bump Debian version

docs/source/index.rst
=> adding bp000 to our documentation

avocado/utils/cpu.py
Rebase and extension of #3660.
=> Utils cpu improvements

docs/source/blueprints/BP000.rst
BP000 documentation rendering fix.
=> BP000 sintax fix

selftests/pre_release/tests/vmimage.py.data/variants.yml
=> pre-release: updating debian versions

avocado/utils/partition.py
This includes the original change from @harish-24 , along with a fix in the handling of loop devices.
=> Partition: handle loop devices and multiple mounts per device

avocado/core/nrunner.py, avocado/plugins/runner_nrunner.py
Added suggestion made here: https://github.com/avocado-framework/avocado/pull/4469
=> [nrunner] small refactor to function and variable name

selftests/functional/test_skiptests.py
In preparation for a bug fix, that will need more tests, let's remove (most) duplication in the current test.
=> Selftests: refactor to the skip tests

examples/testplans/release/pre.json, selftests/pre_release/tests/vmimage.py.data/variants.yml
Couple of minor fixes before release 87.0
=> Pre release (87.0) fixes

examples/testplans/release/pre.json, examples/testplans/release/release.json, scripts/avocado-run-testplan
Couple of leftover fixes detected while running the release test plan for 87.0.
=> Release test plan fixes

avocado/utils/dmesg.py
some of the dmesg error messages which is not actual failure from test,
so wanted to skip those error messages during collect error message
by level.
=> add function to skip dmesg error messages

avocado/core/runners/avocado_instrumented.py
When the exception is raised on the side of the instrumented runner not
inside the test itself, the runner will crash and don't send any message
to the avocado and such an event is not logged into the error log. This
PR handles such event and logs more information about the occurred
exception.
=> Instrumented nrunner error handling

avocado/utils/network/interfaces.py
Adding function to delete any cfg files that are created
during test runs
=> function to remove cfg files

avocado/utils/process.py
Signed-off-by: Akashdeep Dhar <akashdeep.dhar@gmail.com>
=> Used time.monotonic() for utils/process.py timeout

avocado/core/__init__.py, avocado/core/job.py, avocado/core/output.py, avocado/plugins/run.py, selftests/unit/test_job.py
A small number of logging related improvements and fixes.
=> Logging: misc improvements

avocado/utils/software_manager/backends/yum.py, avocado/utils/software_manager/main.py
Adjusts the yum backend log level from the yum module and makes log messages available to others.
=> Software-manager adjustments

avocado/plugins/distro.py
=> fixes bz2 writes when running avocado distro

docs/source/guides/user/chapters/assets.rst
=> [documentation] fix `note` and reword intro of `Managing Assets`

selftests/pre_release/tests/vmimage.py.data/variants.yml
=> pre_release: vmimage: debian bump

man/avocado.rst
Full refresh and update of the avocado man page.
=> Refresh avocado man-page (v2)

Makefile, docs/source/guides/contributor/chapters/environment.rst, requirements-selftests.txt, setup.py
updated v2 from https://github.com/avocado-framework/avocado/pull/4615
=> update packages  required for development (v2)

avocado/utils/vmimage.py
get() method is returning an Image object, let's delegate this to the Image
class.
@clebergnu, I'm aware that we are using this on qemu acceptance tests, if
this is accepted, then we should update there too.
=> utils.vmimage: deprecate vmimage.get() in favor of Image.from_parameters

requirements-selftests.txt
Update all versions to the last released one.
Add a version to netifaces and docutils.
=> requirements-selftests.txt: update versions

avocado/core/safeloader.py, avocado/core/task/statemachine.py
A collection of refactors and cleanups in preparation for fixing issue #4625.  And while at it, an unrelated optimization for TaskStateMachine.
=> Safeloader: refactors and cleanups

docs/source/guides/contributor/chapters/environment.rst
enchant is required by pylint's spellchecker
Reference: #4650
=> docs/contributor's guide: update packages required (enchant)

docs/source/guides/user/chapters/advanced.rst, docs/source/guides/user/chapters/assets.rst, docs/source/guides/user/chapters/concepts.rst, docs/source/guides/user/chapters/configuring.rst, docs/source/guides/user/chapters/datadirs.rst, docs/source/guides/user/chapters/installing.rst, docs/source/guides/user/chapters/introduction.rst, docs/source/guides/user/chapters/loaders.rst, docs/source/guides/user/chapters/logging.rst, docs/source/guides/user/chapters/operations.rst, docs/source/guides/user/chapters/plugins.rst, docs/source/guides/user/chapters/requirements.rst, docs/source/guides/user/chapters/results.rst, docs/source/guides/user/chapters/tags.rst
Some updates I made while reading the user guide with a fix for issue #4635
=> User guide minor update

avocado/core/safeloader/core.py
This splits out duplicate utility code and introduces common utility functions to be reused across the board.
=> Safeloader: utility splits

docs/source/blueprints/BP002.rst
=> [BP002] update the documentation with issues and WIP status

avocado/core/plugin_interfaces.py, avocado/core/test_id.py, avocado/utils/asset.py, avocado/utils/dmesg.py, docs/source/blueprints/BP003.rst
=> [docs] fix most `make html` warnings and some nitpicking.

setup.py
This is an expanded v2 of #4679
=> setup.py updates in clean command to make it more pythonic

setup.py
=> Setup: cosmetic change on clean and Python 3.9 support

avocado/core/safeloader/core.py, avocado/core/safeloader/imported.py, avocado/core/safeloader/module.py, avocado/core/safeloader/utils.py, selftests/unit/test_safeloader_imported.py, selftests/unit/test_safeloader_utils.py
This further splits and reuses code, and improves the coverage for some corner cases found while working on issue #4625
=> Safeloader: further split, and improved test coverage

selftests/pre_release/tests/vmimage.py.data/variants.yml
=> Update vmimage test with current versions of debian.

contrib/scripts/docs-change-home.sh, docs/source/blueprints/BP003.rst, docs/source/guides/user/chapters/introduction.rst, docs/source/guides/writer/chapters/logging.rst, docs/source/guides/writer/chapters/subclassing.rst, docs/source/guides/writer/chapters/writing.rst, docs/source/releases/0_27_1.rst, man/avocado.rst
This just keeps the docs without specific references to specific users and makes `/home/user` the default.
=> Docs: keep /home references agnostic to specific user

examples/testplans/release/pre.json
=> [pre-release] remove duplicated step from pre-release test plan

docs/source/misc/index.rst
This updates the list of known projects using Avocado.  It may serve
as a good reference on how new projects can get started with Avocado.
=> docs: update known projects using Avocado

docs/source/misc/index.rst
POK is a real-time operating system, which is a category not yet on
our list.
=> docs: add POK to the list of known projects using Avocado

avocado/core/runners/avocado_instrumented.py
=> [nrunner] inject run.test_parameters option on Test params

avocado/utils/dmesg.py
Create a class decorator that wraps the test* methods of a class with a method that raises avocado core Failure exception based on DmesgError after checking for a failure at given dmesg level
=> dmesg.py: Add a decorator for test to fail on

selftests/check.py
=> Fix check.py features list

selftests/modules-boundaries.sh, setup.py
=> `modules-boundaries` check in `setup.py lint`

avocado/core/runners/utils/messages.py
The helper method for file messages didn't return value.
=> File message fix

avocado/core/nrunner.py
=> [nrunner] inject run.test_parameters option on exec-test

setup.py
Current setup process is not working when using a virtual env.
This will fix that and also introduce a small code refactoring.
This was "setup: small refactoring (prep work)"
-  Added the last commit fixing #4770.
=> setup: fixes venv and small refactoring (v2)

selftests/functional/plugin/test_logs.py, selftests/functional/test_basic.py
Avocado has a problem with running two jobs which are connected to the
same status server. This problem is reported in #4308. We have two tests
which are affected by this issue because they are running their own
avocado jobs, and it is possible that those tests breaking Travis CI
which is  reported in #4768. This commit fixes those tests by creating
their own status server for their jobs.
Reference: #4308 #4768
=> Nrunner functional tests fix

docs/source/guides/writer/chapters/integrating.rst, docs/source/guides/writer/index.rst
=> [docs] include the documentation on how to use Coverage.py

.github/workflows/weekly.yml, selftests/check.py, setup.py
I have grouped 3 different changes in the same PR because I think they're relatively trivial. Tell me if you find it's a bad idea :-)
At bit of context to the changes in `check.py`. While I don't expect to use the disable options often in our internal CI, they are useful locally when debugging things.
=> Misc updates to setup.py, check.py and weekly ci

selftests/pre_release/tests/vmimage.py.data/variants.yml
=> Update vmimage test with current versions of debian

avocado/core/output.py
=> fix excessive output at the LOG_UI

docs/source/guides/user/chapters/assets.rst
Depersonification and small changes on assets documentations. Addition of `assets register` and `assets fetch` in the documentation.
=> [documentation] Update assets documentation

avocado/core/test.py
Avocado is currently creating the workdir directory at the class
initialization, which means that it's wasted for tests that get
skipped, canceled, or simply don't use them.
To avoid the extra overhead, and possibly leave stale dirs, let's make
the creation of workdir (and the ones used as the basis of workdir)
lazy.
For SIMPLE tests, the test itself can not request the creation of
workdir lazily, so it gets created manually.
=> Test: make workdir initialization lazy

avocado/utils/distro.py
Enable the distro util to have the option to take a populated Session object
that represents a remote machine and detect the remote machine's distro.
Signed-off-by: Cris Forno <fornosoccer12@gmail.com>
=> [utils] distro.py: enable util to detect distro of a remote machine

avocado/core/nrunner.py
I'm working on #4839 and #4840, but first I would like to confirm my understand here.
Please, let me know if this makes sense so I can continue the debugging there.
=> nrunner: not so small docstring fix

avocado/plugins/runner_nrunner.py
This fixes the case where more than one test file is used when running avocado with variants.
Ideally, decoupling variants from runnables would make things more flexible. Issue https://github.com/avocado-framework/avocado/issues/4853 tracks this enhancement.
=> [nrunner] fix runnable copy during task creation for variants

avocado/plugins/runner_nrunner.py
The Avocado nrunner resorts to runners usually made available as
standalone executables.  When those are missing, even if a test
reference is correctly resolved, Avocado won't be able to run them.
Instead of proceeding with an empty test suite (and thus an empty
job), lets flag those early and notify the user about it.
A sample output with these changes look like:
$ ~/.local/bin/avocado run --test-runner=nrunner /bin/true optional_plugins/robot/tests/avocado.robot
JOB ID     : ee65910b3c530d20d9c466cbdbadad14d4d6df3d
JOB LOG    : /home/cleber/avocado/job-results/job-2021-08-19T14.06-ee65910/job.log
Avocado job failed: JobError: Could not find runners for runnables of kind(s): exec-test, robot
Reference: https://github.com/avocado-framework/avocado/issues/4848
Signed-off-by: Cleber Rosa …
=> nrunner: abort job early if missing runners

.github/workflows/prerelease.yml
Not sure if GH is not following symlinks of what. Lets give this a try.
=> prerelease: fix home dir

avocado/utils/network/interfaces.py
Add fuctionality to retrieve a dict of vlans for a given interface, add a vlan
interface given a vlan tag number, delete a vlan interface given a vlan tag
number, and delete all vlans associated with an interface
Signed-off-by: Cris Forno <fornosoccer12@gmail.com>
=> [utils] network/interfaces: add VLAN functionality for an interface

avocado/utils/network/interfaces.py
=> utils.network: minor docstring update (PEP-257)

.github/ISSUE_TEMPLATE/bug_report.md
=> [GitHub] fix spell on bug template

examples/jobs/sleepjob_yaml_to_mux.py
=> [examples/jobs] add an example using yaml to mux

docs/source/guides/user/chapters/advanced.rst, docs/source/guides/user/chapters/concepts.rst, docs/source/guides/user/chapters/installing.rst, docs/source/guides/user/chapters/introduction.rst, docs/source/guides/user/chapters/loaders.rst, docs/source/guides/user/chapters/requirements.rst, docs/source/guides/user/chapters/results.rst
Review the examples and update them to reflect the default runner (nrunner).
=> [docs] update User's Guide for the 92.0 LTS

avocado/utils/iso9660.py, examples/tests/cancel_test.py
Just a couple of fixes caught on/after reviews.
=> Trivial misc fixes

avocado/core/jobdata.py, avocado/plugins/dict_variants.py
Just a fix and a refactor found while looking through the recent commits.
=> Misc fix / refactor

avocado/core/nrunner.py, avocado/core/task/statemachine.py, avocado/plugins/resolvers.py, avocado/plugins/runner_nrunner.py, selftests/functional/test_nrunner_interface.py, selftests/unit/test_nrunner.py
These are misc runner configuration/interface improvements found while working on #5075, but that do not necessarily address the main issue.
=> Misc runner configuration/interface improvements

avocado/core/test.py, avocado/core/utils/loader.py, docs/source/guides/user/chapters/loaders.rst
A couple of cleanups to the test classes at `avocado/core/test.py`.
=> Test cleanups

avocado/utils/network/interfaces.py
Use sysfs param to get the bond interface details and
save the master and slave cfg file
=> get bond interface details and save cfg

avocado/utils/network/interfaces.py
small follow-up for https://github.com/avocado-framework/avocado/pull/4795
cc: @vaishnavibhat
=> utils/network/interfaces.py: Update error message

optional_plugins/resultsdb/setup.py
Fixes: https://github.com/avocado-framework/avocado/issues/5105
=> optional_plugins/resultsdb: set versioned requires

.github/ISSUE_TEMPLATE/bug_report.md
=> GH: new bug reports will receive the 'triage' tag

python-avocado.spec, selftests/unit/utils/test_process.py
Couple of fixes for the release.
=> Release 93 fixes

avocado/utils/archive.py, avocado/utils/cpu.py, avocado/utils/crypto.py, avocado/utils/data_factory.py, avocado/utils/distro.py, avocado/utils/dmesg.py, avocado/utils/file_utils.py, avocado/utils/genio.py, avocado/utils/git.py, avocado/utils/iso9660.py, avocado/utils/kernel.py, avocado/utils/linux_modules.py, avocado/utils/lv_utils.py, avocado/utils/memory.py, avocado/utils/multipath.py, avocado/utils/network/interfaces.py, avocado/utils/partition.py, avocado/utils/pmem.py, avocado/utils/service.py, avocado/utils/software_manager/backends/rpm.py, avocado/utils/softwareraid.py, avocado/utils/wait.py
This is part of bigger effort to better organize our log messages.
=> utils: use __name__ as logger namespace

.github/workflows/ci.yml, avocado/utils/archive.py, avocado/utils/cpu.py, avocado/utils/crypto.py, avocado/utils/data_factory.py, avocado/utils/distro.py, avocado/utils/dmesg.py, avocado/utils/file_utils.py, avocado/utils/genio.py, avocado/utils/git.py, avocado/utils/iso9660.py, avocado/utils/kernel.py, avocado/utils/linux_modules.py, avocado/utils/lv_utils.py, avocado/utils/memory.py, avocado/utils/multipath.py, avocado/utils/network/interfaces.py, avocado/utils/partition.py, avocado/utils/pmem.py, avocado/utils/service.py, avocado/utils/software_manager/backends/rpm.py, avocado/utils/softwareraid.py, avocado/utils/wait.py
This reverts from commit 4e12bd337cb78118f9a83487719c857a881cd205 to
51ba6695b3f16ec25e1b83967da32a6b287d0ecb, because 93 tag it was not
released yet. My bad.
=> Revert a few changes

avocado/utils/distro.py
Signed-off-by: shilei <shileib@uniontech.com>
=> Add probe for uos systems in general

Makefile.gh
We need to update this file for releases as well.
=> Makefile.gh (for release.yml) update main VERSION file

avocado/core/exit_codes.py, avocado/plugins/assets.py, avocado/utils/asset.py, avocado/utils/download.py, contrib/scripts/avocado-fetch-eggs.py, selftests/unit/test_runner_requirement_asset.py
This is a prep-work improving utils.asset and utils.download libraries. I'm working on another PR that will change the podman spawner to fetch eggs before deployment.
=> assets small fixes and prep-work for podman spawner

avocado/plugins/beaker_result.py, docs/source/guides/user/chapters/introduction.rst, setup.py
Sends results and logs to beaker using the harness API.
https://beaker-project.org/docs/alternative-harnesses/index.html
Finds the beaker API entry point using the BEAKER_LAB_CONTROLLER_URL
environment variable.  Does nothing in case the variable is not set.
=> plugins: add beaker_result.py

avocado/core/nrunner.py
References: https://github.com/avocado-framework/avocado-vt/issues/3272
=> fix objects that cannot be JSON serializable

avocado/core/utils/loader.py, selftests/functional/test_basic.py, selftests/unit/test_datadir.py, selftests/unit/utils/test_astring.py, selftests/unit/utils/test_memory.py, selftests/unit/utils/test_network.py, selftests/unit/utils/test_process.py, selftests/unit/utils/test_script.py
More pylint updates to prepare the update to version 2.12.2
Refrences: https://github.com/avocado-framework/avocado/issues/5211
=> Pylint updates, part three

avocado/core/test.py, avocado/core/tree.py, docs/source/conf.py, examples/tests/errortest_nasty.py, optional_plugins/robot/avocado_robot/robot.py, optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/varianter_yaml_to_mux.py, optional_plugins/varianter_yaml_to_mux/tests/test_unit.py
pylint updates to prepare the update to version 2.12.2
References: https://github.com/avocado-framework/avocado/issues/5211
=> Pylint updates, part one

avocado/core/nrunner.py, avocado/core/test.py, avocado/utils/archive.py, avocado/utils/external/gdbmi_parser.py, avocado/utils/vmimage.py, contrib/scripts/summarize-job-failures.py, optional_plugins/varianter_cit/avocado_varianter_cit/CombinationRow.py, optional_plugins/varianter_cit/tests/test_combinationMatrix.py
More pylint updates to prepare the update to version 2.12.2
References: https://github.com/avocado-framework/avocado/issues/5211
@beraldoleal as mentioned, I sent it again, I realized of a problem after pushing it and was in the middle of testing when you started to review it.
=> Pylint updates, part two 

avocado/plugins/spawners/podman.py
When using an isolated spawner (i.e: Podman), sometimes we need to test our
local branch on the isolated environment side. By default, Avocado will try to
download the matching eggs from our Git repository (or use the cached version).
But this will not apply your local changes at this point. You can build
your local egg with `python setup.py bdist_egg` and use the result as
input for this variable so Avocado will skip the downloading process and
use the local egg.
Fixes #5072, #4934.
=> spawners: introduce AVOCADO_SPAWNER_EGG

avocado/plugins/human.py, avocado/plugins/testlogs.py
More to come, this is the first part related to #5244.
=> Removing legacy runner leftovers logic

avocado/core/suite.py
This is a preparation for a more drastical removal here.
Related to #5246
=> core.suite: remove legacy runner leftovers

selftests/functional/test_export_variables.py
=> fix missing "f" on f-string

avocado/utils/network/ports.py, selftests/unit/utils/test_network.py
Currently we are assuming that UDP and TCP ports shares the the same domain,
which is not true. The same is valid for IPv4 vs IPv6. When asking for
free ports, makes sense to be specific about what kind of port we are
looking for. Because of that, going over all the possible domains to get
a free port is odd. Closes #5273
=> utils.network.ports refactoring

examples/testplans/release/release.json
Eventually this could be done automatically as well.
=> Release test plan: add step about website

selftests/.data/test_statuses.py, selftests/functional/test_statuses.py, selftests/unit/test_test.py
... and also questioning about the need of two tests. Comments are appreciated, specially there.
=> selftests: fixes upgrading tests to the new runner

avocado/utils/network/interfaces.py
Returns False for 0% packet loss and True if packet loss occurs
Signed-off-by: Tasmiya Nalatwad <tasmiya@linux.vnet.ibm.com>
=> Function checks for packet loss during ping execution

.packit.yml
References: https://github.com/avocado-framework/avocado/issues/5261
=> packit: add epel 8 and 9

avocado/utils/disk.py, spell.ignore
Adding more methods to disk.py which are more commonly
used for disk operations.
=> Adding more lib methods to disk.py

avocado/utils/podman.py, selftests/functional/utils/test_podman.py
This adds utility to gather information about existing podman container
based on its id.
=> podman container info

avocado/core/nrunner/task.py
Signed-off-by: Plamen Dimitrov <plamen.dimitrov@intra2net.com>
=> Fix connection-refused race condition when spawning tasks

avocado/core/messages.py
There is a problem that sometimes the test is interrupted by timeout
before the test even start. Because avocado is creating test metadata
after the test start, and this metadata is necessary for post test
plugins, this behavior can make Avocado crash. This PR will add
metadata creation into the test finish process if the metadata is
missing.
Reference: #5413
=> Task timeout handling fix

optional_plugins/html/avocado_result_html/templates/avocado_html.js
Before：
After：
Signed-off-by: chengwenzhe <chengwenzhe@uniontech.com>
=> fix avocado_html.js

avocado/utils/software_manager/backends/dpkg.py
Signed-off-by: yangchenguang <yangchenguang@uniontech.com>
=> fix byte use func split

avocado/utils/pci.py
Added definition get_pci_info() to capture slot information using lspci command
Updated get_cfg() to capture Pysical slot, Sub vendor and Device ID from description
Signed-off-by: Maram Srimannarayana Murthy <Maram.Srimannarayana.Murthy@ibm.com>
=> Added one definition get_pci_info() and update one definition get_cfg()

docs/source/blueprints/BP005.rst
Changes since v1:
* Removed draft status (now is approved)
* Added most of the contributions and suggestions to the new blueprint
* Updated the reviewers
=> adding BP005: new autils repository (v2)

docs/source/index.rst
=> BP005: add missing index link

avocado/utils/network/interfaces.py
Function is used to check the netmask value and convert it into shortform (/mask) of netmask values
Example : 255.255.255.0 = /24
255.255.252.0 = /22
Signed-off-by: Tasmiya Nalatwad <tasmiya@linux.vnet.ibm.com>
=> Function is used to check the netmask value and convert it into shortform (/mask) of netmask values

avocado/utils/service.py
Modify avocado/utils/service.py:Adapt if the return value is of type byte
Signed-off-by: wangpeng <wangpengb@uniontech.com>
=> Modify avocado/utils/service.py:Adapt if the return value is of type  byte

avocado/utils/vmimage.py, selftests/functional/test_interrupt.py, selftests/functional/test_utils.py, selftests/pre_release/tests/readthedocs.py, selftests/pre_release/tests/vmimage.py.data/variants.yml, selftests/unit/utils/test_vmimage.py
This a collection of backports and brand new test fixes caught during the pre-release test plan execution.
=> [LTS] Fixes for release 92.1

docs/source/guides/writer/chapters/writing.rst
This is a small update to documentation about test timeout process.
Reference: #5497
=> `Setting a Test Timeout` doc update

.github/workflows/prerelease.yml, selftests/functional/test_utils.py, selftests/pre_release/tests/vmimage.py.data/variants.yml
A collection of fixes for issues caught during the pre-release tests.
=> Release 99.0 fixes

contrib/testsuites/run-kvm-unit-test.sh
Add option to provide branch of kvm-unit-test.
Signed-off-by: Srikanth Aithal <srikanth.aithal@amd.com>
=> run-kvm-unit-test:add option for branch selection

avocado/utils/network/interfaces.py
1.Adding a condition check for RHEL 9 version for new NM connection configuration and keeping old configuration as it is to support old versions
2. Adding condition check for path where file is been stored
3. generating .nmconnection file using nmcli commands
commands used :
nmcli connection add con-name {self.name} ifname {self.name} type ethernet ipv4.address {ipaddr}/24
nmcli c mod id {self.name} ipv4.method manual ipv4.address {ipaddr}/24
nmcli connection up {Network name}
4. For SUSE Wicked configuration support, added a condition check for creating a cfg file with just above given parameters.
Signed-off-by: Tasmiya Nalatwad <tasmiya@linux.vnet.ibm.com>
=> IO: RHEL 9.1 NetworkManager configuration support on NIC tests

avocado/utils/nvme.py
Added commonly used methods for nvme operations.
will be adding more to this utility in future which are needed for nvme operations.
=> adding nvme related utilities

avocado/utils/nvme.py
Fix style related issues introduced on #5488.
Reference: https://github.com/avocado-framework/avocado/pull/5488
=> avocado/utils/nvme.py: style fixes

avocado/utils/software_manager/backends/yum.py
Method `add_repo` is extended by **optional** argument `opt_params` containing dict with optional repo options.
There are some options already defined in `add_repo` method definition: `gpg_check` and `enabled`. If the same options are passed in `opt_params`, then values in `opt_params` take precedence.
Original usage of method is intact.
_Example of expected usage:_
```
repo_options = {
"priority": "1",
"gpgcheck": "0",
"skip_if_unavailable": "1"
}
yum_backend = YumBackend()
yum_backend.add_repo("http://some.path.with.dnf.repo", repo_options)
```
PR  ixes `url` vs. `baseurl` usage preventing method to work.
PR sets `space_around_delimiters=False` for write function of `configparser`, so syntax:
```
skip_if_unavailable = False
````
is replaced by the following one:
``` …
```
=> utils/software_manager/backends/yum.py: make dnf repo options customizable

avocado/utils/genio.py
- added a method read_line_with_matching_pattern()
- This method takes a file name, searches the file for the occurrences of specified "pattern".
- If found returns the line/lines in the form of a list.
Signed-off-by: Rohan Deshpande <rohan_d@linux.ibm.com>
=> utils/genio.py: added method for pattern match

avocado/utils/cpu.py
Patch request to include code to get NUMA nodes with associated CPU's on the system. This function returns a dictionary where "NUMA nodes" as key and "assocaited CPU's" are Values.
Signed-off-by: Shaik Abdulla <Shaik.Abdulla1@ibm.com>
=> Adding function to Get NUMA nodes with associated CPU's on the system.

.github/workflows/project.yml
Reference: https://github.com/orgs/avocado-framework/projects/1
=> GH action for assigning issues and PRs to project

avocado/utils/network/interfaces.py
This feature enables to validate the IP address format interms of IP address and IP octet range.
And also enables to validate the Netmask address format interms of Netmask address, octec range and invalid netmask ranges
Signed-off-by: Shaik Abdulla <Shaik.Abdulla1@ibm.com>
=> Adding support for IP and NETMASK address validation

.github/workflows/ansible.yml, .github/workflows/ci.yml, .github/workflows/prerelease.yml, .github/workflows/release.yml, .github/workflows/setup.yml, .github/workflows/weekly.yml
This is a collection of fixes and version bumps in order to get all PR based CI jobs passing.
=> Address CI issues

avocado/utils/network/hosts.py, avocado/utils/network/interfaces.py
This patch series adds
+ utilities added to identify different Network device interface 
type like virtual NIC, virther ethernet SEA, SRIOV logical interface etc and 
+  added utility to get interface names via unique hardware address 
+ With some pylint changes
=> Network utilities for all device types and to get interface name via hwaddrs

avocado/core/nrunner/task.py
Signed-off-by: Plamen Dimitrov <plamen.dimitrov@intra2net.com>
=> Increase connection establish timeout and fix its error object

avocado/utils/path.py
Modify avocado/utils/path.py:Adds a determination of whether an incoming path exists
Signed-off-by: sunqingwei <sunqingwei@uniontech.com>
=> Adds a determination of whether the path exists when the call is null

avocado/utils/software_manager/backends/rpm.py, avocado/utils/software_manager/backends/yum.py, avocado/utils/software_manager/backends/zypper.py
Added a function signature which can drive rpm build option as user driven
=> Added Support of rpm build option can be user driven

avocado/utils/genericutility.py
Following values are returned by the definition in the form of nested dictionary
wwid, dm_id, disk, disk size, hcil, dm_st, chk_st, dev_st and dev_t
Defintion fetches values from command 'multipathd -k"show topology"'
Generic Utility file added to add any generic definitions which can be used.
Added a definition to genericutility.py which returns a list of differnces.
=> recursive_compare_dict returns list by comparing dictionaries

avocado/utils/network/interfaces.py
This code corrects the logical operation to determine the boolean value, here it set to "False" when given value not in 0-255 range.
=> correcting "logical operation" to determine the boolean value.

avocado/utils/distro.py
Change /etc/os-version file information for uniontech OS
=> Modify the CHECK_FILE_CONTAINS and CHECK_VERSION_REGEX fields of UnionTechProbe

avocado/utils/nvme.py
Added some more usefull methods related to nvme drive in nvme.py file
=> Adding more utility functions to nvme.py

avocado/utils/multipath.py
This definition accepts wwid/mpathx and returns state of all the paths of the particulat wwid/mpathx in a dictionary
=> Utils multipath.py file is update with new definition "get_mpath_paths_status

.github/workflows/ci.yml, .github/workflows/prerelease.yml, .pylintrc, Makefile, Makefile.gh, avocado/core/dispatcher.py, avocado/plugins/diff.py, avocado/utils/build.py, avocado/utils/network/interfaces.py, avocado/utils/nvme.py, avocado/utils/software_manager/main.py, contrib/containers/ci/selftests/check-copr-rpm-version.docker, contrib/containers/ci/selftests/fedora-36.docker, contrib/containers/ci/selftests/fedora-38.docker, docs/source/blueprints/BP005.rst, docs/source/guides/contributor/chapters/rfc.rst, docs/source/guides/writer/chapters/logging.rst, docs/source/releases/57_0.rst, docs/source/releases/70_0.rst, docs/source/releases/98_0.rst, docs/source/releases/99_0.rst, man/avocado.rst, optional_plugins/ansible/setup.py, optional_plugins/html/avocado_result_html/__init__.py, optional_plugins/varianter_yaml_to_mux/tests/.data/mux-selftest.yaml, python-avocado.spec, requirements-dev.txt, selftests/.data/test_statuses.py, selftests/unit/tags.py
This is a collection of fixes, version bumps and small improvements in order to proceed with the pre-release (and release) of Avocado 102.0.
=> CI fixes for release 102.0

avocado/utils/nvme.py
Added 3 more methods that are very useful for tests to run
=> Adding more methods to nvme.py

avocado/core/task/statemachine.py
Sometimes the tasks are not terminated on the SIGINT call. This is caused because termination process will leave tasks which are being handled by starting method.
It happens when termination starts when some task has been removed from state machine inside start method. In such case, the state machine will falsely raise `complete` flag and the termination process will leave this task untouched.
This commit will fix this issue by comparing the number of completed tasks with the number of all tasks in suite, which will remove the false `complete` flag.
Reference: https://github.com/avocado-framework/avocado/actions/runs/5308026818/jobs/9607102523
Signed-off-by: Jan Richter [jarichte@redhat.com](mailto:jarichte@redhat.com)
=> Task termination fix

avocado/utils/softwareraid.py
=> Reduce redundant code

avocado/core/task/statemachine.py
Trivial updates (including one debugging aid) to the statemachine.
=> Statemachine trivial updates

avocado/utils/disk.py
create_linux_raw_partition: Creates specified number of partitions
get_size_of_disk: Retruns size of disk in bytes
delete_partition: Deletes specified partition
clean_disk: Deletes partitions and wipes partition table
get_disk_partitions: Returns exisitng partition on disk
=> Added disk utilities to create and delete partition on disk

avocado/core/settings.py, docs/source/guides/user/chapters/installing.rst, docs/source/guides/user/chapters/introduction.rst
When installing avocado, I found some issues in the documentation. Here are my takes to fix them. I am not a native speaker, so kindly let me know what you think.
=> Doc fixes for installing

avocado/utils/distro.py
Update Amazon Linux distro description
Reference: #5668
=> Update Amazon Linux distro description

avocado/utils/disk.py, selftests/unit/utils/disk.py
Added condition in order to get physical hardisks
and partitions
=> utils:disk.py Modified the get_disk() method

avocado/utils/astring.py
function is used in the loop to get both the index
and the value.  bytearray allows you to process byte
data more efficiently without having to store references
to each element like a list
=> Use Bytearray instead of a list

avocado/utils/git.py
Add fetching submodules
Some git repositories require submodules to compile
=> utils/git.py: Add fetching submodules

.github/workflows/pr_announcement.yml
This is an update for pr-announcement workflow to announce feature freeze for version 105.
=> Feature freeze for 105

avocado/utils/cpu.py
This patch fixes commit 0e79149 to get physical core value.
=> utils/cpu.py: fix commit 0e79149

avocado/utils/astring.py
The operations of converting characters to ASCII values and generating a list of bits can be combined into one loop, reducing the number of passes.
=> Improve execution speed

avocado/utils/path.py
Add a determination of whether the path exists in os.stat
=> Add a determination of whether the path exists in os.stat

examples/tests/sleeptest.sh
=> Fix bash-term-in-posix-shell in sleeptest

avocado/utils/network/interfaces.py
NetworkManager is the default network service for sles16 and above. Patch takes care of handling network configuration for sles16 and above versions.
=> Add support for SLES16 to work with NetworkManager

.github/workflows/ci.yml, Makefile, avocado/core/status/repo.py, optional_plugins/mail/avocado_result_mail/result_mail.py, requirements-dev.txt, selftests/unit/runnable.py
This moves the requirements for static checks to submodules. It will ensure that checks configuration will come from singe source of truth.
=> Static checks requirements from static-checks submodule

selftests/functional/serial/requirements.py
Fixes for the dependencies recipe test.
=> Class dependencies: recipe test fixes

.github/workflows/prerelease.yml, Makefile.gh
This is a set of fixes for errors occurred in the latest pre-release check. See https://github.com/richtja/avocado/actions/runs/13491376138
=> Pre release CI fixes

Makefile.gh, optional_plugins/ansible/setup.py, optional_plugins/golang/setup.py, optional_plugins/robot/setup.py, optional_plugins/spawner_remote/setup.py, optional_plugins/varianter_cit/setup.py, optional_plugins/varianter_yaml_to_mux/setup.py, selftests/check.py, setup.py
Couple of fixes for the 110.0 release
=> Pre release 110.0 fixes

avocado/utils/software_manager/backends/zypper.py
update erase with remove to use "zypper remove PACKAGE_NAME"
=> update zypper command

optional_plugins/html/avocado_result_html/templates/avocado_html.js
Fixing of HTML Reports after recent changes
Column Resizing was not working correctly.
Repositioned text and dropdowns back into previous layout.
Issues listed by Pevogam in previous PR.
Reference: https://github.com/avocado-framework/avocado/pull/6140
=> HTML Results Layout Fix

avocado/utils/cpu.py
Add sockets and thread information as part of lscpu
=> cpu.py: Add sockets and thread information

avocado/utils/aurl.py
The only real added utility of aurl on top of urllib is to extra check for some common protocols.  Let's document that so that users are aware of the behavior.
=> Utils: document aurl.is_url() actual functionality

avocado/utils/path.py, selftests/check.py, selftests/unit/utils/path.py
This is a set of docstrings and unit tests updates to prepare `avocado.utils.path` utility for migration to AAutils project.
Reference: https://github.com/avocado-framework/aautils/issues/47
=> Path utility updates for AAutlis migration

.github/workflows/autils_migration_announcement.yml, avocado/utils/output.py
Announcement of Output Module being deprecated and moved to Autils
=> Output Module Deprecation
