- avocado/core/job.py
Job API caused errors in some result events plugins. This was caused because
these plugins were loaded too early when job environment wasn't completely set
up. Let's load these plugins when they are needed.
Reference: #4034
> [Bug fix] Result events plugins errors

- selftests/job_api/test_features.py
This is the initial support to test the Avocado features/options using the Job API.
There may be some possible optimizations, but this is a good starting point to be added to the codebase.
> [JOB API] Test features/options using Python dictionary variants.

- avocado/__init__.py
- avocado/core/__init__.py
- selftests/isort.sh
We need to move the initialization steps even earlier to accommodate a few options that are used during the import time. IMO, this is not the best approach, but a temporary fix to #4071 and #4081 before LTS.
> future.settings: fixed problem with the settings loading order

- .gitignore
- docs/source/conf.py
- docs/source/guides/writer/libs/vmimage.rst
This generates a documentation table with every tested distribution for
vmimage.
---
Changes from v1 #4088:
- `docs/source/guides/writer/libs/vmimage.rst.data` in .gitingnore file
- import in top of file
> Vmimage automatic documentation [v2]

- optional_plugins/varianter_yaml_to_mux/tests/test_functional.py
Since the new replay command will not support this anymore and it is
already documented on our docs, lets remove this test.
> optional plugins: remove replay test on yaml_to_mux

- avocado/core/nrunner.py
The current runner loader/discovery method is a custom build and finds
modules/tests recursively on the current folder. With the new runner,
part of the python unittest discover was delegated to
'loadTestsFromName()' on the standard library that uses a different
logic for this (assumes that we need to import the test). Because of
that we need 1) create a custom base loader here, or 2) prepend the path
with the current dir so loadTestsFromName will return a valid test
suite.
This might not be the perfect solution but was a hot-fix found for LTS.
Fixes #3851
Reference: https://docs.python.org/3/library/unittest.html#unittest.TestLoader.loadTestsFromName
> nrunner: fix path when loading python unit tests

- avocado/__init__.py
Some plugins have custom configs we need to parse this as soon plugins
are loaded.
> future.settings: fix custom configs after plugins load too

- avocado/core/resolver.py
- avocado/core/suite.py
Because of the automatic expansion of directories entries, it's not
expected that directories themselves will have their resolutions.
Reference: https://github.com/avocado-framework/avocado/issues/4094
> Resolver: ignore references to directories not resolved

- avocado/core/suite.py
Because of line 33. Thanks @pevogam.
> core.suite: Make config optional argument

- avocado/core/utils.py
- avocado/utils/path.py
Small improvements about the `FileNotFoundError` exception that may be raised by `os.getcwd` on some platforms and situations.
> os.getcwd() related fixes

- avocado/core/nrunner.py
- avocado/core/plugin_interfaces.py
- avocado/core/requirements/cache/__init__.py
- avocado/core/requirements/cache/backends/sqlite.py
- avocado/core/spawners/mock.py
- avocado/core/status/repo.py
- avocado/core/status/server.py
- avocado/core/task/runtime.py
- avocado/core/task/statemachine.py
- avocado/core/test_id.py
- avocado/plugins/nrun.py
- avocado/plugins/runner_nrunner.py
- avocado/plugins/spawners/podman.py
- avocado/plugins/spawners/process.py
- examples/tests/passtest_explicit_requirement.py
- selftests/functional/test_requirements_cache.py
- selftests/functional/test_task_statemachine.py
- selftests/unit/test_spawner.py
- selftests/unit/test_status_repo.py
- selftests/unit/test_task_runtime.py
- setup.py
This contains a large number of fixes and prep work, before the final integration PR.  A few notes:
* The selftests for the TastStateMachine is *functional* and can work with other spawners.  I've used it successfully with the podman spawner, and maybe we could add a pre release test with it)
* The status repo is receiving new utility methods as the final monitoring/UI/ results aspects of the job integration are being developed.
* Because the BP003 describe the triage step, I've decided to include the core/avocado requirement checker here, as it gives a concrete example of triaging in the context of the spawners. 
* If reviewers are interested in seeing this prep work in use, this [commit](https://github.com/clebergnu/avocado/commit/8c7b763cb48f996e2e5fa8304fa7e10f27ea9434) should give an …
> N(ext) Runner + Job: prep work [v2]

- Makefile
- avocado/core/nrunner.py
- avocado/core/status/repo.py
- avocado/core/utils.py
- avocado/plugins/human.py
- avocado/plugins/runner_nrunner.py
- examples/jobs/nrunner.py
- selftests/unit/test_status_repo.py
- setup.py
This completes the integration of the N(ext) Runner architecture into an Avocado Job.  It's "good enough" that's used to replace `avocado nrun` on `make check`.
From this point on, other improvements and bug fixes can follow.
> N(ext) Runner: Job integration 

- avocado/core/nrunner.py
- avocado/core/nrunner_tap.py
Sometimes, third-party applications and/or tests will call binaries
without a full path. They need a previous path to be set.  When running
an `avocado-runner-exec` or `avocado-runner-tap` we use `kwargs` as
environment variables. But `env` argument from `subprocess.run()` will
pass to the subprocess only the desired dict. This PR fixes that.
> nrunner: use current PATH on avocado-runner-exec and avocado-runner-tap

- avocado/core/suite.py
This is only valid when using the resolver. This will fix #4131
> core.suite: add hint-file logic when creating a test suite

- avocado/utils/iso9660.py
Fix the following alerts on lgtm:
`Base classes have conflicting values for attribute 'mnt_dir':
Property mnt_dir and Function mnt_dir.`
> [Release 81] fix some lgtm alerts

- avocado/plugins/runner_nrunner.py
Into the reespective test results directory with a test.
Fixes: https://github.com/avocado-framework/avocado/issues/3695
> nrunner: restore collection of tasks output

- docs/source/quickstart/index.rst
This is the first impression users will have about the Job API, so
it's better to have a simpler and runnable example.
Fixes: #4161 
> Job API example: use a simpler and runnable example

- avocado/core/nrunner_avocado_instrumented.py
As it's used on the core nrunner module.  If the same timing mechanism
is not used, the calculation of time elapsed gets done wrong.
Fixes: https://github.com/avocado-framework/avocado/issues/4160
> nrunner: use time.monotonic() for instrumented runner

- avocado/core/nrunner_tap.py
So that, when run as part of a job, they'll be saved in the test
result's directory.
> TAP runner: preserve stdout and stderr

- selftests/pre_release/jobs/pre_release.py
- selftests/pre_release/tests/cirrusci.py
This makes sure we're not progressing with a release that is broken
in Cirrus CI.
Reference: https://github.com/avocado-framework/avocado/issues/3456
Reference: https://github.com/avocado-framework/avocado/pull/3551
> Pre release checks: add a Cirrus CI status check

- avocado/core/suite.py
- selftests/pre_release/jobs/pre_release.py
When calling `from_config()` the settings registered by the various
core options and plugins were not being respected.  This resulted in
crashes such as #4153.  A workaround was added previously in #4154,
but the core issue remained not solved.  With this fix, the workaround
can be removed.
Fixes: https://github.com/avocado-framework/avocado/issues/4157
Reference: https://github.com/avocado-framework/avocado/issues/4153
Reference: https://github.com/avocado-framework/avocado/issues/4154
> Suites: respect registered settings when creating from config

- avocado/plugins/assets.py
This fixes the bug when AST tries to read an attribute during the
assignment phase and it does not have an id but attr.
Fixes #4181.
> [Asset plugin] correctly get the name of attribute or variable.

- avocado/plugins/legacy/replay.py
- avocado/plugins/runner.py
- selftests/unit/test_legacy_replay.py
There are two off-by-one errors in the replay map handling and usage.
Fixes: https://github.com/avocado-framework/avocado/issues/4176
> (Legacy) Replay: fix replay by status

- avocado/core/job.py
- avocado/core/loader.py
- docs/source/guides/user/chapters/introduction.rst
- docs/source/guides/user/chapters/loaders.rst
Update the avocado list command to show the -V option in the
correct position (global option).
Update related occurrences in the documentation.
> [Documentation] fix the verbose option position for list command.

- docs/source/guides/writer/chapters/logging.rst
If readers would like to test a different parameter then the current
code will break because will not convert string to integer. This closes
> docs: small change to fix str convertion when using test parameters

- avocado/core/dispatcher.py
- avocado/core/spawners/common.py
- avocado/plugins/runner_nrunner.py
- avocado/plugins/spawners/podman.py
So that chosen configurations can be respected.  In the case of the
podman spawner, the image name and the podman binary were not being
respected.
> Make test suite configuration available to spawners

- avocado/utils/process.py
- selftests/functional/test_output_check.py
The FDDrainer reads data from processes and writes than to both a
regular logger, that has as '[stdout]' (or similar prefix) and to a
stream logger that writes the stdout/stderr/output files.
It looks for newlines in an attempt to present a human readable
result, but it fails to restore the newline on the
stdout/stderr/output files.  This restores it.
Fixes: https://github.com/avocado-framework/avocado/issues/4167
> avocado.utils.process: restore newline on stdout/stderr/output

- avocado/core/safeloader.py
- selftests/unit/test_safeloader.py
We were adding to the import path on each iteration, which would break
everything starting from the second imported name.
Fixes: https://github.com/avocado-framework/avocado/issues/4038
> safeloader: fix support for multiple classes per import statement

- avocado/plugins/runner_nrunner.py
Without this change, the following is given to the ResultEvents (and
thus the following shows up in the Human UI):
JOB ID     : 3af3f0017081df17162bbee5abaca08f4ec3a561
JOB LOG    : /home/cleber/avocado/job-results/job-2020-09-09T12.03-3af3f00/job.log
(suite01-3/4) examples/tests/passtest.py:PassTest.test: PASS (0.01 s)
(suite01-3/4) examples/tests/passtest.py:PassTest.test: STARTED
(suite01-1/4) examples/tests/passtest.py:PassTest.test: PASS (0.01 s)
(suite01-1/4) examples/tests/passtest.py:PassTest.test: STARTED
(suite01-4/4) examples/tests/passtest.py:PassTest.test: PASS (0.01 s)
(suite01-2/4) examples/tests/passtest.py:PassTest.test: PASS (0.01 s)
(suite01-4/4) examples/tests/passtest.py:PassTest.test: STARTED
(suite01-2/4) examples/tests/passtest.py:PassTest.test: STARTED
RESULTS …
> nrunner: get the task status update as a FIFO

- avocado/core/nrunner_avocado_instrumented.py
This is a similar change to that in 1f5a3e887, but now applied to
the avocado-instrumented runner.
First, by using time.monotonic(), we make sure that status messages
don't get generated with inconsistent times, that is, an earlier
"finished" message than a "running" one.
We also defer to the very last minute to time the message so that the
earlier "finished" than running example, which was actually happening,
doesn't happen.
This fixes a bug in which the 'finished' status is produced with an
earlier time than the 'running' status, and causes the status repo
to discard this update because it's an older message.
> nrunner: use more consistent time reporting

- avocado/plugins/diff.py
- docs/source/guides/user/chapters/operations.rst
The SysInfo plugin produces a `journalctl.gz` that cannot be decoded with the current Diff plugin implementation.
Let's skip files that cannot be decoded for now and propose a more robust solution later.
- Add debug message;
- Update the documentation.
> [Diff Plugin] skip file if it cannot be decoded [v2].

- avocado/plugins/diff.py
When this feature was written, strings were not unicode, so the extra handling were necessary.  Now, the decoding is not possible on (unicode) strings and crashes Avocado.
Note: @willianrampazzo fix from #4211 is included here because without it, it crashes early and never gets to this point.
> Diff HTML report: avoid crashes

- avocado/core/suite.py
- avocado/plugins/run.py
- avocado/plugins/runner.py
- avocado/plugins/runner_nrunner.py
Suite name as a prefix is only be displayed when we have multiple suites
or a custom suite with a name, otherwise we are going to remove this
from output.
This is not the ideal solution, just a hotfix for LTS. We need to discuss better
this id situation. I created one issue (#4210) for that.
Signed-off-by: Beraldo Leal bleal@redhat.com
- We changed the logic here, `TestSuite()` is created without names (`name=""`) now
- Renamed suite01 to SuiteDefault;
- Removed the "SuiteDefault-" from Human Output when running from the command-line to keep compatibility with previous versions;
> core:runner: Fixed the suite name when showing results - v3

- avocado/plugins/runner.py
Just for keeping consistent. Thanks @pevogam.
> small fix: renaming the variable name used in nrunner

- examples/tests/raise.py
When run with the example varianter file:
```
avocado run -m examples/tests/raise.py.data/raise.yaml \
-- examples/tests/raise.py
```
The test gets to a block that misuses the process stdout as bytes
instead of as string.
> examples/tests/raise.py: fix use of bytes instead of string

- optional_plugins/golang/avocado_golang/runner.py
- optional_plugins/golang/setup.py
- python-avocado.spec
- spell.ignore
While a Golang resolver was available, a runner (nrunner-like) was
not.
Like the previous runner version, this does not attempt to manipulate
the GOROOT/GOPATH variables, so to try this out you want to run, from
the top of the Avocado source tree:
$ GOPATH=`pwd`/optional_plugins/golang/tests:$GOPATH avocado run \
--test-runner=nrunner countavocados
> Golang: add a nrunner based implementation

- avocado/utils/cpu.py
Also raising NotImplemented when other families, not only arm.
> utils.cpu: fixed cpu family when 2964 - z13

- avocado/utils/network/hosts.py
add get_default_route_interface() in host.py to get default
interface name.
> function to get default route interface

- avocado/utils/network/interfaces.py
chnage index to -1 and -2 just because its failing for bonding interface.
as in bonding interfcae flags it have extra value.
> changed index in is_admin_link_up() and is_operational_link_up()

- avocado/core/nrunner.py
While looking for suitable runners for a given kind, an
`avocado-runner-$kind` executable is tried out.  This is convenient
because any executable on the system could play the role of an
runner.
But, in some circunstances, those valid executables won't be in a
location that is the `PATH` environment variable.  For instance, on
non-activated Python virtual environments, a command such as:
/path/to/venv/bin/avocado run --test-runner /path/to/test
Won't have `/path/to/venv/bin` in the `PATH`.  One can argue that this
is an uncommon deployment scenario, but it's a valid one and currently
used by projects such as QEMU.
Now, there's already support for alternative ways of finding the test
runners, and the next one attempted is looking for a
"avocado.core.nrunner_$kind" Python module.  This …
> nrunner: fix location and name of runner modules

- .travis.yml
- avocado/core/nrunner.py
This adds one fix to the "Ad hoc checks on OS X", but primarily it's about adding very basic smokechecks (enforced) so that the functionality is not regressed.
This is not claiming that those platforms will now be supported, and if it proves difficult to support even those smokechecks, we can revert them.
The fix from #4259 is also added here because it's needed for running Avocado with runners not on PATH.
> Travis CI: fixes and inclusion of basic Python 3.9 checks and exteded OS X / Windows

- avocado/utils/process.py
- selftests/unit/test_utils_process.py
On some systems, the sudo command does not have the read attribute set, failing avocado.utils.path.find_command as if sudo was not installed in the system.
This changes the behavior to check if the file exists, but do not
check if the file can be executed.
Fixes #4263 
> Avoid failing when sudo command do not have read attribute.

- avocado/utils/linux.py
added utility which check if system is running in selinux enforcing mode if not it enable it
and return True otherwise False
> Added a library function which selinux in enforcing mode

- avocado/utils/exit_codes.py
- avocado/utils/software_manager/main.py
This adds basic exit status codes to the Avocado utilities. To avoid module boundary infringements and to use a meaningful name for the exit codes not related to tests execution, a new exit code file was created under the utility directory.
This also adapts the `avocado-software-manager` to use the newly created exit codes.
Changes from #4279:
- Reduce the number of codes to those used right now plus generic crash.
- Adapt the `avocado-software-manager` to use one code to fail.
> [Utils] Add common exit codes and use it at software manager [v2].

- avocado/core/loader.py
When using the JobAPI there is no subcommand. This patch will fix this
by adding a default command. This will fix #4274.
> Fixes external runner when using the JobAPI

- avocado/utils/cpu.py
While PR #4239 add a new family, also fixed some other minor issues,
like the proper exceptions and return values. Since this is an LTS
branch, I'm just adding the new family here, to avoid creating new
exceptions and break API compatibility.
> backport #4239: new family to utils.cpu

- avocado/plugins/spawners/podman.py
- setup.py
To make it easier to choose a different container image, and podman
binary, for one off executions.
> Podman Spawner: add image and binary command line configuration

- avocado/core/safeloader.py
Migrates from imp to importlib, as the former is depreciated since version 3.4.
As discussed in #3468, for now, only safeloader.py was altered.
Signed-off-by: Tiago Honorato <tiagohonorato1@gmail.com>
> Migration from imp to importlib

- avocado/core/nrunner.py
This removes the requirement for a kind argument *if* the executable
name makes it clear what this runner handles.  It avoids the need
to given the runner name, and at the same time, the kind argument.
It's still necessary to have that option because some executables
(such as avocado-runner itself) can handle multiple kinds.
> nrunner runners: use a default kind based on the executable name

- optional_plugins/golang/avocado_golang/__init__.py
- optional_plugins/varianter_yaml_to_mux/tests/test_unit.py
- selftests/__init__.py
Changes string references to parent `'..'` and current `'.'` directories to cross-platform using `os.path.pardir` and `os.path.curdir` as discussed in  #3470
> Cross-platform reference to current and parent directories

- avocado/utils/path.py
When signaling that a command was not found, the list of paths that
were tried are returned.  These are usually logged as part of a test.
When running two identical tests, and comparing results, the different
order of the list of tried paths adds a lot of noise.  Let's always
return a sorted list of paths, given that the order is, at this point,
not important anymore (given that the command was not found anywhere).
> avocado.utils.path.find_command: provide a more constant list of paths

- avocado/plugins/jsonresult.py
Commit b5521c15 added the warning message in a different location than
other plugins, and it's annoying to have that it gets in the way of
the results part of the UI.
> JSON Result: move deprecation message

- examples/jobs/passjob_html.py
- optional_plugins/html/avocado_result_html/__init__.py
- optional_plugins/html/setup.py
This creates an Init implementation for the HTML options, allowing them to be used outside of the 'avocado run' operation, that is,  in the Job API.
> HTML Result: allow options to be used in Job API

- Makefile
- avocado/plugins/human.py
- selftests/check.py
- selftests/functional/test_job_api_features.py
- selftests/functional/test_journal.py
- selftests/functional/test_replay.py
- selftests/job_api/test_features.py
- selftests/unit/test_jsonresult.py
- selftests/unit/test_xunit.py
The Job API, with its support for multiple test suites, has as of its goals, to be able to consolidate all checks that a project has.  This is *not* what Avocado is doing itself so far.
This consolidates both the "Job API Features" tests, and the regular "selftests" checks into a single job.
> Unify jobs used on "make check"

- avocado/plugins/testlogs.py
- docs/source/guides/user/chapters/plugins.rst
- selftests/functional/test_logs.py
- setup.py
When running tests on certain scenarios, such as on CI environments,
it's usually not a good idea to pollute the output with very verbose
output. On the other hand, when failures occurs, the only debugging
aid is many times printing out the entire test log.
Fixes: https://github.com/avocado-framework/avocado/issues/4266
---
Changes from v1 (#4301):
* renamed namespace from `job.run.testlogs` to `job.output.testlogs`
> Show test logs depending on status [v2]

- avocado/core/nrunner_avocado_instrumented.py
The timeout from the early status can be an actual *None*, and in such
case, the runner will crash trying to convert it to a float.
This fixes the crashes such as:
$ avocado-runner-avocado-instrumented runnable-run -u selftests/unit/test_utils_cpu.py:Cpu.test_x86_64_cpu_online
{'status': 'started', 'time': 3637949.5979991}
File "/home/cleber/.local/bin/avocado-runner-avocado-instrumented", line 11, in <module>
load_entry_point('avocado-framework', 'console_scripts', 'avocado-runner-avocado-instrumented')()
File "/home/cleber/src/avocado/avocado/avocado/core/nrunner_avocado_instrumented.py", line 125, in main
nrunner.main(RunnerApp)
File "/home/cleber/src/avocado/avocado/avocado/core/nrunner.py", line 947, in main
app.run()
File …
> avocado/core/nrunner_avocado_instrumented.py: fix timeout handling

- avocado/core/__init__.py
- avocado/core/nrunner.py
- avocado/core/settings.py
- avocado/core/suite.py
- avocado/plugins/resolvers.py
- selftests/functional/test_nrunner.py
- selftests/unit/test_future_settings.py
- selftests/unit/test_nrunner.py
This PR is doing two things, but they are related: First I'm introducing the ability to send custom settings (config) to the Runners via Runnables, by sending all settings namespaces starting with 'runners'. Finally, I'm using this feature to configure custom exit codes for exec-test runners in case of 'skip'. Today, exec-test is limited to understand only what is fail and pass.
Fixes #4286
* config arg is not optional
* default for `runner.exectest.exitcodes.skip` now is `[]`
* small changes suggested by @willianrampazzo 
* using `'^runner\.'` as regex
> Introduces the 'config' args to Runnable and extend exec-test to support skip tests (v2)

- docs/source/plugins/optional/varianter_yaml_to_mux.rst
Inside documentation of yaml to mux plugin is a problem with None type, which
is passed to parameters as a string due to distinguish between empty values and
default values. This commit should specify this behavior.
> Yaml to mux documentation fix

- avocado/utils/pci.py
Newer pci slot names are in the format: U78D8.ND0.XXXXXX-P0-C7-C0.
So, enhancing the function to accomodate them as well.
> utils/pci: Fix for accomodating newer slot names

- docs/source/guides/contributor/chapters/releasing.rst
- examples/testplans/release/release.json
This is basically the documentation that Merlin has created, which I
have been following for the last few releases.
There are a few changes when compared with Merlin's version, but
nothing really significant:
* Updated versions used in the example to 82.0 -> 83.0
* Removed workarounds needed by aexpect
* Section formatting (since these are now under another topic)
CC: Merlin Mathesius <mmathesi@redhat.com>
Author: Merlin Mathesius <mmathesi@redhat.com>
> Docs: include the Fedora/EPEL refresh steps

- avocado/core/settings.py
In `add_argparser_to_option` the variables `long_arg` and `short_arg` are
swapped.
> Settings, variables swap

- avocado/plugins/jsonresult.py
- avocado/plugins/tap.py
- avocado/plugins/xunit.py
- docs/source/plugins/optional/results.rst
- examples/jobs/passjob_html.py
- examples/jobs/passjob_html_browser.py
- optional_plugins/html/avocado_result_html/__init__.py
- selftests/check.py
- selftests/functional/test_job_api_features.py
This is removing old style 'on'/'off' from some configuration namespaces and replacing by a true bool. This is part of BP001.
Fixes #3440
> Convert old style 'on'/''off' to real boolean arguments on remaining plugins

- Makefile
The variable `AVOCADO_DIRNAME` in Makefile is not set properly on Fedora 33 and
make has warning:
/bin/sh: ${PWD\#\#*/}: bad substitution.
This is fixing it.
Reference:#4318
> Makefile AVOCADO_DIRNAME fix

- docs/source/plugins/optional/varianter_yaml_to_mux.rst
- optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py
Patch handles None type input in yaml as a special case due to limitation in avocado implementation
```
YAML:
setup:
disk_type: 'nvdimm'
fs_type: !mux
fs_xfs:
exclude: null
gen_exclude: 'null'
Before patch:
Variant run-setup-disk_type-fs_type-fs_xfs-exclude-83a1:    /run/setup/fs_type/fs_xfs/exclude
/run/setup/disk_type:type             => nvdimm
/run/setup/fs_type/fs_xfs:fs          => xfs
/run/setup/fs_type/fs_xfs:gen_exclude => null
After patch:
Variant run-setup-disk_type-fs_type-fs_xfs-exclude-8cde:    /run/setup/fs_type/fs_xfs/exclude
/run/setup/disk_type:type             => nvdimm
/run/setup/fs_type/fs_xfs:fs          => xfs
/run/setup/fs_type/fs_xfs:gen_exclude => None
```
Fixes: #4010 
> Fix: Handle None type input in yaml

- avocado/core/nrunner.py
- avocado/core/status/server.py
- avocado/plugins/runner_nrunner.py
- avocado/plugins/spawners/process.py
This is a collection of fixes intended fix: https://github.com/avocado-framework/avocado/issues/4322
> Nrunner: handle large stdout/stderr size limits

- avocado/plugins/dict_variants.py
- setup.py
This fixes the following:
```
$ ./check.py -f
File "/home/wrampazz/src/avocado/avocado.quick-dev/selftests/./check.py", line 518, in <module>
sys.exit(main())
File "/home/wrampazz/src/avocado/avocado.quick-dev/selftests/./check.py", line 500, in main
for variants in suite.config['run.dict_variants']:
KeyError: 'run.dict_variants'
```
> Register run.dict_variants missing option from dict_variants plugin.

- avocado/core/nrunner_avocado_instrumented.py
The current implementation was missing some valid statuses, such
as CANCEL and WARN.  Instead of keeping a duplicate list, let's
use the common definitions.
> Avocado Instrumented Runner: cover all statuses

- avocado/core/job.py
- avocado/plugins/run.py
When running a job using the JobAPI(), pre/post hooks are not being
used.  IMO, users of JobAPI should not have to call this in they
scripts. This is moving the hooks from run command-line to the Job
itself.
Fixes #4339.
> moving pre/post hooks to job module

- avocado/core/loader.py
- avocado/plugins/run.py
- optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py
This is a cosmetic change but help us having a better command-line
syntax as discussed on BP000. Basically this will make argparse raise
errors when option-arguments have no arguments and also fixes the syntax
displayed on help. Fixes #3441.
AFAICT, the only remaining optional option-arguments is 'refeferences' for both 'run'  and 'list' commands. Those are kept there because makes sense.
> bp000: option-arguments should not be optional

- avocado/utils/memory.py
Currently a PowerVM machine has the capability to run on both Hash and Radix MMU, hence remove 16G hugepages only in case of Radix.
> Fix: Remove 16G hugepage only for Hash MMU

- avocado/plugins/runner_nrunner.py
The status servers serve on specific uri even when his test suite finish.
Because of that it blocks other servers from different suites with the same
uri. And avocado doesn't get status from other suites.
Reference: #4346
> [nrunner]Multiple suites

- avocado/utils/ssh.py
The first will remove the control master file, if exists. The second
will return the same file, also only in cases that the file exists.
> utils.ssh: adding a cleanup master method and a property

- avocado/utils/kernel.py
- contrib/packages/debian/rules
Also, removed distutils from debian rules
Signed-off-by: t0xic0der <akashdeep.dhar@gmail.com>
Resolves #4228. Had to make a new PR because I was not able to figure out how to amend and sign off those which were already pushed. Sincere apologies for the inexperience. I also took care of the corrections requested [here](https://github.com/avocado-framework/avocado/pull/4248#discussion_r494208281), [here](https://github.com/avocado-framework/avocado/pull/4248#discussion_r494162839) and [here](https://github.com/avocado-framework/avocado/pull/4248#pullrequestreview-495379241).
I ran a check locally and it returned 0 errors.
```
...
Extracting PyYAML-5.3.1-py3.8-linux-x86_64.egg to /home/t0xic0der/.local/lib/python3.8/site-packages
Adding PyYAML 5.3.1 to easy-install.pth file
Installed …
```
> Replaced LooseVersion with Version from packaging

- avocado/plugins/list.py
This PR adds error handling on the avocado list with loaders. Without this handling the avocado crashed unexpectedly with unknown loaders.
Reference:#4344
> Loader listing fix

- avocado/core/status/server.py
`asyncio` package is not compatible between python 3.6 and 3.7 this checks the
python version and solves problems with status server on python 3.6
Reference:#4359
> Status Server compatibility with python 3.6

- selftests/pre_release/tests/vmimage.py.data/variants.yml
Debian often updates their versions, and Fedora has recently retired version 31.
> Pre-release tests: update tested versions of Debian and Fedora 

- contrib/testsuites/run-kvm-unit-test.sh
The problem comes from #4358, it lacks the symbol "$*", so the script
cannot accept extra avocado arguments.
> run-kvm-unit-test.sh: Re-support for adding avocado arguments

- avocado/core/task/statemachine.py
- avocado/plugins/runner_nrunner.py
- selftests/functional/test_task_timeout.py
There is no way to kill a test if timeout is reached. This
patch is introducing 'task.timeout.running' as timeout.
This closes #4321
> nrunner: introduce 'task.timeout.running' config option as timeout and small fix

- avocado/utils/cloudinit.py
IMO, pycdlib should be an Avocado requirement. For more details, please, visit each commit description.
> utils: iso9660 and cloudinit has pycdlib as requirements

- selftests/signedoff-check.sh
Added -i option to grep to allow matching names and emails
when letter cases in them are different.
Signed-off-by: Pavel Dovgalyuk <Pavel.Dovgalyuk@ispras.ru>
> signedoff-checks.sh: don't take letter case in account

- avocado/utils/vmimage.py
Old (version<32) fedora images now are stored at different server.
This patch adds urls of that servers for base and secondary
fedora image providers.
Signed-off-by: Pavel Dovgalyuk <Pavel.Dovgalyuk@ispras.ru>
> vmimage: fix fedora image provider for older images

- avocado/core/extension_manager.py
- avocado/core/nrunner.py
- avocado/core/nrunner_tap.py
- avocado/core/task/runtime.py
- avocado/core/task/statemachine.py
- avocado/core/test.py
- avocado/utils/memory.py
- avocado/utils/network/hosts.py
- avocado/utils/pmem.py
- avocado/utils/softwareraid.py
- examples/nrunner/task-state-machine.py
- optional_plugins/golang/avocado_golang/runner.py
- optional_plugins/varianter_cit/avocado_varianter_cit/CombinationRow.py
- optional_plugins/varianter_yaml_to_mux/tests/test_functional.py
- requirements-selftests.txt
- selftests/functional/test_basic.py
- selftests/functional/test_interrupt.py
- selftests/unit/test_archive.py
- selftests/unit/test_tags.py
- selftests/unit/test_utils_process.py
Inspektor has the ability to use autopep8 transparently (if installed)
which catches a number of different style issues.
> Style check: enable autopep8 functionality

- avocado/utils/path.py
It clarifies the description for find_command()
Signed-off-by: Oksana Vohchana <ovoshcha@redhat.com>
---
This is simply a squash from the commits on #3530.
> Docs: Description to path related functions

- Makefile
- docs/source/guides/contributor/chapters/environment.rst
- setup.py
This is the first step/experiment for moving Makefile targets to setup.py. Although setuptools is the choice in the Python community to distribute/compile packages, its documentation is not yet complete and even official Python documentation still maintains the distutils documentation as a reference for items not covered by setuptools. This is the case with clean command. This is part of a bigger effort to make our build environments and CI consistent regardless of where we are running the target commands. For sure that we have room for improvements here but in this PR, I would like to focus on the migration only.
> Makefile: migrate clean target to setup.py and cleanups

- avocado/utils/network/interfaces.py
The current format is not supported by SuSE distro as few of the
keywords are not recognised.
> Fixed config file for distro SuSE

- avocado/core/test.py
- avocado/plugins/assets.py
- avocado/utils/asset.py
- selftests/__init__.py
- selftests/functional/test_plugin_assets.py
- selftests/functional/test_utils_asset.py
This proposal is based on some of Avocado's user's needs. They are asking for ways to register assets manually and referencing them by name later, which is not possible in the current design.
This is a small hack to avoid a bigger change. But in general, this proposed approach will change three things: 1) we don't have to initialize objects to do basic operations, since there is a lot of unnecessary arguments when initializing that could be avoided. (vide class methods); 2) Lazy evaluation/validation of objects is being used, for better reuse of objects; 3) a new test method is available: self.fetch_asset_by_name(), I tried to explain the reason for that in the commit message;
Also, I'm doing small refactoring to improve code readability and maintainability.
IMO, this needs a much deeper …
> assets: introduce a way to register assets manually and small refactoring (v3)

- setup.py
We advertise (and test) support for 3.5 and later, so let's bump
the requirement.
> setup.py: fix Python version requirement

- selftests/pre_release/tests/check-copr-rpm-version.sh
COPR only builds packages for current Fedora versions, so let's bump
the version.
> RPM check on COPR: bump fedora version used on the script

- examples/testplans/release/release.json
The location where one finds the option to set the new default to be
displayed by readthedocs.org is actually a different one.
> Release testplan: fix the option name for setting default version

- docs/source/guides/contributor/chapters/plugins.rst
- examples/plugins/tests/README.rst
- examples/plugins/tests/magic/avocado_magic/resolver.py
- examples/plugins/tests/magic/avocado_magic/runner.py
- examples/plugins/tests/magic/setup.py
This is a very simple, hello world like, implementation of a resolver.
If given the right (magic) words, it will return a resolution for the
"magic" test type.
It also includes the simplest possible runner for "magic" words.
It'll result in a successfull test result for URI "pass", and a test
failure for URI "fail".  For anything else, it'll result in an error.
---
Changes from v1 (#4315):
* Added section on Contributor’s Guide
> Introduce example for "magic words" test type [v2]

- selftests/pre_release/tests/vmimage.py
In the vmimage pre_release testing we are downloading all avocado supported
images, but after testing the we leave them inside avocado cache. The images
can consume dozens gigabytes of data which can cause a memory issues. Because
of this problem we have to remove downloaded images from cache after the
testing.
---
Changes form v1:
* Checking the status of cache before and after the test
> Vmimage pre_release tests clean up [v2]

- avocado/plugins/diff.py
- selftests/.data/get_data.py
Since Avocado requires ``python>=3.5``, maybe ``print_function`` and 
``absolute_import`` features from ``__future__`` could be removed as 
those provide functionality already builtin in python 3, used mainly to
provide backwards compatibility with python 2.
> Remove __future__ imports with functionality already in Python 3

- python-avocado.spec
The newer Fedora build roots do have make installed by default.
Instead of adding another package dependency, let's just use the
very simple command we need during the RPM build.
> SPEC: do not depend on make

- avocado/plugins/replay.py
On commit 5414e18702 the calling of pre/post job plugins was moved to
the Job class itself, so it became something that happens
transparently when Job.run() is called.
The replay plugin should not be calling those again.  This fixes, for
instance, a duplicated "JOB TIME" line when using the human UI plugin.
> Replay: avoid calling pre/post plugins twice

- avocado/utils/asset.py
Instead of allowing it to be given an explicit None.  The problem with
allowing None is that the name is given to Python's urlparse(), and it
has the behavior of returning either a ParseResult or a
ParseResultBytes depending on the input given.
To prevent having to add further logic on a large part of the asset
code, let's just normalize the input.
Reference: https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlparse
> Assets: default asset name to empty string

- avocado/utils/multipath.py
The sphinx generated from utils/multipath.py docstrings
ins't formatted correctly. Fixed it. Also made the text
a little bit more uniform.
This is a one year PR and is not intent to do a huge refactoring on those
docstrings. There is still room for improvements.
> utils/multipath: Fix the module's sphinx documentation

- avocado/core/test.py
- avocado/plugins/runner_nrunner.py
The Testlog plugin didn't have the information where avocado-instrumented-nrunner stores the logs of tests. This PR is about fixing this problem.
Reference:#4341
> Output on fail fix

- contrib/packages/debian/changelog
- contrib/packages/debian/control
Hello,
This small series contains minor fixes for the Debian packaging:
* debian: Remove dependency on python-support
* debian: Update package version
make check log: http://www.radix50.net/~ibr/job-2021-02-14T16.04-2659714-debian_buster-v1.log
There are 18 errors, should I fix them? I've only changed contrib/packages/debian.
Feedback welcome.
With kind regards,
Baurzhan.
> debian: Update for Debian 10 v1

- docs/source/blueprints/BP000.rst
- docs/source/blueprints/template.rst
Anticipating that writing BluePrints will become more common, let's
also provide a template file that will help with that.
A few sections of BP000 were augmented just to refer to the template
file or to provide a bit more helpful information to BluePrint
writers.
> BluePrints: add a template file

- avocado/utils/asset.py
Commit 27614569 was introduced as a default value but without effect on the
constructor signature. This small change will allow objects to be
constructed without having to pass None or `''` to the first argument
while keeps `''` as the default value.
> Assets: small fix on Asset constructor consistency

- avocado/plugins/journal.py
Because the "conversion to string" was being done using the
representation of the object, we ended up with quotes on the test
names, and we don't want that.
> Journal Plugin: store test names without quotes

- avocado/core/nrunner_avocado_instrumented.py
- avocado/core/test.py
- avocado/plugins/runner.py
- selftests/unit/test_jsonresult.py
- selftests/unit/test_test.py
- selftests/unit/test_xunit.py
This commit removes the Job instance from the Test class. This is
preparation for legacy runner removal. For the nrunner doesn't make
sense to have Test dependent on Job instance, because Test is run inside
runner separated from Job.
Reference: #4425
> Test independent on Job class

- avocado/utils/pci.py
If the test system do not have any physical disks, the path /dev/disk/by-path/
is invalid, make sure the path exists before it proceeds
fixes ERROR: [Errno 2] No such file or directory: '/dev/disk/by-path/'
> get_disks_in_pci_address: add a path check

- avocado/plugins/assets.py
- avocado/utils/asset.py
- docs/source/guides/user/chapters/assets.rst
- docs/source/guides/user/index.rst
- selftests/functional/test_plugin_assets.py
This PR will introduce some foundation methods and new command-line options for the "avocado assets" command. From now on we have "purge" and "list", options. More information on individual commit messages.
- Fixed out of place code;
- Fixed list;
- Fixed operators dict
> assets: introduce assets purge and list subcommands (v2)

- avocado/plugins/assets.py
The plugin is currently using the wrong name for the utility function.
> Assets: fix wrong method name

- avocado/core/job.py
- selftests/check.py
- selftests/unit/test_job.py
Output of selftests check with summary of all failed tests.
Now the check output will look like this:
```
...
(check-852/956) selftests/lint.sh: FAIL (91.79 s)
RESULTS    : PASS 956 | ERROR 1 | FAIL 3 | SKIP 44 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /home/jarichte/avocado/job-results/job-2021-03-10T15.40-f7a9604/results.html
JOB TIME   : 462.65 s
Failed tests:
check-417-selftests/unit/test_test.py:MockingTest.test_combination_2  ERROR
check-416-selftests/unit/test_test.py:MockingTest.test_combination  FAIL
check-772-selftests/functional/test_loader.py:LoaderTestFunctional.test_python_unittest  FAIL
check-852-selftests/lint.sh  FAIL
```
---
Changes form v1 #4448:
Usage of Job API instead of journal plugin
> Check summary [v2]

- avocado/core/nrunner.py
- avocado/core/utils.py
- examples/jobs/passjob_custom.py
- selftests/functional/test_task_statemachine.py
- selftests/unit/test_spawner.py
- selftests/unit/test_task_runtime.py
A task identifier is a mandatory attribute, and that fact is set clear in the class initializer. But, there are circumstances where users are not interested in manually set them, but just have them being unique.
---
Changes from v1 (#4461):
* Changed the order of parameters in `Task`, making `identifier` the second (and optional) parameter
> nrunner: provide a Task identifier when none is given [v2]

- .cirrus.yml
Given that our CI service is undergoing changes, it's a good idea to look into other services.  We've been using Cirrus CI lightly, but Avocado-VT uses it a lot, and it has always been rock solid.
This increases the coverage done on Cirrus CI, and may lead to more load being sent that way.
> Cirrus CI: expand coverage

- avocado/core/nrunner.py
- avocado/core/runners/avocado_instrumented.py
- avocado/core/runners/tap.py
- selftests/unit/test_nrunner.py
- setup.py
With the possibility of having new runners added to the nrunner architecture, let's move the standalone runners to a specific directory, just like the spawners' structure.
> Move nrunner standalone runners to a new runners dir

- avocado/core/decorators.py
- docs/source/guides/writer/chapters/writing.rst
- examples/tests/skip_conditional.py
- selftests/functional/test_skiptests.py
The `sosreport` project needs to evaluate the conditions for skipping tests based on properties of the classes that contain them.  That is a valid use case, so this implements such a feature, up until now missing from Avocado's `skipIf` and `skipUnless` decorators.
The PR that contains their custom `skipIf` decorator can be found at: https://github.com/sosreport/sos/pull/2431
> Skip* Decorators: allow the conditional to be a callable

- avocado/core/nrunner.py
- avocado/core/suite.py
- avocado/core/utils.py
- avocado/plugins/list.py
- avocado/plugins/runner_nrunner.py
- selftests/unit/test_job.py
A Runnable is meant to contain all descriptive information about what is to be run, while a Task is supposed to contain information that is needed at run time while executing a runnable within the context of a job (and its status server).
This change will keep Runnables in the test suite (which are simpler) and will create the Tasks once they are about to be handed for execution in a job.
This also solves the dilemma of changing a Task identifier, which was not really a problem with the Tasks, but a problem caused by    them being created way too earlier than necessary
> Suite: replace Tasks for Runnables

- .cirrus.yml
- avocado/utils/process.py
- contrib/containers/ci/selftests/fedora-32.docker
- contrib/containers/ci/selftests/fedora-33.docker
- selftests/unit/test_utils_iso9660.py
- selftests/unit/test_utils_network.py
- selftests/unit/test_utils_partition.py
- selftests/unit/test_utils_process.py
- spell.ignore
The tasks introduce here make use of the build requirements (most for running the selftests) that are already coded in the Fedora upstream packages.
Then, it installs those dependencies and sets up a development environment and runs the tests. This should be very similar to the steps that a new Avocado developer on a Fedora distro would go through.
In my observation, the overall jobs finish ~40% quicker than the Travis CI counterparts.
> Cirrus CI: run selftests on Fedora

- avocado/plugins/assets.py
With the replacement of Tasks for Runnables at commit 93f93764f311ef2a988dc23bdbac80db11cfdc3f, the assets plugin started to fail with `Error running method "pre_tests" of plugin "fetchasset": 'Runnable' object is not subscriptable"`.
This adjusts the plugin to skip Runnable objects instead of Task.
> Adjust the assets plugin to skip Runnable objects

- avocado/core/nrunner.py
The idea for this PR came during the discussions over #4441. I guess this is more a design decision than anything else. The idea here is to properly enforce the implementation of ``run()`` in subclasses as well as to avoid direct instantiation from ``BaseRunner``.
Signed-off-by: Tiago Honorato <tiagohonorato1@gmail.com>
> Make BaseRunner an abstract class

- optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/mux.py
Since ``iteritems()`` is no longer an available method for dictionaries in
python3 and ``items()`` returns an iterator by default, it would be preferable
to use ``items()`` directly.
This was something commented briefly over #4411.
Signed-off-by: Tiago Honorato <tiagohonorato1@gmail.com>
> Remove iteritems() when inheriting from dict

- avocado/utils/vmimage.py
The qemu-img uses the cloud-init image as a backing file to build the new
image, but the command warns about:
"qemu-img: warning: Deprecated use of backing file without explicit backing format (detected format of qcow2)"
This adds "-F qcow2" to the list of parameters so that warning is quieted.
> vmimage: Pass the backing file format to qemu-img

- .pylintrc
Depending on the configuration, while running ./selftests/lint.sh,
one may get a series of lines that look like:
selftests/unit/test_utils_network.py:49:48: I1101: Module 'netifaces'
has no 'AF_INET6' member, but source is unavailable. Consider adding
this module to extension-pkg-whitelist if you want to perform analysis
based on run-time introspection of living objects. (c-extension-no-member)
I think it's safe enough to allow the netiface module to be evaluated at
run-time for a proper linting, and get rid of those messages.
> Selftests/lint: allow netifaces to be loaded for proper linting

- avocado/core/safeloader.py
- selftests/unit/test_safeloader.py
Currently the parsing of imported modules support relative imports,
*or* imports with names.  This means that syntax such as:
from ..upper import foo
Is currently broken.  With this change, the upper levels are also
accounted for.
> Safeloader: support relative imports with names

- avocado/core/__init__.py
- avocado/core/test.py
- avocado/plugins/testlogs.py
- selftests/functional/plugin/test_logs.py
- selftests/functional/test_basic.py
This makes two improvements regarding how SIMPLE tests (executable tests) present their results:
* On the "failure reason" string presented along with test PASS/FAIL/ERROR status
* On the `testlogs` plugin that can show the tests log on if a given test result matches the configuration
Now it's possible to configure both the fields that will appear on the failure reason, and the log files that will be shown once the job is finished.
> SIMPLE Tests: improvements on failure presentation

- avocado/core/nrunner.py
- avocado/core/runners/tap.py
The exec-test runner works by leveraging the exec runner, and doing additional check on the last stage, basically deciding the actual result of the test and what to report in the final status message.
The TAP runner is no different, but currently it basically re-implements the execution part of the code.  Because this code diverges, a bug fixed on the exec runner, supporting large outputs that exceed the buffer sizes, where not applied to the TAP runner.
With this change, runners based on exec can choose to simply implement the method that checks/builds the final status.
> TAP: unify implementation with exec based runners

- selftests/functional/plugin/test_assets.py
This is just adding a test to ensure purge by days is working.
This fixes #4460.
> selftests: added new test to the assets plugin

- avocado/core/decorators.py
- selftests/functional/test_skiptests.py
Callable conditional were introduced in f402b6d81, but it also introduced a bug.  In an effort to support both non-conditionals (plain "@skip") and conditionals ("@skipIf" and "@skipUnless") a parameter called condition was introduced, and checked for being None.
The problem is that None should evaluate to False, and thus cause the `skipIf` to *not* skip, such as in:
```python 
@avocado.skipIf(None, 'skipIf with None condition, should not happen')
```
And conversely, `skipUnless` to skip. The bugfix simply makes the non-conditional skip have a `True` condition instead.
> Decorators: fix issue with conditional skips and None

- avocado/plugins/assets.py
- avocado/utils/asset.py
- docs/source/guides/user/chapters/assets.rst
- selftests/check.py
- selftests/functional/plugin/test_assets.py
- spell.ignore
This will remove assets by an overall limit sorting assets by atime.
For instance, it may be the case that a GitLab cache limit is 4 GiB, in
that case, we can sort by last access, and remove all that exceeds 4 GiB
(that is, keep the last accessed 4 GiB worth of cached files). This
fixes #4457.
Signed-off-by: Beraldo Leal bleal@redhat.com
- fixed typo on commit log msg;
- Improved docstring to make explicitly about bytes;
- Improved documentation on our user guide about suffixes;
- Getting valid suffixes from DataSize class;
- Squashed two commits (about spell.ignore)
> assets: add --by-overall-limit to assets purge command (v2)

- avocado/core/utils.py
- avocado/plugins/sysinfo.py
Commit 768455c3 removed the existing configuration files, and with
that, the patching that happened on the RPM SPEC file changing the
sysinfo defaults to the system wide /etc based locations.
Without a configuration file to tweak, we're left wither with patching
code, or making the code more dynamic and respecting the system wide
configuration paths no matter if it's an RPM based installation or
not.  This chooses the later.
Fixes: https://github.com/avocado-framework/avocado/issues/4208
---
Changes from v1 (#4508):
* Added docstring (@pevogam)
* Properly handle absolute paths given as input (@pevogam)
> Sysinfo: support configuration files installed system wide [v2]

- avocado/core/runners/avocado_instrumented.py
- avocado/core/teststatus.py
- avocado/plugins/legacy/replay.py
- avocado/plugins/runner.py
- avocado/plugins/runner_nrunner.py
- avocado/plugins/testlogs.py
- docs/source/guides/user/chapters/concepts.rst
- optional_plugins/html/avocado_result_html/__init__.py
- selftests/functional/test_legacy_replay_basic.py
There are a number of test status which are not being used (maybe have never been).  Lets remove them, and rename and document the current definitions to better match the general style.
---
Changes from v1 (#4510):
* Renamed `STATUSES_SUCCESS` to `STATUSES_MAPPING`
> Test status: remove obsolete and rename / document definitions [v2]

- avocado/core/job.py
- avocado/core/messages.py
- avocado/core/nrunner.py
- avocado/core/runners/avocado_instrumented.py
- avocado/core/status/repo.py
- avocado/plugins/runner_nrunner.py
- docs/source/guides/contributor/chapters/runners.rst
- examples/nrunner/runners/avocado-runner-foo
- selftests/unit/test_status_repo.py
- spell.ignore
This is the messaging between runners and avocado core. It adds the ability to nrunners sending messages to avocado core in runtime. It is created from #4479
As example when you run the instrumented test it will create a test log file under job/test-result/test
It based on #4418, and it solves part of #4308
---
changes from v1 (#4507):
* Removal of `MessageProcessor`, every handler can delegate work to other handlers.
* Fixes in documentation and docstrings
* Moved creating path to the ` _save_to_file()` method
* Rename the `status` variable to `message`
> Nrunner comunication [v2]

- avocado/core/messages.py
- avocado/core/nrunner.py
- avocado/core/runners/tap.py
- avocado/plugins/runner_nrunner.py
- selftests/functional/test_nrunner.py
- selftests/unit/test_nrunner.py
The current changes to the message processing resulted in the stdout/stderr files not being preserved. This restores it.
---
Changes from v1 (#4515):
* Added docstring with note about text log messages and new lines handling (@beraldoleal)
* Preserve python-unittest output
> Nrunner: restore stdout/stderr log files [v2]

- .github/workflows/ci.yml
Only a single commit is fetched by default, for the ref/SHA that triggered the
workflow. Set fetch-depth: 0 to fetch all history for all branches and tags.
> gh-actions: Fixes fetch

- avocado/plugins/assets.py
- selftests/functional/plugin/test_assets.py
The asset plugin is not returning meaningful exit code on some
failures and success situations.  Let's make sure users can count on
that.
> Assets Plugin: return meaningful exit codes

- examples/testplans/release/pre.json
- selftests/pre_release/tests/check-copr-rpm-version.sh
Instead of installing the "latest" package and looking for signs
of installation, let's request the exact package based on its
NVR.
Also let's be more strict with possible errors from the script.
> COPR check: attempt to install a specific package NVR

- avocado/core/decorators.py
- avocado/core/test.py
- selftests/functional/test_skiptests.py
There are two different issues with the skip decorators fixed here:
1) the condition for executing setUp() methods were not being evaluated dynamically
2) where no skip would be performed, the test function would also not be performed
> Skip Decorators: fix issues when setUp or the test function would/would not be run

- avocado/core/nrunner.py
- avocado/core/plugin_interfaces.py
- avocado/utils/datadrainer.py
As mentioned by @pevogam over #4476, using ``abc.ABC`` is much simpler
and direct when compared with ``metaclass=ABCMeta``. 
Since python 3.4, the abc module contains a helper class called ``ABC`` that
will set the metaclass internally. This makes creating an abstract class
more readable and simple as it is only necessary to inherit from ``ABC``.
Avocado, currently, supports python 3.5+ so version should not be a
problem.
Signed-off-by: Tiago Honorato <tiagohonorato1@gmail.com>
> Introduce direct inheritance with abstract classes

- avocado/plugins/testlogs.py
- selftests/functional/plugin/test_logs.py
- setup.py
Adds the test start and finish information in the `job.log`. So, if a
test "1-foo" passes, that should be easy to spot in the job.log file.
Reference: #4366
>  Log information when running tests

- avocado/utils/asset.py
If the Asset.fetch() caller does not provide a hash for the asset then
it is not possible to check its integrity. Problems may arise from using
corrupted files. So let's log a message warning the user about it.
> assets: warn the user when a hash is not provided

- avocado/core/messages.py
- avocado/core/nrunner.py
- selftests/functional/test_output.py
- selftests/unit/test_nrunner.py
This introduces the `category` attribute of a Task. It can be used to keep track of different kinds/categories of Tasks running and take actions based on it. The default value of a Task category is 'test'.
This also changes the `avocado.core.messages` to avoid non-`test` tasks being accounted as tests.
> [NRunner] Introduce task category v3

- avocado/utils/dmesg.py
when skip_dmesg_messages() return nothing getting failed in
collect_errors_by_level(),to avoid this error define a variable
dmsg_log with empty string.
> fix the issue: local variable 'dmsg_log' referenced before assignment

- avocado/plugins/run.py
- selftests/functional/test_basic.py
When using ignore-missing-references, Avocado was returning
AVOCADO_JOB_FAIL without explaining the reason. Since we don't have
exactly an job failed here, I'm changing the return code and adding a
warning message. Fixes #4527.
> better output message and code when using ignore-missing-references

- avocado/core/messages.py
- avocado/core/test_id.py
Some `ResultEvents` plugins expecting that when task is a test that the
identifier is `avocado.core.test_id.TestID`, but this is not enforced an
even the default identifier of Task is not `TestID` but it is a string.
This PR adds the ability to convert `Task.identifier` to `TestID`
before is used by `ResultEvents` plugins.
---
Changes from v1 (#4550)
* The convertor moved from the Task to Messages.
Changes from v2 (#4554)
* The convertor moved from the Messages to TestID.
> Task identifier as TestID [v3]

- avocado/core/suite.py
When no config is used and default one is used (None) an AttributeError
will happen here. Fixes #4573.
> core.suite: small fix on getting config

- setup.py
`selftests/isort.sh` is missing from the list of commands executed for the lint checks.  This was caught when a local failure was not caught by the GitHub Actions job.
> Lint: add isort check

- avocado/plugins/list.py
Introducing the --json option to the 'list' command.
Fixes #4538.
Signed-off-by: Beraldo Leal bleal@redhat.com
- renamed --save-to-json to --json
- Removed "append" mode (now using "write" mode);
- Tags are saved as dict instead of string;
- Lazy format of tags (only at display() method)
> plugins.list: Adding a machine-readable output for 'avocado list' (v2)

- avocado/plugins/list.py
> isort: fixing import order for avocado/plugins/list.py

- avocado/core/loader.py
- avocado/plugins/json_variants.py
- avocado/plugins/legacy/replay.py
- avocado/plugins/run.py
- avocado/plugins/runner_nrunner.py
- avocado/plugins/spawners/podman.py
- avocado/plugins/xunit.py
- optional_plugins/result_upload/avocado_result_upload/__init__.py
- optional_plugins/resultsdb/avocado_resultsdb/__init__.py
- optional_plugins/varianter_yaml_to_mux/avocado_varianter_yaml_to_mux/__init__.py
The automatically generated help message reuses the option names as
their "metavar" is this makes the output quite confusing in some
cases.
This is an attempt to make the help message more human friendly.
---
This is attempts to address [this type](https://github.com/avocado-framework/avocado/pull/4583/commits/419a455e7b0f615c2e40df6241ce59adc5bcd7a9#r631875133) of "regression".
> Improve the output of "avocado run --help"

- selftests/check.py
With the addition of new tests, the static checks started to lose the output while running. Adding a new status server port to the job related to the static checks fixes the problem.
Fixes #4592 
> [bug] fix the status server conflict that prevents output

- optional_plugins/html/setup.py
Jinja2 and Markupsafe versions were being pinned because of Python 3.5
requirements, which are not applicable anymore since 8ece3e244.
This also fixes a version conflict caused when other tools (such as
readthedocs.org) will use the latest Jinja2 versions.
Fixes: https://github.com/avocado-framework/avocado/issues/4596
> HTML plugin: do not pin to Python 3.5 compatible requirements

- avocado/plugins/diff.py
- avocado/plugins/distro.py
- avocado/plugins/variants.py
Follow-up for PR #4587.
Improve the output of generated help messages by diff, distro
and variants to make the output more readable.
Signed-off-by: Ana Guerrero Lopez <agl@redhat.com>
> Update outputs of avocado <subcommand> --help

- avocado/core/nrunner.py
- avocado/core/suite.py
- avocado/plugins/runner_nrunner.py
- python-avocado.spec
- selftests/functional/test_basic.py
- selftests/unit/test_job.py
- setup.py
This commit introduces the `--dry-run` option for nrunner. When you will
use `--dry-run` it will change every runnable kind to `dry-run` and the
tests will be run inside `DryRunRunner` which mark them as canceled.
Reference: #4575
> Dry-run for nrunner

- avocado/core/plugin_interfaces.py
- avocado/core/resolver.py
- docs/source/guides/contributor/chapters/plugins.rst
- examples/plugins/tests/magic/avocado_magic/resolver.py
- examples/plugins/tests/magic/setup.py
Some test might be able to be resolved without a reference. Config
files or other parameters from user can be used for that. As an example
is avocado vt which can use Cartesian configuration for resolving tests.
This commit adds the ability to discover tests from different data
without the test references.
---
Changes from v1 (#4574)
Instead of creating `EmptyReference`. This PR introduces `Discoverer` plugin interface.
Changes from v2 (#4591)
* Removed commit about `list --resolver`
* Added example with Magic Tests
* Documentation update
> Empty reference in resolver [v3]

- python-avocado.spec
The exclusion rule was added to avoid requiring both Python 2 and
Python 3 interpreters.  Now, that Python 3 is supported, this rule
can be excluded.
Note: even though there's no explicit documentation in Fedora's
packaging guidelines, what I found by looking at other packages
is that, if a package is simply a library, it will not contain
a "/usr/bin/python3" requirement, and will rely only on a
"python(abi) = 3.X" requirement.  But, if it contains a script
with a "#!/usr/bin/python3" shebang line, it will contain an
explicit requirement.  So, by removing this line completely,
the package will now have a "/usr/bin/python3" requirement.
Reference: https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/
> SPEC: Remove Python interpreter binary exclusion

- avocado/utils/ssh.py
Ran into this issue when trying to connect to an AIX partition. The ControlPath was not created since ssh stated this: "Pseudo-terminal will not be allocated because stdin is not a terminal.". Passing in the '-T' flag supressed this message and the ControlPath was created.
Signed-off-by: Cristobal Forno <cforno12@linux.ibm.com>
> ssh.py: disable pseudoterminal by default.

- .cirrus.yml
- avocado/core/settings.py
This fixes an issue and allows/checks that Avocado can be used with an egg-based distribution.
---
This is related to https://github.com/avocado-framework/avocado/issues/4336
> Allow Avocado to be used from an egg distribution

- examples/testplans/release/pre.json
- selftests/pre_release/tests/readthedocs.py
readthedocs.org is the platform we host documentation *and* release
notes, so it's very important that it's operational before we do our
release.
Experience has taught us that even outside changes (new requirements
being release on PyPI) can break the builds and cause issues with the
release process.
Let's add an automated check to catch possible build failures before a
release is tagged.
Reference: https://github.com/avocado-framework/avocado/issues/3456
> Pre-release tests: check the status of readthedocs.org builds

- avocado/utils/software_manager/backends/rpm.py
Current code got `inst_version` as `byte` type and cannot compare with
a string or error would be throw out. Replace with `process.run()` to
get string type of output to fix the problem.
Signed-off-by: Haijiao Zhao <haizhao@redhat.com>
> rpm: Get string type of output of installed version to be compared with

- selftests/functional/test_requirements.py
- selftests/functional/test_runner_requirement_package.py
With https://github.com/avocado-framework/avocado/pull/4622, the tests collision described here https://github.com/avocado-framework/avocado/issues/4620 are evident.
Let's skip the functional tests for the requirements resolver until the collision problem is fixed.
> Skip requirements resolver functional tests until collision is fixed

- avocado/core/job.py
- avocado/core/status/repo.py
- avocado/plugins/runner_nrunner.py
The nrunner implementation currently fails to set the test statuses that ocurred on tests to the summary attribute. That attribute controls the exit code that the Avocado command line will set, to reflect tests that failed, had errors, etc.
---
Note: the reason for the CI failures are discussed in #4620
---
Changes from v1 (#4619)
* split the nested list comprehension into a helper utility method
* rename `tasks` into `runtime_tasks`
* fix typo in docstring
> nrunner: set the occurred test status to the suite summary [v2]

- avocado/core/__init__.py
- avocado/core/job.py
- avocado/core/runner.py
- avocado/core/test.py
- avocado/plugins/runner.py
- avocado/utils/asset.py
- avocado/utils/debug.py
- avocado/utils/filelock.py
- avocado/utils/gdb.py
- optional_plugins/robot/avocado_robot/runner.py
- selftests/functional/test_basic.py
- selftests/functional/test_loader.py
- selftests/functional/test_utils.py
- selftests/unit/utils/test_process.py
This should make Avocado more reliable when calculating times. It uses
the monotonic clock that can't go backwards.
This closes #3565
Reference: https://github.com/avocado-framework/avocado/issues/3565
> use monotonic time

- avocado/utils/asset.py
If multiple tests in parallel uses the same image from the same
location, only one thread needs to create the directory. Fixes #4631.
> utils/assets: fixing FileExistsError when running in parallel

- avocado/plugins/runner.py
- avocado/plugins/runner_nrunner.py
This is a preparatory work for variants support in the nrunner.  This adds focuses on the suite, accounting for the number and name of tests produced by variants.  The next step is to pass through the parameters (both from variants and from standalone parameters) to the runners.
By running `avocado run --test-runner=nrunner examples/tests/sleeptest.py -m examples/tests/sleeptest.py.data/sleeptest.yaml` before this PR one gets:
```
$ avocado run --test-runner=nrunner examples/tests/sleeptest.py -m examples/tests/sleeptest.py.data/sleeptest.yaml 
JOB ID     : cbcf5c6f66fdd90516afa40c613b6482d7c66e94
JOB LOG    : /home/cleber/avocado/job-results/job-2021-06-01T00.33-cbcf5c6/job.log
(1/1) examples/tests/sleeptest.py:SleepTest.test: STARTED
(1/1) examples/tests/sleeptest.py:SleepTest.test: …
```
> nrunner: prep work for variants support

- contrib/scripts/avocado-find-unittests
- contrib/scripts/avocado-safeloader-find-python-unittest
- contrib/scripts/find-python-unittest
- selftests/safeloader.sh
This fixes the contrib script and adds a new one that finds Python unittests. It's also a prep work for #4625.
---
Changes from v1 (#4636):
* Turned Cirrus CI task into a test (`selftests/safeloader.sh`)
* Renamed variable `s` into `suite_or_test`
* Replaced `git grep` for regular `grep` in `selftests/safeloader.sh`
* Moved imports to the top of the `find-python-unittest`
> Safeloader: improve the checks and contrib scripts for python unittests [v2]

- avocado/core/runners/requirement_package.py
- selftests/functional/test_requirements.py
- selftests/functional/test_runner_requirement_package.py
On issue https://github.com/avocado-framework/avocado/issues/4620, when two tasks try to fulfill a package, one is smart enough to wait for the other to finish, but as soon as the lock is released, one may fail if the other has still work to complete, like erase the cache.
This patch checks if the failure was not a false negative.
This does not fix #4620 as tests with the same requirement may still collide. Easy to reproduce on s390x. But it reduces the chance of happening on other architectures and allows some self-tests to be enabled.
> Adjust requirement_package.py runner to reduce collision chances

- avocado/core/messages.py
- avocado/core/runners/avocado_instrumented.py
- avocado/core/runners/requirement_package.py
- docs/source/guides/contributor/chapters/runners.rst
- selftests/unit/test_runner_requirement_package.py
The saving of the nrunner messages was too strict. The stdout and stderr
messages could be only bytes and the log messages could be only stings
without a new line at the end. This commit makes the saving more
flexible.
---
Changes from v1 (#4526):
* Typo fixes
*  Moved `filename` argument to ` _save_to_file()`
*  All messages been made binary
> Proper nrunner message saving [v2]

- avocado/core/safeloader/docstring.py
Instead of trying to parse a perfect JSON string, let the safeloader parse anything inside `requirement={}` and the JSON module handle malformed strings.
> [safeloader] stop trying to parse a perfect JSON string

- avocado/core/requirements/resolver.py
When a test depends on a requirement, the requirement runnable needs to know which are the configurations from the test.
> [Requirements Resolver] add config from test to requirement

- avocado/core/safeloader/core.py
- selftests/unit/test_safeloader_core.py
This function was once used for what it's named after: finding class
and method names in a Python source code file.
The problem with that function is that it is not being used to
actually power Avocado's safeloader method.  Worse, it was used in the
unittests, giving a false impression that all test classes in methods
on its own Python file were being properly found.
This removes this function, and some tests that depended on it.  Now
that the *actual* Avocado code to find tests is being used, and issue
#4625 is still not fixed, the import of "selftests.utils" was switched
to a relative import so that the "MultiLevel" class and its tests are
found, and the "FindClassAndMethods.test_self", which references all
tests in the file, passes.
Tests were removed here, but they covered unused …
> safeloader: remove legacy and unused find_class_and_methods() function

- docs/source/guides/contributor/chapters/runners.rst
It adds the fail_reason parameter into finished message documentation.
> Messages documentation fix

- avocado/core/safeloader/core.py
There are two major chunks of code in `safeloader/core`: `_examine_class()` and `find_python_tests()`.  They are very similar, and should ASAP contain much less duplicate code than they currently have.
This is another round of light improvements to the maintainability of the code, still in preparation for a fix for #4625.
> Safeloader: standardize parameters names and order

- docs/source/guides/writer/chapters/writing.rst
These warnings are about features that have been deprecated in version
60.0, and removed in 62.0, more than two LTS versions ago.
It's not highly probably that this information will be of use to
users of the current version.
> Docs: remove warning about environment variables from version 62.0

- avocado/core/safeloader/core.py
- avocado/core/safeloader/imported.py
- avocado/core/safeloader/module.py
- selftests/unit/test_safeloader_imported.py
- selftests/unit/test_safeloader_module.py
Currently, the "data structure", if one can call it that, to keep track of "objects" imported by modules inspected by the safeloader code is a string.  In most situations, it's easy to pack/unpack the following pieces of information from it:
1. the base path of the module
2. the name of the module
3. the name of the object (usually a class, but optional)
But, once you construct a filesystem-like representation of that, you will fail to unpack the individual members correctly when, for instance, the module has multiple members, like "module.submodule", which becomes "module/submodule".  At that point, is "submodule" a component of 2 or 3? And is "module" a component of 1 or 2?
We need to know the individual components, because when looking at statements such as:
```python
from …
```
> safeloader: introduce "imported symbol" module

- .cirrus.yml
Remove Debian 9 (stretch) and add instead Debian 11 (Bullseye),
that will be released next month.
Update tags to use codenames instead of versions. The codename
always point to the latest release, this saves us to update
the tag every time there is a new point release.
Fixes: #4680
> cirrus: update debian images

- avocado/core/messages.py
- docs/source/guides/contributor/chapters/runners.rst
This PR adds a new type of nrunner messages, the `FileMessage`. This message comes with runners ability to create runner specific files and subdirectories in avocado Task directory. This feature can be used when you want to log some runner specific data. It will be used in sysinfo runner.
> Nrunner File message

- .cirrus.yml
Remove Debian 9 (stretch) and add instead Debian 11 (Bullseye),
that will be released next month.
Update Debian 10 to 10.9.
For Debian 11, untils it's being released, used the codename with date.
Fixes: #4680
> cirrus: update debian images (continuation)

- avocado/core/nrunner.py
- avocado/core/suite.py
This PR does 2 two changes to allow passing all the config options to a runnable:
* This handles the nrunner serialization/deserialization process involved in the config. It introduces a mechanism that converts sets into lists inside a dictionary. The dictionary key `__encoded_set__` is used in the decoding process to convert the option back to a set.
* Change the suite to pass all the config options to a runnable instead of filtering.
> Extend runner config options

- avocado/utils/asset.py
When multiple process are downloading the same asset in parallel we have
unnecessary downloads that could be avoided. This attempts to fix that.
Also since that we are getting the lock earlier lets remove the private
call to tempfile._get_candidate_names() and make things simple here.
Fixes #4645, Fixes #4640
> utils.asset: Getting FileLock before downloading

- avocado/utils/software_manager/backends/dpkg.py
Some versions of `ar` do not have the --output parameter available. This patch uses a different approach changing the directory to the destination and then extracting the source file.
> [sogtware-manager] Avoid using --output from `ar` command

- docs/source/quickstart/index.rst
The Avocado project moved from codecov to codeclimate. The codecov badge is outdated and needs to be removed.
> Remove codecov badge from "Build and Quality Status"

- .travis.yml
Travis new credits are not much, let's save some time while GH actions is not
ready. If @ana's work on GH actions is good for merge, then this can be
discarded.
> travis: Remove smokechecks and nightly builds to save some time

- avocado/core/safeloader/core.py
- contrib/scripts/avocado-safeloader-find-avocado-instrumented
We're currently manually adding the base directory of the module we're investigating, which is not standard Python behavior.
This this non-standard behavior, and prevents modules being found at non-expected places, and thus classes *not* being found on those non-expected places.
> Safeloader: do not use module directory on import paths

- avocado/core/runners/requirement_asset.py
- docs/source/blueprints/BP002.rst
- docs/source/guides/user/chapters/requirements.rst
- examples/nrunner/recipes/runnables/requirement_asset.json
- python-avocado.spec
- selftests/functional/test_runner_requirement_asset.py
- selftests/unit/test_runner_requirement_asset.py
- setup.py
This runner handles assets using the Avocado Asset utility. It can be used as a requirement type on tests that define requirements.
Changes from v1 (#4600):
- Skip the test if `name` is empty and do not process anything else.
- Correctly handle the `cache_dirs` based on the runnable config.
> [nrunner] introduce avocado-runner-requirement-asset [v2]

- selftests/check_tmp_dirs
This was checking for both files and directories, with this change
it'll only check for directories.
> selftests/check_tmp_dirs: only check for dirs

- .github/workflows/ci.yml
I have added all the checks to the same workflow and also dependencies between jobs. You can see it graphically at: https://github.com/ana/avocado/actions/runs/949165905
There are 3 main jobs running first: Windows, Linux and OS X with latest python. 
In the case of Windows and OS X, all the test run in the latest Python stable release - 3.9 right now - and if everything  goes fine, then it'll run the smokechecks in Python 3.6  - 3.8. If during the run of the main job in Python 3.9 any of the steps fails, everything is canceled.
For Linux,  all the test run in the latest Python stable release 3.9 and if everything goes fine, then it'll run the checks in Python 3.6-3.8 and the code coverage test that is a long one.
What happens when the test fails? Here an example where the signed off has …
> GitHub Actions: initial implementation (v3)

- Makefile
- setup.py
Add a new setuptools command to build the avocado manpage independently.
Reference: https://github.com/avocado-framework/avocado/issues/4372
> Add setuptools command to build the man page

- .travis.yml
Update distribution from Xenial LTS (16.06) to Focal LTS (20.04).
Update to Python 3.9
Only leave non-amd64 builds: arm64, ppc64le and s390x
This will make Travis to look like this https://travis-ci.com/github/ana/avocado/builds/230556863
> .travis.yml: update following move to GHA

- contrib/job-scripts/coredump-handling/post.d/002-link-core-to-tests
- contrib/scripts/avocado-get-job-results-dir.py
- contrib/scripts/avocado-safeloader-find-avocado-instrumented
- contrib/scripts/avocado-safeloader-find-python-unittest
- contrib/scripts/find-python-unittest
- contrib/scripts/summarize-job-failures.py
- contrib/scripts/vmimage-populate-cache.py
- docs/source/guides/writer/chapters/writing.rst
- examples/tests/synctest.py
- examples/tests/whiteboard.py
- optional_plugins/golang/setup.py
- optional_plugins/html/setup.py
- optional_plugins/result_upload/setup.py
- optional_plugins/resultsdb/setup.py
- optional_plugins/robot/setup.py
- optional_plugins/varianter_cit/setup.py
- optional_plugins/varianter_pict/setup.py
- optional_plugins/varianter_yaml_to_mux/setup.py
- scripts/avocado-run-testplan
- selftests/.data/unittests.py
- selftests/.data/whiteboard.py
- selftests/check_tmp_dirs
- selftests/run
- selftests/unit/utils/test_diff_validator.py
- setup.py
We are using python3 as dependency, and some distributions don't have 'python' symlink. Let's use python3 for all envs.
> Forcing python3 as default environment alias

- docs/source/guides/user/chapters/introduction.rst
The missing double-` `` ` fencing around `--` in the Note is causing ReadTheDocs to format `--` as an en dash.
> Docs: Protect formatting inside a Note box, in the Intro guide

- avocado/core/safeloader/core.py
- avocado/core/safeloader/imported.py
- avocado/core/safeloader/module.py
- selftests/.data/safeloader/data/imports.py
- selftests/functional/test_resolver.py
- selftests/safeloader.sh
- selftests/unit/test_loader.py
- selftests/unit/test_safeloader_core.py
- selftests/unit/test_safeloader_imported.py
- spell.ignore
Among other things, this supports compound import statements with non-relative imports.
It fixes #4625, and greatly extends the coverage of the safeloader by comparing every single Python unittest in our tree with the native (load/executable) approach of the `unittest` library.
At least two other bugs have been found and fixed too (info in the respective commits).
---
Changes from v1 (#4712):
* New commit addressing issue #4611
* Improved commit message on previous `ImportedSymbol.from_statement()` limitation
* Removed all methods from `ImportedSymbol` that were required for compatibility with the filesystem-like method of keeping track of path/module/class imports.
> Safeloader: support compound, non-relative imports [v2]

- avocado/core/main.py
When the SIGINT is sent to the avocado in the early stages the avocado
will crash. This will compare if the exception is a KeyboardInterrupt and
avoid a generic message, since it was intentional. Fixes #4613.
- Added a new line
- Using class object instead of class name
- Exit code now is  `AVOCADO_JOB_INTERRUPTED`
> core.main: Handling KeyboardInterrupt on early stages v2

- avocado/core/messages.py
When the avocado receives a whiteboard message from runner. The
whiteboard is saved to the file, but it is not saved to the test
results. Because of this problem, the result plugins such as
`JSONResult` don't have access to the whiteboard value.
Reference: #4717
> Whiteboard results fix

- docs/source/quickstart/index.rst
Add links to the internal documentation, mostly the user guide
and a few other small typo and formatting fixes.
> doc/quickstart: add a bunch of links

- .cirrus.yml
- .github/workflows/weekly.yml
Add an initial weekly workflow testing with latest development Python. It'll run on Mondays at 5:00 UTC.
> Avocado CI checks: add weekly GHA and update cirrus

- avocado/utils/ssh.py
When the user being used for ssh is different from the currently
logged in user, scp will stop and ask for a password because it
cannot find the ControlPath. Specifying the user solves this issue.
Signed-off-by: Jacob Root <otis@otisroot.com>
> Pass user to scp command

- avocado/core/runners/avocado_instrumented.py
- optional_plugins/robot/avocado_robot/runner.py
- selftests/functional/plugin/test_assets.py
- selftests/functional/test_fetch_asset.py
- selftests/unit/plugin/test_vmimage.py
- selftests/unit/test_datadir.py
- selftests/unit/test_hintfiles.py
- selftests/unit/test_settings.py
- selftests/utils.py
- setup.py
This is a v2 of https://github.com/avocado-framework/avocado/pull/4728
For the selftests, it's now reusing a temporary directory created by the class or inheriting from `TestCaseTmpDir`and using `self.tmpdir`
> Better handling of avocado temporal files during selftests - v2

- avocado/core/runners/avocado_instrumented.py
- avocado/core/runners/requirement_package.py
- avocado/core/runners/tap.py
- avocado/core/runners/utils/messages.py
- docs/source/guides/contributor/chapters/runners.rst
- examples/nrunner/runners/avocado-runner-foo
- examples/plugins/tests/magic/avocado_magic/runner.py
- optional_plugins/golang/avocado_golang/runner.py
- optional_plugins/robot/avocado_robot/runner.py
It brings helper methods for creating avocado messages. This will
simplify the usage of avocado messages for runners developers. Because
they will be able to use a messaging system without knowledge of the
internal structure.
Reference: #4627
---
Changes form v1 (#4662)
* Documentation and docstring fixes.
* Removal of message helpers with base runners because of podman issue
* Usage of a OOP approach
> Nrunner helper methods for sending messages [v2]

- contrib/scripts/find-python-unittest
Python's unittest.loader module, at _find_test_path(), when calling
_get_module_from_name(), may fail with a ModuleNotFoundError because
it doesn't include the current directory in the system path on Python
3.7 and earlier.  Python 3.8 and later changed that behavior.
In the specific case of ./selftests/safeloader.sh, it fails at some
tests with:
ModuleNotFoundError: No module named 'selftests.utils'
> contrib/scripts/find-python-unittest: adapt to pre Python 3.8 behavior

- avocado/plugins/spawners/podman.py
The podman image is already being fetched from the job/suite
configuration, instead of the default settings.  Let's do the
same for the podman binary.
> Podman Spawner: use podman binary from given configuration

- .cirrus.yml
- Makefile
- setup.py
Changes from v3 of https://github.com/avocado-framework/avocado/pull/4725
* Add the option --external to develop that will install and  uninstall external plugins.
* extra ball: Use the list-based version of run() for the manpage command, so there is no need for a shell.
> Add custom setuptools command for 'develop' (v3)

- optional_plugins/html/tests/test_html_result.py
- selftests/check.py
- selftests/functional/test_output.py
- selftests/functional/test_sysinfo.py
Updates to be able to opt-out all the plugins tests so we can split the plugins and still keep the tests in the avocado repository.
> Allow to run the selftests without testing the plugins

- .cirrus.yml
- .github/workflows/ci.yml
- python-avocado.spec
- setup.py
This introduces support for excluding optional plugins on "python3 setup.py develop", which is necessary to restore support for building RPMs.
> Setup: add support for excluding optional plugins on develop

- avocado/core/nrunner.py
- avocado/core/suite.py
- avocado/plugins/runner_nrunner.py
After the #4688 the `Task` has access to the 'nrunner.status_server_uri'
config variable, and it can be used for creating `Task.staus_services`.
Reference: #4352
> Task status_server_uri

- avocado/core/plugin_interfaces.py
- avocado/core/resolver.py
- avocado/core/suite.py
- avocado/plugins/resolvers.py
The resolvers don't have access to the config variable, and they are
using settings.as_dict(). Unfortunately, this method returns only
config from command line and config files. When the configuration is
created by Job API, the settings.as_dict() doesn't respect that. This
leads to the incompatibility between resolvers config and suite config
created by TestSuite.from_config() in Job API.
This problem was hidden because avocado default resolvers don't need
config for resolving references and TestSuite.from_config() rewrites
the runnables config created by resolvers.
It is not such a big problem for avocado default resolvers, but it is a
problem for vt resolver which is using config in resolving process.
---
Changes from v1 (#4713):
* Passing …
> Config variable for resolvers [v2]

- avocado/core/__init__.py
- avocado/core/data_dir.py
- avocado/core/job.py
- avocado/plugins/config.py
data_dir module was created way before our new settings logic was
introduced, default values now are defined at registration time. When
users define a custom value, in some cases Avocado is replacing this
value with a default hardcoded value, instead of respecting users'
choice (for instance when users have no permissions). base_dir is
already defined as default at `~/avocado/`, let's get the values from
the config dict here too. This fixes #4443.
> core.data_dir: make datadir.paths.base_dir consisent

- avocado/core/messages.py
- selftests/functional/plugin/test_jsonresult.py
The path to the test log file wasn't send to the `end_test` plugins.
This commit fix it and adds the appropriate test to catch future bugs.
Reference: #4750
---
Changes from v1 (#4754):
* Test fix - create its own status server.
> logfile value in results.json [v2]

- selftests/check.py
Use only half of the CPUS on arm64 for some tests to avoid problems
with the Travis arm64 builds.  Fixes #4786
References: https://github.com/avocado-framework/avocado/issues/4768
I think this is the best solution for the referenced issue, and it's better to do a  separate PR for other modifications in `selftests/check.py`
> selftests/check.py: workaround for travis on arm64

- avocado/core/safeloader/core.py
- selftests/unit/test_safeloader_core.py
Avocado currently does not support test classes whose parents are
generics, but, it's choking and breaking the discovery of relevant
test classes when one exists.
Let's simply skip classes with generic parents.
> safeloader: do not choke on classes with generic parents

- avocado/core/job.py
- avocado/core/output.py
- avocado/core/runners/utils/messages.py
We are messing up with the root log. After finishing the run, we
need to restore back level and handlers. Because logging is a singleton,
according to the documentation we should be using a context manager for
selective logging, but unfortunately this will not be trivial today. So this should fix it.
Signed-off-by: Beraldo Leal bleal@redhat.com
* Added last commit to handle runners as well.
> logging: we should not remove handlers when using the root log (v2)

- avocado/core/messages.py
- avocado/core/test.py
- optional_plugins/html/avocado_result_html/__init__.py
This is a v2 from https://github.com/avocado-framework/avocado/pull/4762
Reference bug: https://github.com/avocado-framework/avocado/issues/4709
The first and third commit are identical to v1 and what changes is the middle commit that adds both actual_time_start and actual_time_end with nrunner.
The problem with monotonic for the legacy runner was introduced in 14937705f15c8334220599edc1047e7563d04c80 from May this year. The problem with the new runner was introduced in b600a5fe08112ee15b41b1150d849fd63ef276f6 from September 2020, which means it has been around for 10 months without anyone noticing!
I'm wondering how we can test this - because it's a "visual" test - to avoid this problem or a similar one happening a third time.
> show correct start time in HTML reports (v2)

- avocado/core/safeloader/core.py
- avocado/core/test.py
- docs/source/guides/writer/chapters/writing.rst
- examples/tests/sleeptest_async.py
- selftests/functional/test_coroutine.py
- selftests/functional/test_task_statemachine.py
- selftests/unit/plugin/test_spawner.py
Python coroutines, AKA "async def" methods, are a common use case when
the code under test is based on asyncio.
Instead of forcing the user to come up with boiler plate code to run
each of the coroutines in a loop within a test, it's easier to
identify such methods and handle them accordingly.
One further possible improvement on top of this is to let the user
configure how the coroutine should be executed.  In this initial
implementation it simply gets one event loop and runs the coroutine
until it finishes.
Reference: https://github.com/avocado-framework/avocado/issues/4767
> Test: support for coroutines as tests

- avocado/plugins/assets.py
Sometimes users will want to run the same tests multiple times.  On
those situations, assets should be attempted to be fetched only once.
> assets plugin: avoid fetching the same asset multiple times

- avocado/core/safeloader/core.py
- avocado/core/test.py
- selftests/unit/test_loader.py
`avocado.Test.teststmpdir` property is badly named because it matches what is expected to be a test.
Because Avocado inherits from Python's `unittest.TestCase`, and the extended coverage for corner cases in the safeloader introduced, along with the characteristic of the resolver that will give other plugins a chance, this property is now being found as a Python unittest test method.
These changes prevent that from happening, resulting in a more straightforward resolution.  That is, the `python-unittest` resolver plugin will never find tests in a `avocado.Test` based class that contains a `:avocado: disable` tag. 
Besides this change, a method rename is desirable, but this will cause API compatibility issues, which we guarantee until a new LTS release. So, for now, let's disable all test* …
> Safeloader: respect disable on all Python tests and ignore teststmpdir

- avocado/core/runners/avocado_instrumented.py
- selftests/functional/plugin/test_jsonresult.py
The avocado-instrumented runner wasn't gathering the fail-reason of
tests. This fix the problem and adds the appropriate test to catch
future bugs.
Reference: #4749
---
Changes from v1 (#4753):
* Test fix - create its own status server.
> Instrumented tests with fail reason [v2]

- optional_plugins/html/tests/test_html_result.py
- python-avocado.spec
The Fedora `python-avocado` package was recently brought back as a non-modular package. To un-retire the package, it underwent a fresh Fedora package review process which resulted in cleanup to the SPEC file. (See https://bugzilla.redhat.com/show_bug.cgi?id=1930948 for discussion.)
This PR brings the downstream package SPEC file cleanup to the upstream SPEC file.
Also included is a patch to specify the complete relative path to `passtest.py` in the test HtmlResultTest.test_output_compatible_setup_2. Otherwise, for reasons I don't understand, that test fails because it can't locate `passtest.py` to run it when %checks are run with the revised SPEC.
> Spec file cleanup resulting from downstream package review

- avocado/core/nrunner.py
- docs/source/guides/user/chapters/introduction.rst
If a script has not permission or has invalid syntax, subprocess.Popen
will raise exceptions that we aren't capturing. This will avoid some
tests being marked as SKIP without reason. Fixes #4793
Besides that, I'm also adding more info to our User's guide on hint files.
> nrunner: make sure any error will be captured, plus minor docs updates

- .github/workflows/ci.yml
- .github/workflows/weekly.yml
- .travis.yml
- Makefile
- docs/source/guides/contributor/chapters/environment.rst
- requirements-dev.txt
The selftests requirements are a subset of the requirements
needed for development. Renaming the file to requirements-dev.txt
allows us to use this file for all development requirements.
> Rename requirements-selftests.txt to requirements-dev.txt

- avocado/core/plugin_interfaces.py
- avocado/core/resolver.py
In the 43286b5fa3083fc0d3fb4381a4a40024d120eb81 the incompatibility with Setting plugin was introduced. Because of that, avocado doesn't respect plugin specific configuration. This commit adds `settings` variable import to the `plugin_interfaces.py` Because of that, the `circular import` bug is created when the plugins and Settings is initialized during avocado initialization. This will make this import local to specified plugins, which fix this problem.
> Resolver and Discoverer plugins initialization fix

- avocado/utils/ar.py
- avocado/utils/software_manager/backends/dpkg.py
- avocado/utils/software_manager/backends/rpm.py
- selftests/.data/guaca.a
- selftests/functional/test_software_manager.py
- selftests/unit/utils/test_ar.py
- selftests/unit/utils/test_software_manager.py
The actual files that users will have access when installing deb packages are not the contents of the "ar" archive, but the contents of the "data.tar.*" tarball.
> Software manager: fix extraction of deb packages

- avocado/core/task/statemachine.py
- selftests/functional/test_nrunner.py
- spell.ignore
Although nrunner has a distributed architecture and new concepts like
Workers and Spawners, we can deliver the failfast feature with some
limitations. Depending on the number of parallel tasks, some tasks might
have already started when an error occurs, because of that, failfast will
work here in a "best-effort" assumption. This change will move all
non-started tasks to the finished queue when failfast is enabled. Fixes #3870
- Using `self._state_machine._status_repo.result_stats` as source of truth
- Assuming that each test suite has its own StateMachine, so no need to double-check
- Complete new implementation using state-machine (Thanks to @willianrampazzo)
> nrunner: adds support to failfast (v3)

- avocado/core/sysinfo.py
While reviewing #4806, I had the impression that less code needed to be duplicated between the nrunner-based and the current sysinfo implementation.  This is an exercise at that, which also results in cleanups and overall improvements (shamelessly copied from @richtja's work).
> Sysinfo: cleanups and preps for nrunner

- avocado/utils/network/interfaces.py
Currently, if the interface does have not an IP address,
"_get_interface_details" will return an empty list, so this is a problem
to set default version=4. Most of the time, we only need the properties
of the interface itself(e.g: get_mtu), only "get_ipaddrs" will use IP addresses in
interface.py.
> interfaces.py: Support get the interface details without IP version

- avocado/plugins/assets.py
- examples/tests/assets.py
One very important parameter of the fetch_assets() call is locations.
Because we currently only support the parsing of strings using the AST
parser, any example that uses locations fails to be recognized as a
asset for being fetched with `avocado assets fetch` or the equivalent
pre-tests plugin.
This adds support for list assignments, and simplifies the assets
example test so that it's easier to read, and supported under assets
fetch.
Fixes: https://github.com/avocado-framework/avocado/issues/4812
> Assets: support assigments with lists

- avocado/core/exceptions.py
- avocado/core/task/statemachine.py
- avocado/plugins/runner_nrunner.py
- selftests/functional/test_nrunner.py
It will make it consistent with the current runner returning
AVOCADO_JOB_INTERRUPTED, also this is adding a
message to the user about the failfast.
> nrunner: failfast: make failfast return AVOCADO_JOB_INTERRUPTED and nice message

- avocado/utils/download.py
Since we are getting 'avocado.test' logger, let's use it, otherwise we
are writing to the root logger.
> utils.download: fixes root logging

- avocado/plugins/assets.py
- avocado/utils/asset.py
- avocado/utils/download.py
Timeout that is already supported by url_download() method is a
different kind of timeout.  Lets implement a subprocess here and just
export the --timeout option to the user. This fixes #4643
> plugins.assets: adding a --timeout option when fetching

- selftests/safeloader.sh
This is some possible debugging aid, if needed in the future, to check an individual Python test file, instead of all of them.
> Safeloader test: support checking a single file

- avocado/plugins/runner.py
The current logic skips the fail when -p and -m command-line options are
used. Their use together is not supported.
> [runner] fail early when -p and -m are used

- avocado/core/suite.py
- avocado/plugins/runner.py
The test suite has enough information to verify that the user has attempted to use both "plain" parameters and variants (through a compatible varianter plugin).  By moving the check to the test suite, we:
1. Avoid crashing Avocado (the current behavior)
2. Automatically give an UI error message
3. Set a meaninful exit code
4. Make it work with any runner (say nrunner and legacy one)
> Variants and Parameters: move check to the test suite

- contrib/scripts/find-python-unittest
The behavior on Python 3.9.6(-2), as packaged in Fedora 34, has changed when compared to Python 3.9.5(-3), and is similar to the behavior before 3.8.0.
Reference: https://bodhi.fedoraproject.org/updates/FEDORA-2021-d613e00b72
> find_python_unittest: fixes on Python 3 9 6

- avocado/utils/download.py
Even before my previous change on this method, url_open can raise
exceptions and we need to catch as soon as possible. We need to make
sure that errors here are logged. Fixes #4829.
> utils.download: catches timeout errors and small fixes

- avocado/core/nrunner.py
- avocado/core/runners/avocado_instrumented.py
- avocado/core/varianter.py
- avocado/plugins/runner_nrunner.py
This PR adds support to variants on nrunner. Tests are still missing.
To test it you can use one of the available yaml files, like:
```
[wrampazz@wrampazz avocado.dev]$ avocado run --test-runner=nrunner -m examples/tests/sleeptest.py.data/sleeptest.yaml -- examples/tests/sleeptest.py
JOB ID     : 264b50b21a505011bf38aafac58f7cb40d73780f
JOB LOG    : /home/wrampazz/avocado/job-results/job-2021-08-05T16.51-264b50b/job.log
(1/4) examples/tests/sleeptest.py:SleepTest.test;run-short-beaf: STARTED
(3/4) examples/tests/sleeptest.py:SleepTest.test;run-long-f397: STARTED
(2/4) examples/tests/sleeptest.py:SleepTest.test;run-medium-5595: STARTED
(4/4) examples/tests/sleeptest.py:SleepTest.test;run-longest-efc4: STARTED
(1/4) examples/tests/sleeptest.py:SleepTest.test;run-short-beaf: PASS (0.51 s) …
```
> [nrunner] Add support to variants on nrunner

- avocado/utils/debug.py
- avocado/utils/gdb.py
- avocado/utils/process.py
- avocado/utils/wait.py
We should limit printed elapsed times to nanosecond precision, i.e.
nine figures after the decimal point.
First, long decimal fractions are difficult to eyeball.  This
is annoying to read at a glance:
Command 'kill -19 1429623' finished with 0 after 0.0005124460049035922s
Whereas this is easier to read at a glance:
Command 'kill -19 1429623' finished with 0 after 0.000512446s
Second, the system call behind time.monotonic(), clock_gettime(2), has
a resolution of one nanosecond.  Additional figures are insignificant.
Signed-off-by: Scott Cheloha <cheloha@linux.ibm.com>
> avocado.utils: limit printed durations to nanosecond precision

- avocado/core/job.py
- avocado/core/status/repo.py
- avocado/core/task/statemachine.py
The nrunner has a much more decoupled design with many more moving
parts (when compared to the legacy runner), for instance:
* workers trying to get tasks to move over their life cycle stages
* tasks being started by different spawner
* tasks asynchronously reporting their status to status servers
It makes it non-trivial to debug where an Avocado internal failure may
be located.
This introduces the convention of the "avocado.core" logging
namespace, following the actual Python module implementation, so that
developers and advanced users can choose to see the nrunner internals
for troubleshooting, debugging, etc.
Because of the hierarchical nature of the namespaces, one can choose
to see all "avocado.core" information with:
$ avocado --show=avocado.core run --test-runner=nrunner ...
Or …
> nrunner: add debugging aids to the Task/StateMachine/Repo system

- avocado/core/nrunner.py
- examples/tests/sleeptest.sh
- examples/tests/sleeptest.sh.data/sleeptest.yaml
This adds variants support to the exec-test test type and an example similar to the avocado-instrumented example.
> [nrunner] add variants support to exec-test

- .cirrus.yml
- .github/workflows/ci.yml
- .github/workflows/setup.yml
- .github/workflows/weekly.yml
- docs/source/guides/contributor/chapters/environment.rst
- docs/source/guides/user/chapters/installing.rst
- python-avocado.spec
- selftests/check.py
- setup.py
This is an intent to wrap up https://github.com/avocado-framework/avocado/issues/4372 and also includes a v2 of one of the commits from https://github.com/avocado-framework/avocado/pull/4798 (command plugin); I have chosen to leave the `Makefile` updates for a different PR
I'm adding two new commands to `setup.py`: plugin and selftests. A new CI pipeline to test well all the commands provided by `setup.py` and updating the documentation.
The new CI pipeline can be seen at https://github.com/ana/avocado/actions/runs/1090390582
> setup.py: add commands test&plugin, add a CI for setup.py and docs update

- avocado/core/nrunner.py
- selftests/unit/test_nrunner.py
Currently loader.loadTestsFromName() will only find tests that are part of
sys.path. We are adding current directory (.) to that path, assuming that test
references will always be a relative path to the current directory. With this
change we will be able to pass a absolute reference (i.e:
/tmp/foo.py:Bar.test_foo) and the nrunner will add the basedir to the sys.path
correctly. Fixes #4840
- s/unittestname/unitttest name/;
- Fixed commit message;
- Removed `if not uri` check;
- Fixed error msg string when invalid uri;
- Reduced the number of calls on property `unittest()`;
- Refactoring on complex property return line;
- Squashed the last commit;
> nrunner: fixes loader.loadTestsFromName() resolution with absolute paths (v2)

- avocado/core/tapparser.py
- selftests/unit/test_tap.py
From the the specs:
"A harness must only read TAP output from standard output and not from standard
error. Lines written to standard output matching /^(not )?ok\b/ must be
interpreted as test lines. All other lines must not be considered test output."
> core.tapparser: non tap messages should be ignored

- avocado/plugins/spawners/podman.py
The primary goal of the Podman spawner is to provide more isolation to
tests, both for the sake of the tests, and for the protection of the
test execution environment (often a developer's workstation).
But the mismatch between host OS and the OS in the container are not
positive.  This will change the default so that the two of them match
as much as possible.
If it's impossible to detect the host OS, then the latest Fedora
version image will be used.
> Podman spawner: default to using image matching the host OS

- avocado/core/loader.py
Two methods of FileLoader are the same as in the superclass,
delete them.
> loader: remove duplicate methods

- selftests/functional/plugin/test_assets.py
- selftests/functional/plugin/test_vmimage.py
- selftests/functional/test_basic.py
- selftests/functional/test_fetch_asset.py
- selftests/functional/test_task_timeout.py
- selftests/unit/plugin/test_legacy_replay.py
- selftests/unit/plugin/test_vmimage.py
- selftests/unit/plugin/test_xunit.py
- selftests/unit/test_datadir.py
- selftests/unit/test_job.py
- selftests/unit/test_loader.py
- selftests/unit/test_nrunner.py
- selftests/unit/test_suite.py
- selftests/unit/test_sysinfo.py
- selftests/unit/test_test.py
- selftests/unit/utils/test_archive.py
- selftests/unit/utils/test_cloudinit.py
- selftests/unit/utils/test_diff_validator.py
- selftests/unit/utils/test_filelock.py
- selftests/unit/utils/test_genio.py
- selftests/unit/utils/test_iso9660.py
- selftests/unit/utils/test_partition.py
- selftests/utils.py
The very long and detailed temporary directory prefix used on `TestCaseTmpDir` was introduced to quickly identify selftests that may not be cleaning up after themselves.
But, it has one negative side effect: some files names such as sockets have length limitations, and the amount of detail makes it very easy to go beyond that limit.
> selftests.utils: reduce length of temporary dirs

- avocado/core/nrunner.py
- avocado/core/status/server.py
- examples/jobs/nrunner_unix_status_server.py
- selftests/jobs/example_nrunner_unix_status_server
nrunner is supposed to also allow UNIX domain sockets to be used as the transport for status messages, but it has never been set to use.
This fixes a few issues, adding a job as a test that actually makes use of it.
> nrunner: properly support UNIX domain sockets

- avocado/core/sysinfo.py
- avocado/utils/sysinfo.py
- selftests/unit/test_sysinfo.py
This commit moves sysinfo collectibles to the avocado utils. It creates
api for collecting sysinfo. This api will be used in sysinfo runner and
sysinfo plugin. This is part of work on sysinfo support for nrunner.
Reference: #3877
> Sysinfo utility

- avocado/core/messages.py
- avocado/core/nrunner.py
- avocado/core/status/repo.py
- avocado/plugins/runner_nrunner.py
- selftests/functional/test_output.py
- selftests/unit/test_status_repo.py
This extends the nrunner Task, so that it can be set and report its rightful job.  This will help to identify erroneous situations where jobs receive information from other jobs tasks.
This can help, for instance, when a job runs another job as a test, or when some other bad actor tries to inject such data.
This is related to https://github.com/avocado-framework/avocado/issues/4308
---
Changes from v1 (#4864):
* Changed help message of `--category` command line option
* `StatusRepo` won't process messages that are destined for other jobs
* `StatusRepo` will log the complete message when destined for another job
> nrunner: bind tasks to their rightful jobs [v2]

- avocado/utils/distro.py
The distro library is now being used on the Podman spawner plugin
command line configuration since ae62ccc6a.
Let's improve its portability to avoid crashes on platforms that do
not have os.uname().
> avocado/utils/distro.py: improve portability on non-UNIX

- .github/workflows/prerelease.yml
- examples/testplans/release/pre.json
This pipeline performs 5 of the 9 steps outlined `examples/testplans/release/pre.json` and helps with a sixth one "Avocado Remote Machine HTML report" - the HTML is created and saved as an artifact that can be downloaded and checked locally.
There is a detail to take into account, the containers by GitHub Actions to run the step "Avocado Test Run on RPM based installation" have modifications to make them smaller, this means it avoids saving files under `/usr/share/doc`, and avocado packaging is installing there the examples. This is why I changed the the test to run `/usr/bin/true` instead of `passtest.py`
Also as result of using a container, there is not a hostname so the HTML job report says 
`Host: 	/bin/sh: line 1: hostname: command not found"`
The three remaining tasks are:
- check …
> CI: add prerelease.yml to executes automatically some of the pre-release steps

- avocado/core/suite.py
The `Runnable` class has to have configuration because this information
are used by Tasks and Runners. When the runnable is created by
`from_config` method, everything works fine, but when the runnable is
created manually the config might be empty. This commit will set
runnables configuration same with the test suite configuration.
Reference: #4846
> Config for every runnable

- selftests/pre_release/tests/vmimage.py.data/variants.yml
After updating the ubuntu versions at 11649747d3ef5834172bf2fe9c525a1927f3a6a1 the pre-release pipeline fails because ubuntu doesn't include i386, see https://github.com/avocado-framework/avocado/actions/runs/1148234681
> variants.yml: remove i386 in ubuntu

- avocado/plugins/runner_nrunner.py
- avocado/plugins/spawners/podman.py
- examples/jobs/nrunner.py
- examples/jobs/nrunner_unix_status_server.py
- selftests/check.py
- selftests/functional/plugin/test_jsonresult.py
- selftests/functional/plugin/test_logs.py
- selftests/functional/test_basic.py
- selftests/functional/test_nrunner.py
- selftests/functional/test_output.py
- selftests/functional/test_task_timeout.py
This introduces a mode under which the status server will set up its own "listen" and "uri" values.
The "listen" value is of course related to where the status server will be listening for status updates, from clients (tasks) which are given the "uri" value.
Instead of a TCP based socket, the auto mode defaults to using a UNIX domain socket created within the job's own directory, which better avoids clashes (no two jobs should be using the same job directory anyway).
---
Changes from v1 (#4879):
* Squashed the original two commits to avoid enable/disable switch of auto mode
* Added support for podman spawner mapping of UNIX domain sockets status server uris
> nrunner: introduce status server auto mode [v2]

- setup.py
* do not use `os.system()` it's being deprecated because security concerns.
* fix bug in command `test --disable-plugin-checks= ...`
> setup.py: replace os.system with subprocess.run and fix bug

- avocado/core/messages.py
This will save every nrunner messages from stdout and stderr to the debug.log with the proper tag on the beginning of each line, and it introduces the debug.log file as Default log file for nrunner.
Reference: #4804
---
Changes form v1 (#4866)
* Docstring fixes
* StderrMessageHandler `_tag` fix
* Separated method for cheking incomplete lines
> Default log file for nrunner based tests [v2]

- avocado/core/runners/sysinfo.py
- examples/nrunner/recipes/runnables/sysinfo.json
- python-avocado.spec
- selftests/unit/test_runner_sysinfo.py
- setup.py
The runner for gathering sysinfo. It supports the command and system
file collectible from the legacy runner and uses the
'sysinfo.collectibles' configuration. It is the part of work on #3877,
but it is just the runner and misses the configuration part in avocado
job.
You can test it by running the recipe in
'examples/nrunner/recipes/runnables/sysinfo.json'
Reference: #3877
---
Changes form v1 (#4760):
*   usage of __all__
*  rename the log to log_path
*    remove the prefix inside the __repr__ methods
*   use hash for comparisons
*   set the timeout to 0 when the sysinfo.collect.commands_timeout is not defined
*   fix of the recipe example
*   fix the empty arguments bug
---
Changes form v2 (#4806): 
* Usage of sysinfo utils form #4842
> Sysinfo nrunner [v3]

- .github/workflows/ci.yml
- .github/workflows/weekly.yml
CI/`ci.yml`: allow to run workflow manually
CI/`weekly.yml:` Duplicate the pipeline and make two different tests:
* one identical to the one run in every PR but with development python
* one without optional_plugin tests, only with "core" avocado.
Export AVOCADO_LOG_DEBUG and AVOCADO_CHECK_LEVEL properly.
> Updates for ci.yml and weekly.yml

- avocado/core/exceptions.py
- avocado/core/job.py
- selftests/unit/test_job.py
The test results uniqueness are guaranteed because of their unique
TestIDs, but the full result location of a test also takes into
account its suite name.
So far, there was no enforcement of unique suite names, allowing
results to be overwritten silently by tests of another suite with the
same name (if their TestIDs also match).
With this change, a very early and explicit exception will be raised,
allowing users of the Job API to fix their suite creation.
---
Changes from v1 (#4892):
* Renamed `_check_test_suite_uniqueness()` to `_check_test_suite_name_uniqueness()`
* Add all duplicate suite names to the exception message
* Fixed unintended whitespace
> Job: enforce suite name uniqueness within the scope of a job [v2]

- .cirrus.yml
- .github/workflows/ci.yml
- avocado/plugins/list.py
- avocado/plugins/run.py
- docs/source/guides/contributor/chapters/plugins.rst
- docs/source/guides/contributor/chapters/runners.rst
- man/avocado.rst
- optional_plugins/html/tests/test_html_result.py
- optional_plugins/varianter_yaml_to_mux/tests/test_functional.py
- selftests/functional/plugin/test_diff.py
- selftests/functional/test_basic.py
- selftests/functional/test_export_variables.py
- selftests/functional/test_fetch_asset.py
- selftests/functional/test_getdata.py
- selftests/functional/test_interrupt.py
- selftests/functional/test_job_timeout.py
- selftests/functional/test_json_variants.py
- selftests/functional/test_legacy_replay_basic.py
- selftests/functional/test_legacy_replay_external_runner.py
- selftests/functional/test_list.py
- selftests/functional/test_loader.py
- selftests/functional/test_nrunner.py
- selftests/functional/test_output.py
- selftests/functional/test_output_check.py
- selftests/functional/test_resolver.py
- selftests/functional/test_statuses.py
- selftests/functional/test_streams.py
- selftests/functional/test_wrapper.py
This switches the default runner from the legacy (AKA "runner") to the new runner (AKA "nrunner"), and the accompanying legacy "loader" to the new "resolver".
A reasonable number of features are kept being tested under the legacy runner, because they are either only applicable to the legacy runner or there are known caveats about nrunner.
Closes: https://github.com/avocado-framework/avocado/issues/4802
---
Changes from v1 (#4905):
* Drop commit that adds `datadir` file transfer via messages
* Changes test `functional/test_output.py:OutputPluginTest.test_gendata` to use the legacy runner due to the previous point
> Switch default runner [v2]

- selftests/functional/test_interrupt.py
nrunners does not support yet this kind of operation because of its
architecture.
> nrunner: fix nrunner test_interrupt processes

- .github/workflows/prerelease.yml
Give different names to each job artifacts so they are all kept without overwritting.
Do not save any artifact for the job check-rpm-available-copr, since this job only install the packages and doesn't create any output.
Update path for the artifacts generated by the job avocado-deployment-copr, this job is running the tests inside a container and the path changes.
An example of this pipeline being forced to fail  (running `/usr/bin/false`  as last step)  can be browsed at:
https://github.com/ana/avocado/actions/runs/1182268924
The artifacts are listed in the bottom of that page.
> prerelease.yml: update artifacts naming

- setup.py
On a system that has setuptools (which is an Avocado dependency, but
not, at this point, an "avocado.core.nrunner" dependency), it's
possible to find runner classes based on setuptools' entrypoints.
This adds all the missing classes' entrypoints.
---
This should fix CI jobs such as the ones in https://github.com/avocado-framework/avocado-vt/pull/3201 .
> nrunner: update all runner classes as entrypoints

- avocado/core/messages.py
The tag `[debug]`, for log messages inside `debug.log` file, might be
confused with logging level `DEBUG` by users. Let's change the tag to
`[stdlog]`.
Reference: #4925
> debug.log tag change

- .github/workflows/ansible.yml
- selftests/deployment/roles/avocado/tasks/pip/plugins.yml
- selftests/deployment/roles/avocado/tasks/rpm/examples.yml
- selftests/deployment/roles/common/tasks/dependencies.yml
- selftests/deployment/roles/common/tasks/repos.yml
- selftests/deployment/roles/tests/tasks/main.yml
This is a v2 of https://github.com/avocado-framework/avocado/pull/4849
Changes:
* enabled all the methods with avocado_vt, so the 6 combinations are run now
* improve the pipeline to use directly the container support provided by GitHub Actions
* Update the list of repositories used, notably for the official method.
* Some minor changes following discussion in the v1
The current pipeline can be browsed at https://github.com/ana/avocado2/runs/3363033419
The job `Ansible (method=official avocado_vt=true)` doesn't work because the packages of avocado-vt haven't been updated yet. I added the missing releases at https://copr.fedorainfracloud.org/coprs/g/avocado/avocado-vt-latest/ and right now it works when `method=copr`, but I don't know if it'll update eventually the module avocado-vt or …
> CI: deployment of Avocado via different methods [v2]

- .github/workflows/ci.yml
- .github/workflows/setup.yml
Now with nrunner as the default runner implementation, resolver and
explicit nrunner options are no longer necessary.
> GH Actions: remove unnecessary nrunner related options

- .github/workflows/ci.yml
Save the logs if the tests fail.
Keep the Python Eggs as artifacts in case we want to test them.
> CI/ci.yml: save more artifacts

- selftests/check.py
If the Python modules that power some of the tested functionality (in
plugins) are not available, let's go ahead and *not* include them
anyway.
This makes the check.py execution more robust on situations where the
plugin can not be installed and won't be available.
---
[This is a CI run](https://cirrus-ci.com/task/5192662081863680) with an empty `optional_plugins` folder, proving the change in this PR.
> selftests/check.py: check for module presence before using it

- selftests/deployment/roles/avocado/tasks/rpm/plugins.yml
- selftests/deployment/roles/tests/tasks/main.yml
Three updates:
* we have different names for the avocado-vt package: python3-avocado-plugins-vt in copr and python3-avocado-vt in "official". Handle this while we it solved.
* The installation via pip was failing with avocado-vt with the error: 
`Avocado job failed: JobError: Could not find runners for runnable(s) of kind(s): dry-run` I applied the same workaround found here with cirrus https://github.com/avocado-framework/avocado-vt/pull/3204
* For some unknown reason (to me), the boot job now is named `io-github-autotest-qemu.boot` instead of `migrate.default.tcp.default`
These changes are working when I test locally but when running in github actions, I get two methods (pip and copr) failing in one of the avocado-vt tests ( boot and migrate execution), see: …
> Ansible deployment updates after switching to nrunner

- avocado/plugins/spawners/podman.py
There's no point in moving further in the task spawning if the podman
binary is not available in the system, so let's check as early as
possible.
> Podman Spawner: check for the presence of podman binary earlier

- avocado/plugins/human.py
- setup.py
With the nrunner especially, the UI can become crowded with "STARTED"
and then the actual test final status.  Let's allow any of the actual
status to be ommited from the UI if the user chooses to.
> Human UI Plugin: allow the configuration of status to be ommited

- python-avocado.spec
- selftests/check.py
- setup.py
Update `--disable-plugin-checks` to allow disabling several plugins with the same option
When running from the selftests/check.py, it needs to be used as:
`      python3 selftests/check.py ... --disable-plugin-checks html robot`
From the setup.py test command as:
`      python3 setup.py test ... --disable-plugin-checks "html robot"`
Fixes: #4904
References: https://github.com/avocado-framework/avocado/issues/4904
A second commit to force always using the default (n)runner.
> check.py/setup.py: fix --disable-plugin-checks

- avocado/plugins/human.py
I'm hoping we still can fix this configuration option since it has never been released.
This was caught by a weekly run of codespell I'm running in my fork.
> typo fix: ommit -> omit

- avocado/utils/network/hosts.py
Hosts utils ensures that we quit the session object upon exit
Signed-off-by: Cris Forno <fornosoccer12@gmail.com>
> [utils] Hosts: quit remote_session when RemoteHost exits

- examples/jobs/custom_exec_test.py
This adds an example of a custom exec-test using the Job API. The main objective is to document how args and kwargs are used.
> examples/jobs: add an example for a custom exec-test

- avocado/utils/asset.py
Sometimes the URI that identifies an asset will contain a query, as
it's commonly the case in file server that have an HTTP interface.
Instead of using the path as the name of the file, which will be the
same most of the time, let's use the parameters as the differentiating
factor.  Using the example on RFC3986:
```
foo://example.com:8042/over/there?name=ferret#nose
\_/   \______________/\_________/ \_________/ \__/
|           |            |            |        |
scheme     authority       path        query   fragment
|   _____________________|__
/ \ /                        \
urn:example:animal:ferret:nose
```
If a query component exists, the base location in the Avocado cache
will be based on the components up to "path", and the asset name the
query itself.
Fixes: …
> Asset: support query parameters in an URI

- examples/jobs/passjob_with_test.py
The config needs to be loaded with 'from_config' method of the Job.
> [examples/job] fix examples/jobs/passjob_with_test.py

- selftests/pre_release/tests/vmimage.py.data/variants.yml
Update Debian versions and cirros to only use latest release 0.5.2 and 0.4.0
Tested at https://github.com/ana/avocado/runs/3733800797
> Update vmimage tests

- avocado/core/job.py
- selftests/check_tmp_dirs
- selftests/functional/test_job_api_features.py
- selftests/functional/test_nrunner.py
- selftests/functional/test_output.py
- selftests/functional/test_task_timeout.py
- selftests/run
- selftests/unit/plugin/test_jsonresult.py
- selftests/unit/plugin/test_xunit.py
- selftests/unit/test_job.py
- selftests/unit/test_suite.py
Hi, this is a work on top of cleber's PR. And basically is fixing #4392.
@clebergnu I decided to not deprecate core/data_dir.py:get_tmp_dir()
because I saw a few calls for it on avocado-vt side. We need to decide
if the cleanup part will be delegated the same way we do with job
(enter/exit). So this could be another PR/discussion.
- removed one commit content with non-intentional removal;
- fixed typo on commit message
- removing the keep_tmp workarounds
> Fixes tmpdirs leftovers (v2)

- docs/source/guides/writer/chapters/writing.rst
- examples/tests/cancel_test.py
This is just update for first two chapters of Test Writer’s Guide, the
Writing a Simple Test and the Writing Avocado Tests with Python
Reference: #4982
> [docs] update Writing Avocado Tests with Python for the 92.0 LTS

- avocado/core/safeloader/core.py
- examples/tests/property.py
- selftests/functional/test_resolver.py
Avocado can not currently run properties as tests, so it does not make
sense to present those as valid test methods.
Althought this change makes sense in itself, it is also related to the
existence of the "teststmpdir" property in the "avocado.Test" class,
and the fact that it should not be visible as a test method.
In the future, support for using properties as tests may be added,
along with the removal of "teststmpdir" as stated in eb5190962.
> Safeloader: filter out properties from test methods results

- avocado/core/jobdata.py
- avocado/plugins/replay.py
This is and fix for storing job configuration values into the record. This bug was causing problems with replay command reported in #5060. This PR reserve a dict with key `__set__` as a flag for `set` type inside job configuration record. With this change the `sets` can be saved and restored from job configuration records, which wasn't possible before.
> Avocado replay command configuration fix

- avocado/core/__init__.py
- avocado/core/runners/avocado_instrumented.py
- avocado/core/suite.py
- avocado/plugins/run.py
- selftests/check.py
- selftests/unit/test_job.py
There are a number of places, which are triggered when using the API, that still defaults to the legacy runner.
This fixes that by always registering `run.test_runner`, and fixing the tests that wouldn't work properly under nrunner.
Fixes: https://github.com/avocado-framework/avocado/issues/5067
---
Changes from v1 (#5084):
* Have `run.test_runner` always registered, and thus, no need for hard coded defaults
> Nrunner: fix missing default when using the API [v2]

- avocado/core/job.py
- avocado/core/runners/utils/messages.py
- docs/source/guides/writer/chapters/logging.rst
- selftests/functional/test_basic.py
The `--store-logging-stream` option wasn't available for the nrunner.
This PR is fixing this. The change from the legacy solution is that
the streams are not saved inside the job results directory, but they are
split by the tests inside test-result directory. So each test has its
own files with the user stream logs.
Reference: #5081
> `--store-logging-stream` fix for the nrunner

- avocado/core/messages.py
- avocado/core/runners/utils/messages.py
- docs/source/guides/writer/chapters/logging.rst
- selftests/functional/test_basic.py
This adds the ability for the runners to print user-specific logging
streams to the console when the `--show` command is used.
Reference: #5014
> Option `--show` fix 

- .cirrus.yml
- avocado/core/nrunner.py
As described in https://github.com/avocado-framework/avocado/issues/5088 , Avocado can not currently run nrunner based jobs from eggs, because it fails to find the individual runners.
This fixes https://github.com/avocado-framework/avocado/issues/5088.
> Avocado jobs: allow nrunner jobs from eggs

- selftests/functional/plugin/test_jsonresult.py
- selftests/functional/plugin/test_logs.py
- selftests/functional/test_requirements.py
There is no need for those, since nrunner is the default one.
> remove nrunner references when using command line

- examples/tests/custom_env_variable.sh
- examples/tests/custom_env_variable.sh.data/variants.yaml
- examples/tests/params.py
- optional_plugins/varianter_yaml_to_mux/tests/test_functional.py
This finalizes the transition for the Yaml to Mux tests from the legacy runner to nrunner.
> Varianter yaml to mux: move last legacy runner tests to nrunner

- avocado/core/suite.py
- avocado/plugins/runner_nrunner.py
- examples/jobs/passjob_custom.py
By default all suites are enabled, but if we would like to skip any,
just set suite.enabled = False and this suite will not be executed.
Fixes #4832
> suites: introduce the enabled concept

- avocado/core/job.py
The avocado Job was still configuring it's logging with root logger.
This commit will make `avocado` namespace as a root logger for avocado
Job. Also it will rename the `root_logger` variable to `main_logger`.
This is a backport from @richtja's patch.
Reference: #5049
> Job logging with `avocado` namespace

- .github/workflows/weekly.yml
- selftests/pre_release/tests/vmimage.py.data/variants.yml
* `weekly.yml`: use current development Python 3.11
* Update vmimage tests
* Add Fedora 35 and Ubuntu 21.10
* Update Debian image versions
> Update vmimage tests and bump development Python version to 3.11

- selftests/check.py
Make sure all the suites are available to be inspected and
move handling of --list-features to the beginning of the function,
no need to go further if the user only wants the list of features.
Fixes: https://github.com/avocado-framework/avocado/issues/5070
> check.py: fix --list-features

- .github/workflows/ci.yml
- Makefile.gh
Re-implementation of https://github.com/avocado-framework/avocado/pull/4918
Add a couple of experimental checks:
* codespell to complement pycheck's spellchecker
* bandit to find common security issues in Python code
Both will output the problems found without any action.
The actions are run intentionally from a new makefile `Makefile.gh` instead of using pre-made GitHub Actions.
This allows reproducing the checks locally.
> ci.yml: Add experimental checks + Makefile.gh [v2]

- avocado/utils/asset.py
This is part of bigger effort to better organize our log messages. Also
a proper alternative to #5119. More to come here, but I just would like
to test if this will fix the issue reported there.
> utils.asset: use __name__ as logger namespace

- avocado/utils/pci.py
Reading a file content of a file was added with new line character,
using the same output in next line without stripping is failing
to get the desire output. So added the strip() and the issue is
fixed and getting desired output without any issue.
> Stripping the new line character for an output value in pci.py

- python-avocado.spec
This should be a temporary measure, because of a very broken release
of resultsdb-api (2.1.4).  There's a fix in progress, but it will take
some time to land a new package on rawhide.
Reference: https://pagure.io/taskotron/resultsdb_api/pull-request/12
> RPM: do not build resultsdb plugin on Fedora 36 (rawhide) or later

- avocado/utils/vmimage.py
- selftests/pre_release/jobs/pre_release.py
- selftests/pre_release/tests/vmimage.py.data/variants.yml
- selftests/unit/utils/test_vmimage.py
* `pre_release.py`: run download tests serially
Download jobs must be run serially to avoid time-outs from mirrors limiting the download rate.
Fixes: https://github.com/avocado-framework/avocado/issues/5110
* `utils.vmimage`: another ubuntu version fix
This is a follow-up for ccf873fb89bbbf320e2a8cc26fe3d433b4d13f27
get_versions() shouldn't have been removed but rather updated to handle also the case we provide an ubuntu version.
* `utils.vmimage`: fix default version for openSUSE
Switch to use openstack images from OpenSUSE JeOS, the other images has been discontinued after 15.2.
Update `variants.yml` to only fetch openSUSE 15.2 and 15.3. Remove OpenSUSE 15.1 that was EOLed earlier this year.
Test only for x86_64, because there are only JeOS images for this arch.
Fixes: …
> utils.vmimage issues

- avocado/core/messages.py
- avocado/core/nrunner.py
- avocado/core/runners/avocado_instrumented.py
- avocado/plugins/runner_nrunner.py
After the 050bc33 the suite will raise an error when the variants and test parameters are used together. With this in mind, there is no difference between one variant and test parameters from the task perspective. Let's add test parameters to test tasks as a variant. In the future, we can discuss if the `variant` is the right variable name in tasks for holding data about parameters.
This change will fix the issue with representation of parameters in result plugins.
Reference: #4990
> Convert test parameters to variants in tasks

- .github/workflows/release.yml
- Makefile
- Makefile.gh
- examples/testplans/release/release.json
This is a v3 of  https://github.com/avocado-framework/avocado/pull/4961
It uses a makefile for the actions (when it makes sense) to allow reproducing things locally. 
I have to say I find the action is hard to read now.
----
Add a new GitHub Action that will help with the release.
This Action will:
- update all the VERSION files and the spec file
- update and build the new version at readthedocs.org
- build and update the packages (tar.gz and wheel) at pypi.org
- build and publish for ach python version the egg packages  in GitHub Fix:#4692
For making some of this actions, it's required to set up four tokens in github:
`RELEASE_TOKEN` to allow update the repository avocado-framework/avocado
`RTD_TOKEN` to update readthedocs
`PYPI_USER` and `PYPI_PASSWD` to allow twine update pypi.org …
> Add github action for the release test plan [v3] 

- python-avocado.spec
My workflow is to bump the release number, and ask emacs to create a
new changelog entry.  With that, I did not notice the duplicate entry
that existed for release -2.
This bumps it again, making it -3, and thus not duplicate.
> RPM spec file: fix a duplicate release changelog entry

- .github/workflows/release.yml
- Makefile.gh
This is a follow up of https://github.com/avocado-framework/avocado/pull/5127 with some updates after testing.
`release.yml`: use jobs.env for setting up variables
This makes the pipeline easier to read.
Rename TOKEN to TOKEN_RTD to make it clearer this token is for readthedocs.org
A couple of minor fixes:
- use python 3.10.0 because github action don't recognise 3.10
- use `${{github.workspace}}` variable instead of hardcode a path
`release.yml`: move readthedocs step to run later
readthedocs needs a couple of seconds to refresh it copy of the git repository. If we try to update readthedocs immediately after tagging the new release, it'll fail.
This pipeline can be seen in action at https://github.com/ana/avocado-test/runs/4211607135?check_suite_focus=true
After a commit adding "fake" …
> release.yml: updates for setting up variables and move readthedocs step

- .github/workflows/ci.yml
Export variables only once for the full job.
Only run once in latest Python 3.10.0
Split steps to debug faster possible problems: installation, pre script, script and post script.
> ci.yml: improve codecoverage job

- .cirrus.yml
- .github/workflows/weekly.yml
- python-avocado.spec
- selftests/check.py
- setup.py
This is a implementation of https://github.com/avocado-framework/avocado/pull/4954
With --select and --skip we have a bigger flexibility choosing the tests we want to run.
By default, with no argument, it'll run all tests
python3 selftests/check.py
To run all the test except a given one, we can use `--skip`
python3 selftests/check.py --skip static-checks
To run only one or several selected tests, use `--select`
python3 selftests/check.py --select static-checks,unit
If we also want to avoid running the tests of one of the plugins:
python3 selftests/check.py --skip nrunner-interface,static-check \
--disable-plugin-checks golang,robot
Add also a hidden argument `--dict-tests` that stores a dict with the list of tests provided by `--select` and `--skip`.
`setup.py` has been updated …
> selftests/check.py: Implement --select / --skip arguments (v2 reimplementation)

- .github/workflows/ci.yml
Save some build time!
Fixes: https://github.com/avocado-framework/avocado/issues/4919
> ci.yml: run static-checks only once

- avocado/core/nrunner.py
- docs/source/guides/writer/chapters/writing.rst
This adds support to the AVOCADO_VERSION and AVOCADO_TEST_WORKDIR to the
EXEC test on nrunner.
Other variables, like AVOCADO_TEST_BASEDIR, AVOCADO_TEST_LOGDIR and
AVOCADO_TEST_LOGFILE may not make sense as they would hold the
information where the avocado command started and not the environment
where the test is currently running.
Changes from v4:
- Fix documentation
- Add a cleanup method
> [nrunner] add access for EXEC test to some AVOCADO_* env variables [v5]

- avocado/core/teststatus.py
When checking if a test status is "good" or "not good", it's better to
refer to a canonical source for truth.  That currently exists as the
`STATUS_MAPPING` dictionary, but it's not straightforward to use.
Let's add a list of both "OK" and "NOT OK" statuses to make its usage
simpler.
> avocado/core/teststatus.py: add a handy list of OK and NOT OK status

- examples/plugins/cli-cmd/hello/setup.py
Revert hello/setup.py in commit 66514efe50cadea8b6d4e35539110920e825cb8e
Signed-off-by: Linggang Zeng <linggang.zeng@easystack.cn>
> typo fix: hello_option -> hello for hello/setup.py

- docs/source/guides/writer/libs/vmimage.rst
vmimage.get() has been deprecated in favour of
vmimage.Image.from_parameters()
Fixes: https://github.com/avocado-framework/avocado/issues/5160
> docs/guides/writer: update vmimage

- avocado/utils/pci.py
the dir /sys/class/net/ has regular file, (bonding_masters)
which is failing in os.readlink() function check.
so changed the condition check and now able to get the
interface names without any issue.
> Omitting the regular file check while retriving the interface in pci.py

- avocado/core/job.py
- avocado/core/runners/utils/messages.py
For end-users, module name + line number is not an useful information.
Also, recent changes are using custom namespaces to better organize the
loggers. This patch it was postponed for post-lts and now is time to use
this new format.
Related to #5099.
> log: use namespace instead of module

- Makefile
- setup.py
This PR should address the last remaining changes for EPIC https://github.com/avocado-framework/avocado/issues/4372
* `Makefile`: remove obsolete targets
Remove leftover targets source-pypi and python_build
source-pypi is not longer needed since the tarballs are created by the target build-wheel (in Makefile.gh)
Without source-pypi and build-wheel, target python_build  can be also removed.
* `setup.py`: do not remove RPM related directories
These directories were created by targets and command that are   not longer run by Makefile or setup.py
> Wrapping up Makefile/setup.py updates

- avocado/core/__init__.py
- avocado/core/nrunner.py
- avocado/plugins/runner_nrunner.py
- docs/source/guides/user/chapters/advanced.rst
- selftests/unit/test_nrunner.py
With this experimental change, we are enabling users to set custom
identifiers for the runnables/tests. By default we are still using {uri}
as identifier but any custom f-string using uri, args and/or kwargs can
be used. For now we have a global settings for all runners, since we
have the ability to create custom suites. However future improvements
can be added here.
Fixes #4980.
* Added unit test;
* Added a doc section;
* Fixed setting variable name;
> runnable: introduce custom format f-strings (v2)

- selftests/check.py
resolver.references must be initialized for optional-plugins otherwise they can't be run.
This fixes a problem when running: `python selftests/check.py --select optional-plugins`
> check.py: missing initialization for optional-plugins

- avocado/utils/process.py
- selftests/functional/test_output.py
- selftests/functional/test_output_check.py
This PR adds a new attribute log to the utils.process.run
method. This will help users to set their own loggers for running
processes with utils.process.
Reference: #5099
---
Changes from v1 (#5131):
* rename `log` to `logger`
* update of the output tests to correspond the new behavior
* skip of the `output-check` tests
> Custom logger for `utils.process.run` [v2]

- avocado/utils/vmimage.py
- selftests/pre_release/tests/vmimage.py.data/variants.yml
- selftests/unit/utils/test_vmimage.py
The Debian project is moving the cloud images to cloud.debian.org
and has now generic images for environment using cloud-init, such
as OpenStack.
Update variants.yml accordingly using codenames.
Remove Debian 9 (stretch) and include instead Debian 11 (bullseye).
Update selftests/unit/utils/test_vmimage.py with the cloud.debian.org
HTML page and corresponding codename checks.
Fixes: https://github.com/avocado-framework/avocado/issues/5029
Note this will need rebasing if https://github.com/avocado-framework/avocado/pull/5032 is accepted.
> utils/vmimage: use cloud.debian.org for Debian

- avocado/core/job.py
Currently we are using 'avocado' namespace and not touching on the
'root' logger. So this is not needed anymore.
> core.job: remove legacy root logger

- optional_plugins/html/tests/test_html_result.py
The arm64 jobs run on such an environment that contains a
"minimalistic" /proc/cmdline, with content such as:
BOOT_IMAGE=/boot/vmlinuz-5.11.0-40-generic
While other systems /proc/cmdline will have both "BOOT_IMAGE" and
arguments such as "root=", let's use the one available "everywhere".
> Travis CI: work around arm64 /proc/cmdline content

- avocado/utils/debug.py
- avocado/utils/download.py
- avocado/utils/stacktrace.py
Those are remaining calls to root logger and some small fixes with the
namespaces. Fixes #4997.
> utils: avoid using root logger

- avocado/core/output.py
Currently we are using 'avocado' namespace and not touching on the
'root' logger. Unfortunately, we still had some occurrences of the root
logger in `core.output`, this is fixing that.
Reference: #5166
> core.output: remove legacy root logger

- avocado/plugins/spawners/podman.py
- avocado/utils/podman.py
This commit is changing the Avocado deployment model for this
"DeploymentSpawner" (Podman). Currently only nrunner is being deployed
to the isolated environment. With this patch, we are downloading (and
caching) two eggs: avocado and setuptools. Those eggs are then copied to
the container before starting it with a new entry point.
This is part of our new strategy to have a better Avocado support inside
the container when running tests in isolated environments.
Fixes #4933
> spawners.podman: adapt podman spawner to use eggs

- .cirrus.yml
- contrib/containers/ci/selftests/fedora-33.docker
- contrib/containers/ci/selftests/fedora-35.docker
- selftests/functional/test_lv_utils.py
Remove Fedora 33 that reached EOL on 2021-11-30 and add Fedora 35.
Update fedora_selftests_task to use Fedora 35 prebuilt container image, add the dockerfile for this image.
Minor update on `selftests/functional/test_lv_utils.py`  add check for binary modprobe. Skip the test if modprobe is not present in the system and show an useful error message.
> .cirrus.yml: Update Fedora versions (remove 33, add 35)

- selftests/pre_release/jobs/pre_release.py
Let's add the output of the failed tests to the pre-release checks for
easier understanding, which tests have failed.
> pre-release checks failed tests summary

- selftests/check.py
`job.output.testlogs.logfiles` and `core.show` already have default
values, so we don't need to set them.
> Remove the default values from `check.py`

- Makefile
- Makefile.gh
- Makefile.include
- Makefile.pkg
- avocado/core/__init__.py
- python-avocado.spec
The "rpm" target depends on VERSION, which depends on PYTHON, with the later not being defined in the Makefile.pkg file.
Instead of repeating definitions, let's put those common definitions in a single include file.
This also includes other misc fixes (one related to the RPM package).
> Makefile: fix "make -f Makefile.pkg rpm"

- avocado/core/nrunner.py
- avocado/core/plugin_interfaces.py
- avocado/core/runners/avocado_instrumented.py
- avocado/core/spawners/common.py
- avocado/core/test.py
- avocado/plugins/runner_nrunner.py
- avocado/plugins/spawners/podman.py
- avocado/plugins/spawners/process.py
- selftests/functional/plugin/spawners/test_process.py
- selftests/unit/test_test.py
Right now, the test output directory is managed by runners, and it is separated from the job/test-results folder. Most of the runners are using the temporary directory for test output, and this information might be lost. Only possible way how to store this information to the avocado results is use the avocado messages or use the avocado jobs get-output-files script. For some spawners like ProcessSpawner this is an unnecessarily complicated process, because we have to save the same data twice even the tests are run in the same environment as avocado.
This PR will make spawners smart enough to set the output directory for runners, so for the avocado will be easier to manage those files. For example, the ProcessSpawner will set output dir to the job/test-reulst so there is no need for …
> Spawners output_dir [v2]

- selftests/check.py
Dry-run should also be checked during for its interface compliance.
Reference: https://github.com/avocado-framework/avocado/issues/4058
> nrunner: add dry-run to interface check

- setup.py
The `setup.py test` was always returning exit code 0, because the exit
code from `check.py` wasn't respected. This will fix that, by exiting
`setup.py test` with code from `check.py`.
Reference: #5208
> setup.py test exit code fix

- .cirrus.yml
This is a shorter version of https://github.com/avocado-framework/avocado/pull/5186 only including the cirrus updates.
Remove ubuntu 18.04 and add latest release 21.10 instead.
Add upcoming RHEL9 beta.
> .cirrus.yml: update Ubuntu and RHEL versions

- avocado/core/dispatcher.py
- avocado/core/spawners/common.py
- avocado/plugins/runner_nrunner.py
In b8d7ebaf9b4ff757fb6ab12b8f128d244cfb12d2 the test-results directory
was introduced inside spawners. With this change, there might occur a
situation when this variable wasn't set, which caused `NoneType` error.
This commit is adding the default value to avoid this problem.
> Job test-results directory for spawners default value

- examples/testplans/release/pre.json
In #4859 most of our pre-release test plan was moved to the GitHub
Actions, but we  decided to not save artifacts when the tests passed.
This is an update of  pre-release test plan to correspond to the current
behavior of GitHub Actions pipelines.
> Pre-release test plan update

- avocado/utils/distro.py
Fixed an issue where "/etc/uniontech-release" was not generic.
There are multiple distributions of UOS, and there are multiple
branches. "/etc/uniontech-release" is not universal, so it needs
to be changed.
Signed-off-by: shilei <shileib@uniontech.com>
> update the CHECK_FILE

- avocado/core/task/runtime.py
- avocado/plugins/runner_nrunner.py
This will make `RuntimeTask` comparable. It is used for removal of
requirement duplicates from runtime_tasks list. This is part of
preparations for dependency graph from BP004.
Reference: #5202
> Removal of duplicates between requirements

- docs/source/guides/contributor/chapters/how.rst
This is a collection of small improvements to the contributor guide with two objectives:
1) To improve itself for new Avocado contributors
2) To be usable and referenced by other Avocado projects such as Avocado-VT (which currently point to autotest contribution guides).
> Docs: improve contributor guide

- avocado/plugins/spawners/podman.py
- avocado/utils/podman.py
After 7f17ff58502af4e011f22217d5a8ce4f533718bc, a new volume it was
added, however Podman doesn't accept relative paths.
Fixes #5209.
> fixes podman container creation

- avocado/plugins/jsonresult.py
- avocado/plugins/xunit.py
According to our documentation, 'name' should be only the 'name' portion
of the test, without the prefix identifier. Besides being consistent
with out documentation, this will help third-party tools and future
plugins to detect flaky tests when the same test is executed in a
different suite. Related to #5116.
> fixes test.id vs test.name on jsonresult and xunit plugins

- avocado/core/runners/avocado_instrumented.py
- docs/source/guides/writer/chapters/integrating.rst
nrunner spawn sub-processes to run tests which is not good for Coverage
usage. Currently coverage is not working on nrunner. With this patch, we
bring it back. We detect if we are in coverage mode and using the
Coverage API we start, stop and save the measurements if running in
Coverage mode.
Fixes #4765.
> instrumented_tests: add support to Coverage

- avocado/core/suite.py
- avocado/core/task/runtime.py
- avocado/plugins/runner_nrunner.py
- selftests/functional/test_output.py
- selftests/unit/test_task_runtime.py
This PR introduces the dependency graph from BP004. It connects
RuntimeTasks by its dependencies and sorts them by topological order in
the DependencyGraph. The avocado functionality stays the same, but this
topology will make it easier to implement features from BP004 like pre,
post test tasks.
Reference: #5203
> Dependency graph [BP004]  [v2]

- avocado/core/tags.py
- docs/source/guides/user/chapters/tags.rst
- selftests/unit/test_tags.py
The Avocado test tags can be "flat", or they can contain values.
So far, it's possible to filter tests that do have and do not have "flat" tags.  This expands that by allowing filtering of tests whose tags do not have a specific value.
This is based on the discussion happening over at: https://lists.gnu.org/archive/html/qemu-devel/2022-01/msg05193.html
> Tags: allow to exclude tests with a given tag value

- docs/source/releases/94_0.rst
The reference to the utils module is broken because the Sphinx module
tag is missing a leading colon.
> docs/source/releases/94_0.rst: trivial fix for module reference

- selftests/check.py
- selftests/functional/serial/test_requirements.py
The b42f35c7aed488c191f16cb57b2bfc20de410788 is solving the problems of
requirements tests from  #4620, so we can enable them. The only issue is
those are functional tests which can't be run in parallel because the
multiple executions of avocado with requirement runner is  breaking
avocado-software-manager. This commit solves this problem by running
them in serial. It splits the functional selftests into serial and
parallel and runs them in separated suite.
Reference: #4620
> Functional test for requirements resolver

- .packit.yml
Add centos stream 8 and 9 to packit.
References: https://github.com/avocado-framework/avocado/issues/5261
> packit: add centos stream 8 & 9

- contrib/scripts/avocado-get-job-results-dir.py
- contrib/scripts/summarize-job-failures.py
- contrib/scripts/task-state-machine.py
- contrib/scripts/vmimage-populate-cache.py
- examples/plugins/job-pre-post/mail/avocado_job_mail.py
- examples/plugins/job-pre-post/mail/setup.py
- examples/plugins/job-pre-post/sleep/setup.py
- examples/plugins/tests/magic/avocado_magic/resolver.py
- examples/plugins/tests/magic/setup.py
- examples/tests/assets.py
- examples/tests/cabort.py
- examples/tests/datadir.py
- examples/tests/gdbtest.py
- examples/tests/linuxbuild.py
- examples/tests/modify_variable.py
- examples/tests/multiplextest.py
- examples/tests/raise.py
- examples/tests/sleeptenmin.py
- examples/tests/synctest.py
- examples/tests/test_env.py
- examples/tests/vm-cleanup.py
I made a semi-automatic update to f-strings to all the files under `contrib` and `examples`
References: https://github.com/avocado-framework/avocado/issues/5219
> contrib,examples: switch to Python f-strings

- .packit.yml
Add srpm_build_deps key to the Packit configuration to specify the needed dependencies for SRPM build
and indicate to build SRPM in Copr.
If you are interested in the transition to building SRPMs in Copr, you can read more about it [here](https://packit.dev/posts/copr-srpms/).
> Packit: build SRPMs in Copr

- optional_plugins/resultsdb/setup.py
Bump versioned requires on resultsdb directly to 2.1.5
Version 2.1.4 was broken and made some API changes that
are now reverted.
Fixes: https://github.com/avocado-framework/avocado/issues/5117
> optional_plugins/resultsdb: update requires resultsdb

- avocado/utils/lv_utils.py
current code is failing to remove the lv with just vg/lv name format.
So changed the lv path to its obsolute path like /dev/vg/lv format,
and it worked fine.
> fixing lv_remove() fails by using obsolute path of lv

- avocado/plugins/testlogs.py
This will improve the readability when running multiple tests inside a
CI job without the need to run a second command or grep to find failed
tests. This is related to: #5200
> display failed tests at the end of a run

- avocado/utils/cloudinit.py
Currently, we can only start the PhoneServer and wait for a phone call in a single call/method. This small change it will allow clients of this library to first start the server and wait for a phone call in a future call.
It came from this discussion[1] and probably QEMU it will not use this change anytime soon, because of dependency policies but in any case it is valid the change for other users. 
[1] - https://www.mail-archive.com/qemu-devel@nongnu.org/msg871809.html
> utils.cloudinit: small refactoring allowing split the workflow

- selftests/check.py
After the 1bc8f7866967125e4a91dbca71dc4198532ab4e7 the failed tests
summary is not needed in selftest anymore, and it also creates
duplicates in output. Let's remove it.
> Selftests summary of failed tests removal

- selftests/lint.sh
`selftests/lint.sh` contains 3 different checks, if the first
one fails, the other are not run. This can lead to confusion
and to hide issues until the issues in the first command
are fixed.
With this change, all the pylint checks are run and the scripts
will fail if one of them failed.
> lint.sh: always run all checks

- .github/workflows/ansible.yml
- .github/workflows/prerelease.yml
GitHub has stopped supporting unencrypted Git protocol.
More info at https://github.blog/2021-09-01-improving-git-protocol-security-github/
This was breaking the ansible deployment and pre-release github actions.
> do not use unencrypted git protocol

- avocado/core/runners/utils/messages.py
- docs/source/guides/writer/chapters/logging.rst
This will enable non-avocado logging streams in `debug.log` by usage of
`–store-logging-stream` option.
Reference: #5290
> –store-logging-stream for non-avocado loggers fix

- selftests/functional/plugin/spawners/test_process.py
This space is required to separate the arguments.
> selftests: fix missing space

- avocado/core/job.py
Because we started removing legacy code and legacy tests. We can't
guarantee the stability of legacy runner on the master branch, but the
`--test-runner=runner`  option wasn't removed yet and the users still
can use legacy runner. Let's add a warning message that using legacy
runner on the newest avocado might be problematic and soon will be
removed.
> Legacy runner warning

- avocado/core/suite.py
When you have the same config option in suite config and the job config,
the job config will be used, but it should be the suite option because
it is lower level configuration. This will fix that.
Reference: #5305
> job config rewrites the suite config in job API

- avocado/core/settings.py
- avocado/core/test.py
- avocado/plugins/run.py
- avocado/plugins/sysinfo.py
I came across some current inconsistencies with sysinfo that I believe can confuse users (and also blocked some work of mine).
This is a proposal to remove the per-test feature for now, given it's not working consistently, until the alternative implementation is brought back.
This is part of https://github.com/avocado-framework/avocado/issues/3877.
> Sysinfo: per-test not working consistenly

- docs/source/guides/user/chapters/logging.rst
After the 496a984e7791db91407992f06ad2012ba7f378ed the
`--store-logging-stream` option stores logging per test. This commit
updates documentation about such behavior.
> Remove the outdated documentation

- avocado/utils/cpu.py
In present implementention for CPU online and offline function in utils/cpu.py file below cases are present,
**online function implementation:**
**Case-1:** In case the CPU is already online, it will return 1 if it is.
**Case-2:** Upon checking CPU status if the CPU is offline, we write 1 into the "online" file. Then, after writing into the "online" file, we check if the CPU is online and if it is, we return 0.
Logically when the CPU is online it should return 1
-> Above two different cases we are returning 1 & 0 when our CPU is online
**offline function implementation:**
**Case-1:** Checking whether the CPU is online or not, if the CPU is offline, 0 is returned.
**Case-2:** If the CPU is online, it will write 0 into the "online" file, and check the CPU status - if it is still online, it …
> Need Rework for CPU online function in utils/cpu.py file

- avocado/core/loader.py
- avocado/core/status/repo.py
- avocado/core/test.py
- avocado/plugins/runners/exec_test.py
- docs/source/guides/contributor/chapters/runners.rst
- docs/source/guides/writer/chapters/writing.rst
- selftests/functional/test_basic.py
- selftests/functional/test_job_timeout.py
- selftests/unit/test_loader.py
- selftests/unit/test_test.py
This completely removes the SIMPLE test support for the legacy runner, along with some other legacy runner related code.
---
Changes from v1 (#5341):
* Dropped commit [selftests/functional/test_basic.py: split RunnerExecTestStatus](https://github.com/avocado-framework/avocado/pull/5341/commits/69c04e97ed067527aa35f50c89d2bd262520954d) as the tests get removed in a later commit.
* Included "fail reason" for tests returning unsupported status, matching the legacy behavior
> Drop SIMPLE test and other legacy code [v2]

- avocado/core/task/statemachine.py
- selftests/functional/test_basic.py
This PR will add `failfast` option for any "NOT OK" status. Until
now, the `failfast` was working only for `fail` status. This change adds
the same ability to `error` and `interrupted` statuses as well.
Reference: #5357
> failfast for any "NOT OK" status

- avocado/core/jobdata.py
When the suite name contains a slash, the avocado crashes because the
`jobdata` module will try to save information to a folder with path
created from the suite name, which doesn't exist. This commit will use
`astring.string_to_safe_path()` for the jobdata folder path, which fixes
the issue.
Reference: #5365
> suite name contains slash fix

- .github/workflows/weekly.yml
- avocado/core/status/repo.py
- avocado/core/tree.py
- avocado/utils/git.py
- avocado/utils/lv_utils.py
- avocado/utils/memory.py
- docs/source/guides/user/chapters/tags.rst
A set of small changes I had in the pipeline:
* switch some more strings to f-strings
I override some strings because I needed some testing before migrating them. Switch them now and remove the pylint override on C0209
* `weekly.yml`: update development Python version to alpha.7
* typo fixes found by codespell
> typo fixes, update experimental python and some more f-strings

- .github/workflows/ci.yml
- selftests/run
- selftests/utils.py
This fixes a condition where the test suite used during `selftests/run` and `selftests/run_coverage` miss some of the optional plugins.
> selftests/run: failfast and plugins fix

- .copr/Makefile
The creation of SRPM in COPR is currently failing, giving errors
such as:
make -f /mnt/workdir-ipj4venx/avocado/.copr/Makefile srpm
outdir="/mnt/safe-resultdir-unosjbwi"
spec="/mnt/workdir-ipj4venx/avocado"']
cwd: /var/lib/copr-rpmbuild/workspace/workdir-ipj4venx/avocado
rc: 2
stdout: fatal: unsafe repository ('/mnt/workdir-ipj4venx/avocado'
is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /mnt/workdir-ipj4venx/avocado
fatal: unsafe repository ('/mnt/workdir-ipj4venx/avocado' is
owned by someone else)
Let's work around this limitation and more recent git behavior and set
the safe mode on the repo directory manually.
> COPR SRPM build: set git repo directory as safe

- avocado/utils/network/interfaces.py
This method is used to check packet loss that occurs during ping to peer address.
Function returns True for 0% packet loss and False if packet loss occurs.
Signed-off-by: Tasmiya Nalatwad <tasmiya@linux.vnet.ibm.com>
> Function to Check packet loss during ping execution

- avocado/core/status/repo.py
- avocado/plugins/runner_nrunner.py
- selftests/unit/test_status_repo.py
The status repo was discarding messages when the message timestamp was
lower than the latest save message. This change removes timestamp
checking and ensures the status changes only in expected life-cycle of a
test: started->running->finished. This means that change from running to
finished is possible, but from finished to running is not.
This change also stores every message into the `status_journal_summary`
list and sorts them by the timestamp. This sort is not optimal because,
the `runner_nrunner` plugin reads data from the status journal during
runner to server communication. This means that status repo sorts
messages which haven't been read yet by `runner_nrunner` plugin, but
can't ensure the order of the whole communication.
Reference: #5327
Signed-off-by: Jan Richter …
> Discarding older messages from status repo fix

- .packit.yml
The default mock/koji/etc behavior is to *not* have network enabled.
This allows common errors to be caught, such as dependencies being
resolved by means other than BuildRequires (such as an implicit
install of a Python dependency listed in setup.py).
Now Packit has this configuration available, so let's use it.
Reference: https://github.com/packit/packit/pull/1504
> Packit: disable network during builds

- selftests/functional/test_interrupt.py
- selftests/functional/test_lv_utils.py
- selftests/functional/test_nrunner_interface.py
- selftests/unit/utils/test_iso9660.py
This is an attempt to allow for a more Pythonic development workflow,
allowing Avocado selftests to run on a simpler environment than it's
currently required.
Basically, if one has a system with both Python and setuptools,
(core) Avocado should be able to run.  Conversely, I believe if the
same system has the Avocado source code, after a "python setup.py
develop" of sorts, the selftests should be able to run.
To accomplish this, it's necessary to make the extra requirements (not
defined in the setup.py files) *really* optional while running the
tests.
This removes the requirements to have the "psutil" and "jsonschema"
Python modules, and the "which" binary (usually from the package of
same name).
After this, it's possible to test Avocado from scratch with a workflow
such as:
$ podman run …
> Selftests: skip tests if modules and commands are not available

- avocado/plugins/spawners/podman.py
After the migration to eggs and more sophisticated avocado deployment this is no longer necessary.
Signed-off-by: Plamen Dimitrov <plamen.dimitrov@intra2net.com>
> Drop unused module level variable in the podman spawner

- avocado/core/messages.py
- avocado/core/nrunner/runnable.py
- avocado/plugins/jsonresult.py
- selftests/functional/plugin/test_jsonresult.py
This will fix the problem where the tag attribute in the result was
empty because the avocado test tags wasn't propagated to the results.
This will help to recognize which tags were used for each test.
Reference:  #5387
> Propagate avocado tags to results

- avocado/plugins/spawners/podman.py
- selftests/functional/plugin/spawners/test_podman.py
This adds the ability of podman spawner to create read-only volumes for
tests. Because of this, the avocado runners will be able to find test
files inside the container based on runnable uri. With this change is
possible to run exec-tests and avocado-instrumented tests with podman
spawner.
> Podman spawner with volumes for tests

- avocado/core/plugin_interfaces.py
- avocado/core/spawners/mock.py
- avocado/core/task/statemachine.py
- avocado/plugins/spawners/podman.py
- avocado/plugins/spawners/process.py
- avocado/utils/podman.py
- selftests/functional/plugin/spawners/test_podman.py
- selftests/functional/test_task_timeout.py
In the current avocado version, the `task.timeout.running` option wasn't
working. Because we didn't have a mechanism for interrupting tasks after
the timeout reached. This PR adds an ability to spawners to
terminate the pawned task when it is necessary.
It fixes the #5383, but it also helps with solving problems with post
test plugins.
Reference: #5383
> task.timeout.running fix

- avocado/core/nrunner/task.py
This Task attribute is not used, having the RuntimeTask
"spawner_handle" attribute taken its place.
> avocado/core/nrunner/task.py: remove unused spawn_handle attribute

- avocado/core/nrunner/runnable.py
- avocado/core/nrunner/runner.py
- avocado/core/nrunner/task.py
- avocado/plugins/runner_nrunner.py
- avocado/plugins/spawners/podman.py
- avocado/plugins/spawners/process.py
- selftests/functional/test_nrunner.py
- selftests/unit/test_nrunner.py
Some runners (like instrumented) need config values for proper working.
When we are running tasks by `avocado run` or Job API the default
configuration is inserted to runners via runnable. The problem starts
when you run test runner with `runnable-run` command even a small test
as 'avocado-runner runnable-run -k avocado-instrumented -u
examples/tests/passtest.py:PassTest.test` will fail because of missing
configuration. This PR solves this problem by adding default
configuration to the runnable.
Changes from v1 (#5313):
* Usage of features from #5326
It helps to add only necessary config for runners.
Cahnges from v2(#5363):
* The pick_runner_command as static method.
* Class method for creating Runnables with only essential config.
* Method for filtering config
* config setter doesn't …
> Runnable with default config [v3] 

- avocado/core/dispatcher.py
- avocado/core/plugin_interfaces.py
- avocado/core/task/runtime.py
- avocado/core/task/statemachine.py
- avocado/plugins/dependency.py
- avocado/plugins/plugins.py
- docs/source/guides/user/chapters/plugins.rst
- selftests/unit/test_dependencies_resolver.py
- setup.py
Infrastructure for creating pre-test plugins. Such plugin will
be able to add tasks before or after the test task.
It is based on a Draft https://github.com/avocado-framework/avocado/pull/5281
Reference: https://github.com/avocado-framework/avocado/issues/5204
Signed-off-by: Jan Richter [jarichte@redhat.com](mailto:jarichte@redhat.com)
Changes from v1 (#5384):
- Removal of Asset and Package plugins. Instead of that, there will be a dependency plugin which will cover all the dependencies and will make creating new dependencies easier like in #5402
> Pre test plugins [v2]

- selftests/functional/test_teststmpdir.py
This is just a couple of fixes found or related during the execution of selftests under `selftests/run` (which also affects `selftests/run_coverage`).
> Fixes to selftests execution under "selftests/run"

- selftests/pre_release/tests/vmimage.py.data/variants.yml
This will update the Fedora versions in vmimage pre-release checks.
> Fedora version update for vmimage

- .github/workflows/ansible.yml
- .github/workflows/ci.yml
- .github/workflows/prerelease.yml
Fedora 35 and 36 are the currently supported versions and should be
used on CI.
This also fixes an issue with the "Check the right RPM packages are
available" CI check (part of the Pre-release tests) because it was
using an EOL chroot (Fedora 34).
> CI: update to use currently supported Fedora versions

- avocado/core/dependencies/requirements/cache/__init__.py
- avocado/core/dependencies/requirements/cache/backends/sqlite.py
- avocado/core/plugin_interfaces.py
- avocado/core/spawners/mock.py
- avocado/core/task/runtime.py
- avocado/core/task/statemachine.py
- avocado/plugins/spawners/podman.py
- avocado/plugins/spawners/process.py
- docs/source/guides/user/chapters/requirements.rst
- selftests/check.py
- selftests/functional/serial/test_requirements.py
- selftests/functional/test_requirements_cache.py
- selftests/unit/test_task_runtime.py
This PR adds the ability to spawners to store requirements into cache.
This will make more efficient running multiple tests with the same
requirement or rerunning the jobs itself.
This also brings ability to use requirements with podman spawner. So now
is possible to run something like this:
```
class SuccessTest(Test):
def check_hello(self):
result = process.run("hello", ignore_status=True)
self.assertEqual(result.exit_status, 0)
self.assertIn('Hello, world!', result.stdout_text,)
def test_a(self):
"""
avocado dependency={"type": "package", "name": "hello"}
"""
self.check_hello()
```
Warning: Right now, the requirement cache doesn't have any controls for
clearing cache or updating, and also didn't check the current
environment. So if the user do some changes to the environment outside …
> Requirements database [v3]

- avocado/core/test.py
- examples/tests/failtest_with_warning.py
- selftests/functional/test_basic.py
If a test logged a warning via the log.warning command, then no matter
what happened afterwards, the test result was WARN. This fixes this
problem. So the test result will be WARN only when the test itself
succeed with warning.
Reference: #5375
> Test results with warning fix

- selftests/unit/test_nrunner.py
Because the input URI format for unittests changed, these tests were
removed.  But, they do cover valid functionality, and can be adapted
to use other existing URIs.
> selftests/unit/test_nrunner.py: restore unittests from PR #4861

- avocado/utils/data_factory.py
header: fix function make_dir_and_populate
message: When use funciton make_dir_and_populate to create a directory in basedir and populate with a number of files,
raise TypeError: a bytes-like object is required, not 'str'
This PR fix this bug
Reference: See the following drawing
Signed-off-by:WangPeng wangpengb@uniontech.com
> fix data_factory.py

- avocado/core/nrunner/runner.py
- avocado/plugins/runners/exec_test.py
- avocado/plugins/runners/tap.py
- optional_plugins/golang/avocado_golang/runner.py
- optional_plugins/robot/avocado_robot/runner.py
The `exec-test`, and its child `tap` runner, share a lot of code, but there are still some duplication.  Also the `golang` and `robot` runners can share more code and have a more consistent behavior when it comes to the "running" messages.
---
Changes from v1 (#5438):
* announce test "started" sooner (suggested by @richtja)
> nrunner: refactors to exec-like runners [v2]

- selftests/unit/utils/test_iso9660.py
- selftests/unit/utils/test_partition.py
This removes some outdated skips from `iso9960` and `disk` utility modules.
> Utils: iso9660 and disk test skips

- selftests/style.sh
This will add `--diff` attribute to the `black` command. With the diff
attribute will be more clear what is the style issue and how it might be
fixed.
Reference: #5441
> `Black` static checks update

- contrib/containers/fedora-36-latest-copr.docker
Many times it's useful to have Avocado fully installed (all packages)
from RPM packages.  This container image will have installed all of
the latest Avocado COPR builds packages, triggered on every commit of
the master branch.
It will be available from:
quay.io/avocado-framework/avocado-fedora-36-latest-copr
> Containers: add fedora-36-latest-copr.docker

- .packit.yml
The default mock/koji/etc behavior is to *not* have network enabled.
This allows common errors to be caught, such as dependencies being
resolved by means other than BuildRequires (such as an implicit
install of a Python dependency listed in setup.py).
Now Packit has this configuration available, so let's use it.
Reference: https://github.com/packit/packit/pull/1504
> [82lts] Packit: disable network during builds

- .travis.yml
- Makefile
- selftests/unit/test_utils_network.py
Travis CI images based on xenial have been bitrotting, and Python 3.7.1 installed on top of it is particularly broken.
With this bump, the number of sucessfull jobs in Travis go from 2 (Python 3.5 and 3.6) to 5 (Python 3.5, 3.6, 3.7, 3.8 and Code Coverage).
> [82lts] Update Travis CI distro version to focal

- python-avocado.spec
The versions available on the current target distros are either equal or superior to the ones defined in setup.py.
This was tested with Fedora rawhide (F38) packages and the resulting RPMs generated HTML reports just fine.
> [82lts] Packit HTML deps

- .travis.yml
- Makefile
On the most recent setuptools release, the behavior changed and the
"user's local Python library dir" does not support ".pth" files.
This means that, if using "--user", "setup.py develop" have avocado
in the PYTHONPATH.  The message produced on Travis is:
Checking .pth file support in /home/travis/.local/lib/python3.9/site-packages
/home/travis/virtualenv/python3.9.12/bin/python3 -E -c pass
TEST FAILED: /home/travis/.local/lib/python3.9/site-packages does NOT support .pth files
bad install directory or PYTHONPATH
Given this is a CI environment, we can simply instruct develop to
install (more of a link, really) in a non-user location.
> [82lts] Travis CI: address setuptools >= 62.1.0 behavior

- avocado/utils/lv_utils.py
The volume group name and logical volume device parameters passed for vgcreate command were not properly handled
I have fixed the creation of the command to be executed with correct conditional statements
Signed-off-by: Pavaman Subramaniyam <pavsubra@linux.vnet.ibm.com>
> Fixed the volume group creation error

- selftests/functional/test_sysinfo.py
The virtualization type used on Travis for arm64 (aarch64) is LXD,
which normally does not have a root device in the "/proc/cmdline"
file.
Reference: https://docs.travis-ci.com/user/reference/overview/#which-one-do-i-use
> Travis: add exclusion condition for SysInfo html test

- avocado/core/nrunner/task.py
- avocado/plugins/runner_nrunner.py
- selftests/jobs/status_server_auto
- selftests/jobs/status_server_different_uri_listen
The independence of `--nrunner-status-server-uri` and `--nrunner-status-server-listen` is not being respected.
Because `Tasks` are being created with whatever is the current status server URI (either determined automatically, or with the "listen" config), the "uri" config goes unused.
---
Changes from draft PR (#5481): 
* Added two selftest jobs to check "auto" behavior and "uri" different than "listen"
> nrunner: fix behavior of status server "uri" and "listen"

- .travis.yml
- avocado/plugins/runner_nrunner.py
- optional_plugins/html/setup.py
- optional_plugins/html/tests/test_html_result.py
- requirements-dev.txt
- selftests/jobs/status_server_auto
- selftests/jobs/status_server_different_uri_listen
The independence of `--nrunner-status-server-uri` and `--nrunner-status-server-listen` is not being respected.
Because `Tasks` are being created with whatever is the current status server URI (either determined automatically, or with the "listen" config), the "uri" config goes unused.
> [92lts] nrunner: fix behavior of status server "uri" and "listen"

- avocado/utils/software_manager/backends/rpm.py
Change prepare_source function built_option from -bp to -bc. Function named 'prepare_source' used for compiling and testing the distribution provided packages.
Current way of doing:
Download source package
rpmbuild -bp <package name>
Configure using 'configure' with out any options
Compile
Run the unit test cases
the above way is not considering the distribution provided configuration options.
Changing the build option from '-bp' to '-bc' will help in compiling with distribution provided config options.
Signed-off-by: Nageswara R Sastry <rnsastry@linux.ibm.com>
> rpm.py: change prepare_source function built_option

- avocado/core/messages.py
- avocado/core/runners/utils/messages.py
- docs/source/guides/writer/chapters/logging.rst
- selftests/functional/test_basic.py
This adds the ability for the runners to print user-specific logging
streams to the console when the --show command is used.
It is backport of https://github.com/avocado-framework/avocado/commit/e2652b71668068838ea856bb7e16b262d34a511e and https://github.com/avocado-framework/avocado/commit/ddd143e2e928fa326dcd9ee65a942087207c5748.
Signed-off-by: Jan Richter [jarichte@redhat.com](mailto:jarichte@redhat.com)
> Option --show fix

- avocado/core/dependencies/requirements/cache/backends/sqlite.py
- avocado/core/dispatcher.py
- avocado/core/plugin_interfaces.py
- avocado/plugins/cache.py
- avocado/plugins/plugins.py
- avocado/plugins/requirement_cache.py
- avocado/plugins/vmimage.py
- setup.py
This is an initial PR which crates avocado cache interface. It introduces new plugin "Cache" which will be responsible for manipulating with cache, and it's representation through avocado interface. This PR also adds vmimage cache and requirements cache to this interface.
For now, it supports only listing of cache entries, but it is possible to expand for features like prune or edit.
Reference: https://github.com/avocado-framework/avocado/issues/5453
> Cache interface

- avocado/utils/pci.py
Update get_pci_class_name function with usb adapter class name and id
> Add class name and id for USB pci adapter

- avocado/core/__init__.py
- avocado/plugins/list.py
- avocado/plugins/run.py
- avocado/plugins/runner_nrunner.py
- docs/source/guides/contributor/chapters/plugins.rst
- docs/source/guides/user/chapters/dependencies.rst
- docs/source/guides/user/chapters/introduction.rst
- man/avocado.rst
The `--nrunner-$option`s made sense when the old runner was available. Nowadays, it's just more typing and confusion to users.
Also, this PR makes Avocado favor the `--suite-runner` instead of the `--test-runner` command line option, but still allowing for the later as a deprecated option.
> Deprecate nrunner prefix from options

- contrib/containers/ci/selftests/check-copr-rpm-version.docker
- selftests/pre_release/tests/check-copr-rpm-version.sh
This brings backports and one branch adjustment to address the pre-release "Check the right RPM packages are available in COPR" job.
> [LTS] Fixes for release 92.1: COPR check

- avocado/core/nrunner/runnable.py
- avocado/plugins/spawners/process.py
The current setting of PYTHONPATH values is necessary, but as it's implemented, it is similar to a fork bomb.  On each new execution, new values are appended to the global PYTHONPATH environment variable.  In jobs with many tests, this can grow out of the existing limits (besides adding unnecessary memory overhead).
This was actually caught by failures on COPR builds.
> Python path environment bomb fix

- .github/workflows/ci.yml
macOS 10.15 is deprecated.  Let's bump the image used to the next available version.
Reference: https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job#choosing-github-hosted-runners
> GitHub Actions: bump macOS version away from deprecated

- avocado/plugins/assets.py
Couple of changes to the Assets plugin:
* Remove code that handles legacy runner
* Only fetch assets from an unique test once
> Asset: legacy runner and duplicate tests

- spell.ignore
nvme is a static word and it is giving error for other nvme related pacthes as static check failed. so adding it to get ignore so that patches can be merged.
> adding nvme static word to ignore in spell.ignore

- selftests/functional/test_list.py
- selftests/unit/test_loader.py
- selftests/unit/test_resolver.py
- selftests/unit/test_tags.py
This introduces a port of `selftests/unit/test_loader.py` to cover the resolver.  The idea is to have simultaneous coverage until the removal of the loader code.
> Resolver: introduce same test coverage as loader

- selftests/functional/plugin/spawners/test_podman.py
- selftests/functional/serial/test_requirements.py
Because of the release of Fedora 37, the default distro has Python 3.11. The problem with that is there are no "setuptools" (or Avocado eggs for that matter) available for Python 3.11 yet.
This caused a brekage in the selftests run in CI (or in any environment where a reference to fedora:latest was refreshed and resolved to fedora:37).
Because there are tests, it's better to *not* have them changing behavior because of external events.
This still keeps the default behavior of the spawner to use the latest fedora if a distro matching the host can not be detected.
Reference: https://github.com/avocado-framework/avocado/issues/5525
> Selftests: pin Fedora version used on podman spawner

- selftests/check.py
There is one open issue about the order of tests (or suites) impacting test behavior.  This is a workaround so that `make check` passes, while the definitive issue is fixed.
Fixes: https://github.com/avocado-framework/avocado/issues/5378
Reference: https://github.com/avocado-framework/avocado/issues/5532
> Selftests: run static checks first

- .github/workflows/ci.yml
- .github/workflows/weekly.yml
- avocado/core/spawners/mock.py
- avocado/plugins/assets.py
- avocado/plugins/beaker_result.py
- avocado/plugins/bystatus.py
- avocado/plugins/diff.py
- avocado/plugins/human.py
- avocado/plugins/journal.py
- avocado/plugins/spawners/podman.py
- avocado/plugins/sysinfo.py
- avocado/plugins/tap.py
- avocado/plugins/testlogs.py
- avocado/plugins/teststmpdir.py
- optional_plugins/resultsdb/avocado_resultsdb/resultsdb.py
- setup.py
Update the github actions to test also Python 3.11 and add python 3.11 as supported versions.
Reference: https://github.com/avocado-framework/avocado/issues/5503
> Python 3.11 support

- avocado/core/task/statemachine.py
- avocado/plugins/runner_nrunner.py
- selftests/functional/test_job_timeout.py
This commit adds a mechanism for terminating running tasks after the job reaches its timeout.
Reference: #5295
> Task cancelation on job timeout

- avocado/core/__init__.py
- avocado/plugins/variants.py
The two configuration items removed here can be better served by the systems' automatic locale configuration.
> Unicode handling: rely on sys.getdefaultencoding()

- avocado/utils/process.py
signal.default_int_handler needs the arguments to be passed on.
Signed-off-by: Akihiko Odaki <akihiko.odaki@daynix.com>
> avocado/utils/process.py: Handle signal arguments

- avocado/plugins/bystatus.py
- selftests/functional/plugin/test_bystatus.py
The current design uses an absolute path to create symbolic link, this means no matter where the log files are moved/uploaded, the soft link always link to the original directory. This doesn't make sense, so replace it to use relative path, make them link to the correct path.
> bystatus.py: Use relative path to create symbolic link

- avocado/core/__init__.py
- avocado/core/dispatcher.py
- avocado/core/nrunner/task.py
- avocado/core/plugin_interfaces.py
- avocado/core/status/server.py
- avocado/core/suite.py
- avocado/plugins/jobs.py
- avocado/plugins/plugins.py
- avocado/plugins/run.py
- avocado/plugins/runner_nrunner.py
- docs/source/guides/contributor/chapters/runners.rst
- docs/source/guides/user/chapters/advanced.rst
- examples/jobs/multiple_suites_from_config.py
- man/avocado.rst
- selftests/check.py
- selftests/functional/plugin/spawners/test_podman.py
- selftests/functional/serial/test_requirements.py
- selftests/functional/test_basic.py
- selftests/functional/test_nrunner.py
- selftests/functional/test_teststmpdir.py
- setup.py
Note: This PR is marked as Draft only because it's intended to be merged only after Avocado 99.0 is released.
---
The --nrunner-$options made sense when the old runner was available. Nowadays, it's just more typing and confusion to users.
Also, this renames the Runner interface and --test-runner option to SuiteRunner and --suite-runner, to more accurately represent what they do.
Changes from v1 (https://github.com/avocado-framework/avocado/pull/5449):
* Misc commits and the deprecation messages merged in a separate PR (#5493)
> Drop nrunner prefix from options [v2]

- avocado/core/job.py
- avocado/core/result.py
- avocado/plugins/jobs.py
- avocado/plugins/jsonresult.py
- selftests/unit/test_job.py
Currently, an `avocado jobs list` command will usually return something like:
```
0d6874b8902f29d2498e4af1a6449213b261d68 1969-12-31 23:04:52.077601   3 (1/0/0/1)
eab993bf69f5bdc0edd6c8d72cf34ed3c83db6a2 1969-12-31 23:05:11.940534   3 (3/0/0/0)
ec7ca92458b77083334c6775d0011561bc277170 1970-01-01 21:55:22.576918   1 (1/0/0/0)
3ea5516b1bfc398495e340745126396add2bdb91 1970-01-01 21:56:37.293293   1 (1/0/0/0)
```
The date and times are way off.  The reason is the use of the first test's "time", which is a monotonic time and can not be used for an actual date and time.
> Job: fix the start time

- optional_plugins/varianter_yaml_to_mux/tests/test_functional.py
Most selftests do that, in order not to pollute the user's job result dir, but it's missing on this specific test.
> Selftest: use a temp dir as the job's result dir

- examples/jobs/multiple_suites_from_config.py
On 8db957992, "nrunner.shuffle" was renamed to "run.shuffle".  Let's match this example job accordingly and make the behavior of that option more apparent to users.
> Multiple suite example job

- avocado/core/utils/loader.py
The loader has to pass  'run.results_dir' as `base_logdir` to test class. Let's add this change at the beginning of the `load_test` method. It will avoid problems with handling loader errors, because any loader error was overwritten by unexpected keyword argument 'run.results_dir' error in test class. It fixes #5459
Reference: #5459
> Loader unexpected keyword argument 'run.results_dir' fix.

- avocado/plugins/xunit.py
- docs/source/guides/user/chapters/introduction.rst
- selftests/.data/jenkins-junit.xsd
This adds a test file field to the junit result format. This field is well known and used by CIs (like Gitlab)
Reference: #5229
> junit restults add 'file' field

- examples/jobs/unix_status_server.py
- selftests/check.py
- selftests/functional/plugin/spawners/test_podman.py
- selftests/jobs/status_server_auto
- selftests/jobs/status_server_different_uri_listen
- selftests/pre_release/jobs/pre_release.py
Commit 8db957992 dropped the "--nrunner-" command line prefixes, and changed the configuration option names from "nrunner." to "run.".
These are leftover renames that were missing in that changeset.
> Missing renames of nrunner.* configuration options

- avocado/plugins/spawners/podman.py
- selftests/functional/plugin/spawners/test_podman.py
The Podman spawner creates a volume that serves to preserve a test's "outputdir" (aka "data") directory.  But, because of possible (and probable) mismatches between users in the "host" and in the container itself, the current choice of location for the "outputdir" can prove ineffective.
This changes the directory used as the outputdir to an absolute location, that does not depend on the user.
Fixes: https://github.com/avocado-framework/avocado/issues/5556
> Podman spawner: fix outputdir preservation

- .github/ISSUE_TEMPLATE/bug_report.md
Since we moved to the new project board, we don't need tag for triaging issues, because we have special status for that in new project board.
Reference: https://github.com/orgs/avocado-framework/projects/1
> Remove triage tag from issue templates

- avocado/core/messages.py
- avocado/plugins/runners/exec_test.py
- selftests/.data/exec_test_std/exec_test_1mib.py
- selftests/.data/exec_test_std/exec_test_64kib.py
- selftests/functional/test_nrunner.py
Most of the information that generic executables (exec-test) tests generate will be done with their STDOUT and STDERR.
Avocado, since 0a8178ded, inadvertently reduced the size capacity when keeping and storing the STDOUT and STDERR.  Still, limits will always exist, either in memory buffer sizes, network buffer sizes, or even filesystem file size limits or overall storage resources.
This change increases considerably the limits of an "exec-test" by using, when available, the given "output_dir" parameter to a runnable or task.  Whenever a test is run under "avocado run", a task will be used, and a task always has an "output_dir", so, unless one is running "avocado-runner-exec-test" manually and *not* providing an output_dir, the STDOUT and STDERR limits are now the filesystem limits.
The …
> exec-test: allow the use of runnable's output dir for stdout/stderr [v2]

- selftests/check.py
- selftests/functional/plugin/test_logs.py
- selftests/functional/serial/test_requirements.py
- selftests/functional/test_nrunner.py
- selftests/functional/test_output.py
- selftests/jobs/example_passjob
- selftests/jobs/example_passjob_cit_varianter
- selftests/jobs/example_passjob_html
- selftests/jobs/example_sleepjob_dict_varianter
- selftests/jobs/example_sleepjob_json_varianter
- selftests/jobs/example_unix_status_server
- selftests/jobs/passjob.py
- selftests/jobs/passjob_cit_varianter.py
- selftests/jobs/passjob_html.py
- selftests/jobs/sleepjob_dict_varianter.py
- selftests/jobs/sleepjob_json_varianter.py
- selftests/jobs/status_server_auto
- selftests/jobs/unix_status_server.py
This will update selftests to not store temporary results in user's
default results directory.
Reference: https://github.com/avocado-framework/avocado/issues/5554
> Selftests user's default results directory cleanup

- avocado/core/nrunner/runnable.py
- avocado/core/utils/eggenv.py
- avocado/plugins/spawners/process.py
- spell.ignore
When running Avocado Python modules, the interpreter on the new process needs to know where Avocado can be found.  This is usually handled by the Avocado installation being available to the standard Python installation, but if Avocado is running from an uninstalled egg, it needs extra help.
Previously, the content of the set created from the sys.path content which is not ordered by nature, meant that the order of entries on the PYTHONPATH would change unpredictably.
Because of the changes in the spawner, and the much smaller intrusion on PYTHONPATH (and thus on the "import" machinery), the safeloader.sh test issue goes away.
Fixes: https://github.com/avocado-framework/avocado/issues/5378
> Egg support: be more precise when adding egg location to PYTHONPATH

- avocado/core/messages.py
- avocado/core/utils/messages.py
- selftests/functional/test_output.py
The `--show` is currently failing to show live content from custom loggers within `avocado-instrumented` tests. This fixes that situation while also doing some refactors and readability improvements.
It's expected that the logging system as a whole needs to be revisited in a non-bugfix manner soon.
---
Changes from v1 (https://github.com/avocado-framework/avocado/pull/5570):
* Opted for a strictly bug fix, removing all refactors and renames commits, to preserve more compatibility this late in the sprint
* Added docstring for `message_only_formatter` property
> Restore support for --show=$custom_logger on avocado-instrumented [v2]

- avocado/utils/vmimage.py
The files downloaded by avocado.utils.vmimage can be on the large side.  For instance, FreeBSD images are around 600MiB.
In my experience, the servers hosting those images seem to enforce connection bandwidth limits.  Testing the download from multiple sources with adequate bandwith resulted in timeout errors for the current 5 minutes limit.  A manual download (without using vmimage) took around 6 minutes.
To be on the safe side, let's double the download timeout.
> vmimage: double the download timeout

- avocado/utils/asset.py
- avocado/utils/vmimage.py
On cfb691e95, the download timeout for vmimage was doubled.  But, as can be seen in some CI jobs, the downloads for some officially supported images can get easily exceed even the new timeout:
vmimage.py:ImageFunctional.test_get;run-architectures-x86_64-distro-freebsd-version-12.2-9d3c: PASS (590.04 s)
This further increases the timeout to cope with those actual times.
Additionally, it substitutes the magic "120" seconds timeout for the lock with the timeout given.  By then, the file should either have downloaded successfully by the other (possible parallel actor) or timed out.
Reference: https://github.com/clebergnu/avocado/actions/runs/3875993920/jobs/6609284678#step:4:510
> avocado.utils.vmimage timeout: further increase timeout and cover lock

- .github/workflows/ci.yml
- avocado/plugins/spawners/podman.py
On 7a8bbb250, the "avocado-runner" command and the "avocado.core.nrunner" module entrypoint were removed.  But, the Podman spawner failed to sync with this change, and kept using the "avocado.core.nrunner" module when running a task on a container.
The reason this was not caught before is that, all the tests make use of the previously release egg, and not an egg that matches the development state.  This should now be protected with a new CI check.
> Podman spawner: use runner plugins instead of removed generic nrunner

- .github/workflows/release.yml
On 2eb51609f Python 3.11 was added, but we missed the step to build and publish eggs for that Python version during the release process.
> Build and publish eggs for Python 3.11

- avocado/utils/vmimage.py
So the URL for all versions equal or earlier than 35, need to be fetched from the archives.
Reference: https://dl.fedoraproject.org/pub/fedora/linux/releases/35/README
> avocado/utils/vmimage.py: Fedora 35 and earlier are archived

- avocado/utils/partition.py
Mountpoint symbolic links also needs to be searched while getting mountpoint and removal of those are also needed.
Signed-off-by: ayushjain951 <ayush.jain3@amd.com>
> Unmounting of symbolic mountpoints

- avocado/plugins/spawners/podman.py
The --spawner-podman-avocado-egg parameter takes an URL, but that is not obvious from the documentation.  Let's add one explicit example using file:///, which is the easist use case to miss.
Fixes: https://github.com/avocado-framework/avocado/issues/5389
> Podman Spawner: better document the avocado egg parameter

- avocado/core/messages.py
- avocado/core/utils/messages.py
- avocado/plugins/runners/avocado_instrumented.py
- avocado/plugins/runners/python_unittest.py
- selftests/functional/plugin/test_xunit.py
- selftests/unit/test_nrunner.py
Gathering more metadata from resolvers and runners. It will provide better information about test and its failures, which can be used by result plugins.
Reference: https://github.com/avocado-framework/avocado/issues/5332
> Xunit results missing attributes

- .github/workflows/ci.yml
- .github/workflows/release.yml
- avocado/core/status/server.py
- setup.py
Python 3.6 has been EOL'd for over a year.  But some projects such as QEMU still have it as the mininum required Python versions, and this has kept us from deprecating it.
There's a [new effort](https://lists.gnu.org/archive/html/qemu-devel/2023-01/msg04398.html) going on to bump the minimum required version in QEMU, so I feel more confident in dropping it in Avocado too.
> Drop Python 3.6 support

- avocado/plugins/jsonresult.py
- avocado/plugins/xunit.py
- selftests/functional/plugin/test_jsonresult.py
- selftests/functional/plugin/test_xunit.py
After the changes in 059e7646103ea673951e31f7e33895339b69ff14 and 0ccab1521d0286d6bf2c7555fc5be81cb029e96a the result plugins lost information about variants. This is a fix for that.
Reference: https://github.com/avocado-framework/avocado/issues/5589
> Variant in xunit and json results

- avocado/utils/network/interfaces.py
A standard format to configure static ip is to add netmask as prefix to the IP address/24, it is missed in previous change
> Add missing prefix for static ip configuration

- .github/workflows/ci.yml
- Makefile
- Makefile.gh
- Makefile.include
- setup.py
Avocado's CI jobs currently only build eggs for the main "avocado-framework" package, but not for the plugins.  Given that the Podman spawner deserves to be able to also prepare and use runners from plugins, it also needs to have the plugins' eggs built and available for download.
This is a first step that adds the building of the eggs to every job run at PR time.  Later, the same shall be added to the Release jobs, and a permanent location for plugins' eggs will be determined.
Reference: https://github.com/avocado-framework/avocado/issues/5588
> Build plugins' eggs

- avocado/utils/network/hosts.py
While sending previous commit, function name get_hwaddr had minor typo is now fixed
> host.py: fix typo in function name

- avocado/utils/disk.py
In an unpredicatable device name environment, it is better to always work via unique device ids which does not change post install/reboot/dlpar. so added a function to get all devices by its /dev/disk/by-ids
> get_disk_by_id: function to return all disks by device ids

- avocado/utils/cpu.py
Add a utilty to check if a CPU is hotpluggable
by checking if /sys/devices/system/cpu/cpu(cpu)/online present or not in sysfs.
Signed-off-by: Ayush Jain <ayush.jain3@amd.com>
> Add utility to check cpu is hotpluggable

- avocado/core/suite.py
- avocado/core/task/runtime.py
- avocado/plugins/runner_nrunner.py
- examples/jobs/sleepjob_parameters.py
- selftests/functional/test_job_api_features.py
- selftests/unit/test_task_runtime.py
It moves test variant creation from runtime task to suite. When we are creating suite, we have all information about tests and variants, so there is no need to wait for generating test variants. This refactoring will make things easier because we will know the actual test size right after the suite has been created.
Also, it fixes problems with Job API when users want to define variants or parameters by themselves and not with varianters, like in `examples/jobs/sleepjob_parameters.py`
Reference: #5356, #5347
> Test variant creation refactoring

- avocado/utils/network/hosts.py
Added validate Mac address functions to utility.
With misc tests changing from interface based to MAC address need this function to validate the MAC is valid.
Signed-off-by: Manvanthara B Puttashankar <manvanth@linux.vnet.ibm.com>
> Added validate Mac address functions to utility.

- avocado/utils/archive.py
- python-avocado.spec
- selftests/unit/utils/test_archive.py
This adds support for extracting zstd archives using the `avocado.utils.archive.uncompress()` API, and is similar to the feature level introduced earlier for lzma archives.
In the future it should be possible to expand this with:
* support for compression
* support for more backends (such as python-zstd or python-zstandard)
All in all, this should be enough to fulfill the use case described in the matching issue.
Fixes: https://github.com/avocado-framework/avocado/issues/5609
> avocado.utils.archive: add support for Zstandard uncompression

- avocado/plugins/xunit.py
- docs/source/guides/user/chapters/introduction.rst
- selftests/.data/jenkins-junit.xsd
- selftests/functional/plugin/test_xunit.py
because we face some incompatibility issues with avocado JUnit results and Jenkins CI. We have to revert changes to JUnit plugin which added "file" field to the results.
Reference: #5616
> Revert of #5547 'file' field in junit results

- .github/workflows/ci.yml
- avocado/utils/linux_modules.py
- examples/tests/false
- examples/tests/true
- optional_plugins/html/tests/test_html_result.py
- selftests/check.py
This improves portability on UNIX systems that are not necessarily your run-of-the-mill Linux distros.
In this case, a good part of the selftests gets to be run macOS.
> Improve portability

- avocado/core/dispatcher.py
- avocado/core/plugin_interfaces.py
- avocado/core/task/runtime.py
- avocado/core/task/statemachine.py
- avocado/plugins/dependency.py
- avocado/plugins/plugins.py
- avocado/plugins/runner_nrunner.py
- docs/source/guides/contributor/chapters/plugins.rst
- examples/plugins/test-pre-post/hello/hello.py
- examples/plugins/test-pre-post/hello/setup.py
Infrastructure for creating post-test plugins. Such plugin will
be able to add tasks after the test task.
Introduces first post test plugin which is using this infrastructure the sysinfo plugin.
It adds sysinfo gathering into the suite run. It creates pre and
post sysinfo tasks in a suite which will be run before and after the
testing. Those tasks will gather sysinfo by sysinfo-runner and save it
into the test-results folder.
Reference: https://github.com/avocado-framework/avocado/issues/5204, https://github.com/avocado-framework/avocado/issues/3877
Signed-off-by: Jan Richter [jarichte@redhat.com](mailto:jarichte@redhat.com)
---
Changes from v1 (#5452):
* remove PostRuntimeTaskPrototype. I used a different approach. Now the post plugins have to create post tasks for each test result and …
> Post test plugins [v2]

- avocado/core/nrunner/runnable.py
- avocado/core/resolver.py
- avocado/plugins/resolvers.py
- avocado/plugins/spawners/podman.py
- avocado/utils/ar.py
- docs/source/guides/contributor/chapters/plugins.rst
- examples/tests/use_data.sh
- optional_plugins/varianter_cit/tests/basic.py
- selftests/functional/basic.py
- selftests/functional/plugin/spawners/podman.py
So far, spawners that run tests in different environments have been mostly guessing about what the test constitutes.
This adds more responsibilities on the resolvers. If applicable, they can describe which files constitute the test, so that they will be deployed on the actual environment the test will be executed on.
---
Changes from v1 (#5633):
* Added documentation on how resolvers/discoverers should provide test data files information to spawners' use
* Improved portability by using `os.path.join` on the data files `glob.glob()` call
> Introduce support for test data files in resolvers and spawners [v2]

- avocado/utils/disk.py
- avocado/utils/multipath.py
These utils will help to get all the available disks names or alias names disk by-id, by-path, by-uuid, or mapper names and also get absolute device path of a given disk irrespecitve of device type and platform
> disk.py: added disk utils to get all paths and absolute path

- avocado/core/task/runtime.py
- avocado/core/task/statemachine.py
- avocado/plugins/runner_nrunner.py
- docs/source/guides/user/chapters/introduction.rst
- docs/source/guides/writer/chapters/writing.rst
- selftests/functional/interrupt.py
This adds a finer grained handling of the reason why a job is being interrupted, adding proper support for when the user interrupts it by pressing CTRL+C (KeyboardInterrupt) or sending a SIGINT signal.
Fixes: https://github.com/avocado-framework/avocado/issues/5560
> Present proper interrupt reason on KeyboardInterrupt/SIGINT

- avocado/utils/nvme.py
currently we are using the 0] string to get the controller id in list_ctrl option. This may not give always the active controller ID of nvme adapter among the two IDs it holds. So changing the nvme option to id-ctrl and finding with exact controller_id string.
also made the script to pep8 compliance.
> Changing the script to get the exact active controller_id in nvme.py

- avocado/core/messages.py
- avocado/core/spawners/common.py
- avocado/core/task/runtime.py
- avocado/plugins/runner_nrunner.py
- avocado/plugins/sysinfo.py
- selftests/functional/job_api_features.py
- selftests/functional/sysinfo.py
- selftests/unit/task_runtime.py
- setup.py
This PR introduces the ability for Runnable to specify the output_dir. Because of this, the Tasks will be able to share the output directory. Since this was the last piece which has been missing for sysinfo support, this PR also enables sysinfo per test.
Reference: #5647, #3877
> Runnable log_dir and sysinfo support

- avocado/core/exceptions.py
- avocado/core/task/statemachine.py
- avocado/plugins/runner_nrunner.py
This is a clean up of exceptions, most related to the legacy runner and the now clearer separation between tests and jobs.
> Exceptions cleanup

- avocado/core/utils/messages.py
In some circumstances, avocado instrumented runner can hang indefinitely and block other test to execute. This is caused by a very specific bug in `multiprocessing.Queue` which can cause deadlock when you're manipulating with queue during garbage collection. This issue was investigated and well described by @pevogam in
https://github.com/avocado-framework/avocado/issues/4935#issuecomment-938069202 for long story short, this is the process which causes deadlock:
1. The program was calling q.put(2).
2. This involves acquiring a lock.
3. Half-way through the function call, garbage collection happens.
4. Garbage collection calls Object.__del__.
5. Object.__del__ calls q.put(1).
6. q.put(1) tries to acquire the lock… but the lock is already held, so it waits.
Because instrumented runner is …
> Disable garbage collection during logging

- avocado/core/resolver.py
- selftests/functional/basic.py
This will improve avocado error message when some reference wasn't resolved. It adds a pointer to `avocado -V list` which provides more information about references.
Reference: #5644
> Improve message when resolvers don't resolve the reference

- avocado/core/safeloader/core.py
- selftests/unit/safeloader_core.py
- selftests/unit/tags.py
This commit introduces tags inheritance. Now, the avocado tags will respect tags from parent classes and parent methods. Let's imagine such a test file:
```
class Base(avocado.Test):
'''
:avocado: tags=foo
'''
def test_one(self):
pass
class Derived(Base):
'''
:avocado: tags=boo
'''
def test_two(self):
pass
```
The methods Derived.test_one and Derived.test_two will have tags from Base and Derived classes `foo` and `boo`.
Reference: #5680
> Tags inheritance

- avocado/core/task/runtime.py
when we are comparing the task results, we have to be sure that they are in the same format. Because the format of task result is chosen by the runner which runs the task, the formats may differ. This change makes all task results in low-case format. It will fix problem with post test plugins which might be skipped because of wrong result comparison of `result` and `satisfiable_deps_execution_statuses`.
Reference: #5681
> Task result in lower case

- docs/source/guides/writer/chapters/writing.rst
- docs/source/plugins/index.rst
- docs/source/plugins/standard/teststmpdir.rst
This adds section for standard plugins (as opposed to the existing "optional" plugins).  It also documents the `teststmpdir` plugin.
> Document standard plugin teststmpdir

- .github/workflows/ci.yml
- selftests/signedoff-check.sh
On GH Actions, selftests/signedoff-check.sh has been false positive when
the PR commits were older than master branch commits. It was caused by
rebase mechanism of used github action. This will change the action from
"git rebase" to "git merge". Also, we are always checking only the last commit,
this change will add a check for all commits in one PR.
Reference: https://github.com/avocado-framework/avocado/issues/5670
> signedoff-check.sh false positive fix

- examples/tests/test_env.py
Instances of avocado.core.utils.messages.StreamToQueue do not have a isatty() method.  Even if we end up implementing it, it's a good idea to protect the test against the lack of such an interface.
Fixes: https://github.com/avocado-framework/avocado/issues/5659
> examples/tests/test_env.py: protect against lack of isatty()

- avocado/utils/nvme.py
current method is returning list but it is easy to handle if the controller name is in string format. Hence modified accordingly
> Returning String instead of list based on test requirement in nvme.py

- avocado/plugins/assets.py
- selftests/unit/plugin/assets.py
Some "left hand side" part of assigments won't always have an id. This is the case of a Subscript, that exist in assignments such as:
foo["bar"] = "baz"
Instead of attempting to deal with each type of "left hand side" here, let's check for the existence of an "id" attribute, and back off if it doesn't exist.
Reference: https://docs.python.org/3/library/ast.html#ast.Subscript
Fixes: https://github.com/avocado-framework/avocado/issues/5415
> Assets plugin: do not assume assigments have ids

- avocado/core/messages.py
- avocado/core/task/runtime.py
- avocado/core/task/statemachine.py
- docs/source/guides/user/chapters/dependencies.rst
- selftests/functional/serial/requirements.py
This commit will create a new directory in
`{avocado_dir}/job-results/{job}/dependencies` for storing test
dependencies logs. Also for these logs symlinks to test directories will
be created. Therefore, if you want to get dependencies logs related to
one test, you will find them in
`{avocado_dir}/job-results/{job}/test-results/{test_id}/dependencies`
Reference: https://github.com/avocado-framework/avocado/issues/5671
---
changes from v1 (#5673)
* Special directory for job related dependencies
* Symlink of dependency logs to the test-results directory.
* New log message when the dependency has been fulfilled by cache.
> DependencyResolver output fix [v2]

- avocado/plugins/runners/exec_test.py
- avocado/plugins/spawners/process.py
- docs/source/guides/writer/chapters/writing.rst
- examples/tests/env_variables.sh
- selftests/functional/plugin/runners/exec_test.py
This PR enables all avocado variables from
`examples/tests/env_variables.sh` example for exec tests. It will
decrease the difference of environment variables between exec-test tests
and avocado-instrumented tests.
Reference: https://github.com/avocado-framework/avocado/issues/5637
> Environment variables for exec tests

- avocado/plugins/spawners/lxc.py
Before this adaptation we get simple avocado runs to result in
```
[root@c5 site-packages]# avocado run --status-server-disable-auto --spawner=lxc -- /bin/true
JOB ID     : 937ec5bb7275feabd48fcf5b5b315ad2cd2b63fc
JOB LOG    : /mnt/local/results/job-2023-05-02T22.51-937ec5b/job.log
(1/1) /bin/true: STARTED
(1/1) /bin/true: ERROR: [Errno 2] No such file or directory: '/mnt/local/results/job-2023-05-02T22.51-937ec5b/test-results/1-_bin_true/stdout' (0.00 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /mnt/local/results/job-2023-05-02T22.51-937ec5b/results.html
JOB TIME   : 2.69 s
```
while after this fix we finally get
```
[root@c5 site-packages]# avocado run --status-server-disable-auto --spawner=lxc -- /bin/true
JOB ID     : …
```
> Restore LXC spawner task output path handling

- Makefile
- selftests/check.py
- selftests/functional/basic.py
- selftests/functional/plugin/runners/exec_test.py
- selftests/functional/serial/requirements.py
Some avocado selftests leave results in tmp directory. This is caused by wrong inheritance order when test class inherits from Test and TestCaseTmpDir classes. This PR fixes it.
> selftests tmp dir cleanup fix

- avocado/plugins/runners/avocado_instrumented.py
avocado-instrumented tests send periodic "runnning" messages if no other events are occurring.  The implementation of this is quite convoluted, involving two variables with very long, but nonetheless cryptic names.
Replace this with a simplified implementation, using a single variable to indicate when the next running message should be sent
> avocado-instrumented: Simplify implementation of status messages

- avocado/utils/network/hosts.py
A regression bug was introduced by 94fb7a8,which results Host's subclass LocalHost can not be instantiated. Existing instantiation methods the same as "localhost = LocalHost()" will no longer fail after changed.
ID:2219366
Signed-off-by: Lei Yang <leiyang@redhat.com>
> utils.network.hosts: Make subclass of Host instantiable

- avocado/core/utils/loader.py
This fixes a condition on the test loader for avocado-instrumented, in which it can fail to load module from correct path.
More on https://github.com/avocado-framework/avocado/issues/5686
> Test file import versus system module

- avocado/utils/cpu.py
1.By using the get() method to obtain matching patterns, it avoids using try exception to capture KeyError exceptions. 2.Immediately return the result after finding the version number to avoid unnecessary iteration. 
3.Use an empty string as the default return result to avoid returning None
> CPU: Optimizing the Method of Obtaining CPU Version Information

- avocado/utils/cloudinit.py
The rstrip() method removes slashes at the end of the path string instead of slicing
Move the assignment to self.server.instance_phoned_back inside the conditional statement to avoid unnecessary judgment.
> The rstrip() method removes slashes at the end of the path string instead of slicing

- .github/workflows/ci.yml
- avocado/core/loader.py
- optional_plugins/robot/setup.py
The imp module is no longer available on Python 3.12.  Besides enabling usage under Python 3.12, also works as a backport for a test file location import fix.
This also enables RPM builds under Fedora 39.
Reference: https://github.com/avocado-framework/avocado/issues/5686
Reference: https://bugzilla.redhat.com/show_bug.cgi?id=2220126
> avocado/core/loader.py: support Python 3.12 by using importlib

- .github/workflows/pr_announcement.yml
This is a new workflow which will add announcement about LTS release to every new PR. It is a good way how to inform community about merge rules during the LTS version preparations.
You can see the results of this workflow [here](https://github.com/richtja/avocado/pull/10)
> Github action PR announcemnt

- avocado/core/task/statemachine.py
- avocado/core/utils/messages.py
- selftests/functional/serial/requirements.py
This PR adds information about skipping test due to the missing
dependencies.
Before this PR:
```
avocado run /tmp/test.py
JOB ID     : b17da893039e9d2deb33445a277ed2da40739a0d
JOB LOG    :
/home/janrichter/avocado/job-results/job-2023-04-20T13.55-b17da89/job.log
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 1 | WARN 0 | INTERRUPT 0 |
CANCEL 0
JOB HTML   :
/home/janrichter/avocado/job-results/job-2023-04-20T13.55-b17da89/results.html
JOB TIME   : 2.20 s
```
After this PR:
```
avocado run /tmp/test.py
JOB ID     : b17da893039e9d2deb33445a277ed2da40739a0d
JOB LOG    :
/home/janrichter/avocado/job-results/job-2023-04-20T13.55-b17da89/job.log
(1/1) /tmp/test.py:PassTest.test: STARTED
(1/1) /tmp/test.py:PassTest.test: SKIP: Dependecies wasn't fulfilled.
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | …
```
> Dependencies weren't fulfilled fix

- docs/source/guides/contributor/chapters/how.rst
The modern workflow and features on GH makes up for most of the manual creation of PR versions. Still the current documentation still mandates the use of PR versions.
This updates it with a new (simplified) GH workflow.
Fixes: https://github.com/avocado-framework/avocado/issues/5738
> Improve Contributor's Guide: Drop requirement of PR versions

- .github/workflows/release.yml
- optional_plugins/varianter_pict/MANIFEST.in
- python-avocado.spec
- requirements-dev.txt
A small collection of fixes and cleanups related to build and packaging.
> Build and packaging fixes

- avocado/core/task/statemachine.py
- avocado/utils/process.py
This is a simple collection of fixes done while working on the statemachine and task killing support.
> Misc fixes

- .readthedocs.yaml
this configuration is required to keep building documentation on readthedocs.
> Add .readthedocs.yaml configuration

- avocado/utils/iso9660.py
Use os.pathsep instead of the hard coded path separator ':'. 
os.pathsep represents the path separator for the current operating system . 
Use os. path. isfile() instead of os. path. exists() to check if the given path is a file. 
This can avoid misjudging the directory as an executable file.
> Check execution file method optimization

- avocado/utils/path.py
When we are creating path with utils.path.init_dir method, we might get FileExistsError when part of this directory have already existed. This issue created failure of
`selftests.functiona.job_api_features:Test.test_runnable_output_dir` test. Let's set exist_ok to True to avoid FileExistsError.
https://download.copr.fedorainfracloud.org/results/packit/avocado-framework-avocado-5744/fedora-38-aarch64/06259385-python-avocado/builder-live.log.gz
> exist_ok in utils.path.init_dir

- avocado/core/job.py
- avocado/core/messages.py
- avocado/core/output.py
- avocado/core/utils/messages.py
- selftests/functional/output.py
- selftests/functional/streams.py
This commit addresses compatibility concerns by reverting the log message format of Avocado instrumented tests back to the 92LTS (Long-Term Support) version. By doing so, we ensure compatibility with the upcoming LTS version.
Reference: #5721
> Revert Avocado Instrumented Tests Log Message Format to 92LTS Version

- requirements-dev.txt
Add cryptography distribution. Without it, ansible plugin setup
will fail.
Signed-off-by: Sebastian Mitterle <smitterl@redhat.com>
> setup.py: Add dependency for ansible plugin 

- avocado/utils/network/hosts.py
Gets you a list of all hardware addresses for the
given host (local and remote)
> host.py: method to get all the mac addresses

- avocado/utils/kernel.py
Omitted the requirement for multiprocessing. CPU_ Call count() and use None as the default value for njobs. We will check if njobs is a positive number, and if so, link the '- j' option with its value and add it to make_ Args list. Then, based on the binary_ Determine whether to add 'deb pkg' to make based on the conditions of package and distribution name_ Args list. Finally, we use spaces to make_ Connect the strings in the args list and call the build. make() function to perform the build operation
> KERNEL: Optimize source code to build the kernel

- avocado/utils/cpu.py
added a new function to get revision value from /proc/cpuinfo file 
e.g. '0080' for Power10
Signed-off-by: Disha Goel disgoel@linux.ibm.com
> add function to get revision value

- avocado/utils/archive.py
Method _update_zip_extra_attrs optimization:
1. Remove excess assignments from dst
2. handle exceptions in adding files
> Method _update_zip_extra_attrs optimization

- avocado/utils/pci.py
Add the following pci utils:
1) unbind - unbind the driver from pci device.
2) bind - bind the driver to pci device.
3) get_vendor_id - get the vendor id of pci device. 
4) reset - remove pci device in pci devices list in the system. 
5) rescan - rescan the system for pci device.
6) reset_check - check if reset of pci device is successful. 
7) rescan_check - check if rescan of the system for pci device is successful.
8) get_iommu_group - returns the iommu group of pci device. 
9) change_domain - change iommu domain of pci device 
10) change_domain_check - check whether whether change_domain is successful.
> Add some pci utils in avocado framework

- examples/jobs/failjob.py
Use of `Job(config=conf)` met `Unable to resolve any reference or "resolver.references" is empty.`. I think this may not as expected.
Before this fix:
After this fix:
> failjob.py: fix wrong usage of Job API.

- avocado/plugins/runners/avocado_instrumented.py
- selftests/functional/plugin/runners/avocado_instrumented.py
This will remove unsystematic timeout inside avocado-instrumented runner. This timeout has been set to 24 hours and users haven't had a way how to change it. Because we solved problems with `task.timeout.running` in #5383 and `job-timeout` in #5295 this default timeout is not needed anymore. After this change, the users will have more power over timeouts and will be able to run instrumented tests longer than 24 hours.
Reference: #5394
> Avocado-instrumented default timeout removal

- docs/source/guides/contributor/chapters/plugins.rst
- docs/source/guides/contributor/chapters/runners.rst
- docs/source/guides/user/chapters/advanced.rst
- docs/source/guides/user/chapters/configuring.rst
- docs/source/guides/user/chapters/datadirs.rst
- docs/source/guides/user/chapters/dependencies.rst
- docs/source/guides/user/chapters/installing.rst
- docs/source/guides/user/chapters/introduction.rst
- docs/source/guides/user/chapters/operations.rst
- docs/source/guides/user/chapters/plugins.rst
- docs/source/guides/user/chapters/results.rst
- docs/source/guides/user/chapters/tags.rst
- docs/source/guides/writer/chapters/writing.rst
- examples/tests/tags.py
- selftests/functional/list.py
- selftests/unit/tags.py
Updates to documentation in `Avocado User’s Guide` section to respects
the latest changes.
Reference: https://github.com/avocado-framework/avocado/issues/5757
> Doc fixes before LTS - Avocado User’s Guide

- avocado/core/test.py
- selftests/functional/output.py
- selftests/unit/test.py
Because of nrunner architecture, it is no need to save whiteboard by Test class. All logs which have to be stored to files are transmitted by messages and stored by avocado core. Whiteboard logs had been stored by Test class and avocado core, which created duplicates in whiteboard file. Removing it from Test class solves this issue. And we can do it because saving of whiteboard by Test class is legacy behavior.
Reference: #5770
> Whiteboard save removed from Test class

- avocado/plugins/runner_nrunner.py
- selftests/functional/plugin/runner_nrunner.py
When user sets only one of the status server values (uri, listen) Then the avocado will stop working because it will listen on different uri than the messages will be sent. This change will synchronize these values if the user sets only one of them.
Reference: #5740
> status server uris sync up

- docs/source/quickstart/index.rst
Updates to documentation in `Welcome to avocado` section to respects the latest changes.
Reference: #5757
> Doc fixes before LTS - Introduction section

- avocado/utils/ssh.py
- examples/apis/utils/ssh_timeout.py
This uses the remote side "timeout" command to implement a timeout for the actual command the user intends to run.  The arguments given are the simplest possible to be made compatible with "timeout" implementations such as the ones given by busybox.
While it's not possible to have a functional test at this point (because the test would need a second and properly configured machine), the example API script should serve as a proof that this implementation behaves correctly:
$ python3 examples/apis/utils/ssh_timeout.py
10.571667929994874
1.4050129299866967
---
This is a follow up to https://github.com/avocado-framework/avocado/pull/5654
> avocado/utils/ssh.py: add timeout functionality

- avocado/utils/download.py
The log message of avocado.utils.download.url_open() might be misleading because it tells that a URL has been retrieved at a stage where only a response was obtained. This commit will update the message to be more precise.
Reference: #5742
> avocado.utils.download.url_open() log message update

- avocado/utils/cpu.py
Added lscpu command to get values of core, physical sockets, physical chips and chips, this can be extended to get other values related to lscpu.
Signed-off-by: Krishan Gopal Saraswat <krishang@linux.vnet.ibm.com>
> lscpu command added as a function

- avocado/plugins/jobs.py
>  Improve Avocado jobs command

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Makefile.gh
- optional_plugins/ansible/setup.py
- optional_plugins/varianter_pict/setup.py
- optional_plugins/varianter_yaml_to_mux/setup.py
This PR adds twine check for each package, before publishing it.
With this change, we will avoid problems with publishing the packages in
the future.
Reference: https://github.com/avocado-framework/avocado/issues/5713
> Twine check for release

- docs/source/guides/writer/chapters/libs.rst
- docs/source/guides/writer/chapters/logging.rst
- docs/source/guides/writer/chapters/parameters.rst
- docs/source/guides/writer/chapters/writing.rst
- docs/source/guides/writer/libs/gdb.rst
Updates to documentation in `Avocado Writer’s Guide` section to respects the latest changes.
Reference: #5757
> Doc fixes before LTS - Avocado Writers’s Guide

- avocado/core/output.py
Yours truly happens to use the "kitty" terminal emulator, and would love to get the same treatment from Avocado.
> output: support for kitty

- avocado/plugins/spawners/podman.py
This is a collection of small improvements and one fix to a race condition, where the state of the container (and thus the task) would not take into account the transition from "created" to "running".
> Podman Improvements

- .github/workflows/weekly.yml
- examples/plugins/tests/magic/avocado_magic/resolver.py
- examples/plugins/tests/magic/avocado_magic/runner.py
- examples/plugins/tests/magic/setup.py
- setup.py
This will enable all example plugins for new test types during development mode.  The benefits are:
1) bit rot or bad examples are avoided when the plugins are enabled (as can be seen in the description fix for the magic plugin)
2) example plugins can be used in self tests
> Example plugins for test types: enable them during development mode

- avocado/core/utils/messages.py
- selftests/functional/output.py
This commit will re-enable 'avocado.test.stdout' and 'avocado.test.stderr' streams in avocado-instrumented tests and updates appropriate tests to avoid this bug in the future.
Reference: #5779
> 'avocado.test.stdout' and 'avocado.test.stderr' streams fix

- .github/workflows/ci.yml
- .github/workflows/release.yml
- contrib/scripts/avocado-fetch-eggs.py
- requirements-dev.txt
- setup.py
This adds support for testing the coverage of Avocado under Python 3.12, and advertises it as supporting it.
xmlschema is bumped to a version that supports Python 3.12, but left as is on older Python versions.
---
`setuptools` installation handling is required by https://github.com/python/cpython/issues/95299
> Add support for Python 3.12

- avocado/core/__init__.py
- avocado/core/plugin_interfaces.py
- avocado/core/status/repo.py
- avocado/core/task/statemachine.py
- avocado/plugins/spawners/lxc.py
- avocado/plugins/spawners/podman.py
- avocado/plugins/spawners/process.py
- examples/plugins/tests/rogue/avocado_rogue/__init__.py
- examples/plugins/tests/rogue/avocado_rogue/resolver.py
- examples/plugins/tests/rogue/avocado_rogue/runner.py
- examples/plugins/tests/rogue/setup.py
- selftests/functional/plugin/spawners/process.py
- selftests/unit/plugin/spawner.py
While "terminating a task", Avocado would simply request the termination, without checking on its success.  This change alters the interface of the terminate_task Spawner plugin interface when it comes to the expected return.
Then the statemachine is able to, at the very least, log the information about the failure to terminate a task.
Reference: https://github.com/avocado-framework/avocado/issues/4994
> Spawner: make terminate_task return success or failure

- optional_plugins/html/avocado_result_html/templates/results.html
- optional_plugins/html/avocado_result_html/templates/style.css
I think test results make a greater impression if they are colored RED and GREEN. Here is my hacking around to add it to the HTML output. Never used jinja before, let me know if this approach is correct.
> optional_plugins/html: color test results

- optional_plugins/ansible/setup.py
- requirements-dev.txt
Based on the Dependabot the cryptography has two minor security alerts which can be solved by upgrading the version. Because the cryptography package is dependency only for Ansible plugin, this commit will move it the plugin setup.
Reference: https://github.com/avocado-framework/avocado/pull/5769
> Bump cryptography to avoid security alerts

- avocado/core/output.py
Add color support for the terminal I happen to use. Also, sort the entries to prevent duplicates in the future.
> output: support for rxvt-unicode

- optional_plugins/robot/setup.py
robot framework doesn't support python3.7 in newer versions. Let's add requirements restrictions for robot plugin on python3.7
Reference: #5798
> robot compatibility for python3.7

- avocado/plugins/jobs.py
The JSON results file stores the number of tests ended with ERROR in the "errors" key.
> avocado jobs show: fix retrieval of ERROR

- scripts/external_runner.py
the external_runner uses the old import path for Runnable. This path has been changed when the legacy runner was removed. This PR fixes that to avoid ImportErrors.
Reference: #5370
> external_runner import error fix

- avocado/plugins/spawners/process.py
Because a task (usually a test) can simply finish by itself, either before a TERM or between a TERM and a KILL, it's important to protect against the process not existing anymore.
File "/Users/runner/work/avocado/avocado/avocado/plugins/spawners/process.py",
line 87, in terminate_task
runtime_task.spawner_handle.process.kill()
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/subprocess.py",
line 143, in kill
self._transport.kill()
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_subprocess.py",
line 153, in kill
self._check_proc()
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_subprocess.py",
line 142, in _check_proc
raise ProcessLookupError()
The following is an exercept from a …
> Process Spawner: protect against races between TERM and KILL

- avocado/utils/cpu.py
- selftests/unit/utils/cpu.py
- selftests/unit/utils/cpu.py.data/s390x_4
Add recent z16 model. Without this tests on z16
will end with a warning.
Signed-off-by: Sebastian Mitterle <smitterl@redhat.com>
> utils/cpu: add z16 on s390x

- avocado/core/test.py
Avocado fails to build with Python 3.13.0a1, due to:
ModuleNotFoundError: No module named 'pipes'
This is a simple fix, as the function under the pipes module has really been an import from the shlex module for a while.
Reference: https://docs.python.org/3.13/whatsnew/3.13.html#whatsnew313-pep594
Reference: https://bugzilla.redhat.com/show_bug.cgi?id=2244836
Reference: https://bugzilla.redhat.com/show_bug.cgi?id=2250847
> Python 3.13 enablement

- .github/workflows/ci.yml
- avocado/core/resolver.py
- avocado/plugins/list.py
- docs/source/guides/contributor/chapters/plugins.rst
- examples/plugins/tests/magic/avocado_magic/resolver.py
- examples/plugins/tests/magic/avocado_magic/runner.py
- selftests/functional/resolver.py
This commit introduces a new type of resolution result for resolver. It adds the ability for resolvers to inform the user about files which might be a test, but there is something wrong inside them.
If the resolver marks the reference as corrupted, the avocado will write a warning message to the user about it.
Reference: #5710
> corrupt resolution result

- .github/workflows/ansible.yml
- .github/workflows/ci.yml
- selftests/functional/serial/requirements.py
Because Fedora 36 is at the end of its life-cycle the public package repositories has been removed, because of this change our CI is failing. Let's update the used Fedora images to 38.
Reference: https://github.com/avocado-framework/avocado/actions/runs/6979871118/job/18993993584?pr=5804
> Fedora CI update from 36 to 38

- avocado/core/task/statemachine.py
- avocado/core/test.py
- selftests/.data/test_statuses.py
- selftests/functional/statuses.py
When avocado-instrumented test is interrupted, the avocado runner will call a tearDown method to clean the test environment. If some error is raised during the tearDown phase, the `INTERRUPTED` status is overwritten by this error. This is not desired behavior, because the reason for the error was interruption of the test. This fix keeps logging of the tearDown error without change of the `INTERRUPTED` status.
Reference: #5801
> INTERRUPTED status overwrite fix

- avocado/utils/cpu.py
Add support to get VA address size in bits from /proc/cpuinfo.
$ cat /proc/cpuinfo
.............
.............
address sizes   : 48 bits physical, 48 bits virtual
.............
Here, 48 bits virtual => VA address size in bits
> utils/cpu: Add utility to get VA address size in bits

- .readthedocs.yaml
Avocado itself is not being installed with the current readthedocs configuration, while the devel requirements are.
> readthedocs.org: install Avocado instead of devel requirements

- avocado/core/test.py
- docs/source/guides/writer/chapters/writing.rst
- examples/tests/timeouttest.py
- selftests/functional/basic.py
This introduces a "timeout factor", basically another parameter that Avocado Instrumented tests will respect that will be used to alter the actual timeout.
The reason for this feature is the fact that tests are coded with timeouts, but, their actual needed timeouts will depend on the environment they are running on.  It's not OK to expect the test code to be modified when the environment changes significantly for an execution of the tests (say on faster or slower CPUs or networks).
> Avocado Instrumented Test: introduce a multiplier for the timeout

- .readthedocs.yaml
- avocado/core/dispatcher.py
- avocado/core/plugin_interfaces.py
- avocado/core/task/runtime.py
- avocado/core/utils/messages.py
- avocado/utils/cpu.py
- avocado/utils/external/gdbmi_parser.py
- avocado/utils/network/interfaces.py
- avocado/utils/pci.py
- avocado/utils/podman.py
- avocado/utils/software_manager/backends/rpm.py
- avocado/utils/software_manager/backends/yum.py
- avocado/utils/software_manager/backends/zypper.py
- docs/source/blueprints/BP003.rst
- docs/source/blueprints/BP005.rst
- docs/source/blueprints/template.rst
- docs/source/conf.py
- docs/source/guides/contributor/chapters/plugins.rst
- docs/source/guides/reference/chapters/runners.rst
- docs/source/guides/writer/chapters/writing.rst
- docs/source/plugins/index.rst
- docs/source/releases/53_0.rst
- docs/source/releases/59_0.rst
- docs/source/releases/61_0.rst
- docs/source/releases/71_0.rst
- docs/source/releases/84_0.rst
- docs/source/releases/95_0.rst
- docs/source/releases/lts/69_0.rst
- docs/source/releases/lts/92_0.rst
This PR fixes Sphinx warnings and errors in our documentation and adds static tests to avoid those problems in the future.
Reference: https://github.com/avocado-framework/avocado/issues/5757
> Sphinx warnings and errors fix

- optional_plugins/html/avocado_result_html/templates/avocado_html.js
This is an update of status filter in HTML results to correspond with the latest changes in a63423b, which introduced colored statuses.
Reference: #5828
> HTML results status filter fix

- avocado/core/job.py
- avocado/core/utils/messages.py
- docs/source/guides/writer/chapters/writing.rst
- selftests/check.py
- selftests/functional/basic.py
Some functional tests have been masked out due to a safeloader behavior
from https://github.com/avocado-framework/avocado/issues/5817. This commit fixes this problem by changing the tests classes
from unittests to avocado instrumented, where it is needed. Also, it
adds warning to avocado documentation about this behavior.
Reference: https://github.com/avocado-framework/avocado/issues/5817
> Selftest refactoring to fix masked tests 

- selftests/unit/nrunner.py
On Python 3.12 and later (introduce in commit 76632b836), the message given when no tests are run is more precise and verbose.  Let's adapt the nrunner selftest to take that into consideration.
> Python unittest skip messages on 3.12 and later

- docs/source/guides/contributor/chapters/contact.rst
- docs/source/guides/contributor/chapters/how.rst
Since avocado IRC channel is not operational anymore, we need to remove it from our contact info.
> IRC channel doc removal

- docs/source/guides/writer/chapters/writing.rst
This commit adds links to test API, which describes the functionality of `Test.basedir` and `Test.workdir`. This change will help users to better understand what are these variables for.
Reference: #5639
> Better description of Environment Variables in doc

- docs/source/guides/writer/chapters/writing.rst
This commit adds simplewarning.sh test example to doc to show users how BASH extensions can look like in avocado.
Reference: #5640
> Add simplewarning.sh example to doc

- avocado/utils/distro.py
Add CentOS Stream to distro util
Reference: #5667
> Add CentOS Stream to distro util

- optional_plugins/robot/setup.py
Robot framework version 7 is in pre-release, and has different behavior that our plugin is not really validated with.
Let's pin it to require a version 6.x only.
> Robot Framework Plugin: pin compatibility with series 6

- Makefile.gh
- optional_plugins/spawner_remote/MANIFEST.in
- optional_plugins/spawner_remote/setup.py
Without this, building packages (such as wheels) will fail for the plugin.
> optional_plugins/spawner_remote: add missing manifest to include VERSION

- .readthedocs.yaml
- docs/Makefile
- docs/source/.include/helpus.rst
- docs/source/conf.py
- docs/source/guides/contributor/chapters/environment.rst
- docs/source/guides/contributor/chapters/how.rst
- docs/source/guides/contributor/chapters/plugins.rst
- docs/source/guides/contributor/chapters/results.rst
- docs/source/guides/contributor/chapters/rfc.rst
- docs/source/guides/contributor/chapters/styleguides.rst
- docs/source/guides/user/chapters/concepts.rst
- docs/source/quickstart/index.rst
- requirements-doc.txt
This is part of https://github.com/avocado-framework/avocado/issues/5757.
> Contributor guide review

- avocado/core/__init__.py
- avocado/core/settings.py
- docs/source/plugins/index.rst
- docs/source/plugins/standard/distro.rst
- man/avocado.rst
This is a collection of updates to the man page in preparation for the 103.0 LTS release.
Fixes: #5050
> Man page updates

- optional_plugins/golang/avocado_golang/runner.py
- optional_plugins/html/README.rst
- optional_plugins/varianter_cit/README.rst
- optional_plugins/varianter_pict/README.rst
Fixes: https://github.com/avocado-framework/avocado/issues/5757
> Optional plugins review for 103.0 LTS

- docs/source/plugins/index.rst
- docs/source/plugins/optional/spawner_remote.rst
- optional_plugins/spawner_remote/README.rst
- optional_plugins/spawner_remote/setup.py
This Documents some crucial steps for a new user of the remote spawner plugin.
Reference: https://github.com/avocado-framework/avocado/issues/5838
> Add a quick guide for setting up the remote spawner

- avocado/plugins/runner_nrunner.py
- man/avocado.rst
A simple fix of for the help message of the --status-server-uri command line option.
> Status server help message fix

- avocado/utils/network/interfaces.py
This patch includes the fix for "ERROR: 'CmdResult' object has no attribute 'decode'".
Run logs
-------------
without patch 
--------------------
ltcden4-lp12:~/avocado-fvt-wrapper/tests/avocado-misc-tests/io/net # avocado run irqbalance.py -m irqbalance.py.data/irqbalance_network.yaml --max-parallel-tasks=1
JOB ID     : 289cf143a056fa246812f6e8ed20db603beedd65
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2023-12-30T06.19-289cf14/job.log
(1/4) irqbalance.py:irq_balance.test_irq_balance;run-41ce: STARTED
(1/4) irqbalance.py:irq_balance.test_irq_balance;run-41ce: ERROR: 'CmdResult' object has no attribute 'decode' (4.32 s)
(2/4) irqbalance.py:irq_balance.test_cpu_serial_off_on;run-41ce: STARTED
(2/4) irqbalance.py:irq_balance.test_cpu_serial_off_on;run-41ce: ERROR: 'CmdResult' object …
> Patch to rectify the attribute decode issue.

- avocado/core/plugin_interfaces.py
- avocado/core/spawners/mock.py
- avocado/plugins/human.py
- avocado/plugins/runner_nrunner.py
- avocado/plugins/spawners/lxc.py
- avocado/plugins/spawners/podman.py
- avocado/plugins/spawners/process.py
- optional_plugins/spawner_remote/avocado_spawner_remote/__init__.py
- selftests/check.py
- selftests/functional/basic.py
- selftests/functional/plugin/spawners/podman.py
This adds a new mandatory method to spawners: is_operational().  The goal of this method is to signal to the execution of the test suite whether the spawner is fully set up and capable to operate.  This will of course, depend on the spawner implementation and requirements.
In the case of the podman spawner, often times jobs configured to use that spawner will succeed, when they actually need to signal a failure.  This is what happens on a system without a working podman installation:
```
JOB ID     : daf6869a348f14c52460adc6f18f89f35f8d6ecd
JOB LOG    : /root/avocado/job-results/job-2023-04-14T20.57-daf6869/job.log
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 1 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 0.32 s
[root@22d3a3b15197 ~]# echo $?
0
```
Clearly, test workflows depending on …
> Spawner: require runtime operation suitability

- contrib/scripts/avocado-fetch-eggs.py
The ``contrib/scripts/avocado-fetch-eggs.py`` file, as can be seen in PR https://github.com/avocado-framework/avocado/pull/5789, has a TODO to have the special handling after 103.0 is released.
This is a removal of that special handling, and a couple of extra improvements.
> Remove special egg handling for 103.0

- optional_plugins/html/tests/html_result.py
- selftests/functional/output.py
The tmpfile.mktemp function for creating tmp files has been deprecated since 2.3 and has security issues. Let's remove it and use tmpdir instead.
Reference:
https://github.com/avocado-framework/avocado/security/code-scanning/278
> Insecure temporary file removal

- .github/actions/egg/action.yml
- .github/actions/version/action.yml
- .github/workflows/ci.yml
The "version" and "egg" tasks are not effectively setting the container image that should be used.  This effectively means that instead of covering a number of different platforms, it's re-running the same checks on the base OS given in the "runs-on" setting.
These container images for the different OSs may use either DNF or APT as a package manager, and may or may not have Python or setuptools. In theory:
* it should be a matter of setting the "container" and then "image" directives on the GitHub actions YAML
* have a common script that conditionally installs the needed packages
In practice, GH Actions is terminating the execution of the script given in "run" when it has conditionals in varied ways:
* fedora:37 Run if python3 -c "import setuptools"; then Traceback (most recent call …
> CI: fix use of different OS images for egg and version tasks

- avocado/core/jobdata.py
- avocado/core/settings.py
- selftests/check.py
- selftests/functional/replay.py
- selftests/functional/settings.py
This commit introduces `AvocadoConfigParser` which uses `configparser.ConfigParser` to parse INI files with avocado configuration. During the parsing process, it preserves the config files path, which is used for creating error messages when the files are badly formatted. And it removes the `config` file from jobdata directory since it is not used anymore.
Before this PR:
```
...
File "<unknown>", line 2
foo moo
^^^
SyntaxError: invalid syntax
```
After this PR:
```
...
raise SyntaxError(
SyntaxError: Syntax error in config file ../testing/config, please check the value ["CANCEL", "SKIP", "FAIL"]
foo moo
```
Reference: #5857 #5643
> AvocadoConfigParser

- avocado/core/nrunner/task.py
- selftests/check.py
- selftests/functional/nrunner.py
This commit adds error handling to TaskStatusService. When the
connection is lost, it will try to establish a new connection. If the
connection is not possible to renew, the task will send warning message
about new status and remove TaskStatusService from available services.
Reference: https://github.com/avocado-framework/avocado/issues/5794
> TaskStatusService connection lost fix 

- avocado/core/test.py
The runner_queue property of avocado.Test (and related methods and attributes) is used by the legacy runner only.
This is a change in the core test API, but as can be seen from the fact that the latest LTS release (103.0) does not ship with the legacy runner, it's an interface that is not used and produces no effect. Thus, it can and should be removed.
Fixes: https://github.com/avocado-framework/avocado/issues/5340
> avocado.Test: remove runner queue

- avocado/utils/data_structures.py
1.The extend() method was used to add the entire range of values at once, rather than adding them one by one. This can reduce the number of loops and the creation of temporary lists
> Method for optimizing data structure functions

- docs/source/releases/index.rst
- docs/source/releases/next.rst
This PR adds a new `next.rst` file to our release docs. This file can be
used to write release notes during the sprint based on main changes.
> Release next.rst

- avocado/core/__init__.py
- selftests/check.py
- selftests/functional/basic.py
The "SIMPLE" test is a legacy runner terminology, and while most of its features were migrated to "exec-test", theses simpletest.* settings were not.
Let's drop the settings and a test which currently accomplishes nothing.
> Remove simpletest.* settings

- avocado/plugins/spawners/podman.py
The podman spawner will create images with requirements so that they can be reused by other tests.  But those images won't have any meaningful tags associated with them.  That is, users doing a "podman images" command will only see "<UNKNOWN>".
With this change, a somewhat meaningful description is attempted to be used as tag.
> Podman Spawner:  tag created images with meaningful names

- avocado/core/safeloader/docstring.py
/avocado/avocado/core/safeloader/docstring.py
Removing the extra set() function calls
may improve performance slightly
> /avocado/avocado/core/safeloader/docstring.py remove additional set() function calls

- avocado/utils/disk.py
Modify avocado/utils/disk.py:change get_disks(),Exception handling should be added when invoking external commands to handle possible command execution failures or exceptions.
> Exception handling should be added when invoking external commands to handle possible command execution failures or exceptions.

- avocado/utils/cpu.py
get_family utility update for amd x86_64 arch to return with family details Add util for x86_64 arch to get model number
Add Util to get amd zen info
Signed-off-by: Ayush Jain <ayush.jain3@amd.com>
> Add utils for amd cpu

- .github/workflows/ansible.yml
- .github/workflows/ci.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/setup.yml
- .github/workflows/weekly.yml
According to GH, we must update the version of used actions due to deprecations of Node.js 16.  Message given is:
Node.js 16 actions are deprecated. Please update the following
actions to use Node.js 20: actions/checkout@v3,
actions/setup-python@v4, actions/upload-artifact@v3.
Reference: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> GH Actions: mass update of action versions

- docs/source/guides/user/chapters/concepts.rst
This improves a bit the section that presents the basic Avocado concepts to users.
> User Guide: improve section on Avocado's basic concepts

- .github/workflows/release.yml
This PR fixes some issues which were found during the 104 release.
1.  Adds Avocado bot token, to reduce the dependency of the release on @clebergnu's private tokens.
2.  Fixes the issues with setuptools on python 3.12.
> Release workflow updates

- selftests/.data/unittests.py
- selftests/.data/whiteboard.py
- selftests/functional/serial/requirements.py
- selftests/unit/utils/diff_validator.py
The tests modified here are not supposed to be executables, and thus, should not shebangs and/or main() calls.
> Selftests: remove shebangs and main() calls

- selftests/modules-boundaries.sh
It adds module boundary check for importing avocado plugins inside avocado core. Avocado plugins can be dependent on avocado core features, but it can't be the other way. This check will ensure that.
> Module boundaries check for plugins in avocado.core

- avocado/utils/cpu.py
This patch adds support for getting number of physical cores present in a lpar from lscpu. 
This is useful for running perf 24x7 events which requires this value with domain parameter.
> avocado/utils/cpu.py: add getting physical core from lscpu

- avocado/core/__init__.py
- avocado/core/nrunner/runnable.py
- avocado/plugins/runners/exec_test.py
- docs/source/guides/writer/chapters/basics.rst
- docs/source/guides/writer/chapters/writing.rst
- selftests/check.py
- selftests/functional/basic.py
This PR adds more control over the environment variables in exec-tests for users. It brings a way how to disable one env variable or clear the whole environment during the test runtime so it won't be available to test script.
> Extended environment variable control

- avocado/utils/vmimage.py
- docs/source/quickstart/index.rst
- selftests/pre_release/tests/cirrusci.py
- selftests/pre_release/tests/vmimage.py.data/variants.yml
- selftests/unit/utils/test_vmimage.py
This is a collection of fixes to make the pre-release job pass for the upcoming 92.2 (LTS) release.
Example of a successful run can be seen [here](https://github.com/clebergnu/avocado/actions/runs/8886671894/job/24401579237).
Reference: https://github.com/avocado-framework/avocado/issues/5899
> Pre-release job fixes for 92.2

- avocado/utils/disk.py
1- added a utility which Returns io scheduler available for the IO Device
2-Added utility in disk library help to Set io scheduler to a device
> Add couple  utility in disk utility

- selftests/functional/basic.py
The store_logging_stream_external test installs external package matplotlib and checks with the package properly logs to the avocado directories. Unfortunately, this test used hardcoded line number of matplotlib. Because of this, the test started failing when the line was changed. This commit fixes this test by using regex instead of hardcoded string. After this change, the test should be protected against external changes in matplotlib package.
> store_logging_stream_external test fix

- avocado/utils/kernel.py
In the setuptools>=70 the `pkg_resources` is deprecated and some of its features might cause troubles. These changes have impact on avocado CI with python3.12. This commit uses directly the `packaging` package instead of `pkg_resources` which solves the CI issues.
Reference:
https://setuptools.pypa.io/en/stable/pkg_resources.html#package-discovery-and-resource-access-using-pkg-resources
The CI failures can be seen [here](https://github.com/avocado-framework/avocado/actions/runs/9279694152/job/25532776722?pr=5941#step:10:2529).
> cannot import name 'packaging' from 'pkg_resources' fix

- avocado/utils/cpu.py
When I use the cpu.lscpu() function, I find that I get an empty dict result, which is not as expected. When I checked, I found that the reason is that the default language of my system is not English, so I made this change.
I have tested that this language setting only works in the current pipeline and have found no other effects.
Hope to adopt.
> Modify cpu.py - Improve robustness 

- avocado/plugins/list.py
- selftests/check.py
- selftests/functional/resolver.py
When using some of the new resolvers such as "runnable-recipe", there's no longer a 1:1 relationship that the resolver and the "kind" match.
Certain types of resolution may look fine from the perspective of the original resolver, while it may be a broken or invalid reference to a more apt (or canonical) resolver for its set "kind".
By listing the original resolver, users may be able to more easily identify what the discrepancy is and where it's coming from.
Reference: https://github.com/avocado-framework/avocado/issues/5924
> Show origin of resolution in verbose list

- avocado/core/suite.py
This is a removal of left over of legacy code. When avocado supported `legacy` and `nrunner` runners we also distinguished between resolver resolution and test load. When the `legacy` runner has been removed, we don't have this issue anymore, because resolvers are only supported implementation of test resolution. Unfortunately, we kept validation of supported runners during the test reference resolution with hardcoded `nrunner`. This is wrong because `nrunner` is a `SuiteRunner` plugin, and it can be replaced by any installed `SuiteRunner`.
Reference: #5954
> Hardcoded nrunner removal in TestSuite

- avocado/utils/vmimage.py
Fedora has moved versions 37 and 38 to archive, we need to update our scripts to reflect this change.
Reference:
https://github.com/avocado-framework/avocado/actions/runs/9442784424/job/26005494505
> vmimage fedora provider update

- .github/workflows/ci.yml
- .github/workflows/push_ci.yml
This commit adds the coverage CI job to a workflow which will be triggered on PR and after the push to the main branches `LTS` and `master`. This is needed because codeclimate needs coverage date from master to show the proper results.
> Coverage CI after push to master

- avocado/core/task/runtime.py
Just a refactor to reduce the size of the original method.
> avocado/core/task/runtime.py: refactor identifier generation

- .github/workflows/pr_announcement.yml
This PR changes the PR announcement message from hard coded text to env variable. Thanks to this, it will be possible to change the message in the repository settings without creating a new PR.
> PR announcement as env variable

- .coveragerc
- selftests/run_coverage
This PR is an update of Avocado coverage test. It fixes few issues which were discovered after #5944 has been merged.
> Coverage update

- .github/workflows/prerelease.yml
- .github/workflows/release.yml
This will re-enable uploads to pypi with usage of Trusted Publisher Management. It adds again commits from #5926 and #5886 which has been reverted in d069e11a782455f40a376020ed8d9946d67f29d3, 74777fa6cb238f79efe68ffb595cb256073fa66d and 94d6a6183c56f47203f9a352cb3995d70f164293. The only issue with this CI changes was in configuration of pypi and MR. Avocado bot and those have been fixed.
> PyPI upload update revert

- contrib/containers/ci/selftests/check-copr-rpm-version.docker
Fedora 38 has reached EOL, and COPR is not building packages for it by default.  Also, modularity is not something we are carrying forward on Fedora 40, so there's no need to disable the module.
> check-copr-rpm-version.docker: update OS to Fedora 40

- avocado/core/nrunner/runnable.py
- avocado/core/suite.py
- avocado/plugins/runner_nrunner.py
- selftests/check.py
- selftests/unit/nrunner.py
- selftests/unit/suite.py
This addresses a few different issues that in the end, result in the failure to set and apply a Runnable's identifier.
More specifically this:
* fixes a regression that was adding the entire Avocado configuration to every runnable
* makes sure the suite configuration is applied to runnables at suite creation time
* uses the actual configuration of a runnable to set build its identifier
> Runnable: fix job/suite config use and runnable identifier

- avocado/utils/linux.py
The function checks if secureboot is enabled or not from the OS side.
The command output of "lsprop /proc/device-tree/ibm,secure-boot" is used to check the OS status.
> Adding check if secureboot is enabled or not

- avocado/utils/process.py
Added exception handling for OSError that may be thrown by os.read
> Added exception handling for OSError that may be thrown by os.read

- avocado/utils/podman.py
1.Exception message improvement
Change the f "Failed getting information about container:" f "{container_id}." that concatenates two strings together to a single string to avoid unnecessary string concatenation 
2.Replace container ["Id"] with container. get ("Id") to avoid throwing KeyError when the "Id" key is missing in the dictionary
>  Method modification for obtaining container information

- avocado/utils/astring.py
Use a dictionary to store escaped characters and their corresponding escape forms. If you need to add new escape characters later, just add them to the dictionary
> Dictionary storage

- .github/workflows/release.yml
The build and upload eggs release workflow is using Mr.Avocado token, but this token has never been generated for this workflow, therefore it is not working. This commit adds the step with token generation, which will fix the issue.
I have tested it in my fork, and you can see the results [here](https://github.com/richtja/avocado/actions/runs/9889257014).
> Fix for upload binaries to release workflow

- avocado/core/settings.py
When there is an issue with syntax in avocado config file avocado won't provide enough information for the user to understand the problem. This commit will improve the error message by specifying the wrong value and the reason for syntax error.
before this commit:
```
SyntaxError: Syntax error in config file ./pom_config, please check the
value /build/avocado/data/cache
```
after this commit:
```
ValueError: /build/avocado/data/cache could not be converted into a list
During handling of the above exception, another exception occurred:
SyntaxError: Syntax error in config file ./pom_config, please check the
value /build/avocado/data/cache
```
Reference: #5906
> Better description of config syntax error

- avocado/utils/archive.py
- selftests/unit/utils/archive.py
There's value in making the zstd probe function public (which was previously not perceived).  This function can be used to skip/cancel tests when a suitable zstd is not found.
> avocado/utils/archive.py: make probe function for zstd public

- avocado/plugins/legacy/replay.py
- optional_plugins/varianter_yaml_to_mux/setup.py
The `logging.warn()` has been deprecated in python3.3, and it will be removed in python3.13. Let's use `logging.warning()` instead in avocado code.
Reference: https://docs.python.org/3.13/whatsnew/3.13.html
This is a fix for https://bugzilla.redhat.com/show_bug.cgi?id=2250847 and https://bugzilla.redhat.com/show_bug.cgi?id=2304322
> logging.warn() refactoring for 92lts

- contrib/containers/ci/selftests/check-copr-rpm-version.docker
- selftests/pre_release/tests/check-copr-rpm-version.sh
Fedora 38 has reached EOL, and COPR is not building packages for it by default.  Also, modularity is not something we are carrying forward on Fedora 40, so there's no need to disable the module.
Finally, a tag with the right COPR repo is being used for the container image.
> check-copr-rpm-version.docker: update COPR repo and OS to Fedora 40

- .github/workflows/prerelease.yml
- selftests/deployment/roles/common/tasks/main.yml
The COPR repos are building for the active Fedora, so let's bump that to version 40.  While at it, we will be using a version of ansible that has deprecated the "include" tag.  The error one gets is:
ERROR! [DEPRECATED]: ansible.builtin.include has been removed. Use
include_tasks or import_tasks instead. This feature was removed from
ansible-core in a release after 2023-05-16. Please update your
playbooks.
This updates the playbook to work properly under the matching ansible version.
> Deployment test: update to Fedora 40 and matching ansible

- avocado/core/tapparser.py
- avocado/plugins/runners/tap.py
- selftests/check.py
- selftests/unit/tap.py
This PR introduces support for TAP14 format. And few small fixes to tap runner. 
The main differences between TAP13 and TAP14 important for tap runner:
- Add child tests as 4-space indented TAP streams, with a trailing test point and leading comment line.
- Escaping of \ and # characters.
More info can be found in [TAP14 specification](https://testanything.org/tap-version-14-specification.html)
Reference: #5913
> Tap14 update

- optional_plugins/mail/avocado_result_mail/result_mail.py
Plugin was attempting SMTP connections regardless
of if the plugin config was using defaults.
Now checks on pre/post checks to stop attempted
SMTP connections before the plugin was disabled.
> Mail Results - Disable Plugin

- avocado/core/nrunner/runnable.py
- avocado/core/suite.py
- avocado/plugins/sysinfo.py
- examples/nrunner/recipes/runnable/noop_config.json
- selftests/check.py
- selftests/functional/resolver.py
- selftests/unit/runnable.py
- selftests/unit/suite.py
This change allows for the a runnable configuration and the suite and default configuration to coexist with the correct behavior.
In short, if the suite has a configuration, it will become the new default configuration for a runnable, while its own configuration will not be touched.
Fixes: https://github.com/avocado-framework/avocado/issues/5998
> Runnable and Suite configuration support

- avocado/utils/kernel.py
This is a fix of kerne utils compatibility issue with setuptools=>70 which has been introduced in df6b1da.
Reference: #5988
> Backwards compatibility for kernel utils module

- avocado/utils/asset.py
Using pathlib can make file path operations more object-oriented and easy to understand, and have better compatibility across different operating systems.
> Add exception handling to os.remove in the remove-asset-by_pathfang method of the avocado/utilities/asset.py file

- avocado/utils/nvme.py
we see the command output was not splittable and non iterable error. so fixed here for same.
> Fixing the command output not iterable error in nvme.py

- avocado/utils/network/interfaces.py
We need the RHEL10 distro release checking to be included for the avocado misc tests network test bucket to work as it had worked for RHEL9 distro release
> Adding support for RHEL10 distro release

- docs/source/guides/reference/chapters/avocado_instrumented.rst
- docs/source/guides/reference/index.rst
This commit adds a new chapter to the reference guide about avocado instrumented tests and its lifecycle.
Reference: #5995
> [Doc] Avocado instrumented lifecycle

- avocado/plugins/runners/tap.py
- docs/source/guides/user/chapters/concepts.rst
- docs/source/guides/user/chapters/logging.rst
- selftests/unit/plugin/runners/tap.py
This PR adds fixes for TAP runner to not hide failures when some tests are skipped. Also, it updates Avocado documentation to respect newest changes in TAP runner.
Reference: #6007
> Tap runner hides failures fix

- avocado/core/test.py
- selftests/check.py
- selftests/functional/basic.py
This commit is a fix for avocado-instrumented timeouts. When the tests are interrupted due to timeout during `setUp` or `tearDown` method, those tests would result in `ERROR` instead of `INTERRUPTED`. This commit updates the exception handling of this method to fix this issue.
Reference: #6013
> Avocado instrumented timeout in setUp and tearDown fix

- .github/workflows/prerelease.yml
The pre-release checks don't checkout avocado-static-checks submodule, which is mandatory for running static-check after 8639fdb. This is a fix for that.
It fixes failures in https://github.com/avocado-framework/avocado/actions/runs/11099769147/job/30834525300
Reference: 8639fdb
> pre-release tests with avocado-static-checks submodule

- selftests/check.py
- selftests/functional/utils/distro.py
While the standard "debian" container is not so easily suitable for being used in the existing functional tests for distros that run an Avocado job, the very standard "python" container is built on Debian and provides Python (of course).
This should serve to avoid regressions to the distro probes for Debian.
> Distro: add a functional test for Debian probes

- docs/source/releases/108_0.rst
- optional_plugins/ansible/setup.py
- optional_plugins/html/setup.py
This adds markupsafe<3.0.0 requirements to html plugin, because
markupsafe-3.0.0 can't be installed with older versions of setuptools on
RHEL9 and other systems because of `CCompilerError`.
Reference: https://github.com/avocado-framework/avocado/issues/6038
---
We have the same issue in our [CI](https://github.com/avocado-framework/avocado/actions/runs/11257807732/job/31302934938?pr=6039#step:6:431) and this PR should fix it.
> MarkupSafe fix

- .github/workflows/push_ci.yml
- codecov.yml
This is an update for avocado coverage workflow. It changes the coverage reporting tool from codeclimate to codecov since the codecov hasn't been reliable for some time. 
For now, the coverage check is set to `informational`. This means that we will get the reports, but the PRs won't be blocked by changes in coverage. I plan to change this when we make sure that this workflow is stable.
Reference: #6035
---
You can see the working coverage report in https://github.com/richtja/avocado/pull/23
> Coverage report with codecov instead of codeclimate

- avocado/utils/network/interfaces.py
when IP addresses are confiugred from a config file, the generic "ip flush" command does not removes the IP address and IP's will be remain intact.
when user wanted to remove all IP addresses of interface which user doesnot aware of it, this code will helps to find all the assigned IP addresses and removes it.
> Remove IPv4 Addresses of network interface.

- avocado/utils/network/interfaces.py
This is follow up of 66c549d9f.
Reference: https://pylint.pycqa.org/en/latest/user_guide/messages/warning/raise-missing-from.html
> lint: fix one outstanding raise-missing-from / W0707

- .codeclimate.yml
- docs/source/quickstart/index.rst
Since codeclimate check hasn't been accurate and often creates false positive, the positives of having such tool is much lower that the negative impact on PRs. Therefore, this PR removes all occurrences of codeclimate code from Avocado.
> Codeclimate removal

- .github/workflows/ci.yml
Github is depracating the MacOS 12 runner and it will be removed December 3rd. Let's do the update now to avoid any future trubles.
Reference: https://github.com/actions/runner-images/issues/10721
> MacOS update from 12 to 14 in CI

- selftests/unit/utils/cpu.py
The current mock method on the two tests modified here do not support the context manager pattern.  Let's use the standard library support for mocking open that supports it.
This is needed for future lint check improvements that will enforce the use of open() as a context manager to avoid leaking resources.
The test_set_idle_state_withsetstate() test has a significant change of behavior: one io.BytesIO instance was used for the writes that, in real life, would happen on two different files.  The proposed change brings a more realistic, with a single write to a single file (although it only checks half of the values now).  Still, I believe this is an improvement, including the extra check for the file that was actually written to.
Reference: …
> selftests/unit/utils/cpu.py: support the context manager pattern

- avocado/core/result.py
- avocado/core/settings.py
In https://github.com/avocado-framework/avocado/blob/3b1f5cbbb07ea850498b55aa020d74cc0f7fa15f/avocado/core/result.py#L103
The parameter description of 'test' does not match the parameter 'state'
and
Refactor: Remove unused 'option = None' initialization
Signed-off-by: mikigo <huangmingqiang@uniontech.com>
> Update check_test docstring to clarify state parameter

- avocado/core/resolver.py
- Removed the unused variable `hint_resolutions` from the `resolve` function.
- Directly used the dictionary comprehension to populate `hint_references` from `hint.get_resolutions()`.
- Simplified the logic by eliminating an unnecessary intermediate variable.
> Remove unused variable 'hint_resolutions'

- .github/workflows/release.yml
This will additionally display the updated text on pages like https://github.com/avocado-framework/avocado/actions/runs/11215982471.
Here's an example of how job summaries are displayed: https://github.com/ansible/awx-plugins/actions/runs/10793404435#summary-29935289633.
> Surface the release RTD link to GHA workflow summary page

- .github/workflows/release.yml
This patch will make the links on the UI of the [Deployments](https://github.com/avocado-framework/avocado/deployments/pypi) and workflow pages more accurate.
> Set release-specific URLs in PyPI publish jobs

- avocado/plugins/vmimage.py
- avocado/utils/vmimage.py
- selftests/check.py
- selftests/functional/plugin/vmimage.py
This commit adds a new option to `vmimage get` feature called `debug`. It brings possibility to run vmimage command in debug mode to get more detailed information about possible failures. In debug mode, all exceptions caused by vmimage utility will be raised to console. That should provide enough information for further debugging of possible issues.
Reference: #6051
---
`vmimage get` without debug:
```
$ avocado vmimage get --distro Fedora --distro-version 2 
The requested image could not be downloaded
```
`vmimage get` with debug:
```
$ avocado vmimage get --distro Fedora --distro-version 2 --debug
avocado.utils.vmimage: Version not available at https://dl.fedoraproject.org/pub/fedora/linux/releases/
The requested image could not be downloaded
```
> VMimage get --debug option

- avocado/core/resolver.py
- docs/source/guides/contributor/chapters/plugins.rst
- docs/source/guides/user/chapters/operations.rst
- man/avocado.rst
- optional_plugins/golang/README.rst
The message given by the avocado-instrumented and python-unittest resolvers, resolvers that share a lot of code and require Python files, can be made clearer.
One of the earliest checks performed is about the file *name* and its *suffix*, and not necessarily about an actual file (that exists). Even though the concepts are pretty close, let's make it clear that these resolvers are rejecting the references given based on the ".py" suffix not existing in the file name, and not necessarily, at that time, rejecting it based on an actual existing file.
> avocado-instrumented/python-unittest resolvers: improve fail message

- avocado/utils/kernel.py
- selftests/check.py
- selftests/unit/utils/kernel.py
This fixes two problems with the current version parse mechanism:
1. Recent setuptools' version parse function, which has dropped "LegacyVersion" support, raises an InvalidVersion exception for common kernel version info as presented by the system and returned by os.uname()
2. The import of the packaging module is broken on systems with no setuptools and only the "packaging" module.
This introduces a simple but custom version parse that solves both and simplifies dependencies.
Fixes: https://github.com/avocado-framework/avocado/issues/6058
> avocado.utils.kernel: fix kernel version parsing

- .coveragerc
- selftests/run_coverage
The test coverage of avocado gathered by coverage.py. It was not precise, because some of our functional tests were running in sub-processes where the coverage was not enabled. This change it adds `sitecustomize.py` to ensure that coverage will be enabled for all python processes which will run during coverage testing. After this change, the overall test coverage of avocado will increase from 54% to 68%
Reference: https://coverage.readthedocs.io/en/latest/subprocess.html
---
As an example of not working, coverage testing can be #6072. Where the coverage of new runner is 0 even tho the PR introduce its testing.
> Test coverage with multiprocessing fix

- optional_plugins/html/setup.py
- python-avocado.spec
- selftests/check.py
The sqlite3 module (and actually, even the non-python binary with the same name), have "interesting" limitations when it comes to the database path.
When the test that creates the journal file, and checks for it, runs as part of an RPM build, the extra directories (/buildir/...) exceed the path size limit.
While it would be possible to check if the "logdir" path, plus the name of the journal database path, would eventually exceed the sqlite3 limits, this logic would be exclusive for one test variant.
IMO it does not justify adding such logic to keep a test that has considerably low value.
> selftests: drop job-api test variant that may exceed sqlite3's own limits

- avocado/utils/vmimage.py
- selftests/check.py
- selftests/unit/plugin/vmimage.py
- selftests/unit/utils/vmimage.py
Updated the image pattern in FedoraSecondaryImageProvider to match the available Fedora image file names for the s390x architecture. This resolves the issue where the vmimage utility could not download the correct image due to a pattern mismatch.
Reference: https://github.com/avocado-framework/avocado/issues/6071
> Fix image pattern for FedoraSecondary provider on s390x

- avocado/plugins/jobs.py
Fix: Handle missing job data in 'avocado jobs list' command
- Updated 'handle_list_command' to use `job.get()` for safely accessing job data.
- If a key is missing, it now defaults to '<unknown>' instead of causing a crash.
- Refactored some code due to codeclimate suggestion.
Reference:      https://github.com/avocado-framework/avocado/issues/6067
> Avocado Jobs Keys

- avocado/plugins/list.py
- selftests/functional/list.py
Filtering now properly handles both verbose and non-verbose output modes while checking for tag matches.
without changing the existing behavior that users expect when using 'avocado list -t <tag>'
Reference:      https://github.com/avocado-framework/avocado/issues/6066
> Tags Filtering Fix

- optional_plugins/resultsdb/setup.py
The resultsdb-api uses urllib as dependency. The urllib dropped support for the python 3.8 in the version 2.3.0. Let's use older version of urllib to keep python 3.8 support for resultsdb plugin.
Reference:
https://urllib3.readthedocs.io/en/stable/changelog.html#deprecations-and-removals
---
This is a fix for CI failures like [this one](https://github.com/avocado-framework/avocado/actions/runs/12584819073/job/35075262308?pr=6072#step:6:915).
> resultsdb-api support on 3.8 fix

- .github/workflows/prerelease.yml
After the update in github CI runner the avocado install will fail with `Cannot uninstall jsonschema 4.10.3, RECORD file not found. Hint: The package was installed by debian.` This is caused by cached python packages in the runner. Running the pip as standalone app instead of a python module will fix this issue.
Reference:
https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20250105.1 https://github.com/avocado-framework/avocado/actions/runs/12706808734/job/35421314652#step:3:93
---
The working CI with the fix can be seen [here](https://github.com/richtja/avocado/actions/runs/12707646975/job/35422989338#step:3:1).
> avocado-pre-release pip install

- .github/workflows/ci.yml
- .github/workflows/release.yml
- contrib/scripts/avocado-fetch-eggs.py
- setup.py
This adds support for testing the coverage of Avocado under Python 3.13, and advertises it as supporting it.
https://github.com/avocado-framework/avocado/issues/6094
Successful CI Run Python 13: https://github.com/harvey0100/avocado/actions/runs/12882448559
Please let me know if the change inside of python-avocado.spec was required.
> Python 13 Support

- selftests/functional/basic.py
In the version 109 pip runner has been introduced. Lets use it instead of the ansible module in our selftests.
> PIP dependency in selftests

- examples/testplans/release/release.json
This is an update to release plan to reflect the latest changes in the release process.
> Release plan update

- avocado/core/test.py
- avocado/plugins/runners/avocado_instrumented.py
- examples/tests/external_logging_stream.py
- selftests/check.py
- selftests/functional/plugin/runners/avocado_instrumented.py
This commit changes the way how avocado instrumented runner handles test timeouts.  For timeout handling, we used to use signals and raising TestInterrupt error. Such solution has an issue that we can't control where in the code the Error will be raised, and it can be handled before it reaches the runner layer. More info about this issue in #6046.
This change removes the signal handling and uses threading instead. Now each test method will be run in a separated thread and this thread will be terminated if timeout is reached. This solution selves the raising error issue and keeps the current test lifecycle untouched.
Reference: #6046
> Avocado instrumented timeout handling in thread

- avocado/utils/distro.py
- selftests/unit/utils/software_manager.py
This fixes an issue with the Debian version information where it was retrieving a number instead of the codename.
This also fixes an issue where the version of Ubuntu was incomplete and it was retrieving only the first part of it, rather than the full version.
The unit test was failing on recent versions of Debian and Ubuntu because the `login` package is no longer installing the binary on `/bin/login` but rather on `/usr/bin/login`.
We have added a function which will retrieve the binary path depending on the distro as well.
Resolves: #6028
> Fix debian and Ubuntu version detection

- avocado/utils/vmimage.py
- selftests/unit/utils/vmimage.py
The URL pattern for downloading Fedora 40 VM images has been updated to match the format provided by the distribution. This ensures that the vmimage download functionality works correctly for Fedora 40 images.
> VMImage Fedora 40 URL

- optional_plugins/spawner_remote/avocado_spawner_remote/__init__.py
Fixes: https://github.com/avocado-framework/avocado/issues/6117
> optional_plugins: spawner_remote: add setup_timeout option for remote host setup hook

- avocado/utils/cpu.py
This commit enhances the CPU utility to support the Power11 processor by making pattern matching case-insensitive.
> utils/cpu: Add support for Power11 processor

- .github/workflows/ci.yml
- .github/workflows/prerelease.yml
- .github/workflows/push_ci.yml
- .github/workflows/release.yml
- .github/workflows/setup.yml
- .github/workflows/weekly.yml
This support of ubuntu-20.04 runner image will be removed in April 1,
2025. Let's update the runner to avoid any possible complications.
Reference: https://github.com/actions/runner-images/issues/11101
> CI runner update from ubuntu-20.04 to ubuntu-22.04

- .coveragerc
- avocado/plugins/runners/avocado_instrumented.py
- avocado/plugins/runners/python_unittest.py
This commit updates the coverage.py support in avocado. Currently, avocado was only covering lines which has been touched during the test runtime, but such solution omits lines which are used during imports. Because of this the coverage can be inaccurate, because it misses lines with method names, class names, imports etc. After this change the coverage reports are more accurate.
> Coverage.py during test load

- .github/workflows/ansible.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .packit.yml
- contrib/containers/ci/selftests/check-copr-rpm-version.docker
- contrib/containers/ci/selftests/fedora-40.docker
- contrib/containers/ci/selftests/magic.docker
- contrib/containers/fedora-40-latest-copr.docker
- docs/source/guides/contributor/chapters/environment.rst
- selftests/functional/utils/podman.py
Because Fedora 38 is at the end of its life-cycle let's update the used Fedora images to 41 before the public package repositories will be removed.
> Seltests / Containers / CI: Bump Fedora to 40

- avocado/core/status/server.py
Connection resets due to network instability can lead to the status server not catching a test status, an asyncio error like
```
full.log│2024-03-08 03:08:44,053 asyncio base_events      L1744 ERROR| Task exception was never retrieved                                                                                                                                  │
full.log│future: <Task finished name='Task-2038' coro=<StatusServer.cb() done, defined at /usr/lib/python3.10/site-packages/avocado/core/status/server.py:51> exception=ConnectionResetError(104, 'Connection reset by peer')>             ├
full.log│Traceback (most recent call last): …
```
> Handle connection resets in the status server more gracefully

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/weekly.yml
This is a refactoring of CI configuration which removes python minor version specification. After this change, the CI runner will always choose the latest available minor version in CI runner, and we will be able to catch possible errors in minor version changes.
> Latest available python in CI

- avocado/utils/data_structures.py
Added a check to initialize diff_btw_dict as an empty list if it is passed as None. This prevents AttributeError when trying to append differences to a None value.
Original PR link:[#6127 ]( https://github.com/avocado-framework/avocado/pull/6127)
> Fix bug in recursive_compare_dict: Initialize diff_btw_dict if None.

- avocado/utils/cloudinit.py
- selftests/check.py
- selftests/unit/utils/cloudinit.py
This is a set of tests for `avocado.utils.cloudinit` utility, with fixes found on the way, to prepare it for migration to Autils and increase its coverage.
> Cloudinit coverage

- .github/workflows/push_ci.yml
- .github/workflows/vmimage.yml
- selftests/run_coverage
The code coverage analysis was mostly focused on code coverage and the
actual test result wasn't taken under consideration. But with https://github.com/avocado-framework/avocado/commit/546fa49bfa87110faad697cceda324c8c0ee4847
the coverage testing is being used for testing vmimage related features,
therefore we need to change the code coverage script to return exit code
based on the test results to be consumed by CI.
> Test results during the code coverage

- optional_plugins/html/avocado_result_html/templates/avocado_html.js
Fixed issue where users couldn't click on column headers to sort data in the HTML report.
The problem was caused by the column resize handlers intercepting all click events.
Modified the code to only intercept clicks on the resizer element itself, allowing sorting clicks to work properly.
Reference: https://github.com/avocado-framework/avocado/issues/6134
> Enable column sorting in HTML report

- avocado/core/test.py
Previously, the filename API returned a relative path in Python ≤3.9 and an absolute path in Python ≥3.10, leading to inconsistency. This change standardizes the behavior to always return an absolute path, ensuring consistency across Python versions
Link: https://github.com/avocado-framework/avocado/issues/6144#issuecomment-2746929950
Signed-off-by: Ayush Jain <Ayush.jain3@amd.com>
> Ensure filename API Returns Absolute Path Using inspect.getabsfile()

- avocado/utils/linux.py
kernel.sched_schedstats is used to enable statistics of the Linux scheduler, these avocado utility help to do that
> Added utils function to enable kernel.sched_schedstats

- avocado/core/plugin_interfaces.py
- avocado/core/spawners/common.py
- avocado/plugins/plugins.py
- avocado/plugins/spawners/lxc.py
- avocado/plugins/spawners/podman.py
- avocado/plugins/spawners/process.py
This commit adds a new subcommand `avocado plugins --capabilities` for printing info about spawners capabilities to console.
It uses new Enum value `SpawnCapabilities` for listing all possible spawner capabilities and add new static list `CAPABILITIES` to Spawner class to describe supported capabilities by a given spawner.
Reference: #6107
> Spawner capabilities

- .github/workflows/ci.yml
- .github/workflows/release.yml
This is an CI fix for failures like [this](https://github.com/avocado-framework/avocado/actions/runs/14863146289/job/41733051223?pr=6156).
In setuptools version 80 was removed support for the easy_install command including the sandbox module. Because of this avocado's command `setup.py develop` stopped working. This change fixes our CI to avoid installing setuptools version 80 and higher, but if future we will need to remove the setup.py solution completely.
Reference: https://setuptools.pypa.io/en/stable/history.html#v80-0-0
> Set setuptools version to < 80

- examples/testplans/release/release.json
This is an update for release plan, based on our latest release findings to make our release plan better.
> Release Plan

- .github/workflows/autils_migration_announcement.yml
This workflow should notify contributors on their PRs when they are changing an already migrated utility. This should help us to avoid conflicts between avocado.utils and aautils. The announcement looks like this:
```
You are changing one of the avocado utils which has already been
migrated to AAutils project https://github.com/avocado-framework/aautils
and this utility will be removed after the LTS release. Please make sure
that all your proposed changes are already in AAutils and this PR is
only backport.
For more information about AAutlis migration see
https://avocado-framework.readthedocs.io/en/latest/blueprints/BP005.html
For a list of migrated utilities see
https://avocado-framework.github.io/aautils.html
```
> Github workflow for announcement of AAutils migration

- avocado/utils/data_structures.py
- selftests/unit/utils/data_structures.py
**Test code:**
```
from avocado.utils.data_structures import DataSize
test_data = "1.5G"
ds = DataSize(test_data)
print(f"{test_data} => {ds.b} bytes")
```
**Error before modification:**
```
File "/usr/local/lib/python3.10/site-packages/avocado/utils/data_structures.py", line 334, in __init__
self._value = int(norm_size[:-1])
ValueError: invalid literal for int() with base 10: '1.5 '
During handling of the above exception, another exception occurred:
File "/home/test1.py", line 5, in <module>
ds = DataSize(test_data)
File "/usr/local/lib/python3.10/site-packages/avocado/utils/data_structures.py", line 343, in __init__
raise InvalidDataSize(
avocado.utils.data_structures.InvalidDataSize: String not in size + unit format …
```
> Add support for decimal values and flexible formatting in DataSize
